== Chapter VII.

[.chapter-synopsis]
* Removal to New York
* Religious Visit, in Company with John Hall, to Baltimore, Virginia, North Carolina, and Parts of Pennsylvania

On leaving Philadelphia, Stephen Grellet did not at once settle down at New York; but,
his beloved friend Jarvis Johnson, from Ireland,
being then travelling in the service of the Gospel in America,
he joined him in a religious visit to Friends on Long Island,
and in Purchase Quarterly Meeting, within the compass of New York Yearly Meeting.

After the conclusion of this engagement, he came to New York,
just in time to attend the Yearly Meeting held there in 1799.
It was scarcely a month since he had taken leave of his friends of Philadelphia,
and on being now introduced to the members of another Yearly Meeting,
amongst whom he was about to fix his abode, he remarks in his journal:

[.embedded-content-document]
--

My being at the Yearly Meeting, on my first coming to this place,
has given me an opportunity of becoming acquainted with many valuable Friends.
The generality of the sittings were solemn seasons, especially the conclusion,
when the owning and life-giving presence of the gracious Master covered us.
O my soul, humble thyself in the dust, for the Lord thy God has blessed thee!
Truly he is worthy to be continually served, honoured, worshipped, and obeyed,
with my dear Saviour, his beloved Son,
through whom alone I have attained peace and assurance,
and through whom my sins have been blotted out--my Lord and my God!

--

After having taken up his residence at New York, he was engaged, with his brother Joseph,
in mercantile concerns in that city.
But he had been "`bought with a price,`" and he deeply felt that he was "`not his own.`"
The "`love of Christ constraining him,`" he could not "`live unto himself,
but unto Him who died for us, and rose again.`"

[.embedded-content-document]
--

"`I was not long able,`" he writes in his Autobiography,
"`to devote much attention to business.
My mind became much enlarged in Gospel love for the inhabitants of this land;
but it distressed me that I could not feel any distinct prospect
of the parts where the Lord would have me to go in his service.
I greatly wondered why an exercise of that nature should come so heavily upon me.
I was brought to such a state that, to obtain peace,
and the lifting up of the Lord`'s countenance upon me,
I could have given up to go to the ends of the earth.

"`Some time after this, I heard that my dear friend, John Hall, was coming from England,
on a religious visit to the United States,
and the impression was made strongly upon my mind,
that I must stand prepared to join and accompany him in that service.
I cried earnestly unto the Lord that,
if it was indeed his will that I should engage in such an extensive work,
he would condescend to give me some strong evidence of it, and that, as a proof of it,
he would give to this dear friend to see it himself, with clearness.
He arrived at New York early in the Tenth month.
I visited him soon afterwards, when he took me aside and told me, in a solemn manner,
that I was the identical person that he had seen, whilst at sea,
prepared of the Lord to be his companion in the service of the Gospel here.
He further feelingly said, '`I leave the matter entirely to the Lord,
and to thee.`' I felt very cautious not to tell him how it had been with me,
though I marvelled at the Lord`'s condescension in
giving me such an evidence of his will.
After weighing carefully the subject, and seeking for the Lord`'s direction,
I concluded that,
to have a better opportunity '`to try the fleece,`'
I would accompany him as far as Philadelphia;
when, finding it was a service required of me, I came back to New York,
and opened my concern to the Monthly Meeting,
which gave me a certificate of unity and sympathy,
under this my extensive prospect of religious service.

"`Leaving my small temporal concerns under the care of my dear brother and partner,
and resigning myself to my dear Master`'s putting forth and blessed protection,
and to the guidance of His Spirit, I went back to Philadelphia,
to join my beloved friend John Hall.
Many of my valuable friends in that city entered feelingly into sympathy with me, and,
as fathers and mothers, ministered consolation and encouragement to me.
It is right that I should record the names of some of these, who have so often,
as the Lord`'s instruments, ministered to me in my low estate, viz.: Samuel Emlen,
Samuel Smith, John Parish, William Savery, Thomas Scattergood, Henry Drinker,
Rebecca Jones, etc.
All these belonged to the North Meeting, of which I had been a member;
and many others might be named, of other meetings,
who also had been as nursing parents to me.
Never can I forget the Christian tenderness wherewith the Lord enabled
them to enter into a sense of the deep exercises which attended me.

"`We proceeded through Wilmington, Nottingham, Deer Creek, etc.,
taking the meetings thereabouts, on the way to Baltimore.
Here our minds were brought under such Gospel bonds,
that we had to yield to the prospect of religious duty to visit Friends in their families.
The engagement felt very important to me.
I would have pleaded excuses, but I saw that,
if I expected to have my dear Master`'s approbation and protection,
in the service to which He had called me,
I must follow in all things his Divine guidance.

"`Then, taking meetings through that part of Maryland, among Friends and others,
we came to Alexandria.
The sight of the poor slaves brought heavily to my remembrance what I had seen
in Demerara--a galling yoke that I had not expected to behold in this land,
to the degree I then observed it.
Some of the slaves had heavy chains upon them, while they were at work;
others had at the end of these a weight of twenty-eight or fifty-six pounds.
They generally were wretchedly clad and fed.^
footnote:[Passing through these parts several times afterwards,
Stephen Grellet "`had the comfort of seeing much improvement
in the treatment of the greater part of this afflicted,
and, through oppression, degraded portion of the human race.`"]

"`At Alexandria various exercises came upon me.
My beloved companion was sick,
and my spirit was greatly oppressed under a sense of a spirit of infidelity,
prevailing among some that stood in the foremost rank in that meeting;
and at the several meetings I attended there,
my public services were to give them an example of silence.

"`After leaving that place, and having meetings through that part of Virginia,
we arrived at Richmond, in the First month, 1800.
A large public meeting gave some relief to our exercised minds; we then went to Curies,
Wayne-Oak, etc.,
some of which meetings we attended several times before we could obtain relief.
My spirit was kept under continual exercises, and, though my blessed Master was pleased,
day after day, to renew my strength, by the lifting up of the light of His countenance,
qualifying to perform the services He had for me,
yet often my only relief was privately to pour out my soul, with floods of tears,
before the Lord.

"`On the 15th of First month we crossed the James`' River, and came to Gravelly Run.
We attended all the meetings in that section of the country,
till we came into the lower parts of Carolina.
My beloved companion was frequently enlarged, in Gospel authority; yet he,
as well as myself, was often silent.
We felt a watchful care that, both by precept, when thereto called by our Divine Master,
and by example,
we might draw the attention of the people from the
poor instruments to Christ Jesus the Lord,
the ever near and sure teacher, helper, and comforter of his people.
And when we were called upon to minister to the people,
our chief concern was to draw them to the Saviour of sinners, the Way, the Truth,
and the Life, without whom none can come to the Father.
We had in those parts some large and precious meetings among the slaves,
the hearts of some of whom were much tendered.

"`The 28th of First month, we came into the pine woods of North Carolina.
There the Lord was pleased in an humbling, memorable manner, to visit me again,
and to comfort me.
I had gone into the woods, which are there, mostly, of very lofty and large pines, and,
my mind being inwardly retired before the Lord,
he was pleased so to reveal his love to me, through his blessed Son, my Saviour,
that my many fears and doubts were at that time removed, my soul`'s wounds were healed,
my mourning was turned into joy.
He clothed me with the garment of praise, instead of the spirit of heaviness,
and he strengthened me to offer up myself again freely
to him and to his service for my whole life.
`'surely,`' said I, '`every labour, every trial,
yea the bitterness and the gall that I have so often partaken of, are but a trifle,
compared to the joys felt in the Lord`'s presence,
and the grateful sense of his salvation.
Walk, O my soul, in that path which thy blessed Master has trodden before thee,
and has consecrated for thee.
Be also willing to die to thyself, that thou mayest live through faith in Him.`'

"`It took us till the 10th of Second month to visit
the meetings of Friends in that Quarter.
They were, as many had been in Virginia, attended by slaveholders,
with whom the Lord enabled us, at times, to expostulate on behalf of the poor oppressed;
and He so far gave place in their minds to our testimony that,
though we delivered plain truths,
and showed them how contrary the fruits of oppression
are to pure and undefiled religion before God,
yet in some places here, as had been the case also in Virginia,
when feeling our minds engaged to have meetings with their slaves,
and requesting their presence if they inclined, they said,
'`they were fully persuaded we should not say any thing to their slaves in their absence,
that we would not say in their presence.`' Very satisfactory were
some of the meetings we had with these poor afflicted people.
The tenderness and the sensibility of some of their minds have often convinced me that,
of a truth, God is no respecter of persons; Christ has died for all, he is near unto all,
and his blessed Spirit would lead into all truth those that obey him.

"`At Rich Square we put up at our beloved friend Richard Jordan`'s,
a valuable minister of the gospel.
I had known him when, a few years before,
he was on a religious visit to the northern and eastern States,
and my spirit had been united to him in Christian fellowship.
We found him on the eve of leaving home, under the prospect of a visit,
in the service of the Gospel of Christ, through England,
and parts of the continent of Europe.
We remained in that neighbourhood about a week, having several meetings among the people.
Our dear friend, Richard Jordan, accompanied us,
being on his way towards Philadelphia to embark for England;
we had a solemn religious opportunity before we parted.
On our way to Contentnea, we had, amidst imminent dangers, a remarkable preservation.
At about eight o`'clock, on a very dark night, we came near to a creek.
Our guide, though well acquainted with the place and the ford, for greater safety,
rode to a cabin, not far distant, to inquire if the creek was fordable.
He was told that there had been no rain for many days that could raise the creek;
(there had been heavy rains up the country, with which, it appears,
the person inquired of was not acquainted).
Putting a white handkerchief round his hat, that we might the better distinguish him,
our guide rode before us, desiring us to keep close behind him,
as the descent into the creek was steep and difficult.
As soon as we were in, we found the water so deep, that our horses began to swim,
and the current was so strong, as to turn the body of our carriage,
(which was a Jersey wagon), down the stream.
The carriage was soon filled with water.
Our horses, swimming, kept up close behind our guide.
To our surprise, when we came near the other side, we found we had no hind wheels.
We were obliged to leave the carriage and the fore wheels in the water,
at a short distance from the shore.
Fastening our wet baggage with ropes on the horses, we proceeded about a mile,
to our friend Jeremiah Home`'s, who had kindly come to our assistance,
and ministered to us in our wet and cold condition.
The next morning early, on going to the creek to see after our carriage,
we found that the waters had fallen about sixteen inches during the night,
and we discovered the upper part of our hind wheels about six inches above the water,
very near the place where we had first entered the creek,
so that we must have floated soon after we got in.
Had we been left to the current of the river, we could not have escaped being drowned,
for the banks, on both sides of the creek, are for some distance steep and bushy.
Through the help of a canoe, we recovered the wheels.

"`We now proceeded through the meetings in that Quarter.
We felt much for Friends, many of them being settled on very poor,
sandy and unhealthy soil; their countenances bespoke the unhealthiness of the country.
Some of their number, particularly from Core Sound, had gone over to Ohio,
then a new and unsettled country,
to see whether it would not do for them to remove there.
Another great inducement to Friends to wish for a change of their residence,
was the great sufferings of the poor slaves around them.

"`The 3rd of Third month we came into the upper parts of Carolina, to the Spring Meeting,
to our valuable friend Zachariah Dicks`'s, who, years before,
had paid a religious visit to England.
He continued green in old age.
On our way there we met with many difficulties, bad roads and high waters;
several times we had to cross the waters in canoes, having two lashed together,
two side wheels of our carriage being in one, and the opposite ones in the other,
the horses swimming beside them.
The country being thinly settled, and meetings far apart,
we found it difficult sometimes to obtain any kind of accommodation;
but the Lord supported us under all, to the praise of his great name.

"`We had a refreshing meeting at Spring; it was a large one.
The following interesting circumstance was there related to me by John Carter,
a near relative of the Friend who had been an instrument
in raising up that meeting from a decayed state,
and on that account had called it Spring meeting.
A number of years ago, it had become much reduced,
through the unfaithfulness of some of its members, and the death of others.
A young man of the name of Carter became religiously inclined,
so as to feel disposed to open the meetinghouse, and to repair there, though alone,
on meeting days.
He had continued to do so for some time, when, one day, a great exercise came upon him,
to stand up and audibly to proclaim what he then felt to be on his mind,
of the love of God, through Jesus Christ, towards poor sinful man.
It was a great trial of his faith, for nothing but empty benches were before him.
He yielded, however, to the apprehended duty, when,
shortly after having again taken his seat, several young men came into the house,
in a serious manner, and sat down in silence by him,
some of them evincing brokenness of heart.
After the meeting closed, he found that these young men, his former associates,
wondering what could induce him thus to come alone to that house,
had come softly to look through the cracks of the door at what he was doing,
when they were so reached by what he loudly declared, that they came in.
Some of them continued to meet with him, and became valuable Friends.
The meeting increased by degrees to the size it now is.
Thus is the Lord pleased to make the faithfulness of one a blessing to many.

"`After attending the Quarterly Meeting of Deep River and several meetings in that Quarter,
we came to Rocky River, to David Wertell`'s, an aged and faithful Friend.
It was late and cold when we arrived at his house.
Informing him of our wish to have a meeting the following day,
he said he would take all necessary care about it; but,
as he did not leave us till we retired to bed,
I concluded we should have a very small meeting.
I saw no more of the dear friend till next day as
we were passing through the thick woods,
going to meeting.
Wondering at the crowd of people we met, in what appeared a wilderness,
and meeting with David near the meetinghouse,
I asked him why we had not seen him the whole morning?
He said he had been riding all night and morning, giving notice of the meeting;
he then very cheerfully added, '`I feel now much refreshed,
and have just been getting my breakfast under this tree.`'
He had ridden over a considerable circuit that night,
and we found a large concourse of people in the house,
with whom we had a solemn good meeting.

"`We continued diligently engaged in visiting the
meetings through the Quarterly Meeting of New Garden,
the Lord, from day to day, helping us to do or to suffer of his good pleasure.
We met here a body of the people, called '`Nicholites,`' from one Nicholas,
whom I once saw in Philadelphia, after he and several of his adherents,
who are mostly settled on the Western shores of Maryland,
had become members of our Society.
They are in some respects similar to Friends.
We had an interesting opportunity with those near New Garden.
There is, I doubt not, great sincerity in many of them.

"`After travelling about one hundred and fifty miles through a wilderness country,
with hardly any other provisions than what we carried with us, for ourselves and horses,
we came into South Carolina, to a meeting called Putgets Creek.
The fatigue of the road, and the want of accommodation had been such,
that dear John Hall was quite sick on our arrival there,
but after a few days`' rest he was again able to join me.
In that Quarterly Meeting, called Bush River, which extends into Georgia,
Friends were pretty numerous.
They had some valuable members among them,
with whom my spirit was comforted and refreshed, but in general the Divine life was low.
My conflicts were great because of the galling yoke of the poor slaves,
who are under great oppression in these States.
We attended the Quarterly Meeting held at Bush River.

"`Providing ourselves with bread for some days, we set off for Tennessee.
We met with many difficulties on that journey through a mountainous, unsettled country,
having deep waters to ford, there being neither bridges nor ferries over them.
Ours was probably the first carriage that had travelled that road.
It was well we had taken a little bread and corn with us, which we had to use sparingly,
so that a couple of small dry cakes and water served me the whole day,
and the horses eat young twigs and leaves; for very little grass was to be found.
When encamping during the night, which we did several times,
we kept up a good fire to protect us from the panthers, bears, and wolves.
The latter were numerous.
Sometimes it seemed as if a hundred of them were howling at once round about us.
We feared at times lest our horses, frightened with their noise, should get away from us,
but it seemed as if the more danger they apprehended, the nearer they kept to us.
I was, however, more in fear of venomous snakes, than of wolves.
Rattlesnakes and copper-heads were numerous there, as in most of those new countries.
They would even come into the cabins, through the openings between the logs,
or in the floors.
But through adorable mercy, I have never been hurt by any of them,
though I have frequently been in close contact with them.

"`We travelled slowly on account of the difficulties of the roads;
sometimes they were so steep, that with our empty carriage,
the horses could get only a few steps forward at once.
Frequently, indeed,
we had to open a road by cutting down the trees and removing them out of the way.
But, notwithstanding the fatigue, we were favoured with good health,
and enjoyed the beauty and grandeur of the scenery we often had before us,
whilst passing through some of those dense forests, covered with those old lofty trees,
which appeared like '`the cedars of Lebanon that the Lord
has planted.`' We once encamped under the painted rock,
by the French Broad river.
It may be called one of the wonders of nature.
There the Indians used to hold their councils.

"`We visited the various meetings composing the Quarterly Meeting in that State,
where we were often comforted with some valuable, well-concerned Friends,
who are engaged both by example and precept,
to manifest their interest for the promotion of the kingdom of the dear Redeemer,
and also to train up their offspring in a religious life and conversation;
yet in these parts, as in many others, I found a great deficiency in this respect,
which introduced me often into deep exercise and secret mourning.
Through almost every part of the Carolinas and Tennessee, Friends,
as well as the people at large, undergo many privations and hardships.
The education of the young people is much neglected, there being few or no schools,
so that not many children, or even parents, can read.
Yet among such I found some lively, sound Ministers of the Gospel.
The Lord had instructed them by his Spirit,
and blessed the little they had known of Gospel truths.
The state of religion among the inhabitants at large was very low.
A loose, libertine spirit appeared, in several places,
like a thick cloud to cover the minds of many of the people;
yet I found some serious persons among them, with whom we had refreshing meetings.
We visited also some of the Indians with some satisfaction.

"`Through rough and mountainous roads, we travelled towards the upper parts of Virginia,
in the neighbourhood of the Sugar Loaf Mountains.
The meetings composing that Quarterly Meeting are, like those in Tennessee,
a branch of Carolina Yearly Meeting.

"`On the 29th we came within the limits of South River Quarterly Meeting,
a branch of Virginia Yearly Meeting.
Very close exercises came upon me,
and faithfulness in delivering the whole counsel of God,
was the only way to obtain peace of mind.
It has been my allotment, on this journey,
to take private opportunities with individuals to
unfold to them my soul`'s concern on their account.
The service has been very humiliating, but the love of God constraining,
and the mind being kept low before Him,
way has generally been made with those I have thus visited.
The slaves in that part of the country are treated
with more cruelty than I have seen elsewhere.
I felt deeply for them, whilst beholding their ragged and emaciated condition.
I saw the anguish of some of them, whilst passing through the market place of Lynchburg,
as they were publicly selling them, like so many cattle.
O the distress they manifested when separated from their nearest relations!
At a public meeting we had in that place,
the Lord enabled me to plead the cause of our poor oppressed fellow-men.

"`We proceeded thence over the Blue Ridge Mountains to Hopewell,
and attended their meeting, which was a large one.
My mind, during the course of the preceding week, had been brought very low,
but there the Lord, who is the comforter of the afflicted,
was pleased to reveal himself in his ancient power,
and to give access to his sacred footstool publicly also to offer unto him,
with the voice of thanksgiving, '`glory, honour, and praise.`'

"`16th. This day was their Quarterly Meeting, a branch of Baltimore Yearly Meeting.
It was a season of Divine favour,
when some of His afflicted ones were enabled to ascribe
all the glory to Him who is the strength of the poor,
the strength of the needy in their distress.

"`Our minds feeling drawn to visit the meetings in the neighbourhood of Redstone,
on the other side of the Alleghany Mountains, brought an exercise over us.
Our health was but feeble,
after hard travelling and many exposures during the preceding months;
the weather also was very warm;
but apprehending this was a service the Lord required of us,
we cheerfully yielded to his putting forth,
confiding in his blessed guidance and almighty protection.

"`On the 17th we proceeded to Black Creek meeting, where the Lord`'s power,
who is above all, came over us in a remarkable manner.
It was a solemn, awakening time to many present.
The offer of salvation, through Jesus Christ, was made to them.
My soul bowed in humble reverence; for the stream of Divine consolation flowed within me.
We then proceeded to Bear Garden, where I suffered deeply,
because a spirit of unbelief had darkened some of their minds.

"`24th. Came to Hill`'s Creek, just over the mountains.
It was a fatiguing journey, attended with various perils, and want of food;
but the distress of mind under which I was, far outweighed outward difficulties.
May all these baptisms be sanctified to me, both to the purification of my soul,
and to my increased qualification to comfort those that are in any trouble,
with those consolations wherewith the Lord is pleased to comfort me,
under many tribulations.

"`We continued till the 7th month very diligently engaged
in having meetings among Friends and others on these mountains.
Very close testimonies were given me to bear among them, in several places;
but Divine help was afforded to do the work assigned.
At the close of our labours among them, glory and praise unto the Lord,
for his adorable help and his Divine mercy vouchsafed, were offered.

"`We returned into Virginia, near Winchester,
and continued within the verge of that Quarterly Meeting till the 8mo.,
attending some meetings several times, before we could leave them with peace of mind.
One of the exercises that I was brought under,
was on account of a spirit of infidelity creeping out among some who stood in high stations,
and with whom we took a private opportunity, labouring, in tender love,
to show them the inconsistency of their pretensions to Christianity.

"`We afterward proceeded to South Fork, over the Blue Ridge,
where we had a memorable meeting.
Then we went through several Quarterly Meetings,
attending all the meetings composing them, and crossing the Susquehannah,
we came back into Pennsylvania.

"`The 8th of 9th month we came to Chichester.
There I was permitted by my blessed Master,
who knoweth what is good and necessary for my purification,
to be introduced into very deep baptisms,--O the depth of the anguish that came upon me!
No past experience of the Lord`'s redeeming love
and power was able to administer to my distress.
I was plunged into a state of doubting,
and even of unbelief in the mercy of God through Jesus Christ; a dark spirit,
on which account I have at times so bitterly suffered
for those who have been carried away by it.
I continued in such a state for some days, that I could not travel.
It would, indeed, have been presumption to go forth as an ambassador for Christ,
whilst I was tempted to doubt his eternal Divinity and God-head,
his meritorious sacrifice for the sins of the world,
even to let go the hold of my hope in him, through whom is the atonement,
through faith in whom alone remission of sins is to be obtained.
O the workings and subtlety of this spirit of unbelief!
Forever and ever blessed be the Lord, who, after days and nights of fiery conflict,
was pleased to lift up again the light of his countenance upon me,
and at the brightness thereof, darkness fled apace.
O never have I beheld the excellency of the Gospel of Christ, with more ravishing beauty,
than I did then.
The same light which gave me to see the transforming power of Satan and his temptations,
showed me also the Lord of Glory, even Him who has been delivered for our offences,
and raised again for our justification; who is the Way, the Truth, and the Life;
without whom none can come to the Father.

"`Whilst wondering why such an exercise should come upon me,
I saw I must be prepared to feel for, and enter into,
the states of those that are thus variously tempted,
through the subtleties and stratagems of Satan.
It was but a few days after,
that the account reached us of the falling away of Hannah Barnard, from New York State,
while on a religious visit to England.
She had become a prey to this spirit of infidelity,
so that instead of advocating the cause of the blessed Redeemer,
the Lord and Saviour Jesus Christ,
consistently with the work of a Minister of his glorious Gospel,
she was disseminating infidel doctrines,
even denying the Lord that bought us with his own blood,
and calling in question the validity of the Holy Scriptures.
Many in Ireland, captivated by the subtle workings of this dark, deceitful spirit,
were following her pernicious ways,
by reason of whom the way of Truth was evil spoken of.`"

--

From Chichester they proceeded with the work before them and were
diligently engaged in visiting many meetings in those parts,
till the time of holding Baltimore Yearly Meeting drew them to that city.
Here Stephen Grellet remarks:

[.embedded-content-document]
--

On the 11th of Eleventh month began the Yearly Meeting of Baltimore,
to which we went in lowness of mind,
having carefully waited to know that this service was required of us;
for it was at the peril of our lives, the yellow fever prevailing in that city;
about fifteen hundred persons had already died of it.
But, having apprehended that the Lord had a service for us there,
we were favoured with resignation to his will,
confiding in his all-sufficient power to enable us
to walk unhurt by "`the arrow that flieth by day,
or the pestilence that walketh in darkness.`"

Many more Friends from the various Quarterly Meetings attended
than could have been expected at such an awful crisis.
They felt the weight of such a service devolving on the comparatively few then assembled,
and considered the propriety of adjourning the meeting to some future time.
But, as they endeavoured to feel after right direction, keeping low before the Lord,
they were led, day by day, to proceed with the business, to the close of it.
The several sittings were attended by the Lord`'s baptizing power.
He graciously owned them by his Divine presence.
The meeting concluded on the 16th, under great solemnity.
Our spirits were bowed before the Lord, in much brokenness,
for the favour he had vouchsafed us, day by day, keeping us above fear,
under the sense that our lives are in his all-powerful hand.
We cannot but notice, with humble admiration and gratitude,
that from the beginning of the Yearly Meeting to this day,
the number of deaths has considerably decreased.
Before the opening of the meeting, they were from twenty to thirty per day;
during this week, they have only been from five to six,
and today there is only one death.
"`Bless the Lord, O my soul, and all that is within me, bless his holy name.`"

--

Under this "`grateful sense of the Lord`'s goodness,`" they left Baltimore,
and had many meetings on their way to Philadelphia.

On returning from this his first extensive journey in the service of the Gospel,
it was a matter of no common interest to Stephen Grellet
again to mingle with "`many fathers and mothers,
brothers and sisters, among whom, in years past,
he had enjoyed so much sweet conversation and Christian fellowship.`"
The friends of his earlier youth,
who had tenderly sympathized with him as he went forth "`weeping,
bearing precious seed,`" now greeted him as a brother beloved in the Lord,
coming back to the city of his former residence, "`bringing his sheaves with him.`"
It was here that he first joined his beloved companion in the work before them, and:

[.embedded-content-document]
--

"`Here,`" he remarks, "`feeling my mind, for the present,
released from further religious service,
I took an affectionate leave of my dear friend John Hall, and returned to New York,
after an absence of thirteen months, during which I travelled about five thousand miles.
We were very nearly united in our religious exercises and services.
Our travelling together as fellow servants of the Prince of Peace,
attracted the attention of the people in many places,
bringing many of them to our meetings,
to see the Englishman and the Frenchman united in promoting
the cause of righteousness and truth on the earth,
whilst their respective nations were waging such destructive wars against each other.
We heard some of them feelingly comment on the peaceable spirit of the Gospel.`"

--
