== Chapter VIII.

Religious Visit to the Eastern and Northern States,
in Company with John Hall--His Brother Joseph`'s Return to France--Visit to Jersey

Whilst "`fervent in spirit,
serving the Lord,`" Stephen Grellet was "`not slothful in business;`" but,
returned from a long and arduous engagement in visiting the Churches,
he now endeavoured to apply himself with diligence to his temporal affairs.
Keeping his eye single, in these concerns also, to his Divine Master,
he was preserved from undue carefulness, and corroding anxiety.
The believing remembrance of the gracious promise,
so forcibly applied to his own heart in years past,
that "`if he sought first the kingdom of God and His righteousness,
all things needful should be added,`" was often a comfort and encouragement to him,
in his efforts to provide things honest in the sight of all men.

"`I was not permitted, however,`" he writes, "`to remain long thus engaged;
for the love of the Gospel strongly drew me towards the Eastern,
and parts of the Northern States.
Feeling that it was a service which He,
to whom I had made the offering of myself and my all, required of me,
I spread the concern before my friends at their Monthly and Quarterly Meetings,
and obtained their respective certificates of unity.`"

His beloved friend and former companion, John Hall, being led in the same direction,
they again united as fellow-labourers, and, leaving New York together,
in the Fifth month, 1801, proceeded to Long Island.

"`We visited,`" Stephen Grellet continues, "`all the meetings of Friends,
and had several also among the inhabitants.
Our blessed Lord and holy Helper enabled us to labour
among them in the service of his Gospel,
and, in this, to obtain a considerable degree of relief, under our various exercises.
Notwithstanding the high profession made by many under our name, a spirit of degeneracy,
and even of infidelity, had crept in among some of them.`"

From Long Island they returned to New York, to attend the Yearly Meeting in that city,
after which they proceeded to New England Yearly Meeting at Newport.

"`It was held,`" Stephen Grellet remarks, "`under much solemnity,
throughout its various sittings,
and the business was conducted in brotherly love and harmony.
Going thence towards the Island of Nantucket,
we attended all the meetings on the way to New Bedford,
the Lord enabling us to preach among them the glad tidings of the Gospel of his salvation,
and the offer of his free grace to all, through our holy Redeemer,
our Lord and Saviour Jesus Christ.
After having seven meetings among Friends, attending their Quarterly Meeting,
having some public meetings on the island,
and visiting Friends in many of their families,
my beloved companion apprehended himself clear of the place, and,
as a packet was to sail next morning for New Bedford,
he proposed that we should embrace that opportunity.
I felt weights and burdens yet upon me, on account of the inhabitants of that island,
but, being under depression of mind,
I was unwilling to let my kind and beloved companion know how it was with me,
hoping also that I might be excused from further religious service there.
We accordingly went on board the packet next morning early, with a good wind.
Great distress came upon me, which increased as we proceeded on our way;
for I felt that the Lord had some more service for me on the island.
I cried earnestly unto Him whose power can control the wind and the sea,
believing it was as easy to Him to open a way for my return to the island,
as to deliver Jonah out of the whale`'s belly, to go to Nineveh, that great city,
and preach there the word He commanded him.
Thus, confiding in the Lord, my mind was brought into solemn waiting upon him,
to see what he would do for his name`'s sake.
The wind changed, by degrees, then blew vehemently, and became so violent,
that the captain said that we could go no further,
and that our only safety appeared to be to return to port.
During all this, amidst the tossing of the vessel on the boisterous waves,
dismay covered many of the passengers.
But my mind, in much serenity prostrated before the Lord,
was marvelling at this opportunity now given me,
to do whatever he further required of me.
After having been out some hours, with a heart melting with gratitude I landed again.
Our kind friends received us on the wharf, with warm affection,
having been much concerned for our safety, on account of the storm.
The next day, being First-day, I had two meetings with Friends,
at their two meeting houses,
and the day following I had a very large one with the inhabitants.
It was a memorable, solemn season.
During that day, and the following,
I paid a religious visit to several families towards
whom I felt I owed this further debt of love.
On the next day, the wind being fair, we had a short voyage back to New Bedford.

"`After attending the meetings in that neighbourhood, we proceeded through Longplain,
Sandwich, Falmouth, etc., to Lynn.
Through these parts I was frequently introduced into much feeling for the people,
whose minds were brought into perplexity and distress,
because of the doctrine of unconditional election and reprobation,
then zealously preached amongst them.
Some of them were driven to a state of despair,
under the conclusion that they were of the reprobate,
and consistently with that doctrine,
could entertain no hope of redemption through Christ, the Saviour of sinners.
Some had even yielded to the temptation to put an end to their existence.
I was often led to unfold to them the universality of the grace and love of God,
in Christ Jesus, who has died for all, has come to seek and to save that which was lost,
who would that all, coming to the knowledge of the Truth, should be saved.
It proved a time of Divine visitation to some of them; their hearts were made soft,
and prepared both to hear and to receive the glad
tidings of salvation through Jesus Christ.
To one of these meetings came a woman under much distress,
on account of the above doctrines.
She had concluded to drown herself, but, hearing of the meeting,
she felt inclined to come to it.
It proved a good season to her.
The Lord, who saw Hagar in her distress,
condescended also to minister to that afflicted female.
Salvation by Christ was preached, that evening.
After meeting she came to see me, when, with floods of tears,
her heart gave vent to her gratitude, in that the Lord had detected the adversary,
and given her to see and to believe that for her also, and for every sinner,
Christ had died, and ever liveth--our advocate and intercessor with the Father.

"`From Lynn we proceeded to Salem, Newbury, Amesbury, Seabrook, etc., towards Dover,
having meetings in all these places and their several neighbourhoods.
At Amesbury we were refreshed and instructed in the company
of that ancient and valuable servant of the Lord,
Comfort Collins, then upwards of ninety years of age, but green in the Divine life,
and a bright example of humility.
She appeared to have her indwelling in Christ.
Her mental faculties were bright, and she had lately travelled as a Gospel Minister.
About forty years ago, Comfort Collins, then a Hoag,
having surrendered herself and her all to the Divine will,
under a sense of duty to go to England on religious service,
with the unity of her friends, embarked for Europe, accompanied by Sarah Barney.
After they had been out at sea about a week, as they were sitting together in the cabin,
in solemn silence before the Lord, Comfort said to Sarah,
'`The Lord has accepted my free-will offering to his Divine will, to go to Europe,
and now he releases me from this service; and, as a proof of it,
he will bring us back again to the American shores.`' Sarah Barney
told me that the communication was attended with so much solemnity,
that she could not doubt that it was of the Lord.
Without exchanging a word with one another,
they continued a considerable time in silence,
when they heard the captain of the ship speaking with his trumpet to another ship,
stating that he was under the necessity of returning to port,
as his vessel had sprung a leak, which the Friends knew not before.
Thus were these women brought back,
and from that time they felt themselves entirely
released from the service of travelling in Europe.

"`We continued our journey through those eastern parts,
as far as beyond the river Kennebec, the farthest settlement of Friends at that time,
having many precious meetings with them,
and with those of various other Christian denominations.
We met with some trying circumstances among divers
persons that had got into a ranting spirit,
with whom we laboured both publicly and privately, in Gospel love,
that they might be reclaimed from their errors.
We had the consolation to see some brought into a state of tenderness,
becoming sensible of the condition they had fallen into,
through the subtle workings of the adversary.

"`We visited nearly all the particular meetings of that Yearly Meeting,
and had also many meetings among the people at large.
We then went through Connecticut, into the State of New York,
and after visiting the meetings through the several Quarterly Meetings in those parts,
we returned to the city of New York, on the 16th of Twelfth month.

"`Close and peculiar exercises have attended me, on this my late journey;
but my dear Master has been with me,
according to His gracious promise before I left home.
My soul can again sing His praise, on the banks of deliverance.
Praise the Lord, O my soul, and forget not all his benefits.
Thou hast often drunk the cup of sorrow, mingled with wormwood and gall,
and these are still in remembrance,
but thou hast also seen the ways of the Lord in the deeps, and partaken, at seasons,
of that pure, living stream which flows from his Divine presence;
therefore return unto thy rest, for the Lord hath dealt bountifully with thee.
I travelled in that journey about four thousand miles.`"

On his return to his own habitation in the city of New York,
Stephen Grellet applied himself, with his accustomed diligence, to his outward concerns.
During his absence these had very much devolved upon his brother Joseph.
The two brothers had "`kept very much together,
during the various vicissitudes which had attended their checkered path,`" and,
strongly attached by the ties of natural affection,
they felt "`doubly dear to each other in being closely united also in Christian fellowship.`"
It was therefore no small trial to Stephen Grellet when in the next year, 1802,
his brother felt it right to return to their dear parents in France.
The separation was the more painful because he was aware that,
in returning to his native country,
his beloved brother would be much exposed to adverse influences,
that might closely prove his Christian foundation.
He deeply felt the responsibility also,
which was thus thrown upon himself in regard to their mercantile concerns;
"`but,`" he says, "`whilst closely engaged in my business,
I was diligent also in attending our religious meetings.
The Lord was very good to me.
He helped me to get through my daily cares, and, under a sense of his help,
and the consolations of his presence,
my soul had often a sweet song of praise and gratitude to him.`"

Only a few months after his brother had left him,
Stephen Grellet was again called from home, in the service of his Lord,
"`his mind being drawn forth in the love of the Gospel to visit the meetings of Friends,
and the people of other religious denominations in Jersey.`"

"`I made such arrangements,`" he remarks, "`as to leave my affairs with satisfaction;
and, having the approbation of my Monthly Meeting,
I set off for that service in the Eighth month, 1802.
I proceeded direct to Burlington, and attended the Quarterly Meeting there.
My heart was made glad in meeting with many of my dear and valuable friends,
and I sensibly felt the help of their spirits,
whilst silently sitting under their Gospel labours.
O how precious is Gospel unity and Christian fellowship!

"`I proceeded through all the meetings of that State.
Some of them were eminently favoured by Him whose
presence is the crown of the assemblies of his people.
Yet I met with deep baptisms in some places, fervently desiring that,
under every one of these, my soul might be more and more purified.
When these afflictions for Christ`'s sake have come upon me,
I have often been instructed in remembering that the servant is not above his Master,
nor the disciple above his Lord;
how trifling then have appeared my most bitter conflicts,
compared with the sufferings of my holy Redeemer for the sins of the whole world--yea,
for my own sins!
Dwell low, O my soul!
Often contemplate this wonderful and meritorious sacrifice upon the cross!
God clothed with humanity!
In His love and mercy He has bestowed upon thee His holy Spirit, to teach thee,
instruct and lead thee in the way, and to sanctify thee, so as to render thee fit,
in the end, to enter the kingdom of glory.

"`Jersey is that part to which my first religious services were directed,
from the city of Philadelphia, and I continue to feel much for its inhabitants,
some of whom are in a very low state.
May the Lord awaken in them a sense of their sinful condition,
and the need they have of a Saviour.
Having accomplished what I had in prospect,
I was favoured to return to New York in the Eleventh month.
I had with gratitude to acknowledge how bountifully my Divine Helper had dealt with me,
during that journey.
In my weakness and poverty He had sustained me,
given a little ability to perform the service He had for me,
and also cared for my small temporal concerns,
so that they had been as prosperous as if I had stayed at home.
Thus it is good for us to commit our all to Him whose power is over all,
and from whom every blessing flows.`"

Stephen Grellet was now permitted to remain at home for more than a year.
He nevertheless visited some meetings in the neighbouring Quarterly Meetings;
held some in different parts of the city and its environs,
and also paid a visit to the families of Friends in Flushing, on Long Island.
He was diligent in attending all his meetings at home, as they came in course,
and "`as he sought for the Lord`'s direction, in the management of his outward concerns,
and depended on Him alone for a blessing on his exertions,
he felt it to be his duty to make way for his assistants
in business also to attend their places of worship.`"
He was in the practice of closing his store during the hours of meeting,
making the needful arrangements on the previous day.
"`I believe I never lost anything,`" he says, "`by that practice; on the contrary,
I was often made sensible, that it was blessed to my soul, at least.`"

During the latter part of 1803,
the city of New York was again visited with the yellow fever.
The mortality was not very great,
many of the inhabitants having removed into the country, on its first appearance.
But as he was one of those who continued in the city,
he had a fresh opportunity of mingling with the afflicted,
and sympathizing with them under such an awful dispensation.
Feeling a strong desire that those who had retired into
the country to escape from the pestilential disease,
might "`so learn righteousness, whilst the judgments of the Lord were in the land,
as to live increasingly in his fear,`" he believed it to
be his religious duty to appoint several meetings with such,
in the vicinity of the city; and it was cause of great grief to his sensitive mind,
to find that "`many of them,
instead of seriously taking to heart and profiting by the events passing near them,
were spending a great portion of their time in frivolous recreations,
and the pursuit of amusements calculated to lead them still
further away from the paths of righteousness,`" thus,
in his apprehension, "`preparing the way for further chastisements to follow them.`"
