== Chapter X.

[.chapter-synopsis]
* Religious Visit to Friends and Others in Pennsylvania
* Appearance of the Yellow Fever in New York
* Return Home
* Decease of His Mother-in-law
* Illness of his Wife

An interval of six months had scarcely elapsed,
after his last return from the field of Christian labour,
before Stephen Grellet believed it required of him, by his Divine Master,
again to leave his home, on a similar embassy to the churches in Pennsylvania.

In the meantime, he had felt at liberty to attend to his outward affairs,
and his exertions in this respect were blessed.
He had, however,
declined to engage in various extensive and lucrative concerns in business,
which were presented to his notice under very promising aspects,
"`feeling restrained,`" as he says, "`by the limitations of Truth,
from entering into any temporal pursuits,
which were likely to occupy his attention beyond a very limited period.`"
He felt that,
if it be needful for those who are engaged in an outward warfare
"`not to entangle themselves with the affairs of this life,
that they may please him who hath chosen them to be soldiers,`" it must
be infinitely more so for those who are enlisted under the banner of Christ,
and have become soldiers in the Lamb`'s army, to be the Lord`'s freemen,
disentangled from the love and the spirit of the world,
and given up to the willing service of their God and Saviour.
"`O Lord!`" he exclaims, in the prospect before him,
"`the service of a minister of Jesus Christ--how solemn!
Their sufficiency is in thee alone!
Thou alone, art their help, and their strength!`"

With views like these,
"`his mind had been brought under much exercise for Friends and others,
chiefly in Pennsylvania,`" and,
apprehending that "`the love of Christ constrained him again to
resign his all to the Divine requiring,`" he obtained the usual
certificates of unity from his Monthly and Quarterly Meetings,
"`arranged his temporal concerns so as to leave nothing behind that would prevent
his thoughts being wholly directed to the work his blessed Master sent him to
do,`" and proceeded on the visit described in the following memoranda.

[.embedded-content-document]
--

I left home the 17th of Sixth month, 1805.
My beloved wife and her father went with me for a few days.
I had that evening a meeting in Jersey, at Hackensack, among Dutch people.
Our gracious Master owned it by his presence,
and he qualified his poor servant for that day`'s service.
I visited a poor black man in the jail, who was under sentence of death.
He appeared to be in a very insensible state of mind, as to his awful condition,
so near the brink of eternity. I mourned bitterly over him,
and the responsibility of those who,
by their neglect of the religious education of the poor negroes under their care,
and by cruel treatment also,
have largely contributed in sinking many of them
so low in their state of alienation from God.

The 19th, we were at Rahway and Plainfield.
At the last place was their Monthly Meeting, when my valued friend, Henry Shotwell,
an Elder in good esteem,
obtained a minute to bear me company during the visit I had in prospect.
We came back to Rahway, and here my dear wife and her father left me,
to return to New York, after having committed one another to the Lord,
under whatever trial he might see best to permit.
A sense that a cup of this sort might be mixed for us,
rendered this parting solemn and very affecting.

From Rahway we came into Pennsylvania.
We attended the Falls meeting, and the other meetings in that Quarter.
Heaviness of heart was my clothing from meeting to meeting; the love of the world,
like a canker, destroys every greenness.
I met, however, with some valuable Friends in that Quarter,
to whom the Truth is precious, and who, I hope,
will keep their places in it unto the end of the
few remaining days of their earthly race.
I proceeded afterwards into Abington Quarter, the meetings of which I generally attended.
In many of them silence was the only service I had, as a public testimony among them.

I went to Philadelphia and attended five meetings,
in all of which my mouth was closely sealed.
I felt like Jeremiah in the low dungeon.
My supplication was, "`O Lord, help, or else I perish.`"
My way opening to depart from that city, I proceeded to Radnor Monthly Meeting,
wherein I continued for a considerable time under much mental suffering,
but towards the close, the Lord enabled me to minister to their condition,
to the relief of my mind.

I have been very sensible, during these weeks past,
that the low state in which I find our Society, meeting after meeting,
is owing to their having departed from that retiredness of spirit, and lowliness of mind,
which characterised our former Friends, and the primitive Christians.
They have retained indeed, to a certain degree, the outward profession,
but too few continue in the life.
What a neglect is mournfully prevailing in many families,
to train them up in a religious life and conversation,
consistently with our Christian profession;
nevertheless the Lord has a precious remnant preserved in almost every place,
to whom I feel nearly united.
Through many baptisms, He has brought them and preserved them,
and I have faith to believe that, though this people may be chastened, to purify them,
they will not be forsaken; and from among the children, yea, from generations yet unborn,
will arise such as will magnify the name of the Lord their Redeemer.

After that I entered into Concord Quarterly Meeting.
The Lord has been pleased, at nearly every meeting,
to open my way to unfold my soul`'s exercise to the people.
At some of these meetings I have been enlarged in the Gospel of Christ,
in a manner very humbling and memorable to myself,
and to the contriting of the hearts of many present.
The Lord has also been near in private religious opportunities.
Keeping a single eye to the putting forth of the Divine Spirit,
the way frequently opens for private service; in this the application,
"`thou art the man,`" often comes home much more forcibly than in a public meeting,
whether the message be one of reproof, instruction, or comfort and consolation.

25th of Seventh month.
At Little Creek meeting in the forenoon; and one with the inmates of the poor-house,
and the inhabitants of the neighbourhood in the afternoon,
which was held out of doors to accommodate the people.
The love of Christ was felt to flow towards many this day,
to the contriting of our spirits.

26th. At Mother-Kill in the morning.
I sat in silence, but under much exercise,
because of the floating state which the minds of many are in.
In the evening I had a public meeting in Camden.
I was largely engaged among them, in unfolding the nature of true Christian worship,
in spirit and in truth,
contrasting it with that which is only the fruit of the creature`'s devices and inventions.

27th. Had a poor tried meeting at Milford, the light burns very dimly among them,
nearly gone out.

28th. Travelling hard these days past, besides having meetings daily,
together with the present warm season, when the water in these low countries is very bad,
has materially affected my health.
I had two meetings before me, which rendered the prospect very gloomy;
but I was enabled to cast my care on Divine help.
Though far from well, I left my bed in time to go, in the forenoon,
to Cold Spring Meeting.
I was appalled on beholding a large gathering of people.
I cried to the Lord for his Divine help.
My mind was prostrated before him, and I felt the quickenings of his power,
strengthening me every way, so that, under his putting forth and commission,
I preached the everlasting Gospel to the people.
Many minds were baptized and contrited under the power then felt.
The meeting holding late, and the other meeting,
which was to be held in an Episcopalian Meetinghouse, being at some miles distance,
I had to repair to it pretty speedily,
still trusting in the all-sufficiency of the Lord`'s eternal power,
to be my strength and my help.
There also I found a great concourse of people of various denominations.
Soon after sitting down among them, I felt the Lord`'s power upon me, and under it,
I had again largely to proclaim the Gospel of Christ,
and on bended knees to offer prayers, thanksgivings,
and praises to his Divine and Eternal name, who is forever blessed in himself,
whom all his works do bless and praise, as also my soul has done this day.

Help was in a remarkable manner extended to me,
so as to be able to proceed the next day twenty-five miles to William Matthew`'s,
at whose house I had a meeting that evening.

The two following days I had meetings among the people
called "`Nicholites,`" at North-west Fork and Centre.
They are some of the same people I visited some years ago in Carolina.
Silence, solemn silence, was what, by my example, I had to direct them to.
It is safe for us to follow Divine guidance, and I believe that this silent testimony,
when of the Lord`'s ordering, often speaks to the attentive mind,
a volume of instruction.

At Choptank, at a meeting mostly with the Methodists,
the stream of the Gospel was opened towards them.
There is a precious seed here among that people; but oh the need of more stillness,
so as to learn from Christ, the sure teacher.

5th of Eighth month.
At the Bayside meeting, Maryland, many slaveholders were present,
who make a great profession.
I showed the inconsistency of slavery and its various features,
with the spirit of Christianity.
At a meeting at Third Haven, in the Courthouse that evening,
the people were crowded in and out of doors.
Through adorable help, the Lord made it a time worthy to be remembered by many,
but especially by me his poor instrument.

6th. At the next meeting the expectation of the people was so outward,
that the Lord was pleased to send them away disappointed;
silence was my service among them.

7th. At another meeting of the Nicholites,
to which many that belong to their other meetings had come.
After a time of long silent exercise, the Lord was pleased to open the Gospel spring,
and to call me to minister to them.
It was a solemn instructive season.
In the afternoon I had another meeting in Denton Courthouse; it was a trying time,
and yet I was strengthened to declare the truth unto them, and salvation by Christ.

8th. At Queensborough, another very trying meeting.
The doctrines of the Gospel, however, were proclaimed to those present,
directing them to Christ Jesus the Saviour, the sure teacher and bishop of souls.

9th. Chestertown, at Friends`' meetinghouse in the forenoon,
and at the Courthouse in the evening.
The morning meeting was a season of Divine favour;
the other disturbed by the unsettlement of the people, and the irregular gathering,
yet it ended well.

10th. Very unwell last night; my strength is much reduced,
and yet I have two meetings appointed today at some distance from one another.
My inward as well as outward conflict is great.
O Lord, my God, forsake me not!
I went six miles to Cecil meeting,
which I have attended under great bodily sufferings and mental distress.
I endeavoured to centre in that state of submission in which I can say,
"`not my will but thine be done.`"
I rode seventeen miles further to the Head of Chester,
where the other meeting was appointed at five p.m. The consciousness that I was
in simplicity of heart endeavouring to follow my blessed Master`'s putting forth,
sustained me in hope that as my only strength every way is in Him,
He would not forsake me.
I knew He is not a hard but a good and gracious Master,
who requires nothing but what he gives qualification to perform.
My heart being thus stayed on the Lord, I went to meeting.
I was there made afresh a witness that the Lord is
indeed a very present help in time of trouble.
His Divine presence came upon me, and in it I found healing virtue.
I was endued with strength, to the astonishment of my friends,
who had seen my reduced condition, to preach the everlasting Gospel for above an hour.
May all those present remember that season of favour,
and close in with His renewed offer of grace and mercy extended to them.
After the fatigue and exercise of that day, I felt better than I had done for days before.

11th. My mind being now clear from further services, for the present, in these parts,
I concluded to proceed to Nottingham.
My exercises in this Quarter were great indeed,
but my blessed Redeemer was also near to strengthen me,
and to confirm my faith in his eternal sufficiency: he is the rock, the strength,
and the salvation of his people.
In nineteen days I travelled about three hundred
and sixty miles and had twenty-three meetings.

I proceeded from thence to the meetings very generally of the Western Quarter,
and parts adjacent.
Frequently I laboured with them on account of a spirit of unbelief that has crept in,
in some places.
It is hard work indeed to contend with an evil heart of unbelief.

I directed my course afterwards through Robertson, Reading, Maiden Creek,
and to the meetings over the mountains,
having meetings with Friends and others in all those parts.
The roads over the mountains being difficult for carriages, we left ours at Maiden Creek,
taking our journey now on horseback.

On the 7th of Ninth month, I had a meeting with a body of Germans,
who have lately come from Europe,
where for conscience`' sake they had suffered some persecution, even to imprisonment.
I found them in a tender state of mind and communicated
to them through the medium of an interpreter.
In the evening,
I had a small meeting at the widow Harris`'s. Oh how many have lost the savour of Truth.
I had close doctrine to deliver to them, under the clothing of pure love.

8th. Had a meeting at Williams Port, in the Courthouse.
Through the kindness of the sheriff, who showed strangers suitable seats,
the quietness of the meeting was much promoted.
On our first sitting down my mind was brought into much conflict,
under an apprehension that the yellow fever had made
its appearance in the city of New York;
this language passed through it,
"`one of thy near relations is taken with it;`" at
which my soul was bowed before the Lord.
I remembered my feelings in parting with my dear wife and her father at Rahway,
and I endeavoured to feel after that submission and confidence
which is our only refuge and strength in trouble.
After having thus made a fresh surrender of my all to the Lord`'s will,
I was prepared to enter into feeling for the meeting,
which was largely attended by the most respectable inhabitants.
The Lord`'s power rose into dominion, and under it I was able to minister to the people,
many of whom were tender in spirit, when,
on bended knees before the sacred presence I offered prayers, intercessions, and praises.
I came that night to the widow McCarty`'s, who has eighteen children living.
Some of them are pious young people.
She is a valuable minister.

Rising early next morning, we came thirty-six miles to Norwich,
where a meeting had been appointed at five p.m. It is a dark place,
but "`where sin abounds, grace does much more abound.`"
The Lord was pleased in his free love, through Jesus Christ,
the friend and Saviour of sinners, to cause his Gospel to be proclaimed among them.
My mind continues to feel for the distressed in New York,
though I have not yet any outward information of
the yellow fever having begun its ravages among them;
but, under the strong impression that some of my near relatives are taken down with it,
I am ready to conclude it may be right for me to return home,
and methinks I hear the sound of retreat.

I now re-crossed the mountains, and on the 12th came through Reading to Exeter.
Here I heard that the yellow fever was in fact prevailing in New York.

Pottsgrove, 13th. This was a remarkable time to me,
for after sitting a while in the meeting,
it seemed as if I was following some of my near relatives to their grave,
and I saw with clearness that it was right for me to return homewards with all speed.
It was a trial to me, as I had had some prospect of having a few more meetings,
in these parts; but I felt that the same power that had put me forth in His service,
now called me back from it; therefore my soul bowed before the Lord, in adoration.
Then I was introduced into very near feelings for some in that meeting.
My faith was much tried, for according to a superficial judgment,
on looking over the congregation, what I felt upon me to deliver,
did not appear to be applicable to their condition.
But I saw that my duty consisted, in simplicity, not with fleshly wisdom,
to declare what the Lord commanded me.
I unfolded to them the nature of Gospel ministry,
the qualification of a minister of Christ,
and the sad consequences of acting contrary thereto,
both in regard to ourselves and those upon whom a spurious ministry is imposed.
Then I enlarged upon the nature of true worship, in spirit and in truth,
together with the necessary preparation for it,
contrasting it with the worship of human inventions,
setting forth the propriety of our being found in a solemn, silent waiting before God,
that he may prepare our hearts, instruct and enable us by his Spirit, to serve, honour,
and worship him.
After meeting, I heard that there was a clergyman present,
who had been very free in his censures upon Friends and their way of worship, ministry, etc.
I had spoken so very particularly on those very subjects
that he charged Friends with telling me about him;
but they very properly answered, that I was a total stranger amongst them, and that,
besides, they could not have known of his own intention to attend the meeting;
for it appears he had been drawn there from curiosity, to see a French Quaker.

I proceeded that afternoon and the following days, with all speed, towards New York.
On the 15th of Ninth month I reached Rahway, by noon,
and there heard that my wife`'s mother was very ill with the epidemic.
Thus, confirmed in the correctness of the impressions made upon me, I pursued my journey,
and after crossing the North River that afternoon,
I met with a person who gave me the heavy tidings that my mother-in-law was deceased,
and that the family were at Westchester, (twelve miles farther),
where they had retired when the fever made its appearance in the city,
and that my dear wife was sick.
About nine at night I reached the house,
having in two days and a half ridden with my own horse one
hundred and forty-nine miles over hilly ground.
I found the family in great affliction, but supported under the stroke;
and now our solicitude was excited on account of my dear wife,
for she had a heavy load of disease upon her.
It is remarkable that on the evening of this my speedy return to her,
her mind was so sensible of my being near, that she told her sister,
who was near her bedside, that she saw me, as if I was in the chamber.
Her sister thought her flighty, through the fever; but she replied, "`It is a reality;
I see him near;`" though at that time,
she had every reason to conclude I was about two hundred miles distant.
She felt very much the loss of her valuable mother,
which rendered the disease upon her the heavier;
though she did not weep as one without hope--our beloved mother having manifested,
by her daily walk in watchfulness before God,
that she endeavoured to live in a state of preparation.
Religion was her every day work.
Being a full believer in the Lord Jesus Christ,
she was remarkable for the meekness and gentleness of her temper, and the quiet,
cheerful resignation she manifested under the various
trying occurrences which attended her.

--

It is scarcely possible to read this simple record of facts,
without noticing the beautiful coincidence between the dispensations
of Providence and the leadings of the Holy Spirit,
which at once illustrates and confirms the reality of both, and is, perhaps,
one of the best safeguards against inadequate views in regard to either.
Arrested in the midst of his ministerial labours in a remote part of Pennsylvania,
by a guidance as precise as it was direct,
Stephen Grellet was most opportunely brought home to his nearest connections in life,
at a very critical moment, and under circumstances of peculiar need.
His steps seemed clearly "`ordered by the Lord,`" and his
feelings of thankfulness mingled with those of sorrow.
His tenderest solicitude was kept alive on behalf of his beloved wife.
She continued very ill several months after his return,
and her life was repeatedly in imminent danger--her complaint
having assumed the character of a low nervous fever,
from the effects of which her health did not recover for some years.
Though accustomed to bow in humble resignation to the Divine will,
this dispensation proved the more trying to Stephen Grellet,
on account of the prospect of distant scenes of labour
which had long been opening to his view.
Even during this season of domestic affliction, a concern to visit his native land,
in the service of the Gospel of Christ, was gradually ripening in his mind.
