== Chapter XII.

[.chapter-subtitle--blurb]
First Visit to Europe

[.chapter-synopsis]
* The Scenes of His Youth
* Interview with His Mother
* His Relatives
* Brives
* Limoges
* Bergerac
* Bordeaux
* Return to New York

From Montpellier Stephen Grellet passed over the Cevennes;
"`travelling night and day about four hundred and fifty miles,`" he reached Brives,
the place where his mother then resided.

His visit to the little company of Protestants who profess with Friends,
and the inhabitants of the small towns and villages about
Nismes and the hill-country a little to the north-west,
though attended with difficulties and trials, had been a deeply interesting one.
He had had "`large and precious meetings`" among them,
had "`freely visited them in their families,`" been
the means of confirming many in the faith of Christ,
and of encouraging the little community who bear the name of Friends
in the support of a Christian discipline among themselves;
he had enjoyed much of the comfort of love,
and of the help of mutual confidence and brotherly openness,
in his interaction with that simple-hearted people; and he had taken his leave of them,
though not without much Christian solicitude,
yet with the cheering hope that the Lord has a seed
among them which he will preserve and bless.

It was an interesting point in his Gospel Mission, when,
passing away from these more Protestant districts,
he entered upon almost exclusively Roman Catholic ground,
and now returned to the scenes of his youth and early manhood.
He had left them about fourteen years before, in the ardour of military excitement,
in the midst of the great revolutionary struggle--nominally a Roman Catholic,
but in reality an unbeliever; he came back, a humble disciple of the Lord Jesus,
a preacher of the faith he sought to destroy,--a Protestant,
and a member of the religious Society of Friends.

That Christian community, it is well known,
taking its stand upon "`the foundation of the Apostles and Prophets,
Jesus Christ himself being the chief corner stone,`"
recognises no authority in matters of faith and worship,
but that of God; upholding the Holy Scriptures of the Old and New Testament,
as the only Divinely authorized record of doctrines
to be believed and duties to be practised,
it absolutely rejects the idea of authority in the mere traditions of men.
Believing that the true church is confined to no particular denomination of believers,
and depends only on her glorious Head, Christ Jesus the Lord,
who rules the Universe for her sake, governs her by his Spirit,
and blesses her by his gifts,
it acknowledges no right of human interference with the consciences of men;
except "`by the diffusion of The Truth.`"

Giving no countenance to the assumption of apostolical succession, or the continuance,
under any form, of the sacerdotal office,
or the setting apart of a distinct class of men exclusively to minister in holy things,
with a right to claim support from the temporalities of others,
and to exercise dominion over them, that Society expressly maintains, on the contrary,
that Christ himself is the supreme ruler in his Church, and that,
under the guidance of His Spirit,
all the Lord`'s children enjoy the right of self-government; and,
considering all the living members of the Church as Priests of the living God--all capable
of receiving and using the gifts of the Spirit,--it sanctions no ministry in the Churches,
but that which flows from the pure and immediate operations of the Holy Ghost.

Not admitting, for one moment, and on any plea whatsoever,
the religious worship of any other Being but the Eternal Jehovah--Father, Son,
and Holy Spirit,--that Society emphatically proclaims that "`God is a Spirit,
and must be worshipped in spirit and in truth;`" enjoins simplicity, sobriety, and order,
in all the assemblies for the purpose of that worship; and,
calling for the prostration of the soul before the Majesty of Heaven,
in the silence of all flesh,
and for the offering of spiritual sacrifices acceptable to God by Jesus Christ,
it repudiates all the pomp and parade of external rites and ceremonies,
the spurious aid of architectural display, and the delusive charm of musical excitement;
it lights no candles, and burns no incense upon any visible altar,
bows down to no graven image, adores no saint,
and recognises no object of religious homage in the Virgin Mary.
Totally rejecting the notion of works of supererogation,
it performs no pilgrimages to any sacred shrine,
knows nothing of the miraculous power of relics,
is an utter stranger to the imagined flames of purgatory, has no indulgences,
no auricular confession, no sacerdotal absolution, no masses for the living,
no prayers for the dead.
Acknowledging no mediator between God and man but Christ,
no justification of the sinner but through faith in His blood,
no sanctification of the believer but by His Spirit--it
has no sacraments but that of the washing of regeneration,
or the baptism of the Holy Ghost and fire, and a participation, by faith,
in the body and blood of our Lord Jesus Christ,
the Saviour of the world,--no hope of eternal life but through the one
offering whereby He has perfected forever them that are sanctified.`"

As a member of such a Community,
and an accredited Minister of such a Church,--so entirely opposed to the Papal system,
and to every kind and degree of hierarchical or ecclesiastical domination any where,
Stephen Grellet could not fail to appear in striking
contrast with those who now surrounded him,
in the heart of a Roman Catholic country;
it was not strange that peculiar exercises and conflicts should await him,
on mingling with them in social and religious interactions,
both in the intimacies of private life, and on more public occasions.

[.offset]
On entering the borders of his Father-land, he writes:--

[.embedded-content-document]
--

My exercises in approaching Brives were great,
and many of the conflicts I had in America, in anticipation of this solemn occasion,
were renewedly felt, so that I have entered this place with a spirit much bowed down,
and with a great weight resting upon me.

The meeting with my precious mother was an affecting one.
We had not seen each other since the year 1790,
and many eventful circumstances have occurred during that series of years.
Her sufferings, and those of my dear father, during the Revolution, were great,
more so than I had heard before.

I am here entirely surrounded by Roman Catholics, and am a public spectacle among them.
Every part of my dress, speech, and conduct is narrowly considered,
and gives rise to various inquiries.
Never have I felt more forcibly the necessity of constant watchfulness,
and to have my every action so wrought in the light, that, in the light of Truth,
which bringeth conviction to the heart, I may answer their inquiries.
My services among these people are of a different
character to what they have generally been hitherto.
There is no door open, as yet, for public meetings among them;
indeed they do not understand the nature and object of them;
but I have interesting and solemn seasons in private circles.
In almost every company to which I am introduced,
their spirit of inquiry leads to the unfolding of
some of the principles and doctrines of the Gospel,
and the nature of pure religion, and the true worship of God.
Thus I have to set before them,
how unsafe it is to trust the salvation of a never-dying
soul to what their priests can do for them,
to prayers to their saints, etc., the short and only sure way being,
with sincere repentance for our sins, to come to Christ Jesus, the only Saviour,
who has given himself for us to save us from sin,
and not that we should continue to live in sin.

I have been with several of the priests,
but how dark and ignorant they are! pleading for their various superstitions,
gaudy practices in their masses, confessions, worship, their indulgences, pilgrimages,
and many such doings.
They bring forth tradition as their authority, which, they say,
has proceeded from oral command, delivered by the Apostles to the Church,
and has regularly descended to them through the Popes and Bishops, etc.,
and that their traditions supersede the express testimonies of the Scriptures,
the contents of which most of them are very ignorant of.
They moreover appeal to the decrees of the Church of Rome, or the Bulls of the Pope,
as authority for many of their practices.
I directed them, on the other hand, to Christ,
"`the true Light that enlighteneth every man that
cometh into the world,`" and to his Spirit,
"`a manifestation of which is given to every man,`" whose
teaching is in perfect harmony with the Scriptures;
for "`holy men of God spake as they were moved by it;`"
whereas their pretended traditions or Pope`'s decrees,
are most of them contrary to the express language of the Scriptures.

Yet I find amidst such a mist of darkness, some tender, spiritually minded persons, who,
I trust, are near the kingdom of God.
Our merciful High Priest, who is touched with a feeling of our infirmities,
has regard to the integrity of their hearts.
I have had frequent opportunities to open to some
of these the pure and undefiled way to life everlasting.
Their hearts rejoice at the glad tidings, and are often much tendered.
Several of these are among the nuns.
In one convent, their Superior, being a sensible woman, hears the Truth with gladness,
and gives me opportunities for unfolding the truths
of the Gospel of Christ to the nuns of her convent.
If the priests encouraged them in the right way, by example and precept,
instead of setting a stumbling block before them,
bright instruments might arise from among them.
I marvel indeed how, under their present circumstances,
I can have so open a door with them;
for the priests have endeavoured to represent me to them, as a very dangerous person,
who is out of the pale of the Romish Church, and they assert,
that out of the Roman Catholic and Apostolic Church, there is no salvation.
But these pious persons say,
that it is the true and everlasting Gospel that I declare to them,
and therefore their confidence in their priests is shaken.

This has been the case with my beloved mother.
She felt such concern on my account, thinking that,
according to the representation of the priests, I must be finally lost, as a heretic,
that she had them to say masses on my behalf,
and paid also money that prayers might be put up on my account; not satisfied with that,
she urged me to accompany her to her confessor,
a monk in whom she placed great confidence,
hoping he would convert me to the papist`'s faith.
To satisfy her, I yielded to her request.
But great was her disappointment, when she saw that,
instead of using the arguments she expected, to convince me,
he gave way to bitter invectives and reflections, because I would not fight,
refused to take oaths, etc.
I brought forward clear Scripture passages, as authority,
from the positive commands of Christ the Lord, whom we are to obey in all things,
adducing also the Apostles, and the practices of the primitive believers.
Then he gave way to anger, so that he could proceed no further,
and being worked up into a passion, I left him in that state.
After we got out, my beloved mother lifted up her hands in astonishment,
at conduct so unbecoming the Christian professor;
and from that time her mind has been much more open to receive the Truth.
Like the noble Bereans, she peruses and searches diligently the Scriptures,
a copy of which I have given her, to know if these things are so.

I continued at and about Brives thus engaged, amidst many secret and more public trials,
till the 6th of Eleventh month.
I then went to Limoges, the place of my nativity.
My being here revives many past occurrences, and awakens feelings of humble gratitude,
for the mercy and power of Redeeming Love, which has visited me, and in good degree,
I trust, brought me out of that state of darkness and alienation from God, under which,
in this place, the blessed Saviour so long bore with me,
and waited to be gracious to my then impenitent soul.
It also brings to view the many sufferings that my beloved parents have endured,
even from persons who had been among their greatest intimates.
I felt nothing but love, Christian love, towards them, and in this,
I have visited several of them; one of them, the Mayor of the city,
who had been among the greatest persecutors of my family, during the Revolution, told me,
in allusion to those days, "`we have in your absence acted more like ferocious beasts,
than men--much less as Christians.`"
I now only stayed two days in Limoges.

On the 9th, I went to Bellac, to my beloved sister De Boise`'s; there,
or in the neighbourhood,
I stayed till the 27th. I had some interesting religious meetings and opportunities.
One of these was with one of my old tutors, in my father`'s house,
whom I visited at the college of Magnac.
He is a priest, and the head of the college; he was much pleased to see his former pupil,
and manifested more liberality than it is common to find among that class of men.
My dear sister is one who is less under the shackles of superstition than most.
I have great comfort in being with her.
There are also a few persons here with whom the Testimony of Jesus has a place;
but my spirit is under great heaviness on account of the people generally.
Vital religion has fled from among them,
and they have set up their priest`'s inventions instead of it.

I returned to Limoges on the 28th, where,
my dear Master opening a door for preaching the unsearchable riches of Christ,
I continued till the 14th of Twelfth month.
I had many public as well as private religious seasons,
so that many of the priests became much alarmed.
It being the time when some of their renowned orators who had come from a distance,
preach every day, I was made the subject of discourse, in their large church,
(St. Peter`'s). Their church was represented as in
the most critical state it had ever been in;
it was said that Buonaparte had sent for me, from the remote parts of America,
to undermine, and if possible, to destroy their holy religion.
Such representations excited the public curiosity still more,
and brought many more to the meetings I had.
Others also pay me private visits, some from curiosity only,
but others from a disposition to come to the knowledge of the Truth.
Among these, some of the nuns that I have visited, have manifested great tenderness;
but it is very hard for them to be emancipated from
the influence and fear of their priests.
I have had several conferences with some of the latter,
but very few of them to satisfaction, for want of their keeping in the Christian temper.
One of them, however,
must be excepted,--the teacher of Theology in the Priest`'s Seminary.
I was also with another who before the Revolution, was their most renowned preacher.
During the Revolution, before the rude, lawless multitude,
he publicly reviled and blasphemed the Divine character of our Lord Jesus Christ,
trampled upon the Christian religion, turning it into ridicule, and told them,
"`these forty years I have been deceiving you and myself,`" and then gave way,
with the multitude, to acts of vileness and profanity, defiling their altars,
and setting up the goddess of reason (as they called a young woman) upon them.
I did not know then who the man was.
There was a company present of about forty persons, when in a mild, becoming manner,
he inquired into my views on the nature of the fall of man,
and of his restoration through Jesus Christ, baptism and their various sacraments,
the eucharist, etc.; also, into the nature of true Gospel ministry and worship,
what constitutes the true church of Christ, etc.
After I had distinctly answered him on every one of these important subjects,
and some others, he told the company present in a solemn, impressive manner,
"`you have heard this day more true Gospel Divinity than you have ever done before or,
may be, ever shall again.`"
I find that this man, after having gone such a length in infidelity, saw his errors,
and the errors also of the Church of Rome, which he had so zealously espoused before.
Therefore, though pressed by the clergy to resume his former duties,
and even to accept greater preferment, he declined; he also refused to deliver,
at the Bishop`'s request, his manuscripts of sermons, that they might be preached again,
stating that they were written when his mind was in darkness,
and understood not the great Truths of Christianity, as he now beheld them.

I might write much of the various steps taken by some of the priests, or their agents,
to try to gain me to their ways;
sometimes they would make great promises of the church`'s honors and preferments,
that should be bestowed upon me, if I would embrace their opinions; then again,
finding this could not prevail to turn me from the Christian Faith,
they poured out upon me their anathemas, etc.
I have also frequently had to encounter open Deists, and even Atheists.
Thus among the various classes, professors and profane, my sufferings are many;
yet I have had some consolations in being a witness that
the blessed Truth has found a place even with some,
who at first, discarded the Christian religion as a whole, and every other religion,
considering them as the work of priestcraft, to deceive the people.

I returned to Brives the 14th of the First month, 1808.
My mind being not yet at liberty to leave those parts,
I continued thereabouts till the 23rd, having some large meetings.
I then went to Bordeaux, by the way of Bergerac.
There my way was hedged up;
though I was sensible that there were pious individuals in that place,
yet I could not come to the personal knowledge of any.
My soul`'s travail and prayers for them were silently put up in the closet of my heart,
to Him who seeth in secret.
My way in Bordeaux is also much shut up,
though I have the comfort of being with my dear brother Joseph Grellet,
who for the present resides in this city.

I have of late been greatly depressed on account of the condition of this nation;
the almost uninterrupted wars in which it has been involved for some years past,
together with the oppressive system of the conscription,
have brought obvious desolation and distress over the face of the country.
In many places comparatively few men, besides those in public offices, are to be seen,
except those maimed by the war, or the aged, so that females have to perform,
out of doors, a great part of the laborious work that generally devolves upon men.
My heart is also often made sad in beholding the bands of young conscripts,
marching towards the army, now preparing to invade Spain.

Here, in Bordeaux, is a large number of handsome young men from Poland,
of the first families of that nation, training for the new war.
I have been with some of these young people, who appear to have received a religious,
guarded education.
How must their parents`' hearts bleed to have them now thus circumstanced!
Day and night my mind is turned towards Buonaparte.
O could I plead with him! could I bring him to feel and see, as I do,
the horror and misery he is accumulating upon man,
and the vices and immoralities he causes poor unwary youth to be involved in!
I have made several trials to procure passports to go to Paris, but cannot obtain them,
yet I have not told anybody the concern I feel for the Emperor.
If this is a service that the Lord has for me,
he is all powerful to open a door for it--into his hands I commit myself.

I have found here a few pious Christians,
with whom my soul has been refreshed in the Lord.
Among others, I have been with an old woman, a nun,
who manifests much humility and brokenness of heart;
she is acquainted with inward watchfulness and prayer;
it is her soul`'s delight silently to wait upon the Lord, and to meditate on his law.
She finds, she says, far more consolation in this silent exercise before God,
than in any outward performance;
yet the rules of her Order require that she should read every day the Breviary,
a long form of prayers and collects in Latin, of which she hardly understands a word.
She laments the more her situation,
as she knows of none about her who understand the
nature of her soul`'s exercise and travail;
she is even afraid they should know it.
I had a sweet opportunity with her; the language of encouragement flowed towards her.
I have also had several relieving meetings with small select companies.

--

Stephen Grellet`'s labours in his native land were
brought to an earlier close than he had looked for.
Under the restrictions of Napoleon`'s military despotism,
he was not allowed to proceed to Paris, as he wished to do,
and no further service appearing to be required in other directions,
he felt at liberty to leave France,
and to take his passage in a vessel ready to sail from Bordeaux to America.
He thus continues his journal:

[.embedded-content-document]
--

14th of Second month, 1808.
I have embarked this day on the ship _Eliza_, Captain Skiddy, to return to New York;
I found that my efforts to obtain leave of the Government to go to Paris were fruitless,
and the door also closing in my mind to labour with Buonaparte,
who appears bent on pursuing his military operations, I have felt satisfied,
for the present, to retire from this country; I am, however, far from being able to say,
that I leave it with a clear mind.
I am more than ever united to a remnant in it,
and feel more deeply than heretofore for the distress and misery of the people,
under their two-fold oppression,--that of their spirits,
through Popish ignorance and superstition,--and that of their persons as well as property,
through the rod of iron with which they are ruled.
Having felt much for the few professing with us at and near Pyrmont, in Westphalia,
I have written them an epistle; also another to the little flock in the South of France,
whose welfare I have near at heart.

21st. We have been detained several days below the river, near Royan,
by an embargo laid on by the Government,
on account of the sailing out of some of their armed vessels.
The time has not been lost,
as I have made an interesting visit to some Protestants on the river-side.
Yesterday morning, having liberty to set sail, as we were proceeding out of the port,
we saw three English frigates at the entrance of it, at anchor, and blockading the port,
so that our captain, being afraid of being captured, came again up the river;
but last night, which was a dark one, he had every light put out,
commanded entire silence on the ship,
and then passed through the frigates without being observed.
We have now a fine wind.

28th. The wind has continued so fair that it is thought
we have now made half of our distance to New York,
without altering our sails.
We have about thirty passengers in the cabin, men, women, and children, mostly French.
How different is my present situation to what it was on board the Brunswick,
on my way to Marseilles.
Then I was the only passenger, and I had much time for retirement; but now, the day,
and often parts of the night, are rendered so noisy by my jovial companions,
as to give me very little quiet; yet, at seasons, the Lord is pleased to keep me,
in the midst of them, as one that having eyes, seeth not, ears, but he heareth not.

14th of Third month.
For some days past we have had such hard gales of wind,
as to be under the necessity of laying the ship to; my confinement is tedious,
because of the swearing, drunkenness,
and obscene language of some of those among whom I am;
it reminds me of Lot`'s abode in Sodom.

21st. I have succeeded in my endeavors to settle some serious
differences that have arisen among some of the passengers,
in consequence of their wantonness and vicious habits.
For a while it threatened to be followed by effusion of blood.
Awful consideration, to see how the peace and harmony of a little company as we are,
should be thus disturbed.
My soul is daily made sad among them; nevertheless, I behold with gratitude, how,
notwithstanding their ill behaviour towards me sometimes,
when they are under the effects of strong drink,
they come to me when in trouble to settle their difficulties.

24th, New York.
Yesterday afternoon I was favoured to land here safely,
my heart prostrated with gratitude before the Lord,
who has restored me to my dear wife and friends,
and preserved me amidst so many baptisms.
I found my beloved wife still feeble, but able to go with me to meeting.

--

Stephen Grellet had been absent more than nine months;
a few weeks after his re-union with his family and friends,
he adds the following memorandum.

[.embedded-content-document]
--

19th of Fourth month.
Since my return home I have frequently looked back on the
Lord`'s merciful and gracious dealings with my soul,
during the last few months of deep and peculiar exercises and dangers,
both by sea and land.
He has indeed fulfilled the most gracious promise he made me, on my going out.
He has been with me, to help, protect and deliver his poor servant.
What shall I say now, O Lord, under the sense of these thy favours?
Return to thy rest,
O my soul! for the Lord hath dealt bountifully with
thee;--the Lord is thy strength and salvation,
he has been thy shield, thy buckler, thy rock, and thy refuge.
Enable me, O Lord, to the end of my days, to be thine,
and to serve thee with my whole heart.

--
