== Chapter XVI.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Wales
* Bristol
* Bath
* London Yearly Meeting
* Eastern Counties
* North of England

Rather more than five months had been spent in Ireland,
and Stephen Grellet now crossed the Channel into Wales.
The Half-year`'s Meeting for the Principality was about to be held at Brecon, and,
having a few meetings by the way, he proceeded pretty directly to that place.

[.embedded-content-document]
--

"`On the 5th of Fourth month, 1812,`" he writes, "`I landed at Holyhead,
after a rough but short passage, during which I again suffered much from sea-sickness.
O Lord! direct my steps aright through this principality, and, as heretofore,
fulfill very graciously thy word of promise,
in which thou hast enabled thy poor servant to believe: '`I will teach thee,
and instruct thee in the way which thou goest; I will guide thee with mine eye.`'

"`I left Holyhead,`" he proceeds, "`the afternoon after my landing,
accompanied by a dear friend who came over from Dublin with me.
On my way to Brecon,
where the Half-year`'s Meeting for this principality is held at this time,
I had meetings among Friends, and also in places where there are no Friends.
In several of these, the people speaking only Welsh,
I had to communicate to them through an interpreter.
There was great brokenness of heart among some of them.
The meetings at Dolgelly and Tyddyn-y-gareg were seasons favoured of the Lord.

"`On the 14th began the Half-year`'s Meeting,
where I was comforted among some valuable Friends, who belong to it.
I had also a satisfactory meeting with the inhabitants of Brecon,
and another with a considerable number of French officers, prisoners of war on parole.
I spoke to them in French, as they do not understand English.
The hearts of some of them were tendered under the power of Truth prevailing among us.
Many of them came to me after meeting, in much love and good-will,
and some of them bore excellent testimony to the
blessed principle of light and truth in the soul.
'`What a blessed thing would it be,`' they said, '`were men more obedient to it,
then there would be an end of wars and fightings.`'

"`17th. I had a very large, good meeting at Llandilo; many of the people,
and even the children, shed tears;
they were so affected under the solemnity of the testimony delivered among them.`"

--

From Llandilo he went to Haverford-West and Milford Haven.
Thence, "`having one or two meetings every day,
and very close exercises in some of them,`" he returned along the coast of South Wales,
by way of Caermarthen, Swansea, Neath, Cardiff, and Newport,
and crossed the Channel to Bristol.

[.embedded-content-document]
--

30th of fourth month.
I arrived at Bristol in time to attend the Week-day Meeting on Sixth-day.
The next day I was at a funeral; on First-day I attended their two meetings;
the following days I was at Frenchay and Thornbury,
and returned to Bristol to their Third-day Meeting;
my mouth was closed at all these meetings.
I believe this was the service the Lord required of me.
May I ever be preserved under the guidance of his blessed Spirit.
There is a time to speak and a time to keep silence.
I then went to Bath, and had a meeting with Friends, also in silence.
In the evening a large one was held for the inhabitants, in which,
through the Spirit of Christ, our holy Head,
I was enlarged in preaching the glad tidings of his glorious Gospel.
The following day I was at Melksham and Devizes.
At the first place, after a long season of deep and silent wrestling, like Jacob,
for the Lord`'s blessing, I felt as in his presence,
and as if encircled by the spirits of many of my beloved and valuable friends in America,
and some of those to whom I have had the privilege
to become united in the fellowship of the gospel,
since my coming to these nations.
Very preciously near also did I feel some of those,
now disembodied of their tenements of clay,
once like ourselves members of the militant Church,
but now joined to the Church triumphant in heavenly places in Christ Jesus.
It was indeed a blessed, refreshing season.
In the afternoon I had particularly to minister to one, then entirely unknown to me,
but for whom I felt much in spirit.
She was a young woman who has undergone deep trials at her own home,
under the secret baptisms of the Lord, which she has endured,
none knowing the great exercise of her mind.
This afternoon she exchanged her gay attire for the plain garb of Friends,
which she had believed, for some time, the Lord required of her;
but she now felt that the full time for her doing so had come.
Hearing of that appointed meeting she had come to it,
and manifested great brokenness of heart.
I was afterwards with her to much satisfaction,
for she evinces that she is one of those children, who are taught of the Lord.

--

From this time Stephen Grellet was closely occupied
in holding meetings on his way to London,
to attend the Yearly Meeting.
The following brief record only is left:

[.embedded-content-document]
--

Fifth month, 15th. Having had one or more meetings daily, I have come to Walthamstow,
near London, to my long valued, though hitherto personally unknown,
friend William Dillwyn.
There I met very agreeably my dear friend Henry Hull from New York State,
who is like myself engaged in a religious visit to these portions of the Lord`'s vineyard.

The next day I came to London, to my very kind and beloved friends,
Joseph and Rachel Smith, who, soon after my arrival in England last year,
sent me a very kind invitation to make their house my home.
They have received me with Christian and parental affection, and genuine hospitality;
their house is a true resting place to me,
for it feels as if the description given of that of Obed-edom, is applicable to it.

London, 17th of Fifth month.
I attended two crowded meetings, this being the time for holding their Yearly Meeting.
Many Friends from the various parts of this nation, Scotland, and Ireland,
have already come into the city.
I sat both these meetings in silence,
but with a spirit fervently engaged before the Lord,
my heart being poured out at the footstool of the Divine Majesty.
O it feels awful to me to be in this great and crowded city; the sense is heavy upon me,
that bonds and exercises await me here;
my earnest solicitude and frequent prayer is that I may be kept very near to the Lord,
and the guidance of his Spirit, that in all my movements, life, and conversation,
out of meetings, and in all my doings in meetings, be it to sit in them in silence,
or to be called to the exercise of the ministry of
that glorious Gospel of life and salvation,
to which my blessed Lord and Master has called me,
I may approve myself as his faithful servant and minister.

19th. Yesterday and today the meeting of Ministers and Elders sat twice each day;
they were solemn meetings.
My soul was greatly and reverently prostrated before the Lord,
that the ministry among us may be kept pure,
and ever partake of that Life whence it must flow.
I have been as a child instructed among those whom
I feel as fathers and mothers in the church.
In one only of these sittings, my soul`'s travail was accompanied by vocal expression,
which was in fervent supplication to the Lord,
who is the only helper and strength of his people.

Seventh-day, 30th. This forenoon the Yearly Meeting closed,
and that for Ministers and Elders was held in the afternoon.
With grateful and reverent acknowledgment I may join with many dear and valuable Friends,
anointed servants of the Lord,
in believing that the blessed Head of his church has condescended to be with us,
during this yearly solemnity.
He has also enabled his poor servant silently to bear up under various exercises,
and at seasons I have had a door set open before me for the relief of my mind,
and to the exaltation of His holy name, who is blessed forever.

Sixth month, 6th. I continued in London to this day attending several meetings,
some of which were held under great solemnity and
a tendering prevalence of the power of Truth.

--

Leaving the metropolis, Stephen Grellet attended the Quarterly Meetings of Essex,
Suffolk, Norfolk, and Norwich, and had many meetings in Lincolnshire.

[.embedded-content-document]
--

"`Accompanied by my dear friend, George Stacey,`" he writes,
"`we have come into the county of Essex,
and have had several meetings on the way to Colchester,
where their Quarterly Meeting was held at this time.
Here I was edified and comforted by the company of that dignified,
aged servant of the Lord, John Kendall, at whose house I lodged.
He is one of whom it may be said, that he is a preacher of righteousness;
the element in which he appears to dwell is love.
There also I have met my beloved friends William and Rebecca Byrd,
who are on a religious visit to these counties.
They often remind me of Zacharias and Elizabeth; so blameless appears their daily walk.
Towards the close of that Quarterly Meeting, the power of Truth rose into dominion.

"`After attending all the meetings in that county,
and having some large and satisfactory ones among the inhabitants, we came into Suffolk,
and attended the Quarterly Meeting, at which,
and at all the particular meetings in that county,
together with several of a more public character, I had, with much comfort,
the company and united exercises of W. and R. B. We had some very solemn meetings,
when the baptizing power of the Truth rose at seasons into dominion over all.

"`22nd. Came to Norwich Quarterly Meeting, after which,
I had meetings in nearly all the towns of that county.
Several of them were held in their Town Halls,
or in the places of worship of various religious denominations.
They were mostly largely attended, and were favoured seasons.
Christ, the Saviour of sinners, was exalted among them;
the people were directed to him as the only sure refuge and hope of salvation.
If we love him we must prize his gifts, which he has purchased for us by his own blood.
He has given himself for the church,
and bestows also the most excellent gifts of his Spirit, to every man to profit withal.
Grace and truth came by Jesus Christ,
so that by his blessed assistance we might be able to perform acceptably
whatever is required of us--walk in the Spirit--pray in the Spirit,
worship in spirit and in truth.
I had also some precious meetings with Friends,
towards whom my soul is often drawn with fervent solicitude that,
according to our Christian profession,
and the excellency of the Christian testimonies which as a religious
society we believe ourselves called upon to exalt,
we may all be found to maintain them in faithfulness before God and man.

"`Dear G. Stacey leaving me to return home, my friend J. G. joined me during a few weeks.
He is a man of a watchful spirit,
which is peculiarly observable in the exercise of his ministerial gift.
We proceeded through Lincolnshire,
having large meetings in the principal towns of that county; some very refreshing ones,
particularly at Gedney, with Friends.
It was a pleasant rest every way to me, to be at my beloved friend,
Jonathan Hutchinson`'s. He is a man of a meek and quiet spirit,
whose daily life and conversation adorn the Gospel of Christ.`"

--

Having completed his visit to the Eastern counties,
Stephen Grellet passed over into Yorkshire,
and pursued his religious labours through some of the northern parts of the nation.

[.embedded-content-document]
--

Seventh month, 17th. Came to Thorne, in Yorkshire,
where the meeting was attended with solemnity and refreshing from the Lord`'s presence,
similar to what we had in such an eminent manner been favoured with at Gedney;
but soon after this the dispensation to me was greatly changed.
Well known unto the Lord is the end of all his dealings; safe and proper it is for me,
his poor and dependent creature, with all lowliness and submission,
to abide under them all.
Most of the meetings I now had, on my way to York and thereabouts,
were attended with deep inward baptisms; silence in them was generally my portion,
and the little I had to express, in some of them, was of a close, searching nature.
At Beverley,
I had not felt at liberty to allow Friends to give any notice of my being at their meeting,
and yet a number of strangers came in,
when my mind was introduced into great weight of exercise.
Dwelling under it,
I felt it my place to communicate what appeared to
be the word of the Lord unto the people.
Though the outward appearance of those present,
would have persuaded me that such a communication,
could not be suitable to such a congregation,
I opened to them what were the requisite qualifications, under the law,
for the priests to minister in the outward temple,
and from whom the Lord`'s prophets received their
authority and ability to speak in his name.
With this I contrasted the services of the priests of Baal and of Jeroboam,
and the state of the false prophets,
who some of them mixed with the words of their own imagination and deceit,
those they had stolen from the true prophets of the Lord.
Then I proceeded to unfold what, from the early days of Christianity,
has constituted a minister and an Apostle of Christ.
What was their anointing, from whom their mission and authority came,
what made them able ministers of the New Testament,
and what evidence they gave that the Lord, by his Spirit, had sent them;
shewing that as the ministration of the Gospel is now the same,--the same Gospel,
and no other, is to be preached,
the same anointing and qualifications for the solemn
service are to be received from the same source,
even the Head of the Church, the Lord Jesus Christ,
who bestows his Divine Gifts upon his servants according
to the several offices to which he has appointed them.
Thus I set forth the nature, office and qualifications of a Gospel minister;
described what the Church of Christ is, in what consists that worship,
which the Father of Spirits requireth, and which it is our duty to offer unto him,
even in spirit and in truth; finally, I contrasted with all this,
the present formal worship of many Christian professors, their man-made ministry,
whence their qualifications proceeded, etc.
It was a solemn good meeting.
I was informed afterwards that several clergymen were present,
who had been induced to come by the novelty of a French Friend being there.

A few days ago, I was at the Friends`' boarding school at Ackworth,
with much satisfaction.
In the religious opportunities and meetings I had with them,
and with the inmates of that large and interesting family,
many manifested great tenderness and sensibility,
evincing that the fear of God and the love of Christ have a place in their hearts,
and that they are acquainted with the teachings of his grace,
and the operation of his Divine Spirit.
May the Lord`'s blessing rest upon these tender plants, and on their pious caretakers,
and their labour of love.
I have repeatedly beheld the good arising therefrom, in the families of Friends,
whose children have received their education at that excellent seminary.
I have seen the good seed sown there, bringing forth fruits to the Lord`'s praise.
I was also refreshed and edified at York,
in the company of those valuable servants of the Lord, Lindley and Hannah Murray;
and William Tuke, who is as a pillar in the church; his son Henry is so also.
Samuel, the son of the latter,
promises to become worthy to receive a double portion of
that good Spirit who actuates the father and the grandfather.

Seventh month, 27th. I came to Hull, where I tarried two or three days.
Services of a private nature in families were set before me,
as also some of a public kind, among Friends and others in that populous town,
together with the inmates of their poor-houses.
I feel my mind frequently drawn in Gospel love and very
near sympathy to visit that portion of my afflicted fellow-men,
and have had in several places some very interesting and solemn seasons with them.
In some instances I have been forcibly reminded of the description of Lazarus,
given by the evangelist.
I also see this Scripture fulfilling, "`To the poor the Gospel is preached.`"
The stream of this precious Gospel has repeatedly flowed in a wonderful
manner in the meetings that I have had among them.
Prisons also are places to which my mind is often attracted.
How can it be otherwise,
than that the abiding sense I have of the great love and mercy of God, in Christ Jesus,
even towards me, who, like the Apostle, may well call himself,
"`the chief of sinners,`"--should constrain me to feel and to judge,
that if love and mercy have thus wonderfully been extended towards me,
they flow also to the inmates of prisons;
for Christ has died for all men--he has come into the world to save sinners, yea,
the chief of sinners.
O how powerfully did the Apostle feel the force of this,
when he exclaimed "`It is a faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners,`" etc.

I have now a great exercise upon me, because of the accounts received,
that war has been declared between England and America,
that there has already been considerable effusion of blood,
and that free intercourse between the two countries is interrupted.
In consequence of this,
it is very difficult for me to receive letters from my beloved wife,
or to forward her mine.
The accounts also of the destruction of human life by the belligerent
nations on the European continent are truly awful;
torrents of blood do indeed flow, both in the north of Europe, and in Spain and Portugal;
prisoners of war from Spain continue frequently to be sent over to this island.
Under these most afflictive circumstances,
which so awfully develop the depravity and sinful state of the human heart,
how can I but feel myself most imperatively called upon,
with all diligence and faithfulness, to preach Christ the Redeemer,
and the only Saviour from all these evils, entailed on man by sin;
to direct all men to him, the Prince of Peace, and to his Spirit,
who would lead into all Truth,
if they can be prevailed upon to turn to him with full purpose of heart.
My heart yearns also towards the nations on the Continent;
deep is the travail of my soul for them, and frequent are my prayers for their rulers,
that the Lord may so change their hearts, that he himself may come to reign in them,
so that they may be induced to beat their swords into plough-shares,
their spears into pruning-hooks, and neither learn nor make war any more.

I left Hull, accompanied by my dear friends John and Mabel Hipsley;
the latter is the youngest daughter of William Tuke, and a valuable minister.
We had meetings at Welwick by the seaside, at Oustwick, Hornsea, Bridlington, and Quay,
all largely attended, and much owned by the Lord`'s presence and power.
O that my constant dwelling may be with that life wherein ability
is received to do the work of an ambassador for Christ.
Only a short time since I was mostly shut up in silence from meeting to meeting;
no way was seen for the relief of my exercised spirit,
except by secret prayers to the Lord, and the spreading of my exercises before him; now,
at these last meetings, my heart has been enlarged in the Gospel,
and the stream thereof has flowed sweetly, to the refreshment of many.
Bless the Lord, O my soul, forevermore!

1st of Eighth month.
My dear friends from Hull left me this morning for their home,
and I have come to Scarborough, a place of great resort for sea-bathing,
at this season of the year.
In the castle here, G. Fox endured a long imprisonment,
because of his faithfulness to the testimony of Jesus;
great were his sufferings by cruel treatment.
Part of the old castle is yet standing;
the place in which G. Fox was shut up is still pointed out.

The next day, being First-day, though no notice of the meeting was extended,
it was much crowded, both morning and afternoon,
several clergymen and others were present,
but silence was my service among them in the forenoon;
in the evening I sat in like manner among them for a considerable time,
but towards the close of the meeting I had to deliver some very close doctrine.
Sometimes the Lord makes use of his poor servants as sharp threshing instruments;
some were present to whom such kind of plain dealing seemed to be necessary.

The succeeding week I had one or two meetings every day, some precious ones,
till I reached Whitby.
I had close, searching service among them in the morning, and was silent in the afternoon.
The love and pursuits of the world are like a canker in the soul.
On my way to this place I travelled a considerable distance over the moors.
It was on the edge of these black moors that several of our early valuable Friends resided,
and the spot on which Luke Cock lived is yet to be seen; a very rough one,
as to the outward, but from which a precious gem, polished by the Lord`'s hands,
went forth as an ambassador of Christ, to preach his glorious Gospel.

A few days ago I had a meeting in the forenoon at Pickering; on my way thence,
to a large village some miles distant,
where I had appointed a meeting to be held in the evening, we overtook a man, on foot,
going the same way.
A Friend, who accompanied me, being alone in his chaise invited him to take a seat by him.
He soon recognized him, as the person whom he had noticed in the preceding meeting,
much affected by the testimony of Truth that was proclaimed.
My friend`'s attention had been so attracted towards him,
that he tried to speak to him after meeting, but, in the crowd he had lost sight of him.
Now, the stranger, after alluding to that meeting, was melted into tears,
and then broke forth somewhat in this strain: "`What is the matter with me?
what is all this?
I have never known anything like it.
I was going towards Scarborough,
and on my way I felt an irresistible power turning me towards Pickering,
about six miles out of my way, a place where I had no business,
neither had I been there before.
Arriving there this morning, I heard of the meeting, and thought that I must attend it;
but I was so unwilling to do so, that after going to the door,
and looking into the meetinghouse, I tried to go back again,
but I felt constrained to go in and sit down.
O, I heard such doctrine there, delivered with such awfulness and power,
reaching my very heart, as I had never done before;
my secret actions and thoughts were set before me; a heavenly flame was kindled in me,
etc., etc.`"
Then he stated that at the conclusion of the meeting
he retired as speedily as possible into the fields,
out of sight, to give vent to his tears, and having heard of the meeting that evening,
he was now on his way to it.
It was another solemn meeting; blessed be the Lord forever and ever.

On my way from Whitby to Darlington, accompanied by George Sanders, I had,
as for some time past, two meetings nearly every day.
One at Guisborough, was held in a large meetinghouse of the dissenters,
so as to accommodate the inhabitants of the place, and,
a regiment of the local Militia being there, nearly all the soldiers,
with their officers, came to the meeting, and behaved with seriousness;
it was a solemn meeting.

24th of Eighth month.
I reached Newcastle, having on the way thereto very close and laborious services,
both in some of the meetings held for Friends,
and those among the inhabitants of several of the
populous towns in that section of the country,
especially in such towns as Durham, Bishop Auckland, etc.,
which were attended by many of the clergy, among whom,
and on whose account a great load of exercise was felt.

At Newcastle a great concern came upon me,
on account of the poor and labouring classes of the community, the colliers especially,
and those employed in furnaces and glass-houses,
many of whom endure great hardships and very severe privations.
The love of Christ constraining me,
I yielded to the prospect of duty to have meetings among them.
It was a laborious service, especially those meetings held in the evening,
and which were mostly out of doors,
for there were no places found large enough to accommodate the people.
Great solemnity was our covering, on those occasions;
under the Lord`'s power many hearts were greatly tendered.
Truly many of these persons manifested that, though poor in the world,
they are rich in faith.
I entered deeply into the sufferings of those,
who pass most of their days in working in the deep and damp coal mines.
Coming out of them after sunset, they took a very short time to refresh themselves,
so as to be at the meeting in due season.
Sometimes great destruction of life occurs in these mines,
by explosions from various causes; thus many are left widows, or fatherless.
It was but a few days before I was at one of the collieries,
that a large number were destroyed in one of the pits, by the foul air;
many of their widows and relatives attended the meeting I had in that neighbourhood;
it was a large and solemn one;
Divine love was in an extraordinary manner experienced to be over that assembly,
when many felt the oil of joy poured forth upon them,
in lieu of the mourning under which they had been bowed, and, for a while at least,
they exchanged their spirit of heaviness for the garment of praise.
The solemnity and stillness which prevailed in the
meeting continued over the people after it concluded;
on their way home, though in crowds, not a word was spoken,
but swollen hearts obtained vent by sighs, or tears.
My good and blessed Master was pleased, in a very particular manner,
to strengthen me for the special services of these days,--praised be His name!
After some of those large meetings, where I had been very much engaged for a long time,
in the open air, I felt greatly spent; yet in this state, late at night,
I had to ride from four to ten miles, back to Newcastle, to my very kind friends,
Hadwen and Margaret Bragg`'s, where I made my home,
and whose house was a place of true rest, to body and mind;
my blessed Lord and Master also refreshing me by his presence and Spirit,
in such a manner that I was prepared, the ensuing day,
to perform again the portion of work he required.

I returned to Darlington to attend the funeral of one of our Friends there,
John Backhouse`'s wife, Elizabeth, who died rather suddenly,
and left behind her a family of young children;
her brother-in-law William Backhouse was with me,
when the information of her decease reached us.

The ensuing day, accompanied by my beloved friend Edward Pease,
whose hospitable house at Darlington I have made my home, and a place of rest,
I returned to my field of arduous, but very interesting Gospel labours,
now among the lead mines, and the extensive hills and dales of Northumberland,
Yorkshire and Lancashire.
Many of these meetings were numerously attended.
Some were held in districts where it is not known that Friends had travelled before,
but where I found the people ready to hear, and, I believe,
some of them open to receive the testimony to the
Truth that the Lord gave me to bear among them.
Some of these people pass one half of their time at work in the bowels of the earth.
They were by some called a ferocious people, but now,
many of them manifested the quietness of the lamb.
Several of the meetings have been memorable seasons;
they should be held in grateful remembrance,
for it has been a very precious visitation of the Lord,
and an extension of his mercy to the people.
One of them was held on a First-day afternoon, at the heads of Wensley and Bishop-dale.
The notice of it had been spread some days before,
and people came from a distance of ten miles; several thousands attended.
The Lord`'s power was felt in an eminent manner over us,
and the everlasting Gospel was preached, to the tendering of many hearts.
The meeting held upwards of three hours,
but continued to the end in great stillness and solemnity.
It appears that the spot which had been chosen for it,
was a field belonging to the clergyman;
he did not object to the choice made by the people,
and it was the most suitable ground for the occasion.
In these dales and among the hills I have felt much
for the outward sufferings of the people;
there is a great scarcity of grain amongst them; wheat sold for 21s. to 22s., and oats,
their chief food, at 11s. 6d. to 12s. per bushel.
My horse had but poor fare, and I made as little do as I possibly could;
but the Lord has strengthened me every way, blessed and reverend is his name!
The business of many of the people in these dales is to knit woollen stockings.
They are so industrious that men, women and children, walking in the fields,
or on the highways, keep on knitting as fast as they can.

I went thence into Cumberland, Westmoreland, and into Yorkshire again,
visiting the meetings of Friends very generally,
and having many also among the inhabitants; for I feel myself a debtor unto all;
the Lord sends me to preach the Gospel unto all.
My daily baptisms are often very deep, in the prosecution of this work;
but daily also is it given me, through the tender mercy of my God and Saviour,
to rejoice in Him and to magnify his name.
None can feel more poor and destitute than I often do, yet, amidst the many trials,
doubts, and fears that have often encompassed me, what encouragement have I,
in faith and confidence, to rely on that mercy and power, which have, thus far,
in a remarkable manner, borne me up under all my exercises, afflictions, and besetments.
Day by day the Lord has so graciously extended fresh qualifications to his poor servant,
to suffer or perform the portion of service assigned, that truly I may say,

[verse]
____
"`In cares, and fears, and doubts,
Which oft assail my mind,
When they are left to thee, O Lord,
The best relief I find.`"
____

Near the conclusion of this part of his services he writes: "`I came to Undercliffe,
near Bradford, to my very valuable friend, Sarah Hustler,
one of the Lord`'s anointed servants,
to whom I am very closely united in the bonds of the Gospel.`"

--
