== Chapter XIX.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Departure from England
* Arrival in France
* Detention at Morlaix
* Religious Engagements in Paris.

Nearly two years had been spent in paying a general visit to Friends and others,
in Great Britain and Ireland,
and the time had arrived when Stephen Grellet felt it to be his duty to prepare for
carrying into effect his prospect of religious service on the continent of Europe.
After more than forty-five years`' enjoyment of the blessings of peace,
during which many meliorating agencies of a civil, moral,
and religious kind have been in operation,
it is not easy to realize the contrast between 1860 and 1813,
or fully to appreciate the characteristics of the latter period.
At that time there were neither railroads nor telegraphic wires;
the freedom of friendly intercourse between the different
States of Europe had long been interrupted;
superstition and infidelity, vice and wickedness had spread to an alarming extent;
religion was driven into seclusion,
and with many Christianity had become little more than an empty name;
international feuds and jealousies had rendered the system
of police and passport regulations exceedingly annoying,
and painfully restrictive to individual liberty; travelling was difficult,
and often dangerous.
Though Napoleon had been compelled to retire from Russia,
the French war was still raging with unabated, if not with increased fury,
and great excitement prevailed abroad.
To go forth, under such circumstances, and alone,
"`as an ambassador of peace to the nations,
while the sword bereaved on every hand,`" was no small trial of faith and faithfulness.
But Stephen Grellet knew Him in whom he had believed,
and doubted not the safe guidance of His Spirit: he had counted the cost,
and did not flinch in the day of trial;
the sacrifice which he had "`bound to the horns of the Altar,`" was not withdrawn.

The attendance of another Yearly Meeting, in London,
previous to entering upon such a service, was a matter of peculiar interest to him.
He had received the full sanction of his brethren in America to
his present undertaking in the service of the Gospel of Christ;
but, being now within the compass of another Yearly Meeting in a distant land,
he sought its unity and concurrence before he passed beyond its limits
to carry out his Gospel mission in some parts of the European continent.

[.embedded-content-document]
--

"`At the Yearly Meeting for Ministers and Elders, the 17th of Fifth month,
1813,`" he says,
"`I informed Friends that I apprehended the time had nearly
come for me to endeavour to pass over into France,
if practicable, to fulfill there, and in Germany, etc.,
whatever service the Lord may call for at my hands, be pleased to make way for, and,
through the assistance of his Divine grace, qualify me to perform.
I was aware of the trials and dangers that I should have to encounter,
in the unsettled state of those nations, during the bloody warfare they were engaged in,
and also of the difficulty of passing over from England to France;
but I also believed that if the Lord had indeed a service there for his poor servant,
he could make a way for me where there appeared to be none.
A great solemnity prevailed over the meeting,
during the consideration and deliberation on the important subject.
Many Friends expressed their tender sympathy and full unity,
believing that this was a work to which the great Head of the Church,
our Lord Jesus Christ, called me, in the service of his Gospel;
encouraging me to confide in the all-sufficiency of his Almighty power
to protect me and to enable me to lift up the standard of peace,
where that of war was unfurled.
They gave me a written testimonial of their unity with my religious movement,
recommending me to the kind and Christian sympathy
and regard of all those among whom I might come.

"`That Yearly Meeting was a solemn one.
It is very instructive and encouraging to see collected together,
so many dignified and valuable servants, Ministers and Elders, of both sexes;
many of them with grey hairs, bowed down with years, but erect in mind,
like pillars in the Lord`'s house that shall never go out.
There are also those of middle age, and dear young people, who evince that,
under the influence of the same Spirit who has rendered
their elders honourable in the church of Christ,
they are also preparing to fill up, in due time, the same stations with dignity.
My spirit has been greatly comforted in the Lord, on account of many of these.`"

--

[.offset]
After the conclusion of the Yearly Meeting in London, he continues:

[.embedded-content-document]
--

I now endeavoured to find out some way, whereby I might pass over to France;
the weight of the work the Lord has laid upon me in that land, pressing heavily.
Truly, in my measure, I can say, "`I have a baptism to be baptized with,
and how am I straitened till it be accomplished!`"
O Lord! enable thy poor servant to glorify thy excellent name, into whatever suffering,
or even death, thou mayest see meet that he should be introduced.
My friends have kindly undertaken to make inquiries, or be on the watch,
should any opportunity present for my getting over to the continent.

--

[.offset]
In the meantime, he was engaged in various religious services in and about the metropolis.

[.embedded-content-document]
--

During my tarriance in London, I was not idle.
A door for active Gospel labours was again opened
before me in that city and neighbourhood among Friends,
both in their meetings and many of their families,
especially those that were sick and afflicted.
I had also several meetings of a more public character, and visited again, with interest,
some of those institutions that were formed last winter for the relief and protection
of such as were desirous to flee from their vicious and dissolute practices.
In some of these visits the contriting power of Divine love was felt to be over all.
Many of the poor females are now evidently in a penitent state, and will, I trust,
be so thoroughly restored by the power of Divine grace,
as to become valuable members both of civil and religious society.

In company with Mary Dudley,
I visited the "`Found of Mercy,`" composed of the
most abandoned objects gathered out of the streets;
a much lower class indeed than those I had visited a few days before at the Penitentiary.
But the power of Divine grace can mollify the most obdurate heart.
There was great brokenness and contrition evinced among them,
during the course of the meeting that we had there; it was indeed an affecting scene.
For a while a general weeping and sobbing prevailed,
so that I had to cease speaking till they could compose themselves again into stillness.
May the Lord bless his work, and carry it on even to the salvation of their souls.

--

The efforts of Friends in London to make arrangements with the Lords of
the Admiralty for a safe passage to France had now been successful,
and, on the eve of his departure for his native land, Stephen Grellet writes:

[.embedded-content-document]
--

I have had two very solemn meetings with Friends, and some parting opportunities.
May the bread wherewith the Lord was pleased to feed my soul, be to me like that bread,
on the strength of which the prophet went forty days, even to Horeb.

The 14th instant I left London for Portsmouth,
my dear friend Rachel Smith taking me there in her carriage,
accompanied by her sister Mary Stacey,--George Stacey, Josiah Forster,
and Luke Howard following us in another carriage.
We found the Cartel ready to sail tomorrow, from Gosport.

15th. Several other Friends have come,
once more to see me and to bid me farewell in the Lord; after a solemn meeting together,
under the overshadowing of Divine love and power,
the spirit of prayer and supplication has in a contriting
manner been poured forth upon us,
and I have been strengthened afresh,
under the feeling of the bonds and afflictions that await me, to say from the very heart,
"`Thy will, O Lord, be done.`"

--

[.offset]
Stephen Grellet once more safely reached his native country.
On landing, he remarks:

[.embedded-content-document]
--

My dear friends accompanied me to Gosport on board the Cartel Brilliant,
bound for Morlaix, with forty-one French seamen or soldiers, prisoners of war,
discharged because of their incapacity for service, by ill health, etc.
We came over the British Channel the 18th, but on entering the river,
our vessel struck violently on a rock;
the general outcry on board was that the vessel was sinking.
I was then alone in the cabin,
where I sat down endeavouring to have my mind centred in
filial and reverent submission to the Lord`'s will,
should he order that instead of the service that
I apprehended I was called to on the European continent,
I should lay down my life in sight of the land of my nativity.
I was favoured to feel his Divine presence near,
and an assurance that his omnipotence would not permit
the loss of a single life on board by this event.
I felt deeply, however, for my fellow-passengers;
bitter was the lamentation of many of them, who from their very emaciated condition,
did not appear to have many days to live: "`What!`" they cried out,
with tears trickling down their furrowed cheeks, "`after so much suffering,
so many narrow escapes in the war, must we now perish within sight of beloved France,
and not be allowed quietly to go and die there?`"
By the return of the tide, however, the vessel got off the rocks,
and the next day we were favoured to land safely at Morlaix.
The officers of police proceeded immediately to a very strict
and minute examination of every part of my baggage and clothing,
and even of my person; the lining of my garments, the inner sole of my shoes;
everything about me underwent a close search, to see that I had no secreted papers.
That being finished, they inquired the object for which I came to France;
they perused the certificates given me by Friends in America and London,
they took notes of the whole and sent them to Paris, with my passports,
and told me I must wait for an answer from Paris.
O Lord!
I am in thy hands, by thy directions and the putting forth of thy Spirit,
I have come here;
now in submission and confidence I wait to see what thou wilt do for thy great name!
Thou canst remove mountains, and make a way even amidst the tumultuous waves of the sea.

I now endeavoured to wait and see if my blessed Lord and Master
had not some service for me to accomplish in this place,
for, possibly, for this very purpose, my detention here might be permitted.
I became acquainted with an old man, poor in this world, but rich in faith,
who appeared to be no stranger to the operations of the Spirit of Truth and vital religion.
He cannot read, but he evinces that the law of the Spirit of God is written in his heart,
and that his delight is to meditate thereon.
I was soon also introduced to other persons, among whom I found spiritual-mindedness.
One of these, a man 84 years of age, of much observation and learning,
manifests genuine piety.
I felt the more grateful on meeting with these, and other pious persons,
with whom I had some refreshing and instructive religious opportunities,
because it was then the time when the Papists celebrate
what they call "`the Feast of God.`"
Thousands of persons had come into the town from the country round, and,
accompanied by the priests, walked through the streets, carrying their crosses,
and the consecrated wafer, before which they threw flowers and leaves,
and burned abundance of incense.
My soul was deeply grieved at beholding such a display of ignorance and idolatry.
That evening, a considerable number of persons having come to my inn,
the excitement of the day prompted them to ascertain
my views respecting the display that had taken place,
which led them further to inquire into the principles of our religious Society.
This opened the way for unfolding to them the great truths of Christianity;
contrasting them with the pageantry they had seen displayed that day.
Consulting together on what I had said,
they appeared to come to the conclusion that our Society has discarded their many non-essentials,
and the inventions of priestcraft, adhering simply to what real religion requires,
whilst they have discarded real religion to give
place to those various inventions and superstitions.

Having felt my mind drawn in love towards my fellow-passengers from England,
who had gone to the hospital on their arrival here, I went to visit them,
accompanied by a pious person,
a friend of the Superior of the nuns who have the care of the hospital.
I found that several of the men had died shortly after they landed; others were very ill;
and some appeared to manifest tenderness of spirit
and gratitude for their escape from a watery grave.
Several of the nuns having gathered together with their Superior,
gave me an opportunity for serious communications on things
pertaining to the Redeemer`'s kingdom and vital Christianity.
Some of their minds were tender.
I was with them nearly two hours; at our parting,
they intimated that they had never before heard Christian doctrines so unfolded.

Finding that there were many English prisoners in the place,
chiefly taken from merchants`' vessels, I felt disposed to visit them,
if leave could be obtained.
This being given, they were collected together,
none going in with me but the sworn interpreter and his son,
to be witnesses on behalf of the police of what I should say among them.
I found there some piously-minded persons; the Lord`'s presence and power were near;
affliction, being shut up in prison, heavy losses of property, etc.,
had tended to prepare their hearts to receive the
consolations that the religion of Christ offers,
and gives to such as believe in it.
Many of them expressed their gratitude to the Lord for this visit of love, comfort,
and consolation to them.

I continued thus variously engaged in and about Morlaix till the 18th of Seventh month,
when my passport for Paris was handed me by the Commissary of Police.
I made immediate preparations for leaving.
My mind was bowed with reverence before the Lord, who, day by day,
had made way for me privately and more publicly to advocate the blessed cause of Truth,
and to exalt the Redeemer`'s name among a people,
many of whom are sunk in ignorance and superstition, and many, also, to my deep sorrow,
into great moral depravity.

On my way to Paris, I passed through several populous towns;
much distress of mind attended me; the people appear very generally sunk in darkness,
some amidst gross popish superstition,
others wrapt up in the world that lieth in wickedness,
and yet a heavy chastising rod continues to be over them;
but in their trouble they seek not, nor return to the Lord,
who alone can minister to their distress.
I have felt deeply for many of them.
O that their sufferings might be sanctified to them.
There is now a very active conscription throughout France,
to replace the army that has been destroyed in Russia.
My heart has often been sorely rent when hearing the bitter
lamentation of parents on parting with their last son,
some stating that five or more of their children had perished in the wars,
and now their last hope, in their advancing years, was taken away from them.
I was much affected also when meeting on the road companies of poor youths,
thirty to sixty fastened two and two to a long chain, and marched off to the army;
these being such as had manifested some reluctance in going there.
How numerous are the distresses caused by war!
The catalogue of sin, immorality, cruelty, bloodshed and misery that is entailed by it,
is beyond description.

--

On his arrival in Paris, he was pleased to meet his brother, Peter de Grellet,
with his wife and family; but in reference to the object of his mission,
"`very dull prospects were before him.`"
The police regulations were very strict; he was closely watched,
and had to exercise great care in all his movements.
His religious services were, to a great extent, of a private character.
His dress and deportment naturally led to inquiries,
and these not infrequently afforded opportunities for explaining
the Christian principles of the Society of Friends,
and of drawing attention to the great Truths of the Gospel upon which they are based.
He was generally treated with "`great civility;`" and amidst
all the discouragements which attended his solitary path,
he could make the grateful acknowledgment, "`The radiant beam of faith, now and then,
opens something like a crevice through the thick cloud which surrounds me.
It is a great thing to walk by faith, and not by sight,--to live by faith.`"
He proceeds:

[.embedded-content-document]
--

Soon after arriving in the capital of France, I went to see Pomier Rabans and Goep,
one a member of the Lutheran church, the other of the Reformed.
I had brought letters for them from England; they are both men of piety,
especially the last; Rabans`' father was eminently so;
during the great persecution against the Protestants,
he underwent great sufferings for his faithfulness to the testimony of Jesus,
and for many years continued a zealous preacher to the persecuted Protestants,
scattered over the mountains of the Cevennes.
The constraining power of Gospel love and the Spirit of
Christ were what he felt to be his call to the ministry,
and his labours, with his piety and faithfulness, were greatly blessed.
I heard many bear testimony to this, when I was on those mountains a few years since.
Through the medium of these two men,
I was brought to an acquaintance with several more of both denominations;
also with some Roman Catholics, of seeking minds,
who were dissatisfied with what they had discovered of Popish impositions and superstitions.
I have had very interesting conferences with them,
and also some private and more public religious opportunities, when,
sometimes most of the Protestant clergymen in Paris were present.
On one of these occasions they manifested an inclination to inquire
into the various principles maintained by the Society of Friends,
particularly respecting Divine worship, the Christian ministry,
the "`ordinances,`" faith in and salvation by our Lord Jesus Christ, etc.
I was helped of the Lord to open these various subjects
according to clear Scripture doctrine,
so that Truth brought conviction to their minds, and constrained their assent.
I told them,
it is of the greatest importance that our hearts should be converted to the Truth,
and not our understanding merely convinced;
for if the Truth reaches no further than the understanding,
it can never produce fruits unto eternal life.

I have visited some of their Protestant schools,
in which they begin to extend care toward the moral and religious education of the children.
I had religious opportunities in some of them,
when the children were brought into great tenderness.
At the close of one of these,
Goep appeared sensibly to feel the power of heavenly love that had been over us,
and he earnestly desired, in a few broken expressions,
that the children might treasure up,
and often recur to such an unlooked-for extension of Divine favour to them.
I have been particularly delighted in visiting their schools for girls,
set up under the special care and over-sight of females of rank,
whose minds having been brought under religious concern on their own account,
now feel the same for the rising generation.

Pious persons of inquiring minds come frequently to see me at my private lodgings;
some desiring to become better informed of our religious principles,
to whom I sometimes hand books on the subject;
several have requested to have Barclay`'s Apology, with which I can supply them,
having many copies both in French and Latin.
One of these was a venerable-looking old man, who, for some years,
was a priest at Cambray; but,
his mind being by degrees enlightened by the Spirit in the great truths of Christianity,
his convictions became such as to induce him totally to retire from those forms of worship,
and the ceremonies he had been in the practice of.
Among the things that at first brought strong conviction on his mind,
was the repetition from the pulpit or altar of that part of the Lord`'s prayer,
"`Forgive us our trespasses, as we forgive, etc.;`" when pronouncing the latter part,
he said, he knew it would be a lie for many present thus to say.
He appears to have acquired much experience in the school of Christ,
being a believer in the influences of the Divine Spirit; he says,
he sensibly feels its operations in his own soul, to teach him, lead him,
reprove or comfort him.

I have been visited also by a Jewess, the wife of a man of great wealth;
she has become convinced of the truths of Christianity,
but does not see her way to unite with any form of worship, or ceremonies, or creeds,
which do not harmonize with the pure and simple truths
that she finds unfolded in the Holy Scriptures.
She is in a very tender frame of mind,
and appeared to have a heart open to understand and receive
what I felt it my place to communicate to her.

The fact of my being in Paris becoming known, induces many to come and see me.
Some of these, now on a visit in Paris, reside in various parts of this country,
and as I hand them books treating of the great truths of Christianity,
in several languages,
a door is opened for the knowledge of our principles to become extensively diffused.
This great eagerness for some of our books,
has led me to see the necessity of having my stock of small tracts, especially,
increased; I have, therefore, prepared some of these for publication,
particularly the short account of our principles, etc.
It was necessary, before they could be printed,
that they should pass the examination and have the
approbation of the Inspector of the Press.
I had to go several times before the chief Inspector,
on account of that part in the Summary of our principles which relates to war.
They could not reconcile our upholding the peaceable
spirit that the religion of Christ inculcates,
with the warlike spirit that animates France, and their rulers.
I was also summoned to appear before the Commissary of Police;
he very closely and particularly inquired into every part of my life since I left France,
at the time of the French Revolution; my reasons for going to America;
my motives for becoming a member of the Society of Friends, and a minister among them;
where I had travelled in America, and in England, etc.;
what was my object in thus travelling, and whether I have any political one in view?
I have endeavoured to answer all these questions separately according to truth,
which has led to an exposition of many of our Christian principles,
and also to proclaim to him and others present, the redeeming love,
power and mercy of the Lord Jesus Christ.
In connection with this, my certificates were read,
and the good order of our Society before granting such was explained.
I stated, that in the course of my religious engagements in England,
visiting the prisons, poorhouses, etc.,
I had also meetings with the French prisoners of war,
and that it was on the same errand of love that I had now come to visit this nation;
that I had nothing to do with politics; my business as a servant of Jesus Christ,
the King eternal and immortal, the supreme Ruler in heaven and on earth,
was not to induce men to join this or that party,
but to invite them all to come to Christ, so that through his Divine mercy they might,
by his grace, become heirs of his kingdom, which stands in righteousness, peace,
and joy in the Holy Ghost,--a kingdom where no enmity prevails, and wars are not known;
glory to God in the highest, on earth peace, and good-will towards men,
being the song of its inhabitants.
This also led me to unfold the ground on which the testimonies
which our religious Society maintains against wars,
oaths, slavery, etc. are based.

After I had answered all these interrogations, and he had finished writing my replies,
he made me sign the paper.
He then took down from the shelves, on which were a great many boxes,
alphabetically arranged, one,
out of which he drew papers in which were recorded the time when I left France,
as an emigrant, with others of the nobility,
together with various circumstances attending;
also a statement of the time of my last visit to France, and of my engagements;
having compared all these with the answers I had now given to some of the same particulars,
he said, "`It was all correct.`"
And then he took the whole to the Minister of Police,
who appeared much pleased with the perusal of my certificates,
and the care and good order maintained by our religious Society, not over ministers only,
but over our members generally, especially over our poor,
so that they never become chargeable to the public,
whilst we contribute equally with our fellow-citizens to
the support of the poor of the community.
He had received from the Inspector of the Press a
copy of the "`Short account of our principles,
discipline, and doctrine, etc.,`" which he had perused with care,
before the printer was allowed to furnish me with any copy of the work.
If they have placed the whole of these interrogatories thus signed by me,
with the other documents they had respecting me, since I first left France,
they have quite a history of my life thus far;
and if they extend the same care and trouble towards others,
how voluminous must be the accounts collected.
I feelingly remembered whilst in Paris, my concern to come here,
during my visit to France a few years since,
and the great exercise I felt on my mind on account of Buonaparte,
but not being permitted to go then, I left France under much distress;
and now that I am here, I have no wish at all to see him, were he now in Paris,
and access to him easy to be obtained.
The day of the Lord`'s visitation that I then felt to be extended towards him,
appears to me to have passed away from him.

Here, in France,
nothing is heard of what transpires in Germany and Spain
but the splendid victories of the Emperor`'s armies,
and the multitude slain by them; their own losses are stated to be very small,
and yet it is well known that fresh conscriptions are continually called forth;
but such is the strictness of the police, that no true accounts are published.

Apprehending that the time of my departure from Paris was at hand,
I endeavored to make preparation for it, by obtaining the requisite passports,
and by having also some private and more public religious opportunities,
with those pious persons with whom I have become acquainted.
As they move in different ranks in life,
and also belong to separate religious professions, Papists, Protestants, etc.,
I have been obliged to have separate meetings among them.
These were held in private houses, and it would have been very difficult,
if not impossible, to have had those persons promiscuously gathered together.
Some of these parting opportunities have been solemn and tendering;
but I wish I could see greater depth in many, a fuller redemption from the world,
and more love to the dear Redeemer,
manifested by acts of obedience to his well-known will.
I have been mournfully affected in finding so few Bibles among them,
even among the Protestants; but there is a prospect that an edition of the New Testament,
put forth by Francis Leo, will soon be out of the press; it is now being stereotyped.
I have succeeded, however, through Soulier,
an aged and pious Protestant with whom I became acquainted
in the south of France a few years ago,
to discover in an upper room, a parcel of Bibles in sheets, of Martin`'s edition,
printed some years since, but which have remained neglected.
I have obtained about two hundred of them, had them bound,
and sent in separate parcels to various parts,
through which I expect to travel on my way southward.
I hope that now such an interest begins to be awakened respecting the Scriptures,
that the other copies, yet in sheets, will soon be put in a way for useful circulation.

--
