== Chapter XX.

Second Visit to Europe

Departure from Paris--Visit to Limoges--Brives--His
Mother--Montauban--Toulouse--Albt--Rodez--Montpellier--Congenies, etc.

Leaving Paris, he proceeded to Limoges, and the scenes of his earlier days;
and having spent some time amongst his relatives in those parts,
he extended his travels to the south of France,
to re-visit the little community who profess with Friends in Languedoc.
Of this journey the following particulars are given:

I left Paris the 15th of the Eighth month, 1813.
The first place where I made a short tarriance was Orleans.
I met with few with whom my spirit could mingle.
Profaneness and superstition are very prevalent; yet,
there may be piously-minded and retired ones, whom the Lord knows,
though I am ignorant of them.
The prophet thought that he was left alone in Israel,
nevertheless there were seven thousand who remained faithful to the Lord.

I arrived at Limoges the 20th of the Eighth month.
Many of my relatives,
and of those pious persons with whom I had often mingled when here last,
soon came to see me.
I was comforted on finding that religious sensibility and
tenderness are still the clothing of some of their minds.
Among those to whom I paid an early visit were two cousins of mine, who,
though no longer nuns in their convent--for during the Revolution those establishments
were sold out by the government--still adhere to the strict rules of their order.
Though, in many respects, under the yoke of superstition,
they nevertheless possess genuine piety,
and love the Lord Jesus Christ in sincerity and truth.
I had a long and satisfactory opportunity with them.
We had continued some time together in sweet fellowship of spirit;
their minds were brought into great tenderness, whilst I directed them to "`Jesus Christ,
in us the hope of Glory,`" the Minister of the sanctuary,
our High Priest and only Saviour, through whom alone forgiveness of sin can be obtained,
etc., when two of their priests came in; one was the Grand Vicar of the Bishop, and,
seeing that I was not a papist, he soon began to proclaim damnation upon me,
and upon all those who are out of the pale of the Romish Church, where only, said he,
by confession to the priests and the pronouncing of their absolution,
sin could be remitted; repentance and contrition because of our sins, he added,
were not necessary--attrition alone, with the priest`'s absolution sufficed;
forms of prayer, uttered with the lip, though in language not understood,
or in which the heart was not, were nevertheless prayers acceptable to God;
so was also the prostration of the body before their altars,
and the images of the Virgin Mary, saints, etc.,
though the heart might be lifted up in pride or vanity; he said,
though a priest were ever so vicious in his life and conversation, yet,
in virtue of his office, having received at his ordination the keys of Heaven,
he had power to retain or forgive sin at his pleasure,
and whatever he says in his priestly capacity ought
to be received and believed as the word of Christ,
whom he represents.
The poor man went on to utter so many absurdities
that the nuns seemed to be astonished at him.
I found it in vain to say much to him,
for on my attempting to do so he gave way to such passion
as seemed to me would only lead him to add sin to sin.
However absurd were that priest`'s assertions,
I have heard many others advancing the same.
I have frequently heard virtuous and pious females state what a great trial it
was to them to have to believe that it was their indispensable duty to confess,
and still more so when they know that the priest to whom
they go to do so is a vicious and immoral man.
It is no wonder that so many individuals should become infidels,
as is the case in many parts of the Pope`'s dominions.
One of these blind guides told me "`that though a man should so fully love God and his
neighbour as to be able to act according to whatever the Gospel of Christ requires,
yet if he did not go to confess he would be lost forever.`"

I had several religious opportunities in families,
and sometimes thirty or fifty persons collected together at private houses;
public meetings, in a country like this, could not be held,
neither would the people understand what they are called together for.
There are here some very tender spirits.
They are all Roman Catholics, and there is not perhaps one Protestant within fifty miles.
I visited also several small towns and villages near Limoges,
and had some satisfaction in those visits; among others one to a relative of mine,
who is the Curate of Verneuil;
but generally my mind has been under much sadness
in beholding what gross darkness covers the people,
and how with it, vice and corruption prevail.
These, I think, have of late greatly increased.
The few soldiers who have escaped being slain in the wars and have
returned home have brought with them abundance of vice,
which like subtle poison is diffused from them to those around them.

The Mayor here, having been my companion in early life,
manifests much kindness towards me, and gives me free admittance to the prisons,
poor-houses, etc., which I have visited.
I distributed in them some copies of the Scriptures, which were received with gratitude.
In one of the prisons I had all the prisoners collected in the yard; some of them,
under the sensible feeling that the Redeemer`'s love was extended to them,
were very tender in spirit, which they evinced by their tears;
visits like these they had never known, said they, nor heard of before.
The like sensibility was prevalent in the hospital, and, in a precious manner,
among the nuns who have the care of it; a laborious charge it is.
They are mostly young women of good families,
who from benevolent and pious motives devote themselves wholly to the sick and aged.

Here, as in Paris,
I have had several private visits from pious individuals dissatisfied
with the various forms and ceremonies with which pure religion is veiled,
and the very performance of which sap the precious life.
One of those was a priest in high office in their church;
he appeared under strong convictions,
but how hard it is for a man to be willing to be accounted a fool
by those who have hitherto considered him an oracle of God!
Two others were nuns,
among whom there appeared a greater disposition to receive the Truth in its simplicity.

On the 28th I had a solemn and tender parting meeting with my relatives,
and those pious persons here with whom I have been intimately acquainted.
It was a baptizing season; the love of Christ was felt sweetly to flow,
and they were earnestly pressed henceforth to evince that they love Him,
not by words only, but by deeds.

Leaving the place of his nativity, he reached Brives, the residence of his mother,
late in the evening of the 29th of Eighth month.
He remarks:

I am much comforted in being permitted to be again with my beloved aged mother, who,
since I was here, has, under the teachings of the grace of God,
made further advances in vital Christianity;
the scales of superstition that were once upon her eyes have now fallen off;
her hope and confidence are no longer in the priests, or the Pope,
but in the Lord Jesus Christ alone; her delight also is to read the Scriptures,
a copy of which (in French) I left with her on my previous visit.
Among the pious persons I visited soon after my coming here were the nuns of the hospital,
with whom I had such precious seasons of the Lord`'s favour six years ago.
Their aged and venerable Superior continued in the greenness of the Divine life,
manifesting Christian meekness and humility.
Some of the nuns accompanied me through the several wards of the hospital,
where various opportunities presented for religious communications,
under feelings of Gospel love; some of these were with the inmates of the several wards,
collected together; others were more private, near their sick-beds.
There was an entrance for the word preached in the hearts of many of the poor sufferers;
I left some Bibles for their perusal.
On returning to the aged Superior, I found that, Cornelius-like,
she wished that her household should share with her
in the consolations she hoped for from my visit;
she therefore had all the nuns collected;
we were soon brought into solemn silence before the Lord,
who baptized us together by the one Spirit into the one body.
Then was my heart enlarged among them in the love of Christ,
who was preached to them as the only Saviour and the Bread of life;
they were directed to enter into the temple of their hearts, sanctified by the Spirit,
and there to offer up to God the worship well pleasing
in His sight in spirit and in truth.
That baptism which constitutes the new creature was set before them,
and also the Bread of Life, on which this new-born child of God lives.
As he is not born of man, nor of the will of man, but of God,
so none of the doings or workings of man,
can minister living bread to him but Christ alone, even through faith in His name.
The next day a nun from another religious order, who sometimes visited at my mother`'s,
accompanied me to some of the prisons, which she attends once every week.
At the close of two of the religious opportunities I had during that visit,
and which were peculiarly solemn, to the contriting of many of the prisoners, that nun,
under much feeling,
entreated them to lay up in their hearts this visitation of Christ`'s love to them,
who was revealing Himself to seek and to save such as are lost.
There was something particularly pleasing to my mind thus to hear a nun, as my co-worker,
directing sinners to Christ as the only hope of salvation.

Shortly after this I received a message from the nuns stating that one of their priests,
on coming to the hospital, had seen the copies of the Scriptures I had left with them,
and had manifested great displeasure, finding fault with them for having received them,
and had taken them away; "`but,`" said the nuns,
"`he has not seen the other books and tracts you have given us,
and we shall take great care to keep them out of
his sight;`" among these were "`No Cross,
no Crown,`" and some smaller works of William Penn,
a short account of our Christian principles,
a selection of the memorials of deceased Friends, etc., etc., all in French.

I had several religious opportunities with persons of seeking minds,
some of whom appear much weaned from Popery; one of these,
a nephew of the late Bishop of Chartres, and a former close acquaintance of mine,
came several miles to see me.
"`I am convinced,`" said he, "`that it is only in retirement, in the school of Christ,
and under the sensible influences of his Divine Spirit,
that we can become convinced of the real truths of Christianity,
and by the grace of God be enabled to put them in practice.`"

Amidst these engagements at Brives,
Stephen Grellet`'s mind was brought into much exercise on
account of the horrors of war which came to his ears,
and he writes in a letter to a friend, 5th of Ninth month:

Much heaviness attends me; the whole earth,
all the elements seem in commotion--"`wars and rumors of wars.`"
How long ere the sword be again put into the scabbard, to be used no more?
The Lord sends me an ambassador of peace to the nations,
but the sword everywhere bereaveth.
Did not the Lord, by his grace and good Spirit,
sustain my often drooping and discouraged mind,
I must yield to the weight of attending distress.
Will He not cause the cheering beams of His sun of
righteousness to dart out of the clouds of gloominess?
"`If the dead rise not,`" says the Apostle, "`why are we baptized for the dead?`"
So, then, may not some of us say,
"`if there is no hope to see the end of these scenes of human misery,
anguish and distress,
why are we brought into the wrestling state?--why do we tread the agonizing path?`"
O, Lord, hasten the time when the end of thy chastenings over the nations shall be seen;
and they, under Thy judgments, shall learn righteousness!
I must, however, say,
that He who was with His servants in their various and fiery
trials in ancient days is with me in this land,
as He has been in my former pilgrimages.
He very graciously makes good His promise: "`I will never leave thee, nor forsake thee.`"
He keeps my mind, in a good degree, stayed upon Him,
so that though the sea roar and dash its waves, His everlasting arm is near,
my soul humbly and gratefully acknowledges.
Most abundantly I can--I ought to sing His praise, to proclaim His wondrous doings.

His memoranda proceed:

I left Brives the 7th of Ninth month for Toulouse,
stopping on my way to visit some piously-inclined persons at Cassades,
Cahors and Montauban.
At the last place I was much distressed on finding to what an extent the
principles of infidelity have prevailed in the Protestant college there;
several of the principal professors openly teach and preach doctrines repugnant to Christianity;
so that Popish superstition on the one hand, and Infidelity on the other,
threaten to destroy all sense of true religion.
There are a few, nevertheless,
preserved even in this Sardis to whom the name of Jesus is precious.
In the college itself, Bonard, one of the professors,
with whom I had been acquainted on my preceding visit to France,
testifies boldly that Jesus is the Christ,
and that there is no salvation by any other name than His.
There are also a few visited and pious individuals who resort to him,
and who show by their life and conversation,
that there is a manifest difference between those who know, love,
and endeavour to serve the Lord Jesus Christ, and those who love and serve Him not.

I came to Toulouse on the 10th, and, amidst very deep conflicts,
I was comforted among a few precious spirits, visited servants of the Lord.
It is beyond comprehension how man can be capable
of giving way to such an excess of depravity,
mirth and folly, in the midst of so much suffering and distress,
as there is publicly exhibited in this city.
It was but a few days since, that, after a battle between the English and French armies,
such a number of wounded soldiers were brought in
that the streets were strewed with these,
till places to remove them to were prepared; and so numerous were the amputations that,
in several parts of the city, piles of legs and arms, like heaps of wood,
were to be seen; nevertheless, in the sight of all this, there are public diversions,
and great wantonness!
How terrible is the scourge of war!
What misery and sin are annexed to it!
My soul is exceedingly sorrowful, my eyes and ears also deeply affect my heart.

The 12th of the month I came to Alby; this place was formerly inhabited by Protestants,
who suffered so greatly during their severe persecution
that it appears as if they had been totally destroyed;
now Popish darkness and irreligion seem to have an undisturbed reign.
I felt much distress in that place, from which I proceeded to Rodez,
where I remained some days.
I again found there a little door opened for religious intercourse
with some Roman Catholics of tender and pious spirits,
acquainted with vital Christianity.
Here, also, I visited the prisons and the hospital,
in all which I found individuals whose minds had been softened under their afflictions,
and who were thus prepared to hear of Jesus the Saviour of penitent sinners,
and the Comforter of the afflicted who flee to Him for consolation;
great brokenness of heart, accompanied with many tears,
was manifested by many of these poor sufferers, at the several meetings I had among them.
In the prisons I had also the company of some other persons,
who appeared to partake of the visitations of the dear Redeemer`'s love,
and the offers of His mercy, that were graciously extended.
In the hospital, several of the nuns accompanied me;
they appeared to feel great interest in my religious movements in the place, having,
of their own accord,
collected together those of the inmates who were able in some of the wards.
It was remarkable to behold the silence and solemnity prevailing on such
occasions among persons totally unacquainted with our religious Society,
and our views and practices connected with the holding of our meetings for Divine worship.
I had also a precious, baptizing season among the nuns assembled for the purpose;
I am persuaded that many of them are very near the kingdom of God,
and they might become bright and shining ornaments to the Church of Christ,
were it not for the ascendency that the priests, their blind guides,
have obtained over them.
I have been told here that the priests at Brives, on hearing that I had left the place,
lifted up their hands in token of joy, because my presence,
which tended to the overthrow of their superstitious fabric, was no longer among them.

I have visited in a prison a considerable number of young conscripts, called refractory,
waiting to be sent in chains to the army.
I found great openness in the soldiers, who have them under guard, and in their captain,
who allowed me to have a religious opportunity with them,
he and the guards also being present.
It was a very tendering time; these poor young men sobbed aloud;
I had no other consolations to offer them but such as the Gospel of Christ affords,
and these are sure.
I earnestly entreated them to believe in the Lord Jesus Christ,
who could sanctify all their afflictions,
or make a way for their release in a manner they did not know.

At Rodez he had much satisfaction in being with his brothers, Peter and Joseph.
The former held the post of Receiver-General of that district,
and had returned with his family from Paris, a little before his own arrival.
His mother also had joined the circle of relatives.
Towards the conclusion of his religious engagements in that neighbourhood, he remarks,
in a letter to a friend, Ninth month, 20th:

I requested a religious opportunity with my brothers and their families,
and my mother and uncle, which was readily granted.
The Lord has very mercifully owned us to the contriting of many, if not all our hearts.
It is a day loudly calling for gratitude and praise,
which have been offered on bended knees.
It was a debt I owed--the Lord has helped me to discharge it.
My dear connections have never been more precious to me,
and I believe the Truth has never been more endeared to them.

I have last night felt fresh pressure on my mind,
which has been brought on by sympathy with suffering humanity,
particularly on account of the bloody scenes of war.
Ah! what distress! what horrors!
My very heart is broken--my bones and my flesh are bruised.
Is it to prepare me to hear of new scenes of devastation and cruelty?
O Lord! when will the end of all this be?
How long shall man be to man his most cruel tormentor?

Leaving Rodez at ten o`'clock in the evening of the 20th,
he travelled day and night over a mountainous and very rough country,
and reached Montpellier on the 23rd of Ninth month.
Resuming his memoranda, he says:

It was a trying parting from my dear mother; it may prove a final one.
I parted from her with a grateful heart,
believing that she has received the Truth in the love of it,
and that all her comfort is in walking in it,
though she may continue in the observance of some externals.

At Montpellier I found my dear friend, Louis Majolier, waiting for me.
He had come from Congenies to meet me,
and began to be under some discouragement at my non-appearance;
but our meeting at last was grateful to us both.
Some of the pious families I am acquainted with at this place I found
under heavy affliction on account of the death of their sons in the army,
and now, others of their children are being marched off also to the place of slaughter,
or perhaps worse--to the sink of vice and immorality.
Our meeting, both in private and collectively in a religious capacity, was solemn.
The Lord is near and very gracious to the contrite in heart and the broken-spirited ones.

Accompanied by my beloved friend, Louis Majolier,
I came to his hospitable house at Congenies on the 25th. The next day, being First-day,
I had two meetings among them, which were numerously attended;
Friends and others had some expectation that I should be with them that day,
and on that account they had come to Congenies from
ten different towns or villages many miles distant.
The overshadowing of the Father`'s love, and the melting influence of his Divine Spirit,
were felt in such a powerful manner that the whole assembly, even the children,
were broken into tears.
The following day I had another very interesting meeting:
one of their members who resides on the Cevennes mountains, above St. Hypolite,
having previously, according to the good order of our Society,
obtained the approbation of Friends for his proceeding
in marriage with a young woman of Congenies,
the marriage was solemnized that day,
which drew to the meeting a large number of persons
both from the Protestants and the Roman Catholics,
among whom the Lord and his Truth were exalted.

Louis Majolier accompanied me after this towards the Cevennes, having two,
and sometimes three meetings a day on our way thereto,
and some of them were very mercifully owned by the Lord`'s presence.
To one of the meetings in the mountains the people came from miles distant;
the Mayor and the chief magistrates were among the number present,
as well as the principal inhabitants.
The testimony of Truth appeared to be received with gladness, and the Gospel,
like a refreshing shower upon the tender grass, distilled down among them.
After meeting many of their old people, bathed in tears, taking me in their arms,
desired that the Lord`'s blessing might rest upon me,
and upon the labour of love bestowed that day upon them.
The inhabitants of these mountains are generally Protestants.

At St. Hypolite, where six years ago I had a memorable meeting,
I had now another highly-favoured one; the Commissary of Police,
who had been so rude before, now treated me with all kindness and civility.
He took upon himself to have a place prepared for a meeting that I appointed;
he made choice of a very spacious, convenient building, had it properly seated,
and during the meeting he took his seat by me.
The place was crowded with Protestants and Papists.
Though nearly all unacquainted with our religious Society,
great silence and solemnity prevailed over that numerous
company from the first of our coming together,
and it proved to be a season of peculiar visitation from the Lord,
by the extension of his love towards the people;
many of them appeared to be sensible of it.
O that fruits may be brought forth to the Lord`'s praise and glory!
At the close of the meeting, an old Popish priest, residing in that town,
came to me and expressed his gratitude for the favour
and mercy that the Lord had granted us that day,
and added,
"`that since the Lord Jesus Christ had thus chosen me for his instrument
to preach his glorious Gospel of life and salvation,
I should go and proclaim it throughout all their towns and villages,
seeing what great good might be done thereby.`"
I stated in a few words what the duty of a servant of the
Lord is--that he is not to direct his own steps,
but in simplicity and faithfulness to go only where the Lord sends him,
and to speak that only which he is commissioned to do.
To which the old man with tenderness assented.
The two ministers of the Protestant Church came to me at my lodgings.
Gautier, who had been with me before,
continues to evince that the truth is precious to him.

I returned to Congenies the 5th of Tenth month,
when my attention and labours were very particularly directed
towards those in religious profession with me;
I hope they have not been unavailing.
I had also meetings among the inhabitants of Congenies,
and in the towns and villages thereabouts,
where the Protestants have generally manifested much openness;
but in several places the Popish priests now try
to prevent their people from coming to our meetings;
many of them have nevertheless attended.
Some of the meetings in this southern part of France have been held out of doors,
as frequently no place sufficiently large to accommodate the people could be obtained.
It has been therefore a laborious service to me,
especially as I am mostly obliged to walk from one place to another;
but my good and gracious Master has helped me every way, blessed and holy is His name.

The 9th I went to St. Gilles on foot; this gave me an opportunity for silently musing,
and pouring forth my soul before the Lord;
my heart was contrited under a grateful sense of
the help and strength whereby he has enabled me,
his poor and feeble servant,
to proceed in the great work for which he has sent me into these nations,
and in which I have been engaged single-handed.
Thus far, way has been made for me in a manner extraordinary to myself;
for though in several instances I have heard of threats made against me by men in power,
yet to this day I have had no interruption in my religious movements.
But the weight of the further services that I have to perform at times overwhelms me;
O Lord! in Thee only is my refuge and strength!

I have found those professing with us at St. Gilles in a very low state;
in some of them the spark of Divine life is nearly extinguished;
my visits to their several families have been attended with close searching of heart;
with some of them it would appear as if the fresh invitations of the Redeemer`'s love,
now extended, might, if they be faithful, renew them again,
so as to hold their religious meetings with more propriety and advantage.
There are, nevertheless, two or three here that have kept their integrity in the Truth;
one of them, Francis Brun, has a precious gift in the ministry.
Several of the meetings I have had with the inhabitants have been to some satisfaction,
but my soul has deeply lamented over many of them.

The 12th I had a more satisfactory meeting than any of the preceding ones in this place;
some manifested much tenderness,
and appeared to be in earnest in their desire to
walk more consistently with their Christian profession.
I had appointed that evening a meeting at Nismes;
notice of it was sent there by a pious Moravian, named Jalabert Blanc,
who also undertook to have proper information of it given to pious persons in that city.
As I could not procure any conveyance to take me to Nismes,
I had to perform that journey also on foot,
which prevented me from getting there as early as had been anticipated;
finding on my arrival that the hour at which the meeting was appointed had come,
I went directly to the house.
About eighty persons, some of them Moravians, soon collected;
silence and great solemnity prevailed.
The blessed Redeemer rendered us partakers of his gracious
promise to the two or three gathered together in his name.
Whilst we were thus assembled,
two officers of the Gensdarmerie (police) with some
soldiers came in and took their seats;
the meeting continued some time in solemn silence before the Lord;
many present were worshipping the Father of spirits in spirit and in truth.
Some of them even evinced that they were prepared to offer
unto the Lord the sacrifices of a broken heart,
and of a contrite spirit.
He gave me a solemn testimony to bear to his blessed Truth,
and to the great love of God to us through his beloved Son Jesus Christ,
our blessed Redeemer.
Towards the close of the meeting solemn prayers and supplications
were offered up on bended knees to the Lord God and the Lamb,
through the Spirit.
The whole assembly were broken into tears, and with the most tender affection,
took their leave of me.
The officers of police came with the others to shake hands with me,
having also tears in their eyes.
After I had come into the street they followed me, and one of them,
who was the Lieutenant of the gensdarmes, drew very politely towards me,
and after making several apologies,
told me they had been sent by the Prefect of the Department to apprehend me,
and had orders to bring me before him.
They stated that they had been in search of me for
some days--had been as far as the Cevennes,
but that I was gone from the several places I had been at before their arrival there;
at last, having heard that I was at St. Gilles, they had rode all night to meet me there,
and had been much disappointed on finding I had left that place also;
they hoped to have overtaken me on the road, but being again disappointed,
were going to make their report, when hearing of the meeting,
they thought they might there hear of, or perhaps find me.
Now they could bless the Lord for having permitted them to attend such a meeting,
and so sensibly to feel the visitation of His redeeming love,
adding how trying it was therefore to them to be
under the necessity to take me to the Prefect.
I encouraged them to do their duty, and said that I was ready to follow them immediately.
They were somewhat reluctant to proceed before giving
me an opportunity of taking some refreshment,
for they saw how exhausted I was after the exercise of such a meeting,
and the fatigue I had endured from walking all the way from St. Gilles,
after a meeting there;
but as it was then past nine o`'clock it was thought
best not to put off going to the Prefect.
He, at first, gave me a rough reception,
because of the many and large meetings he had been informed I had had through the country,
and threatened what should be done to me, but that for the present I must go to prison,
and wait till he could send to Paris a statement of the whole case.
I told him that the Minister of Police was not ignorant of those meetings,
for I bad given him in Paris a full statement of the nature of
my religious engagements in other places where I had been,
and what I proposed to do as I travelled throngh the nation, etc.
The Prefect, after a while,
took the officer aside to inquire of him what had passed in the meeting.
I heard the officer give him a pretty accurate short statement of it,
concluding with these words: "`I have never heard any one speak in such a manner before;
the whole assembly was melted into tears.`"
After further consultation, I was told that I might go for the night to my hotel,
but must return next morning at nine o`'clock. It was pretty late by that time,
but though spent in body, my spirit was refreshed of the Lord;
the joys of whose presence, wherein there is life,
had been in a gracious manner dispensed to me that day,
and I felt great peace in resigning myself to His will,
whatever He might permit to be done unto me.
I went to the Prefect the next morning at the time desired.
I was now received with more civility;
many inquiries were even made with apparent interest into the nature
of the Christian testimonies of our religious Society,
and of my object in having such meetings "`to which,`" he said,
"`the people are flocking in such crowds.`"
On finally parting, he manifested good will towards me.

Having thus narrowly escaped the walls of a prison at Nismes,
Stephen Grellet took a short journey to Montpellier,
and had several religious interviews with pious individuals and families there,
"`the Lord refreshing them together.`"
From this little digression he returned to Congenies,
to mingle once more in Christian sympathy and fellowship
with those of his own religious profession in that neighborhood,
before leaving the South of France to pursue his mission elsewhere.
During his late visit, he had "`found among them the same tenderness of spirit as before;
but the same weakness also abounded.`"
His heart had been again enlarged among them in the love of the Gospel,
and he had labored abundantly, both publicly and from house to house,
to establish them in the Truth as it is in Jesus,
and "`to set in order the things that were wanting.`"
He was now about to take his final leave of them.
The day before his departure "`Friends from different parts met together,`" and,
after a meeting for divine worship in the morning,
and an interesting conference on the affairs of their little community in the afternoon,
"`their hearts overflowed with gratitude towards their Heavenly Father,
thus mindful of them.`"
"`Mine also,`" he remarks, "`has overflowed,
in that the Lord has given us proofs that he has not forsaken
that people--that he has yet a seed among them,
which he cherishes and visits.`"
The next day, 18th of Tenth month, he adds:--

This morning I have taken a solemn farewell of Friends who have come generally
to Majolier`'s. The Lord`'s power has broken in upon us in a remarkable manner.
A most solemn silence covered us.
Truly the spirit of prayer and thanksgiving was upon us.
It is indeed the end that crowns all.
I had at last to tear myself from the arms of these dear friends,
some of them following us even to Nismes.
