== Chapter XXI.

Second Visit to Europe

Marseilles--Nice--Genoa--Turin--Geneva--Lausanne--Berne--Zurich--St. Gallen

Quitting Languedoc and the Cevennes, Stephen Grellet went to Marseilles.
Thence he "`essayed`" to go into Italy,
but not being "`suffered`" to penetrate that country further than Genoa, he proceeded,
by way of Turin and Chambery, to Geneva, and some of the principal towns of Switzerland.
His services as a minister of the Gospel, during this journey,
were chiefly confined to private interviews with pious individuals or families,
and little companies of persons whose hearts had been directed
"`into the love of God and the patient waiting for Christ.`"
Interesting particulars of this visit are given in his memoranda.

Coming through Avignon and Aix, I paid some visits, particularly at the latter place,
to pious Roman Catholics, and reached Marseilles on the 23rd of Tenth month, 1813.
Here I was again very kindly received by Malvezin, brother-in-law to Mollet,
from whom I experienced genuine hospitality.

The little company who, since my visit to this place six years ago,
have continued to meet together for Divine worship,
have received me with much cordiality.
We were several times refreshed together in our little select meeting.
The Lord also very graciously owned some more public meetings I have had here,
and visits paid in the love of Christ to several families,
where the bread that He gave me to hand to them was blessed by Him.

Stephen Grellet had come to Marseilles with the prospect of going to Italy;
and he was now brought into great conflict in looking
at the accomplishment of this service.
It was a time of war; he was alone; the roads were much infested with robbers;
and he was not easy to join the caravans of ordinary travellers,
accompanied by armed men.
But "`offering up his life and all to the Lord,`"
he was afresh animated to put his trust in Him,
and to be faithful in his service.
His "`path of religious duty appeared clear towards Italy,`" but he felt
restrained from taking the accustomed route through Mont Cenis, etc.
Without going a long distance round, there was no other course,
except a very difficult one over precipitous mountains, by way of Nice.
"`After deep conflict,
and earnestly praying to the Lord for right direction,`" he believed
it right to choose the latter apparently impassable road:
"`assured that the Lord could carry him through all, he reverently bowed before Him, and,
trusting in his Divine guidance,`" he left Marseilles on the 30th of Tenth month,
and reached Nice in safety.
There he thus continues his journal:

At this place my distress has been great.
My heart is deeply affected by all I hear and see.
I do not know when I have seen so many Romish Priests together as here,
or so much levity as is exhibited by that class of men.
They have been celebrating "`The Feast of the Dead,`"
and truly they appear dead to God and his truth.
On the other hand,
I hear of the numerous bands of brigands that frequent the road I am going to travel.
But, surely, the Lord is a refuge and strength in time of trouble!
Blessed be his holy name!
I have found him so again at this time.
My faith in his gracious promise, that through fire and water he would be with me,
has been renewed,
and therein strength has been given again to commit myself and my all to Him.

The first place I came to was Mentone,
a very beautiful little town at the foot of the Alps,
whose summits are covered with perpetual snow.
The narrow valley in which the town lies is by the side of the Mediterranean Sea.
The heat of the weather would be unbearable,
were it not that the air is very pleasantly tempered by the ice and snow above.
The orange trees are abundant in that valley; they grow to the size of our apple trees,
and are planted like our orchards; they are continually blossoming and bearing fruit,
which is of the best quality.

I had a letter of introduction given me by Kothen, at Marseilles, for Maurice Berea,
a friend of his, a pious Roman Catholic, who resides at his country-seat, near the town.
I went to see him, and met at his house several persons who, like him and his wife,
are piously-minded.
To be in company with such, especially after what I had suffered at Nice,
on account of the gross darkness and irreligion, was truly refreshing to my spirit;
I felt free to accept the pressing invitation to tarry the night with them.
Among other visitors was a sister of M. Berea`'s, whose husband, General Partenai,
is at present a prisoner of war in Russia, and bears an excellent character,
very uncommon for men in his station in these days.
His wife is not behind him, for she possesses a tender and pious mind;
her great humility, with her many charities,
evince her endeavour to walk as a disciple of Christ.
In the evening, the whole family being collected together,
we had an opportunity for religious retirement, and for the worship of God.
He condescended to open the spring of the ministry of his Gospel among us,
to our mutual refreshment and edification, and the contriting of our hearts before him.
There was present a Popish priest, an old Dominican friar,
who appeared astonished at what he heard and saw,
but he did not attempt to show any opposition.
The next morning M. Berea accompanied me back to the town.
He is in the meridian of life, and a man of bright parts;
but from a sense of religious duty he has withdrawn from the world`'s pursuits,
to live in retirement in this sequestered but beautiful and fertile spot,
covered with vineyards, olive, lemon, orange, almond, fig, and other trees;
the hedges lined with pomegranates, myrtle, rose, green-aloes, etc.

I now proceeded towards Genoa, through Savona.
The Lord was pleased to bring me safely through that journey,
notwithstanding the dangers and difficulties attending it;
neither did I meet any of the robbers so much talked of,
and though I had very coarse accommodation,
I generally met with civility from the people.
I found that the road, as it had been described, lay over high rocky mountains,
by the side of great precipices,
and so narrow that a mis-step of the mule would have precipitated us to a great depth.
Sometimes even that narrow path was covered with rolling stones,
and so steep that it was like ascending or descending a staircase.
I was favoured to pass all this without injury,
though once or twice my mule stopped short, refusing to go forward, till my guide,
who had kept behind, coming in sight, had only to speak, and the mule went on.
The scenery before me was frequently very grand,
so that with admiration I could not help crying out, "`Great and wonderful are Thy works,
Lord God Almighty, etc.`"
Surely His works do praise Him.
A project is being carried out to render this road
even superior to the one through Mont Cenis;
should they complete it, it will be one of the finest roads in Europe.
I met numerous companies of priests and friars in almost every village.

From Savona to Genoa the road is so good that I travelled in a wheel-carriage;
it passes through a very fine and fertile country,
having a great number of large and nicely finished houses,
with handsome grounds attached to them.

Soon after my arrival at Genoa, I became acquainted with the Swadish Consul, a pious man;
he introduced me to several others like-minded with himself;
among those he brought to my lodgings to see me was an Italian,
to whom the Consul had given the perusal of the short account
of our Chriotian principles that I had presented to him,
with other books of a religious kind.
He was so delighted to find in that tract sentiments so
in accordance with the convictions made on his own mind,
by the secret but powerful operations of the Divine Spirit,
that he came to me with a very full heart,
rejoicing that there were others convinced of the same Gospel truths.
We had a very affecting and interesting time together, the Consul also being present; he,
like the Italian, is a man of great information and learning; but above all,
both evince that they have learned in the school of Christ.
I presented them, among other books, with [.book-title]#Barclay`'s Apology#, in Latin,
which they received with gratitude.

The way was now opened for my having several small meetings,
composed of from fifty to sixty persons, Protestants and Papists, generally of pious,
seeking minds, so that the Lord`'s baptizing power,
and the comforts of his Divine Spirit endeared us to one another,
and refreshed us together in his presence.
I had also a precious meeting with some of the Waldenses,
who have retired from the valleys of Piedmont, and reside here;
there are about one hundred.
Some of these meetings were held at my hotel, the owner of which,
being himself a pious man, and one of the Waldenses,
the people were more free both to attend the meeting and to see me in private.
It was often very pleasant to find in these visitors such as evinced
that they were dissatisfied with their popish tenets,
and sought after a better way.
Copies of the Scriptures which I presented to them were very acceptable.

During my tarriance at Genoa,
I was introduced into very close exercise of mind and trial of faith.
Deep had been my concern on account of various parts of Italy--Rome, Naples,
etc.--places that I had felt for in years past,
with an apprehension that I should be required to visit them in Gospel love.
I thought that the time had come for me to engage in that service,
especially as I was then in Italy.
Finding, however, that it would be impracticable to go by land to Rome,
on account of the numerous bands of robbers that attacked
travellers even when escorted by large companies of soldiers,
I concluded to try to go there by sea, by way of Leghorn.
As I was going to engage my passage for that port,
my mind was introduced into unutterable distress--gross darkness seemed to be before me,
whilst a bright stream of light was behind; I stood still for a while,
and found I could not go forward.
I returned to my lodgings, and in my chamber poured forth my soul unto the Lord,
entreating him to direct me aright.
He knew it was in obedience to his Divine will that I had come to these nations,
and that to his Divine guidance and almighty protection
I had wholly committed myself and my all.
He very graciously condescended to be near to me in my distress,
and to hear the voice of my supplication.
He gave me to see, and strongly to feel, that to Rome, Naples, etc., I should indeed go,
that I had baptisms there to be baptized with, but that the time for it had not yet come,
and the language of the Spirit was to proceed with all speed for Geneva and Switzerland.
My soul was greatly humbled and tendered before the Lord,
who thus condescended to instruct his poor servant,
and to direct him in the way which He would have him to go.
I remembered with awful reverence and gratitude the gracious promise made me,
before I left America, when,
contemplating the extent and magnitude of the Lord`'s work to which I was called,
my soul was dismayed:
"`I will teach thee and instruct thee in the way in which thou goest,
I will guide thee with mine eye.`"
Now I saw how wonderfully my blessed Lord and Redeemer fulfilled his Divine word,
and he also renewed a little faith in the safety of his guidance and almighty protection.

I soon agreed with a person to take me in a carriage to Turin,
for which place I set off the next day, the 13th of the Eleventh month.
There was only one other passenger with me.
We had proceeded a very little way out of Genoa when,
meeting with another carriage going back empty to Turin,
our coachman stopped and began to bargain with the driver about taking us there.
It was a long time before we knew what they were about, and, after we found it out,
in vain did we represent to our coachman the impropriety of such conduct,
and urge his going forward; he remained deaf to our entreaties.
As we could not help ourselves, patience was our only resort;
we were however amused at being thus sold out on the highway.
After some hours detention, we proceeded with our new driver and carriage,
but we had not travelled far when we overtook another
carriage going to Turin with four passengers.
The two drivers bargained again about us, which took them a long time,
and the result was that we were sold a second time,
and were now six of us crowded together,
and we could not obtain any redress by complaining.
It took us four days to accomplish the journey, which we were favoured to do in safety.
We had several alarms from the robbers; of their depredations on travellers,
and of the murders that were almost daily perpetrated by them we had heard dismal accounts,
but the Lord condescended to preserve us in the midst of dangers, blessed be His name.
Many of these robbers are said to be conscripts, who, unwilling to go to the army,
have fled to these mountains,
and for want of means to obtain food are now driven to acts of desperation,
to the terror, not of travellers only, but of the inhabitants also.
Large numbers of them join together in their acts of plunder,
and when too strong a force comes against them they
retire into the fastnesses of the rocky mountains.

I arrived at Turin late in the evening of the 16th.
I had letters from Genoa to some pious persons here,
to whom I have paid, or from whom I have received some interesting visits,
and I have had several religious opportunities with them.
One of these, Vassally, formerly a Popish priest, is in an inquiring state of mind;
several others manifest much tenderness of spirit;
among them are two physicians and some professors of the university.
Through the medium of these, many persons met me at my lodgings for religious purposes,
who made many inquiries respecting our Christian principles and doctrines.
Several of these, like Vassally, have been Popish priests,
but their eyes having been opened to see the inconsistency of Popish superstitions,
they could no longer, with peace of mind, officiate in that capacity.
I had also a very interesting visit from the Chaplain of the Prince of Sardinia,
who made sundry inquiries respecting my views on various of their tenets,
among others the authority of the Pope and his clergy, their sacrament of the mass,
transubstantiation, confession, and absolution, invocation of Saints, the Virgin Mary,
etc., etc.
I was favoured so to answer his inquiries as to induce him
to wish to know more of the principles of our Society.
He requested that I would favour him with some books treating thereon,
having heard that I had such with me; I presented him with some accordingly,
with which he was much pleased.
I frequently find persons who have a great disposition to obtain books of this kind,
and I am glad to have it in my power to furnish them.
It has been a matter of surprise to me that though my baggage
has been so often narrowly examined since I entered France,
and in Italy, yet my books, Bibles, etc., have not been taken away.

On coming to Turin my mind was turned with strong Gospel
love towards the Vaudois in the valleys of Piedmont,
not far distant.
I did not know but that it might be a suitable time for me to discharge
the debt of love which I have long felt I owed them;
but, seeking for the Lord`'s direction, my way has appeared totally closed.
I have felt as if I must proceed with all speed for Geneva;
the impulse on my mind was as if I must flee for my life;
surely the ways of the Lord are above our ways! vain would
it be for poor man to inquire why or wherefore it is so?
At least I found it so with me.
Under the conviction that my only safety was in simple obedience to the Lord,
I have said,
"`Thy will be done,`" and I have accordingly taken
my passage in a carriage going to Geneva.

After travelling five days and nights, he arrived in that city, and remarks:

As I proceeded on my way, I felt that I was leaving a heavy weight behind me,
and that a bright light shone on my way forward;
such peacefulness accompanied me that I did not feel any weariness from the journey;
the consolation of the Lord was so richly extended to me that my
soul was poured forth in reverent gratitude before Him,
surprised, nevertheless, in having been thus driven to Genoa, and now brought to Geneva;
surely the Lord has wise designs in all this, though I do not understand it.

It was soon manifest that there was, indeed,
"`a cause`" for this visit to the "`city of Calvin, of Farel,
and of Beza,`" and that it was peculiarly well-timed;
Geneva had sadly fallen from its ancestral faith, and proved how vain are historic names,
orthodox creeds, and Scriptural formularies,
when the Spirit ceases to animate the lifeless form.
The clergy at that time were, with scarcely an exception, Socinian;
and there is ground to believe that Stephen Grellet`'s
labours amongst them were permanently blessed.
The journal continues:

Soon after my arrival, I called on some individuals for whom I had letters.
Among these were Vaucher and Duby, both professors of theology at the university here.
After a pretty long conference together,
during which they appeared to take great interest in the object of my
thus travelling in these nations in the love and service of the dear Redeemer,
they made various inquiries into the nature of our Christian profession,
and told me that that evening there was to be a general meeting of all their clergy,
and gave me a pressing invitation to meet with them.
On the first mention of it, I could not accept the invitation; I even recoiled at it,
but the more I tried to put it away, the stronger the weight of it came upon me;
so that I could only give for answer that I would take it into consideration.
I went back to my inn, and after waiting on the Lord,
and earnest prayers that he would direct all my steps in his Divine counsel,
I found it would be my place to attend that meeting;
I felt it nevertheless a great cross,
being very sensible of my want of qualification as a man to appear
thus alone among so many wise and learned men and high professors.
The weight of exercise and distress, however, under which I had been at Montauban,
and other places,
on account of the principles of infidelity I found
disseminated by some of the clergy among the Protestants,
together with a desire I had often felt to have an
opportunity to plead with them on this account,
came forcibly before me,
with a fear of now flinching from bearing my testimony
for the Truth when a door appeared open for it.
Moreover,
I felt that it might be in part for this purpose
that the Lord had brought me here with such haste.
About the time of their meeting, Vaucher and Duby, accompanied by Picot, their President,
came to wait upon me.
I found fifteen of their ministers collected together,
with the three Professors of Theology.
I felt very low indeed among them, like a poor stripling,
but was favoured in calmness to have my mind stayed upon God.
They were informed of the invitation given me to sit with them on this occasion;
but I thought it proper to request them to proceed
with the business for which they had met,
as they would have done was I not present.
They answered that they could meet at any time to transact their business,
but that they might never have another opportunity of having me among them,
and therefore desired to know if I had any objection to
answer a few questions they felt disposed to ask me,
not for disputation, but for information.
I told them that I was willing to answer all their inquiries with Christian candour;
indeed I felt the love and power of the Redeemer to be over us;
His gracious promise to his disciples that it should be given them what to say
or to answer when they should be brought before kings and rulers for his sake,
was very sweetly and encouragingly brought to my remembrance.
They inquired of the nature and qualification requisite for a minister of the Gospel,
of Divine worship--what renders a man a true member of the Church of Christ,
of baptism and the supper; then passed on to perfection, election, reprobation,
and dwelt very particularly on redemption and salvation by our Lord Jesus Christ.
I endeavoured to answer them in as concise and clear a manner as the Lord
enabled me to do on all these and some other very important subjects.
Among the questions respecting the Divinity and God-head of the Lord Jesus Christ;
one of them said "`if Christ is from eternity,
why is he called the first-born of every creature?`"
This fully opened a door for me to testify to the
Lord Jesus Christ in his various offices and attributes,
being true God and true man also, who is from everlasting to everlasting.
It also prepared my way to speak of my great distress at Montauban,
and particularly to lay before them the great responsibility which
rested upon them on account of the infidelity which was thus promulgated
by men who had been sent there from this university.
They heard all I had to say in answer to their various questions with becoming attention,
seriousness and solemnity prevailing over us during
the whole time that we continued together,
upwards of three hours.
At the conclusion they said:
"`This has been to us a season of instruction and edification.`"

Thus has the Lord been pleased to help his poor servant,
and to magnify the great and adorable name of Jesus, my Saviour.

A wide field was now set before me for religious labours among serious individuals,
both among the wealthy inhabitants of this city and those in humble life.
I found several companies of these in the practice
of meeting frequently together for religious edification.
I had some very solemn and tendering seasons with them;
a number of these meetings were also held in the houses of some of the Protestant ministers.
Among others I had several at Dumoulinier`'s and Demalleyer`'s. I was
several times much comforted with Mary Ann Vernet and her family,
where several more of that class met us;
some of these evince that they have learned in the school of Christ,
and are well acquainted with his Law, written in the heart.

Eight of their clergy called at one time upon me,
wishing to have further information on certain subjects, particularly the ministry,
spiritual worship, baptism and the supper.
They appeared to be in a tender state of mind, particularly Gideon Gabaret,
Pastor of Zully,
who wrote me afterwards a letter which more fully exhibited the exercise of his mind,
and his honest desire to come to the knowledge of the Truth.

My dear Master has given me much service among that class of men.
I have been much exercised on their account,
because of the Socinian principles which have crept in among them.
May they treasure up these days of labour amongst them.
After I had in simplicity and sincerity once more set before
them the consequences of the baneful principles of Socinianism,
several of them said they were almost persuaded; I would they were altogether so.
My dear Master has enabled me clearly to lay before
them what is the dispensation of the Gospel.
Blessed be the Lord for this renewed help of his Holy Spirit
to testify of his Truth and power among the great and wise.

I have been at several of the villages about Geneva,
having some very solemn religious seasons among them.
Truly, the Lord has a precious seed in these parts;
may they keep very near to him who has revealed himself to them as the beloved of souls,
the Lord their Redeemer.

During my tarriance here I have had a little unfolded to my view
why the Lord has led me about in such a remarkable manner,
to deliver me from the bonds and snares that were devised against me.
I now learn that the Prefect at Nismes wrote to the
Minister of Police at Paris respecting me,
as he told me he should do.
He received an order from him to have me arrested, and sent to Paris.
In consequence he sent his Gensdarmes after me to Marseilles,
expecting that I was still there; but finding that I had left that place for Italy,
they did not think I could have attempted to go there by that difficult road,
through which the Lord directed my steps,
but that I must have followed the highway through Chambery and Mont Cenis;
and finding that I had not passed through Chambery,
they reported to the Prefect that they could not discover where I had gone; and again,
why I have been prevented, in such a remarkable manner, from going towards Rome,
or even among the Waldenses, and felt myself constrained to come here with such speed,
is now explained as being a very merciful interposition of my blessed Master,
under whose guidance I desire to be kept.
The armies of Buonaparte have met with signal defeats in Germany, at Leipzic,
and in several other places, so that the survivors of his once large army,
are hastily retiring, some over the Rhine to France;
and the army of the king of Naples to Italy, by way of the Tyrol, the Simplon, etc.;
so that I had hardly left Italy when they began to arrive,
closely pursued by the Austrians.
A delay in Italy of a few days longer, might have shut me up there,
as there is no possibility, at present, for any body to pass away from their lines;
neither could I now escape from Chambery.
Thus have I been delivered from two-fold dangers,--from being carried
to Paris as a prisoner for the testimony of Jesus,
or shut up in some corner of Italy.
Bless the Lord, O my soul! trust forever in the guidance of his Divine Spirit,
who alone can and ought to direct thy steps, and all thy movements,
especially in the service of the ministry of the Gospel, to which he has called thee.

More than a week had now been closely occupied with
religious engagements in and about Geneva,
and,
kindly furnished by his friends there with introductions to pious
individuals in various parts of Switzerland and Germany,
Stephen Grellet left that city.
At Lausanne, he met with many of the followers of Madam Guyon, called Pietists.
Respecting these he remarks:

They spend much time in religious retirement,
and their meetings for Divine worship are mostly held in silence.
I had several religious opportunities with them,
in which a real religious exercise appeared to prevail to wait upon the Lord,
and to worship him in spirit and in truth.
Some of these seasons were times of refreshing from the Lord`'s presence,
who is near to those that wait upon him.
I also visited these people in their families, and I was comforted among several of them,
who are of the poor of this world,
but rich in the faith which is in Jesus Christ our Lord.
Some of their leaders, however, under a high profession of spiritual-mindedness,
are but little removed from superstition, very nearly bordering on Popery,
though they keep the mass of their adherents unacquainted with their mysteries,
as they call them; these being above their capacity to comprehend.
It is, I have told them, a happy ignorance for them;
sufficient for them is the simplicity of the pure Truth.

Berne, Twelfth month, 12th. On my arrival here,
I found the inhabitants in much anxiety and distress; parts of the army of Italy,
in their retreat, have passed through this place, and left a contagious fever,
which in many instances proves to be mortal.
A number of persons attacked with it did not survive more than a day or two.
I was several times much affected on being told in the morning of the decease
of pious persons whom I had been with at meeting the preceding evening.
Great seriousness prevailed over many minds,
and our meetings were solemn baptizing seasons, attended by many pious persons,
rendered still more serious under the present aspect of things.
The Austrians, it was known, were on their march towards Berne, intending only,
they said, to pass through it, in their pursuit of the French;
but the rulers of that Canton could not yet agree to grant them the liberty to do so;
if refused, there was an apprehension that they would do it by force, in which case,
a great effusion of blood must be the consequence.

At this juncture he was himself taken ill with the prevailing epidemic,
and for several days his recovery seemed doubtful.
In reference to this, he says:

Several pious persons I had become acquainted with came to my inn, very kindly,
to minister to me.
They thought that there was but little prospect of my surviving the attack;
but my mind was preserved in great calmness, in resignation to the Divine will,
feeling at the same time a renewed confirmation,
that the service for which the Lord has sent me into Germany must be performed,
and that I should be enabled to surmount all difficulties
and dangers to which I might be exposed.
That sickness was a season when my faith and confidence in the Lord were renewed.
My strength soon returned, after the fever left me;
and a door being set open before me for religious service, I was enabled, with diligence,
to attend to it, both in private families and smaller or larger meetings.
As many of these were held among persons who spoke the German language only,
I was obliged to make use of an interpreter.
In this service L`'Orsa, a pious Protestant minister, very kindly assisted me,
translating for me from the French, which he did with much feeling, and at times,
with great tenderness of spirit.

I left Berne on the 24th of Twelfth month.
As I was passing through the gates of the city,
I met the advanced posts of the Austrians coming in,
and the whole way to Zurich I found the Austrians on their march to France.
They treated me with civility; but finding the towns crowded with soldiers,
and the inns occupied by them, I travelled night and day without stopping,
except to take some refreshment.
I have found here in Pestalozzi (a banker of Zurich) a very kind and faithful friend;
he has devoted much of his time, during my tarriance in this city,
to going about with me, and acting as my interpreter whenever it was requisite,
both in families or in larger congregations; as I have had several meetings,
and the mass of the people understand the German only.

In the widow of the late Lavater, and in many branches of her family,
I have found genuine piety.
Christian lowliness, meekness and humility,
very conspicuously prevail among several of them.
One of the daughters married to George Gessner, one of their clergymen,
has been largely taught in the school of Christ,
and is well acquainted with the influences of the Holy Spirit,
by whose guidance she manifests a desire that her steps should be directed.
This is also the case with her sister Louisa.
Gessner also is a man of piety, who sees beyond forms and shadows.
I have had several precious religious opportunities with them and their numerous relatives;
their hearts were open to hear the testimony of Truth.
Gessner has also opened his house for more public religious meetings.
This has been the case also with Antistes Hesse, an aged man,
the head of the clergy in this Canton; he is green in old age,
and of a very tender spirit.
On one occasion, when, at his request,
I had given him an outline of the views entertained by our religious Society,
respecting the new birth, the Christian baptism,
the bread of life on which the renewed man feeds, on worship, ministry,
the church of Christ, faith in our Lord Jesus Christ, his various offices,
redemption and salvation by him,
together with the gift and operations of his Divine Spirit, he, with much tenderness,
expressed his gratitude in that the Lord has raised himself
a people among whom the standard of Truth is lifted up,
and the Gospel in its purity is proclaimed.
"`I have read and diligently studied the Scriptures,`" said he, "`in Greek, Hebrew,
and Latin, but it is in the school of Christ only,
through the teachings of that Spirit by which alone the things of God can be known,
that I have learned that those things you have now set forth are true.`"

This place was crowded with Austrian and Hungarian troops;
many of the officers put up at the hotel where I had taken my lodging.
I felt it to be my duty to take my meals with them at the public table;
I thought there was a service for the Lord in it; I soon found it was the case,
for my dress, manners, and language, attracted their attention,
and drew forth their inquiries into my religious principles, in respect to war,
in an especial manner.
I was much gratified to find among that class of men, the Hungarians particularly,
so much sensibility as they manifested.
"`Thankful should we be,`" said some of them,
"`were the nations gathered into the peaceable spirit,
which the gospel of Christ inspires, and your religious Society maintains;
we should not then be, as we now are, marching to the slaughter to kill and be killed.`"

During the time I stayed at Zurich, I continued to take my meals in like manner;
and as the troops daily went forward, and others arrived,
I had an opportunity to proclaim the Gospel of peace and
salvation to a considerable number of the military officers.
Their anxiety for information, and their attention to my answers to their inquiries,
were such that I frequently rose from the table without
having had time to eat more than a very few morsels.

By letters I received from Berne,
it appears that my friends there had been very uneasy on my account,
as they hod heard that several persons had been plundered,
and others murdered on the road that I had travelled, by some of those bad characters,
who generally go along with the armies; many of these, to avoid detection,
disguise themselves by appearing like Cossacks.

In some of the meetings I had,
I was engaged to press upon the people to attend faithfully
to the teachings of the Holy Spirit in their hearts;
for it is the Spirit of Truth who not only brings the repenting sinner to Christ,
the Saviour, but also "`leads into all Truth.`"
I also earnestly pressed upon them to repair often to the house of prayer,
with faith and confidence in our Lord Jesus Christ,
who has promised that "`whatsoever ye shall ask in my name, it shall be done unto you.`"
After one of these opportunities, Lavater, a physician, brother to the late Lavater,
told me,
"`I have great reason for being fully convinced of these great and important truths,
that you have delivered.
Once I did not believe in them, and even ridiculed them;
but the Lord was pleased to convince me of their
reality in the following manner:--My son,
my only son, was very ill; I had exerted all my medical skill upon him in vain,
when in my distress I wandered out into the street,
and seeing the people going to the church where my brother, Lavater, was to preach,
I went also; he began with that very text that you have mentioned,
'`whatsoever you shall ask in my name, believing,
it shall be done unto you.`' He dwelt very particularly on the nature of prayer,
in whose name and to whom it is to be offered;
he described also the efficacy of that faith,
which is to be the clothing of the poor supplicants.
I attended very closely to what my brother said,
and I thought I would now try if it was indeed so;
for my solicitude for the recovery of my son was great,--my prayer for it was earnest;
I thought also that I believed the Lord Jesus had all power to heal him if he would.
Now,`" said he,`' "`in my folly I dared to limit the Almighty to three days,
concluding that by this I should know that he was indeed a God hearing prayer,
if my son was restored within that time.
After such a daring act, all my skill, as a physician, seemed to be taken away from me.
I went about, looking at my watch to see how the time passed, then at my son,
whom I saw growing worse; but not a thought to minister anything to him arose.
The three days had nearly passed away, when with an increase of anguish,
and also a sense of the Lord`'s power, I cried out, '`I believe,
O Lord! that thou canst do all this for me,
help thou my unbelief;`' on which some of the most simple things presented to me,
to administer to my son; so simple that at any other time I should have scorned them;
yet believing it was of the Lord, I administered them, and my son immediately recovered.
Now,`" said the doctor, "`I felt fully convinced that the Lord heareth prayer,
and that there is an influence of the Spirit of God on the mind of man,
for I have felt it.`"
He added, "`To this day I feel ashamed of myself, that I, a poor worm,
should have dared to prescribe limits to the Lord, and wonder how,
in his boundless mercy, he shonld have condescended, notwithstanding my darkness,
to hear me.`"
These are very nearly the words of the doctor;
they were accompanied with brokenness of spirit.

During my continuance at Zurich the seat of war was brought so near,
that the distant sound of heavy artillery could be heard, both towards Basle,
and on the other side of the lake.
Very mournfully was my spirit affected,
in daily seeing so many of my fellow-men marching to the field of battle.

The armies of the Allies are passing through this land to enter into France,
so that I am now in the midst of them.
Poor France, where I have just proclaimed the glad tidings of God`'s salvation,
and the day of his vengeance also,
is now going to be the theatre of war--herself drinking of the cup of
blood she has so plentifully administered to the other nations.

On the 1st of the First month, 1814, I left Zurich and proceeded to St. Gallen,
travelling again both day and night.
By so doing, besides avoiding the difficulty of accommodation on the way,
on account of the soldiers, I save much time.
I find that this manner of proceeding has, within the last few months,
saved me twenty-four days, which is great gain on such a journey.
There are in this place, a considerable number of pious individuals, who,
under their present sufferings, have deepened in the root of vital religion.
They have been apprised of my intentions to visit them, by their friends of Zurich.
They have received me with Christian affection.
The meetings for worship, I have had with them, were tendering seasons;
for the Lord Jesus, who is very precious to many of them,
condescended very graciously to be near to us,
giving us to partake together of the consolations of his Divine Spirit.
Some of these dear people are spiritually minded,
and in several of them the fruits of the Spirit are apparent,
particularly in the Schlatter family.
I have felt it my place to visit most of them in their families.
Many of these visits were, in a memorable manner,
like the breaking of bread which the Lord did bless, from house to house.

In some of the villages about here reside a number of persons,
both protestants and papists, who, from religious conviction,
and tenderness of conscience,
have withdrawn from the various professions they were joined to.
They spend much of their time alone in religious retirement; and when they meet together,
sit in silence, or read some portions of the Holy Scriptures.
Some of them appear also to be convinced of the unrighteousness of war,
and of the unlawfulness of oaths, under the Christian dispensation.
I have heard of many others, under similar convictions, who reside among the mountains,
and several of these are Romish priests.

At St. Gallen ended his labours in the Helvetic Republic.
He left it with deepened feelings of Christian interest in its inhabitants.

"`Though Switzerland,`" he writes,
"`has drunk of the cup of fornication with all the surrounding nations,
yet there are in it many precious characters who are partakers
of the life that is hid with Christ in God,
and near to everything that is capable of feeling within me.
O! that I may know my dwelling to be near to Shiloh`'s brook,
and the streams of everlasting life,--not in the heights, but the depths!
The Lord keeps me in the low valley; and for my deep plungings and baptisms,
which are not few, I can thankfully bless his name!
Though I have hitherto been mostly alone in my pilgrimage,
it is admirable how way has been made for me.
I am contrited in contemplating how bountifully the Lord has supplied all my need.`"
