== Chapter XXIII.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* The Kingdom of Wirtemberg
* Frankfort
* Neuwied
* Cologne
* Elberfeld
* Barmen
* Pyrmont
* Minden
* Bremen
* Return to England

In Bavaria, Stephen Grellet had met with much that interested him,
and called forth his sympathy and solicitude.
He found it no easy thing to part from those to whom he had become
so closely united in the bonds of Christian fellowship;
but the time had come to enter upon new fields of labour.
The prospect of attending the ensuing Yearly Meeting in Ireland had opened before him,
and he had yet much to accomplish in Germany.
Diligently pursuing his labours, he writes:

[.embedded-content-document]
--

I arrived at Stuttgard on the 28th of First month, 1814,
where I met with several persons prepared, by letters from their friends of Geneva,
to see me; and I had several solemn religious meetings with them;
much Christian simplicity appears among them.

I paid several visits to the Countess Seckendorf and her daughter, in their affliction.
The Count, who was Prime Minister to the King, died only a few days since.
He was a man of great worth, and, above all, of much piety;
and such are his bereaved near relatives.

I have found the greater openness here, in consequence of a time of recent excitement,
which appears to have been blessed.
Dan, one of their clergymen, a man of great piety,
found it his duty to proclaim against public places of diversion,
showing how contrary these are to the precepts of our holy religion.
His preaching had an awakening influence on many, and particularly on some in high life;
at which others became so displeased, that a persecution against him soon followed.
They succeeded in having him removed from Stuttgard,
to an out of the way place among a rough, depraved people.
This proceeding has led many more sensibly to feel his worth, and now to endeavour,
with faithfulness, to act according to the doctrines he preached among them.
How frequently do we see that the efforts of men to prevent
the Lord`'s work only tend to promote it;
this appears to be the case in this place and neighbourhood.

I then proceeded to Tubingen, where reside several persons I felt desirous to see.
On my way there, I turned out of the road, about 12 miles, to visit Dan,
in his sequestered abode.
I found him in affliction.
One of his family had just died in the house, and his wife was ill with the same fever.
The dear man was preserved in much calmness and Christian resignation,
waiting to see what the Lord would further do for the refinement of his soul.
Since his coming here, a great reformation has taken place among the people,
in a place where irreligion and vice prevailed.
Thus has the Lord overruled for good the evil that
had been intended against this pious servant of His.

Some of the persons towards whom I felt my mind drawn
at Tubingen are professors at the university.
They are full believers in our Lord Jesus Christ,
and feel it to be their religious duty to maintain their faithful testimony against
the introduction into that university of principles repugnant to Christianity,
as has lamentably been effected in many other places.
I found them in a tender but tribulated state,
and endeavoured to encourage them to uprightness and faithfulness.
We were mutually comforted by the visit.

I went a little further to Ocksingen, where I met with a few disciples of the Lord Jesus.
Our religious intercourse was truly pleasant.
My spirit is often contrited when meeting here and there with the Lord`'s visited children,
who, like a little salt, are sprinkled over the land.
If these are faithful in their several allotments, they may be like lights in the world.

I had for a length of time felt my mind strongly drawn towards Carlsruhe, and now,
believing the time had come to go there, I proceeded towards it,
visiting a few places on the way.
I arrived at Carlsruhe, after being two nights on the road.
I had letters for Jung Stilling, a man extensively known in Germany by his writings;
and for his daughter,
much respected by many because she puts in practice
what her father describes in his writings.
I was introduced by that family to several serious persons, of various ranks in life.

Many Prussian soldiers are here.
I find among some of their officers much religious sensibility.
The Baron de Lachevalery is under a very precious visitation from the Lord;
it does not appear as if he could long continue in his military career;
he longs to be under a better standard;
he does indeed already feel that there is a banner over him which is love.
Another is General Stockhorn; he was in a very broken state of mind;
strong are the convictions of the Spirit of Truth upon him.
I told him it would not do to struggle against them any longer,
and queried whether he did not feel that the time
had come to take off his military garments,
to put on the meekness and gentleness of Christ,
and to exchange his warlike weapons for the Christian armour.

I met here the Baroness Krudener; she is a remarkable woman,
and has been an instrument of real good among several young women of high rank,
particularly here at court.
They frequently meet with her for religious purposes,
and this has enabled me to have several religious opportunities with them.
One evening, when the meeting was silently gathering, two of them came softly to me,
and said, "`Do not be disturbed if we withdraw before the meeting concludes,
for this week is our turn, as maids of honour, at court;
but we wished to stay at the meeting as long as we could.`"
Several of these young women feel such conscientious scruples, that,
when performing duty at court, they cannot join in the pleasures or pastimes of it; and,
when not needed, they retire to read their bibles, etc.
Much of the service that has been laid upon me in these meetings,
and with others in private also,
has been to direct them to the teachings of the Lord`'s Spirit in their own hearts,
telling them that, to hear the language of the Spirit,
silence on our parts and cessation from our own actings is necessary;
we must "`hearken and hear what the Lord has to say unto us.`"
The Lord is nigh to them that wait upon him.
This is an acknowledgment that several of those young women have made,
after we had spent some time together in silence.
Though I had consolation here with the visited children of the Lord,
my soul was greatly oppressed, and my heart made sad,
because of another spirit which has great ascendency over the people.
What I heard also of the horrors of the war, greatly afflicted me.
Several bloody engagements have taken place not far distant from this.
I was not released from my close engagements here till the 9th of Second month.

On my way to Frankfort, I was greatly distressed several times,
on meeting with wagons loaded with wounded soldiers,
that they were carrying away from the field of battle fought near the Rhine;
the blood ran down from the wagons.
And in some of the towns through which I passed,
I saw the poor wounded ones remaining a considerable time exposed,
before provision for their reception could be made.

I found in Frankfort a considerable body of Russians and Cossacks,
Prussians and Austrians; these were of the troops that fought at Leipsic, Dresden, etc.
They had many of the French prisoners with them,
and I have seldom seen more distressed looking beings--so reduced by disease and famine.
It was difficult in Frankfort to obtain provisions sufficient for the multitude.
The description given me by some Prussian officers
of the roads through which the French army retreated,
is most awful.
It was strewed with the dead or dying;
many died in consequence of malignant fever that broke out among them;
and they were the means of introducing the fever very extensively through the country.

My mind has been deeply afflicted on account of the inhabitants of this city;
their sufferings have been great; bloody battles have been fought within their walls;
they have even now before their eyes the sad consequences of them;
yet few appear to lay it to heart.
I find a very small company only, with whom I can assimilate in religious fellowship;
with these few, however, the Lord has given us the consolations of his presence.

I left Frankfort with a heavy heart for Neuwied, where I arrived the 16th instant.
Very solemn have been my feelings on the way,
attended with reverent gratitude to the Lord, who has called me from darkness to light,
and from the service of the prince of darkness to that of His glorious and blessed Gospel.
Twenty-three years ago, I passed through these parts as a military character,
in the same spirit that actuates those I am now among,
who have been the means by which torrents of human
blood have mixed with the waters of the Rhine.
It is true that by the Lord`'s tender mercy I was preserved from the shedding of blood,
but nevertheless,
I abhor myself in the remembrance of the spirit by which I was then animated.
O that I might be an instrument of inducing many now to come and
range themselves under the standard of the Prince of Peace!
May it not be in good measure for such a kind of
service that the Lord has sent me into these nations,
at this time?
Day by day I have opportunities, at the inns particularly, to be with many officers,
when the way is often made for me to preach Christ to them,
and to unfold the nature of his kingdom, and the peaceableness of it.
Though I have been thus very frequently engaged,
I have once only met with an opposing spirit.
It was at Frankfort from the military Governor,
saying what he would do if Friends were sent to him as soldiers,
and should refuse to fight.

The Moravians have a large establishment in Neuwied;
and here is also a people who go by the name of Quakers.
They maintain many testimonies similar to Friends; that against war, among others,
on which account some of them have suffered greatly.
Their meetings for worship are conducted much like those of our Society.
I have visited these persons individually, and had some solemn meetings with them.
Peculiar circumstances greatly tended to contrite our spirits together,
and bring us to feel the uncertainty of time.
This is a place through which numerous bodies of the French, in their retreat,
have passed.
By their plunders they have left great desolation behind them;
and by the seed of diseases which they have spread,
the destruction of human life is continued.
Perhaps there is not a family here which is not mourning over the death of near relatives.
It very frequently occurs that, in the morning,
we hear of the illness or death of some that were congregated
with us in a meeting for Divine worship the evening before.
Very solemn in these meetings is the contemplation that some of us, in a few hours more,
may be gathered into the Lord`'s presence.
O that we may be found prepared to join his redeemed ones!

I had also a good meeting with the Menonists.
Their pastor, a pious man,
who had taken a kind and Christian care to have notice of the meeting given,
died that evening, before meeting-time; several of his family were also taken ill.
Loud is the warning to endeavour to stand in
readiness, having our lamps trimmed and burning.
Amidst so much calamity, many hearts are made soft, and my way is open among every class.
I have visited the clergy among the Protestants, and also the Popish priests,
who have all received me with cordiality,
and appeared to take in good part the messages that, in the love of God,
I had to deliver to them.

I make my home in the family of one of those called Quakers, or Inspirants,
which gives me an opportunity of hearing much of that people, and of their history.
I am persuaded that if they had been faithful in the maintenance
of the testimonies committed by the Lord to their forefathers,
they would have become a great and good people; their light would have been bright,
and many might have gathered to it.

My host has given me an awful account of the sufferings
that prevail over the country generally,
in consequence of the war.
He has heard of and knows several travellers who have been plundered and wounded;
others have been killed.
He has been himself stripped nearly naked, and so abused, that after reaching his house,
he was for some time in a helpless state, and he has not yet fully recovered.

On leaving these dear people, they put me over the Rhine in a small boat,
and I took the public carriage for Cologne;
I should otherwise have had to ride many miles to effect it.
My mind was greatly saddened on the way to that city and in it,
because of the multitude of soldiers,
many of whom have come from the further ends of Russia, Calmucks, Tartars, Cossacks, etc.
Desolation and misery are over the land, and yet rioting,
drunkenness and all manner of wickedness prevail.
Thus vice and misery are mixed closely together;
at the sight of it my soul is overwhelmed with anguish.

From Cologne I went over the Rhine again,
and soon fell in with the advanced guard of about thirty thousand of the Swedes,
who are marching into France to join the Allied armies, against that nation.
Great order and sobriety prevail among the Swedish army,
neither do I hear any of the inhabitants, through whose country they pass,
complain of their conduct.

I arrived at Elberfeld the 21st of Second month.
Here, and in the neighbourhood, I met with many persons of tender and visited minds.
They received me with Christian affection.
"`In our great distress and many bereavements,`" said they,
"`the Lord has sent you to minister to us the consolations of his Gospel.`"
My spirit greatly rejoiced, at seasons, before the Lord, whilst among that people,
in that he very compassionately condescended to his afflicted ones,
and caused the stream of his consolations, and the refreshings from his Divine presence,
to flow among us during the meetings that we had together.
Truly they were meetings for worship;
for our spirits were very reverently prostrated before the Lord, at his sacred footstool.
As it was given me most tenderly to enter into feeling with these people,
under the grievous sufferings they have endured by
the hands of unrighteous and wicked men,
so also I share in the joys and consolations that the righteous God and blessed Redeemer,
the Comforter, causes to flow among them.

Through this part of the country many of the French troops passed on their retreat;
desolation and destruction marked their steps,
and as they were closely followed by the other armies,
what had escaped the first destroyers fell a prey to the others;
wanton acts of destruction have been committed,
furniture and other articles which they could not carry away, were broken to pieces.
But these have been their minor sufferings.
The inhabitants were under the necessity to send their wives
and daughters away to conceal them from the soldiers,
and in various instances, because they refused to disclose the places of their refuge,
they were sorely beaten, wounded, or even killed.
It is also very lamentable that they received no better
treatment from many who professed to be their friends,
than they did from the French, who treated them as enemies.
Who that has seen the horrors of war, its accompanying cruelties and vices,
can plead for it?
Or who that has only heard of the wickedness and misery that attends,
but must bitterly deplore it?
From my observations I may say,
that the sight of the bloody field of battle conveys but one part,
and perhaps the smallest part,
of the woes and miseries that attend this horrible scourge.

Among the pious persons at Elberfeld is an aged man, Herman Pelzer, at whose house,
many years since, were our dear friends, George Dillwyn, Mary Dudley, Sarah Grubb,
and their companions,
he speaks of their visit and religious communications
as having made a deep impression on him.
He is now eighty-four years of age, strong in body and mind, but above all,
he appears to love the Truth.

At Barmen I had a solemn and baptizing meeting.
Under the influence of the one Spirit, we felt that which unites in the true fellowship.
I had a pious female for my interpreter,
and she did her part with much tenderness of spirit and Christian dignity.

Whilst I was in these parts, several bodies of the Swedish army passed through.
Their sobriety and good behaviour are very becoming.
Such quietness prevailed in the evenings and through the night,
that a stranger arriving there could not have discovered
that he was in the midst of so many soldiers.
They all retired early in the evening to the several quarters assigned them,
and previous to their lying down the Subaltern attending
each small company offered up a short prayer,
in which the others joined.
I had several opportunities of hearing them.
They gave thanks to God for the preservation they had witnessed during the day,
and interceded for the continuation of the same day by day,--then entreated the Lord
for his blessing of preservation to their families and near relatives in their absence.
In the morning, when ready for their departure,
they were all marched in a body before the door of
the house where their commanding officer had lodged,
and he, with a loud voice, read to them a small portion of the Scriptures,
and then offered up a short prayer.
I have not heard of the like practice in any of the
armies of the several nations now confederate together.

I set off for Pyrmont in the evening of the 24th,
and was three nights and three days on the road, which I found very difficult to travel.
I went part of the journey by a sleigh,
but the glaze of ice formed on the road was such
that it was very dangerous in some places;
for on both sides of the road were deep gullies, ravines or ditches,
so that it was needful to keep on the middle of the road.
At one time, whilst thus situated, I saw a body of horsemen coming towards me.
They might be about six thousand men.
My driver tried repeatedly to bring his sleigh to the side of the road,
but at every attempt it seemed as if we should be precipitated on one side or the other.
The General, who was with his officers at the head of the troop, seeing my dilemma,
very kindly gave the order for the horsemen to open their ranks,
and to pass on the right and left; whilst he himself saluted me very civilly.
I could not account for this marked attention,
but possibly he might be one of those officers whom I had met at inns.
I believe he was a Prussian;
but there were many Cossacks also attending that little army,
and some of these as they passed looked very sour at me,
on whose account they were obliged to crowd on the side of the road.
The other part of the way I travelled in an open farm wagon.
The ice on the road had disappeared; but so many heavy cannon, and ammunition wagons,
had passed over it, that it was cut down very deep, and very rough beside.

After my arrival at Pyrmont, a place of much resort on account of its mineral waters,
I felt myself much straitened for a while.
I had expected that a Friend there,
who is well acquainted both with the French and English languages,
would act as my interpreter, but he was not in a state of health to do so.
Several services laid heavily on my mind towards
those professing with our religious Society,
and others.
I poured forth my soul to the Lord, who I knew could open a way for me,
where all seemed to be closed up.
As I was going to their meeting,
and saw a considerable number of strangers drawing towards it,
a great exercise came upon me, for I did not see how help was to come;
but I endeavoured to possess my soul in patience,
to see what the Lord would do for his great name.
On entering the house I was told that very probably a youth, who was pointed out to me,
who understood English well, could act as interpreter, should I need one.
He was only about sixteen years of age,
and on my asking him whether he thought he could undertake the office,
he replied that "`he would do his best.`"

I was brought under great weight in that meeting,
but I also felt the Lord`'s power to arise into dominion, with a little faith that,
in attempting to communicate to the company present
what I thought to be the word of the Lord to them,
all would be well; I rose on my feet, and the dear boy stood by my side,
and interpreted for me into German, as I went on, with all readiness.
I felt much attached to him,
and he became my faithful and kind helper through
all the meetings I had at Pyrmont and the vicinity,
and in my visits to the families of those under our name in that district.
He went with me to Minden, and several places thereabouts,
where some professing with us reside.
I had meetings with them and with the inhabitants also;
I went in Gospel love to all the families of those who are called by our name,
and found it here, as in Pyrmont, an arduous and trying service.
There are a few valuable Friends rightly concerned
for the cause of truth preserved amongst them,
and I hope they will, through faithfulness,
feel themselves increasingly girded with strength.
Frederic Smith is a valuable minister of the Gospel, and stands as a father amongst them.

I left Minden for Bremen on the 14th of Third month,
and suffered much on that journey from the severity of the cold,
and the badness of the roads;
an open farm wagon was the only carriage that could be used.
At Bremen I found in the senator John Volmers a truly pious and interesting man;
several branches of his family are so also.
He would not allow me to stay in any other place than his house;
and during the whole time of my being at Bremen he
was my constant attendant,--a helper by his spirit,
and of great assistance as an interpreter.

Here I have found a considerable number of honest inquirers after truth;
others also who I hope have come to the saving knowledge of it.
Some of these give very precious evidence that the
love of God is shed abroad in their hearts.
I had satisfactory and solemn meetings in this place; some were numerously attended.
It has been very pleasant to me to behold the love and fellowship
maintained among the various ranks in life,
rich and poor.

Volmers is one of the eight senators by whom this little republic is governed;
but his standing in life does not prevent his sitting
very lowly at the footstool of Christ.
He is in the daily practice of religious retirement,
and a small company unite with him in a silent meeting for worship;
for none of them have believed themselves called publicly to minister to others,
but each receives his instruction and consolation from the Lord himself,
the true and great minister.
They told me of a sailor who resided sixty miles distant, in Friesland,
who went to England a few years ago, and being at Yarmouth,
happened one day to pass by the meetinghouse of Friends, as they were going in.
He felt inclined to enter also.
The meeting was held in silence;
but such were the strong convictions made by the Spirit and power of truth on his mind,
that since his return home he has continued in the practice
of silently sitting down to wait on the Lord,
though entirely alone.
Having heard of the pious people at Bremen, he had sometimes come to sit with them,
and they wished I could see him.
What was their surprise, when, that very evening,
shortly after we had sat down together and were gathered into silence,
they saw him coming in.
He had just arrived, and came immediately to the house.
I could not help noticing the great reverence with which he sat,
and the brokenness of his spirit during the meeting.
The little intercourse we had with one another afterwards
furnished me with an evidence that he is a disciple of Jesus.

Visiting one day a female of rank, called lady Mettapost,
where I expected to meet none else but her,
I was surprised to see a large company of females of rank coming in;
we sat in silence for some time, during which,
and under the testimony to the truth given me to bear,
the hearts of many of these were contrited.
This lady is an unmarried young woman, possessing a large estate,
and has a liberal hand in administering to the needy;
she frequents the little meeting at senator Volmers`'.

I left Bremen at five p.m., the 20th, for Osnabruck.
On my arrival there I felt for a while much discouraged, for I knew nobody in the place;
I had not even the name of any one; but I concluded here, as I have done in other places,
to wait on the Lord, and feel after his guidance,
knowing that if he has any service for me he can open a way for it.
After a while I thought it proper for me to go out, and walk in the streets.
I had not proceeded far when I was met by a serious, respectable looking man, who,
after attentively looking at me,
addressed me with the inquiry if I did not belong to the Society of Friends,
and if I had known John Pemberton?
He then gave me a short and very interesting account of his religious visit to that city.
His name is Mertens, and he is pastor of the Lutheran Church.
He took me to several pious persons, rich and poor,
and soon after accompanied me to a meeting which
he had very quickly put in a way to be collected.
It was composed, like the few families he had taken me to visit, of rich and poor,
Protestants and Roman Catholics; but all of a class that love the Lord Jesus,
who makes no difference between Jews and Gentiles, bond and free.
It was an unexpected meeting, and a very solemn one.
The Lord owned us graciously by his Divine presence.
After meeting several of the aged people,
who remembering John Pemberton about twenty years ago,
manifested much satisfaction at seeing in me one of the same religious denomination,
having as they said,
been favoured again in the Lord`'s presence to have the bread of life broken unto them.

Now, feeling my mind released, for the present, from further service in Germany,
I accepted with gratitude the prospect set before
me of returning to England by way of Holland.
On account of the French continuing to have possession of several fortresses,
I was under the necessity of going a round about way.
I found much difficulty also, in consequence of heavy floods,
by which some of their dikes had been broken,
and above two hundred miles of land in circumference had been covered with water,
to such a depth in several places as to carry away houses, barns, etc.
Great was the destruction of human life, as well as cattle, horses, etc.
I was told that families,
after having for many days continued on the roofs of their houses,
were at last rescued by boats sent in various directions to the relief of the sufferers.
The waters had retired from the highways on which I travelled,
but had left so many large cakes of ice as to render travelling tedious and dangerous.

I made a short stay at Zwolle,
where I visited two persons who appeared in a tender state of mind.
From thence I went direct to Amsterdam, where I found my way much closed up.
The people were under great excitement;
a great concourse having flocked to that city to see the coronation of their King,--houses
were so crowded that I had great difficulty in obtaining a miserable lodging.
I visited however, to some satisfaction,
several valuable persons whom I had known in former years,
and then went direct for Hellevoetsluis to embark for England.

Feeling my mind released from the great weight of exercise
under which I have been for the people on the continent,
my soul has been prostrated very reverently before the Lord,
who has been my saving help and strength day by day,
night after night--the everlasting arms have been underneath to uphold and preserve me.
During this winter I have been more than forty nights on the road,
many times amidst robbers and murderers.
I have repeatedly been where contagious diseases prevailed to a high degree,
so that the mortality was great; often also I have made but one scanty meal a day;
but amidst all these things the Lord has borne me up, and delivered me,--yea,
rendered hard things easy.
My health is now as good, or better,
than when I landed in France more than nine months ago.
And, above all, the Lord, my great and blessed Master,
who called me to this service in these nations,
has opened a way for me to find and visit a portion of his seed,
and to proclaim the glad tidings of his salvation to thousands of the people,
both rich and poor.
Bless the Lord, therefore, O my soul, and forget not all his benefits!
O Lord! bless thou also those pious ones whom thou hast enabled me to visit!
O, bless the work of thy hands everywhere!

--

Thus he concludes the account of his second visit to the continent of Europe.
Numerous letters followed him from Gessner, Vernet, Gautier, etc., of Geneva;
Langalerie of Lausanne; Hess, Schlatter, etc., of St. Gallen; Baron Gumpenberg, Gossner,
President von Ruosch, Baron Pletten, the Princess Jeanette of Oettingen, etc., etc.,
in Bavaria.
These, with others, all bore testimony to the value of his religious visit and services,
and the spiritual comfort and instruction derived from them.
With some of these interesting characters he kept
up a correspondence for many years afterwards.^
footnote:[Dr. Steinkopff,
the well-known and devoted disciple of our Lord and Saviour,
whose earthly course was finished on the 29th of the Fifth month, 1859,
gave the following testimony respecting Stephen Grellet,
on his return from the extended journey on the continent of Europe: "`He is,
properly speaking, a French gentleman; he is a native of France,
but at the time of the Revolution went to America,
where he became enlightened amongst the society of Friends.
He is now in England on a religious visit;
when I saw him two weeks ago he gave me some account of his travels on the continent,
and it was indeed astonishing to me to hear how he had escaped danger in many parts.
Previously to his going this journey I had an interview with him,
when he told me his intended route:
I said '`it is one of the most difficult you could have formed.`' I knew
that if he gained a passport at all to visit some parts of France,
that it would be from one of the most strict police officers on the continent,
and much I feared the safety of this excellent man;
but when he began to tell me what his religious views were,
and I saw how his heart was bound to his duty, I believed that the Lord sent him,
and that it was His work; I could not doubt of its accomplishment.
So it has proved.
Stephen Grellet is now safely returned to England;
after having passed through armies of Cossacks,
from whom he met with little or no insult.
The blessing of the Lord was with him, and I doubt not made him instrumental of much good.
This gentleman has all the vivacity of a Frenchman, with the solidity of the English.`"]
