== Chapter XXIV.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Dublin Yearly Meeting
* Religious Engagements in the Irish Capital
* London Yearly Meeting
* Various Religious Services in England
* Flanders
* Voyage Home

It was not long before the "`Peace of Paris`" that,
after an absence of a little more than nine months,
Stephen Grellet again set his foot on British ground.
He landed at Harwich on the 1st of Fourth month, and without making much stay in England,
proceeded to Dublin, to the Yearly Meeting there.
He was detained by his religious services in the Irish capital nearly three weeks,
and then returned to England in time to attend the Yearly Meeting in London.
Peace had now been concluded on the Continent,
and several of the sovereigns of Europe were expected to meet in the English metropolis.
His mind had been much exercised on account of the
anti-christian nature and the horrors of war,
and he brought the subject before the Yearly Meeting.
It was concluded that the Emperor of Russia and the King of Prussia
should be addressed on behalf of our religious Society,
in support of the great principles of Peace proclaimed by the Gospel of Christ,
and always advocated and practically maintained by them.
Stephen Grellet was one of the Friends who obtained
interviews with those sovereigns on the occasion.
After this,
various religious engagements in the north and south of England and in and about London,
with a short visit to Flanders,
closely occupied his time and attention till the end of the Tenth month,
when he felt that his services in Europe had come to a close,
and he was at liberty "`to resume in New York Mordecai`'s situation,
sitting at the gate.`"
On landing at Harwich he resumes his journal.

[.embedded-content-document]
--

I was favoured with a short passage from Holland to this place.
My soul felt the overflowing of the love and mercy of my blessed Redeemer;
very graciously indeed has he dealt with me,
one of the poorest and most unworthy of his servants.
Here some of my beloved friends from Ipswich, Richard D. Alexander and others, met me.
Several friends from London, hearing of my arrival, have also come.
My spirit has been refreshed in being thus met by my beloved friends,
after so many months`' separation from them.
Here also I have received letters from America,
after having been long without any from my beloved wife.
The terrible war between the United States and England
has rendered the communication very difficult,
and it has not been less so between England and the European Continent.
The Lord has been very gracious to my beloved spouse
since our separation from each other,
not one of his promises to us has failed.
Blessed and adored be his holy Name.
My faith has often been very weak,
but gracious and merciful has been the Lord in giving me
day by day to be a partaker of his saving help and strength.

Here I have also received the mournful information of the decease of my valuable friend,
Rachel Smith, by which a private and public loss is sustained.
I feel mine severely.
Their house has been a pleasant home to me; a true resting place both to body and mind.
She deeply and kindly entered into my exercises in London.
As an elder in the church worthy of double honour, and a mother in Israel,
I have been attached to her.

5th. I went to Ipswich.
At my dear friend, Dykes Alexander`'s,
I had a precious religious season with several friends who met me there on my arrival,
and another very refreshing one by the bedside of his wife,
who continues a patient sufferer,
with cheerful resignation waiting the Lord`'s time to be released.

6th. I attended their meeting at Ipswich in silence,
but my spirit was reverently prostrated before the Lord
with grateful acknowledgments of his gracious dealings,
guidance,
and preservation from many perils during j my journeying these nine months and a half.
My soul was also poured forth in prayer for those
pious ones whom the Lord enabled me to visit.
I feel still very deeply for them under their soul`'s travail and sufferings.

The seat of war is now transferred to France, and I am in distress for my native land;
will not Divine mercy be pleased to interfere,
so that it will not be rendered unto them as they have done unto others.
I have this day accepted with gratitude a glimmering hope that the merciful
God will avert the threatening evil that seems near to overtake Paris;
for there are more than the "`ten righteous persons there.`"

After meeting I left Ipswich for Chelmsford and Tottenham,
visiting on the way that aged and dignified servant of Jesus, John Kendall.
The feebleness of old age now confines him to his bed, but much sweetness, serenity,
and peace are the covering of his mind; he appears swallowed up in the love of Christ.

7th. I reached Tottenham this morning, in time to attend their meeting:
my soul was made joyful in the presence of God my Saviour.
He has done great things for his poor servant;
thanksgiving and praises were ascribed to Him on bended knees.
Here I was comforted by sitting near my dear friend Susanna Home.
I had left her in the United States, where, as an ambassador for Christ,
she had diligently laboured.
My valuable friends, George and Mary Stacey,
have most kindly invited me to make my home at their house, when in this neighbourhood.
Mary is a sister of my late dear friend, Rachel Smith.
She is a weighty Gospel minister.
I feel great freedom in accepting the kind offer of these dear friends,
and grateful to my great and good Master for his thus opening towards
me the hearts and hospitable houses of such dignified servants of His.

8th. I went to Epping Monthly Meeting, in which I sat in silence.
There are many secret exercises and baptisms to be silently borne.
In the evening I went to Walthamstow, to my very kind friend, William Dillwyn`'s,
where I met with Elizabeth Coggeshall of New York,
lately arrived in this land on Gospel service.
She is one to whom I have long been closely united in near fellowship.

14th. I have been in London attending their several Monthly Meetings,
and the Meeting for Sufferings;
silent travail of spirit in them has been mostly my service.
I feel it a favour that after such long and constant engagements in another nation,
I am permitted now, for a while,
in silence and retirement to commune with my own heart before God,
and to have my strength a little renewed.
My dear friend William Allen is urgent that I should
make my home with him at Plough Court,
when I am in this city, and I accept his invitation.
He is a friend beloved by me; one whose life is spent in acts of benevolence,
but who is designed by our gracious Lord to occupy a station in his church,
beyond that of serving tables.
I look upon him as one of the Lord`'s anointed.
My apprehension respecting his beloved daughter and only child, Mary, is very similar.
I feel bound in Christian affection to these dear friends,
as also to dear Margaret Allen, mother of William; she is a valuable minister,
full of good works among the poor and afflicted.

--

After a short tarriance among his friends in and fioout London,
he crossed over to Ireland, and thus continues his memoranda:

[.embedded-content-document]
--

Dublin, 20th of Fourth month.
Whilst I was in Germany,
before I had seen with clearness the time of my release from that land,
I felt my mind strongly attracted towards the Yearly Meeting for Ireland,
but I left it to the Lord to bring it about.
From the time of my return to England,
it has dwelt upon my mind with weight to come here; accordingly,
accompanied by my friend John Pim, I left London on the 16th,
and arrived here this morning,
where my kind friends Jonas Stott and wife have again given me a most kind reception.

I was engaged in having meetings till the 23rd, when the Yearly Meeting began.
Friends think it has been the largest and the most
satisfactory one that they have had for some years.
Several of the sittings were attended by much solemnity,
for the Lord owned us by his presence;
the Gospel stream also flowed to the refreshing of many.
My dear friend William Forster, who is with us,
has often been greatly favoured in his ministerial labours.

After the close of the Yearly Meeting,
I felt my mind brought under deep exercise for several
classes of the inhabitants of the city of Dublin;
my baptisms on their account were very similar to those I passed through,
some time since, in London.
My beloved friend William Forster, joined me in several of my very arduous services,
as he did then.
We had two large meetings with the soldiers, who are in garrison in the castle;
there are pious men among them, who strongly reminded me of Cornelius the Centurion.
We held also several meetings among the most degraded portion of the inhabitants.
O what a mass of woe and misery have I beheld! how great
is the prevalence of vice and depravity among this people!
I felt at times as if my spirit, together with my outward man,
would sink under the weight of distress.
My beloved friend William Forster was under the necessity
to let me pursue this humiliating service alone;
it was too much for his tender frame to endure.
This engagement, however, was attended with some consolations;
for in several of those abodes, which at first resembled a Sodom, I found a Lazarus,
poor, full of sores like him, but rich in faith:
in others I have been with a weeping Mary, sitting at the Lord`'s feet;
and many also of the meetings,
held among such as seemed to be of the outcasts of society,
have been much more quiet than could have been expected,
and tenderness of spirit appeared in some of them.
The visit I made to their great poor-house has left
impressions that can never be erased from my mind;
several thousands are there crowded together, of every age and sex.
My distress at what I have seen and felt here,
is a true counterpart to what I formerly endured in London.

I had a pleasant visit to the establishment of the Moravians in this city,
especially in the female school, and in the apartment for the sisters.
At a meeting, in an asylum for poor children, a very large number were collected;
and I was comforted in beholding so many of these brought under
tender sensibility whilst I was pleading with them because of sin,
and directing them to Jesus the Saviour of sinners.
Was the same tender and watchful care taken of them,
as is bestowed on many of our children,
how many of these might become bright instruments in the Lord`'s hands;
but even in their neglected state, the Lord is able, by his own immediate power,
and the efficacy of his blessed Spirit, to render them so,
if they are obedient to its manifestation; to this I earnestly recommended them.

These visits kept me closely engaged till the 12th of Fifth month,
when I felt released from Dublin.
Having had two or more meetings nearly every day,
besides several visits between the meetings,
in the chambers or wards of the poor and afflicted,
where I breathed very impure and tainted air, I feel much worn.
The great distress of mind has also much affected me;
for truly I have suffered with the sufferers.
My heart has nevertheless been made glad in hearing of the
entrance of the armies of the allies into Paris,
in a peaceable manner, with very little bloodshed, and that the Emperor Alexander,
instead of retaliating on the French for what they had done in Moscow,
used every means to prevent the effusion of blood,
so that the entrance of the armies into Paris was
more like the coming in of protectors than enemies.

--

The Yearly Meeting in London was now at hand, and, taking his departure from Dublin,
he travelled day and night, and reached the city on First-day morning,
the fifteenth of Fifth month, a quarter of an hour only before meeting-time,
and proceeded immediately to the meetinghouse, in Grace-church street, where he says:

[.embedded-content-document]
--

I found a large number of Friends, many from the various parts of the nation,
having already come in to attend this yearly solemnity.
It has been a good meeting; the Lord`'s presence,
which is the crown of the assemblies of his people, was with us.
The same Divine favour was granted us at the meeting in Devonshire House,
in the afternoon, which was likewise very large.
This evening I feel refreshed in body and mind,
though when I left Dublin I was much worn down.
O how great is the Lord`'s goodness; may not such a worm as I am,
unworthy of the least of the Lord`'s mercies, exclaim with David,
"`all my springs are in Thee!`"

30th of Fifth month.
The Yearly Meeting closed this evening.
Various subjects of great- importance have been under
the very solid deliberation of this body,
and though one of them particularly was of a trying nature,
being an appeal by which the fundamental principles of vital Christianity were assailed,
and these had to be unfolded and defended,
it proved by the Lord`'s help and strength one of the most instructive
and solemn seasons that even the aged present had ever witnessed.

I was brought under deep exercise for suffering humanity,
on account of the cruel scourge of war,
such as I have so awfully beheld during my late engagement in France and Germany;
my soul was poured forth with supplication to the Lord,
that he might open a door for me to plead with the Kings and Rulers of the nations,
that if possible a return of such a calamity might be averted.
Whilst I was bowed under this exercise,
I heard that there was an expectation that the Emperor of Russia, the King of Prussia,
and others, perhaps now in Paris, would come to London.
On this information I felt as if the prayer of my soul might be heard,
and that an opportunity was about to be given to plead before some of these crowned
heads for the Kingdom of righteousness and peace of our Lord Jesus Christ,
which, if not now embraced, might never be offered again.
It appeared also that this was a subject in which
the whole of our Society now collected together,
as a Yearly Meeting, were deeply concerned;
and that a step so important to humanity and religion would have much greater weight,
if felt and proceeded in as the concern of the collected body.
Accordingly, at a suitable time, I opened my concern to the Yearly Meeting.
It brought great weight over Friends;
they felt it a duty to embrace the opportunity to uphold the peaceable
principles of the Gospel before the Rulers of the nations;
but as these crowned heads had not yet come to England, and possibly might not come,
it did not appear proper then to prepare any Addresses to them, but by a suitable minute,
the Yearly Meeting directed the Meeting for Sufferings to act in it,
as soon as way should open to carry into effect this concern of the Yearly Meeting.

A few days after this, the Duchess of Oldenburg, sister of the Emperor Alexander,
who had arrived in London, came to one of our meetings, with several of her retinue;
also the young King of Wirtemberg.
They sat in a very becoming and serious manner.
We had a precious meeting, and the Duchess appeared to feel it to be so to her.
During this Yearly Meeting I received very interesting letters from several of
those pious persons with whom I mingled in Christian fellowship in Germany.
It is very sweet to have evidence that Jesus continues to be precious to them,
and that several little companies have continued to meet
silently together to wait upon and worship the Lord,
from whom only is their expectation.
One of these letters is from Gossner, in Munich,
who tells me that his translation of the New Testament is finished,
and ready for the press.
Several of my beloved friends here have entered into a liberal
subscription to enable him to have a large edition printed;
and the money requisite for the purpose is forwarded to Gossner accordingly.
I believe this is a work that will be productive of much good,
especially to those numerous Roman Catholics who appear
disposed to inquire into the reality of religion.
The more their priests endeavour to prevent them from reading the Scriptures,
the more eager they are to possess them.

17th of Sixth month.
Since the Yearly Meeting I have been closely engaged in
having meetings in this great city and its environs.
The Emperor of Russia and the King of Prussia have come to London,
and the Meeting for Sufferings has met to endeavour
to carry into effect the concern of the Yearly Meeting.
Friends felt deeply on the occasion,
and were united in the sentiment that Addresses to the Emperor
Alexander and the King of Prussia should be prepared;
for which service a committee was separated.
Our meeting together on the occasion was interesting.
Dear Joseph Gurney Bevan took so much interest in it,
that after hearing the views of Friends respecting
the subjects which the Addresses should embrace,
he, though now blind and in great feebleness of body,
nevertheless undertook to prepare these documents.
He has a remarkably clear head, and above all, a very pious and tender spirit.
I am often instructed in beholding in this great
and wise man the littleness and simplicity of a child.

The Addresses having been prepared, were approved of by the Meeting for Sufferings.
My dear friend, William Allen and myself were amongst those nominated to present them.
We had to seek and wait for suitable opportunities, which were difficult to obtain,
so many persons, from various motives, crowding about these Sovereigns.
The King of Prussia was the first to whom we had access.
As he did not understand English, but French, I presented him the Address,
dear William Allen being with me together with two other Friends.
He received us very civilly; according to the custom on such occasions,
he had seen a copy of the Address before, and he was prepared with a suitable reply;
among other things he stated,
that there were some under the name of Friends in his dominions,
and that they were good men.
His attention having been particularly directed to the great misery, vice,
and destruction of human life attending war, contrary as it is to Christianity,
he intimated his strong desire that the love and the peaceable spirit
which the Gospel of Christ inspires might pervade the whole world,
and lamented the sufferings that have attended the last few years.
We presented him also with a number of our hooks, for which he thanked us,
and placed them together with the Address under the care of his Ambassador to this nation,
who accompanied him.

We could not find an opportunity to be with the Emperor
Alexander till the 21st of this month,
though we were informed that he had heard of our intention,
and desired to receive us as early as he could.
Dear William Allen and another Friend went with me to the Pulteney Hotel,
at the time appointed by the Emperor.
He came to meet us at the door of his apartment, took us by the hand in a kind manner,
and said that for a length of time he had wished for an opportunity to be with us.
Through the Empress, who was at Baden when I was at Carlsruhe last winter,
he said that he had heard of me and of my visit there.
Then he inquired into several of our religious testimonies, principles and practices,
to which dear William Allen answered in English, which language the Emperor speaks well.
Whilst William was engaged in stating the nature of our Christian principles,
the Emperor said several times, "`These are my own sentiments also.`"
He was very particular in his inquiries respecting our views
and practices in connection with Divine worship,
the ministry, the influence of the Divine Spirit, etc.
He made several very pertinent remarks on these various subjects, particularly on prayer;
respecting worship he said, that God who knoweth our hearts cannot be pleased with,
nor be acceptably worshipped by the observance of outward forms and ceremonies,
or the repetition of words which the wicked and the hypocrite could use,
though continuing in their sinful practices;
but that a worship in spirit and in truth is the most acceptable to God, who is a Spirit,
and that before him our own spirit must be reverently prostrated.
Respecting prayer, he said, "`I pray every day, not in a form of words, but as the Lord,
by his Spirit, convincing me of my wants, enables me to do.`"
We entered fully on the subject of our testimony against war, to which he fully assented.
He made several other inquiries of a religious character, which having been answered,
silence ensued, during which, feeling my heart warmed by the love of Christ towards him,
and under a sense also of the peculiar temptations and trials
to which his exalted station in the world subjected him,
I addressed a few words to him; his heart appeared sensibly and tenderly affected;
with tears, he took hold of my hand which he held silently for awhile, and then said,
"`These, your words, are a sweet cordial to my soul,
they will long remain engraven on my heart.`"
We furnished him with a number of Friends`' books, which he received with pleasure,
and on our taking leave of him, having been together upwards of an hour,
he took each of us by the hand, and said, "`I part from you as from friends and brethren;
feelings which I hope will ever remain with me.`"

After we had left, the Grand Duchess, his sister,
sent a request to us to furnish her with books like those we had presented to the Emperor,
which was cheerfully complied with.
Here I may say that the Emperor and his sister, accompanied by Count Lieven,
his Ambassador, came to one of our meetings, at Westminster Meetinghouse; William Allen,
who knew of their intention, through the Ambassador, accompanied them.
It proved a good and solemn meeting.
The Emperor and Grand Duchess, by their solemn countenances and religious tenderness,
gave evidence that they felt it to be so to them.

I felt my mind much relieved after this service with these crowned heads,
particularly as I had a full opportunity to lay before them the enormities of war,
and to direct their attention to the peaceable Spirit of Christ;
Alexander especially appeared deeply to feel the subject,
and to be sincere in his desire for the promotion of harmony, love, and peace,
throughout the world; he told us that his concern had been great,
that the several crowned heads might conclude to settle their differences by arbitration,
and not by the sword.

--

After these interesting interviews Stephen Grellet went down to the North of England,
and attended the Quarterly Meetings of York, Durham, Westmoreland, and Lancashire,
holding many meetings by the way, and in returning to London.

[.embedded-content-document]
--

I left London on the 25th of Sixth month for Yorkshire, accompanied by my dear friend,
George Stacey, Jr.
At Bradford I had two very solemn meetings.
Here I felt deeply for my beloved friend, Sarah Hustler,
who was under great weight of religious exercise,
which she soon after made public at their Monthly Meeting at Leeds.
Her concern is to visit, in the love of Christ,
some parts of Germany and of the South of France.
She obtained the near sympathy and unity of Friends in that Monthly Meeting,
and a few days after, that of the Quarterly Meeting at York.

From the Quarterly Meeting at York I went to that of Durham,
held this time at Darlington;
I was comforted by having at these two Quarterly Meetings and some other meetings
in those parts the company of those truly valuable servants of the Lord,
William and Rebecca Byrd.

After the Quarterly Meeting I returned from Durham into Yorkshire,
having made arrangements previously to my going there,
to have a meeting with the Moravians at their settlement at Fulneck.
No meeting had been held there by Friends before, but Charles Latrobe,
one of their chief men who resides in London, being here, readily made way for me;
he having received an account of my visit to their brethren at Neuwied, in Germany,
as also in Dublin.
The people very generally attended, and the meeting was large,
composed of different characters, though of the same religious denomination.
I was comforted with the evidence that some of them are a pious baptized people,
who not only profess but endeavour to act consistently with the religion of Jesus;
some were tender under the testimony given me to bear among them.
Sarah Hustler accompanied me to that meeting,
at the close of which she was solemnly engaged in supplication.

My dear friend G. Stacey, junior being still with me, we went into Westmoreland,
(S. Hustler being also in company,) and attended that Quarterly Meeting;
then that of Lancashire; thence we returned to London,
having travelled since we left it about eight hundred and fifty miles,
and had more meetings than days.
My dear young friend, George Stacey, has been a very acceptable companion to me;
he has a feeling and religiously disposed mind, and a sound judgment for his years.
He appears ripening in the Truth,
and preparing to walk in the footsteps of his valuable father,
who is a man of a strong mind.
I have seldom met with one more guarded in his religious movements;
nor do I recollect to have heard him speak more than
once on any subject in our Meetings for Discipline,
however important the subject, or ever so much felt by him.
When, one day, I told him what I had observed, he replied,
"`I think it is proper for me before I speak on any subject to
endeavour to have a right sense of it in its various bearings,
and then to know that it is my duty to speak upon it; if so,
I consider that I ought to do it in as brief but as clear a manner as I can;
having done so, I leave it to the meeting to judge and act;
should Friends not see as I do,
my repeating the same thing again would not be better understood,
nor alter their own views.`"

I continued engaged in and about London till the 24th of Seventh month.
My mind, during this time, has been under deep depression,
feeling again heavily for the woes and miseries of afflicted humanity,
both in London and throughout the nation, and Ireland also.
It felt as if my soul was brought into their souls`' stead.
The accounts that I received from various parts of
the Continent which I visited last winter,
especially from Germany and Switzerland, very deeply affect me.
Several of the pious persons I then visited have
died in consequence of the sufferings they endured;
others are reduced to poverty, who were before in a degree of affluence.
My sorrows are also stirred up for my friends and near relatives in America,
and the people at large; the cruel scourge of war, and its concomitant evils,
prevail among them.
O that the people would learn righteousness,
whilst the judgments of the Lord are thus poured forth upon them!

--

A short time was now occupied in a visit to Kent and Sussex,
from which he again returned to the neighbourhood of London.

[.embedded-content-document]
--

Accompanied by Robert Forster, I went into Kent and Sussex.
From Rochester I went on board a large prison-ship, below Chatham,
to endeavour to have a meeting among the prisoners of war on board.
They were generally Danes and Norwegians.
Many of them were taken on merchants`' vessels; some during their fishing excursions.
A very remarkable visitation of the Holy Spirit took place on this prison-ship;
three or four of the prisoners felt so powerfully convinced of sin,
that they sat together in the crowded ship weeping and praying.
This drew upon them the sneers of the crew, and the abuses of their fellow-prisoners;
but they bore all with so much patience and meekness,
that some of their persecutors felt constrained to join them.
Through living faith in Jesus Christ, the Saviour of sinners,
some of them now felt their sorrow because of sin to be exchanged for joy and gratitude,
a lively hope being begotten in them in His mercy and redeeming love.
Their minds were so far illuminated by the Spirit in the deep things of God, that,
witnessing a spiritual communion with the Father of Spirits,
a right sense was given them of the nature of that
worship which is in spirit and in truth;
they accordingly sat together in silence, having their spirits gathered before God,
undisturbed by the noise about them, or the revilings and reproaches,
and even the stripes inflicted upon them.
What greatly encouraged them was, that amidst so much suffering their number increased,
and several of their most cruel persecutors became one in spirit with them,
and in their turn,
endured with Christian patience the same sufferings
that they had before inflicted upon others.
During that time some on board,
happening to tell to the men in a boat which had brought provision to the ship,
what a strange people they had among them, one of the boatmen said,
"`They were like the Quakers.`"
That account came to the knowledge of a Friend,
who sent to the ship a copy of "`Barclay`'s Apology,`" in the Danish language.
The little company read it very carefully,
and found there several Christian testimonies of which they had been convinced before.
They easily apprehended that against war and oaths, and in favour of silent worship, etc.
Their number increased to thirty, nineteen of whom are Norwegians.
Their good conduct attracted the attention and kindness of the captain of the ship,
who generously granted them several privileges.
He received me and the friends that accompanied me with great civility:
he had the spacious decks covered with awnings, and seats prepared,
and we had a meeting with about seven hundred prisoners; many were much affected.
After this we had a private opportunity with about forty of the Norwegians and Danes,
whom the Lord has so mercifully visited.
It was a very tendering time.
They appear acquainted with genuine piety.
Free communication was allowed us on board this ship,
because peace is now made between the European nations.
These men are waiting till there is an opportunity
to send them back to their respective nations.
I went after that along the seashore to Maidstone, Canterbury, Margate, Dover, etc.,
etc., having meetings in those places, besides being among Friends separately.
I had searching and trying services in those parts.
The love of money is like a canker; it destroys the tender life.

Seventh month, 29th. On my way from Folkstone to Lewes,
I stopped at the house of Nathaniel Rickman,
who gave me an account of a very unexpected visit that the
Emperor Alexander and his sister had made to his family.
On their way to Dover, passing by the house of Nathaniel Rickman, who, with his wife,
was standing at their door, the Emperor, from their dress,
soon recognized them as Friends.
He ordered his carriage to stop, and he and his Bister went into the house,
which is a neat, comfortable farm-house.
They cheerfully partook of the refreshment set before them.
They visited every part of the house, even the dairy,
and found everything in such neatness and order that they were much pleased,
and particularly noticed the very becoming behaviour of the children.

I visited the meetings in Sussex, and came to Tottenham the 4th of Eighth month,
much worn in body and mind; I had had two meetings almost every day,
and some of them of a trying nature.
O the distress that I have endured in some places.
My blessed Lord has enabled me, however, to labour faithfully and honestly among them.
There is a small remnant left in those parts, by whom the name of the Lord is exalted.

I arrived here in time to attend the funeral of Anna, wife of John Sanderson.
She was a valuable minister.
The meeting was a solemn one.
The sense given of the preciousness in the sight of the
Lord of the death of his saints was very animating.

--

His mind was now again brought into close exercise on behalf of
some of his "`suffering fellow-men,`" and about this time he writes:

[.embedded-content-document]
--

I had hoped for a release from further religious services in this land,
and to be set at liberty by my blessed Master to retire
from this long and arduous field of Gospel labour,
and to return to America to my beloved family; but the Lord,
whose sole right it is to direct my steps,
has given me to feel that my bonds in this great city of
London and in some other places are not yet loosed.
My soul has bowed very reverently before Him,
to whom I have made the surrender of myself and all, and I said, "`Here am I Lord,
do with me whatever thou pleasest,
only condescend to uphold me and preserve me from
bringing any reproach on thy blessed cause,
and be pleased in the end,
through thy Divine and unmerited mercy in Christ Jesus my blessed Redeemer and Saviour,
to receive me to thyself.`"

My mind feeling attracted towards such of the poorhouses
in London as I had not visited before,
I felt peace in yielding to that service of love
towards this portion of my suffering fellow-men.
My beloved friend, Mary Stacey, joined me in these visits.
Our spirits were much affected in beholding so many of our
fellow-beings brought low under affliction and infirmities.
Some of them were once in easy circumstances, but are now obliged, in advanced life,
to avail themselves of the refuge that a poorhouse offers them.
The number of inmates in several of these places is pretty large.
The managers of them were very ready to make way for our visits,
and to collect the people together.
The Lord graciously condescended to be near to us,
repeatedly fulfilling the saying that "`to the poor the Gospel is preached;`" giving
us also joyfully to believe that to more than a few of the poor in the world,
the blessing annexed to the poor in spirit doth belong.

I also visited again the houses of refuge opened to the poor, destitute,
and once degraded females.
Many tears are poured out there by some of them, in the remembrance of the past,
and songs of joy also are heard, for the unmerited love and mercy of a gracious Redeemer.

I had much satisfaction in another visit to the establishment for Jewish children,
where about one hundred and forty boys and girls
are instructed in the principles of Christianity;
but I have especially been comforted in the house of refuge,
opened for the reception and instruction of those young females among that people who,
obliged to leave the paternal home on account of persecution,
or turned out of doors because of their disaffection to Jewish principles,
have found a safe retreat here.
Some of them manifest much religious sensibility.

Whilst thus engaged in feeling for and labouring among suffering humanity,
my concern towards the members of our own Society did not abate;
but I attended all our meetings in and about London.
The more I have mixed with persons of other religious denominations,
the stronger has become my attachment to our own
Society and the Christian principles which we maintain.
I rejoice greatly indeed in having met with individuals,
yea many in the several nations where I have travelled,
who are very near and dear to me in spirit,
and who I believe love the Lord Jesus in sincerity; but I met with no people, who,
as a religious body, maintain doctrines and testimonies,
so scriptural and agreeable to vital Christianity,
as does the religious Society of Friends;
and my great concern and frequent labour for this people are,
that they may not only believe in these principles and Divine Truths,
but also walk uprightly and with faithfulness in accordance therewith.

--

At the conclusion of these services in and about London,
his attention was once more turned to some parts of the Continent,
and "`believing that he had a little further debt of Gospel love to discharge in Flanders,`"
he "`resigned himself to the Lord`'s requirings,`" and crossed over to that country.

[.embedded-content-document]
--

On the 14th of Ninth month, accompanied by George Stacey and Joseph Foster,
we came to Margate, and set off immediately by the packet for Ostend;
we were favoured with a good passage.
My soul was reverently prostrated before the Lord who,
in his adorable goodness and mercy,
gave me to partake of the calm and serenity that
prevailed over the waters below and the skies above.

We proceeded pretty directly to Ghent, where I continued some days,
but found very little opportunity for service among the people,
except with a few individuals; the inhabitants are strongly entrenched in Popery.
I found much greater openness in Brussels and Antwerp,
where I had several public and private religious services.
Some of those meetings were owned by the dear Master`'s presence;
but my soul was rendered sorrowful under the feeling of the sufferings
that the people in these parts have endured during the war,
and the little improvement that they have made in the fear and love of God.
The conduct of many of them seems indeed to proclaim
that the fear of the Lord is not before their eyes.
Besides this I hear of several bloody battles that have been fought in America.
I have indeed mingled my tears with my bread.

Whilst at Brussels I heard an interesting circumstance respecting
the Emperor Alexander when he was in that place.
He had taken a walk through the streets alone, in plain garments,
so that his rank was not observable by his dress.
A heavy rain came on, which induced him to look for shelter.
A tailor`'s shop being near, he went in, and entering into conversation with him,
inquired about his family, and how he succeeded in his business.
The tailor, by his answers, manifested that he was a pious and conscientious man,
but under pecuniary embarrassment, not being able to pay the rent of his house and shop.
Alexander left him without making himself known; but,
to the great surprise of the tailor, a few days after,
a person came to him and handed him the title-deed of the house he lived in,
made out in due form to him.
It was not till some time after that he found that
his benefactor was the Emperor of Russia,
and the same unknown person who had taken shelter in his shop.

My mind being now released from these parts,
we returned to England by way of Dunkirk and Calais.
We escaped some serious dangers on the road; for our carriage having broken down,
it was night when we came over the sands, where we missed our way,
of which we were warned only by hearing the roaring of the sea coming towards us;
there the tide rises to a considerable height,
and for a while we could not discover any elevated place to retire to;
but a small light that we perceived at a distance, to which we directed our course,
brought us again into the right path.
Next morning, leaving Dunkirk very early before daylight,
we had another narrow escape from falling with carriage and horses into a deep ditch.
Notwithstanding all this detention,
we were favoured to arrive at Calais in time to got on board the packet for Dover,
just ready to sail.
We had a boisterous passage, and I was very sick.
On landing, I went direct for London.

Hearing that there was a Cartel ship at Dartmouth, nearly ready to sail for New York,
I felt my way pretty clear to endeavour to go by her.
My mind being now released from continuing longer at present in this land,
the sound of the trumpet of retreat appears to be clear,
and O what a favour to have a perceptible evidence of the Lord`'s guidance,
both in our going out and in our coming in.

The necessary arrangements having been made,
and liberty from the government being given to take my passage in the Cartel,
called the Jenny, Captain Myers, I left London on the 19th of the month,
being accompanied by my dear and valuable friends, G. and M. Stacey.
We reached Dartmouth on the 25th,
where several dear friends from London and other parts have kindly come to meet me,
to bid me once more farewell in the Lord; and truly we may say,
that it is in the fulness of the love of the Gospel, and the precious fellowship thereof,
that we part one from another.
I have however been introduced into deep exercise, and close searching of heart,
to know if it was indeed right for me to embark in this ship.
It is stated by persons who profess to know the vessel, that she is not seaworthy.
Some of my friends, alarmed at these reports, are very unwilling that I should go by her;
but there is no other vessel going,
and in this time of war it is very seldom that even Cartels go.
I endeavoured to wait for and ask counsel of the Lord.
I believe she is a poor vessel, but my trust is in the.
Lord, that she will bring me safely over to America,
and I feel a sweet calmness and peace of mind in the prospect of going by her.

--

After taking a solemn leave of his beloved English friends,
Stephen Grellet went on board the Cartel about eight a.m., on the 29th of Tenth month,
and the vessel set sail from Dartmouth a few hours after.
They had thirty cabin, and seventy-five steerage passengers.
Though the former paid a high price for their passage,
they soon discovered that the captain had very insufficiently provided for their wants,
and found it needful, before leaving port, at their joint expense,
to lay in a good stock of additional provisions of various kinds of their own.
They had "`a boisterous,
uncomfortable voyage across the Atlantic;`" the vessel proved leaky;
their beds were often wet,
and the cabin floor was sometimes several inches deep in water;
they were frequently exposed to much danger, and their prospects were often gloomy.
"`Yet the Lord,`" writes Stephen Grellet,
"`condescended very graciously to keep my mind in confidence and peace,
trusting in him amidst our various difficulties and perils.
The evidence he had given me, as I thought, that the ship should carry me safely,
continued as an anchor to my soul, even when my fellow-passengers were in great dismay.`"

[.embedded-content-document]
--

"`When in sight of the Jersey shore,`" he continues,
"`we had so nearly finished the provisions which could at all be eaten, that,
on coming near Sandy Hook in the evening, we partook of our last scanty meal.
That night was very stormy, threatening to blow us out to sea again.
The captain at last thought he might succeed to reach Newport; but,
to our great thankfulness, the wind altered; a pilot came to us,
and by ten o`'clock we were near the lighthouse.
The account of our situation soon reached New York, when some of our kind friends,
officers of the Custom House, several of whom knew me, went to some of the hotels,
and put in requisition some of the provisions they had ready prepared,
which they brought to us in a pilot boat, and through their kindness we made a good meal,
after a long fast.
My soul was reverently prostrated before the Lord for the preservation extended to us.
His own arm brought us deliverance.
At seasons,
when violent winds and foaming billows assailed our very frail and shattered vessel,
and my fellow-passengers saw no possibility for us to escape a watery grave,
this gracious promise, '`Thou wilt keep him in perfect peace,
whose mind is stayed on Thee, because he trusteth in Thee,`' was revived.
Thus did my gracious Lord uphold me, and deliver me;
forever adored and praised be his Holy Name.
How often has he, in the course of these last three years and a half,
greatly magnified his name.
He has been my refuge and strength, and has never failed me.
I have travelled during this engagement about twenty-six thousand miles by land,
besides several thousands by water,
and have had during that period nearly as many meetings as days.
I went out poor; I return poor--very poor in spirit;
and yet I can truly say that I have not lacked any thing.
It is the Lord`'s doing, and to him the whole praise and glory are ascribed!
On my arrival at New York I found that my beloved wife was at Burlington.
We soon met there, and rejoiced together in the Lord for his great goodness to us both,
exciting a desire that, through his Divine grace helping us,
we may stand offered up to him and his service to the end of our lives.`"

--
