== Chapter XXV.

Partnership with Robert Pearsall--Prospect of Further Religious Service--Visit to Hayti

On his return from Europe Stephen Grellet again took up his residence in New York.
"`I found it my place,`" he remarks, "`as early as I could rightly do so,
to engage again in some business, that, by the Lord`'s blessing on my exertions,
I might have the means to defray all needful expenses,
should my dear Lord and Master see meet to call me
out again in the service of his glorious Gospel.
I did not desire great things for myself,
but I felt there is a blessing in being able to give, even a little only, to others,
rather than be under the necessity of receiving.`"

Way soon opened for his entering into partnership with his brother-in-law,
Robert Pearsall.
They "`endeavoured to conduct their business with all prudence, attending,
in the management of it, to the restrictions of the Spirit of Truth.
The Lord prospered them in their undertaking, and it was even becoming a lucrative one.`"
But it was not long before an impression was made on Stephen Grellet`'s
mind that he must "`stand loose from the world and every earthly object,
and hold himself prepared for further service in distant parts of the Lord`'s heritage.`"
In allusion to this he remarks:

I had entertained a hope that I had accomplished in.
Europe the whole of the work that my dear Master had for me there;
and very sweet peace had continued to attend me,
when I recurred to the deep and peculiar exercises, and the nature of my services there;
but now I beheld such a field of further labours in those nations,
as well as in the West Indies, which I should have to enter,
that my soul was dismayed at the prospect.
The North of Europe, Norway, Sweden, Russia, parts of Asia Minor, Greece, Italy, Rome,
many parts of Germany and Spain, etc., were brought into view,
as portions of the earth where I should have to proclaim
the Lord`'s redeeming love and power.
Strong and awful was the impression made on my mind,
that I could not enter into my Master`'s rest till this work was accomplished.
With this a little faith was given that Omnipotence
can enable to perform what to man seems impossible.
I bowed very low before the Lord, and through the aid of his Divine grace,
I was enabled to say: "`Here I am, Lord! do with me as thou wilt; only go with me,
and fulfill again thy blessed promise,
as thou hast so graciously done on every previous occasion when
thou hast sent thy poor servant on thy Gospel errands,--'`I will
teach thee and instruct thee in the way in which thou goest;
I will guide thee with mine eye.`' O Lord! thou hast not only guided thy servant,
but also helped, sustained, and, to this day, preserved him, a monument of thy goodness,
mercy, and power.`"

Whilst thus exercised in the midst of his outward engagements,
and enabled to stay his mind on God in the prospect of what
was before him in regard to the nations afar off,
and the people of other religious denominations,
his love and Christian solicitude were kept alive
towards the members of his own religious Society,
both in the City, and the Quarterly and Yearly Meetings to which he belonged.
The invidious workings of "`the spirit of error,`" assuming
the garb of an "`angel of light,`" deeply affected him.
"`The light of the Gospel of the glory of Christ`" had shined upon his own heart,
and with an eye sharpened by love to the Redeemer,
he was very quick-sighted in regard to everything
derogatory to his Divine character and offices.

"`I have deeply lamented,`" he remarks in reference to these things,
"`because of the gradual ascendency which the grand enemy of Truth gains over many minds.
Some are carried away by a worldly spirit,--others by that of Antichrist,
under a specious appearance of sanctity.
Attempts to detect it, or to proclaim against it,
have no more place in the minds of many than had the endeavours of Lot
to prevent his sons and daughters from falling in the overthrow of Sodom;
he seemed to them as one that mocketh.
Nevertheless, I have felt it to be my duty to labour in love with individuals,
and particularly with Elias Hicks.`"

Little more than a year had elapsed since his return to the bosom of his family, when,
"`for Christ`'s sake and the Gospel`'s,`" he felt constrained
to make preparations for again leaving all.
In recurring to his previous prospects, he continues:

For months the exercise on account of several parts of Europe, where I have not been,
has been heavily on my mind; but after waiting carefully upon the Lord,
that he might order my ways in his counsel, I have felt that, for the present,
Hayti only is the part to which I must go.

In the forepart of the year 1816,
the time appearing fully to have come for me to go to St. Domingo,
and pay a visit in the love of Christ and his Gospel to the coloured population there,
according to the good order of our Society, I spread my concern before my Monthly,
Quarterly, and Yearly Meetings.
They severally entered feelingly and tenderly into
sympathy with me under my Gospel bonds,
and gave me their certificates of unity with my religious concern.
I left my temporal affairs under the care of my partner, and, on the 25th of Sixth month,
1816, taking a solemn and affectionate leave of my beloved wife and dear friends,
I went on board the schooner Remittance, bound for Les Cayes, Hayti.
My dear friend, John Hancock, a member of New York Monthly Meeting, accompanied me.
His affection for me, and his love for the cause of Truth,
prompted him to make this free-will offering.

The time of Stephen Grellet`'s visit to Hayti was an interesting period in its history.
In the fearful struggles which broke the chain of slavery,
and ultimately secured the political independence of the island, Toussaint L`'Ouverture,
that noble hearted negro patriot,
had been wickedly betrayed into the hands of his enemies, and carried away,
with his family, to France, where, under the cruel despotism of Napoleon,
he had been suffered to "`pine away and die in the dark, damp,
cold prison`" of the Fort of Joux.^
footnote:[Beard`'s Life of Toussaint L`'Ouverture.]
The French, nevertheless, totally driven away from St. Domingo,
had left the government wholly in the hands of the freed sons of Africa.
Dessalines, himself once a slave, having assumed and greatly abused the supreme power,
under the title of Emperor, had been dethroned and slain.
Christophe, the negro chief, having accepted the reins of government,
had been opposed by Petion, the mulatto general,
and years of conflict between the two competitors had ended in the former
establishing his power in the north under the title of King Henri I.,
and the latter retaining a firm position as President of the new Republic in the South.
The horrors of war had been succeeded by the blessings of peace.
Christophe was pursuing a course of gradual improvement in his northern dominions;
while Petion, relieved from the cares of military operations,
successfully applied all his powers to the amelioration
of the condition of those whom he governed.
Accessible and courteous to all,
and labouring indefatigably to secure the due cultivation of the land,
to administer justice, to promote order,
and to lay the foundation for the intellectual and moral improvement of the inhabitants,
he had gained the general good-will, and was beloved by his fellow-citizens,
when Stephen Grellet and his companion landed on
the southern shore of the island of Hayti.

They had a prosperous voyage, and only one fellowpassenger.
When the weather allowed, they held religious meetings on board their vessel twice a week.
These were generally attended by all that could be spared from the ship`'s duty.
On landing in Hayti, Stephen Grellet remarks:

We were favoured to arrive at Les Cayes on the 17th of Seventh month.
We soon became acquainted with some serious characters,
who have received us with much kindness.
After visiting some of them in their families,
my way has opened for an attempt to spread the notice
of a religious meeting among the inhabitants.
It was for a time discouraging,
because of the obstacles put in the way by some Spanish priests and friars;
but notwithstanding their malice, I felt it to be my duty to pursue my prospect,
and commit the result to the Lord.
A spacious place was provided, and the meeting was largely attended.
Among those present were the General-in-chief of the Department, several generals,
and military and civil officers.
Some of these are entirely black, others are of lighter complexion.
One of the Romish priests also attended.
All conducted themselves with propriety;
and after meeting several expressed their gratitude in that the
love of Christ had constrained me to come and visit them,
some saying their hearts were prepared and open to receive such doctrines as I had communicated,
for they were disgusted with their Romish priests,
whose conduct they considered to be a reproach even to morality.

30th of Seventh month.
I have had five additional meetings, generally well attended.
I had one for the white population here,
among whom the testimony of Truth given me to bear was of a close nature,
for which I find there is great cause.
I have been comforted among some of the people, who manifest a tender conscience.
Having brought with me Bibles and Testaments in French, and books and tracts of piety,
they are gratefully received.
Our visits to many families have been seasons of edification and instruction.
We purchased horses here to take us to Portau-Prince.
The roads in this part of the island are not suitable for carriages:
it was also necessary to hire a guide to go with us.

Leaving Cayes, we went the first day to the habitation of General Borjellat,
a handsome looking mulatto.
He received us with courtesy and hospitality,
and very readily made way for a meeting to be held in a spacious room in his house;
his large family and about one hundred persons who work on his sugar plantation attended.
The Lord`'s presence and power was over us,
so that many of those sable countenances were bedewed with tears
under the contriting sense of the visitation of his love to them.
We set out long before daylight on the next day,
as in this hot climate it is necessary to do so, for after nine o`'clock a.m.,
the heat of the sun is powerful, and travellers try to avoid it.
We arrived at a small town called Cavarillon; where,
feeling my mind engaged to have a meeting, the Romish priest readily promoted it.
He united with others in giving immediate notice,
and the inhabitants very generally came to it.
The word preached on the occasion appeared to have an entrance in many of their hearts,
and the priest, who had been very attentive in meeting, was kind and civil after it.
We took a late breakfast after meeting, time not having allowed us to do it before,
and then rode under a warm sun to St. Louis.
It was formerly a town of note,
but during their wars it has been rendered a place of ruins.

By three o`'clock next morning we were again on the road, wishing to reach Acquin,
thirty miles distant, in time for breakfast.
Here I felt it my religious concern to have the inhabitants called together.
A meeting was appointed at four p.m. The notice spread so quickly in the country, that,
with the people in the town, a large number collected.
The meeting was held out of doors.
Through Divine aid, the Gospel was largely declared unto them.
Though some of them have pious minds,
yet the greater part were very ignorant of the things pertaining to truth and godliness.
At first they appeared not to like to have their sins set before them,
and what must follow if they die in them; but after awhile,
the power of truth came so forcibly over them, that they trembled under it,
and many tears were shed by them.
I was forcibly reminded of what our ancient Friends sometimes said of their meetings,
"`there was a general convincement among them.`"
O that conversion may follow!

The next day we set off at two a.m.,
having a long distance to go to a place on the road where we might obtain some refreshment.
Though we travelled fast we did not reach that place, a kind of inn,
till ten o`'clock. The master of the house cultivates a small coffee plantation,
some bananas and Indian corn.
He resides on the mountains, and has very few settlers near him.
He immediately sent his young daughter some miles
distance to obtain some eggs for our breakfast.
Whilst this was preparing, he requested our assistance in endeavouring to learn to read.
The little he has acquired thus far has been by the
aid of the few travellers who come that way,
and can spare a few moments for him.
What he learns he imparts to his children, who are nice, well-behaved blacks.
He was much pleased on my presenting him with a New Testament.
We reached Miraguano that night.

Long before daylight we were again on the road next morning, when,
after passing through the Little Gonaive, and the Grand Gonaive, we succeeded,
though not without great efforts, to reach Leogane that night.
We passed over a very difficult road; a great length of it winds through a narrow space,
between high hills or mountains, through which also runs a stream called a river.
We crossed it above thirty times during the day.
In some places the water came up to the middle of our horses, generally above our knees;
and riding under a broiling sun rendered it very uncomfortable.
We met at Leogane a few individuals who appear to be serious persons,
with whom we had some satisfactory intercourse.

I felt my mind pressed to go to Port-au-Prince also;
and on reaching that place we paid an early visit to the President, Alexander Petion.
He had heard of our arrival, and was desirous to see us.
He received us with much affability,
and expressed his gratitude that the Lord has put it in
our hearts to come and visit them on this island,
and has prospered our way thus far.
Petion is a large, portly man, of a rather handsome and pleasing countenance,
a light mulatto, very plain in his apparel and simple in his manner of living;
in this he acts from principle,
to give an example to his officers that they may not oppress the
people to obtain the means of supplying the expenses of high life.
He is also a very humane man,
and is not known to have ever sanctioned taking away the life of any offender,
even of those who have conspired against him.

Eighth month, 11th.--I have had several meetings for Divine worship since my coming here.
There appears to be a great openness in the minds of the several classes of the inhabitants;
some are drawn evidently by no other motives than those of curiosity;
but sincerity appears in others.
The meetings hitherto have been held in private houses;
but the President was anxious that the meeting on
First-day should be held in their large Romish Church,
that being the largest and most convenient place to accommodate the people of this town,
and the country round.
I endeavoured to set before the President the objections that some might have against it,
the priests particularly; but he could not see any difficulty in the way.
"`The meetings that you hold,`" said he, "`are meetings for Divine worship,
and for this very purpose the church has been built.`"
Moreover the chief-priest came yesterday to see me, and said that he had no objection,
nor did he think any one else would have.
He appears indeed, to care very little about religion.
His emolument, twenty thousand dollars a year, is his great object.
He told me that he did not hoard up that money, but expended it as freely as it came.
It was trying to me to have a meeting in that place,
but I felt it my duty to see the people; for this purpose I have come here,
and therefore I agreed to have it appointed.
It has been largely attended, many persons from the country coming to town.
Great was the travail of my spirit for this large congregation.
The Lord condescended to hear my prayer, and to reveal his power among us,
and to cause the stream of his glorious Gospel to flow.
The nature of pure and undefiled religion before God the Father was set before them,
together with its fruits.
The fruits of false religion were also described.
Christ, the Saviour of sinners, was largely preached;
and they were earnestly entreated to come to Him, who, by His Divine Spirit,
reveals Himself to be very near to seek those who are lost in their sins,
and to save them.
Much quietness prevailed among that multitude, and many appeared tender.

12th. This evening I had a more select meeting, and a precious season it has been.
The people now appear to understand the nature of silent worship;
a solemn silence prevailed over us.
The company, very generally, were in tears,
and feelingly united in the acknowledgment that was made, on bended knees,
to the love and mercy of a gracious and compassionate Redeemer,
and the prayers offered for his grace and Spirit
to enable us so to live as to bring glory,
and no reproach, to his Holy Name.

18th. I have had one or more meetings every day during this week.
They were held in the several parts of this city, so that most, if not all,
the inhabitants have had an opportunity to attend them.
Those in the evening, however, are attended chiefly by a select company,
whose hearts appear in earnest to seek the Lord and his Truth.
The greater part of these are females.
This morning, being First-day, I had a meeting with about six thousand of the military,
who were collected before the palace of the President,
and stood in close ranks near the porch,
where seats had been prepared for Petion and his chief officers,
about two hundred in number.
The President sat by me.
I was enabled to preach the unsearchable riches of Christ,
describing the nature and blessedness of his kingdom of righteousness,
peace and joy in the Holy Ghost;
urging them to come and range themselves under the standard of the Prince of Peace,
who would enable them to bring forth the fruits of peace.
As the weather was very calm, and great stillness prevailed among the people,
(for many of the inhabitants had collected besides
the soldiers) my voice was heard distinctly by all.
About an hour after I had retired to my lodgings, the General-in-chief, Boyer,
with most of his staff, came in to express to me, on behalf of the military at large,
their grateful acknowledgment.

19th. I had another large meeting this morning; then we went, by invitation,
to dine with the President at his country seat.
He lives very abstemiously himself, drinks water only, and eats of but one kind of meat;
but keeps, however, a good table.
There were about sixty persons present, besides his family.
The whole was conducted with becoming seriousness, and a part of it to edification.

21st. Yesterday and today I had three other meetings; one, very largely attended,
was held at Colonel Sabourin`'s. In several of the meetings I have had on this island,
and especially in this city,
I have been led to impress on their minds the duty of paying strict attention and obedience
to the law of the Spirit of life in Christ Jesus written in their hearts,
which would set them free from the law of sin and death;
consequently their rulers would make no other laws than such as coincide with
the dictates of the Spirit of Truth which leads to all righteousness and truth,
and the people would be enabled by the same Spirit to walk uprightly,
keep the law of God, and those enacted by their government.
Thus they would live in peace and harmony one with another;
none would give way to that quarrelsome and revengeful spirit,
which is so contrary to the patience, forbearance and love,
which the religion of Christ calls us to.
I dwelt the more on that subject, because many among this people,
who may be called a military nation,
(for they are all soldiers) are in the shameful practice of fighting and duelling,
even for trifling causes.
Their morals also being greatly relaxed,
and the sacred tie of marriage disregarded by a considerable number of them,
I laboured much, in private as well as in public,
to shew them the necessity of living a virtuous and moral life,
without which it is impossible for religion to grow;
neither can domestic happiness and harmony be witnessed;
nor can a joyful hope be entertained for their children and youth,
whilst the parents set them bad examples.
I frequently pleaded with the rulers of the people, privately, on these accounts,
and I hope not without some fruit with some of them,
who were induced to marry those with whom they had
for many years lived in a state of concubinage.
The subject of a liberal education, coupled with a pious and guarded training,
was held up to their view.
They have indeed many schools, and the children make rapid progress,
and are in no wise behind any white children in intellect and capacity;
but the evils that the French have entailed upon them,
are not less galling and destructive to their minds,
than were the cruelty and oppression of slavery to their bodies.
Besides the bad examples they set them by their immoral lives and their irreligion,
they have left behind them numerous books of the most demoralizing, vicious,
and obscene kind; as well as many deistical works of the French philosophers.
These publications come into the hands of the young people as soon as they can read,
and thus they are early initiated into the evils indulged in by many of the parents.
I have succeeded in having many of those books removed from their schools,
and in their stead I have given them Bibles, Testaments,
and other works of piety and usefulness.
It has been very grateful to me to observe the eagerness
with which some of the people have received the Scriptures;
I had bought several hundred copies with me,
also a pretty large number of useful and religious books.
Among these are many relating to our Christian principles, which are well received.

Another great difficulty to which these people are subjected,
is the very general demoralization of the Romish priests among them,
so as to induce some to turn the religion of Christ into ridicule,
when told that their salvation depends on men who publicly
evince by their conduct that they are the servants of sin.
President Petion sensibly feels these important subjects;
he endeavours to prevent any more priests coming into the Republic.
He has destroyed as many of the bad books as he properly can,
and he tries to counteract their evil tendency by
opening the way for the importation of useful works.
For this purpose he has built a spacious place for a public library,
which he is endeavouring to have well stored.

We left Port-au-Prince on the 22nd of the Eighth month for Duford,
a plantation that belongs to General Inginac, Secretary of State to Petion,
where we had a meeting with the cultivators of that estate and others in the neighbourhood.
The next day we travelled over a pretty high mountain and difficult roads,
on our way to Jacmel.
We forded several times a deep river over which our horses had to swim.
The following day being First-day, we had a meeting at Jacmel,
which was largely attended and very satisfactory:
yet my mind was not released from the weight of religious
exercise I had felt towards the people.
Whilst I was considering whether I must not endeavour to have another meeting there,
a deputation came from the notables of the town,
requesting me to have another meeting among them;
I felt most easy to let it be appointed for the following day.
This was likewise numerously attended,
and was a solemn and very relieving meeting to my mind,
as also were several opportunities I had in their families,
when a large number collected together.
I have found here more tenderness of spirit generally prevailing,
than in most other places.

We went from thence to Grande and Petite Gonaives.
We crossed the windings of a river sixty-two times;
the water often coming up far above our knees.
The people came down the mountains from a considerable
distance to attend the meeting at Gonaives,
which was held out of doors to accommodate them.
They stood very quiet and attentive,
and some of them appeared much affected under the
testimony that the Lord gave me to deliver.
Here, as has been the case in some other places, many of them have said,
"`O if you could come among us once a year only, or let one of your friends come,
we should not want to hear any one else,
and should have done entirely with the priests.`"
After I left the place I heard that the priest was so chagrined
at seeing the people flock in such numbers to the meeting,
that he got into a fit of passion that brought a heavy fever upon him; yet, poor man,
he leads a very immoral life.

The next meeting I had was at Miraguane.
It was held in the house of Colonel Augur, Commandant of the place.
The power of truth was so felt by many that tears
indicated the tenderness of their spirits.
There had not been any priest in that place for some years;
but one had arrived the day before to take possession of the benefice of that parish,
and said his first mass at the very time that my meeting was appointed.
Thus the people had a full opportunity to make their election which to attend;
six persons only went to him, and a very large company attended the meeting I had.

After that meeting we forded Little River, which was attended with some danger.
We lodged at Colonel Adonis`', the Commandant.
He was stolen from Africa when very young.
I find many who were thus carried away from their homes.
Some moving accounts they give of the cruelties they beheld,
and the sufferings they endured.
One of them, whilst relating his sufferings,
was moved to tears in the recollection of them, and added, "`but me must love them,
(his persecutors) and try to render them good for evil, and pray for them.`"
That evening I had an interesting meeting at the house of the Commandant,
but instead of feeling my mind relieved thereby,
a great increase of exercise came upon me,
so that I requested to have notice of another meeting
for the next day spread round the country.
The whole night,
my exercise was such that my soul cried deeply unto
the Lord for his saving help and strength.
It was as if the weight of the mountains was upon me, and I felt so poor and empty,
that I thought I could never more advocate the cause of Truth.
Early next morning, First-day,
I was greatly dismayed at beholding the number of people
who had already come into the town to attend the meeting,
whilst others were seen at a distance descending the mountains round about.
To accommodate such a crowd,
it was considered proper to hold the meeting in their large marketplace.
About meeting time a regiment of soldiers, on their march to Port-au-Prince,
also arrived in the town, and their officers brought them all to the meeting.
Several thousand persons, it was supposed, were collected.
They stood very close round me, and I was placed on the market cross,
or rather Liberty Tree, which is planted in almost every town.
The Lord very graciously condescended to be near to support me on the occasion.
I had been brought very low, but He is riches in poverty, as well as strength in weakness.
It was a quiet, solemn meeting.

That evening I went fifteen miles further to Petit Front,
where I had the next day a meeting, attended by the inhabitants very generally.
There again the Lord`'s contriting power was over the assembly.
Nearly wherever I come there is a wide door open in the people
to receive me and the testimony of Jesus given me to bear.
The fields seem to be white unto harvest.

I had felt some drawings further on towards Jeremie, thirty leagues distant,
but the Lord has been pleased to excuse me from service there,
and to open my way to return toward Port-au-Prince.
We came to Lansavone, and leaving that town early the next morning,
we got to breakfast at the house of a kind, serious man, named Denis,
near the Great River.
We had a satisfactory religious opportunity with his family,
and by the time that we were prepared to proceed on our journey, the waters of the river,
which were very high when we arrived, had considerably subsided,
so that with the assistance of our kind, new friend, Denis,
we were favoured safely to cross, though the water came up to our saddles.
In the evening we reached Miraguane, where we had a meeting,
and early next morning we proceeded towards Great Gonaives,
where we had a very precious meeting at the house of the Commandant, Colonel Simmons.
After the conclusion of it, we set off for Leogane, fifteen miles distant.
A little before our arrival there it began to rain heavily,
and continued to do so in such a manner that at ten o`'clock in
the evening a general alarm was sounded throughout the town,
and every body called out to work, to endeavour to put a check to the overflowing waters,
now rushing into the town, threatening general destruction.
The extensive plain round the town was like a sea;
the water was from three to six feet deep,
and torrents continued to pour down from the mountains.
The streams flowing through the streets were like so many rivers.
We had truly an awful night.
Next morning the whole country around presented nothing but waste and desolation;
the most beautiful, rich plantations had now not a sign of verdure,
nor of good soil left; all had either been carried into the sea,
or was covered with stones and gravel brought down from the mountains;
houses and other buildings, horses and cattle, were in like manner carried away.
It was supposed that the lives of many of the inhabitants had been destroyed.
Heaps of large trees brought down from the mountains,
against which many stones and much sand had accumulated, blocked up the roads.
Had we been only an hour later, the preceding evening,
we must have shared the portion of other travellers who were drowned.
It was indeed reported that we were lost, two Spaniards, who were drowned,
having been taken for us.
The Lord graciously watched over and preserved us.
I felt much for the people in their affliction, and the great bereavement of many,
both by the loss of property, and that of their relatives.
I had a very solemn meeting with the people of the town;
their minds in affliction were prepared to receive and appreciate
the consolations which the Gospel of our Lord Jesus Christ imparts.

The next day I had two other meetings.
That in the forenoon was held in the market-place;
for the crowd who from various causes had come down from the mountains, was great;
and many soldiers had been sent as labourers, to endeavour to assist the sufferers,
so that several thousand persons were collected on the occasion.
It seemed that day as if, "`when the Lord`'s judgments are in the earth,
the inhabitants of that part of the world were learning righteousness,`"--seriousness
prevailed over that numerous assembly,
and the hearts of many were contrited.
The meeting in the afternoon was more select,
and the refreshing from the Lord`'s presence was sensibly felt by many.

I frequently marvel in beholding how among these descendants of Africa,
who have had so few advantages compared to many of the Europeans,
the Gospel stream does flow; and the word preached appears to have an entrance;
they receive it in the simplicity of their hearts, and in the love of it.
I may also bear testimony to their general good conduct and honesty.
One may travel among them with the greatest security.
I have heard that very frequently large sums of money are
sent over these mountains from one seaport to another,
and no attempt at robbery has been known.
Very lately a man had six horses loaded with sacks of dollars,
and one of the sacks had become so worn, that when the driver discovered it,
it was nearly empty.
On his going back he found the dollars scattered on the road for some miles,
and people collecting them.
They immediately gave him what they had picked up, and assisted in finding more.
When the driver sat down to count, he found that only about ten were missing;
and then these men went further on in search,
and at length brought him back every single dollar!
We might in vain look for so much honesty among many of our white people.

The ninth of Ninth month we set off for Port-au-Prince,
and the General very kindly sent one of his officers
to conduct us through bye-paths across the country,
the highway being rendered impassable by the flood.
In some places the Grand River had changed its course,
the former bed of it being nearly dry,
and it now passes through plantations very lately covered with luxuriant sugar cane,
but which are now a bed of stones and gravel.
Our guide took us a good way up to ford it; the water, however,
reached to the backs of our horses;
but we were favoured to arrive safely at Portau-Prince in the evening, when our host,
Archibald Kane, received us with his former kindness.
My dear companion, John Hancock, with myself,
felt our hearts bowed before the Lord with reverent gratitude,
for his great mercies and favours bestowed upon us during that journey.
He has supported us under very great bodily fatigue,
preserved us from a watery grave several times,
and has enabled his poor servant to preach the unsearchable riches of
the Gospel of Christ to thousands of our fellow men of the sable race;
blessed and adored forever be his glorious Name!

10th. At Port-au-Prince.
I have had a meeting this evening with the more select company of this place,
with whom I used to mingle.
There appeared to be an increase of solemnity among them,
and a deep ingathering into the sanctuary of the heart before the Lord.
It appears they have continued to hold their meetings during our absence,
and their dependence being then entirely drawn from man,
and directed with singleness of heart to the Lord, the Minister of the Sanctuary,
they have become better acquainted with the operation of his Divine Spirit,
and have made some advances in the root of religion.

11th. I have been several times with the President and chief men of this place,
for apprehending that the time of my release from this part of
the service that my blessed Master had for me is near at hand,
I desire not to withhold from them any portion of
the Lord`'s counsels which I feel towards them.
The more I am with Petion,
and the more I hear of him by those who during many
years have had full opportunity to know him,
even under the most difficult and trying circumstances,
the more do I feel for him and respect him.
I believe he is truly a great man;
there is that in him which leads me to believe that it is
his littleness in his own sight which exalts him.
He has repeatedly manifested much religious sensibility;
may his heart become more and more enlarged in the love of God,
through Jesus Christ our Lord!

Feeling my mind now very nearly released from further services on this part of the island,
I have had it under my very close consideration to pay a visit
also to that part which is under the government of Christophe.
I am brought into great straits and deep exercise on that account.
If it is my place to go there, I am persuaded that the Lord, my blessed Master,
will show it to me with clearness, and also open a way for me to get there.

12th. I had another meeting with the inhabitants of this city.
It was again much crowded.
To be generally heard, I had to raise my voice considerably, which much exhausted me;
for I was very unwell when I went to the meeting;
but as I apprehended that it might be the last opportunity
of the kind I should have with them,
the weight of my exercise and concern pressed upon me so heavily,
that I felt willing to be spent on their account.
I had very close doctrine to deliver.
I set before them the blessings that would attend them if
they turned to the Lord with sincerity of heart,
and amended their ways and doings,
through obedience to his Divine will manifested to them; and on the other hand,
I testified of the curses, the misery and woe,
that a continuance in sin and vicious practices would entail upon them,
now especially that they had not the plea of ignorance,
for they themselves could now say that the way of life and
death had been clearly set before their view.
It has been a solemn meeting; many of the people have been greatly contrited,
and they felt deeply also when, towards the conclusion, I told them,
that this was probably the last opportunity I should
have thus to plead with them in the love of Christ,
to whose grace and mercy I commended them.
I have felt very unwell since meeting;
it seems as if I were on the eve of having a heavy sickness.

According to the apprehension expressed in the foregoing memorandum,
Stephen Grellet was seized with a severe attack of illness.
On his partial recovery, about a fortnight after,
he makes the following record in reference to it.

The disease made such rapid progress,
that in a few days I was reduced to the greatest weakness;
neither the physician nor those about me thought my recovery possible;
my limbs were already cold.
I was very sensible of my situation,
and that my life did now hang on a very slender thread,
and that it was proper I should stand prepared for the moment of my departure,
should the Lord order it to be so near at hand as it appeared to be.
Accordingly I gave directions for my funeral, and circumstances attending my demise.
My mind, through my dear Redeemer`'s love and mercy, was preserved in much calmness, and,
in peaceful acquiescence with his Sovereign will, prostrated before him.
I marvelled if, in his Divine mercy and compassion,
he would now indeed cut short my work in righteousness,
and release me from the great weight of service which I
have repeatedly felt for many of the European nations particularly.
At the time when I was the lowest,
my concern in Gospel love for these nations came upon me with force,
and the language was proclaimed in my ear, "`Thou shalt indeed visit those nations;
the days of thy earthly race are not yet accomplished.`"
My soul bowed reverently before the Lord, and I said, "`Do with me,
O Lord! according to thy Divine will.`"

The night of the 18th was a terrible one on this part of the island;
there was a great hurricane with an earthquake;
the total destruction of the place was threatened;
many houses were blown away to splinters;
those more substantially built were thrown down,
and the roofs carried away with their contents.
Few in Port-au-Prince escaped being more or less injured; that of Archibald Kane,
in which I am, is among those that suffered the least;
yet nearly all the roof covered with slates has been carried away.
As it rained heavily, I was greatly exposed.
I had at the time a high fever, and the rain fell upon me in torrents;
my beloved companion, John Hancock,
a most kind and faithful attendant on me by night and by day,
removed me "`for I was too feeble to help myself to a corner of
the house that remained a little sheltered from the weather;
but considerations about myself were absorbed in feelings for the mass of the inhabitants,
whose distress was great.
All the vessels in the port were sunk, thrown on their beam-ends,
or cast high up on the shore.
The water ran through the streets in torrents, and brought down from the mountains,
houses, horses, cattle, etc.; men and women, children in their cradles,
were rescued a short distance only before they reached the sea.
The devastation by the hurricane has extended to a considerable distance.
Leogane is nearly destroyed; very few houses are left at Jacmel,
and the shipping is gone;
but the destruction throughout the country is not less than in the towns,
and many lives have been lost.
When Petion was told of the overthrow of a great part of his buildings,
his first inquiry was, "`Is the library safe?`"
being told it was, he said, "`Blessed be the Lord for this merciful preservation!`"
He had lately placed in it a considerable number of valuable books,
that he wished should supersede the many deistical and immoral ones they had before.

A week later, Stephen Grellet continues:

4th of Tenth month.
My strength returns slowly.
I am now able to sit up a part of the day, though the fever is yet high,
and perspiration is very profuse; I have, nevertheless,
concluded to leave this island for New York, and have taken my passage accordingly.
I am of the mind that the sea air is the most likely means
to restore me from the feeble state in which I am.
I have sought the Lord`'s counsel in this movement, not wishing to do anything rashly,
and I believe that in this I have his gracious approbation, not to say guidance.
I had a precious and solemn religious parting opportunity
with a select company of pious persons,
chiefly females, who, during my illness, have paid me every kind attention.
Many a time I have been refreshed in my spirit when
they have been sitting silently by my bedside.
Sometimes, when lying with my face towards the other side of the bed,
on my turning about I discovered half-a-dozen or more of them,
who had come very softly into the chamber, sitting down silently,
their eyes bedewed with tears.
Near relations could not have been more attentive in ministering to me in my sickness,
than many of these dear people were.
May the Lord further the work of his Divine Grace that he has begun in them!

I am entirely released from the apprehension I had that
I might be required to go to the other side of the island;
my beloved Master does not require what my feeble
state of body could not accomplish at present.
This afternoon I have taken a solemn leave of the people here, the President among others.
They accompanied me on board the ship La Franchise, Captain Nuisan.
She is a fine vessel and belongs to the President.
There are fourteen passengers on board, besides my companion and myself.

At sea, 16th of Tenth month.
We sailed early on the morning after I came on board;
we have had very fine weather since; the pure, fresh air has,
through the Lord`'s blessing, proved very salutary to me.
The very heavy chills that preceded the fever, left me three days after I came on board,
and since we crossed the tropic, the profuse sweats have also disappeared.
I have gained strength; but my limbs are so feeble and swollen,
that I cannot take any exercise.
The kind of fever I had is far more dreaded by the
inhabitants of Hayti than the yellow fever;
they are frequently two years lingering under the effects of it.
I am persuaded that my coming to sea has hastened my recovery.
The passengers on board are very civil;
they are mostly young men who had been enticed from
the United States to go to South America,
under fair promise of great advantage, but after being at sea,
the designing Captain changed his flag,
and they found that the vessel was to be used as a pirate.
Such vessels frequently came into the harbour of Port-au-Prince from America.
I saw, from my chamber, their manoeuvres in changing their flags,
and generally they hoisted up that of some of the Republics of South America;
sometimes there was fighting among them because of the unwillingness
of some on board to submit to become pirates.
The passengers on this ship are of that class;
they have made their escape from one of these vessels.
I have had some meetings with them, and the crew of the ship.
Some of them appear to appreciate the privilege,
and greatly rejoice at having escaped the dreadful life of a pirate.
Their escape has been at the peril of their lives.

20th. The weather having been stormy the last few days, my sickness has come on again,
with a return of fever; but, through the Lord`'s tender mercy,
my mind is preserved in sweet peace, and,
while retracing my steps on the island of Hayti,
the nature of my religious exercises and services among that people,
the Divine help vouchsafed in those large meetings,
and the preservation mercifully granted from the various
dangers that have attended the crossing deep waters,
etc., my spirit is contrited, and ascribes praises and glory to the Lord, my Redeemer.

26th of Tenth month.
Favoured to arrive safely in New York, and to find my beloved wife in good health.
We have united in thanksgiving and praises to the Lord.
Though he has afflicted me sore in my outward man, his love, goodness,
and mercy have been great, and the consolations of his Spirit are multiplied upon us.`"

The deep religious interest which Stephen Grellet had felt in the people of Hayti,
did not cease after his return.
He corresponded with Petion and some of the chief men of the island, and,
both by enlisting in their favour the efforts of English philanthropists,
and by more direct influence,
he was the means of rendering valuable aid in advancing the cause of general education,
and of social as well as moral and religious improvement amongst them.
But neither Petion nor Christophe lived many years after his visit;
Boyer first succeeded the former, and then the latter,
in the supreme power over the south and north, and in the commencement of 1822,
the Spanish part of the island also yielding to his sway,
the whole were peacefully settled as one united Republic under his Presidency.
On the voluntary surrender of his authority in 1843,
the office of President changed hands repeatedly, till in 1847, the negro general,
Faustin Soulouque, became the ruler of Hayti,^
footnote:[The Spaniards had, in the meantime,
asserted their independence and proclaimed the "`Dominican
Republic`" in their portion of the island.]
and afterwards exchanged the title of President for that of Emperor.
On his recent abdication a republican government has been restored.

Bearing in mind the obstacles which must necessarily stand in the way
of a people just emerging from the disqualifying influence of slavery,
and still suffering from the effects of long continued struggles for political liberty,
it is no disparagement to the African race, that,
by the side of the most cultivated nations,
their advancement in the arts and habits as well as the enjoyments of civilized life,
should be comparatively slow and fluctuating;
but what has been already realized in their attempts at self-government,
during the short period of their independence, is enough to encourage the hope, that,
through the Divine blessing upon persevering efforts in a right direction,
a still brighter future awaits the free children of Hayti.

Anticipations like these cheered the heart of Stephen Grellet whilst,
a few days after his return from that island, he wrote to a friend in England,
respecting his dear wife, and himself: "`we are now seated in our quiet habitation,
with hearts far from being capable of embracing that fulness of gratitude
which we are sensible that we owe for the favours multiplied upon us.`"
