== Chapter XXVI.

Third Visit to Europe

Voyage to England--Companions Provided for Continental
Service--Preparations to Embark for Norway

It was some months after his return from Hayti before Stephen
Grellet fully recovered from the effects of his severe illness;
he was able, nevertheless, to devote some time to his temporal concerns,
and "`felt it to be his duty,`" as much as possible, to relieve his partner, upon whom,
during his absence, the whole care of the business had rested.

Due attention to his secular affairs was not, however,
permitted to interfere with what he "`felt to be
his primary duty--the service of his Divine Master.`"
He diligently attended all his ordinary religious meetings as they came in course,
and paid several visits to surrounding Quarterly Meetings.
In the spring of 1817 he took a journey into Pennsylvania,
and attended the Yearly Meeting in Philadelphia.
On completing his services in that city,
he returned home to his own Yearly Meeting in New York.
Soon after its conclusion he went, in company with "`his valuable friend,
Mary Naftel from England, then on a religious visit to the United States,
having Hannah Lewis for her faithful companion,`" to the Yearly Meeting of New England.
Both on their way to it, and subsequently,
they had a number of meetings within its compass.

After his return from New England the prospect of another religious visit to Europe,
alluded to in the last chapter, was brought before him with deepening interest,
and under date of the 26th of Eleventh month, he makes the following memorandum:

The weight of the service which the Lord calls for from me in Europe,
becomes heavier and heavier; my whole mind is at seasons absorbed by it.
I greatly wonder that services of this kind should be laid upon me,
in nations whose language I understand not,
where I do not know that there is even a practicability to travel,
and where numerous difficulties and great perils must necessarily attend me.
Yet sometimes it seems as if I saw a plain path before me in Norway, Sweden, Russia,
towards the Crimea, over the Black Sea, in Greece, Italy, etc.,
with a conviction that the Lord can remove every
difficulty and "`make of the mountains a way.`"
Many days and nights I have spent prostrated with much reverence before him;
and now believing that, in simple faith and childlike submission,
I must commit myself to his Divine requirings,
I have found it my place to prepare to follow the Lord,
wheresoever he is pleased to call me.
My dear family, my life, and my all, are again offered up to him, even if,
as it may prove to be, I should never return to this land.
Thus my first step must be to wind up all my temporal concerns and retire from my business,
which has become a prosperous one,
whereby I have been enabled to defray the heavy expenses of my last journey,
to provide for my beloved family,
and to lay up enough to pay my expenses during the extensive service before me.
The little substance with which the Lord has blessed me is offered to his service,
and a promise made me years ago, "`that if I endeavoured faithfully to serve him,
he would provide for me everything necessary,`" is renewed.
Under these my exercises and deep conflicts my beloved wife is my faithful helper;
she very sweetly encourages me,
believing as she does that our happiness in time and our hope of blessedness in eternity,
depend on our following the Lord in the paths of obedience in all faithfulness.

In due time he spread his concern before the Friends of his Monthly, Quarterly,
and Yearly Meetings.
They respectively entered "`into much feeling with him,
under the magnitude of his religious prospect of Gospel labour in distant nations,
and by their certificates commended him to the Christian
notice and kindness of those among whom he might come,
in the course of his service in the Gospel of our Lord and Saviour Jesus Christ.`"
Soon after this, he embarked on his third visit to Europe.
The following particulars are taken from his journal:

17th of Sixth month, 1818.
Having settled all my affairs and taken a very solemn
farewell of my beloved wife and child,
giving up one another to the Lord`'s sovereign will and almighty disposal,
even unto death,
should it be so ordered that we should never meet again in this mutable state,
I came this day on board the ship Hercules, Captain Cobb, bound for Liverpool.
My dear friend, Mary Naftel,
who has completed the service for which the Lord had sent her to these United States,
has likewise embarked to return to her native land.

23rd. I have been very sea-sick, but, through Divine favour,
my mind is kept in much calmness, trusting in the Lord, who is pleased to retain bound,
as on the +++[+++altar of offering, the sacrifice I have made to him of my life and my all.
Last First-day we had a refreshing meeting in the Lord`'s presence;
the Captain and his wife, three of our fellow-passengers,
and such of the ship`'s crew as could be spared from duty, sat with us;
Mary Naftel was solemnly engaged in prayer.

27th. We have pleasant weather; but it is as cold as in winter,
so that we can hardly keep ourselves warm; we must be in the neighbourhood of ice.
We have had another satisfactory meeting; surely we can say that,
in these our silent and reverent approaches to the Lord,
his voice in the secret of our hearts is felt "`louder than the noise of many waters,
yea, than the mighty waves of the sea.`"

28th. First-day.
At my request, our steerage passengers,
who had before declined joining us in our meetings, have now all attended, so that,
together with the sailors, we have had a pretty large company.
I feel much towards this class of my fellow-men,
some of whom have had very little opportunity for religious instruction,
and my soul`'s desire unto the Lord is,
that their time on board this ship may prove a blessed season to them.
I was enlarged towards them in love,
in preaching Christ and the salvation which is by him.
M+++.+++ Naftel had very good service.

29th. Yesterday afternoon and last night we had an anxious time; we had a very high sea,
and passed near large icebergs.

1st of Seventh month.
We have continued to be among the ice; several large bergs,
and a good deal of field ice have enclosed us;
it is very difficult and dangerous to be thus surrounded, the wind also being high.

2nd. The storm is increasing, we are closely shut up in the cabin,
and have the lamps lighted during the day.
The waves wash over us, and the billows beat vehemently against us;
men are standing with their axes near the masts, to cut away both them and the rigging,
as it may be needful.
What a blessedness, at such seasons, to know the Lord as our refuge and strength!
My times, O Lord, are in thy hands; at thy command I am here,
and into thy hands I have committed myself.

3rd. Last night our prospect was still more alarming; the tempest rose to its height.
It has now much abated.

5th. The weather is so pleasant after the storm that
we have held our religious meeting this day.
It has been a solemn one.
The narrow escape we have had from a watery grave
has softened the hearts of several on board,
and they are prepared to join in praising the Lord for our deliverance.

12th. In addition to having had as usual, our week-day meeting,
we have again sat together today, it being probably the last meeting we may have,
as we are very near land.
It has been a precious season, felt to be so by several of our company,
who when they came on board appeared very thoughtless, and strangers to good feelings;
but now they evince tenderness of spirit,
and show that love to the Saviour has a place in their hearts.
Besides having meetings with the sailors and steerage passengers,
I have felt it my place several times to read to them portions
of the Scriptures and suitable religious tracts.

It was not quite four years since Stephen Grellet left Liverpool,
after his former visit in Europe.
On again reaching the shores of England, he says:--

Liverpool, 14th of Seventh month.
Through the Lord`'s favour we have landed here safely this morning.
I am once more under the hospitable roof of my dear and very kind friends,
Isaac and Susanna Hadwen.
My beloved friends in this city receive me in the love of Christ,
with hearts warmed by Christian affection;
to the Lord be the praise for this and every other blessing!
I feel it a great privilege to have the love of the brethren.

16th. I have attended their meeting here this day.
The Lord has condescended to be near his poor servant,
and to grant me an evidence that it is in his counsel,
and the requirings of his Divine will, that I am here.
His gracious promise has been renewed, "`My presence shall go with thee,`" etc.
My soul, in silent adoration, says, "`Good is the word of the Lord,
and his promise is sure.`"
This evening, previous to the departure of dear M. Naftel, we had a solemn opportunity,
several other friends being also present.

Manchester, First day, 19th. I came here yesterday, accompanied by Isaac Hadwen,
and attended their two meetings.
They are in a low state; some of their pillars have lately been removed by death.
Where are the willing-hearted ones whose hearts incline to the Lord?
Here my dear friends, Josiah and Robert Forster, have kindly come from Tottenham,
to accompany me to London.
O Lord! send the angel of thy presence to direct the footsteps of thy servant,
and be pleased,
according to thy word,--in which thou hast given me to hope,--to
prepare a companion for me after my own heart,
to go with me in the great work whereto thou dost send me.

On his arrival in London he took up his quarters at William Allen`'s,
who then resided in Plough Court, Lombard Street.

London, 21st. I arrived here this evening,
and have not delayed telling my dear friend William Allen,
that I have thought for some time,
that it was he who was to be yoked with me in the Lord`'s work among the nations,
and have left the matter for him to consider.

22nd. Attended the meeting at Grace-church Street;
in my secret communion in spirit before the Lord,
I felt that a bitter cup was prepared for me to drink of in foreign nations;
but the cup that my Heavenly Father giveth me shall I not drink?
O! how very nearly did I feel for my beloved William Allen during that meeting.
I felt the travail of his soul.
I believed he was passing through deep baptism.
Being, after that, with him and his precious daughter, at his valuable mother`'s,
we were again baptized together by the one Spirit.

The Lord has laid upon him the same concern that I have upon me.
He felt it before my arrival in this land;
the weight of it has been at times overwhelming to him;
he has so many things that hold him like strong bands
that he does not know how he can be released;
but the Lord is all-powerful to remove every obstacle.

26th. I have attended several meetings, and visited several families in affliction.
In most of these services dear Allen has accompanied me.
Great is the exercise of his mind,
but I have rejoiced in the evidence that the Lord is with him.
This evening, in company with his mother and daughter, and dear Rebecca Christy,
we had a season of most solemn silence.
It was felt to be precious, and was broken by dear William, prostrated on his knees,
offering up himself and his all to the Lord,
to go with me wherever the blessed Master may be pleased to send us,
and to drink whatever cup he may prepare for us in the course of that service,
be it even unto death.
O! it was a solemn season indeed;
my soul very reverently adored the excellency of the Lord`'s power
and mercy in thus providing for me the companion after my own heart,
towards whom my mind had been inclined for a length of time,
though none knew it except my beloved wife.
Bless the Lord, O my soul, and all that is within me, bless his holy name!

In looking at the prosecution of his religious labours,
Stephen Grellet`'s attention had been much turned
towards the northern parts of the Continent,
and in allusion to it, he remarks:

Dear Allen having now concluded to go with me, at least as far as Petersburg,
and there to wait to know what the Lord may further require of him,
uses every exertion to prepare to leave home,
and he has also laid his religious concern before Friends,
and obtained their testimonials of near unity and full approbation.
In the meantime I have diligently visited meetings, etc., in and out of London.
My concern is great for this Quarterly Meeting and those adjacent.
O that we, as a Society, may not be professors only,
but possessors of the blessed Truth,--a city set on a hill that cannot be hid.
I am frequently clad with poverty.
I feel that I am a man of a fearful spirit.
Ah! it is a life of great humility, prostration and abasement, to live by faith.
This, I find, must be my daily bread.
My blessed and very compassionate Saviour nevertheless condescends to
grant opportunities whereby my faith in him may be renewed and confirmed.
Another of these is now given me.
I had been under great apprehension as to how I could be of the least
service in the great work of my dear Lord in Norway and Sweden,
for neither dear Allen nor myself understand their language.
I felt, indeed, at times, the word of promise proclaimed in my spirit,
"`The Lord will provide,`" and I said, "`Good is the word of the Lord;`" but yet,
I was again full of fears and doubts.
Now, to my soul`'s wonder and reverent gratitude,
it is given me to see that the Lord`'s promises are indeed verity and truth;
they are yea and amen forever.
Enoch Jacobson, a Norwegian, one of those I saw during my last visit to this nation,
on board the prison-ship of war, and who there became convinced of Friends`' principles,
having heard that I proposed to return from America to visit Norway, etc.,
has just arrived in London.
He has come under the apprehension that he would find me here,
and that it was his duty to come and render me any service in his power.
Surely this is the Lord`'s doing!
My friends here unite with me in the acknowledgment of it.
Blessed forever be his holy Name, who is glorious in holiness, fearful in praises,
doing wonders.

Thus provided both with a companion and an interpreter,
Stephen Grellet left London for Ipswich and Harwich, to embark for Norway.

Eighth month, 8th. This morning several friends met us at dear William Allen`'s;
we had a solemn religious season before the Lord, when,
through the efficacy of his Divine grace, our strength was renewed to trust in him.
W+++.+++ A. took leave of his dear family,
and accompanied by Enoch Jacobson and several others,
we came this evening to our beloved friends`', Richard D. and Ann Alexander, at Ipswich.

First-day, 9th. We had an instructive meeting.
I endeavour out of meetings, as well as in them, to keep my mind in great watchfulness;
the weight and importance of the embassy of love on which my dear Lord is sending me,
are heavily upon me; poverty is my clothing; I have neither purse nor shoes,
nor anything to carry out with me; but in the Lord I trust; he only is my sufficiency;
trust in him at all times, O my soul!

Accompanied by Joseph Foster, from London, and several other friends, we came to Harwich.
The vessel in which we took our passage in London, is waiting here.
She is one of those smacks that go to Norway for fish, principally for lobsters.
Her name is Freeling, Captain Heart.
She has been chartered to take us to Stavanger and Christiania, for seventy guineas.
