== Chapter XXVII.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Norway and Sweden

Stephen Grellet now entered upon his third "`Missionary Journey`" on the European Continent.
To have a fellow-labourer in this important service so entirely
"`after his own heart,`" greatly added to its interest and usefulness.
It was only recently that William Allen had publicly espoused
the Redeemer`'s cause as a preacher of the Gospel,
and he was not yet recorded as an acknowledged minister
of Christ in the Society of Friends;
but during the present engagement he had an opportunity of making "`full proof of his
ministry,`" and he was "`indefatigable in his exertions on behalf of the poor,
the ignorant, and the oppressed.`"
Stephen Grellet rejoiced in his companionship,
and there is good reason to believe that the union was owned and blessed of the Lord.
Banded together in His service,
the Christian brothers spent about two months in Norway and Sweden,
and Stephen Grellet thus notices their religious engagements.

[.embedded-content-document]
--

Norway.--Stavanger, Eighth month, 25th, 1818.
Through Divine favour we arrived here this day, i.e. William Allen, Enoch Jacobson,
and myself.
We had a rough and tedious passage on this North Sea.
Our vessel being small rendered it more trying.
Our landlady here is a very motherly woman;
her heart is moved with Christian kindness toward us.
We are much enfeebled by sea-sickness and want of proper food,
but she devises whatever she can towards our comfort.

26th. We presented ourselves this morning, with our passports,
before the Chief Magistrate of this place.
He has exercised the functions of a Judge for 25 years,
and is an intelligent and serious man.
On our inquiring into the state of the morals of the people of his district,
containing upwards of 40,000 inhabitants, scattered over about 140 square miles,
he told us that during the whole 25 years, one person only has been sentenced to death,
and that her punishment was changed to that of imprisonment for life;
but that her good conduct had procured her release after a few years.
The only crimes punishable here with death, are high treason and murder.
That of this female was infanticide.
The average number of criminals has been from six to seven per year,
mostly on account of small thefts, for which they are confined for a term of years.
An annual investigation of the conduct of those thus confined takes place when
the term of their imprisonment may be mitigated or terminated accordingly.
This town contains about 3,000 inhabitants, and the parish 4,000 more.
There are very few among them but what can read,
which is also the case throughout the district,
and yet it is thought that fifty Bibles could hardly be found among them all;
indeed money cannot procure them here;
one young Lutheran Minister has not been able to obtain a copy,
and he very gratefully received one that we presented to him,
(for we have brought a quantity of the Scriptures with us.)
We had some satisfactory intercourse with this young man,
and also with the senior clergyman,
who unequivocally acknowledged his full assent to the Gospel
truths that we felt engaged to communicate to them.
Enoch Jacobson is already very useful to us.

28th. Several of the dear people who became convinced of our Christian
principles in the prison-ship in England reside here;
we have visited them in their families,
and had very solemn and interesting religious seasons with them; one particularly,
with two young men and two young women;
a solemn silence in the Lord`'s presence prevailed over us.
These people are here as shining lights,
so that several pious persons in this place have joined them in silent,
reverent waiting on the Lord.
They meet regularly together twice a week for the worship of God;
they have no kind of vocal communication,
so that their meeting together is truly and solely to wait on the Lord.

We met with them at their usual week-day meeting; there were seven men and seven women,
with a few children.
We found them gathered into the same recollectedness of spirit and state
of solemn silence as we witnessed in our visit to their families.
Surely this is a people that gather to Christ, whom they know to be their teacher.
After we had sat a long time,
and enjoyed together in the Divine presence a very precious fellowship
of spirit in harmonious silent waiting on the Lord,
dear Allen and myself were enlarged in vocal ministry,
Enoch interpreting sentence by sentence.
It seemed like dew falling upon the tender grass;
we felt weightily the necessity of their having some
kind of order and discipline established among them,
to watch over one another for good,
so that their lives may be kept blameless and clean among men,
as becometh the Christian profession they make.
This appeared the more needful as there are a number of persons who often meet with them,
and who have in a greater or less degree joined them in religious profession.
They have moreover come under the notice of the Government;
and it is proper that there should be an understanding as to those whom
they consider as being in religious fellowship with them or not.
We have endeavoured to lay the subject before them for their consideration,
and they appeared to feel the propriety of taking such a step;
for the church of Christ is a church of order.
After having briefly but clearly set before them the manner
of life and conversation which ought to distinguish those
who wish to be considered members of their religious community,
and what are the cardinal portions of the Christian doctrine and precepts,
which they must firmly believe and endeavour to act up to,
we left them to consider these various matters among themselves,
and to see who among them felt warranted to give
in their names as members of their Christian community.
Enoch Jacobson, being one of them, stayed with them.
He told me that they proceeded in this concern under
great weightiness and tenderness of spirit;
eight only, out of nearly thirty,
apprehended themselves prepared to make such a solemn profession;
and yet several others are truly spiritually minded and conscientious men and women;
but they wish to act with deliberation.
We endeavoured to prepare a few rules of discipline suitable to their condition,
which they have adopted,
and have sent them for the consideration of those
who profess with them in other parts of Norway.

Several opportunities have presented for our being
with many of the inhabitants of this place.
Sometimes a large number were collected together.
They received the truths of the Gospel that we felt
ourselves called to proclaim with religious sensibility.
The two Lutheran clergymen have been to see us;
their object appeared to be to obtain a few hundred copies of the Scriptures,
which has been attended to, and we expect they will receive them in a few weeks.
They wished to understand more fully our Christian principles and testimonies.
Whilst we were endeavouring to inform them,
the aged clergyman especially manifested great tenderness of spirit.
We have also walked out into the country several times,
to visit some families who have in degree come under the influence of the power of Truth.
Some of these opportunities have been very interesting.

This part of the country is rocky and stony, but very picturesque;
there are many small lakes.
The people generally are very poor; they subsist mostly by fishing;
they have often to pay very dear for the small portion of bread that they eat,
and have several times been reduced to the necessity of eating the bark of trees,
instead of bread.
They cultivate a small quantity of oats or barley,
in little patches here and there among the rocks.
Their horses are small ponies, very strong for their size.

The little company here who profess with Friends,
have hitherto held their religious meetings in one of their houses,
which sometimes subjected them to interruptions,
and piously inclined persons feel diffident in coming
to sit with them in a private house.
This has induced us to endeavour to procure a suitable place for them to meet in.
We have obtained a commodious room, which we have hired for one year,
and had it properly seated and prepared.

First-day, 30th of Eighth month.
My mind was very low last night, and under a great weight of exercise.
Many baptisms has the Christian to endure; may those that I pass through purify my soul,
and prepare me for the Lord`'s service, whether it be actively to do,
or silently to suffer, his Divine will.
Those professing with us came pretty generally to our meeting this morning,
which was held in the new house.
They were about fifty.
It was a good meeting, and yet the great weight that I felt on my mind last night,
returned and continued till we went to the afternoon meeting.
We found a large company collected, and many more coming in.
Curiosity, most probably, was the only inducement that brought many of them, but others,
I am persuaded, came from better motives.
The crowd out of doors, as well as in the house, was great, and yet,
no public notice had been given of our meeting.
The Lord`'s power came over us, and brought all into stillness; when,
after a pretty long silence,
my heart being warmed with Christian love towards that assembly,
I addressed them in the words of the Apostle; "`After the way which they call heresy,
so worship I the God of my Fathers,
believing all things written in the Law and in the Prophets,
and have a hope towards God that there shall be a resurrection of the dead,
both of the just and of the unjust,`" etc., etc.
I unfolded to them the nature of true worship, in spirit and in truth;
who He is whom we are to worship and bow down very reverently to.
Then I set forth what the Christian Baptism and the Lord`'s Supper are,
and earnestly besought them to come to be baptized by Christ`'s Spirit,
so that they may have a right to partake of His Supper,
even to feed on the Bread of Life, which if a man eat of he shall live forever;
not like the manna of which the Jews did partake and are dead;
nor like that bread of which so many Christian professors so often partake,
which they call the Lord`'s Supper, and yet continue dead in trespasses and sins.
I proclaimed to them the glad tidings of salvation by Jesus Christ,
and invited them to come to him, their Saviour, who is so near to us,
that he is described in the Scriptures as "`Christ in us the hope of glory.`"
I forewarned also the disobedient and the rebellious of the day of the Lord,
who will render to every man according to his works.
My dear friend William Allen had also very good service.
The people were very attentive, and some very tender.
In the evening the old clergyman, who had been at meeting, came to us,
and in a very feeling manner expressed his gratitude
for the opportunity given him of the Lord,
to hear the great Gospel Truths that had been proclaimed that day.

31st. This forenoon we visited their prison and their schools;
the former is kept by an old woman.
She had but one prisoner in it,
and had so much confidence in him that the door of his cell was kept open.
In the afternoon we had another meeting with most of those professing with us.
We endeavoured to encourage them to keep near to Christ, their foundation;
that He may keep them,
and enable them to maintain all their Christian testimonies with uprightness and faithfulness,
that so they may be made a blessing to their neighbours and the nation.
We assisted them in organizing a meeting for maintaining
good order and Christian care over one another,
which is to be held every two months.

We then took leave of them under much brokenness and nearness of spirit.
Fervent prayers also were offered unto the Lord for one another,
that he may prosper the work of their soul`'s redemption.

Ninth month, 1st. Tananger, three Norwegian miles from Stavanger.
We went this morning on board a little vessel to take us to Christiansand.
The weather was fine, but we had proceeded a little way only,
when the wind blew vehemently, and with it such a high sea,
that the Captain had great difficulty to put into this place for shelter.
There are here a few fishermen`'s cabins; their business is to catch lobsters,
for the London market mostly.
The storm being of long continuance,
has given us an opportunity to walk a considerable distance round this place,
and to visit the people in their solitary habitations.
The country is very barren; heaps of rocks and stones seem nearly to cover it.
We left Bibles and Testaments in many of their families, who gratefully received them.
We met a young man who resides on a small island at some distance.
He was at Stavanger when we first came.
We then gave him a Bible.
The people on the little island have daily gathered about him whilst he read it to them;
and he expects they will continue to meet together for that purpose,
chiefly in the evening, and on First-days.

--

Having been detained several days by stress of weather,
they did not leave Tananger till the 6th, on their way to Christiansand.

[.embedded-content-document]
--

9th. Christiansand.
It has taken us two days to come here in our little vessel, which we have now discharged,
as we expect to proceed by land.

Accompanied by Peter Isaacson, a pious man to whom we were introduced,
we have visited the Governor, who treated us with great civility,
and is disposed to give us every facility he can in the
prosecution of our religious or benevolent objects.

We had at P. Isaacson`'s a solemn religious time with twelve
or more of the principal pious inhabitants of this place.
We visited an establishment which was endowed by his father,
and in which the son takes a lively interest.
It is a spacious, neat building, suitable for the accommodation of fourteen females,
each having a separate apartment.
Several of them have become reduced from good circumstances in life;
but they have here every comfort they could reasonably desire.
They appear happy and grateful to the Lord,
who has provided for them such a benefactor. The
religious opportunity we had with them was solemn.
There is also near these premises a school where
sixty poor children are taught and clothed gratis.
We also had a religious opportunity at the prison.

We find in this place a people called Saints.
Some of them are scattered over various parts of this land.
There are conscientious and spiritually minded persons among them.

10th. We had this evening a meeting at the house of one of these "`Saints.`"
Above fifty had collected.
Some of them are in a tender state of mind, towards whom we felt much;
we ministered to them the word of encouragement to hold fast unto the end,
for it is they that endure to the end that shall be saved:
but there are others who have turned aside from the right way,
under various discouragements, and by the falling away of their once valuable leader.
We pressed upon them to return to the good old way from
whence they have swerved in the day of temptation.
They were brought into much tenderness, and we parted from them in Christian love.

--

Leaving Christiansand on the 11th,
they availed themselves of several opportunities for religious service,
during a long and perilous journey of nearly ten days, to Christiania, by way of Arendal,
Brevig, Holmestrand, and Drammen.
Stephen Grellet remarks:

[.embedded-content-document]
--

Arendal, 13th. This place is only eight Norwegian miles from Christiansand,
and yet it has taken us two days to travel it;
the road is over a succession of hills of sharp ascent; the horses being small and weak,
we had four and sometimes five to the carriage, and yet we walked most of the way.
We had some narrow escapes; once especially,
when crossing a deep water the horses failed us;
but the Lord in his love has preserved us, blessed be his adorable name!
It was past eleven last night when we arrived here.
This morning we had a religious opportunity at the house of A. H. Dedecamp.
It was a trying and very exercising time; there were nearly sixty persons present.
In the afternoon I felt great distress of mind.
I retired into my chamber to pour out my soul before the Lord,
and to crave the sustaining help of his Divine Spirit.
He mercifully condescended to hear the voice of my supplication,
and to renew his promise that he would not forsake
me under any of my trials and sore baptisms.
My soul was a little renewed in faith.
On returning to my dear Allen, I found that he had likewise retired to his chamber,
and that our dear Lord had been with him also, to the great refreshing of his spirit.
We united together in acknowledgments of gratitude
and praise to our blessed Lord and Redeemer.
We then went to a small meeting appointed at the
house of a pious man whom I had met with in the street,
in the morning.
There were only eight persons present; we had truly a precious season together.
They appear well acquainted with the sensible influences of the Divine Spirit,
for which they are in the practice of waiting in silence.

17th. After two days hard travelling, early and late, we reached Brevig.
We lodged last night out of doors, half way up a steep hill;
the horses could not go any further.
The Lord`'s presence was near us that night in a very precious manner,
so that we felt much refreshed in body and spirit.

18th. We came this evening to Holmestrand.
The roads have been better, so that we have been able to ride most of the way;
the preceding days we had not only to walk,
but also to push the carriage behind in going up hill.
It would have been easier to perform the journey on foot, had it not been for our baggage.

19th. We have come to Drammen, the largest town in Norway that we have yet been in;
as we arrived here early this afternoon, we had time to call on several persons;
but we find they care but little for the things pertaining to the kingdom of God.
There are a few of those called Saints,
under whose care we have left the giving notice of a meeting to be held tomorrow.

20th. First-day.
About fifty persons attended the meeting.
It has been held to more satisfaction than we had apprehended.
Some of the people are serious,
but the mass of the inhabitants do not appear to stand high in morality.
In the afternoon we had a very agreeable time with a young man and his sister,
who profess with the few under our name,
and who sometimes attend their meeting at Christiania.
In the evening we had also a refreshing season at our inn, with a few serious characters.

21st. Christiania.
We arrived here early this afternoon,
and had this evening a small meeting at Canute`'s with those who profess with us.
Some of them I had seen on board the prison-ship in England.

27th. We have found here a wide door set open before us by our blessed Master,
who has also been pleased to give us a little ability
to labour in his Gospel among various classes.
We have had many meetings among those who profess with us,
and have also visited them in their families.
They cordially unite in adopting the rules of Discipline prepared at Stavanger;
and also conclude to establish a Two-Months`' Meeting.
They will meet alternately,
so that they may receive at each of their meetings
an account of what transpired at the other.
We have also had some pretty large and satisfactory meetings with the inhabitants.
There are serious and pious individuals among them, who are open to receive our testimony.
We find great openness among the men in power,--the Governor,
the chief Minister of State, their several officers, and many of the principal merchants.
Some religious meetings among that class of men have
been held at the residence of the Governor,
and have been seasons of Divine favour.
There is here a fortress, in which many prisoners are confined for life;
others for a term of years.
The Governor of the castle had them collected in their respective yards,
to give us an opportunity to have meetings with them.

This evening we closed our religious engagements in this place
by having a meeting with the little company that profess with us.
Some of them are in a tender state.
May the Lord bring to perfection the work that is begun among them!

--

Having now completed their services in Norway,
they left Christiania about noon of the 28th of the Ninth month,
and proceeded in a direct course to Stockholm,
a distance of four hundred and twenty miles.
With the exception of a little difficulty on account
of the occasional "`unruliness of the horses,
which were much stronger than those in Norway,`"
their journey was accomplished with comparative ease.
On entering Sweden,
the free use of "`strong drink`" by the people formed a
striking contrast to the more sober habits of the Norwegians.
Passing through Carlstad, "`a fine town,
beautifully situated at the head of a lake,`" Stephen Grellet remarks that,
neither there nor in other places on their route, did way open for any religious service,
concluding that "`the Lord knows best how to direct his servants.`"

They arrived at Stockholm on the 5th of Tenth month,
and were detained in the Swedish capital more than three weeks.
On a review of the various religious services in
which they were engaged during that time,
Stephen Grellet makes the following memoranda:

[.embedded-content-document]
--

20th. We have been closely occupied since coming to this city,
where we felt ourselves particularly concerned for the poor and the suffering.
It has led us to visit their various institutions for the relief or retreat of these.
We have had the acceptable company of Phillipson, a pious and very benevolent man,
whose time and large estate are employed in acts of benevolence.
He is the founder and supporter of several of these establishments,
and takes a very active part in many others.
Those for the education of poor children are very extensive:
they are on the most liberal plan, and in good order.
The same may be said of their retreats for the aged;
they are treated more like persons in middle circumstances
in life than is generally the case in poor-houses;
their bed-chambers are cleanly.
They have no beggars here; indeed they are not allowed; if a man cannot obtain work,
some is provided for him; if he knows not how to work, he is taught;
if he cannot sell his produce, a reasonable price is given him for it,
to enable him to live till he can do better for himself.
The aged, infirm or sick, are maintained in the most liberal manner.
We have visited all these establishments, and their prisons also,
having religious meetings in many of them; Enoch Jacobson being our interpreter.
We have had many religious opportunities also among the inhabitants;
some of these were held at our lodgings, where we have a spacious room for the purpose.

Soon after our arrival here, we waited on the Count D`'Engerstrom,
for whom we had letters; he is the King`'s Prime Minister.
He told us that the King had been informed of our arrival in his dominions,
and had expressed a desire to see us, when we came to Stockholm.
We told the Count that we should wait on the King whenever he requested us to do so.
The Count has appeared to take much interest in the object of our religious engagements.
His wife is a pious woman.
We have had several interesting religious seasons in the family,
also in that of Count Rosenblad, another of the King`'s Ministers,
and President of the Bible Society.
At one of these, held at the Count D`'Engerstrom`'s,
we became acquainted with the Countess von Bielke; her residence is at Copenhagen,
near the Queen; but she has large estates here.
She is a pious woman, and appears much interested to know our religious principles,
on which account she made many inquiries.
On my being afterwards with her,
she produced in writing my answers to her various questions,
which she had taken down from memory pretty accurately.
She wished to know if they were correct; her object, she said,
was to send them to the King and Queen of Denmark,
who she knew would be gratified with it.
We had previously felt much for that King and Queen,
and apprehended it was right for us to write to them;
we wished to bring before the King the subject of liberty of conscience,
and to secure his notice and protection for those few individuals who,
on board the prison-ship of war in England, had been convinced of our principles,
to whom a few others have joined themselves since their return to their homes.
We told the Countess that we were about writing to the King and Queen,
and proposed to send some books that treat particularly of our
religious principles and Christian testimonies and discipline.
She kindly offered to be herself the bearer of the whole of these,
and was much pleased with our giving her also some works of a similar character.
Julie von Bielke is a woman of a tender spirit,
and being acquainted with several pious persons in Finland and Russia,
she has given us letters of introduction to them.
She believes that the King and Queen of Denmark will respond readily
to our request on behalf of persons of a tender conscience,
for whom we plead in our letter to the King.

22nd. Being informed by Count D`'Engerstrom, that the King,
(Bernadotte,) would receive us this evening at his palace at Rosendale,
a little out of town, we went there at the time appointed.
The Count came to meet us on our arrival, and said he would present us to the King.
We had requested that it might be a private audience,
but the Count at once introduced us into a very spacious and richly furnished room,
full of the King`'s great men, ministers, generals, etc.,
etc.,--all in full court dresses--for we were actually brought into the court.
I felt pretty low on finding myself in such company.
What a contrast we were to them! we in our plain, simple garb,
our hats on,--they in their rich attire, and many insignia of high rank.
They treated us, however, with respect, and even with affability; several especially,
at whose houses we had been, and who had attended our meetings.
Shortly after, we were introduced to a private apartment, where the King was alone.
He received us with kindness,
entered with interest into the objects that have brought us into his dominions,
and wished every liberty and facility to be given us to visit any place we may desire;
and requested us to impart to him any observations we make,
that he may administer help and relief where needed, adding,
"`but you know that the King`'s name, which implies power,
is not always attended with it; on the contrary, I feel very often my impotency.`"
Having inquired what further stay we proposed to make in Stockholm,
and finding it was to be prolonged for a few days, he said he desired to see us again.
He would soon let us know,
and wished we might be more privately together than we could be then.

24th. The visits of pious or inquiring persons,
have kept us closely engaged at our lodgings, early and late,
when we were not holding meetings.
Among them are several of the clergy; some appear dissatisfied with their various forms,
which are but little removed from popery.
Some very interesting young men have also been with us;
they have been educated for the ministry, but are now brought under many scruples.
They seemed tender, and have ears to hear,
as well as hearts open to receive what we had to unfold
to them of the spirituality of the Christian religion.
An aged clergyman,
who at first raised many objections against what we had advanced
in support of the vitality and spirituality of real religion,
and strongly advocated a man-made ministry,
by the imposition of the hands and ordination of the bishops,
brought to us afterwards two of his sons, young men of a tender conscience, who,
having been educated for the ministry, now decline to be ordained,
not apprehending themselves called of God to the sacred office, as Aaron was,
and finding difficulties in reconciling many practices
and ordinances in their church with the Scriptures;
among others, worship, baptism, the supper, etc.
In the presence of their father,
the young men stated their objections with great feeling, and religious sensibility.
We endeavoured to unfold to them those various subjects, with others connected therewith,
agreeably to scriptural testimony, the force of which they appeared to feel.
The father, instead of raising objections as he had done before,
now appeared to unite with us, and on parting manifested much love and good-will,
requesting some books that treat of those subjects more fully.
One of the pious persons who has come to see us was once a renowned preacher,
but during the last eighteen years of his life,
he has withdrawn from all outward fellowship, and spends his time in retirement,
in silent worship and prayer.
He has given us an interesting statement of the Lord`'s gracious dealings with him,
and of his experience of the quickening influences of His Spirit,
who leads into all truth, and out of all error; by whose teaching we must learn daily,
things old and new.

25th. The Count D`'Engerstrom having sent us information
that the King wished to see us at five p.m.,
in the town palace, we went accordingly.
The Count was waiting for us, and brought us at once into the King`'s private chamber.
He received us in a kind and friendly manner, and made us take seats by him,
none being present with us but the Count.
We had a very full opportunity with him,
in the course of which we pressed the necessity of
allowing liberty of conscience in his dominions;
and pleaded on behalf of the little flock of his subjects,
who have embraced principles similar to ours,
and who have in some instances been brought into suffering
for maintaining their testimony against war,
oaths, an hireling ministry, etc.
The King, in a feeling manner,
said that he had made himself acquainted with our Christian testimonies,
of which he spoke in a respectful manner, adding, "`I know you are a peaceable people,
opposed to wars and the shedding of blood;
that under some circumstances you may perhaps parry a blow, but you cannot return it;
therefore, above any other people you ought to be protected,
and your Society shall have the utmost of my protection.`"
He feelingly alluded to the great responsibility he felt as King over this realm;
that if he was successful in doing any good, he was but a weak instrument in it;
indeed his power was very limited.
He spoke with much feeling, of the case of the poor Jews,
who by the law of the nation are not allowed to reside in this country.
He has several times tried to have this iniquitous law repealed,
but his efforts have been in vain.
He mentioned an occurrence that took place lately.
A number of Jews were wrecked on the Swedish coast,
when it was with the utmost difficulty that he, the King,
had succeeded in allowing them to be landed;
but he could not protect them from being sent out of the kingdom as speedily as could be,
though the poor sufferers had lost their all.
Supplies were given them from the King`'s private purse.
We were almost two hours together; and on our parting, the King held us by the hand,
and embracing us, seemed as if he could hardly let us go,
following us with his eyes and uplifted hand till we were out of sight.

26th. On our calling this morning on Count D`'Engerstrom,
who himself was much affected during our visit to the King yesterday,
he took us to his cabinet,
saying the King was willing that we should know how he spends some of his time.
The kingdom is divided into many provinces,
and these are so managed that a daily statement laid before
him of what has occurred in each during the week,
brings under his notice the state of all.
These accounts are separated into several heads;
one of them relates to circumstances of a more private nature,
such as the losses the poor may have sustained by the death of a horse or a cow;
a barn or cabin being destroyed by fire; of peculiar distress by sickness, etc.
These occurrences are read to the King every morning before he rises,
and out of his own purse, he administers assistance as the cases appear to require;
the Count produced to us the book of those private donations,
which evince the King`'s great sympathy for his poor suffering subjects,
as well as his great liberality.
After breakfast, other items of what has transpired in each province,
of a political nature, or otherwise, are also brought before his consideration.
In this way he had been made fully acquainted with our movements
and engagements since our first arrival in Norway.

--

This second interview with the King of Sweden very much
brought their labours in that country to a conclusion.
They made and received a few more visits,
in connection with the object of their Christian errand,
and took their departure from Stockholm on the 27th of Tenth month.

"`Feeling now released,`" says Stephen Grellet, "`from further service here,
our minds are strongly attracted towards Russia,
wishing to cross the Gulf of Bothnia before the winter sets in.
I had felt strong attractions towards the north of Sweden,
but after endeavouring carefully to feel for the Lord`'s guidance,
our way opens with clearness to proceed by Finland to Petersburg.
Several persons, hearing of our proposed departure, came to bid us farewell;
among others, the British Ambassador, Lord Strangford, and his wife.
We have had some precious seasons in their family; she is a woman of a pious mind,
and her Christian care over her children and family is exemplary.`"

They took an affectionate leave of Enoch Jacobson,
on board the vessel that was to take them across the Gulf to Abo.
He had been "`a kind and useful friend and a faithful and feeling interpreter,
and co-worker,`" without whose aid their services would have been much hindered; though,
in his intercourse with the well-educated classes, and persons of rank, in Christiania,
Stockholm, etc., Stephen Grellet experienced no difficulty,
as "`they spoke French correctly.`"
