== Chapter XXIX.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Russia
* Petersburg

Stephen Grellet and his companion arrived at Petersburg just at the setting in of winter.
They remained there four months.
The Emperor Alexander was absent in other parts of his dominions,
and did not return to the Capital till near the end of their stay.
But, in the meantime,
"`a great door and effectual was opened`" to them for their united
labour to promote the advancement of the Redeemer`'s kingdom,
both among the rich and the poor,--the prisoner and the outcast.
Their services were of a peculiar kind; but it was evident that the Lord was with them,
and "`preserved them whithersoever they went.`"
Stephen Grellet makes the following memoranda:

[.embedded-content-document]
--

Petersburg, 12th of Eleventh month, 1818.
On our arrival this afternoon, by the side of the Neva, opposite to Petersburg,
we found that the boats that form their floating bridges here,
had been removed a few hours before, for the ice was coming down in large masses.
It was a considerable time before we could meet with any
body that would venture to take us over in a boat;
but, as we could find no kind of an inn or shelter in which to pass the night,
or even to have refreshments, we persevered in our endeavours,
and towards evening succeeded in persuading some
men to take us over the Neva in a small boat,
which was effected, though not without danger and suffering from the cold.
It was dark when we came to the Hotel de l`' Europe.
Among a people of a strange language, we feel ourselves strangers indeed.

14th. We delivered letters that we had for several persons.
It brought us to an acquaintance with some who manifest kindness towards us,
and through whose medium we have obtained convenient private lodgings,
at the house of an English woman, widow of a Russian officer, where we have now removed.
It is a great accommodation to be in a house where they speak a language we understand.
We have therefore discharged our Finnish attendant.
He has been of good service to us;
his fidelity and good conduct have justly deserved our esteem, and he is, besides,
a serious and sober man.
We find in Samuel Stansfield, a young Friend from Sheffield,
settled here in mercantile pursuits, an agreeable and useful companion.
We have reason to believe that his conduct is consistent with his religious profession.
Daniel Wheeler and family reside at Ochta, a few miles up on the other side of the Neva.
They came to Russia some months since.
The Emperor Alexander had employed some persons to
drain extensive morasses near this city;
but they did not understand their business, and sought only to make money,
so that under various pretences they expended considerable sums;
which induced the Emperor, after his return from England, to desire, if possible,
to have a member of our Society to undertake the management of such works,
believing that he could rely on the faithfulness and uprightness of such persons;
and he wished also to have near him a man of religious principles,
whose example might have a good influence on others.
In consequence he wrote to the Prince Lieven, his ambassador in London,
who consulted with William Allen.
During that period our dear friend Daniel Wheeler, who resided at Sheffield,
had felt strong drawings of Gospel love towards Russia;
though he did not feel called upon to go to travel as a Gospel minister,
he yet thought that it was a sense of religious duty
that prompted him to go to that nation.
He was brought under very deep exercise and conflict of mind; when,
hearing of the desire of the Emperor that a member of our
Society would undertake the draining of those morasses,
Daniel felt immediately that it was for this very object that his mind had been preparing,
and accordingly, in due time, he removed here with his family.
Though his work has only been in operation during last summer,
his success and progress are such as to excite the wonder and surprise of all.
He holds religious meetings regularly twice a week, in his own house.

15th, First-day.
We were prevented by the severity of the weather, and other obstacles,
from attempting to cross the Neva, so as to attend the little meeting at Ochta,
with Daniel Wheeler and family; but dear Allen and myself sat down together, as usual,
to wait upon the Lord.
This has been our daily practice since we left England, and mostly twice a-day;
we have not been prevented by travelling,
often finding our carriage like a little sanctuary,
where the Lord`'s presence has been near, and our spirits contrited and refreshed by him.
This day our dear Redeemer has again condescended very graciously to be near us,
and to hear the secret but fervent language of our supplications;
for we have been brought very low since our arrival here.
He has mercifully confirmed us in the faith that we have
come into this Empire by his Divine appointment,
and that he will be our all-sufficient guide and helper for the work he may call us to,
and also our almighty protector under whatever trials may overtake us; if we,
on our part,
follow the putting forth of his Spirit with singleness of heart and faithfulness.
We both were greatly contrited under the sense of
the Lord`'s goodness and tender mercies towards us.

17th. We visited, yesterday, several persons for whom we had letters;
a few of these are of sober and serious minds.
The Count Lieven, elder brother of the Ambassador in London, came to see us;
his family are Protestants; they are from Livonia.
He is at present under deep affliction; his wife, who was a pious woman,
died a week since; rind his eldest son, with the other branches of the family,
have gone to accompany her remains to Livonia, to be buried on his estates there.
Feeling much for the Count in his bereaved state, we went to see him today.
His only daughter was with him; they are in a tender state of mind,
prepared to receive the consolations of the Gospel of Christ.
There were some other young persons present,
and we had a very precious season before the Lord; their hearts were tendered.
The Count appears to have been for years a man of piety; he knows, therefore,
where to flee for help and consolation in time of affliction.
Among those who extend great kindness to us, and are helpful in many respects,
are John Venning and Walter his brother.
They are benevolent men, and spend much of their time in doing good.

19th. We visited the Prince Alexander Galitzin, Prime Minister of the Emperor.
The Prince has a Christian spirit; he received us with an open heart; he was prepared,
said he, thus to welcome us,
as the Emperor had given him an account of the visit we paid him when in London.
"`The Emperor,`" said he, "`is not here at present,
and it will be some weeks before his return,
but here is a letter I have just received from him,
in which he says you were soon expected to arrive in Petersburg,
and he charges me to treat you as hit friends, and to detain you here till his return.`"
The Prince inquired into the nature of our religious prospects,
and how he can in anywise assist us.
We gave him our certificates, the reading of which pleased him much.
After various inquiries of a religious character, his Secretary, Papoff,
a pious young man, being present also, we were brought, in a simultaneous manner,
into a state of silent prostration before the Lord,
an experience to which the Prince does not appear to be a stranger.
In the love of Christ towards them I communicated
a little out of the overflowing of my soul.
Before we separated,
the Prince kindly offered us free access to whatever
place we might feel ourselves disposed to visit,
prisons, poor-houses, etc.

We went to see the Princess Metchersky.
She is a woman of superior mental abilities,
greatly improved and directed to the right channel for usefulness
by the grace and Spirit of the Lord Jesus Christ.
As she is well acquainted with several languages--French, English, German,
etc.,--she has been much engaged in translating several works and tracts,
especially into the Russian language, calculated to promote virtue and morality,
and to set forth the spirituality of the Christian religion;
she has them printed and widely circulated in this vast Empire.
She was an instrument in the Lord`'s hands in fostering
religious impressions in the mind of the Emperor,
when he first came under the powerful convictions of the Spirit of Truth.
As a proof that the Emperor is in the daily practice of reading the Scriptures,
she stated to us that some years since they agreed
to begin to read the Bible at the same time,
one chapter of the Old Testament in the morning,
and another of the New Testament in the evening;
that however far separated they might both every day read the same chapter;
and as they correspond,
the Emperor in his letters often alludes to the particular religious
impressions made on his mind by his reading that day;
by which she knows that he continues the practice.
He wishes her to translate and print the excellent work of William Penn,
called "`No Cross, No Crown;`" believing that it would be highly beneficial,
especially to those of high rank in the Empire.
Our next visit was to the Minister of the Interior; his wife is seriously disposed,
as also appears to be the Princess Shabatoff, who resides with them.

21st. My mind has been under much depression for days past;
today I felt as one sinking in deep mire, like the prophet in the dungeon.

First-day, 22nd. Accompanied by S. Stansfield, William Allen and I went over to Ochta,
to Daniel Wheeler`'s, about five miles distant from our lodgings.
We had to go pretty early, as at this time of the year the days here are very short;
the ice on the Neva being now very thick, we walked over it.
There were about twenty persons at meeting, including the family of Daniel Wheeler;
two persons that are not members are diligent attenders,--some others come occasionally.
The meeting was held in silence;
and ability was received to perform worship to the
Lord in reverence and brokenness of spirit.
After dinner, the family and a few others being present,
I felt it my place to express my conviction that it was
necessary for us to have our indwelling in the deeps,
and that I was confirmed in the faith that it was of the Lord`'s counsel,
that they were brought here.
It is in the deeps that the Lord`'s wonders are seen;
memorials are brought out from thence.
I felt much for dear Daniel, under the various baptisms he has to pass through.
I had a few words of encouragement for him.
Dear Allen had a little more to communicate, particularly to the young people present.

23rd. We mingled with some persons of seeking minds to satisfaction,
especially with Solomon, a Jew from Poland, converted to Christianity.
He is a man of great natural parts, but now brought to the littleness of a child.
His words are few; his spirit appears to be clothed with meekness and humility,
and to be sincere in the pursuit after vital religion,
and the saving knowledge of the Lord Jesus Christ.

--

After several days of laborious service in the prosecution of their religious engagements,
Stephen Grellet proceeds with his memoranda:--

[.embedded-content-document]
--

28th. I continue under deep mental conflicts.
My exercise for the people among whom we are is deep.
Some of the places I have visited, accompanied by dear Allen,
have brought me the more deeply to feel and to suffer.
We have been at nine of their prisons, called Segees.
They are much of the character of the Bridewell at New York, or the Compters in London,
except that men and women are more mingled together.
Young females for very small offences, or taken only on suspicion,
are night and day exposed to the vile company of hardened wretches.
We have succeeded in obtaining the liberation of two of these young persons.
Last Fifth-day we held our little meeting in our private apartment.
We felt increasingly low, as we had made an engagement to visit Kazadavloff,
the Minister of the Interior.
We besought the Lord to preserve us so close under the guidance of his Spirit, that,
if he had any service for us, it might be tc the exaltation of his great name.
We found there a large company, beside his family and their nephew and niece,
the Prince and Princess Shabatoff.
Among others, there were the Princess Metchersky, the Princess Sophia, her sister-in-law,
the Princess Tenbetokoy, Papoff, Secretary to Prince Galitzin, Paterson,
secretary of the Bible Society, etc., etc.
Way was made for our having a religious opportunity,
and the hearts of some appeared open to receive and
acknowledge the testimony unto the Truth which,
in the love of Christ, we felt constrained to proclaim among them.

29th.--First-day.
A heavy snow storm prevented our going to Ochta.
We held our meeting at our lodging, where Samuel Stansfield joined us;
also another person, who is, in some measure, convinced of our religious principles.

30th. By appointment,
we spent two hours this morning with the Prince Alexander Galitzin and Papoff.
The heart of the Prince is open towards us in Christian liberty and fellowship,
and we feel him as one baptized with us by the one Spirit.
We had a precious season with them in silent retirement before the Lord.

Twelfth month,
5th. During these last days we have mingled again in feeling with poor sufferers;
some because of their vices, others from other causes.
Whilst visiting the great and smaller prisons, we were deeply and sorrowfully affected.
It would appear that sympathy with the sufferings
of humanity in the nations that I visit,
is one of the services laid upon me.
O, that the Lord would soften and comfort their hearts under their deep sufferings, that,
through sincere repentance and faith in Christ,
they may know reconciliation and acceptance with God.
I am much grieved at beholding the great exposure of young females,
mixed together with the men prisoners, and the soldiers guarding them.
Great filthiness prevails in many of those places.
Various kinds of vermin are numerous.
The bed-bugs are seen in clusters on the walls,
like swarms of bees on the sides of their hives.
The air is noxious.

We spent some hours this day at the Princess Metchersky`'s.
I had a pleasant opportunity with a sister of hers,
who spends much of her time in religious retirement and meditation,
"`where,`" as she expressed it, "`without forms or the aid of any shadow,
He whom no man can comprehend nor make any likeness of,
is to be worshipped in spirit and in truth.`"
We dined at John Venning`'s; the Prince Galitzin, Papoff, and Paterson,
were the only strangers besides us.
The Prince related some interesting circumstances about the Emperor,
strongly evincing his Christian benevolence and tender feelings towards the afflicted,
and also showing his piety.

First-day, 6th. We went over the Neva to Daniel Wheeler`'s, and attended their meeting.
It has been a precious season to me.
The Lord has lifted up the light of his countenance,
and caused his face to shine upon his poor servant.
I had been kept very low for a long season;
days and nights of great distress had been mine.
Blessed be the Lord, who reviveth again, by his Spirit, my drooping soul.

7th. Count Lieven having participated in another cup of affliction,
by the death of his late wife`'s father, we have visited him again;
the dear old man has made a peaceful end; he has departed in the hope of the Gospel,
and of the mercy of God, through our Lord Jesus Christ.

9th. Yesterday and today I have been under sore distress from what
we have seen and felt in abodes of wretchedness and misery.
The prison near the Admiralty is so filthy, and the air so impure,
that it much affected our heads and our stomachs.
The prisoners, by their emaciated countenances, show that they also suffer by it.
Ten of them were fastened, two and two, to a long chain, marching out to Siberia;
what sufferings must these poor creatures have to endure, during so long a journey,
to be performed on foot, and in the severity of a winter like this.
May the Lord be pleased to open our way, in due time, to plead for so many sufferers,
that their distress may be relieved.
Among other places, we visited the houses of correction,
(it should rather be houses of misery,) poor-houses, and also their great hospital.
To some of these poor sufferers we were enabled to
administer the consolations of the Gospel,
and we found broken and contrite spirits prepared to receive our testimony.

Fifth-day, 10th. Walked on the ice to Ochta.
Our meeting was held in silence;
the Lord himself condescended to minister to our spirits,
and to refresh us in his presence.

14th. Our engagements have continued to be among the poor,
and in visiting several schools.
We had also a season of silent retirement in company with the Prince Galitzin,
when on bended knees,
prayers were offered up to the Lord for the help
and guidance of his Spirit in all our movements;
"`Send forth thy light and thy truth,
let them lead me and guide me,`" was our earnest supplication.
We were visited yesterday by Skotchinsky, a pious and enlightened man;
he has learned in the school of Christ; we had much satisfaction with him.
We also attended the meeting at Ochta, our fellowship in silent travail was in suffering.
I felt very low in the prospect we had of paying a visit to Michael,
the Metropolitan of the Greek Church.
The Prince Alexander has encouraged us in it, and kindly offered to make way for it.
This afternoon was the time appointed for going there.
We accordingly went to his residence,
the monastery called "`Alexander Nevsky,`" Papoff accompanying us.
It is about three miles out of town, and is a great mass of buildings;
the place of worship alone covers a large space of ground.
The Metropolitan, to receive us very simply attired Quakers,
had put on his rich pontifical garments;
his apparel reminded us of the clothing of the High Priests under the Mosaical dispensation;
under his large purple robe was a richly embroidered garment;
he had a white tiara or mitre upon his head,
on the front of which was a cross made of emeralds, diamonds, and other precious stones;
from a golden chain on his neck hung a fine picture of one of their saints;
on his sides were several small and large stars,
and in his hands was a large string of amber beads;
his beard was long and of a flaxen colour.
He received us with much affability, and made us sit down by him;
he soon began to inquire of our religious principles and practices,
and much approved of our reasons for not conforming to the compliments, language,
and fashions of the world;
the account we gave him of the Christian discipline exercised
over the members of our Society pleased him much;
he inquired also into our manner of conducting our religious worship;
our care and practice in the acknowledgment of our ministers,
and what object they have in going abroad in the service of the Gospel.
We gave him the perusal of our certificates;
he then said that he had not heard of any people acting on grounds so scriptural,
and conformable to ancient apostolic practice.
We entered pretty fully on the important subject of Divine inspiration,
and the gift of the Holy Spirit, a manifestation of which is given to every man;
to all of which he assented.
We could not help, in allusion to some of the subjects that were treated upon,
contrasting his rich attire with our simple one, and their pompous way of worship,
with the simplicity of ours.
We made several attempts to withdraw,
but he evidently wished to have further conversation with us;
ordered tea to be brought in, and finally on parting,
he accompanied us to the door of the outer room, and, taking us by the hand,
desired that we might remember one another in our prayers.
We went thence to see Philaret, who is an Archbishop and Vicar of the Metropolitan.
His habitation is also in the monastery.
His apartment is of great simplicity, like the cell of a monk;
the little furniture in it corresponds therewith;
his dress is the same that the Greek clergy have worn for several ages--a black gown,
black cassock on his head, a long beard, and his long hair hanging on his shoulders.
He is a man of learning,
acquainted with most of the ancient and modern oriental languages;
but he bears the marks of great humility;
he ia considered a man of piety and spiritual-mindedness.
We think, from what passed during the long opportunity we had with him,
and from what is told us by persons acquainted with him,
that he deserves such a character.
He stated that the knowledge of ancient languages
may facilitate the understanding of the words written,
but that the Spirit of God alone can give a right knowledge of the things of God;
for they can only be spiritually discerned.
In a very modest manner,
he said that he should wish to know why we declined the practice,
so general among the Christian churches, of partaking of the communion, or,
as he called it, the Eucharist.
After stating to him what we apprehend constitutes the real Christian,
according to the definition given in the Scriptures, "`If any mnn be in Christ,
he is a new creature,`" we described what this new birth or new man is;
then we proceeded to answer his question, showing what bread, living bread,
the Christian is to feed upon--in reality and not in shadows; that to live on Christ,
through his Spirit, is the only living bread of the soul;
it is the only food that nourishes it unto eternal life.
On which he said, "`We have had hermits amongst us, who, from various causes,
have lived entirely secluded from the world,
to whom it would have been impossible to participate
in the outward communion of bread and wine,
or in any of the ceremonies in the worship of God or other like practices, but who,
nevertheless, in their solitude did really feed on the Lord Jesus Christ by his Spirit,
through living faith in him; they had no places of worship to resort to,
no man to minister to them, but the Lord Jesus Christ,
the Minister of the Sanctuary was their minister,
and their worship was in spirit and in truth.`"
Philaret further said, "`All these forms, ceremonies, and ordinances,
that have been introduced into the churches,
though they be performed with ever so much sincerity and devotion, can only be,
as the law was to the Jews,
'`a schoolmaster to bring us to Christ.`' He is the
end of all these things and their substance.`"
Philaret has been a useful instrument of much improvement among the clergy.
The Emperor, who knows his worth, places great confidence in him; to him, therefore,
is committed chiefly the selection of suitable persons,
best qualified by their piety and spiritual-mindedness,
to fill important places in the Greek church; and at the head of their large schools,
of which there are several in the Empire, supported at the expense of the Government,
containing each from nine to twelve hundred pupils.
These are chiefly composed of the sons of the clergy;
according to their capacities or inclinations they
pass from these schools to the clerical office,
or stations in the civil department;
every one intending for the priesthood must marry before he can be ordained;
but when he loses his wife by death, he cannot marry another; if he chooses,
he can retire to a monastery and thus become eligible for
a higher station in the church than simply that of a priest.
The monks do not marry.
Michael, the Metropolitan,
was some years since a priest in one of the churches in this city,
and was a man of piety, concerned for the religious advancement of his parishioners,
and induced to preach to them in a language they could understand.
The general practice of the clergy has been to perform their public
service and read the Scriptures in the Slavonian language,
which very few among the people understand.
After a while, Michael`'s wife died.
Some tried to persuade him to retire to a monastery, for which he felt no inclination;
but Paul, who was then Emperor,
and had much approved of his giving public religious instruction by preaching,
sent him word that on a certain day he should attend at the monastery,
"`Alexander Nevsky,`" where he should take the vows of a monk.
Michael could only consider this message of the Emperor
Paul as an absolute order which he must obey;
however reluctantly, he went at the time appointed; Paul was there,
and as soon as the ceremony of being made a monk was ended,
the Emperor had the mitre and garments of a Metropolitan brought in,
(that office was then vacant), and had Michael, to his great astonishment,
invested with them, and ordained to that station.

22nd. We have had various religious opportunities.
Some of these were held at our lodgings,
where Skotchinsky has brought several pious persons, like himself.
They are wearied out with their forms and ceremonies,
and seek after the substantial realities of religion.
Some of them speak German, and have gratefully received religious tracts in that language.
We have visited several of these people in their families.
They are mostly in humble life,
and perhaps better prepared to receive the simple truths of the
Gospel with readiness than the wise and rich in this world.
There are some, nevertheless, of the latter class,
whose hearts appear broken down by the power of Truth.
We have been twice at Ochta.
The meetings were refreshing seasons,
and were attended by a few of those serious individuals that come
to our lodgings for the purpose of waiting together on the Lord.
On our last return from Ochta, we had a narrow escape.
On passing over the Neva, the ice broke in under us,
but our Almighty Preserver rescued us from a watery grave:
blessed and praised be His adorable name.
This day we had an agreeable visit from Reichel, a Moravian Bishop, who,
with his wife and daughter, are on their way to Sarepta, on the Caspian Sea.
He appears to be a humble and pious man.

23rd. Spent some time at the Senator Hablitz`'s, for the second time.
He was Ambassador to Persia for several years, and has returned in very poor health.
He now feels much more concerned to seek after the things pertaining
to his soul`'s salvation than for the politics of this world,
in which he had been absorbed for many years of his life.
We were met there by Skotchinsky,
who is of one of the most ancient and noble families of this Empire.
He takes great interest in prisons and schools,
and he wished to hear our observations on our visits to those places.
We hope he may be of service towards the removal of some of the
great miseries that we have beheld in many of these places.

--

[.offset]
At this time, Stephen Grellet writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To William Dillwin

[.signed-section-context-open]
Petersburg, 23rd of Twelfth month, 1818.

This is a great place, the capital of a great Empire;
though we see that much is to be done,
and that there is an open door with many precious minds,
I have never entertained any prospect of our doing great things;
yet I rejoice in the humble station of a waterer.
Divine aid is afforded to diffuse a few of the drops
that He first puts himself into the vessel,
over some of his precious and thirsty plants, to whose acquaintance He brings us:
for these my soul is often in secret travail; and I believe we are in our right place,
though it be often one of deep inward suffering.
From the accounts some may have of our often meeting with great and public characters,
and of the open door that the dear Master has been
pleased to set before us in many of them,
they may conclude that we ride about on the King`'s horse; but,
from the exalted state in which Mordecai appeared placed,
he saw and felt full well the humble station he must speedily resume.
Though there is an outside washing and anointing,
yet the sackcloth may remain underneath; and, as to myself,
I see very little prospect of its being loosened from my loins,
so long as I continue in this mutable state.
But do not conclude from this that I repine in any degree,
as complaining of my allotted portion; for, contrariwise, I may even now,
as frequently through the mournful days of my pilgrimage,
"`with the voice of thanksgivings and praises publish the Lord`'s wondrous works.`"
They have been marvellously displayed on our behalf,
poor solitary pair as we often feel to be, when going from city to city,
and from nation to nation.

--

[.offset]
The journal proceeds:

[.embedded-content-document]
--

24th. My beloved friend William Allen being unwell, I went alone to Ochta,
to attend the meeting there.
I walked the whole distance, going and returning,
and enjoyed the retirement of the walk;--the blessed Master condescended, in mercy,
to be with me in the way, and to enable me to renew my covenant with him.
He has also renewed my faith in his promise that
he would lead me and protect me in the path of duty.
Our meeting at Ochta was owned by his Divine presence.
We are permitted to have many seasons of refreshment
from the Lord with our dear friend Daniel Wheeler,
and his family.
Our fellowship of spirit is sweet.
This evening I spent a little time at Count Lieven`'s with his family,
which leaves a precious savour on my mind.

28th. We have passed, this morning, about two hours with the Prince Alexander Galitzin,
which we generally do every Second-day morning, from nine to eleven o`'clock,
for the purpose of religious retirement, and to wait together on the Lord;
or for mutual religious edification.
We have also frequent seasons of this sort with the Princess Metchersky, her sister,
the Princess Sophia, and several others, both in high rank,
and those of the poorer class.
The Lord is no respecter of persons; he is good to all that seek him,
and to all that call upon him.

31st. We had a visit from five pious persons; one is called a General.
Three of them appear to be men of meek and quiet spirits,
who have withdrawn from outward forms of worship and ceremonies,
and seek for God in the temple of their hearts.
We had a satisfactory time together.

Ninth of First month, 1819.
The last few days we have been very closely engaged
in visiting various extensive public institutions,
mostly under the care of the Empress-mother.
Among these are retreats for poor widows; hospitals; and a deaf and dumb establishment,
an institution for about two thousand children,
where every care in a moral and physical sense, appears to be bestowed.
The foundling hospital is also on a very extensive scale.
At a proper age, the children are well instructed.
Some receive a complete education, others learn a variety of useful trades.
In these visits we were accompanied by Prince Galitzin, uncle of Prince Alexander.
He has the general oversight of all these institutions of the Empress-mother,
and has readily made way for our having religious
opportunities whenever we felt it our duty.

11th. The Emperor, who was absent, has now returned to Petersburg,
and sends us word by the Prince Alexander Galitzin that,
as soon as he can make way for it, he wishes to see us.
Two pious persons, whom we had not seen before, visited us last Seventh-day,
and went with us to the meeting at Daniel Wheeler`'s, yesterday.
They are very serious in their deportment, and tender in their spirits;
almost every day we come to the knowledge of some such characters.

15th. Accompanied by Skotchinsky, we visited some poor pious families,
among whom we have found Christian faith exemplified.
We had also a solemn season with a young man, who, constrained by Divine love,
has left bright prospects in the world, to go as a missionary to Siberia;
he feels much for the prisoners sent there, and for the pagan nations thereabouts;
he is now endeavouring to acquire their language,
and has begun the translation of the New Testament, to take with him;
it is to be printed at the Bible House here,
where they have in the press or are preparing to
print the Scriptures in twenty-eight different languages.

24th. We received a note last evening,
stating that the Empress-mother wished to see us at the Palace;
but on our going there today,
we found that the information of the very sudden death of her daughter,
the Queen of Wirtemberg, has just been received;
this affecting event is deeply felt by the Emperor, especially;
she was a much beloved sister to him.
When with him in England, she was the widow of the Duke of Oldenburg,
and afterwards married the King of Wirtemberg.
Amidst our various engagements we have visited a school,
just established on the Lancastrian plan, for the benefit of the military,
but which is designed to spread this system throughout the empire of Russia.
We saw at that school young men, Russians, Calmucks, Tartars, Cossacks, etc.,
from various parts, who are preparing to teach that system in their several regiments,
after they have acquired the knowledge of it;
we were surprised at the quick intelligence they display;
so that their progress in learning is very rapid.
But we were much grieved on finding that some of the lessons given them to read or write,
are sentences taken from such authors as Voltaire, etc.,
and of a very demoralizing tendency;
this induced us to go to the office where those lessons are printed,
and on looking carefully over them we found among them impious and deistical sentiments;
some very obscene, some from the ancient philosophers, and one out of Cicero:
"`When life becomes a burden, it is magnanimity of soul to release ourselves from it.`"
We felt deeply the incalculable mischief that may thus be done,
and are very anxious to do all in our power to prevent the evil.
No time is to be lost.

The more we have dwelt on the subject, the more sensible we are, that,
by the introduction of suitable lessons into these schools,
the knowledge of the principles of vital religion, piety, virtue,
morality and justice may be extensively spread over this vast Empire,
and various vices and immoralities exposed and proclaimed against,
and that the knowledge of the blessed Truth,
and of that salvation which comes by our Lord Jesus Christ,
may be brought to those who are now totally ignorant of it.
But in the prosecution of such a work,
we are well aware that the jealousy of the clergy
of the Greek Church should not be at all excited,
and that no sentiments should be expressed in these lessons which might have that tendency.
It is therefore intended that the simple language
of Scripture only shall be brought forward,
and having so far prepared our plan, we expect diligently to prosecute the work.

--

In carrying out this important concern,
in which they were heartily joined by Dr. Paterson and his wife, and both the Vennings,
these devoted servants "`whilst closely engaged during the day,`" in their Gospel labours,
"`spent parts of some nights`" in preparing a series of
Scripture lessons of a very comprehensive character.
For this purpose they "`cut up several Bibles,^
footnote:[The Editor has now before him,
two of the identical French Bibles used on the above occasion.
They are at present the property of Wilson Armistead, of Leeds,
and are not without some historical interest:
on the leaf before the title-page each has the following memorandum,
signed by its former owner:
{footnote-paragraph-split}
"`One
of the Bibles out of which selected passages were cut,
and first pasted on blank paper by Stephen Grellet and William Allen,
when in Petersburg in the winter of 1818-1819,
wherefrom lessons were printed for the use of Russian Schools,
and since adopted by the British and Foreign School Society, in London.`"
"`Samuel Stansfield.`"
{footnote-paragraph-split}
Dr. Paterson,
in his interesting Reminiscent of Bible Circulation, remarks:
"`Prince Galitzin was highly delighted with the work,
and said that if our friends had done nothing else but this in Petersburg,
it was well worth while having come.`"
Dr. P. adds: "`Though humble in appearance,
it was in effect a truly great and blessed work.
As far as the Old Testament was concerned,
the translation into the modern Russian had to be made on purpose,
into the language of the people; and to this day, with the exception of the Psalms,
this is their only Bible.
Blessed be God, it contains all the leading facts, and doctrines,
and duties of Divine revelation.
The child who thoroughly knows it, may truly be said to know the Scriptures,
which are able to make him wise unto salvation through faith
in Christ Jesus.`' We all loved these good men.
Certainly, like myself, they had come to Russia just at the right time.
The way was not open sooner, either for prison or school plans,
and a few years later it would have been shut.
Thousands and tens of thousands have profited by their plans.`"]
taking a verse here and another there,

and neatly pasting them in a book, arranged under different heads,
so that it was obvious at first sight that the work contained nothing but Scripture.`"
These lessons were not only adopted, by order of the Emperor,
for the use of schools in Russia, but translated afterwards into many languages,
and extensively used in different countries,
leading the young to an acquaintance with the Holy Scriptures,
which they could not easily have gained otherwise.

[.embedded-content-document]
--

1st of Second month.
Besides the meetings for Divine worship that we frequently have,
we continue to visit places where the door is open for religious service,
as in the hospitals, poor-houses, schools, etc.
Frequently also we are visited hy pious and inquiring persons.
Some of these have come to Petersburg from a distance,
to confer with us on religious subjects.
Today, two Russians that we had not seen before, came to our meeting,
and they tell us of three others that reside one hundred and fifty versts from here,
who are expected shortly for the purpose of also being with us.
May the Lord bless our feeble endeavours to labour in his glorious Gospel,
and to exalt his holy name among the people.

At one of our late visits to the Prince Alexander Galitzin,
he related to us an interesting circumstance that occurred lately in Finland.
Some children from seven to nine years of age,
were so brought under the sensible influences of the Spirit of God,
convincing them of their sins, that, on their going to or from school,
they retired into the woods, and there put up their prayers to the Lord, with many tears.
By degrees their number increased.
The parents of some of them found them thus engaged,
and with rebukes and stripes dispersed them; but the parents of others,
who had noticed the increased sobriety and good behaviour of their children,
encouraged them to meet together in their houses, and not to go out into the woods.
The children did so, and some of these parents, observing their religious tenderness,
and hearing their solemn prayers to the Lord, the Redeemer and Saviour of sinners,
felt themselves strong convictions of sin.
They joined their children in their devotions,
and a great reform took place in that part of the country.
This excited the angry feelings of the priest, who was a bad man, and a drunkard.
He went to the magistrate, to enter his complaints against both children and parents.
The prosecution issued in their all being sent to prison.
They had been some months in confinement,
when Prince Alexander Galitzin heard that children were in prison on account of religion.
He thought it so strange an occurrence that he sent
confidential persons to inquire into it.
They found so much religious sensibility and tenderness in the children,
that they were greatly surprised,
especially at the simplicity with which they related how they had
been brought under trouble because of their sinful hearts,
and how they had felt that they must pray to the Lord Jesus Christ,
who alone could forgive them and enable them to live in a state of acceptance before God.
Being inquired of, if their parents or others had not put them on doing this,
they said that so far from that,
they were afraid that their parents or any one else should know how it was with them;
that they retired privately in the woods to pray and cry with tears unto the Lord.
The parents also stated that the children had been the instruments
of bringing them to a sense of their sinful lives,
and to seek to the Lord that he might give them a
new heart and pour forth his Spirit upon them.
Moreover,
it was found that the conduct of these people and children had been such
during their imprisonment as to comport with their Christian profession.
The Prince ordered their release,
and had the priest and magistrates severely reprimanded, and removed from their offices.
The Emperor having heard of all this,
and of the great sufferings to which these families
are reduced in consequence of their long imprisonment,
which took place last year before harvest,
ordered that all their losses should be liberally made up to them,
making ample provision also for their present support.
The Prince told us of some other instances that occurred lately in Russia,
of children who have been brought under the influences of the Holy Spirit,
and rendered instruments of good to their parents and others;
they felt it their filial duty so tenderly to plead with them,
on account of their drunkenness, swearing, and other vicious habits,
as to prevail upon them to forsake their evil ways.

--

About this time,
Stephen Grellet was "`brought into great heaviness,`" under the apprehension
that it was not improbable that his companion would soon have to leave him.

[.embedded-content-document]
--

"`My beloved William Allen,`" he writes, "`when he left England,
did not see his way with clearness to accompany me further than this place,
and he has it now under his close consideration to leave me to
proceed without him in my further religious labours in this Empire,
and other distant nations to which the Lord calls me.
The prospect of such a separation, should the Lord permit it to take place,
is a close proving to me; it leads me again to surrender my life and my all to the Lord,
and to endeavour to rely wholly upon him--yea, to live in faith on his gracious promise,
that he would provide all things necessary for me.
He has hitherto done so in a wonderful manner.
The path before me, previous to entering Norway and Sweden, Finland and Russia,
appeared as dark and discouraging as it now does; yet the Lord,
my blessed helper and guide, has made a plain path for my feet,
and has enabled his poor servant to proclaim his great name,
and the unsearchable riches of Christ, in palaces and in dungeons,
and among the poorest of the people; and now I wait, with deep reverence,
to see what the Lord will do.
As he put it into dear Allen`'s heart to come thus far with me,
he can also give him a commission to accompany me further.
To live by faith--how precious!`"

--

He was not long left in doubt.
This trial was soon cleared away.
William Allen found that he could not leave him,
and they continued their course of faithfulness together.
