== Chapter XXXI.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Russia
* Novgorod
* Tver
* Moscow

It was no small comfort to Stephen Grellet, on his departure from Petersburg,
to be able to look forward to the continued companionship of his beloved friend,
William Allen.
"`During four months of the darkest season,`" the interesting little family
group at Ochta had been "`cheered and refreshed`" by their company,
generally two days in the week,
and they had often been "`comforted together by the mutual faith`" of each other,
and a sense of the lovingkindness of their common Lord.
It was no wonder that the solitary few who remained
behind should deeply feel parting with such friends.
"`They left us,`" says Daniel Wheeler ten days afterwards,
"`with minds full of peace,--beloved and regretted by all
who had the happiness of becoming acquainted with them.
The stream of Gospel love which was at seasons permitted to flow,
when channels were open to receive it, has made, I believe,
an impression on the minds of some, which will never be obliterated;
and which has clearly evinced whose servants they are!
They were, I think, of all men, most fit to move in such a work, in such a place,
and under such circumstances.`"^
footnote:[Daniel Wheeler`'s Memoirs, page 73.--Ed. 1842.]

[.offset]
At Novogorod, Stephen Grellet continues his memoranda:

[.embedded-content-document]
--

Third month, 18th, 1819.
We came here this evening in twenty-four hours,
one hundred and eighty-six versts from Petersburg.
This is a large town; formerly it was very populous,
and an extensive trade was carried on; it covers much space.
We find none with whom to mingle in spiritual fellowship,
and what we have seen of their prisons and poorhouse greatly saddens our hearts;
even their retreat for the poor widows of the priests,
deacons and others connected with the clergy, and which stands close to their cathedral,
is in a most wretched state; but their foundling hospital exceeds all.
According to the statement they gave us, out of ninety infants admitted last year,
seventy died a few weeks or months after admission.
It is a great question whether these institutions,
originally intended as establishments of mercy, do not more harm than good.

--

[.offset]
At Tver they made a little longer stay, and had some interesting engagements.

[.embedded-content-document]
--

Tver, 22nd. Travelling three hundred and eighty versts in three days and two nights,
we came here this evening.
We found the road difficult, owing to the high drifts of snow,
and the great number of loaded sledges that travel on it;
many of them come from three to five thousand versts distance;
they are mostly loaded with tallow, fish, hemp, etc.;
it is supposed that from ten to twelve thousand of them pass daily on that road;
one driver having the care of several.

24th. Here we have had the pleasure of meeting the Princess Metchersky;
she is on a visit to her father and brother; the latter is the Governor of this province;
we had a letter from the Emperor for him;
he readily makes way for our admittance to such places as we desire to visit.
We find their foundling hospital in a miserable state; here also,
out of one hundred and eighty-four of the poor infants admitted last year,
forty-two only remain alive; and according to the ratio of preceding years,
five only of these probably will reach twelve years of age.
We had a letter from Philaret for Athanasius, the Archimandrite,
with whom was another Bishop, from a distance;
their hearts were open to receive the religious communication we made them;
they accompanied us to their large school for the sons of the clergy,
who were collected together; several other persons came in also.
I felt my mind concerned to draw their attention from outward observances,
forms and shadows, to Christ Jesus, the eternal substance.
He is the Light of Life to whom we must come and whom we must obey;
grace and truth come by him.
He is the Rock of Ages on whom we must build; we have no other foundation.
I unfolded to them what true religion leads to; what is the Christian baptism;
and in what the true communion with Christ consists;
several other subjects of vital importance were also laid before them.
The young men were serious.
The Bishops acknowledged that the truth, as it is in Jesus,
had been declared to them that day.
In the evening, the Archimandrite met us again at the Governor`'s; also his sister,
the Princess Metchersky, and a pretty numerous company.
Our minds were solemnized together,
and the Lord gave us a fine opportunity to proclaim among them the everlasting Truth.
Christ, the only Saviour, the way, the truth and the life,
without whom none can come to the Father, was preached to them;
they were tenderly entreated also to consider,
if there is not a danger of having our attention turned aside from Christ,
when we assiduously follow the many ways of man`'s device and invention,
or are captivated by the spirit of the world.
It has been a relieving season to us, and one also, we hope,
of edification to that company.

We had religious opportunities in several schools, houses of correction, and prisons;
also at the house of the Procurator-general, who is a man of a tender spirit;
and another at his wife`'s mother`'s, who is a woman of piety;
several persons had collected at their houses on these occasions.
Pious individuals have come to see us at our lodgings; they are sober inquirers,
who cannot be satisfied with their outward forms of religion; their inquiry is,
"`what shall we do to be saved?

25th. Last evening we had another solemn religious meeting at the Governor`'s house:
may the Lord perfect his work, which, through the operation of his Divine Spirit,
he has begun in the hearts of several of these people.

--

Moscow afforded them a still wider field of usefulness,
and many objects of deep interest claimed their attention.
Stephen Grellet gives the following details of their numerous services:--

[.embedded-content-document]
--

Moscow, 26th. We left Tver yesterday afternoon, travelling during the night,
and arrived here this evening, one hundred and sixty-eight versts;
the road is very bad by the deep snow and the great number of sledges upon it;
we counted them as we passed during two hours and a half;
they amounted to one thousand one hundred and thirty-three;
but we are persuaded that during some other parts of the day,
there were three times as many.
The quantity of produce that goes down is immense; including beeves, sheep, fish, etc.
The meat is frozen solid, and keeps so as long as the cold weather continues.

28th. The weather is intensely cold; a heavy snow storm, which began two days since,
still continues, so that we cannot venture out of doors.
Samuel Stansfield being here at the same hotel,
has sat down with us in our little meeting, composed of three only.
Our spirits were refreshed in the Lord`'s presence.
We had felt very low, and under great discouragement, but the promise has been renewed,
that He would guide our steps in the way in which he would have us to go,
and preserve us therein, however deep the exercises and trials attending us.

31st. The day before yesterday we delivered various letters of introduction.
Among others those for the Governor and Minister of Police.
Our minds are here again brought deeply into feeling for suffering humanity,
both for those who now reap the evil fruits of their sins and crimes, and those who,
through various circumstances that they could not control, are reduced to abject poverty,
and have become the inmates of poor-houses.
Free access has been given us to these places.
One of the officers of police who speaks French accompanies us, and interprets for us.
We have found the advantage of having such a person with us,
for we had to pass several times under one of the gates of the city,
on which is the image of a tutelar saint; a guard of soldiers stands continually there,
and no one is allowed to pass the place without uncovering his head.
We could not do this; but our attendant, fully apprised of our religious scruples,
has uniformly made way for us.
The prison of the Tribunal stands very near this gate;
it is called the "`Hole,`" and it is well named, for it stands in a hollow place,
and is most gloomy; but cleanliness has of late much improved it.
Another, called the Great Prison, is a large and commodious building,
constructed on the best plan that I have seen any where, and kept very clean;
the prisoners are also clean in their persons, especially the women,
who are entirely separated from the men;
the several degrees of guilt are also separated from one another.
We had several tendering religious seasons among them, in their various wards.
At their dinner-hour we were pleased to see,
that in addition to the fare allowed by the prison, which appears sufficient,
pious and benevolent persons sent baskets filled with good food;
we were told they did this daily, and that to each of the prisons;
so that prisoners in Moscow are treated better than in other places.
This large city is divided into twenty districts,
in each of which there is a Segees prison, like those of the same name in Petersburg;
we visited fourteen of them today,
and so close was the engagement that it was nine o`'clock
in the evening before we returned to our lodgings;
our hearts are sad at what we have beheld.
The greater number are confined for drunkenness;
as soon as a drunken man falls down in the streets,
he is carried into one of these prisons to prevent his being frozen to death; but here,
or before they reach the prison, they are stripped of the little money they may have,
or the good clothes, if they have any; and in other respects, by the abuses of policemen,
they are well fleeced before they are released,
so that they pay very dear for their drunken frolics.
We found also several confined here because of irregularity in their passports;
many young women are among these.
This is a very oppressive part of police regulations; country people,
by such neglect or forgetfulness, are brought under severe suffering;
sometimes it takes months before they are released.

Fourth month, 2nd. The last two days we visited the six other Segees,
and two large hospitals for soldiers, founded by the Empress Catherine.
We found about eleven hundred persons in them.
They are kept clean and comfortable, and some evinced religious sensibility.
We went also to a large establishment for the education of the children of soldiers,
founded by the same Empress.
It looks like a palace, and has about three thousand five hundred children;
three days since they began to introduce into it the Lancastrian plan of teaching;
a few sheets of the Scripture Lessons, which we prepared at Petersburg,
are already sent here.
We were gratified in a visit to a retreat for one hundred and fifty aged men and women,
endowed by a benevolent person;
every outward comfort appears to be extended to its inmates;
they themselves speak of it with gratitude.
Our religious opportunity with them has left pleasant impressions on our minds.
We have also been to several schools for boys, and to poorhouses,
supported by some of the merchants; but we find no schools of this sort for girls,
the education of whom is very much neglected.
This evening we spent some time with the Civil Governor.
He is inquiring after the things that belong to salvation,
and gratefully received several books in French that treat of our Christian principles;
his mother is an English woman.
We endeavoured in that family, to enforce the necessity of a pious life and conversation,
and that without holiness no man shall see God;
they were brought into seriousness and tenderness.
Thus the Lord, who is no respecter of persons,
but would that all men should come to the knowledge of the blessed Truth,
calls upon us and enables us, his very poor servants,
to proclaim his glorious and blessed Truth to the
poor and wretched inmates of prisons and poorhouses,
and also to those that have their habitations in palaces,
directing them all to the same Redeemer and Saviour,
who is good and merciful to all that seek him with sincerity of heart.

3rd. We had a letter from Philaret for the Archbishop.
He received us with kindness.
We were greatly surprised, when he brought us into a spacious parlour,
to find ourselves amidst a large company of the clergy, monks, etc.
There were several Bishops among them, and two Archbishops;
also some Princes from Georgia, who are of the Armenian Church.
These are hostages to this Empire.
The Inspector-General of the Posts in the Empire, a man of religious sensibility,
had come with us, and kindly acted as our interpreter.
Various inquiries were made respecting our Christian testimonies and religious practices,
to which having answered,
a door was open for us to impart to them some impressions made on our minds.
I felt much, especially for the Georgian bishops and princes;
seriousness prevailed over the whole company.
At the conclusion of the meeting, one of the monks, who speaks French,
came and sat near me, and alluding to some parts of my communication, said,
"`all outward rites and observances are but forms,
Christ and his Spirit are the substance; this we must press after,
without it nothing else can avail us.`"
I had been brought under much exercise,
when I found myself thus unexpectedly in such a company;
great was my secret cry to the Lord that He would
preserve us so close under his Divine guidance,
that the blessed cause of Truth might receive no wound,
but rather that his Holy name might be exalted.
He has very graciously heard the voice of our supplication; praises be to Him forever!

4th. We held our little meeting together this morning, as is our regular practice,
whatever other, or more public religious engagements we may have;
we often find these very profitable seasons,
and good preparations for the work that our blessed Lord may require of us in the day;
we found it so this morning; the Lord condescended to renew our strength,
in his presence.
We felt deeply in the prospect of being with the Prince Sergie Galitzin,
a distant relative of Prince Alexander, at Petersburg; he had written to him about us,
and we had accepted his invitation to dine with him;
we had besides a letter for him from the Empress-mother.
Many of his near relatives were with him, sisters, nephews and nieces,
I think thirty-four in all; his palace is very spacious, but he is,
in his person and manner of living, a plain man; he is very wealthy,
and spends liberally his large income, in acts of benevolence;
he gave very lately two hundred thousand rubles towards the further endowment of a hospital,
founded by an uncle of his.
He is a pious man, like his relative Prince Alexander.
Our conversation before dinner was altogether of a religious character,
on topics which appear to be uppermost in his mind; not on speculative,
but substantial and practical religion.
The young princes and princesses paid great attention,
and appeared to take a lively interest in what was said;
they evince that the great and saving truths of Christianity
have often been brought before their view,
and that they are no strangers to the influences of the Divine Spirit on their minds;
several in that company were melted into tears.

5th. Visited the large hospital, founded by the uncle of Prince Sergie,
in which every comfort appears to be extended to the afflicted inmates,
even such as many of us have not in our own houses.
Near it is a retreat for poor and old persons, conducted in the most liberal manner.
We next went to a large hospital called "`Peter and John,`"
founded and supported by the present Empress Dowager;
it is exclusively for persons who are considered pious characters.
From this we visited a retreat for one hundred and forty-five widows,
most of whom had once been in easy circumstances; here they are made so comfortable,
that Christian cheerfulness appears to be their clothing;
the children of these widows are also taken in,
and educated so as to fit them for business.
Though our engagement this day has been very laborious,
we feel this evening much comfort;
these visits have been so different from those we so often make,
where nothing but wretchedness and misery are to be seen.
We had also this day a number of tendering religious opportunities; Christ,
the refuge in trouble, the Saviour of men and the hope of eternal life, was proclaimed.

6th. This has been a very trying day to our feelings whilst visiting the foundling hospital,
which is a spacious place, like a little town.
It is under the patronage of the Empress Dowager, who had kindly written to the Director,
Vice-Admiral Sabine, to accompany us to it.
There are eight thousand eight hundred and thirty-one children under its care,
indoors and out.
Though great attention is paid to them, great mortality prevails here also;
it is not equal, however, to what we have beheld in other similar institutions.
Most of these infants, when their wicked or miserable parents bring or send them here,
are so diseased that those who do not die a few hours or days after admittance,
seldom survive many months.
It is calculated that one half die, about two weeks after being admitted;
and half of the survivors do not live to the end of the year.
These establishments give some idea of the vice and immorality that prevail;
our feelings are overpowered by distress.
O Lord! arise, plead Thy own righteous cause!
Amidst the scenes of desolation and misery we have beheld,
there has been some consolation;
the children who have attained from eight to eighteen years of age here,
as at the like establishment at Petersburg,
have great care bestowed on their moral and religious education;
school learning and several kinds of trades, are taught them; moreover,
the Empress has one hundred boys and one hundred girls here selected from
among these children who appear the best qualified for the purpose;
the boys receive such an education as may render
them able to occupy civil offices under government,
or to become surgeons, etc.
The girls are rendered capable of entering as governesses into
the families of the nobility or to fill similar situations.

7th. This day we have been chiefly among the children of the rich; poor or rich,
both have but one Almighty Father.
We first went to an institute for young women of the nobility called "`Catherine;`"
the next was for the daughters of burgesses and priests.
There are about two hundred in each; they receive a complete education here,
as in similar establishments in Petersburg, not only of a literary character,
and in the so-called ornamental branches,
but also such as to render them qualified to become
useful mistresses of families when they marry;
they each take their turns in the several departments of the family;
the cleaning part of the house, the bedchambers, at the ironing-tables,
etc.--in the kitchen, bakery, etc.; the girls in active service during the week,
deliver to their successors in the ensuing one,
a complete inventory of everything belonging to the particular department of the family,
into which they enter, and that by number and kind, by weight and measure;
they hand them, stated in writing,
what is the weight or measure of the articles that are to be consumed day by day,
such as flour, potatoes, butter, meat, etc.,
and they are required to keep their accounts very exact; in like manner plates, knives,
forks, towels, every kind of linen, or other articles,
must be delivered at the end of the week, or accounted for.
By this mode of proceeding each of these young women knows exactly the amount
of expense requisite weekly or daily for each individual in the family;
they are thereby brought into habits of order and economy.
We had satisfactory religious opportunities with these young women,
and with the mistresses who are over them;
we endeavoured to strengthen the latter to train
up these interesting young pupils in piety and virtue,
and to the practice of vital religion.
These were seasons of comfort to us.
We also visited another hospital under the notice of the Empress Dowager;
much attention is paid to the patients in it;
some of them appeared acquainted with Him who is the sure refuge in time of trouble;
there are about nine hundred in this establishment.

8th. Visited a boys`' school composed of about three hundred and fifty;
it is in a very poor condition;--no order in it.
We went from thence to a small establishment lately founded by Prince Kurakin;
it is only for thirty-two poor persons of serious habits and moral lives;
every two of them occupy a neat room.
Here we met two priests, one aged, the other younger;
both of them give evidence that they are men of piety and spiritual-mindedness;
they were pleased at our presenting them with some
books that treat of our Christian testimonies.
We dined at John Matezoff`'s, to whom the Princess Metchersky had recommended us;
we found him and his wife as she had represented them, persons of piety;
our intercourse with them and their family has been to edification;
he accompanied us the next day to the Archbishop, who wished again to be with us,
in a more private manner than in our previous visit.
He appears to be a moderate and liberally-minded man; he spoke highly of what,
in our former visit, we had advanced in support of the blessed Truth, as it is in Jesus.
He availed himself also of the opportunity to inquire
further into several of our Christian principles,
and acknowledged that our visit was to edification.
In the evening we went to see the Countess Orloff;
she is a young unmarried person of very large estates,
and liberally expends her wealth in acts of benevolence and charity.
It is to her and some others of that benevolent class,
that so many charitable institutions in this city, and other places,
are indebted for support; but, above all, the Countess has a pious, humble mind;
she is one of those spirits with whom we could mingle in very near Christian fellowship;
she knows what it is, like Mary, to sit at the feet of Jesus, to hear through the Spirit,
his gracious words.
We had with her a season of edification; we presented her with "`No Cross,
no Crown,`" and other small works.

9th. The Civil Governor accompanied us six versts out of Moscow,
to visit a large poorhouse under his direction;
also a house of correction and a workhouse; they are kept in good order and cleanliness.
The Governor kindly acted as interpreter of what we felt it our place
to communicate to the inmates of those respective establishments.
These visits enable us to have access for religious
services to several classes of the inhabitants,
and some who come from various parts of the country, whom we could not otherwise see,
and to preach to them Jesus crucified for our sins, risen again for our justification,
pressing upon them to break off their sins by repentance,
and to come with faith unto the dear Redeemer, who would have mercy upon them.

10th. We dined in company with the Civil Governor at a widow`'s, of high rank,
who spends her large income in acts of benevolence, particularly in boarding schools,
which she has established in various parts of the country; some for boys,
others for girls;
they are there cared for and educated so as to render them fit for business.
They are also assisted with means to pursue it; when they marry,
she gives them a portion to begin housekeeping.

19th. The last few days we have had some interesting
private opportunities with persons who,
on religious grounds, have come to see us; also some of a more public kind,
at the houses of several of them.
One was at the Military Governor`'s, and another with the chief Minister of Police.
We have endeavored, with these and the Civil Governor,
to plead for some of the objects that attracted our
special attention in our visits to the prisons,
Segees, etc.
We have succeeded in having several persons released from their bonds.
We are preparing an account of some of these visits for the Emperor,
as he encouraged us to do, stating to him what, in our apprehension,
should speedily be attended to,
and that the severity of the law or the latitude taken by the police,
of sending to prison men and women,
and some very young persons for little irregularities in their passports,
ought to be put a stop to.
We do not doubt that the Emperor will immediately attend to it.
We have met here much to comfort, but much also to afflict and depress us;
my soul has been plunged into deep exercises;
it seems at seasons as if it was poured out unto death,
so that during some nights my tears have flowed in abundance.
The Lord is very gracious in my distress,
and his promise is in the most consolatory manner renewed, that he will be with me.

21st. We were again with the Prince Sergie Galitzin, and several of his family;
some of the subjects introduced by the Prince were the spirituality of religion,
divine worship, saving baptism, etc.
Among those present was a Romish priest,
who did not appear pleased with the matters treated upon; but,
though showing his uneasiness, he kept silence.
In the evening we went to General Gourard`'s. We met the General at the door, going out,
but we were introduced to his wife`'s apartments,
where we found about fifteen females together.
On our first coming among them, total strangers to one another,
our minds were solemnized; a feeling sense was given that the Lord`'s presence was there;
it seemed as if we had suddenly come into a meeting of spiritually minded persons;
very few words passed between us,
but we were all gathered together into solemn silence and prostration of soul before God,
evidently "`drinking together into the one Spirit.`"
We had continued some time in this state, when, the love of Christ, the dear Redeemer,
constraining me, I began to speak as by his divine Spirit he gave me utterance;
we had a contriting season;
indeed I have seldom known any select company of my beloved
friends in religious unity and fellowship with me,
when more of the Lord`'s baptizing power has been felt, than we then witnessed together.
After the conclusion of that solemn meeting, we gave some account of ourselves;
for we were as great strangers to the company as they were to us;
we handed to the mistress of the house the letters
we had for her from the Princess Metchersky.
Among those present were two Princesses from Georgia, sent to this Empire as hostages;
another is the Countess Toutschkoff, and two of her sisters;
the others were of the same rank.
They are in the practice of meeting frequently together, silently to wait upon the Lord;
they have become acquainted with the operations of his Spirit, and the power of Truth,
under which they have witnessed the one baptism,
and are also favored at seasons to partake together of the one bread,
even Christ the bread of life.

The Countess Toutschkoff gave us an interesting narrative of the
manner in which she was first brought to the conviction that there
is a secret influence of the Spirit of God in the heart of man.
The impressions made upon her were such that she
can never doubt that it was the Lord`'s work.
It occurred about three months before the French army entered Russia, the General,
her husband, was with her, on their estates near Toula;
she dreamed that she was at an inn in a town unknown to her,
that her father came into her chamber, having her only son by the hand,
and said to her in a most pitiful tone, "`all thy comforts are cut off, he has fallen,
(meaning her husband,) he has fallen at Borodino.`"
She woke in great distress, but, knowing that her husband was beside her,
she considered it as a dream, and tried to compose herself again to sleep;
the dream was repeated, and attended with such increased distress of mind,
that it was a long time before she could rise above it, and fall asleep again.
A third time she dreamed the same; her anguish of mind was then such,
that she woke her husband and queried, "`where is Borodino?`"
and then mentioned her dream; he could not tell her where that place was;
they and her father carefully looked over the maps of the country,
but could not discover any such place.
It was then but an obscure spot,
but has since become renowned for the bloody battle fought near it.
The impressions, however, made upon the Countess were deep, and her distress great;
she considered this as a warning given her of the Lord,
that great afflictions were to come upon her, under which she believed,
that his Divine grace and mercy could alone sustain her.
From that period her views of the world became changed;
things that belong to the salvation of the soul, hitherto disregarded,
were now the chief object of her pursuit.
She ceased to attend places of diversion, which formerly had been her delight;
she looked forward to see what the Lord would do with her;
for she believed that she had not had mere dreams,
but warnings through the Lord`'s Spirit, of what was impending over her.
At that time the seat of war was far off, but it soon drew near:
before the French armies entered Moscow,
the General Toutschkoff was placed at the head of the army of reserve;
and one morning her father, having her little son by the hand,
entered the chamber of the inn at which she was staying;
in great distress as she had beheld him in her dream, he cried out, "`he has fallen,
he has fallen at Borodino.`"
Then she saw herself in the very same chamber,
and through the windows beheld the very same objects that she had seen in her dreams.
Her husband was one of the many who perished in the bloody battle,
fought near the river Borodino, from which an obscure village takes its name.

The Countess said that the impressions made upon her, that the Lord, through his Spirit,
communicates himself to man, became strongly confirmed;
she was convinced that there is a sensible influence of the Divine Spirit;
she endeavored to attend to it;
one thing after another was unfolded to her of the "`deep things of God`"
and those "`which concern the Lord Jesus Christ;`" and it was by this
that she had become acquainted with the nature of spiritual worship.
This was the case also with her two sisters, then present;
the same conviction had been brought on the minds of the other pious females,
through the immediate operation of the Lord`'s Spirit and power;
they knew it to be the Spirit of Christ, the Spirit of Truth, that leads into all truth.
The Georgian Princesses are in a humble and tender state;
we were indeed all broken and contrited together before the Lord.

The next day the Countess Toutschkoff came to our hotel, bringing her son with her,
and told me she came to request that I would take
this her only child and educate him as my own,
that however dear to her, and her only earthly treasure left,
her love to him and her desire that he might become a child
of God rendered the sacrifice of thus parting from him easy;
she was so sincere and so pressing,
her Christian feelings so predominated over the maternal
that I felt very tenderly with and for her;
she strongly reminded me of Hannah bringing her son
Samuel to be offered up to the Lord`'s service.
But I did not see how I could then undertake so important a charge;
I explained to her the nature of the service I was engaged in,
the different nations that I might have yet to visit,
the various hardships and dangers that possibly may attend the prosecution of my service,
the length of time it may take before I return to America, and when there,
the great distance at which her son would be from her,
and consequently the difficulty of hearing from him; besides his rank in life,
the large estates to which he was the only heir, and various other apparent obstacles.
The dear woman, for a length of time, could see no difficulty in all this,
but what she was very willing to submit to,
being even desirous that her son should in every respect
be educated as a member of our religious Society;
to see him in the way to become a true Christian was far more desirable to her, she said,
than to have him heir of earthly treasures, or to obtain ever so many worldly honours.
Our parting was a very tendering and solemn one.

--

It was quite cheering to Stephen Grellet to meet with such a character,
and to mingle with such a group of pious Christians in the heart of Russia.
He afterwards had some correspondence with the Countess, and "`her letters,`" he says,
"`displayed the same religious sensibility, and the same love for the blessed Saviour.`"
This little fragment of her personal history and Christian
experience doubtless presents some points of peculiar interest,
as an instructive illustration of the variety of ways in
which the Lord is pleased to deal with his children.
In connection with narratives of this kind there is perhaps, in some minds,
a tendency to foster an unhealthy appetite or craving for the marvellous and exciting,
which is to be carefully guarded against and repressed.
But, on the other hand,
there is a dread of admitting what is out of the usual course of man`'s experience,
not less morbid, and still more mischievous in its effects.
The simple facts of the world`'s history so clearly
attest the supernatural and the Divine,
and certainly, the records of Christianity, both of the Old and New Testament,
so abundantly assert and confirm it,
that it is only "`the evil heart of unbelief`" which withholds
the assent of the understanding and the judgment to evidence so
conclusive as to the direct operations of the Divine hand.
It is indeed only in harmony with the dispensations of Providence,
and the gracious influences of "`the Spirit who leads into all
truth`" that real sanity of mind can be attained and preserved;
and it may well be questioned whether infidelity, in some of its forms,
does not indicate a diseased state of mind,
arising from a wilful disregard of the gentle operations
of "`the Spirit that is of God`"--bestowed upon the believer,
"`that he might know the things which are freely
given to us of God,`" through our Lord Jesus Christ.
Stephen Grellet`'s own experience had prepared him
tenderly to sympathize with kindred spirits.
His journal proceeds:

[.embedded-content-document]
--

25th. First-day.
We have made the acquaintance of several piously disposed merchants,
who have brought us to the knowledge of others seriously inclined,
with whom we had today a satisfactory meeting.
O that all those who readily acknowledge the excellency
of the Truth would also submit to its dictates.

27th. We had several other religious opportunities with the inhabitants of this city,
mostly of the middle rank in life; some of them are in a seeking state of mind.
We went ten versts out of town to an estate of Count Romanoff`'s,
Chancellor of the Empire, with whom we had been at Petersburg; our chief object,
at present, was to visit a Scotch family who manage the estate;
we found piety among them, especially in the mistress of that large establishment.
This evening we visited again at General Gourard`'s. The
time of our departure from this place being at hand,
we felt it on our minds once more to be with some of those
spiritually minded persons we had met there some days since.
We found among those collected on the occasion several young women,
who were not present before,
but who are likewise under a precious visitation of the Lord`'s love;
we had a solemn meeting together, and, under a sensible influence of heavenly love,
we took a solemn and probably a final leave of each other,
with the joyful hope that through the dear Redeemer`'s mercy and
love we may meet before the throne of God and of the Lamb,
where there shall be no more parting.

We are preparing for our departure; the snow is fast melting away;
we have purchased a kind of carriage called britzka, without springs,
but the most safe for the long journey we have before us.
We were with the Prince Obolunsky, the Curator of ten Departments,
in a religious opportunity in his family; several others were present.
A portion of my religious communication to them was,
to reason with them of righteousness, temperance, and judgment to come;
I laid closely before them the importance of time,--the shortness of it,
and the necessity rightly to improve it whilst we have it,
calling upon them deeply to consider how trivial and how vain are
the enjoyments that this transitory life is capable of ministering,
compared with the eternal woes that will attend us,
if we have neglected that great salvation that comes by our Lord Jesus Christ.
As I was speaking, the Prince, inclining towards my dear friend, William Allen,
whispered,
"`It is very seldom indeed that such plain and sound truths are proclaimed to us.`"
Much seriousness prevailed over all.
The Prince afterwards accompanied us to a school, for about three hundred men,
sons of the nobility;
we felt it on our minds earnestly to recommend them to apply themselves
to the knowledge of the blessed and saving Truth which would enable
them to become possessors of the true nobility,
and if their lives are spared, prepare them to abound in works truly noble,
in the sight of God and man.
We visited after that about two hundred persons at the University,
where we had also a religious opportunity, with them and their teachers.

28th. We called for the last time, probably, on several persons, among others,
the Military Governor; his wife and family were all present;
we had a serious parting time with them;
other similar opportunities took place with the families of the Commandant of the place,
the Civil Governor, and the General of Police.
O! that the plain Gospel truths that the Lord has called us,
and enabled us to deliver among these and other great men in the world, may sink so deep,
through His power, that they may bring forth fruits unto everlasting life!
Some of them have appeared deeply to feel on these occasions,
even like Felix to tremble under the power of the testimony of Jesus; may they not,
like him, put off to another season which they may never have again.
We have consolation,
in that they have attended to some of our pleadings
on behalf of many poor sufferers in prisons,
etc., so that our visits to those afflicted fellow beings, have not been wholly in vain.
Some of the persons in high life have told us, "`we expect to hear the truth,
plain truth, without disguise from you; we are persuaded that it is in the love of God,
and love to us, that you visit us; your requests also are not for yourselves,
you seek not the favour of man, but your requests are on behalf of suffering humanity,
and your entreaties for our own soul`'s best welfare.`"

The police here is so strictly ordered, that transactions that appear very private,
soon come to their knowledge;
the day that we went to purchase the vehicle intended for our journey,
there was a heavy snow storm; hardly any one was to be seen in the streets;
going the next day to the Minister of Police, he at once told us,
"`you have then concluded to leave us, and have purchased a carriage.`"
We asked him how he knew it, for we had not told it to anybody.
"`I knew it,`" he said, "`an hour after you had purchased it,
and how much you gave for it; I sent to have it examined,
to see that you were not imposed upon.`"

29th. Amidst the necessary arrangements preparatory to our departure,
we have received the visits of several persons who have come to bid us farewell;
some have done so in great brokenness of spirit.

--
