== Chapter XXXII.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Russia
* Ekaterinoslav
* Mennonites
* Malakans
* Duhobortzi
* Perekop
* Simferopol

A long and arduous journey southward now lay before them.
Arrested at different intervals in some of the towns on their route,
they visited the German colonies of Mennonites, on the left shore of the Moloshnaia,
spent some time among the truly Christian Malakans,
and the neighbouring settlement of the Duhobortzi,
and then crossed the Steppe from Altona, the last establishment of the Mennonites,
to Perekop and the Crimea.
The letters of introduction with which they were
furnished through the kindness of the Emperor Alexander,
and the various civil and ecclesiastical authorities in Petersburg,
opened the way for them wherever they came,
and "`both in the palace and the prison`" the Lord
continued to prosper their labour of love.

[.offset]
On the 1st of Fifth month, 1819, Stephen Grellet continues his memoranda:

[.embedded-content-document]
--

We left Moscow yesterday, and did not arrive at Serpoukhov till two this morning.
We were several times in danger in crossing the waters
that are yet high from the melting of the snow.
A messenger was waiting our arrival,
to accompany us to the chateau of the Count de +++_______+++, twelve versts further.
He received us with much civility; he has large establishments about him,
and several schools, etc.;
but our minds were clad with much sadness the whole time we were there;
we did not feel ourselves in our right place,
for neither the knowledge nor the love of the dear Saviour appear to be there.

We arrived at Toula on the 2nd of the month, late in the evening.
Our difficulties on account of the high waters were considerable,
and the road very rough besides; we are sorely bruised by it.
Here we were several times with the Archbishop, whom we find,
as Philaret represented him to us, a spiritually minded man;
several of the monks here are the same.
The Archbishop accompanied us to their seminary,
and to their large school for the sons of the clergy,
among whom we had an interesting religious opportunity,
some of those spiritually minded monks, for whom we had letters from Philaret,
interpreted for us.
We endeavoured to direct the attention of those young
men to the influence of the Spirit of God,
who leads into all truth, by whom alone the things of God can be known,
and the worship acceptable to God can be performed;
much solemnity and seriousness prevailed over them before we left them.
The Archbishop entreated them to attend to the gospel truths which had been delivered,
saying that vain would be their improvement in scholastic knowledge
if they did not learn and make advances in the school of Christ,
as he instructs us by his Spirit.
We had another memorable season with those at the head of this large establishment,
and many of the monks who reside in the place; some of them, of the younger class,
were brought into great tenderness.
We returned to the Archbishop`'s to take tea; many priests and monks met us.
The Lord proclaimed silence over us, and gave us a solemn season in his presence; Christ,
the shepherd and Bishop of souls, was preached to them;
it is his prerogative to feed and instruct his people; his servants,
even those who are divinely anointed as his ministers,
can only hand out to the flock the bread which the Lord first gives them for the purpose,
and which he himself blesses;
neither can any availingly instruct the people but as the
Lord himself commissions and qualifies them by his Spirit,
so that they have nothing good to give but what they
themselves first receive from the Divine fountain;
hence the necessity to attend to the dear Master`'s injunction to his disciples,
"`Tarry ye at Jerusalem until ye be endued with power from on high.`"
I also felt my mind engaged in the love of Christ,
particularly to address the Archbishop; his Spirit was tendered;
with brokenness he acknowledged the favour that the
Lord had bestowed on us together this day;
a day to be had in remembrance by them all; some young priests were in tears.
It is very remarkable to us to find so much more vital religion among several of the
high clergy or dignitaries in the Greek Church than is to be met with among the Papists,
and generally also their manner of life is much more simple; those, however,
with whom we have mostly been are such as were recommended to us because of their piety.
It may also be observed that,
as the recommendation of suitable persons to high offices is entrusted to Philaret,
he nominates persons who have given sufficient evidence of their spiritual mindedness.
Among the mass of the clergy, and of the monks,
there is however much ignorance of real religion.
This brings me the more to feel desirous,
when I visit these large schools for the sons of the clergy,
that those under whose tuition they are placed may
rightly instruct them in the way of the Lord.
Here also we visited a school for young men of the nobility,
for whom we felt great interest.
Our visits to the prisons, hospitals, etc.,
have been attended with exercises of a trying nature;
our sympathetic feelings were much excited.
The misery entailed on the world by sin is great indeed.
O how could I forbear very earnestly to preach Christ,
the only but sure Saviour from sin and its many woes!
At the foundling hospital we find that out of four
hundred and ninety-six infants admitted last year,
twenty-three only remain alive.
O what a waste of human life!
We had some satisfaction in a visit made to us by some of the merchants,
with whom we left religious tracts.

Orlov, 6th of Fifth month.
We came here this afternoon.
We find in the Civil Governor a mild, serious man.
He lost one of his limbs at the battle of Borodino.
With his family, the Military Commandant,
several of the officers and others we had an unexpected religious opportunity.
The commandant has considerable knowledge of our Christian principles;
the open door we found among them reminded me of
those many seasons I had in Switzerland and Germany,
years since, with the officers of the army that marched into France;
surely it is the will of God that all men should be saved, and therefore,
besides the operation of his good Spirit in their hearts,
he commissions his servants to proclaim the Gospel of his salvation to all,
to invite all to come to Christ, who has died for all; accordingly,
my blessed Lord calls me, his poor servant, to proclaim his name,
and his redeeming love and power to all,--in palaces and in prisons,
to those secluded in monasteries, and to the soldiers.
O! Lord, bless thy work, and prosper thou it!

Here also we visited their schools, hospital, and prison.
We have been much delighted in being with an aged priest.
He is ninety years old; his name is John,
and he has spent the last fifty years of his life in acts of benevolence and charity;
he is but poor himself, his income being only two hundred roubles, about forty dollars;
he not only gives a part of this to the poor,
but spends yearly about ten thousand roubles,
that persons who know his great charity entrust him with,
though he never knows whether his supplies shall continue; but he says,
"`he lives by faith.`"
Besides his other claims, he has a poorhouse of his own, where he has sixty inmates;
they live with him on his premises, poorly indeed, like himself,
but they appear full of love and gratitude to him and to their heavenly Father.
The blessing pronounced by the dear Redeemer, may very properly belong to many of these,
"`blessed are the poor.`"

Koursk, 9th. We travelled all night from Orlov, here; yet, on our arrival,
we felt fresh in our bodies and in our spirits; for, on the road,
our souls were prostrated before the Lord, who is a covenant keeping God;
we were sensible of the fulfilment of his promise, "`My presence shall go with thee,
and I will give thee rest.`"
Under the feeling of the Lord`'s presence, how clear, how precious,
is the sense of his watchful care and mercy over us!
What refreshings also flow from his holy presence!`'
Here is a resting place for the soul;
if so sweet is a feeling of this sort, mercifully granted in this vale of tears,
what will be the fulness of the fruition in the Lord`'s everlasting rest!
My beloved Allen and I joined in praising and magnifying the Lord our Redeemer.
Here we did not feel ourselves called to much service, except with a few individuals,
who are in an inquiring state of mind; we distributed to them some religious tracts.

Biel Gorod, 12th. We left Koursk yesterday morning, and arrived here at midnight.
This is a poor place; we are lodged in a very dirty, miserable house.
The lodging places we have been at generally since we left Toula are among the Jews,
which introduces us often into conversation on religious subjects;
some privately inquire into the Christian religion,
but they appear to be afraid that other Jews should hear them;
we also find that some of them have the New Testament in Hebrew,
which they keep secreted from the view of others;
we have given Testaments in Hebrew to some, which they are grateful for.
We had a letter from Prince Galitzin for Bishop Eugenes;
we found him surrounded by many of the clergy, monks,
and some of the principal inhabitants of the place.
Our conversation was of a religious character.
A Divine savour attended.
We found the Bishop a man of a meek spirit, and acquainted with experimental religion.
Wishing to have a more private opportunity with him,
we visited him again in the afternoon; it was a time of mutual comfort:
we had fellowship with his spirit, under a feeling of the peculiar exercise of his mind,
I offered for his acceptance what I thought was the word of the Lord;
he repeatedly said on our parting, "`this is one of the most precious days of my life;
my faith in the Lord Jesus is greatly confirmed.`"
We had some consolation in our visit to their poorhouses; in one particularly,
which is under the care of, and supported by, benevolent and pious merchants.
Here is also a boarding-school for the sons of the clergy;
it contains about nine hundred pupils, all young men grown up;
several of the monks and priests accompanied us.
Visits of this kind introduce me into great exercise,
perhaps as deeply as any service I am engaged in.
O! how is my soul poured forth that the Lord`'s Spirit
of wisdom and counsel may be with me.
The Lord and his Truth were proclaimed to them; his worship and service set forth;
also the nature of the priesthood under the Gospel dispensation,
and what constitutes a minister of Christ;
whence the qualification to exercise the solemn office, etc., etc.
The Lord helped us, his poor servants, to exalt his blessed name.
We found the prisons in a very miserable state,
and felt much for some of the poor inmates.

13th. Kharkov.
We set off very early; for which we were prepared,
not having undressed these three days and nights; we did not even take off our boots;
but we feel very comfortable in the Lord, who is our strength.
Way being made for us by the Governor, we proceeded in the work, which,
almost from place to place, is called for from us.
The Governor has not only kindly accompanied us throughout our close engagements,
these two days, but has also acted as a faithful and feeling interpreter;
how great is the Lord`'s goodness in thus making a plain path for us, day after day,
and in providing such as can assist us in imparting to others,
whose language we understand not, our religious exercise and concern for them.
Those in high rank very generally speak French,
but hardly any of the mass of the people understand any other language than the Russ.
My services are frequently rendered here the more laborious,
because my beloved companion and fellow-labourer in the Gospel of the Lord Jesus Christ,
not understanding the French language sufficiently well to convey his religious exercises,
he does it in English, which I translate into French;
thus a double service falls upon me; but the Lord is very good to us.
It does not appear that the weight of our communications
is lost by passing through these translations.
Here are several schools;
that for the children of the soldiers contains one thousand four hundred boys;
that for the sons of the clergy, seven hundred young men;
an institute for young women of the nobility fifty-two.
We had relieving religious opportunities in these various establishments;
but it is a grief to us to find nearly every place destitute of schools for girls,
unless it be for the daughters of the nobles.
Their prisons are in a wretched state; the air is so fetid;
it is enough to create putrid diseases.
We found here many of the prisoners under heavy irons, yet one of them,
committed to the guard of six soldiers, effected his escape a few nights since.
Our visit to the establishment for the insane has left very painful feelings.
They are treated with inhumanity.
We were glad to have the Governor with us, that he might see all this,
which he had not done before;
and we are not without hopes that he will speedily have these evils remedied.
We met at his house several serious persons, particularly his wife;
we had a religious opportunity with them,
and endeavoured to draw their attention to those parts of
Scripture which describe pure and undefiled religion.

Ekaterinoslav,
18th. We had a very tedious and dangerous journey of two days and two nights,
to this place; we passed through Constantine Grade, but were satisfied not to stop.
One of the nights was so dark that our driver missed his way;
we found ourselves among precipices, and narrowly escaped being upset;
but our greatest difficulty was in crossing the Dnieper,
about three quarters of a mile wide in that place, and very rapid.
The Greeks called this river Borysthenes; a heavy wind had prevailed for three days,
which had rendered it impassable; it had then abated, but the water was very rough.
Here we are accommodated at the house of a Jewess;
there is a little more cleanliness than in most of the places we have put up at of late;
generally, a variety of the most disgusting kind of vermin greatly annoy us.

Here resides Contenius, originally from Germany; he also speaks French and Russian;
he is Superintendent of the Colonies of the Germans, Mennonites, Duhobortzi, etc.,
in the Crimea, and is a valuable, serious man.
Senator Hablitz had given us a letter for him;
he appears very kindly disposed to render us every assistance in his power;
from religious motives he has devoted the last thirty years of his life
to endeavours to promote the well-being of the several Colonies;
he has been to them an instrument of much good, as Prince Alexander Galitzin told us;
he does not act from motives of interest, but from principle; he is seventy years of age.
On a visit to the Governor of this place, we met with the Governor of Kherson,
which was a pleasant circumstance, as we have it in contemplation to be at that place.
In the evening I was much gratified by the receipt of a letter from my beloved wife,
giving a good account of herself and our dear daughter;
it has met me here nine weeks after date, having travelled from England to Petersburg,
then been forwarded to Moscow, and from thence here.

19th. Accompanied by that valuable old man, Contenius, who acts as our interpreter,
we visited prisons, hospitals, and schools;
we had a satisfactory visit at Count +++_______+++`'s under whose
superintendence are all the schools in this province.
In the evening we went to the monastery to see Macarius,
for whom we had a letter from Philaret;
he is Rector of the seminary for the sons of the clergy; he is about my age;
we found him in his cell, a very simple place indeed;
one table and a few stools appeared to be the only furniture in it;
he is a man of great humility and religious tenderness,
and he felt his heart so open towards us, as to impart some of the exercises of his mind,
and the ways in which the Lord, by his Spirit,
is pleased to lead him,--paths which very few about him can understand;
he has been much tried about the various ceremonies
attending Divine worship in the Greek Church,
and the bowing down before images;
his views of baptism and the supper appear to be very similar to ours;
respecting the ministry, he said that formerly he endeavoured,
and that with much care and labour, to prepare his sermons,
but when in the pulpit he attempted to preach them,
he felt them to be so dry and lifeless that his tongue
seemed to refuse to perform its office,
and he was obliged to stop; when, under very deep abasement before the Lord,
he felt the quickening influences of his Spirit constraining him to speak,
as he then gave him matter and utterance, now, when he ascends the pulpit,
his dependence is on the Lord alone, and he has nothing prepared beforehand.
We spent some time in silence together,
an engagement which the dear man appears acquainted with,
and during which he shed many tears.

21st. This morning we had a visit from an old man, eighty years of age,
one of the people called Malakans because of some of their religious scruples;
they call themselves Spiritual Christians.
We had heard of that people, and hoped to meet with them,
but did not know there were any of them in this place.
There are about twenty families, and we appointed a meeting with them,
to be held at our lodgings that evening.
Macarius came in as the meeting was gathering; at first,
we feared that his presence might mar the religious opportunity; for,
during the reigns of Catherine and Paul,
this people and the Duhobortzi suffered heavy persecution from the clergy and the government.
They did not however appear to be at all disturbed by his presence.
We were soon all gathered into solemn,
silent waiting and prostration of soul before the Lord;
this is the manner in which these people meet together for Divine worship, in silence,
which is not interrupted, unless some one present apprehends,
under the sensible influences of the Divine Spirit,
that he is required to speak as a minister among them, or to offer vocal prayer.
The meeting was a solemn season;
conversation with them afterwards made us desirous
to know more of their religious principles and doctrines;
we therefore appointed another meeting for conference with them,
to be held tomorrow morning, at one of their houses.
After they had retired, Macarius remained for some time absorbed in silent meditation,
then, with a flood of tears, he cried out,
"`In what a state of darkness and ignorance have I been?
I thought I was alone in these parts endeavoring to walk in the light of the Lord,
to wait for and sensibly to feel the influences of his Spirit,
so as to be able to worship him in spirit and in truth; and behold,
how great has been my darkness,
so that I did not discover that blaze of light here round about me,
among a people poor in the world, but rich in faith in the Lord Jesus Christ.`"
He left us much affected.

22nd. Previous to our going to the meeting with the Spiritual Christians we prepared
a list of the principal subjects respecting which we wished to inquire of them.
They were very free to give us every information we asked for,
and they did it in few words, accompanied, generally,
with some Scripture quotations as their reasons for believing or acting as they did;
these were so much to the purpose that one acquainted with Friends`'
writings might conclude that they had selected from them the most
clear and appropriate passages to support their several testimonies, etc.
On all the cardinal points of the Christian religion, the fall of man,
salvation by Christ through faith, the meritorious death of Christ, his resurrection,
ascension, etc., their views are very clear;
also respecting the influence of the Holy Spirit, worship, ministry, baptism, the supper,
oaths, etc., etc.,
we might suppose they were thoroughly acquainted with our religious Society,
but they had never heard of us, nor of any people that profess as they do;
respecting war, however, their views are not entirely clear,
and yet many among us may learn from them; they said,
"`War is a subject that we have not yet been able fully to understand,
so as to reconcile Scripture with Scripture; we are commanded to obey our rulers,
magistrates, etc., for conscience`' sake; and again, we are enjoined to love our enemies,
not to avenge ourselves, to render good for evil;
therefore we cannot see fully how we can refuse obedience
to the laws that require our young people to join the army;
but in all matters respecting ourselves,
we endeavor to act faithfully as the Gospel requires; we never have any law-suits;
for if anybody smites us on the one cheek, we turn to him the other;
if he takes away any part of our property, we bear it patiently;
we give to him that asketh, and lend to him that borrows, not asking it back again,
and in all these things the Lord blesses us; the Lord is very good also to our young men;
for, though several of them have been taken to the army,
not one of them has actually borne arms; for, our principles being known,
they have very soon been placed in offices of trust,
such as attending to the provisions of the army, or something of that sort.`"
Their ministers are acknowledged in much the same way as ours, and like us,
they consider that their only and their best reward is the dear Saviour`'s approbation;
therefore they receive no kind of salary.
Understanding that they have some among them in the station of Elders,
we queried how these were appointed, "`We do not appoint them,`" said they,
"`but when any one among us grows up to the state of a father or a mother in the Church,
we acknowledge them in the office for which the Lord has qualified them;
they do the work of fathers and mothers;
their works proclaim what the Lord has made them.`"
They pointed out to us the great distinction there is between them and the Duhobortzi.
The latter deny the authority of the Scriptures;
they deny the Divinity of our Lord Jesus Christ;
the offering up of himself a sacrifice for sin on Calvary, and salvation by faith in him.
There is a third class, who in every respect resemble the Spiritual Christians,
except that, like the Jews, they scrupulously keep the seventh day of the week,
and abstain from eating swine`'s flesh or those animals described in Scripture as unclean.
Where there are but few in a place, they join the Spiritual Christians in their worship;
their number is small compared with the Malakans; the latter,
it appears are scattered in various parts of Russia, from the Crimea to Siberia,
and on the Caucasus mountains;
they make their total number to be about one hundred thousand.
Before we separated we had another religious opportunity with them;
we felt them very near in spirit to us.
They use the Slavonian Bible; few of them, however, can read; but those who can,
read to the others, and these from memory teach the children,
so that their young people are very ready in quoting the Scriptures correctly.
They have some kind of discipline, and they watch over one another for good;
but have not been under the necessity of disowning any one for misconduct.
We left them a few books in the German language, which some of them understand,
and will read to the others.

In a visit to the sons of the Clergy, Macarius interpreted for us,
in a very feeling manner.
We had also a relieving opportunity in a large establishment for girls,
daughters of the nobility; some tender-spirited young women are among them.
Dear Contenius`' heart being much drawn to us, he has concluded,
notwithstanding his age and infirmities,
to accompany us to some of the colonies in the Crimea.
This engagement was often before my view, before I left America,
as one to which the Lord would call me, though I did not know what people were there.

Accompanied by dear Contenius we left Ekaterinoslav early in the morning of the 23rd,
for the colonies of the Mennonites, on the Dnieper;
we came sixty-five versts to the chief village of
the fifteen that form this part of their settlement;
they are an interesting people; much simplicity of manner,
and genuine piety appear prevalent amongst them.
I felt my mind so drawn towards them in the love of Christ,
that I apprehended it my duty to endeavour to have a religious meeting among them;
their Bishop,
who resides in this village was sent for by Contenius to
consult on the place and most proper time to hold the meeting;
the dear man, who is very plain in his manners and way of living,
was at the time in the field behind the plough;
for neither he nor any of the clergy receive any salary.
They maintain themselves and families by their honest industry.
They are faithful also in the maintenance of their testimony against oaths,
public diversions, and strong drink.
The Emperor exempts them from military requisitions.
The Bishop concluded that there was no better,
or more suitable place than their meetinghouse, which is large,
and in the centre of the other villages; the time was fixed for the next day,
and he undertook to have notice spread.
At the time appointed, they came from all the other villages;
the house was crowded with the people, and their ministers; much solidity was evinced.
The people gathered at once into such stillness and retiredness of spirit,
that it seemed as if we were amidst our own friends, in their religious meetings.
I was enlarged among them in the Gospel of Christ;
Contenius interpreted from the French into German;
dear Allen had an excellent communication to them, which I first rendered into French,
and then Contenius into German; we also had access together to the place of prayer;
our spirits were contrited before the Lord; the dear children,
who also felt the Lord`'s power over them, were in tears.

We went thence about thirty-five versts to Cortitz island, in the Dnieper,
where we stopped awhile with Peter Hildebrand, one of their pious ministers;
we had with him and his wife and family a refreshing season before the Lord.
Then they accompanied us, in small boats, about eight versts down the river,
to one of their villages below Aleksandrovsk,
where we had that evening a large and satisfactory meeting.
We felt much for concerned parents in that place;
their young people are exposed by being so near a city of resort and temptations.
Before we took our departure, the next morning,
we had a tendering opportunity in the family, where also several others met us.
Peter Hildebrand`'s heart was full on parting with us.
We left with them, as we had done in the other villages, some of our books in German.

We then travelled sixty-five versts, over what is called a steppe,
where not even a shrub grows, only coarse grass.
That night we came to a village of German Lutherans,
where are kept beautiful flocks of Merino sheep, for the use of thirty villages.
We had some religious service, but we did not find much piety among them.
Thence we went over the river called Moloshnaia,
which divides the settlement of the German colonies from a settlement of the Mennonites,
composed of twenty villages.
We stopped at their first village, where they have a large cloth manufactory;
their land is in high cultivation; formerly,
not a tree or shrub was to be seen on their vast steppes;
now they have fine orchards of various kinds of good fruit.
Travelling over these steppes, we saw, as we thought, at a distance,
large groves of beautiful trees, and to our astonishment,
the scenery continually changed; at first it appeared as if the groves were in motion;
on coming nearer, we found that they were flocks of cattle feeding.
At other times we thought we saw large sheets of water, like lakes;
but all this was an optical delusion, caused by the state of the air.

The Mennonites, here, are preserved in much Christian simplicity, in their worship,
manner of living, and conversation.
They have also a testimony against making the Gospel chargeable,
and against wars and oaths.
I felt it my religious duty to have a meeting amongst them.
It was agreed to be held in the evening of the next day,
and the Bishop readily offered to have notice of
it sent to the villages round,--ten in number.

In the forenoon we had a meeting with the children of several villages,
collected on the occasion;
their sobriety and religious sensibility give pleasing proofs that
their parents have not attempted in vain to instruct them,
by example and precept, in a Christian life.
We also visited with much satisfaction several of their families.
The meeting in the afternoon was largely attended.
The Lord owned us by his Divine presence,
and gave us an evidence that he has here a people,
whom he graciously owns as members of his church.
We afterwards went a few versts further, and lodged at an aged couple`'s; Christians,
indeed, they appeared to be; we were much refreshed with them, in our bodies and spirits.

Next morning, we had another meeting with about five hundred of their young people.
I have rarely met more general religious sensibility than among these.
I had not spoken many sentences,
when a great brokenness and many tears gave evidence of their religious feelings.
In the afternoon we had a meeting with the people at large; a very satisfactory season.
Dear Contenius is a faithful helper to us; he is so feeling in his manner of interpreting.
After visiting many of these people in their families, we went to another village,
where we had a very large meeting.
Many of these dear people came to it from fifteen different villages round,
their meetinghouse being large.
It may be said to have been a holy solemnity;
the Lord`'s baptizing power was felt to be over us.

We then went to Altona, their most distant village,
which stands pretty near the colonies at the Duhobortzi.
We put up at the house of a Mennonite, a young man, who is a minister among them.
The order of his family and children is most gratifying;
piety seems to prevail over them all;
the simplicity and neatness of the house are beautiful.
Much quietness and simplicity is also apparent in the religious meetings of this people.
They are very regular and punctual to the hour at
which their meetings for worship are held.
When gathered, they all kneel.
They continue so in total silence, in secret meditation or prayer, about half an hour.
After resuming their seats, their minister is engaged either in preaching or in prayer;
both extempore.
Before they separate they kneel down again, and continue for some time in silent prayer.
The Emperor grants them every privilege, and liberty of a civil and religious nature.
They choose their own magistrates,
and are not under the authority of the police of the Empire.
This is exercised by themselves.
They are exempt from military requisitions, and have no taxes,
except those requisite among themselves, for their own government,
and they are placed under the superintendence of those persons
who preside over the colonies in the Crimea generally.
Contenius is the chief person on whom that care now devolves.

29th of Fifth month.
This afternoon we went to the principal village of the Duhobortzi;
they inhabit several others near.
We went to the abode of the chief man among them.
He is ninety years old, nearly blind, but very active in body and mind.
He appears to be a robust, strong man.
Fourteen others of their elders or chief men were with him.
We had a long conference with them.
He was the chief speaker.
We found him very evasive in several of his answers to our inquiries.
They however stated unequivocally,
that they do not believe in the authority of the Scriptures.
They look upon Jesus Christ in no other light than that of a good man.
They therefore have no confidence in him as a Saviour from sin.
They say that they believe that there is a spirit in man,
to teach and lead him in the right way,
and in support of this they were fluent in the quotation of Scripture texts,
which they teach to their children;
but they will not allow any of their people to have a Bible among them.
We inquired about their mode of worship.
They said they met together to sing some of the Psalms of David.
Respecting their manner of solemnizing their marriages, they declined giving an answer;
but a very favourite reply to some of our questions, was, "`the letter killeth,
but the Spirit giveth life.`"
We found however that they have no stated times for their meetings for worship;
but that tomorrow, which is First-day, they intend to have one, and this,
they said we might attend, and see for ourselves.
We left them with heavy hearts and returned to Altona.

First-day, 30th. I had a sleepless night;
my mind being under great weight of exercise for the Duhobortzi.
I felt much for these people, thus darkened by their leaders,
and I did not apprehend that I should stand acquitted in the Divine sight,
without seeking for an opportunity to expostulate with them,
and to proclaim that salvation which comes by Jesus Christ.
It appeared best to go back to their village,
and see what opportunity the Lord would open for it, after their meeting,
whilst they are all congregated.
My dear Allen and Contenius felt very tenderly with me on the occasion.
We rode again to their village in the morning;
having previously appointed a meeting here among the Mennonites to be held in the afternoon.
The Duhobortzi collected, at about ten o`'clock,
on a spacious spot of ground out of doors; they all stood, forming a large circle;
all the men on the left hand of the old man, and the women on his right;
the children of both sexes formed the opposite side of the circle;
they were all cleanly dressed; an old woman was next to the old man;
she began by singing what they call a Psalm; the other women joined in it;
then the man next the old man, taking him by the hand, stepped in front of him,
each bowed down very low to one another three times and then twice to the women,
who returned the salute; that man resuming his place,
the one next to him performed the same ceremony to the old man, and to the women; then,
by turns, all the others, even the boys,
came and kissed three times the one in the circle above him, instead of bowing.
When the men and boys had accomplished this, the women did the same to each other;
then the girls; the singing continuing the whole time.
It took them nearly an hour to perform this round of bowing and kissing;
then the old woman, in a fluent manner, uttered what they called a prayer,
and their worship concluded; but no seriousness appeared over them at any time.
O how was my soul bowed before the Lord,
earnestly craving that he would touch their hearts by his power and love!
I felt also much towards the young people.
I embraced the opportunity to preach the Lord Jesus Christ,
and that salvation which is through faith in him; "`If ye believe not that I am He,
(the Christ the Son of God,) ye shall die in your sins.`"
I entreated them to try what manner of spirit they are of;
for many spirits are gone out into the world; and "`hereby know we the Spirit of God;
every spirit that confesseth not that Jesus Christ has come in the flesh, is not of God;
but this is that spirit of Antichrist,`" etc.
Whilst I was speaking, the old men appeared restless;
they invited me several times to retire to the house,
but I could not do so till I had endeavoured to relieve
my mind of the great concern I felt for them;
many of the people were very attentive, and the Truth appeared to reach their hearts.
We then went into the house with the old men; they had a few things to say,
but not to any more satisfaction than yesterday.
We left them with heavy hearts, and returned to Altona.

At five o`'clock the meeting with the Mennonites began; it was very numerously attended;
the people came from several other villages.
O! what a difference in our feelings with this people
and those we were with in the morning;
then darkness encompassed us, but here was light, as in Goshen;
the Lord`'s presence was over us;
the stream of the Gospel of life and salvation freely
flowed towards the various ranks in life;
many in the assembly were contrited before the Lord,
and under a sense of his redeeming love and presence
we took a solemn leave of each other.

There nre no post-horses to be had in these parts;
we therefore hired one of the Mennonites to take us with his horses to Perekop.
Early in the morning of the 31st,
after a solemn and tendering opportunity in the family where we had been so kindly entertained,
several others coming in also, we set off for a long journey through the wilderness.
Contenius, who had become increasingly endeared to us,
and whose services have been so valuable, accompanied us about ten versts on our way.
At the entrance of the desert we took a solemn leave of each other,
under feelings of Christian love.
This desert or steppe extends all the way to Perekop and a great distance beyond,
and to the right and left; the water is bad and brackish.
Several lakes of salt water occur.
Large herds of cattle, flocks of sheep,
and many wild horses are met with on these steppes.
Nature has bountifully provided for these animals; for, though fresh water is scarce,
the dews are heavy in the night, so that the grass grows up to a considerable height;
but not a shrub is to be seen.
Water-melons of an excellent kind grow spontaneously, in great abundance,
during the summer; man and beast find them a great luxury.
We now and then passed near some villages of the Tartars,
but our carriage was our habitation night and day.
We sometimes obtained a little milk, in addition to the provisions we had brought with us.
One night we stopped near a small Tartar hut, at which other travellers rested.
We found our company consisted of Tartars, Turks, Greeks, Russians,
our attendant and interpreter who is a Pole, my companion an Englishman,
and I a Frenchman.
A Mennonite, from Altona, overtook us in this wilderness;
he was the bearer of letters for us, which had arrived after our departure.
One was from America, from my beloved wife;
in ten weeks it had travelled from America to England, whence it was sent to Petersburg,
then to Moscow, to Ekaterinoslav, then to several of the colonies on the Moloshnaia,
and finally it came to hand in this desert.

Passing one day through a large village of the Tartars,
where we stopped to try to purchase some refreshments, the Chief among them,
who spoke Russ, pressingly invited us to his habitation; he gave us a cup of tea,
and said that, if we would stay the night,
he would have a sheep killed,--a great treat among them.
We could not, however, accept his kind invitation.
He then took us to a school where we met a large number of boys.
Their master is a Mahometan priest.
The boys sat cross-legged after the Eastern fashion.
They were writing with reeds instead of pens, from right to left.
Others were reading in the Alcoran.
We felt constrained to speak to them of the great love of God to man,
"`for God so loved the world that he gave his only begotten
Son that whosoever believeth on him should not perish,
but have everlasting life,`" etc., etc.
Our Pole interpreted what we said into Russ, and the person who attended us into Tartar.
The young men and their master were serious, and repeatedly expressed their approbation,
by putting their hand on their breast, with eyes lifted up;
they manifested their love towards us on our going away,
and our kind host kissed our hands three times, and then laid them on his forehead.

Our road led us afterwards frequently in sight of the Putrid Sea.
We met several herds of camels, flocks of large birds and some large eagles.
Wolves are very common on these steppes,
and they are so bold that they sometimes attack travellers.
We passed by a large one lying on the ground with an eagle,
which had probably attacked him, by his side, its talons were nearly buried in his back;
in the struggle both had died.

--

After a tedious journey over "`the great steppe,`"
they reached Perekop on the second of Sixth month,
and once more had "`the luxury of a good wash in pure, fresh water,
which they had not enjoyed for some days;`" but,
"`finding very little to detain them there,`" they continued their journey the next day,
"`still travelling over the steppe.`"
They arrived at Simferopol about noon on the fourth of Sixth month,
and it was not till that day that they saw, for the first time since leaving Abo,
a distance of nearly two thousand miles, "`the horizon bounded by a range of high hills,
or mountains.`"
The face of the country had now changed;
they were in the midst of the beautiful scenery of the Crimea.
