== Chapter XXXIV

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Constantinople
* Dardanelles
* Smyrna

Stephen Grellet had been permitted to leave Russia under very peaceful feelings.
These continued to cheer him on his passage over the Black Sea, though,
notwithstanding the fine weather, he was suffering from "`very distressing sickness.`"
The ground of his rejoicing was not that, through the Divine power,
"`the spirits had been made subject,`" but rather that, through the Redeemer`'s love,
"`his name was written in heaven.`"
He felt himself "`an unprofitable servant,`" yet,
in looking back upon the scenes of his past labours,
he had the reward of grace--the "`answer of peace.`"

In looking forward, however, to what yet awaited him,
he was brought very low "`under great pressure of exercise.`"
It was "`not the fear of going into the midst of the plague that distressed him:`"--

[.embedded-content-document]
--

"`I feel confidence,`" he writes on board the Lord Cathcart,
"`that my life is in the hands of my Almighty Father and Protector, so that,
in quietness and peace,
I can resign myself into his Divine hands and keeping;`" "`but,`" he adds,
"`I have a baptism to pass through,
under a sense of the further service prepared for me in the nations to which I am going.
I feel that I am but a worm.
O Lord! direct and assist by thy Spirit thy very poor and unworthy servant!`"

--

On the 11th of Seventh month, being still very poorly, and unable to move about,
he writes:

[.embedded-content-document]
--

This day, being First-day,
my beloved companion inclined to have the seamen called together,
to read the Bible to them.
I encouraged him to do so.
He afterwards spoke to them very suitably.
As for me, silent prostration of soul before the Lord is my proper allotment.

--

[.offset]
His memoranda then proceed:

[.embedded-content-document]
--

12th. I spent a night of watchfulness unto prayer, like Jacob,
wrestling the whole night for the Lord`'s blessing, and towards morning,
the light of his countenance has very graciously arisen upon me.
My trust and confidence is renewed in him,--blessed and praised be his adorable name!

At seven a.m., we discovered the entrance to the Bosphorus.
We came down very rapidly, keeping close to the Asiatic side, and by six o`'clock p.m.,
we anchored near the Seraglio.
Constantinople, from our ship, appears a very beautiful city,
with her many and large mosques, and their towering minarets; the many graveyards,
with upright gravestones, and tall green aloe trees:
the stones for the women are all of white marble, shaped to a point;
the top of those for the men are shaped like the head of a man,
painted according to the kind and colour of the turban that the individual wore.
The streets are like an amphitheatre, one above another.
The Asiatic part, on the opposite side, is beautiful also.
This is the time when the Turks keep their Lent, or Great Ramazan,
and now during the night all their minarets are illuminated;
some of them appear to have thousands of lights of various colours,
according to the glasses in which they are fancifully placed; these make a grand display,
particularly on the minarets near the Seraglio.

Constantinople, Seventh month, 13th. We landed at ten a.m. Thomas Nixon Black,
a merchant here for whom we had letters, kindly came on board to welcome us.
He accompanied us up to Pera, where Sir Robert Liston, the British Ambassador resides.
He had heard from London that we proposed to come to Constantinople, and expected us.
Both he and his lady, who looks like a serious, motherly woman,
very kindly pressed us to make our home in their palace,
which stands in a very airy situation; but we declined their invitation,
for we had previously accepted that of Nixon Black.
We found that it would be unsafe to put up at any of the Turkish hotels,
in most of which there are, or have been, some cases of the plague.
Nixon Black resides very near to Sir Robert Liston`'s. The latter has had the
kindness to send his Dragoman and a Janizary to bring our baggage from the ship.
They put it in large bags made of horse-hair,
which though handled by persons who have the plague, is not liable to communicate it,
whereas woollen, cotton, etc., are conductors of it.
They passed it through the custom-house without having it at all examined,
not even opening the bags.
When walking up the street from the ship,
we tried to keep at a respectful distance from the Turks,
so as not to touch their long flowing robes.
We find the interior of this city very different from what it appeared from the ship.
The streets are narrow, very steep and dirty.
Some have loose rolling stones in them, which appear very unsafe footing for horses,
yet we saw Turks going up or down with rapidity,--so sure-footed are their horses;
but there is no way for carriages.
We dined with the Ambassador. He stood for some years in that character in Philadelphia,
before Washington was built,
so that both he and his wife are well acquainted
with several of our friends in that city,
where they frequently attended our meetings;
they are therefore not strangers to our religious principles.
Among other persons we met there, is his chief Dragoman, an old Turk of good information.
He communicates nearly daily with the Sultan.
Most of the business of Ambassadors here is transacted through such a medium,
so that their Dragoman may be considered as their Prime Minister.
He speaks good English and French, and evinces great liberality of sentiment.
Several letters from America and England, of late dates, were waiting our arrival.
One from dear William Forster,
enclosing minutes of both the men`'s and women`'s Yearly Meetings,
signed by their clerks,
in which they convey their near and tender feeling of sympathy and unity with
us under our various exercises and religious engagements in these distant nations,
desiring our encouragement to proceed with faithfulness
in the work whereto the Lord has sent us.
Oh how sweet it is, thus to have the unity and sympathy of the church!
This is indeed a word of comfort and encouragement,
that the Lord sends us in time of need.
We received here a large supply of books of a religious character,
and also some treating of our principles, in different languages,
and a pretty good supply of New Testaments, sent us from Malta, in Greek, Latin,
and Italian.
Some of the Testaments are in modern Greek.

15th. Among the serious persons that we met with, are Greeks, Armenians, Italians,
some from Ragusa, also the old Dragoman--a Turk, and his son-in-law.
Seriousness appears in some of them.
They generally manifest a great desire to become informed of our Christian testimonies;
the Ragusans especially.
They told us that some of their friends in their country had heard of our Society,
and had often expressed desires to know more of us.
We have supplied them with appropriate books,--all in French.
We had religious opportunities with these persons to some satisfaction.
We do not expect to have much to do among the Turks;
my chief concern is for the Armenians and Greeks.

10th. We had felt our minds drawn towards their great prison, called the Bagnio, and,
through the Dragoman, permission to visit it was obtained.
It has now only five hundred prisoners, but in time of war, especially,
it is very crowded.
Several thousands of poor fellow-beings are then immured in it.
They are all mingled together, criminals, and prisoners of war.
All those that are able to labour, are put to work in the ship-yards, arsenals, etc.,
contiguous to the prison.
The latter is spacious and pretty airy during the summer,
but very uncomfortable in rainy seasons, or cold weather.
The prisoners are mostly chained two and two; no meat is given them;
the ration of bread allowed by the Government would be sufficient if they received it,
but the various hands through which it has to pass
before it comes to them retain a great part of it,
so that in the end the poor prisoners receive not one half of their allotted portion,
and they have in consequence emaciated looks;
some are so feeble that they can hardly drag themselves along.
We had several opportunities with them, through our Dragoman.
The Turkish officers who accompanied us did not appear to make any objection to it.
We found but few attacked with the plague in the prison, at which we were surprised,
for many parts of it are very filthy.
It is thought to be owing to the free circulation of air.
Whilst at work, which is from daylight to sunset,
except a quarter of an hour at noon to eat their morsel of bread,
an officer has the oversight of ten prisoners, and with a stick,
which he applies pretty freely, urges them on to their work.
These poor prisoners have indeed a miserable life, in consequence of which,
many of them die.
We visited other prisons, which are like the Segees in Russia; but here,
as justice is quickly administered, they do not remain long.
It frequently occurs that the police-officers,
without taking the trouble to carry the offender to prison,
give him the bastinado on the spot where they take him, or, if carried to prison,
they administer it there on the soles of the feet.
It is so severe, in some cases, that the sufferer dies in consequence of it.

The Captain Pasha wished to see us.
We found with him the Captain of the Port.
His Dragoman, who is a Greek Prince, interpreted for us.
The Pasha wished to inquire into the object of our visit here,
what other nations we had visited, etc.
It opened the way for our pleading on behalf of the suffering prisoners.
We told him it was the love of God and man that prompted us, not to see the country,
or the curiosities of it,
but to endeavour to press upon all men to live virtuous and pious lives.
If they did so, they would love God and man, and desire to promote the good of all men.
As we parted, the Captain of the Port invited us to go and see the launch of a man of war.
We told him that the most desirable sight he could
give us would be that of a man of peace.
These have been very painful engagements to us.

In the evening we visited a Greek merchant,
who has large possessions on one of the islands in the Archipelago,
where he has introduced several schools for the children of the poor.
Other Greeks met us here, with whom we had a religious opportunity;
these have generally received a good education.

The next morning,
Sir Robert Liston and his valuable wife accompanied us some
distance up the Bosphorus to see the Russian Ambassador,
for whom we had a letter from Prince Alexander Galitzin; we went in his barge,
which had eight rowers, all fine young Turks; each man handles two oars,
and they manage them with great dexterity.
We kept near the European side, on which are many handsome palaces;
some of these are the residences of the Sultan`'s relatives.
Some of the European Ambassadors also reside there.
Sir B. Liston took us first to the Spanish Ambassador`'s, a particular friend of his;
he sent him word yesterday that we should take a late breakfast with him.
On account of the great heat of the weather we left Constantinople very early,
but there having been a fine rain during the night, it was cool and very refreshing.
On our entering the apartment of the Spanish Ambassador`'s wife,
we were greatly surprised.
It seemed from her dress and manners, as if we were with one of our women Friends;
the Ambassador himself is a grave man, and simple in his dress and manners.
She told us that from a child she was brought up in simplicity of dress, which she likes;
it was, said she,
her valued mother`'s maxim and practice to endeavour
to adorn the mind with Christian virtues,
and not the body with vain apparel, which disfigures rather than embellishes it.
"`I have frequently thought,`" she said,
"`that could I have been in one of those nations where your Friends reside,
I should have been one of your Society,
for what I have heard of your religious principles
has greatly endeared your Friends to me;
you are, however, the first that I have ever seen.
My mother often spoke of your Society and religious principles;
she had read some of your books, but never saw any of your members;
she dressed as plainly as I do.`"
We found, on conversing with her on her religious views,
that she has a claim to our Christian affection;
the tenderness of her heart rendered her very near to us;
she is acquainted with the sensible influences of the Divine Spirit.
We were soon met by some of the other Ambassadors and their wives,--the Austrian,
the Neapolitan, and the French.
It was pleasant to see the harmony that appeared to be maintained
among these representatives of different nations;
had I anticipated such a meeting, I should probably have passed under much exercise,
but being thus brought about without any agency of ours,
I felt it my place to yield to whatever service might
be designed by my dear Master on such an occasion;
all speak French well; it was therefore easy to communicate to them what,
in the love of the dear Redeemer, we apprehended ourselves required to do.
We then went to the Russian Ambassador,
who kindly offered to serve us in all things that he can.

On our return to Constantinople, we kept on the Asiatic side of the Bosphorus;
we went on shore a short time,
to see the beauty of the country and the prodigious size of the trees growing there.
I felt much for our rowers, for they worked very hard,
and being very strict observers of the fast, during Ramazan,
they do not eat or drink from sunrise to sunset;
they were very thirsty under the burning sun, yet they would not touch a drop of water.
Amidst such observances of man`'s invention,
what a great departure there is from the law of God!
My heart is made very sad at the voice of the criers from the tops of their minarets,
that the hour of prayer has come: those who cannot go to the mosques,
fall down on their knees in the street, their heads to the ground,
and there remain for some time, regardless of the passengers around them; and yet,
during these last nights, many murders have taken place;
by order of the Government many of the Janizaries and others have been beheaded,
and the bodies thrown into the Bosphorus; it is said,
that last night two hundred had heavy irons put on them,
and then were thrown into the river, at the point of the Seraglio.
Sometimes I feel myself encompassed about with horrible darkness and distress.

21st. We have had several religious meetings in the palace of the British Ambassador,
held in the large audience chamber; and some others at our own lodgings,
where our generous host treats us with great kindness.
We met with some valuable persons among the Armenians;
they told us of some pious people at Tiflis and that neighborhood.
We have sent them some books that treat on our Christian doctrines.
We also find great openness among the Greeks.
We do not go to see the Greek Patriarch,
as there are some cases of the plague in his palace.
We often see in the streets persons attacked with this disease,
and it is not unfrequent that we meet the bodies
of such as have died with it carried to the grave;
they are laid upon a plank, which the bearers carry on their shoulders,
and walk very fast, the body shaking so as almost to roll off;
it is a very affecting sight.
The mortality increases rapidly, and has now risen to about eight hundred per day.

We were today with several strangers,--Prussians, Swedes, Spaniards, etc.
We directed them to the peaceable spirit of Christ.
We had also another satisfactory meeting at the palace of the British Ambassador;
among many others, the various Ambassadors and their wives were present;
as we proposed soon to leave the city, this was a parting opportunity.
Our taking leave of the wife of the Spanish Ambassador was in great Christian nearness;
we leave with her some Friends`' books, which she appears much to value.
Sir Robert Liston and wife have acted towards us the part of dear friends,
and greatly facilitated our religious services, when opportunity for such has presented.

--

[.offset]
Having taken their departure from the Crescent City, Stephen Grellet, goes on to say:

[.embedded-content-document]
--

Dardanelles, 25th of Seventh month.
Feeling ourselves at liberty to leave Constantinople, we took our passage for Smyrna,
on the British brig Whiting.
My mind had been under great oppression whilst in that city;
great darkness prevails there; the poor Jews are under heavy suffering;
the children of the Turks cast stones and dirt at them as they pass in the streets,
and they dare not give a sign of displeasure,
lest the parents of these children should inflict worse punishment on them,
even to the cutting off their heads.
The Greeks are but little better treated.
The Franks, however, (persons of other European nations) are treated civilly,
they being under the protection of their several Ambassadors.
Dogs are seen in great numbers throughout that city; if a Jew or a Greek tries,
with his stick or foot, to clear his way among them, and a Turk happens to see it,
he does not escape a severe punishment.

In our visit to those oppressed Greeks and Armenians,
we obtained the names of several valuable persons,
who reside in parts of Greece where we may come.
The account we have from Smyrna is gloomy, the plague has greatly prevailed there.
We are at anchor here,
waiting for a pass from the castle to allow our vessel to proceed on her voyage.
'`We are in sight of those enormous guns whereby stones of great size are intended to
be thrown at the vessels that attempt to pass up or down the Dardanelles without a permit,
or in time of war.

26th. Smyrna.
We came down here with great rapidity, the current being very strong.
We had the island of Tenedos on our right,
and the spot on which ancient Troy was seated on our left, in Asia Minor.
Then, passing by Mytilene, we arrived here this afternoon,
where we have taken up our quarters at an inn, kept by a Swiss.
Here resides David Offley, son of our late much valued friend Daniel Offley.
I knew David in Philadelphia when he was a youth; he has given us a hearty reception.
During the prevalence of the plague,
all intercourse between the Franks and other inhabitants was interrupted,
but now it is restored again.
The day before yesterday there was but one new case of that disease,
and no other has appeared today.

29th. Our minds are here greatly relieved from the load
of oppression and distress under which we were at Constantinople.
We meet with a number of Greeks who are serious persons, and religiously disposed.
We have had some private and more public religious opportunities among them.
A Dragoman kindly undertakes to be our interpreter,
both among the Greeks and such of the Turks as we visit.
One of these in particular has much interested us.
He is the Bey Effendi, Director of the custom-house.
He sent us an invitation by our Dragoman to visit him.
He is a mild, good-looking man.
When we came to his spacious apartment,
he was sitting after the Turkish fashion in his divan on a rich carpet, cross-legged,
with several pillows under and near him.
There were about twenty Turks with him, who all kept silence.
The Bey had his own Dragoman in attendance, so ours gave way to him.
He first introduced coffee,--a sign that the visitor is welcome; then sherbet, a cooling,
very pleasant drink,--a further evidence that he is superlatively welcome;
soon after which a conversation began between the Bey and us.
His Dragoman interpreted, but it went on very heavily.
Our minds were strongly attracted towards the Bey,
but there was something which we could not understand.
It was even distressing to our feelings.
On our withdrawing the Bey took leave of us in a most kind manner,
as if he had a sense of the state of our minds.
He called our Dragoman near, and whispered to him,
"`I cannot confide in these men (the Turks,) about me,
but very soon I will send another request to these friends to come here.`"
We were sent for again the next day.
We felt at first much disappointed on finding the Bey surrounded
by many more Turks than there were on the preceding day;
but the Bey now told us through our own Dragoman, "`you may now speak freely;
all these are my friends, in whom I have all confidence.`"
He evinced great liberality of sentiment;
said that he lamented the benighted state of his nation;
inquired into the nature of our religious principles,
and both he and the other Turks appeared much pleased with our answers.
He said,
that if all men were attentive and obedient to the Spirit of God in their hearts, peace,
harmony and happiness would prevail over the whole world;
for all the woe and misery that attend man in this life,
are the consequence of his departure from this blessed and Divine principle.
He made no objection to the testimony we bore to that redemption
from sin that comes by the Lord Jesus Christ,
and to the nature of that kingdom of blessedness
and glory which he has prepared for those,
who, believing in him, love and obey him.
Being told that we proposed to go from Smyrna to Scio,
he called for his secretary to write some lines recommending
us to the Turkish Governor there,
his particular friend, and son of the Captain Pasha, at Constantinople.
The secretary wrote on his knees, with a reed.
Instead of signing it, the Bey, after their manner, sealed it with his signet,
which he carries at his wrist.

We had several religious opportunities with the Armenians and others;
also with many of the Europeans of several nations.
Besides merchants, almost every nation has a Consul here.
Those attached to them and their families make them pretty numerous.
We had a long visit from a Popish priest, who said much in support of their mass,
confession, penance, purgatory, etc.,--but he got into such a passion,
that we tried to get rid of him as soon as we could.
We visited their prisons.
In one of these we were much interested in a young Greek whose offence was,
that he was found in the night without a light.
We succeeded in having him released,
by paying to the keepers of the prison twenty piasters, about two dollars.
In another prison we found many confined for small debts, mostly Greeks.
Several of them claimed much of our tender feeling and sympathy.
By paying one hundred and fifty piasters,
we had most of them released from their confinement.
We could but smile at ourselves, being among Turks,
and bargaining with them for the liberty of those poor Greeks and Armenians,
which we obtained for about two-thirds, or three-fourths less than at first asked.
We also visited the Greek and Armenian hospitals,
for some of whose inmates we felt very tenderly.
We had much satisfaction in a visit to a school for about three hundred Greek children.

31st. Paid another satisfactory visit to the Bey Effendi;
we gave him "`Penn`'s Maxims,`" "`Rise and Progress,`"--"`No Cross, No Crown,`" etc.
He desired Regio, our Dragoman, to come and read these to him.

Previous to our departure, we had a satisfactory meeting in the house of David Offley,
whose wife is a Greek;
many of the Greeks and persons who inhabit the quarter of the Franks attended.
By the British Consul from Adrianople, who came with us from Constantinople,
we had a good opportunity of sending to that place, and parts adjacent,
a selection of books treating on our religious principles,
as we heard that there are pious persons there who
inquire into the Christian testimonies of our Society.
Their desire to know more of them appears to have arisen from the circumstance,
that a Greek Bishop, at Janina, by some means came into possession, a few years ago,
of a copy of Barclay`'s Apology, in Latin, from Malta.
The reading of it pleased him so much, that he made a translation of it into Greek,
and took the pains to have two or more copies transcribed.
One of these was sent to Tiflis,
where again the bishops had some portions translated into Arabic,
particularly those on Divine worship and the ministry.
Some of these were circulated both in Egypt and Armenia.

By the advice of our friends here we have procured a person to act as interpreter for us,
and to provide for us in our future journeyings; without such an attendant,
they say we could not get along; for here,
as in Russia and particularly among the Tartars,
we have to buy our food and cook it ourselves.
Sobiesky, our Pole, had been very serviceable to us in these respects.
The person we have engaged here is well recommended; he is a Greek,
and speaks the Turkish, Italian, and French languages.

--

Having made these arrangements they left Smyrna, and went on board the boat for Scio,
about half past ten at night.
