== Chapter XXXVI.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Corinth
* Patras
* Zante
* Corfu

They now "`departed from Athens and came to Corinth.`"
This place so closely connected with the life and
labours of the great Apostle of the Gentiles,
and the early progress of Christianity,
they found almost crushed under the influence of Mahometan oppression.
The city where Paul was once so much "`pressed in spirit,
and testified that Jesus was Christ;`" where he commenced his Christian
correspondence with the primitive churches,--from which,
or to which,
he wrote some of his most important Epistles,--and which has so
many interesting claims upon the attention of the Christian student,^
footnote:[See the "`Life and Epistles of St. Paul,`" by Conybeare and Howson.]
did not afford much scope for their Gospel labours.
They soon left it, and passed on to Patras.
Thence they sailed to Zante, among the Ionian Isles.
Here they were detained by the serious illness of William Allen.
After his partial recovery they proceeded to Corfu, where,
having "`partaken together of the consolations of
the Gospel,`" their joint labours came to a close.
With deepened feelings of Christian fellowship they took leave of each other.
William Allen went to Malta, on his homeward course;
and Stephen Grellet embarked for Italy.
Pursuing his narrative he says:--

[.embedded-content-document]
--

Eighth month, 28th. We left Athens early this morning on horseback.
The roads were hilly and stony, and the sun very hot.
The country is beautiful, and some of the views are grand.
We came about twelve miles to a village which was formerly a considerable town,
called Lefsina.
From the many ruins scattered about,
we judge that it had once large and stately buildings The marble columns
that sustained some edifices are beautifully carved and fluted.
Many of them are more than three feet in diameter.
The miserable house at which we stopped,
and in which we were glad to have a shelter from the scorching sun, has an earthen floor.
Our horses were admitted as well as ourselves;
but on the place which we occupied there were some mats to sit upon.
I felt so weary and spent by the heat of the sun,
that I would gladly have laid down to take some rest: but we had hardly come in,
when about twenty of the villagers came to gaze at us.
More of them followed soon after, and their priest among them.
I felt the love of Christ towards them.
I wished to communicate something to them, but our interpreter was not there.
He had gone into the village to buy some provisions.
Another way however seemed to open for conveying my religious impressions.
I opened the Greek Testament on those parts which
contained what I wished to bring before them.
These passages I got the priest to read to them.
So forcible is the plain truth, in the simple language of Scripture, that,
on hearing it read, several of these people were much affected, and broken into tears,
so that when our interpreter returned,
their hearts were prepared to receive what we had further to impart.
We found that they had never heard the Scriptures read.
The priest himself had not a copy of them.
He entreated us to give him one, saying,
he would keep it very carefully locked up in the church.
We told him, before all the people, that we would give them a few copies,
on condition that they would not keep them locked up,
but that frequently during the week, and especially on First-days,
they would meet together, and that the priest or such of them as are able,
would read them audibly to all the others.
They promised they would do so, and parted from us in great tenderness.

We rode then about fifteen miles further to Megara, an ancient town of the Athenians;
it was formerly a very populous place, now it contains about two thousand inhabitants;
their houses are poor, and so is also their land about them, for want of cultivation;
it was once very fertile; the mountains round are beautiful.
We found much openness among the people,
and distributed several New Testaments and tracts.
I felt very unwell during the night; the heat of the sun having affected my head,
and the bugs, etc., not allowing us to keep in doors,
we passed the night on the house top, a flat roof as is usual here;
but there the red ants greatly annoyed us; they are very venomous.

Next morning we rode twenty miles to a large shady tree,
near which there is water,--two very desirable objects under such a warm sun;
we needed them both very much, especially as we had just come down a steep,
rocky mountain, in doing which,
some dangers attended by the falling down of our horses and mules;
here we made our meal on a piece of bread, and drank some of the water;
it so refreshed us,
that we thought the best served table could not have proved a better treat to us.
The whole of our ride today has been mostly through a rocky and barren land.
The first signs of inhabitants we met were four large dogs that came furiously at us;
we were in a strait for awhile, but some Turks appeared at their barking,
and we found ourselves at a military post of Turks placed there a few months since.
The part of the country we have travelled was infested with robbers,
especially near the water where we had refreshed ourselves; we did not see any,
though travellers are still frequently molested by them,
sometimes to the loss of their lives.
The Lord, under the shadow of whose wings we have trusted,
is mercifully pleased to be our shield and deliverer, day after day;
blessed and holy is his name!
We reached Corinth at night.
We took up our quarters at a kind of inn kept by an Italian.

Corinth,
30th. We spent some very interesting hours with the Primate of the Greeks in these parts;
he is in a feeble state of health, and is a thoughtful serious man;
he feels deeply for the degraded and oppressed state in which the
people of his nation are kept by the Turkish authorities;
the iron yoke being heavier on them here than in any parts where we have been.
The Turks in their sports, or to try the edge of their sabres, cut off a man`'s head,
as he passes them in the street or highway; or, to show what good marksmen they are,
they fire at him with their guns; and no public notice is taken of it.
The Primate appears to have his heart turned towards a better life,
which he hopes to enter through faith in the redeeming mercy and free love of Christ.
We gave him Penn`'s "`No Cross, No Crown,`" and some religious tracts.
We shall long remember the sweetness and tenderness of his spirit.

Finding no object to detain us here, we hired a fishing boat to take us,
by the Gulf of Lepanto, to Patras.
The description given us of the road across the country
induced us to try to proceed in this way.
We left Corinth in the evening, and greatly enjoyed the air, the night,
and the fine views on this beautiful gulf, the sea being very calm.

The next day the wind blew hard, and so contrary,
that our boatman was obliged to seek for a place of shelter, by going back some distance;
here we passed a second night in our small boat, which did not protect us from the rain,
accompanied by thunder and lightning.
The wind having abated in the morning, we moved on again, by rowing for some hours;
but at last, the sea got so high that we could not safely proceed further;
we therefore turned back towards a village, where we landed.
We were also in want of provisions;
the bread we had taken with us was wet by the waves and the rain of the preceding night.
Tn the village we met a number of the Albanian soldiers;
we had some religious service with them and the Greeks,
and gave them some tracts and copies of the New Testament;
they had not Been the latter before;
they said they would have them safely deposited in their church;
we dissuaded them from that, and they promised to collect together and read it,
especially on First-days.
We passed the night again in our boat,
though it is too small for any of us to attempt to lie down.
Next morning, the wind continuing high and stormy,
we endeavoured to hire mules to take us by land the remainder of the journey to Patras.

--

Through much difficulty and fatigue they reached that place on the 3rd of Ninth month.
They found the people on the road in a state of great ignorance,
and "`a truly affecting degree of insensibility,
many of the monks not appearing to understand that they had a soul to save,
or even that there is a God.`"

[.embedded-content-document]
--

"`We found very little in Patras,`" Stephen Grellet continues, "`to comfort our spirits,
except a few individuals who manifested some religious tenderness.
How deeply do I deplore the conduct of some of the monks here.
By their evil example they entice many of the poor ignorant people into vice.
Our way appears now pretty clear to leave the Morea for some of the Ionian Isles.`"

--

They left Patras the next day, and, after a good passage, arrived at Zante.
There they had to perform quarantine,
on account of the plague which prevailed in Turkey and Greece.

[.embedded-content-document]
--

Zante, 5th of Ninth Month.
Through the kindness of Colonel Ross, Commandant of this island, and of Doctor Thomas,
who has the charge of the quarantine, quarters are assigned us in an old monastery,
instead of the lazaretto, which is crowded.
Here we have the privilege of a garden to walk in.

10th. I enjoy these days of retirement, though clothed with great poverty.
The Lord is also graciously pleased to settle my mind in much calmness and resignation
in the prospect of being left by my beloved companion and co-worker.
He continues to believe that the time has nearly come for his return to London.
To the Lord`'s guidance I must resign him.
Great has been His goodness to me in granting me such a beloved one as fellow-helper
through the various countries we have visited since leaving England.
Now instead of repining at the prospect of a separation,
my soul blesses the Lord for favours received, and is permitted also to hope for more;
though which way they will come I do not know;
but they all proceed from Him who is the God of all our sure mercies.
Through the favour of Colonel Boss, the time of our quarantine is shortened;
we are told that we shall be liberated this afternoon.

12th. We have visited several Greeks seriously disposed, and been also in their prisons,
poorhouse, and hospital.
Here we are among so many English people,
that we find no difficulty in obtaining interpreters.
Many of the Greeks of the higher class also understand French.
A monk of the Greek church came to see us yesterday.
He was inquisitive after the Truth, and the doctrines of it;
yet I thought he resembled Pilate, who inquired "`what is Truth?`"
but had no disposition to walk in it.

13th. Accompanied by Doctor Thomas,
we rode some distance in the island to visit the inhabitants of some of their villages,
among whom we had several religious opportunities; in one particularly,
many of the people were gathered, and manifested much soberness.
In every place they gratefully received the Greek
Testaments and religious tracts we handed to them.
In one of these villages we met with the Governor, Colonel Ross, and many of his officers.
The country is nicely cultivated with vineyards, and the currant vines.
We passed near a spring from whence a substance like tar is continually oozing.
It is used on timber for the same purpose as tar.
We returned in time for a late dinner with the Governor.
His wife is a very interesting woman.
The modesty and good behaviour of her daughters shew
forth the fruits of her pious example and instructions.

14th. We had this morning a visit from Prince Cornuto, with whom we had been before.
He is a serious, aged man.
He went with us to a meeting held at the Protopapa`'s,
which was largely attended by the Greeks and English.
Many of the clergy, and military and civil officers were also present.
There appeared to be an open door with them to receive what, in the love of Christ,
we felt it our place to proclaim to them.

16th. I spend many hours in retirement, pouring forth my heart and tears before the Lord.
My poverty is very great.
I am humbled to the dust.
No past favour, nor experience of the Lord`'s power and mercy can,
even by a lively remembrance of them, minister to the soul`'s present wants;
its supplies must flow fresh from the Divine fountain.
In this state of deep abasement, ability is given to enter the house of prayer,
and with supplication to make our wants known to Him who alone can minister to us.

18th. Yesterday morning the Protopapa with six of his clergy came to see us.
He was serious.
He gives a deplorable account of the ignorance and morals of many of the monks.
A Capuchin friar, a Roman Catholic, has also come.
He was at first full of words, and queried of us in a dogmatical manner,
why we do not use the church ceremonies, sacraments, etc.
'`We told him that if he had come to enter into religious
dispute or controversy we must decline it,
for we never saw these tend to edification; but if, from religious motives,
he was desirous to converse on things pertaining to the salvation of the soul,
through our Lord Jesus Christ,
we would endeavour in the simplicity of our hearts to answer him.
He then inquired into our opinions respecting the true church, water baptism, their mass,
purgatory, etc.
We endeavoured to give him our views on these subjects; he was moderate,
but with him Scripture authority did not avail.
The Pope`'s decrees and their church`'s traditions are his strong-holds:
he appeared to have a very imperfect knowledge of the Scriptures.
We had a precious religious season at the Governor`'s house,
and another at Doctor Thomas`'s, with his family and others.
This evening, dear Allen and I had a sweet refreshing season in the Lord`'s presence,
favoured to resign one another to his will: W. A., to return home, and I to proceed,
single-handed, in the further service my blessed Master has for me in other nations,
not only to go to Rome, but to die there also,
should he order that my life be like a seal to the Gospel service required of me there.

--

For some days William Allen had occasionally suffered from headache.
Soon after the preceding record he was obliged to "`give
up entirely to nursing,`" and became very seriously ill.
Stephen Grellet continues:--

[.embedded-content-document]
--

19th. My beloved companion has a high fever.
I also receive heavy tidings from some of my relatives in France;
and of my beloved wife in America, who was sick.
Thus are the troubles of my heart enlarged; in the Lord alone is my refuge;
He can support under every tribulation, and sanctify them all.

24th. The illness of dear William Allen continues to increase.
I have accepted the kind invitation of the Governor to have him removed to his palace,
to airy apartments fronting the sea.
The rooms we occupied in the town were in a confined place.
I had him carried in a sedan chair.

26th. I had a distressing night; my beloved friend appeared gradually sinking away;
all the skill of Doctor Thomas, who is an experienced physician in this climate,
is exerted on his behalf; my solicitude on account of my dear wife is great also;
but the Lord who gave me, when resigning my all into his hands,
to feel a peaceful calm in the assurance that by his love and power all will be well,
can restore the health of dear Allen, if so be his good pleasure.

27th. My dear friend consented last evening to my calling in two other physicians,
to consult with Doctor Thomas;
they agree with him in his course of treatment of the dear patient.

30th. W. A. is a little better.
We had last night an earthquake; the second since we came on this island,
where they are frequent; last year several houses were thrown down by them.

8th of Tenth month.
My beloved companion gains a little strength, though still feeble.
These days past I have had some satisfactory religious meetings.
I also receive frequent visits from persons piously disposed, who have inquiring minds;
there are among these, Greeks from several other islands, and also from the Morea.

11th. I had a letter this day from America; my beloved wife`'s health is better;
dear W. A. also.
My soul blesses the Lord for these favours!

12th. A small vessel came in last night from Corfu, and is to go back this evening;
dear Allen has thought that if there was a vessel here to take him there,
the sea air would do him good, and might accelerate his recovery;
his physicians think it would be of use to him, and I also feel ready to go hence;
I have therefore industriously prepared everything for our departure this evening;
dear William proposes, as soon as he is able and a suitable vessel presents,
to go to Malta, thence by France to London;
my line of duty appears to be to proceed from Corfu to Italy.

13th. Cephalonia.
I had wished to come on this island but did not see how
it could be effected in the feeble state of my dear companion;
at four p.m., yesterday, he was carried on board the cutter _Diana_;
the weather was fine and serene; after we put out to sea he felt much refreshed;
it acted on his feeble frame as it did on me when I left the island of Hayti.
But our fair prospect soon changed, a violent storm arose,
accompanied with torrents of rain, thunder and lightning; the sea broke in over us,
and dashed into the cabin, so that dear William was completely drenched.
The Captain succeeded in getting into a harbour on this island called Fitscardy;
but even here the vessel tossed greatly, so high were the waves.
It would not have been prudent to remove dear W. A. from the vessel,
as the village stands at a distance on a high hill.
I went there and had a religious opportunity with the inhabitants;
they appear generally to be in profound ignorance,
much unacquainted with things pertaining to salvation; a few of them, however,
gave some signs of tenderness, whilst I reasoned with them of righteousness, temperance,
and judgment to come.
The islands of Santa Maura and Ithaca are in full view from the top of the hill.
Santa Maura is at present in a state of insurrection,
so that British troops are sent there from the other Ionian islands; Ithaca is small,
and resembles the hull of a ship.
From what I could discover here, Cephalonia is ripe for an insurrection also.
A short distance from our vessel is a beautiful grotto;
the only entrance is from the sea,
and so small that I had to crouch down in the boat in passing into it; after getting in,
we are under a fine spacious vault of solid rock, from forty to fifty feet in height,
from whence hangs down in festoons a very delicate fern of a fine texture.
The cave is one hundred and ten yards in length, sixty in diameter,
and the water is of great depth; at the further end,
close to the smooth side of the rock,
is a natural seat that extends the whole breadth of the cave,
having a small place between it and the water quite dry; it is a beautiful, cool retreat.

Corfu, 17th. We left Cephalonia on the 15th;
but contrary winds and a high sea prevented us from progressing, except slowly;
I was very sea-sick;
neither I nor our Greek attendant was able to minister to dear W. A.; but he,
amidst these difficulties, continued to gain strength,
so that on our arrival he seems like a new man; and here, to our great comfort,
we met with Doctor Skey,
an old acquaintance of William Allen`'s. On hearing of our arrival,
he came immediately to meet us on board the vessel,
and in the most hospitable manner has taken us to his house,
where dear William has many of the comfortable accommodations of an English home;
he felt so refreshed every way after getting here, that to our great surprise,
he sat with us at the dinner table; I could hardly believe my own eyes.

18th. Last night we had a storm, attended with an earthquake;
the rain fell as if the flood-gates of the sky had been opened;
truly thankful we were not to be on the unstable element.
My dear Allen continues to improve,
and has come to the peaceful conclusion to go from here
to Malta by the packet which is expected two weeks hence,
and to take with him there our faithful Greek attendant;
my own way opens with brightness to go from here to Barletta;
there is a vessel in port bound for that place.
I have visited some pious individuals to satisfaction, also their hospital.

19th. Sir Thomas Maitland, Governor of the Ionian Isles,
and Commandant of the British forces in the Mediterranean, arrived here last night;
we had a letter for him from the British Ambassador at Constantinople,
which it was proper I should deliver to him early,
as I had taken my passage for Barletta, and dear William was not able to go.
I was brought into trial; for after coming to the palace,
it appeared that the General had come from Malta
in consequence of the insurrection at Santa Maura,
and the threatening of the same in others of the Ionian Isles.
I sent the letter to him,
but he was then in close conference with the chief
men among the Greeks in several of the islands,
who had come to meet him; he sent me word to wait a short time for him;
from the apartment in which I was, I heard him speak to the Greeks under much excitement;
gladly would I have retired, had I not been requested to wait,
for I thought he would not be in a state of mind in which
I could have much satisfaction in seeing him.
Their conference broke up at last, and I was introduced.
The General had received letters from England,
by which we were both recommended to his kind attention;
he soon assumed a mild and placid countenance and made many
inquiries respecting the places we had visited,
and the nature of our engagements; he knows dear William by character,
and feels for him in his present feeble state of health.
Understanding that I proposed to go to Naples, he said,
"`Why then will you go by Barletta,
when from thence you will have a rough and dangerous journey to Naples?
my frigate has nothing to do; it will be ready at any hour you please,
to carry you to Malta, where you will have a very short quarantine to perform;
whereas you will have a long one at Barletta.`"
I excused myself from accepting his kind offer by
saying that I might meet with some detention in Malta,
if there was no vessel ready to go to Naples.
"`You need have no fear on that account,`" he answered, "`for I will send orders,
and one of my ships shall be ready to take you at any time.`"
Then I told him plainly on what ground I could not go by a ship of war;
that I was on an errand of peace; that besides,
I wished to visit some parts of Italy between Barletta and Naples.
"`Well,`" said he,
"`as you may perhaps meet with some difficulties among those bigoted Papists,
at Naples and at Rome, I will have letters ready for our Ambassadors there,
also for the Chevalier de Medici, Prime Minister of the King at Naples,
and also for the Cardinal Consalvi, Prime Minister of the Pope;
he is my particular friend, and I shall have him apprised of your coming,
before your arrival there.`"
I stated to the General the deplorable ignorance
of the mass of the people in these islands,
and the necessity of endeavouring to raise them from their
degraded and demoralized condition by establishing schools,
where the children might be educated in the principles of morality, virtue and religion.
The General appears disposed to take steps towards this,
and have qualified and pious teachers from England for the purpose.

--

Occupied to the last with the objects of his mission and cheered
by seeing his beloved companion so much improved in health,
Stephen Grellet was now brought to the parting hour.
It was an interesting and a solemn one;
it is thus alluded to on board the vessel that was to take him to Barletta.

[.embedded-content-document]
--

20th. At sea, on the Adriatic.
This morning, previous to our separation,
dear Allen and I had a very solemn and precious season before the Lord;
we felt the bond of gospel love uniting us closely,
and perhaps more powerfully felt than at any time before;
but believing that our separation is in the counsel of Him who, in his love and mercy,
had banded us together, we resigned one another to His will,
and we commit ourselves to His guidance and protection.
I leave him peacefully, under the care of Doctor Skey, a very kind friend to him.
The Doctor accompanied me on board the vessel at two p.m.

--
