== Chapter XXXVIII.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Rome

Pius VII was in the last years of his Pontificate.
He had lived in eventful times.
Raised to the Papal chair in the early days of the French revolutionary wars,
he had crowned Napoleon at Paris, in 1804; but was, nevertheless, seized by him in 1809,
and kept a prisoner at Fontainebleau till,
almost entirely by the intervention of Non-Catholic powers,
he regained possession of his states, at the downfall of his oppressor, in 1814.
Though one of the first acts,
by which he distinguished his return to the administration of his office,
was the restoration of the Jesuits, there seemed to be evidence, during his latter days,
that "`the conflict respecting creeds had been nearly set at rest in political circles,
and was gradually losing its violence in civil life.`"^
footnote:[Kanke`'s __History of the Popes__]
He had nearly reached the advanced age of eighty, when Stephen.
Grellet visited Rome, and was admitted to a personal interview with him.

During the fortnight which Stephen Grellet spent in the Papal city,
his Christian labours were varied, and almost incessant.
Interesting particulars are preserved in his Diary.

[.embedded-content-document]
--

Rome, 25th of Eleventh month, 1819.
I left Naples on the 23rd, in the evening.
Travelling two nights and one day, I arrived here early this morning.
Through the Lord`'s merciful preservation,
I have again escaped falling into the hands of banditti, which abound on this road,
notwithstanding the severity of the laws against them.
Every few miles I beheld the horrible sight of human flesh,
hanging on posts by the sides of the road,
near the places where murders have been committed,
giving evidence that they have been many.
Some of these appeared to have been quartered only a few days before;
but notwithstanding all this, robberies and murders are no less frequent,
especially on the Pope`'s territory.
How often, in these my journeyings, do I feel as if my life was offered up;
day after day, and night after night,
I know not but that I may fall a prey to the hands of unrighteous and wicked men;
but very good and gracious is my blessed Lord:
how precious is the sense of his Divine presence!
David said, "`Thou art continually with me.`"
Truly I may say so likewise; the fear of offending so good and gracious a Master, was,
during these nights, or under such circumstances,
greater than any apprehension of what may be suffered to befall my outward man.

On my arrival here, this morning,
I found that this is the day on which the Cardinal Consalvi, Prime Minister of the Pope,
gives his public audiences,
when all who have petitions or wish to have a private interview present themselves.
It seemed as if I could do nothing in this great
and ancient city till I had been with him.
I had been two nights and one day on the road,
but the great weight of exercise on my mind prevented my feeling much weariness.
I was now in the place for which I had deeply felt for years;
my rest was to see what my great Master had for me to do,
and to endeavour to engage in it, though it might be to enter into bonds and sufferings;
for truly, like Paul, I do not know what things are to befall me here,
only the persuasion arises that sufferings await me.
I changed my travelling garments, took some refreshment, and by eight o`'clock,
I was at the Quirinal, the Pope`'s palace.
I did not know how to act, or what to do; I was alone; I knew nobody;
but I thought I would take notice of what others did.
I first came into a spacious hall,
near the foot of the stairs that lead up to the Pope`'s apartments;
here was collected a large company of priests, monks, military, private citizens,
strangers from several nations; many of them had papers,
or rolls of paper in their hands, which I considered might be their petitions,
etc. so I had my letters from Maitland and Medici ready.
We waited nearly an hour,
during which I plainly saw that my dress and hat attracted general observation;
whispering, querying who I could be.
They all were uncovered.
After a while there was a general bustle among the company.
They went out into a large corridor, extending from the stair-case,
and stood in rows on each side, with papers in their hands.
I took my station with them in the ranks.
As the Cardinal came on, each, as he passed, presented his papers,
which were placed in the hands of his attendants.
Some tried to kiss his hand, others his feet.
As he came towards me, by my dress he probably recognized who I was,
so that before I could hand him the letters, he politely asked,
"`Are you not Mr. Grellet?`"
to which answering in the affirmative he said.
"`Please to call on me at my own palace,
tomorrow morning;`" and I gave him the letters I had for him.

I now wait to see what may be unfolded for me to do here.
Great is the travail of my soul, that I may be preserved watchful unto prayer,
and enabled with singleness of heart and faithfulness,
to attend to all my Lord`'s requirings.

26th. I went this morning to the Cardinal`'s palace;
in the ante-chamber I had some satisfaction in conversing with two young priests,
his secretaries;
they evince more liberality of mind than is generally found among that class of men;
there were many in waiting to have an audience with the Cardinal,
but as soon as he found I had come, he came out from his cabinet, called me in,
and made me sit down on a sofa by him;
from the nature of his inquiries it would appear that General Maitland had given him
a particular account of my late travels and religious engagements through Russia,
Greece, etc.; but he was particularly desirous to know more of our religious Society,
its principles, doctrines, discipline, etc.
On some such occasions I find it proper to give the perusal of my certificates.
The religious care of our Society towards their ministers,
before liberating them for the work of the Gospel,
to which they apprehend they are called of the Lord, is much commended by the Cardinal.
As there were so many persons in waiting in the ante-chamber,
I made several attempts to withdraw; but he had more inquiries to make,
which detained me altogether about an hour and a half with him;
he was not in anywise offended when, in answer to some of his inquiries,
I had to expose pretty fully some of the superstitions of the Romish Church,
and to make my confession that the Lord Jesus Christ is the only Head of his Church,
and the Saviour of men.
I also gave him a full statement of the conduct of their missionaries in Greece,
the mischief they are doing there,
and what seeds of distress and unhappiness in families they are sowing;
I represented to him also the very unchristian and unbecoming conduct of those who,
in the south of Russia, did hang and then burn the Scriptures,
and of the public burning of the Bible, at Naples, by the Bishop and his clergy;
all of which the Cardinal reprobates, and properly says,
"`It militates against religion.`"
Finally, before we parted, he wished to know in what he could serve me;
I told him I should like to visit some of their prisons and public establishments,
and that I should be obliged to him if he would procure me admittance to them;
he then took me by the hand, and accompanied me,
through those waiting in the ante-chamber, to the door into the court.
Surely it is the Lord`'s doing, in the very centre of Popery, even among the heads of it,
to make way for one, who holds testimonies so contrary to them,
to proclaim the Lord Jesus as the sole Head of the church,
and the author of eternal salvation to all that believe in him.
Under the concern that I have in visiting the abodes of human misery and woe,
I find that,
besides feelings of near sympathy for the sufferings of so many of my fellow-men,
it is in some of those places that I am often in
the way of meeting with benevolent and pious persons;
for in places of public concourse these are not to be found.

In the evening the Cardinal sent me a letter,
enclosing orders for my admittance into the various places that I wish to visit,
with his instructions to go first to the Governor, Pacca,
who would provide a suitable person to accompany me, and to interpret for me.

27th. This morning, about nine, I went to the Government house.
At first, under the garb of a priest, I could not recognize the Governor; he,
seeing my embarrassment, said, "`You must know that here, at Rome,
the clerical garb is that of the court.`"
I am told that their General is a Cardinal; thus,
those who profess to be ministers of the Prince of Peace are ministers of war,
and generals of armies!
O the inconsistency!
Many persons were with the Governor all dressed like priests;
I could not find out what they were; one of them was Olgiati,
President of St. Michael`'s Castle, for whom I had a letter from the Cardinal Consalvi,
which I handed to him.
I was myself an object of curiosity to them,
for it is a very novel thing for them to see a Quaker; they had much to inquire after,
but were all very civil, and my blessed Lord strengthened me to proclaim his holy name,
without equivocation, in simplicity and truth.
He performs his gracious promise, "`I will make thee as an iron wall,
and a brazen pillar before them.`"
The Governor sent for a young man, one of his secretaries, to accompany me.
Whilst I was waiting for him, in another apartment, the Assessor came in, who,
on seeing me with my hat on, was much offended, so that, for a while,
there was no room to enter into any explanation; he had never heard of the Quakers,
nor of their principles; after a while his clerks came in,
for it appears I was in his apartment; by degrees his countenance altered,
and in the presence of a number of others that came,
he entered into many inquiries respecting our principles,
and what constitutes true Christianity;
he was much brought down and treated me with great civility.
By that time the young man sent for by the Governor came in;
I felt from the first my heart inclined towards him; he is a serious young man,
and his mind is made soft and chastened by the loss of his wife within a few weeks, who,
I am told, was a beautiful and virtuous young woman; he speaks good French.
He went with me to several prisons for the Gallerians, and to the secret prison;
here they have a complete system of espionage;
the cells are so constructed that they succeed in becoming
acquainted with what the prisoners say to one another.
They have very high ceilings, in which there is an opening,
which appears to be intended only for a ventilator,
but here a man is stationed who can hear nearly every word spoken in the cell.
They place in the same cell such as have been connected together in crimes,
that they may be encouraged to converse with each other.
The person whose business it is to hearken to what the prisoners say,
is particularly attentive to be at his station before
the prisoners are taken out to be interrogated,
and on their return also;
on which occasions they are often heard to agree on what they shall say,
and to talk on what occurred during the interrogation, and thus they commit themselves.
But the listener may often hear indistinctly, and by misrepresentation,
though without evil intention,
cause these men to be condemned on the plea that they have avowed their guilt.
By their laws no man is condemned unless he confesses himself guilty,
and by this plan they think they obtain such an acknowledgment;
some years past a confession was extorted by the cruelty of torture.
I saw some prisoners confined there on account of religion,
but could not understand for what particulars; my kind attendant is, however,
very ready in interpreting for me whenever I request him,
and during some communications I made through him in several cells,
some of the prisoners were tender.

28th. I visited two large hospitals called St. Spirito and St. Charles;
and a large poorhouse, where, besides aged people,
there are four hundred boys and five hundred girls.
I had several religious opportunities, in some of which sensibility was apparent.
I was also in a prison where about one hundred and twenty brigands are confined.
They, and their wives and children, were routed out of their habitations,
and are intended to be settled in distant places.
Some of them may be innocent.
The tenderness manifested during the religious opportunity I had with them,
may perhaps induce me to entertain such a sentiment.
I was pleased with a retreat for convalescent persons.
They are sent here from the hospitals, where,
for about two weeks previous to their final discharge, they have good,
nourishing food given them,
that they may get strength to proceed in the necessary business of life.
The meeting I had among them was a peculiarly tendering season.
Adjoining to this is a spacious place for the reception of pilgrims,
travelling to various parts, even such as go to Jerusalem.
Here they remain a longer or shorter time to rest,
according to the length of the journey they have come, or have to go.
The apartments for men and women, are entirely separate.
In each place are large marble basins,
some for washing the feet only,--for the pilgrims travel barefoot,--others for baths,
into which warm and cold water may be let in, to the liking of the pilgrim.
They have also good beds and food provided for them.
It is very common for men and women of rank, priests, bishops, or cardinals,
at least once a year, to repair here and wash the feet of the travellers;
also to serve them during their meals.
They consider such acts as very meritorious.
The eating room is large and lofty.

This has been another day of very close engagement and mental suffering.
I visited a prison, said to be a place of correction for boys;
very imposing was the sight on my first entering,
accompanied by several priests belonging to this establishment,
and others connected with it,
as they were giving a glowing description of the
great reform that they were instrumental in effecting.
The lofty apartment I was in, is about two hundred feet in length, and forty in height.
On both sides of this room were small chambers; opposite to each door was a boy,
cleanly dressed, with a spinning wheel: all seemed industrious,
and profound silence prevailed amongst them.
It seemed to be a pleasant Bight; but, casting my eyes downward,
I observed that every boy had a chain at his ancle,
allowing him to go only from his cell to his wheel!
Then I beheld several inclined blocks, with stocks to confine hands and feet,
and knotted cords and whips, near them.
Inquiring the meaning of all this; "`O,`" said the priests,
"`these are the places where they receive their correction morning and evening,
on their bare backs.`"
"`Is this,`" I queried,
"`the method whereby you bring about such great reform among these boys?
You may indeed excite the angry passions in them, by such doings,
but you will never change their evil heart.`"
In another part I was with women and girls, towards whom similar treatment is used,
to reform them from their vicious habits.
My endeavours to plead with these priests,
and to set before them the ways that a Christian spirit would dictate, and which,
through the Lord`'s blessing,
might prove efficacious to the recovery of these young persons, have, I fear,
had very little place with them.

29th. I had a suffering night, my mind was under great distress;
I feel at times as if I was among lions and serpents,
and as if I was treading over scorpions, and yet, amidst these feelings,
it is laid upon me to try to visit the Inquisition; thus to go into the lion`'s den.

This afternoon I visited the foundling-hospital, and large schools for boys.
In the first I met many of the nuns; some appeared to have ears to hear,
and hearts to feel.
I had also an interesting season with a large number of the foundlings,
grown up to young women`'s estate.
Some of the priests interpreted for me to them, to the nuns, and to the boys.
Priests are often the instruments that the Lord provides for me,
to convey to others the things pertaining to his glorious kingdom,
and the nature of that religion, pure and undefiled,
so contrary to those pollutions that men`'s devices
have introduced into the Church of Christ,
and into his worship.
This evening I am told that there is a great outcry
raised by some of the Cardinals and others,
at the liberty granted me to pry into their secret things.
Some also say, that my appearing, as I have done, with my head covered before a Cardinal,
is a thing never before known.
I see no other way for me, but, in simplicity and singleness,
to go on in the way that my blessed Master directs me.
To him I leave all the result.
My liberty, and even my life, is in his hand.
I miss very much the company of my beloved friend, William Allen.
He was such a faithful fellow-helper, under preceding deep conflicts;
but now I am left a poor solitary one; and yet not alone,
for I am very sensible that the Lord fulfils his very gracious promise to his poor servant,
"`verily, my presence shall go with thee.`"

30th. I went this morning to the Quirinal, and spent some time with Consalvi;
he wishes me to send him an account of my observations,
in the visits I make to their prisons, etc., etc.
I told him of my wish to visit the Inquisition;
he said he could not himself grant such a permission,
but he would endeavour to obtain it from Father Miranda,
who is the head of the inquisitors.
// lint-disable invalid-characters
I had a private satisfactory time with the Abbé Capacini, Secretary of the Cardinal;
he is a feeling, liberally-minded young man.
My visits this day to some hospitals and poorhouses have
administered more consolation than on preceding days;
I found much religious sensibility with several, also among some monks and nuns.
I preached to them the Lord Jesus Christ the only hope of salvation,
and described to them what the christian cross is, and where it is to be borne.
One of these hospitals for men only is attended altogether by monks;
I thought some of them evinced genuine piety:
their great kindness in waiting on the sick is striking.
The dear young man, my faithful attendant,
is very useful in interpreting when he has not to give way to the priests;
but even then he is a witness that they perform their task with faithfulness.

1st of Twelfth month.
I visited this day a large college, formerly kept by the Jesuits, now banished from here;
there are about six hundred students in it.
There I was among many priests also;
when I began to speak some of the young men were somewhat rude; but very soon,
silence and seriousness spread over them.
The Lord helped me to proclaim the everlasting Truth among them.
Then I went to another school for four hundred boys, where their teacher,
a very feeling man, a priest, acted as my interpreter.
My next visit was to a nunnery, which has a school for girls,
where the Lord was also near, in enabling me to proclaim his holy name;
the Superior of the nuns has felt the Lord`'s power; she has a pious mind.
It is marvellous that,
though these religious services bring me into contact with so many priests,
monks and nuns, when they hear doctrines so new to them,
which also strike at the root of Popery, no one has yet made an objection; but,
on my taking leave of them, they treat me with kindness;
some even say that they are persuaded that it is
the love of Christ that constrains me to visit them.
I had a satisfactory visit from a young priest, a Prince of Rome and Austria,
his name is Charles Odescalchi; his uncle is Nuncio in Spain.
I thought, on seeing this young man, that there was something lovely in him;
his mind was brought into great tenderness; I can but have good hope of him.
Three pious persons came in also to see me;
two of them are of the monks that I was with yesterday; one is a young man.
I had a full opportunity with them; I directed them to Christ, and to his Spirit.
The young monk was broken into tears.
In many of these opportunities I have to set before them in what true religion consists,
and that it is not by works of righteousness that we may perform that we can be saved,
but by faith only, in the free grace of God, through our Lord Jesus Christ,
who is the only Saviour of men.

2nd. I was occupied very late last night in preparing
the documents that Cardinal Consalvi wishes to have,
relative to my visits to their public establishments.
I apprehend it my duty to expose the various abuses that I have observed,
and in several instances, misapplication of money designed for acts of benevolence;
I represent also the sufferings of many of the prisoners in small, dark, crowded rooms,
and the heavy chains on them, which are not removed from some of them till after death;
I saw some greatly reduced by long illness, who, nevertheless, wore their heavy chains.
I met this day, at the Russian Ambassador`'s, some persons whom I visited in Russia;
we had a season of edification together;
I had another with the Prussian Consul who came to see me;
he and some others appear to enter into sympathy
with me in my religious movements in this city.
// lint-disable invalid-characters
This evening I had a letter from L`'Abbé Capacini,
enclosing a letter from the Cardinal for Miranda, the inquisitor;
the Cardinal also wishes to see me in the morning.

3rd. I went to the Quirinal this morning;
the Cardinal wished to make some arrangement for me to visit the Pope;
I had given him some hints of my apprehension that
I should not be acquitted in the Divine sight,
without attempting such a visit, if it could be granted.
The Cardinal wished to know if I would not be satisfied by being introduced to the Pope,
at Court.
I told him that I was no courtier, nor desired to visit such places,
but that my wish was to be with the Pope privately; yet I should be much pleased if he,
the Cardinal, would accompany me, and be the interpreter for me.
He, having told me that though the Pope understands French well,
yet he was unwilling to speak it in public, said that in his capacity of Prime Minister,
it would not do for him to go in with me,
as the other Cardinals might take offence at it.
Then I requested that, if the Pope admitted me,
he would endeavour to make choice of such a person to be present as he
could confide in to make a faithful report of what should then transpire.
This appeared the more necessary,
as the jealousy of several of the Cardinals against me is greatly excited.
I did not know what, under such circumstances, would befall me in the Inquisition;
but I committed myself to the Lord, and, accompanied by my interpreter,
we went to the convent of the Dominicans, to Father Miranda, who is a monk of the order,
and the chief inquisitor.
I gave him the letter of the Cardinal; he could not read it,
his eyes having been lately operated upon for cataracts;
he requested my young attendant to read it to him.
It was a request from the Cardinal to him,
to give me every information I might wish to have respecting the
manner in which the Inquisition was conducted in former years,
and is now managed, and likewise to show me every part of it.
Miranda said that he had not been able to go out
since the operation on his eyes had been performed,
but that he would send for the Secretary and keeper of the archives,
who was better able than himself to give me every information;
and thereupon a messenger was dispatched for him;
till he came I improved the opportunity to inquire
of Miranda how the Inquisition is now conducted;
when the Secretary came in, he had the letter of the Cardinal read aloud to him.
He was then told to give me every information, and to show me everything in it.
On our way I made the same inquiries of him that I had put to Miranda,
to which he gave similar answers.
The accounts given me by several persons in Rome of the Inquisition,
were very contradictory.
Some represented it as being in full force, only conducted with more secrecy;
but these stated that it had been totally abolished for some years;
that when any foreigners at Rome, or in Italy,
advance sentiments considered heretical or scandalous to their religion,
they come under the cognizance of the civil officers,
and are mostly banished from the country;
but that when such is the conduct of citizens of Rome, or subjects of the Pope,
they are sent to certain convents,
where their most severe punishment is to be kept in solitude on low diet,
whilst efforts are being made to reclaim them.
The Inquisition stands very near the church of St. Peter.
The entrance is into a spacious yard,
in which nothing is in view but extensive and sumptuous buildings,
containing their very large library, paintings, etc.
On the left hand is a door, hardly to be noticed, which opens, through a very thick wall,
into an open place, round which are buildings of three stories, with many cells;
the doors of all these open into passages fronting the yard.
These cells, or small prisons, are very strongly built; the walls are of great thickness,
all arched over.
Some were appropriated to men, others to women.
There was no possibility for any of the inmates to see or communicate with each other.
The prison where Molinos was confined, was particularly pointed out.
I visited also the prisons, or cellars underground,
and was in the place where the Inquisitors sat,
and where tortures were inflicted on the poor sufferer; but everything bore marks that,
for many years, these abodes of misery had not been at all frequented.
As we went on,
I heard the Secretary say something to my interpreter about the Secret Library.
I therefore asked him to take me there.
He took me to the large Public Library.
I told him this was not what I wished to see, but the Secret one; he hesitated,
stating that it was a secret place, where there could be no admittance;
that the priests themselves were not allowed to enter there.
I told him that the orders that had been read to him were to show me everything, that,
if he declined to shew me this,
I might also conclude that he kept other places concealed from me;
that therefore I could not contradict the reports I had heard, even in Rome,
that the Inquisition was secretly conducted with the ancient rigour.
On which he brought me into the Secret Library.
It is a spacious place, shelved round up to the ceiling, and contains books,
manuscripts and papers, condemned by the Inquisitors, after they have read them.
In the forepart of each book the objections to it are stated in general terms,
or a particular page, and even a line is referred to; dated and signed by the Inquisitor;
so that I could at once know the nature of the objection
to any book on which I laid my hands.
The greater number of manuscripts appear to have been written in Ireland.
Some of them contain very interesting matter, and evince that the writers were,
in many particulars, learned in the school of Christ.
I could have spent days in that place.
There are writings in all the various modern and ancient languages, European, Asiatic,
Arabic, Grecian, etc., all arranged separately, in order.
I carefully looked for Friends`' books, but found none:
there are many Bibles in the several languages;
whole editions of some thousand volumes of the writings of Molinos.
After spending a long time in this place of much interest, the Secretary said,
"`you must now come and see my own habitation.`"
I thought he meant the chamber that he occupies;
but he brought me to spacious apartments where the archives of the Inquisition are kept,
and where is the _Secretairerie_.
Here are the records of the Inquisition for many centuries, to the present time.
I looked in some of their books from the fifteenth century.
They are kept as the books of a merchant`'s journal and ledger,
so that looking in the ledger for any name,
and turning thence to the various entries in the journal, a full statement is found,
from the entrance of the poor sufferer into the Inquisition
to the time of his release or death,
and in what way it took place, by fire or other tortures, or by natural death.
The kind of tortures he underwent at each examination is described,
and also what confessions were extorted from him.
All these books are alphabetically arranged.
By examining those of late date to the present day,
I find that the statement given me by Father Miranda of
the manner in which the Inquisition is now conducted,
is entirely correct.
I could have spent days in this place also;
but the examination of some of the books of several centuries,
gave a pretty full view of the whole subject.
This is an examination that probably very few have made, or are allowed to make.
Here also I saw many of the bulls of the Popes,
relating to the conduct of the Inquisition.

4th. I spent my time in writing,
except that several piously minded persons and religious inquirers called upon me;
some appear awakened to see the emptiness of their
confidence in priests and outward observances;
"`What shall we do to be saved?`"
is their inquiry.

6th. I had an interesting and solemn meeting with several persons of the above description.
Accompanied by the Prince Charles Odescalchi,
I visited a large establishment placed under his charge;
it is a night retreat for every one who chooses to come in the evening;
no question is asked who the individual is, where he comes from,
nor if he was there before.
There are separate buildings for the accommodation of men and women;
in each place are spacious baths;
provision is also made for those who have cutaneous diseases to be fumigated.
They all repair to a place of worship,
where the Prince addresses them on subjects calculated
to impress sentiments of morality and virtue.
Those present, he says, are generally well known to be immoral and vicious characters;
preaching to them was not customary, till lately introduced by the Prince,
who appears to feel deeply for this poor and wretched class of the community.
They all come afterwards to the refectory, where supper is given them,
and beds are provided for all.
In the morning they have water to wash, and their breakfast before they disperse.
Many of them return again in the evening, especially when the weather is stormy,
or they have not been successful in begging to obtain sufficient to eat.
Sometimes this establishment has four thousand inmates during the night.
It was a well-meant institution, but the good intention has been much perverted;
yet the pious labours of the young Prince may prove a blessing to some.

6th. By appointment of the Cardinal Consalvi,
I went to the palace of the Quirinal this morning.
The antechamber and parlour were crowded with people and priests;
in the latter were several Bishops, among whom I remained a short time.
I kept my mind retired to the Lord; for in him alone is my help and my strength.
The Cardinal at last had me invited to his private cabinet.
I had a full opportunity with him, to the relief of my mind in various respects.
He told me that he had read my reports respecting the different institutions, prisons, etc.
I had visited, that the subjects I had noticed as needing help, relief to the afflicted,
etc., were put in a way to be speedily attended to.
He has shown the whole to the Pope,
and has had my observations on the various institutions copied separately,
so as to be sent to those who have the particular management of each,
and he hopes that thereby greater care may be had to the right
application of the funds that belong to the respective places.
I told him that I had lately heard that the Bishop
in Bavaria had hanged and burned the New Testament,
printed at Munich by Gossner, after the example of the Bishop of Naples,
and how greatly this militates against Christianity.
He said, that for his part,
he should not object to every individual having a
copy of the Scriptures in his own hands,
only he should wish that care might be rightly extended
to prevent the spurious translations from being circulated,
as has lately been done by the Socinians in Geneva and some other places;
the Bishop Tartini, of Florence,
has lately published a Bible which is sanctioned by the Pope,
which he should like to see widely spread.
He said also, that the Pope would be pleased to see me;
that owing to various engagements, he could not fix a time till now,
but that tomorrow evening he would admit me.

7th. I was today with the Governor Pacca, and several others.
He is well-disposed to relieve the prisoners from some of
the sufferings which I have represented to him.
This evening I went to the Quirinal as appointed yesterday by Consalvi.
// lint-disable invalid-characters
I expected to find L`'Abbé Capaciui in waiting for me, to take me to the Pope;
but no one was there who knew anything about my coming.
There is something in this I cannot understand,
unless it be that the priests and others are much displeased, as I hear,
at my having visited their holy things, as they call the Inquisition.

8th. Went early this morning to the palace of the Quirinal.
I was a short time only with Consalvi, who was much engaged.
He says, the Pope was disappointed last evening, for he expected me.
From Capacini, however, I find that monks, priests, and even Cardinals,
are some of them under great excitement and irritation,
highly offended at my having profaned their holy places,
by inspecting their secret things in the Inquisition;
and the countenance that Consalvi has given me since my coming to Home,
displeases them also.
Some of them, I believe, are particularly sore,
because I have exposed their misapplication of the money, intended,
in several institutions, for acts of benevolence,
and which they apply to their private use.
Here I am, as in the mouth of the dragon; the Lord may keep him chained down;
in patience and resignation I wait to see what he will do with me and for me.
I had hoped to be able to depart tomorrow for Florence,
and accordingly engaged and paid my passage by the Courrier, tomorrow noon,
but now a place of confinement may be my portion.
The Lord`'s will be done, so that in bonds or sufferings, even in death,
his name be glorified.

9th. This morning I had a message from Cardinal Consalvi to call upon him,
before he went up to the Pope, which is at seven a.m. I went accordingly.
He well knows the dissatisfaction of some of the Cardinals and others towards him,
but says it may do good eventually, that,
for his part he is fully disposed to serve me in what he can here; or after my departure,
whenever he can do it.
He further said, that it is very proper I should be with the Pope before I leave Rome,
and requested me to wait for his return from his apartment,
when he might tell me what time the Pope will receive me.
I had, whilst in waiting, an interesting time with Capacini, and other secretaries, etc.
Their inquiries led me particularly to speak of the influences of the Divine Spirit,
a gift freely dispensed of God, which man`'s wisdom,
learning or power cannot obtain for himself; much less can he dispense it to others;
by it only the deep things of God can be known; by it acceptable worship is performed;
qualification for the ministry of the Gospel is received; the Apostles were, by this,
rendered able ministers of the New Testament, not of the letter, but of the spirit.
This led me to state that the Popes, Cardinals, Bishops, etc.,
in their ordination of ministers or priests, cannot confer upon them spiritual gifts,
neither have they themselves any in virtue of their stations; but Christ Jesus,
the Head of the church, is the giver of spiritual gifts,
and with his Divine anointing he gives power; he alone can forgive sin;
he only is the Saviour of men.
They were all very serious whilst these and other
subjects of vital importance were treated upon;
that of the mass, confession, absolution, indulgences, etc., were also adverted to.
The Cardinal came down,
and said the Pope would see me at twelve o`'clock. He knew
that the Courrier by which I had taken my seat for Florence,
was to start at one o`'clock; but, said he, "`Take no thought about that;
the Courrier shall not go till you are ready;`" he also said that
Capacini would be here in time to wait on me up stairs,
and that he had provided one of his friends, approved by the Pope, who would,
if necessary, serve as interpreter,
and moreover be a witness to correct any misrepresentation
that envious spirits might attempt to make.
// lint-disable invalid-characters
I returned to the palace at the time designated; L`'Abbé Capacini was waiting for me;
we went up stairs, through several apartments, in which were the military body-guard;
for the Popes are, as kings of Rome, both earthly princes and heads of the church.
Thence we entered into the private apartments; the hangings about the windows,
coverings of the chairs, etc., were all of brown worsted, or silk of the same colour;
all very plain.
In a large parlour were several priests; among these,
the one provided by Consalvi to go in with me to the Pope.
One dressed like a Cardinal, but who is the Pope`'s valet de chambre,
opened the door of his cabinet, and said in Italian,
"`The Quaker has come;`" when the Pope said, "`Let him come in;`" on which the priest,
who was to act as interpreter, led me in, no one else being present;
as I was entering the door, some one behind me gently, but quickly, took off my hat,
and before I could look for it, the door was quietly closed upon us three.
The Pope is an old man; very thin, of a mild, serious countenance.
The whole of his apartment is very plain.
He was sitting before a table; his dress was a long robe of fine, white worsted,
and a small cap of the same (the Cardinals have it red);
he had a few papers and books before him; he rose from his seat when I came in,
but as he is but feeble, he soon sat down again.
He had read my reports to the Cardinal respecting many of the visits I had made in Rome,
to prisons, etc.; he entered feelingly on some of these subjects,
and intends to see that the treatment of prisoners
and of the poor boys in the house of correction,
and various other subjects that I have mentioned, should be attended to,
so that Christian tenderness and care be exercised; means, as he said,
more likely to succeed to promote reform among them than harsh treatment.
He reprobates the conduct of their missionaries in Greece;
also the burning of the Holy Scriptures by the priests and bishops in several places;
he acknowledges, like Consalvi,
that it militates much against the promotion of pure Christianity,
and is more likely further to darken the minds of the mass of the people,
than to enlighten them.
On the subject of the Inquisition, he said,
he was pleased I had seen for myself what great changes had been brought about in Rome,
in this respect; that it was a long time before he could have it effected;
that he has made many efforts to have similar alterations
introduced into Spain and Portugal;
had succeeded in part to have the Inquisition in those nations conducted with less rigour,
but was far from having yet obtained his wishes.
"`Men,`" he said, "`think that a Pope has plenitude of power in his hands,
but they are much mistaken; my hands are greatly tied in many things:`" he, however,
expressed his hope that the time was not far distant when
Inquisitions everywhere will be totally done away.
He assented to the sentiment,
that God alone has a right to control the conscience of man,
and that the weapons of a Christian should not be carnal but spiritual.
The fruits of the Spirit being described,
he said that to produce such and for the same end, should spiritual weapons be used.
I represented to him what I had beheld in many places in Europe, and the West Indies,
of the depravity and vices of many priests and monks,
what a reproach they are to Christianity,
and what corruption they are the means of spreading widely over the mass of the people.
I then stated what is the sacred office of a minister of the Lord Jesus Christ,
a priest of God; what the qualifications for that office should be,
and who alone can bestow them.
As I was speaking on these and other subjects connected therewith,
the Pope said several times, on looking at the priest present,
"`These things are true;`" and the priest`'s answer was, "`They are so.`"
Other subjects were treated upon, as, the kingdom of God,
the government of Christ in his Church, to whom alone the rule and dominion belong;
that he is the only door, the only Saviour,
and that those who attempt to enter in by any other door but him,
are accounted as thieves and robbers.
Finally, as I felt the love of Christ flowing in my heart towards him,
I particularly addressed him;
I alluded to the various sufferings he underwent from the hands of Napoleon;
the deliverance granted him from the Lord;
and queried whether his days were not lengthened out to enable him to glorify God,
and exalt the name of the Lord our Redeemer, Jesus Christ,
as the only Head of the church, the only Saviour, to whom alone every knee is to bow,
and every tongue is to confess; that such a confession from him, in his old age,
would do more towards the advancement of Christ`'s
kingdom and the promotion of his glory,
than the authority of all the Popes, his predecessors, was ever able to do; moreover,
that thereby his sun, now near setting, would go down with brightness,
and his portion in eternity would be with the sanctified ones,
in the joys of his salvation.
The Pope, whilst I thus addressed him, kept his head inclined and appeared tender;
then rising from his seat,
in a kind and respectful manner he expressed a desire that "`the Lord
would bless and protect me wherever I go;`" on which I left him.

On returning to the other apartment, my hat was given me,
and excuses were made for having taken it away, stating that,
as this is done when our Friends appear before the King in England,
they thought they could not do otherwise on the present occasion.
They also said: "`The Pope must have been much pleased with your visit,
for we have never known him to give one-half so much time to anybody in a private audience,
nor conversing with them as he has done with you.`"--My soul magnifies the Lord,
my strength and my help.
The work is His, and the glory also!
May He bless the work of his own hands!

The priest who was with me before the Pope, was very tender,
and has now taken leave of me in great affection.
Consalvi met me as I came down from the Pope`'s apartment.
He renewed the expression of his desire to serve me whenever he can;
and in christian love, we took a solemn farewell of one another.

I came to my inn to prepare for my journey;
it was a considerable time after the hour at which the _Courrier_ usually sets off;
but when I came to the post-house, I met one of the attendants of the Cardinal,
who told me that the Courrier had orders to wait for me; that, therefore,
I need not hurry myself.
I was, however, ready to go.

--

So Stephen Grellet concludes the account of his visit to Rome.
By the grace of God he was what he was.
He had been enabled to accomplish all that he believed to be required of him.
Without any direct attack upon the system and the exhibitions of Popery,
and ready as he had been to appreciate and cherish the good in all,
his repeated visits at the Quirinal and other public places had, nevertheless,
attracted the jealous attention of the less liberal Cardinals and inferior officials.
A much longer tarriance near the Vatican might have called
forth the spirit of opposition if not of persecution,
and been the means of interrupting his progress.
As it was,--the singleness and purity of his purpose,
the disinterested devotedness and the Christian integrity
in the discharge of apprehended duty,
which had marked his course,
and his faithfulness and zeal in simply pleading the cause of Christ,
had made a deep impression upon many.
The practical illustration of the spirituality and freedom of the Gospel
dispensation and the simple character and polity of unadulterated Christianity,
which his example and his teaching had held forth,
could not be lost;--beautifully reflected, as it had been,
upon the dark cloud which scarcely concealed the
"`mystery of iniquity`" with which he was surrounded,
it could not escape the observation of the more serious and considerate.
The poorest of the poor, and the wretched criminal in his miserable cell,
had felt its force; princes and nobles, priests,
and ecclesiastical dignitaries of the highest order, had recognized its influence.
He had "`done what he could,`" and, with a thankful heart,
he was now permitted peacefully to retire to other scenes of labour.^
footnote:[More than twenty years afterwards Stephen
Grellet received a letter from his friend,
B+++.+++ B. Wiffen, near Woburn, Bedfordshire, mentioning an interview he and his companion,
G+++.+++ W. Alexander, had had at Lisbon, in 1842, with Capacini,
then the Papal Nuncio to Portugal.
Alluding to the conversation which passed with the Nuncio,
B+++.+++ B. W. writes to Stephen Grellet,
"`Finding that we were members of the Society of Friends,
he made earnest inquiry respecting thee, whom, he said,
he had known at Rome some years ago,
and charged me to convey to thee the sentiment of his affectionate remembrance and esteem.`"]
