== Chapter XXXIX.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Florence
* Leghorn
* Venice
* Verona, etc.

Travelling day and night he reached Florence early
in the morning of the eleventh of Twelfth month,
1819, and resumes his journal.

[.embedded-content-document]
--

After the conflicts of mind, and bodily fatigue I had in Rome,
travelling alone in the open air was refreshing to me every way;
besides the grateful sense that I have been enabled by my good Master,
to throw off a great load of religious concern, which I had borne for years.
Marvellous indeed, are the ways of the Lord,
in making it possible for me to do so--first through General Maitland;
then by so inclining the heart of Consalvi and others towards me;
and also in delivering me from the hands of those envious and persecuting men at Rome.
Surely, it is the Lord`'s doing!
All praise and glory belong to Him.

After breakfast I went to the Prime Minister of the Grand Duke of Tuscany,
Count Fesson Brodrion, for whom I had a letter from the Prince Cardito at Naples.
I find him, as described to me by the Prince,
a man possessed of kind and benevolent feelings, enriched by piety.
He encourages me to visit some of their public institutions and prisons,
to all of which he gives me free access.
The Chevalier Coassini, under whose special charge many of these are, was present,
and the Count desired him to give me every aid I may need in those visits,
should I undertake them.
In the afternoon I called on several persona of whom I had heard as being serious characters.
I find some of them are such.
I also went to see a family in affliction, by illness,
and was enabled to mingle with them in their tribulated state,
and to draw their attention to Him who is the sure refuge in time of trouble.

12th. Feeling during the course of last night,
fresh concern and exercise for the poor sufferers in prisons and poorhouses,
I apprehended it was the line of my religious duty
to mingle here also in near sympathy with them,
at least by visiting some of them.
As a man, I recoil from visits of this sort; they are so trying to my nature,
and in such places I have endured great suffering;
but my proper business is simply to follow my dear Lord,
as by his good Spirit he directs my steps.

--

[.offset]
A few days after he adds:--

[.embedded-content-document]
--

I have been at two hospitals, the asylum for the insane,
the foundlings`' orphan`'s house, a large poorhouse, and some schools,
having religious opportunities in most of these places.
In several of them,
I was with the nuns who devote themselves to minister to the sick and the afflicted.
Among these I meet here also persons of conscientious and pious minds.
In the poorhouse I was enlarged in directing the inmates to Christ, and to his Spirit.
Some of them appeared to have hearts to feel the value of pure religion,
and to have tasted of its consolations.
The prisons here are very different from those in Naples and Rome.
The prisoners are treated with much greater humanity.
They do not show themselves so hardened in crime.
In the meetings I have had with them, brokenness of heart prevailed in many,
and but few juvenile offenders are to be seen.
The President of Police tells me that, during the five years that he has been in office,
in a population of one million and three hundred thousand persons,
only five have been put to death; that is, one person a year.
Crimes have considerably lessened throughout Tuscany:
murder is seldom heard of in these parts.

The Prince Carrine has been several times with me.
We have visited several families piously disposed,
and I had a meeting with some of these collected for the purpose of worship.
I have also distributed some religious books, in French and Italian.

--

[.offset]
Suspending his labours in Florence for a few days, he passed over to Leghorn.

[.embedded-content-document]
--

Leghorn, 16th. Travelling during the night, I came here in fourteen hours.
I wished to visit this place previous to my departure from Tuscany,
and through the President of Police at Florence, a door was set open for me here.
I felt it my place to visit their prisons, etc.

I was much tried, among the Gallerians,
in beholding the heavy chains they are loaded with, when at work,
and during the night also.
They all lie on an inclined plane, and a heavy chain passes from one end to the other,
through strong staples and the rings they have on their feet,
so that they must lie nearly on their backs the whole night.
Many of them appear to have very hardened minds, but in a few I found tenderness.
I think some of these show that, if they could, they would, like the prodigal,
return to the parental house.
In the evening I was with twelve families of the principal inhabitants of this city.
They had felt great concern for their children, that they might receive a liberal,
but virtuous and guarded education, especially their daughters;
but they could not see how this could be rightly
obtained by sending them to boarding or other schools,
nor even by introducing teachers into their families;
they therefore concluded to unite themselves into a society for that purpose,
and to attend themselves to the education of their children.
Every member of this little society has a family of children,
and must be able to teach some branches.
They take turns, week by week, in the laborious part of the work.
They began this school two years since.
They have found the employment so delightful, that during that period,
whether on active service or not, none miss regularly to attend with their children.
They say that every desire for visiting or pleasure, as it is called, is taken away;
their greatest delight is to be together with the children.
At first they met alternately, at one another`'s houses; but of late,
they find it most convenient not to change about.
During the fore-part of the day, they attend to their respective avocations.
In the afternoon the young people repair to the house,
the boys in separate apartments under the tuition of the fathers,
and the girls in others, with the mothers.
In the evening they all meet in one room,
where more general instruction is imparted to them; and whilst they were thus engaged,
I was much pleased to see how they introduced excellent precepts of a moral, virtuous,
and religious nature,
calculated to turn the attention of the children from outward objects to spiritual considerations,
and to that salvation which comes by the Lord Jesus Christ.
To these great objects their various branches of learning are designed to lead.
They answer to one another like the lowest link in a chain to the uppermost; for example:
under the drawing of a flower, an insect, an animal, or shell, etc., etc.,
the pupil writes at length, the appropriate class, nature, use, etc., and finally,
his own reflections on the love, the wisdom, and power of the Almighty Creator of all;
thus drawing, writing, and other objects are combined together.
I felt great interest in these young people, and not less in their parents, who,
whilst instructing others, are evidently learning themselves in Christ`'s school.
I had a precious religious opportunity with them all.

17th. In my visit to the hospitals today,
I found that for the females attended by eighteen nuns,
and that for the men by fourteen monks,
who respectively devote themselves to this act of benevolence towards the sick.
I had some satisfactory religious intercourse with them, and with many of the sick;
among these I found a young American, from Boston;
he went to a ball with shoes too tight,
in consequence of which he has had his leg amputated; he bitterly laments his folly,
and appears serious and tender; he pays, as he says,
very dearly for his pleasure in dancing.

I had this evening a relieving religious time with about twenty five persons,
some of whom are merchants; the Governor was also present; one of the merchants,
a pious and benevolent individual, has a school for poor children,
supported at his own expense, which I visited to some satisfaction;
peculiar attention is given to moral instruction.

--

[.offset]
On his return from Leghorn he continues his notes on Florence:

[.embedded-content-document]
--

19th. On my way back to Florence I stopped at Pisa,
where I met but little to claim my attention.
I was today with the Marquis of Pucci, the Counts Tartini and Puccini;
the former is President of the Government;
he paid great attention to my statement of the condition
of the prisoners in several prisons,
and manifested great interest in my plea on behalf
of those who appeared to be in a penitent state;
he assured me that this very day measures should
be taken for the relief of the poor sufferers.

To my comfort I find, this evening, that prompt attention is paid to it,
not only in this place,
but that orders to the same effect are sent to Leghorn and other parts of this Government,
and that both here and elsewhere measures are taken for a better provision for the poor,
who are much neglected in some places.
I am richly paid, indeed, for my sufferings in my visits to afflicted humanity,
by being able to obtain some relief for the destitute, and I hope also,
the liberation of some of the penitent ones.

21st. These two days I have had several religious
opportunities in families of pious persons;
in one instance, a number of them congregated together for the purpose;
it was a season when their spiritual strength was renewed,
and their faith in the Lord Jesus Christ was confirmed.
The Counts Bardi, Tartini, and Puccini,
are much concerned for the education of the children of the poor,
and they have established schools for them, which I visited.
I have encouraged them to extend to the young people a virtuous and religious education,
founded on the pure principles of Christianity.
I have given them the "`Scripture Lessons`" prepared in Russia,
which they propose to introduce into those schools,
and they have accordingly put them in train to be printed in Italian.
I have also had an interesting visit from Doctor Betti and some of his friends;
some of them were with me before I went to Leghorn,
to whom I gave some tracts treating on our Christian principles.
They tell me now that several of their friends have joined them in the perusal of these,
and felt so much interested that they have already translated some of them into Italian,
to have them printed.

Tuscany is among the finest countries I have seen; the soil is fertile,
and in a high state of cultivation; their villages and the inhabitants are cleanly,
and great industry is apparent.
Among other occupations,
that of plaiting for their fine Leghorn bonnets is carried on to a considerable extent,
but what is far more pleasant still,
is that the morals of the people generally far exceed what
are lamentably to be found in other parts of Italy.

--

Having concluded his services in the Tuscan capital,
he proceeded by way of Bologna and Ferrara to Venice.

[.embedded-content-document]
--

22nd. Bologna.
I travelled last night by the Courrier,
and was favoured to arrive here safely this morning,--safely I say,
for this road over the Apennines has of late been greatly annoyed by highway robbers;
a few hours before I passed it a company of ten of them attacked and plundered two carriages;
they tore the ears of some of the females to obtain their ear-rings,
and one had her finger nearly cut off to procure her ring.
Here I am again on the Pope`'s territory.
It does not appear that any service is required of me; yet, for a while,
it seemed as if I might be brought into trouble; they narrowly examined my baggage,
and took hold of my few remaining books,
which they carried to the police office to inspect them more closely;
they threatened to send them to Rome; I told them that I had come from there; and,
after many questions, they were restored to me, by order of the Governor,
whom I went to see.

Venice,
25th. I came to Ferrara on the 23rd. There also my
mind was closed up as to any religious service.
I left it next morning for this place.
I accomplished the journey by water, in one of their canal boats;
it was an unpleasant one; there was a rude company on board.

Soon after my arrival here this morning, I was in company with the Chevalier Naranzi,
who is the Russian Consul; he is a feeling and pious man,
and through him I am brought to an acquaintance with several others of a similar character.
I am told that by German papers, printed at Augsburg,
they have here the information of the nature of many of my religious engagements at Rome,
and of my visit to the Inquisition and to the Pope;
allusion is made to some of the religious principles I maintain
as a member of the religious Society of Friends,
and a minister of the Gospel among them; in this capacity, the papers state,
I now travel in these nations.

26th. I had hoped that I might not be long detained in this ancient city,
but a field for religious service opens before me,
and I dare not flinch from whatever He, in whose service I am, sees meet to require.
I felt a strong attraction towards the prisons, etc.,
but did not know how to get admittance to them.
Whilst I was with Naranzi, a Venetian nobleman, Prefect of one of the departments,
in a respectful manner made various inquiries into our Christian principles,
such as salvation by the Lord Jesus Christ, Divine worship, etc.,
when Baron Mulazzani came in,
and manifested great interest in the important subjects we were treating of,
and also in the nature of many of my engagements in several places, in visiting prisons,
poorhouses, etc.
He was formerly the Minister of Police in this place.
When he came into office, about twenty years since, Venice was in a deplorable state;
murders and many robberies were committed every night,
multitudes of beggars crowded the streets,
and Mulazzani had authority given him to correct these evils;
he took a general survey and formed his plans;
and began by providing several places to be used as temporary prisons; others,
in which he had a variety of raw material stored,
to give employment to such as were destitute of it.
Then during one night, he had every suspected character in Venice arrested,
and shut up in prison; he forbad every kind of begging under heavy penalties,
and published a notice that every one out of employment might obtain work,
for which he should be remunerated.
Ample provisions also was made for the aged, the infirm, and the sick.
All who had been arrested were speedily and strictly examined;
those who were found to be vicious characters,
were kept in prison for further examination.
The consequence was that robberies are now very seldom heard of; no beggars are seen and,
except in a few solitary cases, no murders have been committed.
For a while the workhouses were full; many of the people also took their work home,
and were paid at a price a little below what they might obtain by ordinary employment,
to induce them to seek for it;
the result is that very few labourers are now to be found in the workhouses,
except such as, being feeble or infirm,
could not obtain a sufficiency by labour elsewhere.
Mulazzani kindly offered to accompany me to such of their prisons, etc.,
as I might wish to visit; he is also an excellent interpreter.
The first place I wont to was the palace, where the Doges formerly had their residence.
It is in a very poor condition; the prisoners are crowded, and have heavy irons;
yet they might be said to be in a comfortable state
compared to what they were in twenty years ago,
or less.
I was with the Count Gardanis, President of the Criminal Tribunal,
who appears to be a man of sensibility,
and I hope he will succeed in ameliorating the present condition of these poor prisoners.

In the evening I met at the Countess Albrissizzinveli`'s many noble persons.
We had a religious opportunity.
They all speak French, therefore I needed no interpreter.
Christ was proclaimed to them,
and we were reminded that except a man takes up his cross daily, and follows him,
he is not worthy of him,--he cannot enter into life;
and the nature of the cross which the Christian is to bear was set forth.
The Countess takes great interest in the principles of Friends.
I have given her some books on the subject.

29th. Yesterday and today I visited their hospitals, a retreat for old people,
and their house of industry.
These are under good regulations.
I had several opportunities among them, and religious sensibility was apparent with some,
especially among the aged people.
I was also at the foundling hospital, the large schools for boys,
and the house of correction.
To these places the Chevalier Naranzi accompanied me, as my interpreter.
I had also at my lodgings, several pious persons.
Among these was a Popish priest, who is in a tender state of mind.
The language of many after the religious opportunities I have with them, is in substance,
"`Thou almost persuadest me to be a Christian,`" but the cross stands in the way,
and they turn away sorrowful.
My soul loves them, and truly mourns over them.

30th. It appears that I do not escape here, any more than in Rome,
the jealousy of some who are disposed to do me mischief, if they could.
They have, as I am told, written to Vienna,
to give the Emperor their own representation of me.
I tread indeed among scorpions, but the Lord can deliver me out of all evil.
I see no better way for me than to go straight forward in the path
and line of service into which my blessed Lord directs me;
the consequences I resign entirely to Him, as I have done also my life and my all.
I visited a hospital, and the asylum for the insane;
both these are under the care of the monks called
"`__Buoni Fratelli;__`" they take care also of such,
as, by accident or otherwise, are wounded or hurt in the street.
I had a precious time with these monks,
who are devoted to acts of benevolence and charity.

--

In the afternoon "`a solemn parting meeting with many of the pious or
serious persons of the city,`" closed his religious labours in Venice,
and he left the same evening for Verona.
He continues:--

[.embedded-content-document]
--

Verona, First month, 1st, 1820.
I came here in two nights and one day.
My way is hedged up; I neither find,
nor do I hear of any with whom I can mingle in religious fellowship.
I have spent the day in retirement before the Lord;
my mind is prostrated very reverently at his footstool;
he has done great things for his poor servant.
He gives me also truly to feel, that it is not by works that we have done,
not even of righteousness, but of his mercy only, that we can hope for salvation,
accompanied with the conviction of my unworthiness, even of the least of his mercies;
great poverty of spirit is my clothing.
The bread of yesterday, which the Lord did bless, cannot now supply my soul`'s wants,
unless my gracious Lord condescends to minister to me afresh out of his bounty;
nor can the grateful remembrance of the saving help and strength,
time after time granted to me under many past trials and baptisms,
give strength and confidence, now that I journey from one nation to another people.
Unless the Lord`'s hand be stretched forth to uphold me, I must sink under the trials,
that I am sensible await me, during the succeeding days of my probationary life; yet,
with deep reverence I can say, "`I know Him in whom I have believed;`"--though weakness,
yea, nothingness belongs to me, "`in the Lord Jehovah there is everlasting strength.`"

--

From Verona he proceeded by way of Ala, Trent, Brixen, Insspruck, etc.,
through the Tyrolese Alps, to Munich in Bavaria.
On the whole of this journey,
he did not feel it to be his religious duty to make
any stay in the places through which he passed.
He "`felt deeply`" for the inhabitants,
but "`prayer seemed to be the only service required.`"
The Tyrol much interested him; "`I doubt not,`" he remarks,
"`that among these high mountains, and deep valleys, the Lord has a seed,
precious in his sight, which he waters by his own Spirit.`"
