== Chapter XLIII.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Concluding Services in England and Ireland

After an absence of a little more than a year and a half,
Stephen Grellet found himself once more among his English Friends.
Before leaving the place of his landing on British ground, he continues his memoranda.--

[.embedded-content-document]
--

Dover, 23rd. This day I have been refreshed in my spirit,
by mingling with several dear friends, and in visiting a school for poor children.

London, 24th. I left Dover last evening, and arrived early in this great city.
I came first to my long beloved and valuable friends, Thomas and Rebecca Christy.
I found them in the midst of many engagements;
several buildings close to their house and store were consumed by fire last night.
They very narrowly escaped being heavy sufferers themselves.
Many friends soon came in to see me.
It was very instructive to notice that though much
noise and confusion prevailed in the street,
where the goods of the poor sufferers by the fire were heaped np together,
and a great crowd of people was collected,
yet our little company in the house was gathered in great quietness.
A solemn silence was proclaimed by the Lord.
My beloved friend, William Allen was with us,
clothed with that meekness of spirit and peacefulness,
which bespeak that he has returned home from his long journey with me,
with sheaves in his arms.
We had a solemn meeting together.
Our spirits were contrited under the living sense of the
love and mercy of God through Jesus Christ our blessed Redeemer,
to whom be everlasting glory and praise.
Soon after this I went to the house of dear Allen.
His only child and beloved daughter reaps richly her reward,
for having so freely offered up to the Lord`'s service her dear father.
How precious is the unity and fellowship that I am
favoured to partake of with these beloved friends!

25th. Visited some dear friends at Stoke Newington, Stamford-hill, and Tottenham.
The Lord very graciously refreshed us together.

26th. First-day.
I attended Gracechurch Street meeting in the morning,
and Devonshire House in the afternoon.
They were solemn meetings.
Many of us, by one Spirit were baptized together into one body,
and were all made to drink into one spirit.

29th. The Quarterly meeting for Ministers and Elders was held yesterday.
It was a uniting season.
"`Eye hath not seen, nor ear heard, neither have entered into the heart of man,
the things which God hath prepared for them that love him,
but God hath revealed them unto us by his Spirit, for the Spirit searcheth all things,
yea, the deep things of God.`"
The Quarterly meeting for business had two long sittings yesterday, and another today.
A lively exercise prevailed among Friends during
the consideration of the answers to the queries;
but some subjects came before that meeting which brought very deep feeling,
and suffering, also, on some of us.

31st. I attended a meeting at Islington school.
Many of the dear children were very tender.
In company with dear Allen, I visited the Ambassadors of Russia, Sweden, Bavaria,
and Wirtemberg.
These visits have given us much peace.
Their hearts were prepared to receive us, and our testimony to the Truth.

First-day, Fourth month, 2nd. Dear Allen and I were at Southwark, and had a good meeting.
At Gracechurch Street in the afternoon,
I was favoured silently to sit at my Master`'s feet,
and to receive instruction immediately by the Spirit that speaks to the heart.
In the evening I joined my beloved friend, Mary Dudley,
in having a meeting at Westminster for the nobility who reside at the west end of London;
it was a quiet, good meeting.

6th. These days past I have attended the Monthly Meetings of Devonshire House,
Gracechurch Street, and Tottenham, in all which,
Friends proceeded in their business with weight;
brotherly love and harmony appeared to prevail among them in a very precious manner.
"`How good and how pleasant it is for brethren to dwell together in unity;
it is like precious ointment, etc.; there the Lord commands the blessing,
even life forevermore.`"
I went to Plashet, to see my dear friends, Elizabeth J. Fry and her sister-in-law;
both have been ill, but are now recovering.
The Lord gave us sweet access together to his presence, where there is life.

7th. To day the Meeting for Sufferings was held;
they had business before them of great weight; Friends felt it,
and a watchful care prevailed to seek for Divine wisdom and ability.
O that Friends everywhere, in all their meetings,
were thus engaged to look up to Him who alone can
direct rightly by his Spirit of wisdom and counsel!

Having felt my mind drawn in Gospel love to attend the ensuing Yearly Meeting in Ireland,
and to have meetings at some places on my way there,
accompanied by Luke Howard and Robert Forster, I came to Bristol,
where I continued a week.
During that time I visited many families among the sick and afflicted;
one of these visits was to a young woman, a Moravian, a great sufferer,
but whose mind appears to be very sweetly stayed on the Lord,
and in the patience of Christ.
She has now been about eighteen years laid on her back,
unable to speak or lift up her hands to her mouth;
but not a feature of her countenance indicates murmuring,
though her sufferings are often great.
The religious opportunity I had with her, was a contriting season;
I saw there fulfilled the Prophet`'s testimony,
"`Thou wilt keep him in perfect peace whose mind is stayed on thee,
because he trusteth in thee.`"

I had also several meetings among Friends and others;
one was in the Moravian establishment.
The female, who is at the head of the sisters,
gave me such a welcome as I could not at first understand,
not recollecting to have seen her before,
but I found she had been at the head of the Moravian establishment
in Dublin when I visited it some time since.
In the course of my religious communication there I particularly addressed a young woman,
warning her against yielding to the strong temptation which was assailing her;
for if she did, anguish and misery would be the result;
but if she sought to the Lord for help to resist it, he would be her saving strength,
and would greatly bless her succeeding days.
I knew nothing concerning the young woman,
but I could not help thinking my address to her a singular one Now,
I am informed that a young nobleman had found means of obtaining access to her,
and under fair pretences of strong affection and promise to marry her,
he had nearly persuaded her to elope with him.
This had come to the knowledge of my informant a very short time before I was there.
As soon as I went away the young woman came to her,
bitterly reproaching her for telling me the circumstances,
but she satisfied her fully that she had not been with me,
except in the presence of them all, and that nobody could have told me about it,
since no other person was in the secret;
she must therefore consider it as a particular interposition
of the Lord to induce her to flee from temptation,
and escape the ruin that threatened her.
The young woman resolved, by the Lord`'s help, to do so; she was enabled to resist,
and soon after heard that he who made such fair promises to her was a profligate person.

I met in Bristol with my beloved friend, William Forster,
who had come there to embark for the United States, on a religious visit.
The prospect of such a voyage was trying indeed, under his bodily sufferings;
a cow had run upon him and wounded him severely with her horns, on his knee,
so that he cannot stand.
He hopes to recover during the passage.
I felt very tenderly for him and his beloved wife,
at parting from one another under such circumstances.
They both were greatly supported, leaning on the Lord`'s arm,
resigned to his Divine will, to be separated for the service of the Gospel.
The same day that he embarked, I left Bristol for Birmingham,
where I had two large meetings.
The following day, my beloved friends, William Allen and his daughter, met me,
and we proceeded together to Coalbrookdale,
where their Half Year`'s Meeting for the Principality of Wales was held.
It was pleasant to meet there several Friends who had come from various parts of England,
to attend it.
A deep and living exercise was prevalent, for the prosperity of the cause of Truth.
I felt much for the youth of that Principality,
as well as for a large number who attended from neighbouring Quarterly Meetings.
I appointed a meeting for them, at which dear William Allen had very good service.
My own mind also obtained relief.
The Lord`'s power rose into dominion.
I had been under great exercise before that meeting,
and my spirit is bowed again very reverently in gratitude
for His continued help and mercy.

We proceeded thence to Holyhead.
By the steam-packet,
we had a passage over the channel to Ireland of only six and a half hours;
the surface of the sea was as smooth as glass,
totally different from what it was when I crossed it before.
So is my passage through life; I travel over very rough paths,
but now and then my blessed Master leads me in ways of pleasantness,
where all his paths are peace.
Blessed and adored be his name!

--

On a review of this visit, and the attendance of the Yearly meeting in Dublin,
he makes the following remarks.--

[.embedded-content-document]
--

In the space of six years great changes have taken place among Friends here.
This life is indeed very chequered, and full of vicissitude.
Some, who were in affluence, sailing with the tide of prosperity,
are now greatly reduced in their circumstances.
Others, who stood high and flourishing in the world,
have their mortal remains now mouldering in the silent grave,
and their heirs squander away the large estates that they
had spent many years of assiduous labour in collecting together.
Others, much beloved by me,
have now joined the church triumphant in the heavenly places in Christ Jesus.
I visited with much interest and deep feeling, the bereaved survivors of some of these,
who, sensibly feeling that, by their loss, they have contracted heavenly ties,
sorrow not as those that are without hope, but their desire is,
that through the Redeemer`'s love and mercy, they may be allowed also, in his time,
to keep the feast of ingathering in his holy presence.
Jonas Stott, the dear friend at whose hospitable house I made my home, heretofore,
is one of those now removed from time to eternity.
My dear William Allen, his daughter and myself,
are kindly entertained at Jonathan Pim`'s. We came
to Dublin a week before the Yearly Meeting,
during which we had meetings in the prisons, and in some poorhouses,
and visited also some of the sick and afflicted.
The Yearly Meeting was a time of deep exercise to us.
There is yet much cause for this,
for the deadly wounds inflicted by the cruel adversary are not fully healed;
nevertheless,
there is great occasion also for gratitude to the Author of all our mercies.
The prospect among the dear young people is much brighter.
Many of them, who were before estranged from the Truth,
evince now that they are under the baptizing power of it,
and that the yoke of Christ is upon them.
Dear Allen joined me in some public meetings I had in that city.
Many of the Roman Catholics came to one of these.
Our services were very harmonious, being together of one mind, of one accord,
baptized by the one Spirit, for the one work of the dear Master.

--

Returning to England, he attended the Yearly Meeting in London.
On the eve of retiring from the field of his European labours,
it was a time of peculiar interest, both to himself and his friends,
and in reference to it, he makes the following record.--

[.embedded-content-document]
--

We left Ireland in much peace; had at Worcester a solemn meeting with Friends,
and another with the inhabitants.
Then came pretty directly to London, to be at the Yearly Meeting.
It was attended by a large and valuable body of Friends.
The Lord`'s baptizing power was repeatedly felt over us during the several sittings of it.
Also in the women`'s meeting, which I visited, and in the several meetings for worship.
Yet my soul was sometimes brought very low under the weight of deep exercises.

Having now in prospect soon to be liberated from the extensive
field of Gospel labours in these European nations,
in which I have been diligently engaged for nearly two years,
I spread before my friends of the Meeting for Ministers and Elders,
my prospect of soon returning to America;
they gave me their testimonials of Christian unity,
with my various labours and deep exercises whilst among them,
and on the European continent.
Our parting from one another at the close of the Yearly Meeting,
was under strong and warm feelings of Christian love and fellowship.
There are many there whom I love and venerate as
fathers and mothers in the Church of Christ;
others are very dear to me as brethren and sisters in the Lord;
and for the dear youth and precious lambs of His fold,
I feel as if my very life was bound up in theirs.
With dear Allen, the separation has been in the fulness of the love of the Gospel.

--

He now went down, on a farewell visit to his friends in the North of England,
on his way to Liverpool, to embark for America.

[.embedded-content-document]
--

Accompanied by George Stacey, junior, I left London for Leeds the 9th of Sixth month.
After having a meeting there, we came on to Undercliffe,
of which my valued and much beloved friend, Sarah Hustler, is no longer an inhabitant;
the Lord has provided a better mansion for her in his kingdom.
Her dear brother and wife, John and Mary Hustler, now occupy this spot,
which has for so many years been a place of refreshment, every way,
to the Lord`'s servants on Gospel mission in these parts.
I had two meetings at Bradford that were crowned by the Divine presence.
I was permitted also to enjoy sweet communion of
spirit with many of the dear departed ones,
who have entered into the joy of their Lord.
Such a communion with those dislodged from their mortal tabernacle,
furnishes me with a very strong argument in favour of the reality of the soul`'s immortality.

Lancaster.
15th. John Hustler kindly accompanied G. Stacey and myself to this place,
by way of Settle.
On the road my mind was engaged in retracing my steps
and exercises among the nations I have lately visited;
the sore troubles that have attended me,
the peculiarity of my religious engagements among the rich and the poor,
military and clerical characters, in palaces and prisons,
and how my blessed Lord and Master has been with me, his very poor servant,
to uphold and help.
I was greatly contrited before Him; truly did I say,
"`Great and marvellous are thy works, Lord God Almighty; just and true are thy ways,
thou King of saints; who would not fear thee?
who would not glorify thy name?`"
Should my life be prolonged to that of the antediluvians,
the period thus lengthened would be too short to proclaim
the whole of the praise and the glory of my dear Redeemer.
Amidst these feelings, however,
I remember the Lord`'s disciples who were telling him what
great things they had been enabled to do through his name.
He forewarned them of the sore trials that were impending on them:
"`But now I say unto you, let him that hath no sword,
sell his garment and buy one,`" etc.
So a sense is given me of the sore tribulations that await me, on my return to America.
If my dear Lord and Master is rejected and traduced, I, who am but a very poor servant,
if I keep my allegiance to Him,
must not expect to escape my share of the afflictions of the Gospel.
My prayer is that the Lord would clothe me with his holy armour of Light,
strengthen my faith in him, and preserve me in patient suffering with and for him,
even though all should forsake him.

We stayed one night at Settle, at my valuable friend`'s, Mary Birkbeck;
I was pleased at being once more with her brother Joseph,
now in an advanced stage of life;
some years past he was a kind companion to me through some counties in this nation;
he is in a humble, childlike state.
I attended their Quarterly Meeting at Lancaster; several beloved friends from a distance,
who met at the Yearly Meeting, were in attendance,
whom it was very pleasant to be with again.
The Quarterly Meeting was preceded by their Select, and Preparative,
and Monthly Meetings; in all these,
the Lord was pleased to enable me to proclaim the Gospel
message in a manner suitable to their conditions.
There were the poor and needy, seeking and afflicted ones; also the rich and the full,
among whom I had close services, but the love of Him who has come to seek and to save,
was felt to be over all.
At this Quarterly Meeting my long beloved, valuable and aged friend, Charles Parker,
spread his concern to visit, in the love of Christ,
the western counties of this nation and Ireland;
the meeting felt very tenderly for him in his infirm state of health,
but great unity was expressed with him,
and liberty given to pursue the service to which his Great Master calls him.
It may be the last offering of the kind he may be required to lay on the Lord`'s altar.

From that Quarterly Meeting, accompanied by Sarah Benson, I came to Yealand,
to Charles Parker`'s; had a meeting there; visited several families in affliction,
and then went to Kendal.
I had two meetings there; and went thence to Manchester, to David and Abigail Dockray`'s;
she is a daughter of Sarah Benson`'s,
and has been many years under the Lord`'s forming hand,
to prepare her to receive the Divine unction for the ministry of his glorious Gospel,
in which work she has now come forth in much humility and watchfulness;
she evinces great care closely to keep near the guidance of the Lord`'s Spirit.
Here I visited with comfort and instruction that valuable handmaid of the Lord,
Mary Robinson, now in her eightieth year, bearing fruit to his praise.
I attended their meeting, wherein I had deep wadings of soul and very close service;
mourning and lamentation were my clothing; there are, nevertheless, among our Society,
in that town, some valuable Friends and hopeful young people also.

On our way to Liverpool we passed through Warrington,
stopping a while at those two very valuable aged friends`', John and Elizabeth Bludwick;
they forcibly remind me of the character given of
that noble pair who walked blamelessly before God;
such appear to be the lives of these dear friends;
my spirit was refreshed in their company,
and encouraged by beholding in them the efficacy of the Lord`'s grace,
according to the promise to Paul, "`My grace is sufficient for thee.`"
I came the same evening to Liverpool,
where I am again received with open hearts by my very hospitable friends,
Isaac and Hannah Hadwen,
who have so often ministered to me in their house of rest to the poor weary pilgrim.

First-day, 26th. I was largely engaged today, in two crowded meetings,
in proclaiming the greatness of the love of God towards poor, fallen and sinful man:
"`God so loved the world that he gave his only begotten Son,
that whosoever believeth in him should not perish, but have everlasting life;
for God sent not his Son into the world to condemn the world, but that the world,
through him, might be saved.`"
These are subjects that could engross the mind with
awful reverence and prostration for ages.
The angels themselves desire to look into these things.
They were solemn, good meetings.

27th. Went to see a ship bound for New York, the James Monroe, Captain Rogers;
the same who commanded the vessel in which I went to the island of Hayti.
I sat down quietly in the cabin,
my mind turned to the Lord that he would direct me in the right way,
and show me if this is indeed now the time for me to return to America,
and if his presence will go with me in that ship.
I felt sweet peace there; it seemed to me like a little sanctuary, and now,
on the eve of my return home,
the gracious promise made at the time of my departure from America was sweetly revived,
"`Verily my presence shall go with thee, and I will give thee rest.`"
Good is the word of the Lord, says my soul, worshipping before him;
I have engaged my passage on that vessel.

29th. I was at meeting this day, which was a solemn parting season with my friends;
the Lord broke bread for our souls`' nourishment, and blessed it.

30th. Several friends from London and other places have
kindly come to bid me once more farewell before I embark;
among these are Luke Howard, G. Stacey, etc.
I am pleased that my dear William Allen could not come;
for these repeated partings are hard to bear.
I had this afternoon a most solemn season with a
considerable number of friends that came to see me;
it was an awful solemnity; I saw evidently,
and felt how the powers of darkness are combining
together in the world to try to obtain the mastery;
to crush and to destroy that which is good,
so that though now the outward sword between nation and nation is sheathed,
yet the prince of darkness, that ruleth among the children of disobedience,
seems to have great power.
My soul felt deeply, and,
like the prophet when he saw what distress Hazael would bring upon Israel,
I wept bitterly.
But our blessed Lord condescended also to show me, that in his time,
by the brightness of his arising, he would destroy that spirit;
but many may first be destroyed by it,
and houses great and fair be left without inhabitant.

--

Thus closed his third embassy to Europe--his second visit to Great Britain and Ireland.
Though the "`shadow of coming events,`" brought a cloud over his prospects of the future,
the "`light of the Gospel of the glory of Christ`" shone brightly upon him.
His heart was fixed--trusting in God!
