== Chapter XLVI.

[.chapter-synopsis]
* Religious Visit to Ohio
* Indiana
* Illinois
* New Orleans, etc.

From Virginia Stephen Grellet had crossed over into Ohio,
and now pursued his labours in the great valley of the Mississippi as far as New Orleans.

[.embedded-content-document]
--

New Garden, Ohio, Eighth month, 18th, 1824.
I get on under great depression of body and mind; my sorrows indeed are multiplied.
I am firmly persuaded, however, that none of the combined powers of antichrist,
the prince of darkness, who was a liar from the beginning,
will in anywise affect the blessed Truth; it will stand forever and ever,
and triumph gloriously over all.

I attended all the meetings in this Quarterly Meeting,
and thence I went into Salem Quarter.
Some of their meetings in this new country are very large,
many join Friends by _convincement_, as they say; but very few indeed do I find, who,
if convinced of the Truth, are converted to it.
I much fear, besides,
that there are those among them who have never known what the Truth is.
It is a lamentable fact that many of these so called convinced members
are among those who are carried away by the spirit of infidelity,
which in this Quarter also is greatly spreading.
In these meetings I am often reminded of the concern of the Apostle Paul,
as he wrote to the Corinthians, "`Moreover, brethren,
I declare unto you the Gospel which I preached unto you; by which also ye are saved,
if ye keep in memory what I preached unto you, unless ye have believed in vain.
For I delivered unto you first of all that which I also received,
how that Christ died for our sins, according to the Scriptures, and that he was buried,
and that he rose again the third day, according to the Scriptures.`"

Mount Pleasant, Ninth month, 4th. John Street, from Salem,
at whose hospitable house I have been several times
accommodated whilst in that Quarterly Meeting,
accompanied me to several meetings till I came to Smithfield,
when Benjamin W. Ladd became my kind attendant.
I have travelled very diligently, having frequently two meetings a day,
the distance between them being sometimes considerable;
but my blessed Master is my daily helper.
I go on day by day, in weakness, poverty and fear; in the Lord Jehovah, in whom I trust,
there is help sufficient for each day`'s work; may I only keep in faith and faithfulness,
near his Divine guidance.
I found in those parts many Ranters, under the name of New Lights;
they are very troublesome in Friends`' meetings;
and are sometimes joined in their disorder by such
members of our Society as have embraced infidelity,
who thus openly show forth what manner of spirit they are of.
There are, nevertheless, some substantial,
valuable Friends who maintain their ground in the church of Christ,
and bear a right testimony against these evil-doers.

The Yearly Meeting for Ohio was numerously attended;
several well-concerned Friends belong to it;
they keep a watchful eye over the inroads made in their borders by the adversary,
and the anti-christian doctrines that several persons from other Yearly Meetings are now,
or have lately been, promulgating.
They have hopeful young people`' among them,
who appear to be bending under the yoke of the dear Redeemer.

Chillicothe,
24th. From Mount Pleasant to this place I had several
meetings where Friends have no settlements,
and also among Friends.
I had at most of these meetings the acceptable company of Micajah Collins,
from New England, who was also at the Yearly Meeting.

I then proceeded to Richmond, Indiana, taking meetings on the way.
That Yearly Meeting was very large;
the immigration from slave states to these parts is great;
it renders them however a very mixed company,
and it will require time before they can rightly understand one another,
and get over their various early prejudices.
Their business was conducted harmoniously.
There are some here also who have made strong efforts to sow the seed of infidelity,
and have succeeded in many cases.
I am truly amazed at what is transpiring in our Society
throughout the several sections of it.
O! how busy is antichrist! and how many coadjutors is he enlisting under his banner!
No wonder, therefore, that from place to place,
I should be called upon to preach the Lord Jesus,
and redemption from sin through faith in his name.

My dear friend, Benjamin W. Ladd, has come from Smithfield, Ohio,
to join me as a companion during the journey I have in prospect, as far as New Orleans.
How good is my dear Master in providing me with a helper in such a long,
wilderness journey.
Truly does my flesh and my heart faint at the prospect of the service,
but God is the strength of my heart, and of my feeble frame also.
In Him doth my soul trust.

Cincinnati.
Tenth month, 14th. Accompanied now again by Benjamin W. Ladd,
I had many meetings on the way to this place, where no Friends reside.
The Lord was very near his poor servant.
His baptizing power was felt in a remarkable manner.
The meetings in this place were well attended by the inhabitants,
and great seriousness prevailed over them.

Thence we went towards Blue River, to attend that Quarterly Meeting.
I hope it was a profitable time.
The bonds of Christian unity were strengthened among
those who remain chaste in their love to Christ,
and some of those who have been ensnared by the stratagems of the deceiver,
appeared to be brought under some sense of their fearful condition.
I had close labour, in Christian love, privately and publicly with many of them.
Their meetings were attended by a crowd of people, who came from miles distance.
Blessed be the Lord who remains to be the all-sufficient helper of his poor servants.

I attended all the meetings in that Quarter.
At a small town called Hindostan, on White River, we found the place so sickly,
that one third of the inhabitants have died in consequence.
At Vincennes, an old French town,
we had a very interesting and solemn meeting in the Courthouse.
Many of the French people attended.
They generally understood English.
Some who did not I addressed in the French language.
At the close of the meeting, an aged physician exclaimed in French,
in a very serious manner,
"`How very consonant is your doctrine with the views
I have long entertained of the Christian religion!
My principles agree with yours, and gladly would I become a member of your Society,
did any of your Friends reside here.`"
Accompanied by him we called on several pious aged persons, Roman Catholics.
They were tender-spirited.
We also were with one of their Romish priests.
He at first appeared light and trifling, but towards the last he was sober and civil.

We crossed the Wabash into the State of Illinois, and traversed several prairies,
on our way to Vandalia.
They have the appearance of a garden of flowers,
and the woodlands skirting them add greatly to their beauty.
The accommodations on the road were very poor, especially the lodgings.
We several times had wild turkeys.
They are numerous.
Wild honey is abundant.
They collect it from the forest trees.
At Vandalia I found in the Governor, Edward Coles, an interesting and valuable man.
He was a large slaveholder in the Southern States, but he liberated his slaves,
and gave them land to settle upon.
I had a meeting here, but it was a hard time, like the people that mostly attended it.
These settlers are generally hunters and woodsmen, and are very dissipated,--yet,
under the axe of the Gospel, which is lifted up against the root of the corrupt tree,
some of them were brought into tenderness.
The Governor sat near me, with great seriousness.
We went afterwards for Edwardsville, where we had a large meeting.
From the appearance of the people, I anticipated it would be like that at Yandalia,
a hard season: but it was, like the meeting at Vincennes, attended with great solemnity.
Many of the people were broken into tears.

We travelled thence towards the Mississippi, over the prairies,
and passed several pretty high mounds of earth, which some think are artificial.
They have a very curious appearance.
We crossed the fine, broad and rapid river, opposite to St. Louis;
there I had several large and good meetings.
One was for that part of the inhabitants who only speak French.
It is a place of much dissipation.
Many have become hardened in vice.
Among these I had close service; yet it is remarkable how quiet these meetings have been.
They are the first held here by a Friend.
At the close of the meeting for the French, a young woman came to me,
whose heart was so full that she could hardly speak.
The Lord`'s power was over her.

On the 5th of the Eleventh month, we embarked on the steam boat, Superior,
for New Orleans, and sent back our horses and carriage to Indiana, to wait our return.
We have a great mixture on board, French and Americans.
Some have come down the river, about 900 miles; they reside near the Rocky Mountains;
the cold there is so great that the ice is five feet in thickness,
and last winter it was so severe as to freeze the mercury.
Buffaloes are numerous;
in some of the prairies herds of some hundreds can be seen together.
One of our passengers went last winter 700 miles beyond those mountains,
by the Lake of the Woods; he travelled in a sleigh drawn by dogs;
they put from three to six of these animals to a sleigh,
according to the state of the road, or of the weight they carry,
and they travel forty or fifty miles a day;
on his return to Fort Anthony he sold his equipage for 150 dollars.
This river is rapid; the shores on the side of Illinois are flat about here,
but on the Missouri side they are high, rocky and very romantic.
Lead mines are abundant.
We stopped some hours at a town called Herculaneum, where I had a meeting,
whilst lead was putting on board our boat;
three-fourths of the inhabitants are French people.
Then we came to St. Genevieve, where we stopped a night;
nine-tenths of the inhabitants there are French.
I had a meeting among them also.
My speaking their own language tended to open their hearts to receive me and my testimony.
I felt much for them under their various temptations and privations;
some of their young people manifested religious sensibility and seriousness.
I am the first Friend they have seen,
yet their deportment in meeting might have led us to conclude they had attended many.
Proceeding down the river, we struck ou a snag, but did not receive much damage;
the water being low we grounded at three different times.
It took us some hours of hard work to bring the boat again into deep water.
During the course of this last year three steamboats have been wrecked in these parts.
We found the navigation tedious and dangerous the
whole way to the junction of the Ohio river,
and had narrow escapes from sawyers and planters,
as they call trees carried down the rivers.
This is only 500 miles from St. Louis,
but they consider that the difficulty and time it takes,
are equal to the whole of the other part of the voyage to New Orleans.

We passed by a large steamboat that ran aground three weeks since;
they have not yet succeeded in getting her afloat.

Eleventh month, 9th. We passed by New Madrid;
it was some years since in a flourishing state, but is now nearly deserted.
The earthquake that occurred in 1812 spread devastation
for many miles distance down the river.
It is supposed that an extent of land of one hundred and twenty
miles in length and sixty in breadth sunk down about seven feet,
so that that part of the country which heretofore was far above water,
is now overflowed when there is a rise of the river.
Some suppose that what was thought to be an earthquake
was caused by the alluvial soil giving way,
by the undermining of the river.
Two persons now on board tell me, that they were then on the Mississippi going down,
and the noise was similar to loud rumbling thunder;
the river was for a while in terrible commotion, and the current entirely changed,
so that it carried them up stream a considerable distance, and that with rapidity.
Since that period the bed of the river is altered; islands have sunk; others are formed;
lakes now appear where there was no water before.

12th. We began to flatter ourselves that we had got over the worst part of our navigation,
but last night we were in imminent danger several times by striking on snags,
and now we are fast on a sand bank, and have only about four feet of water.
Very near us is a steamboat that left St. Louis some weeks before us;
she has only one and a half feet of water; when she grounded she had five.
Twenty of her passengers have come on board of our boat,
which increases our weight and crowds us much.
The trial is rendered greater by the unruliness that prevails on board,
together with gambling, drinking and profaneness.
They continue their revellings till late at night.
We are besides much annoyed by a small species of cockroach,
which by night come out of their hiding places by thousands.

15th. After hard work they succeeded yesterday in dragging the boat into deeper water,
but we had proceeded a few miles only when she grounded again.
The men have laborious work.

18th. We succeeded the day before yesterday to get on our way again,
but our difficulties and dangers have continued.
The snags and sawyers and planters are numerous,
and it seems sometimes as if our boat would become a total wreck by them.
We see very little ground cultivated near the banks of the river;
a few poor log cabins are only to be met with;
yet on the chart they have the drawings of large towns,
in which fine streets and large public buildings are represented;
but when we come to the spot we find that hardly a tree has been cut down.
The fine town is only what may be.

20th. We overtook, a few days since, a flat boat loaded with about 40,000 skins of deer,
buffaloes, bears, etc.; their cargo was brought from far up the country;
they had made fast to our steamboat, but last night they passed over a snag,
that broke in ten pieces of her timber.
It is remarkable how we escaped it ourselves.
At the same time we passed by a large steamboat that went aground three months since,
and is not expected to be able to get out again till spring,
when the waters generally are high.

Natchez, 23rd. We arrived here yesterday, after a long, dangerous and trying passage,
rendered the more so by the dissipation of our company;
I was nevertheless favoured to have many seasons of quiet retirement,
amidst the noise and confusion that surrounded us.
Last First-day, in a particular manner, will be held in grateful remembrance;
the voice of the Lord uttered in the secret of the
heart was mightier than the noise of many waters,
yea, than the tumultuous songs and revellings of the drunkard.

Hearing of several persons, both in this place and on the other side of the river,
who have or have had a right of membership in our Society, we went to seek for them.
They are much to be pitied,
having involved themselves and their children in
various difficulties by settling in a slave country;
they have also become slaveholders themselves; they know it is wrong,
but have not strength to break away from the chains they have made strong for themselves.
We had meetings with them and their slaves.
I think that the yoke of bondage, under which they have placed themselves,
is heavier than that of their slaves.
I felt much for some of them; but I have very little hopes of them,
for the love of money greatly increases their bondage.
My mind was brought under sore distress on beholding
the immorality of many of the people in this town,
especially in the lower part of it; cock-fighting and drunkenness are very prevalent;
but the love of Christ, the dear Redeemer,
who has not come to call the righteous but sinners to repentance,
constrained me to endeavour to have a meeting among them,
and to proclaim the offer of salvation through faith in Christ.
Many strangers are at present in this place, it being Court-time,
and also the season when planters come in from a considerable
distance with their cotton to ship to New Orleans.

As soon as my intention to have a meeting in the upper part of the town became known,
the principal inhabitants, of their own accord,
took care to have notice of it extensively diffused,
and had printed notices widely circulated.
It appeared by the wording of the notices,
as if they had been well acquainted with the practices of Friends,
though a meeting of our Society was never held here before.
Their most spacious meetinghouse was selected for the occasion.
It was much thronged, but remarkably quiet, and, beyond my expectation,
it proved to be a solemn, good meeting.
The power of Truth was felt.
The doctrine I proclaimed was indeed very new to many, who have seldom, if ever before,
been at a meeting for Divine worship,
or heard the terms of the Gospel and salvation by Christ held forth to them.
The hearts of many were tendered,
and several came to me after meeting in a loving and affectionate manner.
Among those who called at my lodgings was a Colonel, a rich planter,
who resides about sixty miles distant in the country.
He told me that for many years he had been a man of pleasure,
seeking only the gratification of sense and animal enjoyments,
living out of the fear of God, not even thinking that he had a soul to lose or to save.
About three years since, the Lord, in his love and mercy,
brought him to feel his sinful condition,
and the depth of misery into which he must be plunged for eternity,
should he continue in such a course of life, and die in his sins.
By the operation of the Divine Spirit, who convinceth man of sin,
of righteousness and of judgment, his mind was directed to Christ,
the Saviour of sinners.
He was induced to peruse the Holy Scriptures, and, by degrees, the Lord opened his heart,
which became expanded in love to God and man.
He now felt that, if God, through Christ, had in his mercy so loved him,
he ought also to love his fellow men.
He looked upon his slaves and felt that the love of God is towards them,
that Christ has died for them, and would have them to be of the number of his saved ones;
that therefore he ought to love them, and seek their good, temporal and spiritual.
Now, he said, he longed for their salvation as for his own.
He felt for them as his brethren; whereas, before,
he had only considered them as slaves or chattels.
He had about four hundred on his plantation.
At first he thought he would invite them to meet,
that he might read the Scriptures to them, and try to persuade them to love the Lord,
and earnestly to seek for the salvation of their souls.
"`But,`" said he, "`how should they believe that I was really concerned for their souls,
unless I gave them proof that I was equally engaged to promote their outward wellbeing?`"
Accordingly he collected them together, told them what the Lord had done for him,
and what he believed He would do also for them,
and that he would endeavour to promote their good as far as he could.
"`To convince you of my sincerity,`" he added,
"`from this day the lash of the whip shall no more be lifted upon you,
by any direction of mine; your food and clothing shall be increased,
and I will promote your general comfort.
I have confidence in you that you will try to conduct yourselves well,
and do your best on the plantation, and be industrious; but, rest when you are tired,
and when sick I do not wish you to work; on the contrary,
I desire that good care be taken of you.`"
His slaves were like men amazed at the hearing of such language; but much more so when,
from that day, they saw all these promises fulfilled.
They collect daily at his house, when he or some one else reads the Scriptures to them,
and prays with them.
He also offers to them, at times, such words of instruction, comfort or encouragement,
as the Lord puts into his heart.
The slaves, on their part, appear disposed to do their best;
for they are as ready to evince their love towards him,
as he has been to manifest his towards them.
Of their own accord they have so worked,
and the Divine blessing has so attended their labors that,
although his expenses in providing for them have been great,
yet his yearly income has nearly doubled.
A few months since he received a deputation from
the planters who reside for miles around him;
they came with loud complaints against him, saying,
"`By your conduct you not only expose us all to be ruined,
but to have our lives also destroyed,
for you put our slaves in such a state of discontent and ferment,
that they are ready to rise upon us.`"
"`What have I done,`" replied the Colonel,
"`that I should be the means of bringing such an evil upon you?`"
"`You give so much liberty,`" said they, "`to your slaves; you treat them so well;
you allow them also to meet together, under pretences of Divine worship,
and opportunities are thereby given them to plot together to destroy us.`"
He answered, "`If this is all I have done,
I can but advise you as your greatest security, and for your interest,
to treat your slaves as I now do mine.
By the steps I have taken, I am so far from being in the way of ruin,
that my income has nearly doubled, and my life has never been more secure.
I, like you, some years past, never went out without being well armed; I also, as you,
kept during the night my sword, pistols and gun close by my bed side;
the barking of a dog,
or the rustling of the wind among the trees alarmed me as it does you;
but now I take no such precautions, for I have no fear.
I feel myself so secure among my people that I know every
one of them would expose his own life to preserve mine.
Therefore, I can only strongly advise you to follow my example.`"
What will be the result of this appeal the Colonel could not say,
though he had but little hope they would take his advice.
He much deplores that the laws of the land do not allow him to give liberty to his slaves;
but he treats them as free men.
He is aware of what will probably be their condition after his death,
but he hopes he may succeed to have them sent into free States.
He is at present in a very tender state of mind,
and is a striking example of the force of Truth and
the efficacy of the grace and love of Christ.
This man seems to be clothed with a meek and gentle spirit,
and is in the simplicity of a child.

The next day we went some miles distance to Washington, a handsome town.
Two Baptist ministers, who were at the meeting in the evening, went with us.
They were anxious the meeting at Washington should be held in their meetinghouse,
but that of the Methodists was thought more eligible.
There are some tender spirits in that place; the Gospel stream flowed freely among them,
for their hearts were open to receive it; some were bathed in tears.
On our return to Natchez we found a steamboat at the wharf
that had just stopped on her way to New Orleans;
we went immediately on board of her,
and she being a powerful boat we arrived there before the Superior,
in the evening of the 28th. A few hundred miles before reaching New Orleans,
we saw the banks of the Mississippi in a high state of cultivation;
there are large plantations on which are handsome mansions,
and on a great part of the land the sugar-cane and cotton are extensively cultivated.
There seems to be a succession of villages, but it is, for the most part,
the out-buildings of the plantations and the negro habitations that give that appearance.
They have from three to six hundred slaves on each of these plantations, and,
from the information given me, they are treated with great rigour,
and even cruelty in many instances,
especially when the owners do not reside amongst them.
A system is followed here by many of the overseers similar to that I observed in Demerara;
many of these are mercenary men; the slaves are not their own;
they have not the same care for them that many of the masters have;
they use every means they can to make money;
by over-working the slaves they succeed in obtaining a large quantity of produce;
but this surplus they keep for themselves and not for their employers; again,
they deprive the poor slaves of part of the ration
of food or clothing allowed by the master,
though they charge him with the full amount; again,
some of them purchase damaged corn at a low price for the food of the slaves,
and charge it to their employers at the full price of good corn;
thereby sickness and death occur among the slaves.
I have known planters who have been ruined, whilst the overseers were made rich;
but the greatest weight of suffering falls on the poor slaves,
of whose idleness the masters have continual complaints, whereas,
the whole blame properly attaches to the unfaithfulness and the depravity of the overseers.

New Orleans, Twelfth month, 5th. We met here seriously disposed persons;
some are from New England and other parts of the Northern and Eastern States,
others are inhabitants of this city.
Here also are several members of our Society from England and Ireland,
who have come on business; I knew several of these when I travelled in those countries;
they are in various ways helpful to us.
Becoming acquainted with some pious characters,
among the several religious denominations here,
has brought me to feel for those who have some religious tenderness.
They are exposed to many temptations in a place like this,
where vices of various kinds abound,
and they are in danger of losing the little good
they have been favoured with of the Lord.
I apprehended it was my religious duty to endeavour to have meetings among them,
if possible,
to strengthen that which remains with some and to encourage others
whom I have found in the situation of the wandering prodigal.
Way has also been made beyond my expectation to have several meetings with the inhabitants.
Some were held in the Episcopalian, the Presbyterian, and Methodist meetinghouses.
That of the Presbyterians is the largest and most convenient;
therefore I had several meetings in it.
One of these was held particularly for that portion
of the French inhabitants who do not understand English.
I had meetings also among the free people of colour.
These are a numerous class, many of them are of much respectability,
and some of them of genuine piety;
but they are kept under great oppression by the laws of the land, called the Black Code.
These laws are such,
that I could not hold meetings with these free people in
the evening without exposing them to severe sufferings,
should they be found in the streets when returning to their homes, after eight o`'clock.
I wished to have meetings also with the slaves, but found it impracticable.

I was several times with the mayor, a Frenchman, who treated me with courtesy.
Once, when I called on him at his office,
he was surrounded by the members of the Council,
and some others of the principal men of the city, most of them being French people.
It was a novelty for them to see a Quaker, a French one especially.
It drew their particular attention.
They made various inquiries into our Christian principles and religious testimonies,
which I felt very free to answer,
and especially that relating to the keeping of our fellow men in a state of bondage;
and I stated how great is the injustice of their penal, or Black Code, as they term it.
The unlawfulness and cruelties of war, connected with this,
were also brought under consideration; when one in the company, an aged Frenchman, said,
"`these our practices and our laws are very unjust,
for men have no right to make laws that are in opposition to the law of God.`"
I told them that, according to this sound position, wars, slavery,
and all kinds of oppression, were unjust, being contrary to the law of God,
which is a law of love and mercy, not of cruelty like theirs.
I stated to them that it was love that prompted me to have meetings with their slaves,
to endeavour to bring them to the knowledge of our Lord and Saviour Jesus Christ,
who could deliver them from the bondage of sin,
raise them out of the state of degradation into which they were reduced,
and render them meet to be heirs of his kingdom of blessedness and glory.
But their law says that if a slave goes to any such meeting,
he is liable to be imprisoned, and to receive twenty-five lashes;
and they were the men that put such wicked laws in force.
They said the laws were such, and by their office,
they were obliged to have them executed, though they did not approve them,
and they read them to me; they further said, that,
as I had meetings in the places of worship of other religious denominations,
they requested that I would have some also in their large church (a Roman Catholic one);
that perhaps the truths of the Gospel that I should preach,
might lead to an alteration in their laws.
I acknowledged their kind invitation, but I did not feel that service laid upon me.

I visited an asylum for sixty orphan girls.
The managers of this valuable institution were present.
The widow Hunter is the chief of these.
She was born a member of our religious Society, and came here in early life.
But the religious impressions made upon her in her youth have not left her.
She encourages sentiments of benevolence in many around her.
Perhaps it is owing to a few of these,
that the destruction of this place is not permitted.
My soul is greatly oppressed at what I see and hear.
The first day of the week is not regarded by the greater part of the inhabitants,
and business during most of that day is carried on as actively as on any other day.
Their gambling houses, and places of diversion, are numerous.
Drunkenness and vice abound.
My services in some of the meetings were very close and trying.
I feel very tenderly for those who are afflicted on these accounts.
I visited some of them in their families,
to endeavour to strengthen and encourage them to keep themselves,
and those under their care, from the spots of the world.
I had also a meeting among that class of men.
It was composed of persons of the several religious denominations
who fear and love the Lord and hate evil.
It was a season of Divine favour, and ministered such relief to my mind, that, after it,
the way seemed clear for me to leave this city.
When our conclusion became known, many of these dear people came to see us,
and used strong arguments to induce us to tarry a few months, or weeks only,
longer among them, saying that their several meetinghouses,
their hearts and habitations, were freely open to us.
But it appeared most safe closely to follow my blessed Lord`'s guidance,
to come at his bidding, and to depart at the same.
I have endeavoured to lead this people to the Lord and to his Spirit,
and there it is safe to leave them.
May they keep very near him, and be obedient to his sovereign will in all things!

On the steam boat Indiana.
Twelfth month, 8th. Last evening we had another meeting,
chiefly composed of those persons who are piously inclined,
or who have been brought under religious convictions since we came among them.
It was a solemn and contriting season to many.
May the Lord bless the work of his own hands!
I left New Orleans with an aching heart,
because of the depravity of the greater part of the inhabitants;
but with near Gospel love and strong solicitude for the little remnant
of those who have felt the love of Christ kindled in their hearts.
It is now winter, and yet the weather here is as with us in the spring.
The roses and other flowers in their gardens, are in full bloom.
Their orange and lemon trees are full of fruit and blossom.
They have green peas and other vegetables.
O! that the light of Truth might so shine upon them,
as to induce them to open their hearts to the descendings of the heavenly dew,
and enable them to bring forth fruits of righteousness to the Lord`'s glory!

13th. This steamboat has a powerful engine, so that we make rapid progress up the river,
which is now much higher than when we came down.
She is a large vessel, but we have many passengers on board.
Yesterday, being First-day, I had a meeting with them.
About one hundred and thirty were collected.
A few appear serious, but the greater part are very rough and dissipated men.
Those who attended the meeting behaved with propriety.
In the afternoon, I found more of them than I expected disposed to read the Bibles,
Testaments, and religious tracts I distributed among them,
both in the French and English languages.

15th. We passed near the steamboat Mandane, which, three days since, struck upon a snag,
and is wrecked.
She was run into shoal-water, in time to enable the passengers to escape a watery grave.
Many of them have come on board our vessel, so that,
with others whom we take in daily on the way, our company is becoming very large,
and with this addition, licentiousness, drunkenness, and gambling are increased also.
We have professed gamblers among us.
Many of this class keep going up and down this river,
in pursuit of such a nefarious practice.
They now continue at the gaming table both day and night.

24th. My situation has become more and more trying; my dear companion, Benjamin W. Ladd,
is ill with the dysentery; it has greatly reduced him,
and under such a trying complaint he is, night and day,
exposed to the noise and profanity of those around us;
they sit at the gambling-table close by, and right before the berth in which he lies.
Could I procure a small,
retired corner for my dear friend it would be a great accommodation;
but it is not to be had.

We had last night a very narrow escape; one of our large iron shafts broke suddenly.
It gave such a jar to the vessel that it was thought she had broken to pieces;
but what is very unusual they had on board another shaft similar to it,
so that in a few hours we were prepared to proceed again on our way.

26th. We were crowded here before, but now we are packed close together.
A very powerful boat, the Phoenix, that left New Orleans three days after us,
has overtaken us; but her machinery is now completely broken,
and it will be months before she is repaired;
many of her passengers have come upon our boat;
they bring with them an increase of dissipation.
It has risen to such a degree that the captain, his pilots and engineer,
when not on actual duty, sit at the gaming table instead of taking their required rest,
and thus are very unfit to have the charge of the
vessel when their turn comes to be on service.
We have several times run upon snags, or sawyers, and received some injury.
It is very frequently owing to such conduct that so many vessels are lost on these waters.

My dear companion is better, which is a great relief to my anxious mind;
surely it is the Lord`'s doing,
and of his mercy that he should recover under such circumstances as we are in;
in want of every kind of accommodation, and amidst continual noise.
Most of our cabin-passengers are very unfeeling; there are however a few exceptions.
The deck-passengers are also very much crowded; there are several hundreds of them,
and many are sick; one died last night, and when we stopped this morning to take in wood,
the corpse was buried on shore;
but even this solemn occasion did not interrupt those who were sitting at the gambling-table.
There is some tenderness of spirit among some of the deck-passengers;
I hold meetings regularly among them, and visit their sick, which they take gratefully.

30th. We are very near Louisville, where we expect to leave this abode of dissipation;
it is like a Sodom.
The nearer we draw to the end of this voyage the more intent
they are on their gambling and their riotous dissipation.
A few of the cabin-passengers, however, join us in the meetings I hold on the upper deck,
among whom impressions of a religious nature appear to have been made.

First month, 5th, 1825.
We arrived at Louisville on the 30th of last month.
In the evening I had a large meeting among the people of that place;
we then went to Albany, where another very satisfactory meeting was held today,
for which favour,
and the preservation granted of the Lord during our
perilous and suffering passage from New Orleans,
our souls have very reverently offered praises and thanksgivings to our gracious Helper.
I do not know when I have, during the same number of weeks,
endured so many sufferings and privations, and been amidst so many perils;
but the Lord to this day has helped us; blessed be his adorable name!

Blue River, Indiana, 8th. We came here on horseback,
which was very fatiguing to dear Benjamin W. Ladd; here, at our dear friend,
Nathan Trueblood`'s, he has every attention bestowed upon him.
Our horses and carriage are here, awaiting our return from New Orleans;
also my kind friend, John Street, from Salem, Ohio, who, at the Yearly Meeting,
had agreed to meet me at this place, to proceed with me to the Southern States;
he arrived here the day before we did, so that we have not waited long for one another.
I had here a precious meeting with Friends.
It was truly cordial to be with them after being so long among those not of our Society.
Truly do I love this people,
notwithstanding the causes for sore exercises that exist among them.
Here, I had the Ministers and Elders, and Overseers called together,
and endeavoured faithfully to labour with them,
and to strengthen the hands of those who deeply lament
the inroads which the adversary is making among them.

My dear friend, B. W. Ladd, has improved in his health; he now proposes to return home.
It was his prospect to do so when he first joined me, and, accordingly,
J S has come to take his place.

I met here letters from my beloved wife.
Among other accounts given me is that of the decease of my companion in Carolina,
Samuel Hutchinson, with whom I parted at Lynchburg.
He reached his home pretty comfortably;
but a few weeks after his complaint increased upon him, and he died.
It was with reluctance that he left me.
I am thankful that he reached his home before his decease.

--
