== Chapter XLVIII.

[.chapter-synopsis]
* The Separation

The autobiography of Stephen Grellet is now brought to a point at which
it would be matter of joy to be able to pause,--to pass over in silence,
or to obliterate much that occurred in the few succeeding years;--not on his own account,
but because of the sorrowful events which took place around him in rapid succession,
as results of the influence of Elias Hicks and the promulgation of his opinions.

The Christian reader,
cordially sympathizing with Stephen Grellet in his views of the person,
the attributes and the work of the Saviour, the Lord Jesus Christ,
must indeed already have found it a thing of painful interest to follow him in the conflicts
and exercises which mark some of the previous chapters of this memoir.
And that charity which "`thinketh no evil--beareth, believeth,
hopeth and endureth all things`" would gladly sink
in oblivion the calamities of those days;
but the faithful biographer is not at liberty, in historical truthfulness,
to suppress facts that tend to illustrate the Christian
standing and character of the subject of his narrative.

Stephen Grellet had come into the Society on the ground of conviction;
after a careful examination he had recognized in the religious principles of the Society
of Friends the practical carrying out of the Christianity of the New Testament.
It was at no small sacrifice that he had made them his own;
he had "`bought the Truth,`" and he knew what it had cost him.
Deeply feeling, as he did,
the absolute need of the enlightening influence and power of the Holy Spirit
to a right understanding and a saving application of the truths of the Gospel,
had he been asked "`a reason for the hope that was in him,`" he
could have unhesitatingly adopted the words of George Fox:^
footnote:[See his Epistle to the Governor of Barbados. 1671.]
"`Jesus, who was the foundation of the holy prophets and apostles, is our Foundation;
and we believe there is no other foundation to be laid but what is laid,
even Christ Jesus; who tasted death for every man, shed his blood for all men,
is the propitiation for our sins, and, not for ours only,
but also for the sins of the whole world: according as John the Baptist testified of him,
when he said: '`Behold the Lamb of God,
that taketh away the sins of the world.`'`" With
equal readiness he could have said with Robert Barclay:^
footnote:[Apology, Prop. v. and vi.]
"`We firmly believe it was necessary that Christ should come,
that by his death and sufferings he might offer up
himself a sacrifice to God for our sins,
who his own self bare our sins in his own body on the tree;
so we believe that the remission of sins which any partake of is
only in and by virtue of that most satisfactory sacrifice,
and no otherwise.
For it is by the obedience of that One, that the free gift is come upon all,
to justification.`"
And most cordially could he have united also with the statement of William Penn^
footnote:[__Primitive Christianity Revived.__ Chap, viii, s. 4.]
in reference to this point: "`The first part of justification,
we do reverently and humbly acknowledge,
is only for the sake of the death and sufferings of Christ, nothing we can do,
though by the operation of the Holy Spirit, being able to cancel old debts,
or wipe out old scores.
It is the power and efficacy of that propitiatory offering, upon faith and repentance,
that justifies us from the sins that are past.`"
As fully did he accord with the same writer,
in his open avowal that "`it is the power of Christ`'s Spirit in the heart
that purifies`" the penitent convert--looking in faith to Jesus,
the Lamb of God that taketh away the sins of the world,
and freely forgiven in virtue of the one most satisfactory,
propitiatory sacrifice,--and strengthens him to "`go on unto perfection.`"
Thus, humbly trusting in Christ alone, as the Rock of his salvation,
Stephen Grellet pressed towards the mark for the prize,
studying to shew himself approved unto God, a workman that needeth not to be ashamed,
rightly dividing the word of Truth.

It was in no sectarian, but in a truly Catholic spirit,
that he loved the Christian community of which he had become a member, and,
with a godly jealousy, he watched over its interests,
and sought to promote its spiritual prosperity.
With tender susceptibility, quickened by Christian solicitude,
he had marked some of the earliest aberrations of Elias Hicks,
and had observed with no small concern his wider
departures from the Truth as it is in Jesus.
He had clearly foreseen the consequences,
and had faithfully forewarned his brethren of their approach.
The hidden fire now burst out into an open flame;
the breath of popular excitement swiftly carried it to nearly
all parts of the Society on the American Continent.

Rising out of and above the civil and religious struggles of the seventeenth century,
the Christian Society of Friends had existed nearly two hundred years.
It was widely spread over North America,
and the number of its members on that continent was large.
To a great extent the descendants of the first emigrants from Great Britain and Ireland,
they professed to hold the same religious principles
as the "`early Friends`"--George Fox,
and the faithful of his day.

George Fox himself was a man of no ordinary character.
Though possessed of but little of the "`learning of the schools,`" yet, as a Christian,
his spiritual understanding was sound, clear and comprehensive.
Christ was its centre, and the Truth, as it flowed from him, its area and circumference.
With a mind as humble and childlike in its willingness to be taught,
as it was fearless and unflinching in its obedience to what it had already learned,
he had comprehended the practical bearing of the great Christian doctrine--the
simple fact--of the direct influence and perceptible guidance of the Holy Spirit;
he saw and appreciated not only its entire accordance with the Holy Scriptures,
but its importance also as an essential part of Gospel truth.
The Old and New Testament were the canon of his religious belief.
In doctrine--he fully recognized the conclusiveness of their Divine authority;
in practice--he felt it to be his bounden duty, under the guidance of the Holy Spirit,
at all hazards,
faithfully to carry out in life and conversation all that was required by their teaching;
and he was ever willing that both his principles and his
conduct should be brought to the test of their decision.
Mere human systems were nothing to him in point of authority;
ecclesiastical establishments with their Popes and Cardinals,
"`Right Reverend Lord Bishops,`" and the lower grades of the priesthood, were,
in his view, unscriptural institutions,
inconsistent with the spirituality and freedom of the Gospel dispensation.
In willing subjection to the enlightening operations of the Holy
Spirit he had prayerfully and diligently "`searched the Scriptures,`"
and in humble faith he had come to Him of whom "`they testify.`"
In Him he had beheld his Saviour and his God,
and he could "`call no man master on the earth.`"
Taking a firm footing upon the only true foundation--Christ
Jesus himself--he stood forward as a practical reformer,
with a mind of no common grasp; with one great stride he stepped over centuries,
and reached a point of Christian development,
and originated and sustained a Christian polity,
than which nothing could well be more scriptural,
or more in accordance with the words and spirit of the Saviour`'s teaching.

Calmly looking back on the characteristics of early Quakerism,
as it regards the comprehensiveness of its Christian principles,
the completeness of its standard of Christian practice,
and the spirit of its Christian discipline,
and viewing them in connection with the universal church of professing Christendom,
it appears to be a simple historical fact, that wherever, in any direction,
there has been real progress--any onward movement--it has been towards
the position occupied by the early Friends--George Fox and his associates.
It is not needful to particularize; the thoughtful and intelligent reader will be able,
at a glance, to fix his eye upon various points of Christian principle and practice,
which illustrate what has been said.

In taking this estimate of the early Friends and their sphere of usefulness,
it would not be serving the cause of truth to attribute to them a freedom
from human infirmity to which they themselves laid no claim;^
footnote:[It ought not to be forgotten with what
chaste attachment to the Redeemer`'s cause,
George Fox exclaimed respecting himself and his brethren, "`We are nothing;
Christ is All!`"]
and in justly appreciating their worth,
it is well to bear in mind that they were fallible men of like passions as we are,
liable to be biased in judgment and influenced in their
actions by the difficult times in which they lived.
They did not seek but rather avoided the use of terms of scholastic theology;
yet as Christian men, under a strong sense of their accountability to God,
they did not hesitate plainly and honestly to declare their religious belief.
They did not leave the world in doubt as to their Christian stand-point;
and a careful and candid perusal of their writings and biographies will afford incontrovertible
evidence that they were thoroughly sound in the fundamental doctrines of the Gospel.
They had no new Gospel to proclaim.
In common with other orthodox professors of the Christian name they most
fully recognized the Divine inspiration and authority of the Holy Scriptures,
and thoroughly believed in all that is revealed therein
concerning the unity of the Godhead--the Father,
Son, and Holy Ghost--one God over all, blessed forever;
they unhesitatingly held the utter depravity of human nature in consequence of the fall;
the pre-existence and incarnation of the Son of God; the proper,
eternal Deity and the real manhood of the Lord Jesus Christ;
the need and efficacy of his propitiatory sacrifice,
as an atonement or expiation for the sins of mankind;
his mediatorial intercession and reign:
the forgiveness and reconciliation of the repenting sinner, through faith in Him alone;^
footnote:[It is interesting to notice the beautiful harmony between one of the first
testimonies and one of the last exhortations of George Fox in reference to the Saviour.
"`The sins of all mankind were upon Him,
and their iniquities and transgressions with which he was wounded,
which he was to bear and to be an offering for, as he was man,
but he died not as he was God; and so, in that he died for all men,
and tasted death for every man,
he was an offering for the sins of the whole world.`"--pg. 21. "`Christ reigns,
and his power is over all; who bruises the serpent`'s head,
and destroys the devil and his works, and was before he was.
So all of you live and walk in Christ Jesus; that nothing may be between you and God,
but Christ, in whom ye have salvation--life, rest, and peace with God.`"--Pg. 66,
and three days only before his death.
[.book-title]#Fox`'s Journal#, vol.
i, p. 51, and vol.
ii, p. 352, Armistead`'s Edition, Leeds, 1852.]
the work of the Holy Spirit in the conversion of the sinner, and in the preservation,
guidance, and sanctification of the believer in Jesus; the immortality of the soul;
the resurrection, and the final judgment of the world by our Lord Jesus Christ;
the eternal blessedness of the righteous, and the eternal punishment of the wicked.
In reference to these things William Penn,
in the full maturity of his judgment and the brightest period of his Christian experience,
had explicitly declared:
"`Where we are vulgarly apprehended to differ most we dissent least,
I mean in doctrine.--For,
except it be the wording of some of the articles of faith in school terms,
there are very few of those professed by the '`Church of England`'
to which we do not heartily assent,--I say then that,
where we are supposed to differ most,
we differ least.--It is generally thought that we
do not hold the common doctrines of Christianity,
but have introduced new and erroneous ones in lieu thereof,
whereas we plainly and entirely believe the truths contained in the creed
commonly called the '`Apostles`' Creed,`' which is very comprehensive,
as well as ancient.--If keeping to the terms of Scripture be a fault--thanks be to God,
that only is our creed; and with good reason too:
since it is fit that That only should conclude,
and be the creed of Christians which the Holy Ghost
could only propose and require us to believe.`"^
footnote:[__Defence of Gospel Truth.__
Works, 3rd Edition, vol.
v., pp.
380, 381, and 417.]

It is evident that those Christian testimonies by which the early Friends were
more especially distinguished from their brethren of other denominations,--their
views on the direct influence of the Holy Spirit,
on worship, the ministry and the "`ordinances,`" on liberty of conscience, war, oaths,
ecclesiastical impositions, and some other points,
were all based upon the essential doctrines of the Gospel.
Their whole superstructure plainly and broadly rested upon the
immutable foundation of the revealed truths of the Bible.^
footnote:[In proof of these statements it is sufficient
to refer to the Selection from __George Fox`'s Epistles,__
by Samuel Tuke; Second Edition, London, 1848; Evans`' __Exposition,__ Philadelphia;
Rules of Discipline,
and Advices of the Yearly Meeting of the Society of Friends in London; London 1834;
and Epistles from the Yearly Meeting of Friends, held in London,
from 1681 to 1857 inclusive, 2 vols.; London, 1858.]

It would be a great mistake to suppose that the separation among Friends in America,
which arose out of the course pursued by Elias Hicks and some of his adherents,
hinged upon non-essentials.
It was what William Penn calls the common doctrines of Christianity,
those essential facts and truths without which Christianity would be a
mere name--a shell without a kernel--that were the objects of attack,
and were boldly denied.
That faith in a crucified and risen Lord which overcomes the world, the flesh,
and the devil, and is abundantly fruitful in holiness and good works,
was sought to be supplanted by a refined and spurious spiritualism, which,
under a partial adherence to a scriptural phraseology,
totally rejected the true scriptural "`Doctrine of Christ.`"^
footnote:[These remarks are written with no feeling of unkindness towards a single individual,
either of the past or of the present generation.
There were no doubt many of the past who, from family considerations or other causes,
were associated with the seceders without holding their extreme views;
and in regard to the present generation,
it is indeed cause for thankfulness that there are
increasing indications of a spirit of candid inquiry,
which, through the Divine blessing,
may eventually lead to a cordial acceptance of the
fundamental doctrines of the Christian faith.
It is obvious, however,
that such an acceptance must of necessity be based on a
just appreciation of the character and work of the Saviour.
A deep feeling of Christian love and interest on behalf of those who are separated from
us prompts the earnest desire that all who bear the name of Friends may thus be brought
to rejoice together in "`the fulness of the blessing of the Gospel of Christ.`"]
Few, perhaps,
besides Elias Hicks and some of the prominent characters among his followers,
had any clear perception of the real merits of the controversy,
and the vital nature of the points at issue; many young people, as well as others,
unwittingly followed their leaders, little suspecting, it may be,
the wide departure from "`the word of the truth of the Gospel,`"
to which they were in danger of being carried.
Without attempting to lay open the depth and significance of some
of the causes which led to the deplorable results that followed,
it must not be overlooked, that, at the time referred to,
a very inadequate provision for early instruction and for a guarded and religious education,
and the habitual neglect of the diligent and prayerful perusal of the Holy Scriptures,
had left many in great ignorance of the saving truths of the Gospel,
and destitute of a clear understanding of the real
nature and grounds of their religious profession.
The knowledge of the Christian principles of the Society was, with many,
merely traditional,
and little calculated to afford them the means of readily detecting points of divergence.
Thus, blind to the danger and almost defenceless,
they were ill prepared to meet the subtle fallacies which assailed them,
and fell easy victims to the "`spirit of error`" that prevailed around them.
It is thought that about one-third of the Society
in America was swept away by that fearful schism.

Stephen Grellet stood unmoved in the midst of the storm; meekly firm and humbly bold,
he was a faithful witness to the Truth.
He loved Quakerism because to him it was identical with pure and simple Christianity,
and he did not lose it in the conflict;
his apostolic spirit was not robbed of the freshness of its bloom,
nor of the sweetness of its fragrance; much beloved by those who knew him best,
he was still the loving disciple of the Lord Jesus--the faithful minister of Christ.

[.offset]
In the Tenth month, 1826, he makes the following memorandum:--

[.embedded-content-document]
--

I have been most of my time at home since last year,
except attending some meetings not far distant.
During the summer I visited most of the meetings in this State, New Jersey,
in which service I was repeatedly brought under deep and trying exercise;
for principles of infidelity are here also gaining the ascendency over many minds.
At our last Yearly Meeting we had the very sorrowful
evidence that there are very few sections,
if any, in this Yearly Meeting,
where the baneful influence is not felt to a lamentable extent.

--

The crisis was now at hand.
The Society was on the eve of a separation.
Many faithful labourers from the various churches in America, and some from Europe,
nobly contended for the "`faith once delivered to the saints,`"
and earnestly sought to restore the erring,
and to guard the unwary--by "`manifestation of the Truth.`"
But the development of what had long been worming
itself into the foundation and bulwarks of the Society,
produced a state of things which left but little hope that the breach could be healed.
At this juncture Stephen Grellet felt it to be required of him, in the love of Christ,
to pay a general visit to Friends in the compass of his own Yearly Meeting.
On his return home from this engagement, which occupied about five months,
he takes the following review of the service:--

[.embedded-content-document]
--

Ninth month, 1827.
I have just returned from a very trying engagement throughout this Yearly Meeting,
except this State, New Jersey, which I visited last year.
It was a duty that pressed on my mind, and, during the last few months,
I felt it in a manner so imperative that I could
not understand the nature of the attending impressions.
"`Now or never!`" seemed to be the language proclaimed in my ear.
But now I can "`run and read;`" for it was only then, indeed,
that a service of this kind could be performed.
One day later would have prevented my attendance of many of the meetings I visited.
It was at many of those Quarterly, Monthly, and other Meetings,
that those who have rejected the Lord Jesus Christ as their Saviour and Redeemer,
and counted the blood of the covenant which was shed on Calvary as an atonement for sin,
an unholy thing, organized themselves as a separate body from us,
and publicly identified themselves with the followers of Elias Hicks.

I spread my religious concern before Friends of my
Monthly and Quarterly Meetings of Burlington,
who gave me their testimonials of unity.
I then went to our Yearly Meeting of Philadelphia.
It appears that those now opposed to our Christian testimonies had had private conferences,
and had taken measures to obtain the ascendency in the Yearly Meeting;
but the Lord frustrated their devices and overruled all to his own glory.
We had some very trying seasons during that Yearly Meeting,
when many fervent prayers were put up,
and we had repeated evidence that our Lord is a God that heareth prayer.
I have seldom been a witness to greater fervency of spirit and solemnity,
than was frequently over us,
even when by their levity and impious expressions some were
giving evidence that the spirit of antichrist actuated them.
Truly, to many of these, I saw the applicability of the language,
"`If your light becomes darkness, how great is that darkness!`"
My silent request for them was, "`Father forgive them,
they know not what they do!`" for the power of darkness was over them.
At the close of the Yearly Meeting,
those disaffected members held meetings to organize themselves
into a separate body from our religious Society.

Fifth month 19th. I went to Abington Quarterly Meeting, held at Horsham,
which was a turbulent time.
I could not have credited what I saw and heard.
There was no room for me to preach the Gospel of peace,
and to exalt the name of the dear Redeemer.
My place was to suffer with Christ,
and also to bear my portion of reproach for his great name`'s sake.
Before I left the neighbourhood, however,
I had two solemn religious opportunities with Friends, who were prepared,
by what they have suffered, to receive the consolations of the Gospel of Christ.
He continues precious to some of them as a Saviour and a Redeemer.

I returned to Philadelphia, and from thence went to Wilmington,
to attend Concord Quarterly Meeting held there.
I had not been at the meeting of Wilmington for many years;
very painful changes have taken place there;
they have yet a large body of nominal professors with us,
but alas! many of these deny the only Saviour, and reject the only hope of salvation.
On First-day their meetings were largely attended by these and the town`'s people.
The burden of the word given me to preach was Christ and him crucified;
who was delivered for our offences, and raised again for our justification;
I set forth the heinousness of the sin of unbelief in Christ,
and earnestly besought them to return unto him whom they had denied,
that they might have hope to obtain eternal life through him.

The Quarterly Meeting was held during the two succeeding days.
The power of darkness was felt; but the Lord`'s power had the dominion.
The committee of the Yearly Meeting attended, and brought weight with them.
I had an opportunity to labour in Gospel love,
entreating most affectionately those who have been shaken from the Christian hope,
to reconsider well their steps.
Many of the young people appeared serious,
and several Friends seem disposed to maintain their allegiance to Christ with firmness;
but in that Quarter, a large number are too wise in their own conceits,
to accept salvation from a crucified but risen Lord.

18th. Attended the Quarterly Meeting of Cain.
It was held to more satisfaction than the preceding one.
Many appeared glad that Christ, the Way, the Truth, and the Life, was preached;
and that his glorious name, as a Saviour, was exalted that day among them.

21st. I had some meetings on my way to the Quarterly Meeting of London Grove.
These are days when the Gospel must be preached with great plainness of speech.
Whether the people will hear or forbear, I must publicly confess unto Jesus,
as the Saviour of sinners.
At this Quarterly Meeting were many opposing spirits,
and by some blasphemous doctrines were held forth.
It was laid upon me loudly to proclaim that hope of redemption
which the believer has through faith in our Lord Jesus Christ.
I went to meeting,
and sat for a while under a very oppressive load of poverty and distress.
This was much increased by the unsavoury communications of some of the disaffected ones;
when the word of the Lord seemed like a flame kindled in my heart; "`whilst I was musing,
the fire burned, then spake I with my tongue.`"
As I spoke the Lord`'s power came over all.
O! that the people would bow down to him,
before the day overtakes them that will grind to powder all the rebellious.

I went from thence towards the Eastern shore of Maryland,
to attend their Quarterly Meeting at Easton.
On the way I had several meetings.
Throughout this Quarterly Meeting Friends have, with some few exceptions,
adopted the views of Elias Hicks, and are pursuing measures to separate themselves,
in a body, from our religious Society.
Their Quarterly Meeting was a very distressing time.
They do not conceal their anti-Christian notions.
Neither could I forbear, privately and publicly, among them,
and the inhabitants of the place, who numerously attended some of these meetings,
to testify unto the whole truth as it is in Christ, to expose the nature of infidelity,
its baneful tendency, and what must be the end of those, especially,
who after having once known the Truth, and felt the power of it, now depart from it,
crucify the Son of God afresh, and put him to an open shame.
Under the sensible feeling of the love of that Saviour, whom they deny,
who has come to seek and to save them that were lost,
I laboured and pleaded with them very earnestly and affectionately.
I did the same throughout all their particular meetings in that Quarter,
seventeen in number.
I saw, indeed, as was intimated to me before I left home, that "`now was the time,
or never;`" for separating themselves from us, and that on such awful ground,
there is no prospect that any other opportunity for religious
meetings with them will be had for a long time at least.
My soul mourned deeply over them, and I shed many tears.

Here my spirit has also been under great oppression,
because of the hard bondage under which many of the slaves are kept.
Considerable numbers are sold to be sent to Louisiana.
This causes many heart-rending occurrences, when husbands and wives,
parents and children, are torn asunder.
Frequently, also, the free negroes are kidnapped, gagged,
and chained to the bottom of wagons, and thus carried away to be sold.
Whilst a woman was for a short time absent from her home,
some of these men-stealers came in, took away her children, and to conceal their deed,
if possible, set fire to her house,
to lead her to conclude that the children were burned in it by accident.
They were discovered and pursued, but not overtaken.
The poor mother lost at once, by these depraved men,
her children and her all in this world.
A negro man was more successful.
A traveller was passing, and, seeing his little son playing about the house,
took him in his gig and went off with him.
The father, who was at work in the field happened to see him from a distance,
ran after him, and overtook him in the town of Camden, where,
by the assistance of some benevolent persons, he recovered his son.

The Nicholites residing in these parts, which I visited some years since,
have very generally joined our religious Society.
They were then a very tender people.
Many of them appeared to adorn our Christian profession;
but they now are mostly carried away by an infidel spirit.
I could wash them with my tears.
It could never have been credited that Satan`'s devices should have proved so successful,
even with such as once appeared to love the Lord Jesus,
had actually tasted of his goodness, and were monuments of his mercy.
All this loudly proclaims the necessity for me to watch and pray, and that continually,
lest the flood of temptation should at any time prevail also against me.

I returned into Pennsylvania the 14th of Sixth month,
and proceeded to visit the meetings in Chester and Lancaster Counties.
I found that active persons in the separation, from Philadelphia and other places,
were very diligent throughout those meetings,
in disseminating their pernicious doctrines, and in organizing their separate society.
It brought me frequently into contact with some of them,
and as my religious labour was directed to the building
up that which they tried to destroy,
they did not spare their personal abuse of me.
Truly the servant cannot expect to be above his Master, nor the disciple above his Lord;
those that reviled and rejected my Saviour, the Lord of all,
could but treat in like manner his poor servant.
These are days of very sore conflict.
My heart mourns over many, especially of the young people,
who are carried away by the craftiness of those who rob them of their greatest blessing,
even of that salvation which is by faith in the Lord Jesus Christ.

It was laid upon me, from place to place,
as the last opportunity I may ever have with them,
and which perhaps some of them will ever have to hear the Truth as it is in Jesus proclaimed,
to set before them with clearness, the way unto life and peace, through Jesus Christ,
and that to everlasting misery, through infidelity and unbelief.

I was a little encouraged in some places,
by meeting with tenderness among the dear youth,
and also in finding nearly everywhere a few Friends
who retain their integrity in the Truth.
The Lord condescended very graciously to comfort and encourage
us together to hold up our Christian profession without wavering,
to the end of our earthly race.
My faith during these days of scattering and trouble,
is more firmly and clearly established than ever before,
in the great truths of the Gospel,
and the brightness of the Sun of Righteousness seems to shine, in my view,
with greater lustre and glory.

From these counties I proceeded towards the mountains,
on the other side of the Susquehannah.
I went as far as Catawissa, Muncy, and Elklands.
Throughout those parts I found that the enemy has succeeded in sowing his tares,
and that they are growing strong in the hearts of many.

On my return I attended the meetings in Abington Quarter,
and lastly those in Bucks County.
In these parts also the adversary has made a great inroad;
antichrist is openly preached without rebuke, but rather, it would appear,
with general approbation.
As they had not yet fully organized their new society, but nominally, at least,
are yet of ours, I felt it to be my place to have meetings with them;
it being the very business for which my dear Master
has sent me on the present Gospel embassy,
to proclaim from place to place,
as now I have done in nearly all their meetings in this Yearly Meeting,
the warning voice, whether they will hear or forbear;
very mournfully indeed have I left them day by day, when after a meeting,
I could but compare my sorrowful heart to that of one returning from a funeral.

I came home the midst of the Ninth month,
having been absent about five mouths on that trying service.
Since my return my afflicted soul,
remembering the many sore services during that journey,
and the frequently renewed extension of the Lord`'s love and mercy towards the backsliders,
still weeps bitterly over them.
How applicable to them is the Saviour`'s lamentation over Jerusalem,
"`How often would I have gathered thy children, etc., but ye would not.
Behold now, thy house is left unto thee desolate,
and the things that belong to thy peace are hid from thine eyes.`"
Ah! how awful is the language!
My soul trembles with fearfulness,
lest this be actually the state of many of these people.

--

Though his own particular meeting was, in great measure,
preserved from the devastating influence of the prevailing evil,
the poison had spread considerably in the surrounding district.
His Christian solicitude was kept painfully alive,
and instead of resting from his labours,
his active services were again called forth in the Redeemer`'s cause.
On the 4th of Fifth month, 1828, he makes the following entry in his note book:

[.embedded-content-document]
--

On my return home last fall, I found that the same spirit,
under which I had suffered so deeply during my last journey,
had acquired much ascendency in these parts also.
This introduced me into a field of arduous labour, throughout this Quarterly Meeting,
and those adjacent.
Many families have become involved in deep trial in consequence of this spirit.
It divides between those who were heretofore united by the close ties of friendship,
and Christian fellowship.
This strong bond is, in several instances,
broken even between those who are joined together by the marriage covenant.
Very often my most tender feelings of sympathy are awakened.
In some of the sufferers I have beheld the excellency of the religion of Christ.
O, how contrary are the fruits of the spirit of antichrist,
to those which are borne by such as act under the
influence of the spirit of the dear Redeemer,
our Lord and Saviour Jesus Christ! "`Charity suffereth long and is kind;
charity envieth not; charity vaunteth not itself, is not puffed up,
doth not behave itself unseemly, seeketh not her own, is not easily provoked,
thinketh no evil; rejoiceth not in iniquity, but rejoiceth in the Truth;
beareth all things, hopeth all things,
endureth all things--charity never faileth.`"--Such
a rich treasure is the fruit of the love of God,
through Christ Jesus.
The Christian believer may cherish the hope of obtaining it,
because the love of God is shed abroad in his heart,
by the Holy Ghost which is given unto him.

Now separate Meetings are set up throughout our Quarterly Meeting,
as is also the case throughout this Yearly Meeting.
Here, in Burlington, we have, to a considerable extent, escaped the overflowing scourge.
No separation has taken place in our particular Meeting.
May the badge of Christianity more and more prevail
among us I If the love of Christ dwells in our hearts,
then we shall love one another.

--
