== Chapter LII.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Hanover
* Brunswick
* Quedlinburg
* Magdeburg
* Potsdam
* Berlin

Their stay in Hanover and places on their way to Berlin was short;
but in the Prussian capital they were detained nine days in the
prosecution of the interesting objects of their Christian embassy.
They met with many who "`worshipped God,
and whose hearts the Lord opened that they attended
to the things which were spoken`" by them.

[.embedded-content-document]
--

On our way to Hanover, we tarried a few hours at Eilsen, near Buckeburg, a clean,
beautiful place, of great resort, its mineral waters being in high repute.
The grounds near it are extensive,
parts of them covered with lofty trees reminded me of our dense forests in America.
The air also is very pure; neither are they annoyed by insects.
There are on the grounds many grottos and summer-houses,
in which visitors can retire and be as private as they desire.
We arrived the same evening at Hanover.

We wished to see the Duke of Cambridge,
who made way very readily for our being with him the ensuing morning,
the 14th. We were at first introduced into the drawing-room, where we found many persons,
both of the military and civil departments.
They soon gathered round us in a respectful manner.
They made many inquiries respecting our Christian profession.
Others were particularly desirous to obtain information respecting prisons,
and the religious and moral education of the children of the poor.
After being with them nearly half an hour,
the Duke sent us a message to go to his private apartment.
He knows the manners of Friends,
and took no notice of our appearing before him with our heads covered.
He recognized William Allen, who had been with him in London;
he listened with attention to what we had to communicate to him,
and manifested great openness towards us.
Here, also, we had to plead for full liberty of conscience.
Their Society for the circulation of religious tracts has met with many impediments.
Every sheet that is printed has to pass under the
censorship of the military or civil department.
We hope that some of the oppressive restrictions on the press will be removed.

We found here a few persons of piety, with whom we had satisfactory intercourse.
Many of the houses in this place, as in Minden, are built in an antique style;
the gable-ends face the street; the roofs are high and have three or four stories,
and there are from four to six stories underneath,
so that the buildings have a lofty appearance.
As every story projects over its base about one foot,
it renders the upper ones in the streets, which are generally narrow,
so close to one another,
that the inhabitants of the upper stories may almost touch hands.
Some of the streets are far from being kept clean,
and the free circulation of air being much impeded,
they are rendered gloomy and unhealthy.
This city is not very extensive, but as nearly every story accommodates one family,
it contains from thirty to forty thousand inhabitants.
The environs of the place compensate for the narrowness or confinement of their streets.
They are planted handsomely with shrubberies and trees;
have walks beautifully laid out and gravelled,
with retired arbours where the people can sit down.

15th. Came to Brunswick.
This town is kept more clean than Hanover.
The environs are also beautiful.
Here I found in the landlord of the hotel at which we put up, a Frenchman,
who came from the vicinity of Limoges, the place of my nativity, and who,
like myself and others of the nobility, emigrated to Germany in the year 1791.
We were together in the same army; he continued in it after I left.
The body of the army he was in was first sixteen thousand men strong,
but it was so recruited from time to time,
that he says they lost about fifty thousand men in that bloody war,
and there was but a handful of them left at last.
He was delighted to see me.
He has a large family, and has made a handsome estate.
I endeavoured to urge upon him the gratitude with
which his mind should be clothed before the Lord,
who, in such mercy and compassion, has preserved his life to this day,
even when he beheld thousands fall around him,
and had also to contemplate the great religious insensibility that was
manifested by many of his companions to the last moments of their lives.
This was such that,
whilst their advanced posts were so near those of the French Revolutionists that
though they could not see one another because of the darkness of the night,
they could distinguish the sound of voices,
and therefore spoke to one another only in a whisper,
yet even then they were so intent on card-playing,
that they did it by the aid of glow-worms.
They held these in one hand and the cards in the other, now and then laying them aside,
to fire upon the enemy in the direction of the voices,
whilst they were fired at in return; though now and then some were killed,
yet others would readily take their places, and continue the game!
O the cruelty,
the depravity and the wickedness that war brings
with it! it baffles all attempt at description.
We had a tendering religious opportunity with this person and his family;
he accompanied us to the houses of some pious persons whom we wished to visit;
one of these, Staubvasser, is a Moravian;
his father was for years a devoted and useful missionary in South America.
This man has an extensive manufactory of japanned articles made of paper-mache,
out of the profits of which he has largely contributed
to the benevolent exertions of the Moravians;
he has a pious family.

16th. We came to Quedlinburg, through tedious and bad roads;
this is a miserably built place.
Our minds were brought under much exercise among them,
but we saw no way to obtain any relief.
Our chief object in turning out of the great road to Berlin,
was to visit a family here in religious profession with us; there were several formerly,
but the Prince of this small principality,
has in various ways persecuted them by imprisonment, confiscation of their property,
and banishment.
This family has suffered considerably; they have been banished three times,
and it is most probable they will be again.
We endeavoured to encourage them to live in the fear and love of God,
and in the faith and patience of Christ.
We wished to be with the Prince to plead before him the cause of conscience,
but he was absent.
We met with a few persons here,
whose minds appeared open to receive what we apprehended
was our religious duty to impart to them,
and through whom also we hope that the Prince will hear some of the concerns
we had wished for an opportunity to spread before him.

Thence we went to Magdeburg, which is a fortified place;
the fortresses are considered to be particularly strong.
It is a well-built city, many of the streets are wide and clean.
It contains many inhabitants,
but we could not come to the knowledge of any one
with whom we could mingle in Christian fellowship;
yet probably there are those unknown to us who love the Lord Jesus.
As we walked the streets people of all descriptions
stared at us as if we were strange beings;
very probably they had not seen a Friend before.

On our way to Berlin we passed through Potsdam and some other towns,
but we did not find anything to detain us among them.
We came to Berlin early in the morning of the 19th.
As we frequently travel during the night,
we are enabled to save much time on the road.
Soon after our arrival I went to see Gossner,
one of those Roman Catholic priests convinced of the errors of
Popery that I was with about nineteen years since at Munich.
He, with others, underwent much persecution; being banished from Bavaria,
he wandered to various places till he received an invitation to go to Russia;
this was done through Prince Alexander Galitzin, whom I made acquainted,
whilst at Petersburg,
with the sufferings that Gossner and others had endured on account
of their faithfulness in maintaining sound Christian doctrines,
in opposition to the errors of Popery in which they themselves had heretofore been involved.
Gossner`'s labours, after coming to Petersburg, were chiefly among the Germans,
who are pretty numerous in that city; the Divine unction attended his ministry,
and the Lord`'s blessing upon it was such that it caused a great sensation in Petersburg.
The religious meetings that he held were attended by a large number of persons,
and such was the change in their lives,
and the evidence of real piety apparent in many of them,
that it excited the jealousy of some of the clergy of the Greek Church;
and the more so because some of the Russians forsook
them to attend the meetings held by Gossner.
He preached Christ and the truths of the Gospel,
divested of those inventions that the blind zeal
and activity of man have mingled with it,
particularly in the Roman Catholic, the Greek and other Churches.
His great aim was to bring men to Christ,
and to an acquaintance with the operation of the Holy Spirit on their own minds,
and to encourage them watchfully and faithfully to attend to the dictates thereof,
because it is the Spirit that leads into all Truth;
it is He also who reproves or convinces the world of sin, of righteousness,
and of judgment, according to the words of the Lord Jesus,
"`I will not leave you comfortless, but I will send you another comforter,
even the Spirit of Truth,`" etc.
Gossner`'s example was in harmony with his precepts;
for he was frequently engaged in silently waiting on the Lord,
seeking for the guidance of the Divine Spirit,
and for his assistance in the performance of the solemn act of worship, which,
as Christ said, is to be in spirit and in truth.
Persecution here also was finally stirred up against him,
and he was obliged to retire elsewhere.
He came to Berlin; the King of Prussia, who had heard of his great piety,
gave him a kind welcome.
The Pastor of the Bohemian Church had lately deceased,
and this appeared to be a field prepared for Gossner
to enter into the labours of the Gospel.
These Bohemians, or their parents,
had been obliged to flee from their country on account
of persecution by the Romish Church.
They now compose here a large church, which is also attended by many of the inhabitants,
particularly of the pious in high rank, among whom Gossner has much place.

He continues, by letters,
to extend his Christian care over those he has left at Petersburg,
and he has satisfaction and consolation in that some
of them maintain their integrity in the Truth,
and their allegiance to Christ,
whom they acknowledge and find to be their bishop to instruct them,
and their high-priest to present their offerings unto God, whether they be prayers,
or sacrifices of brokenness of heart and contrition of spirit.
They know Him, also, as their Shepherd to lead them into, and feed them in,
the pastures of Life.
Thus, though they have none vocally to minister unto them,
they forsake not the assembling of themselves together;
their expectation being on the Lord alone, they are not disappointed,
for he is ever nigh to all that wait upon him, and good to those that call upon him.

One of the pious nuns, the sister Ida, whom I saw at Munich, is with Gossner.
We had, for a length of time, very little to communicate to one another by words;
but wa were all of us retired in reverent and solemn silence before God,
and refreshed together under the precious evidence
that our communion and fellowship is with the Father,
and with the Son, Christ our Lord, through the Spirit.^
footnote:[Dr. Paterson in the work already quoted,
gives an interesting account of Gossner`'s labours in Russia,
and the persecutions he endured.
"`Perhaps no individual,`" he says,
"`has done more for advancing the cause of the Saviour in the world than he has done.`"]

Dear Allen was not with me this morning;
he needed rest after the past days of close engagements and travelling.
Previous to leaving Gossner, I appointed a meeting for Divine worship,
to be held this evening, of which he undertook to spread the information.
Those that collected together on the occasion were generally persons of piety.
It was a season when refreshings from the Lord`'s
presence were very sweetly extended to us.
We felt the baptizing power of the Spirit to bring us into the oneness,
enabling us reverently to worship the Father, and to drink together into the one Spirit.
Among those present were Eisner,^
footnote:[It was at his suggestion that Tholuck wrote his __Guido and
Julius,__--one of the best and most useful of his valuable works.]
the Secretary of the Bible Society here, and Charles La Roche,
who is at the head of the department of the mines in this kingdom.
One of them interpreted for dear Allen and for me.

20th. We visited some pious persons; one was Theodore Julius Gamet;
his parents were of the French Refugees, during the persecution in that nation.
There is a congregation of these in this city.

We were with the Count and Countess Von der Groben;
they are acquainted with vital religion.
We thought we could salute the Countess as a disciple of the Lord Jesus.
Meekness and humility are the clothing of her spirit.
Though she is frequently with the Crown-Prince`'s wife,
yet she mingles very seldom with the Court.
Her visits to the Princess are of a private character,
and her pious influence over her as it regards the
principles and practice of genuine piety is considerable.
This is also the case with the Count, her husband, towards the Prince.
It was truly comforting to us and refreshing to our spirits to be with them.

We next went to Dr. Julius, Inspector of the prisons.
He accompanied us to several other families,
one of which is very zealous in acts of benevolence,
reducing into practice what pure religion is described to be.
In the afternoon, Doctor Julius still accompanying us,
we visited a retreat for juvenile offenders, both boys and girls.
During one half of the day they receive school learning and religious instruction.
The other part is employed in manual labour, in or out of doors.
The boys are extensively engaged in making screws;
the girls have employment adapted to their sex.
The manager of the establishment, and his wife, both have a benign look;
they treat these juvenile offenders with kindness, and appear to rule them by love,
and thereby to subjugate their tempers, and to correct their evil habits.
Great cleanliness and order prevail throughout the establishment.
It is seven years only since it was founded.
About one hundred and fifty have been discharged during that period,
who appear to be entirely reclaimed from their vicious habits.
Many of them are now engaged in business on their own account.
Thirteen per cent, only have relapsed into their former evil courses.
In order to prevent the exposure of their names whilst they are in this establishment,
they are only known by the number given them on their entrance.
The manager has such a peculiarly engaging way in imparting religious and moral instruction,
that some of the inhabitants, even persons in high rank,
attend the meetings held there on First-days, and bring their children with them.
Doctor Julius interpreted to the inmates of that
place what we felt it right to communicate to them.

21st. We visited several families of pious persons.
Woe were particularly interested in that of Semler, Counsellor of State.
He appears to be one who loves the Lord Jesus with sincerity;
and he also manifests his love to man by his great benevolence.
He takes much interest in promoting the religious education of the children of the poor.
Woe were in an establishment under the especial care of the Baron von Kottwitz.^
footnote:[It was the contemplation of this Baron`'s Christian life,
for he taught but little in words,
that first led Tholuck to discover the true Spirit of Christianity;
and it was he who is introduced in his [.book-title]#Guido and Julius,#
as "`father Abraham,`" and uttering those significant words:
"`The work of the Spirit of God at the present time
(1823) is greater than you and most others imagine.
The dawn is appearing of a great revival.
There are hundreds of young men in every place awakened by the Spirit of God.
Everywhere the truly converted are drawn closer together.
Even science is becoming the servant and friend of the crucified One.--Many
an enlightened minister now proclaims the Gospel with power;
many now unknown will come out.
I see the morning, but the day I shall behold, not from hence, but from a higher place.`"
See Tholuck`'s [.book-title]#Guido and Julius;# Martin`'s translation.--p. 121.]
It is for the reception of poor families, destitute of a dwelling,
who can be recommended as bearing a good character.
Here they are provided with such kind of work as they are capable of.
The children are kept and educated till suitable
provision out of the house can be made for them.
Each family has separate apartments,
and there are at present eighty-four families in the establishment,
composed of five hundred and fifty persons.
The Baron extends a Christian care over them.

We were next in an institution for poor children, who are mostly orphans.
It is supported by private contributions.
They are taken in from about three years old.
Many of these children are applied for by private families.
Great attention is paid to place them out with those who will take proper care of them,
and of their education.
If not thus provided for, they are kept till they are fifteen years of age,
during which time they receive an education to fit them for business.
The establishment is for one hundred only.
Many are continually on the list for admittance, and whenever there is a vacancy,
the first on the list is allowed to enter.

In the evening I had another meeting at Gossner`'s,
which my dear friend William Allen could not attend,
being prevented by bodily indisposition, increased by our close engagements that day.
It was a good meeting.
Several who desire to be found in a state of acceptance before God,
through the Redeeming Love of Christ, were present, and manifested brokenness of heart.
Among these were the Countesses Dernath and Von der Groben.
After meeting I told one, who had on his military attire, and is of high rank,
that he must strip off those marks of a man of war, and put on the Christian clothing,
and give evidence that he ia now enrolled under the banner of the Prince of Peace.
He is in a visited and tender state of mind.

22nd. We were in several families; we feel great peace in that kind of service,
when we have greater opportunity to mingle with their spirits,
and to impart what we feel particularly towards them.
In the evening we were at Count Von der Grbben`'s; several pious persons,
generally of high station in life, attended; the Lord was nigh and gracious to us;
we were enlarged in the Gospel among them;
we held forth the terms on which alone we can have a good
hope to be of the number of the Lord`'s disciples;
our hearts must not be divided; we must follow Christ wherever he leads.

23rd. Accompanied by Dr. Julius, our valuable interpreter,
we visited their large public schools, and then went to Von Rudloff`'s,
Major General of the Army; he had called on us several times when we were out,
and an appointment had been made for us at his house.
We had wished to see him on account of the oppressive military laws under
which our Friends at Minden and other places have so heavily suffered.
It appears that, though occupying such a military post,
he yet desires to obtain a part in the kingdom of God.
He had invited a pretty numerous company of both sexes;
and we had a very full opportunity to proclaim to
them the way of life and salvation by Jesus Christ;
describing also the nature of the Christian`'s warfare,
and of the armour he is to be girded with,--weapons which are not carnal,
but mighty through God; several present were greatly broken down.
I cannot see how some of them can much longer wear the carnal sword,
if they abide under the convictions that the Spirit of Truth has made upon them.

In the evening we had a meeting with the French Refugees, or rather their descendants;
I needed no interpreter; there are some visited,
humble spirits among them who are inquirers after the Truth.
Our souls are reverently prostrated before God,
who thus opens a door for us to proclaim his great
and glorious name to the various classes of men,
rich and poor, learned and unlearned.
He is the God and Father of all, and Jesus Christ is the appointed Saviour of all,
and therefore also a manifestation of the Spirit is given
to all to profit withal,--even to obtain everlasting salvation.

24th. By appointment we visited this morning the Prince Wittgenstein;
he is the King`'s Prime Minister; he received us with kindness and openness.
We imparted to him several subjects that have rested
with weight on our minds since our coming to Prussia,
which we wished to be brought before the King for his consideration;
and which the Prince has a full opportunity of doing, as he is daily with the King.
Woe met there, General Boye,
who was with us yesterday at the Major General Rudloff`'s. From
conscientious motives he has retired from a military life;
he finds, he says,
that a private character is more consistent with
the Christian course which he desires to pursue.
The Saviour said,
"`My kingdom is not of this world;`" and the weapons
of the Lord`'s servants are not carnal.
He now devotes a portion of his time to benevolent objects;
he accompanied us in a visit to the prisons and to the hospitals for the prisoners,
and was our interpreter.
We had also in company a young man of a very tender spirit,
who from religious motives is much devoted to visiting the prisoners and the afflicted.
In one of the prisons we met with about one hundred and fifty Jews,
who composed a band of robbers linked together,
but scattered over various parts of this kingdom.
The prisoners are numerous;
this is owing to the very slow process with which the laws are administered,
which is a great injury; there are not any public executions;
we are told that no life has been taken in this way since 1819,
and they have no place abroad to transport their convicts to.

In the evening we had a religious meeting at the house of Eisner;
we felt sweet unity and fellowship of spirit with many that met us there;
I translated into French for dear Allen;
those present generally understood that language.
Eisner is a very useful and devoted man;
besides the many thousand religious tracts that he translates,
or has printed and puts in a way to be distributed through Germany,
he takes journeys himself for the purpose.
In this way he distributed about thirty thousand last year.

25th. At the suggestion of the Prince Wittgenstein, we went to see Kohler,
Minister of the Interior.
The Prince said that he might be of service to us in promoting some of
our views and concerns for the better treatment and accommodation of the
prisoners whom we had found very crowded in small apartments badly ventilated,
so that the air is rendered very foul.
We also thought that their ration of bread is too small, ami the quality of it bad,
so that their countenances bespoke their suffering condition.
We hope now that relief in these respects will be extended to them,
and that by a more speedy administration of justice the
number of those so confined Trill be considerably lessened.

We spent some time very agreeably with Gossner,
who gave us further interesting accounts of his religious labours in Russia.
It was his general practice there,
as it is here also when other religious services do not prevent,
to have a company of pious persons meet with him at his house in the evening;
they spend together a considerable time in silence waiting on the Lord,
thus reducing to practice what he frequently recommends to them in his public communications;
for he believes in the truth of the Scripture assertion,
"`They that wait on the Lord shall renew their strength.`"

In the afternoon the prince Wittgenstein came to see us;
he said that the King was desirous to be with us; but that he was very unwell,
and therefore under the necessity to leave Berlin for his private summer-residence;
he gave us also a kind message from the Crown Prince,
telling us that he regretted not to be able to see us,
being obliged to go immediately to Pomerania, but that the Royal Princess, his wife,
wished to see us tomorrow morning, if we were not otherwise engaged;
he also mentioned the names of several persons to
whom he thought a visit from us would be of service,
both as it regards them and the promotion of benevolence and piety.
In the course of our conversation, allusion having been made to liberty of conscience,
and to the sufferings to which the Menonists and Friends are subjected,
under a military government,
the way was open for us to lay before him the difficulties to which the little
body of professors with us at Barmen are subjected by the clergy and magistrates,
besides the severity of the militia laws;
and we requested him to speak to the King on their behalf.
Ho promised to do so, but as one who knows the world, he further said,
"`I advise you also to speak yourselves to the Minister of Worship,
who has it in his power to give immediate relief to your Friends;
kings often give fine words and promises, but all ends there; you want deeds,
not words.`"
Then he gave us the address of those we may see on these subjects,
with liberty to use his own name in speaking with them;
he appears to understand the objects we have in view,
and the nature of our Christian principles and religious testimonies.
After speaking a few words to him in the love of Christ, he said,
"`I nm convinced that I am not what I ought to be,
but the Lord is pleased to grant me a hope in his Divine and unmerited mercy.`"

In the evening we received a visit from a young man, Leopold de Lucken,
from the Duchy of Mecklenburg Schwerin: he is of a rich family,
and appears to be very modest and of a humble mind; he apologized for intruding,
as he said, upon us;
his religious scruples induced him to withdraw from the meetings of the Lutheran church,
in which he had been educated;
he saw the inconsistency of their various forms and ceremonies
with the purity and simplicity of Divine worship,
as described by the dear Redeemer to the woman of Samaria,
which is to be in spirit and in truth;
neither could he reconcile the salaries received by clergymen for preaching,
or otherwise officiating as ministers of Christ,
with the commission to his messengers to preach His Gospel, "`Freely ye have received,
freely give.`"
As the gift of the Holy Ghost is the free gift of God, and that of the ministry,
and the many other gifts, as saith the Apostle, are by the same Spirit,
he could not see how men professing to be servants of the Lord,
could receive salaries for the performance of the sacred office,
publicly avowing themselves thereby to be of the spirit so sharply reproved by Peter,
in Simon Magus, who thought that the gift of God could be purchased with money,
and consequently, if thus purchased, sold also for money.
Paul, who well knew whence he had received the dispensation of the heavenly gift, said,
"`Woe unto me if I preach not the Gospel.`"
His apprehension of the nature of the Christian baptism is,
that the baptism of Christ is by the Holy Spirit,
which is efficacious to those that receive it;
for it stands not in outward forms or shadows, but in substance;
it renders the recipient of it a new creature,
therefore he could not conscientiously have his children
sprinkled after the forms of the Lutheran Church.
These things, together with some others relating to his religious scruples,
had brought persecution upon him; he had been twice imprisoned,
had several fines of a hundred dollars levied upon him, and now he was banished;
he was obliged to leave his wife behind in a state of bodily illness.
He says that several other persons in the parts that he comes from
are convinced of the same principles with himself,--convictions
which have not been made by any outward instrumentality,
but by the immediate operation of the Divine Spirit, which leads into all Truth,
and by which the things of God are known,
and the right understanding of the Holy Scriptures is given.

26th. Agreeably to the arrangement made by Prince Wittgenstein,
we went this morning to the palace, to the Baron von Schilder, Grand Master of the Court;
from the nature of his office we apprehended that
we should only find in him a refined courtier.
We felt pretty low in our minds,
and our communication to each other was nearly in the language,
"`Can any good thing come out of Nazareth?`"
But very soon after being with the Baron we became convinced that it is unsafe to form
any conclusion respecting characters before we have had an opportunity to know them.
We soon found that as even Nero had among his household disciples of the Lord Jesus,
so there are such also in this place.
The Baron received us with Christian affection and tenderness.
Instead of a haughty spirit, which we thought we should meet,
we found in him lowliness and humility,
even saying that he considered it a favour that the Lord had directed us to him.
Having understood that the Prince Wittgenstein had
recommended us to see the Minister of Worship,
the Baron said he was his wife`'s father, and that he would introduce us to him.
He then accompanied us to the old palace, where the Crown Prince and the Princess Royal,
his wife, reside.
We were immediately introduced into her private apartments, where she received us,
accompanied by one of her attendant ladies only.
She is sister of the present King of Bavaria, and remembers me when, some years since,
I visited him and her father, who was then living.
She made some apology for desiring to see us,
but wished to obtain correct information of our views respecting Divine worship,
and the manner we conduct that solemn act; also respecting prayer, the ministry,
women`'s preaching, the influence of the Divine Spirit on the heart of man, etc.
Soon after she began to make inquiries into these interesting subjects, the Crown Prince,
her husband, came in;
he said he had succeeded in putting off his journey into Pomerania for a few hours,
and availed himself of them to be with us.
As he speaks good English, dear William Allen had a full opportunity with him;
and I proceeded in French to answer the inquiries of the Princess,
which appeared to proceed from a mind under religious exercise,
and seeking after the Truth.
This desire after the knowledge of the Truth began in her years since,
when I was at Munich with the King, her father, and the Crown-Prince, her brother.
She had also heard of the religious meetings I had then,
which were attended by many of the people at Court.
Here, again,
by the Countess Von der Groben and others she hears
much of the spiritual doctrines held forth by Gossner,
and of the seasons of silent retirement that they have with him.
My mind was enlarged in the love of Christ,
to give an answer to the several inquiries of the Princess.
I drew her attention to the teachings of the Divine Spirit,
which is ever near the believer in Christ, to direct and instruct him,
to help us under all our infirmities, and to comfort us under all our trials.
Her heart was open to receive the words of encouragement
and consolation given me to communicate to her.
Her spirit also was very tender.
The conversation then became more general, with the Prince,
particularly on the subject of liberty of conscience,
and our Christian testimony against war, consistent with the precepts of Christ,
that we should love one another, even our enemies, as He has loved us.
He promised us to use his influence to promote this,
and he hoped that the cruelties exercised by military laws against our Friends,
or others, would never be enforced again.
After a time of solemn silence, feeling my mind constrained by the power of Gospel love,
I imparted to them my soul`'s concern for them, that they may so live in the fear of God,
and maintain the faith in our Lord Jesus Christ,
that after witnessing the blessing of preservation from the many
snares and temptations attending their high stations in life,
they may, through the Redeeming love and mercy of God in Christ Jesus,
become heirs of his everlasting salvation.

On parting, the Prince said that he regretted he could not be longer with us,
that the King, his father,
regretted also that his bodily indisposition prevented him from seeing us,
remembering the visit that we both had made him, when he was in London,
and that he would not fail to impart to him what we had said,
especially on the subject of liberty of conscience,
and the severity of the military laws, which, though not enforced at present,
yet are not repealed.
We told the Prince and his Princess,
that they must expect themselves to have tribulations,
if they were sincere in their desires to live a godly life in Christ Jesus; for,
if they did so indeed, they could not please the world,
and if a man will please the world, he is at enmity with God; further, we told them that,
if they were true in their desires to be found followers of the Lord Jesus Christ,
they must not stumble at the cross, but follow Him in the path of self denial.
We parted from them in Christian affection.

That afternoon we had a meeting with a numerous company,
who collected for the purpose at Gossner`'s. We had requested that the invitation
might be especially extended to such as are known for their piety.
We sat together a considerable time in solemn silence;
truly those that are joined to the Lord are of one spirit; we were engaged,
as being baptized together by the One Spirit, in offering to God spiritual worship;
and as worship is not performed in silence only,
but also by the offering up of every sacrifice and gift of his preparing,
whether it be by the ministration of his glorious Gospel,
or the offering at his sacred footstool of vocal prayers and intercessions,
thanksgivings and praises,
the Lord was pleased to call upon dear Allen to proclaim the truth of
his Gospel of life and salvation among that interesting congregation,
and to give us access to the place of prayer, when, through the Spirit,
living praises were offered up to God, and to the Lamb.
It was truly consoling to behold so much of the oneness of spirit among that company,
composed of such as are poor in this world,
and of many others of the highest rank in life,
but who all witness the truth of Christ`'s saying, "`One is your master,
and all ye are brethren.`"
There are in this city many pious characters in high life, of the nobility so called,
and from them I understand,
that many similarly minded are to be found throughout this kingdom,
especially in that section of the country which extends towards and along the Baltic Sea.
What a wonderful change has taken place in this palace and those that frequent it.
During the reign of the present king`'s ancestors,
dissipation and infidelity prevailed in a high degree, and received every encouragement;
surely this is the Lord`'s doing.
His works loudly proclaim his praise.

Among some interesting persons that we were with this day,
was a young man awakened very lately to a sense of his fallen and sinful state,
and brought to the knowledge of that salvation which is through our Lord Jesus Christ.
He appears determined to forsake all to follow Christ in the way of regeneration.

We went to the Baron Altenstein, at Shoenberg, the Minister of Worship.
He is now an aged man;
he has for many years occupied important stations in the government,
and was during some years Minister of Finance.
We found him, as represented to us, a serious and pious man;
he received us with Christian kindness and affability.
He appears to be acquainted with the religious ground
on which our Christian principles are founded,
particularly that against war.
He even said that a nation that possesses men convinced of such peaceable principles,
and who maintain these with faithfulness, enjoys great advantages;
its security is thereby more firm than armed forces can render it.
Further, he said,
that a government possessing such men who conscientiously
and faithfully maintain their allegiance to God,
the King eternal and immortal,
has the assurance that they will with equal faithfulness adhere
to every other law of the nation not opposed to that of God;
whereas,
no confidence can be placed in the allegiance of
those men who are void of the fear of God,
and whose habitual conduct is in violation of his Divine precepts.
We told him of the sufferings that some of our Friends had
endured at and about Minden under the military laws,
and the threatened execution of these on some at Barmen.
He told us that the subject respecting the military
law came not under his immediate notice,
but that he would use his influence so as to prevent
further proceeding in the case at Barmen;
"`There is no law,`" said he,
"`as yet that protects your Friends,`" but he hoped one would be made;
he had always been opposed to the molestation of
men who had religious scruples against bearing arms.
In relation to the sufferings of our friends at Barmen,
on account of the solemnization of their marriages,
or their religious scruples in not taking off their
hats when summoned to appear in Courts of Justice,
or others of their testimonies, he promised to attend to it immediately,
as that came under his own notice.
Speaking of the King, the Baron said, that he was under very sore distress of mind,
during those cruel wars that had ravaged Germany and Prussia to a great extent;
he was conscious that it was the Lord,
and not the arm of flesh that had delivered him from the iron yoke of Buonaparte, and,
at the time, in the gratitude of his heart,
he vowed to make returns unto the Lord for the mercy and favour extended to him,
and that ever since he had been silently but uniformly endeavouring to perform his resolution;
that it was owing to this that such a reformation had taken place in the palace, where,
in years preceding, so much dissipation had prevailed.
He said also,
that the silent example set by the King had greatly contributed to cherish morality,
piety, and virtue in the people, especially in those about him.
Our intercourse with this valuable aged man has been
of an interesting and satisfactory nature;
before we separated, the Lord gave us access together to his sacred footstool,
where prayers, adoration and praises were offered up vocally unto him.

26th. We had another solemn meeting at Gossner`'s;
many met us this day that we had not been with before.
We have an interesting letter from the General, who is the Adjutant of the King;
we had heard so much said in his favour by some of our pious friends,
that we wished to have seen him; it appears that he also desired to be with us;
but as the King has gone into the country, the General, who is his constant attendant,
has had to go with him;
his letter evinces that his mind has become awakened
to a sense of the importance of religion,
and that his inquiry is, li What shall I do to be saved?`"
We have answered his letter.
O that the work which the Lord by his grace,
has begun in the hearts of many here may be carried
on to perfection! that they may not only know,
but also obey the Divine will.
Were this the case, I believe that many in this place, and throughout this kingdom,
would soon beat their swords into plough-shares and their spears into pruning-hooks,
and would neither learn nor wage war any more.

27th. We were with Eisner,
and made arrangements for printing five thousand
copies of the "`Importance of Religion "`in German,
and the same number of the "`Scripture Lessons,`" that we prepared in Russia.
We find the former very useful for distribution in this land,
and the Scripture Lessons are intended to be introduced into their public schools.
Their Tract Society concludes to issue double that number.

Apprehending that a release from this place was granted,
we went once more to see the Prince Wittgenstein;
he told us that the King left Berlin very reluctantly without seeing us,
but that he hoped that a few days in the country might so
recruit him as to enable him to return to Berlin,
and he had queried if we might not be detained here till his return;
we gave proper consideration to this,
but told the Prince that we felt best satisfied to proceed to the
further services that may be required of us in other places,
and requested him to express to the King our earnest desire that,
through an increase of fervency of soul, and watchfulness unto prayer,
he may witness the guidance and quickening influence of the Divine Spirit,
both to instruct him in the right way of the Lord,
and to strengthen him in all things to do his will,
and to seal by every sacrifice required the covenant
that he made in the days of his distress,
and also to perform unto the Lord all his vows.
The Prince took his leave of us in much tenderness of spirit,
expressing his desire that the Lord may bless our labours of love towards them,
and bless us also and all ours.

We went once more to the Countess Von der Groben`'s; the Count left Berlin,
in company with the Crown Prince, immediately after we left the palace.
We had a contriting parting opportunity with her;
she is a rare example of piety and spiritual-mindedness.

Several of the beloved people came to our inn in the afternoon,
with whom we mingled once more in precious communion of spirit;
then recommending them to God and to the word of his grace,
which is able to build us up and to give us an inheritance among them that are sanctified,
we took a solemn and probably a final farewell of one another.
Several of them accompanying us, we went to the post-house, and at six p.m.,
we set off for Wittemberg.

--
