== Chapter LIII.

Fourth Visit to Europe

Wittenberg--Halle--Weimar--Leipzig

Halle, Weimar, and Leipzic, places of peculiar though very different interest,
next attracted their attention, and they spent some days in each.
On their way from Berlin to the first, they passed through Wittemberg,
the cradle of the Reformation, and the scene of "`Luther`'s development,
and Luther`'s work.`"^
footnote:[D`'Aubigne`'s [.book-title]#"`History of the Reformation.`"#]

"`It was here,`" says Stephen Grellet,
"`that he first engaged in the great work of the
Reformation,--from hence it spread so widely,
and shook the strongholds of Popery to their very foundation.
Portions of the monastery which was his abode are still standing.
In front of it they have erected a statue of him, to perpetuate his memory.
Much better would this be done,
by all those who commend his Christian labours endeavouring,
under the influence of the Divine Spirit, to build upon the same foundation that he did,
and to love and exalt the name of the blessed Redeemer, the Lord Jesus Christ,
as it was his concern to do,--and in the doing of which he loved not his life unto death,
but was ready to suffer and die, for Jesus`' sake.`"^
footnote:[To some readers it may be interesting to
see the last words of his noble defence at Worms:
"`Unless I am convinced by the testimony of the Scriptures or by clear
reason (for I do not trust either in the pope or in councils alone,
since it is well known that they have often erred and contradicted themselves),
I am bound by the Scriptures I have quoted and my
conscience is captive to the Word of God.
I cannot and will not recant anything,
since it is neither safe nor right to go against conscience.
Here I stand, I can do no other.
God help me.
Amen.`"]

We tarried here a short time, and then pursued our journey to Halle in Saxony.
We had a trying night.
The roads were rough, and we had crowded, uncomfortable seats.
My lame shoulder gave me great suffering,
but our minds were clothed with such a sense of gratitude
to the Lord for the consolations bestowed upon us in Berlin,
and the favour to have been able to mingle with so many who love the Lord Jesus,
and others who, we believe, are serious inquirers after the Truth,
that thanksgiving and praise were our silent engagement most of that night.

We arrived at Halle about noon, the 28th. The Lord,
who doeth all things well according to his Divine purpose
which we poor short-sighted mortals cannot fathom,
was pleased to prepare another dispensation for his poor servants;
for we soon became sensible of the darkness that covers the minds
of many of the people in this place,--the seat of knowledge,
as it is termed by many,
because of its renowned University;--the greatest part of the professors,
men of great learning, are unbelievers in the saving truths of Christianity,
and teach their pernicious doctrines to the numerous young men sent to this place,
who return to their distant homes with minds poisoned by Socinian principles, and,
in their human reason, exalted above the simplicity of the Gospel of Christ.
I lament bitterly over them.
I have felt as if my soul was made sorrowful, even unto death.
My sorrow is also increased by letters from America,
bringing the affecting tidings of the spread of the cholera in the United States,
particularly in New York and Philadelphia;
informing me also of the illness of my beloved wife and daughter;--but
surely the Lord is a strong and sure refuge in time of trouble.
He is the Hock, and there is no unrighteousness in him.
If my soul is sinking under the weight of oppression, let it be,
O Lord! to sink only to come through the deeps to thee,
my rock and sure foundation.--To thee, my life, my all has been offered up;
into thy hands, and with resignation to thy sovereign will,
the whole of my offering is renewedly made, by thy assisting grace.

This evening, the Lord sent us comfort, blessed be his name! by a visit from F. Tholuck,
who is one of the professors at the University here,
but a man of a totally different spirit from the generality of them;
he is a full believer in the dear Redeemer, the Lord Jesus Christ, in all his offices,
according to all the great truths revealed to us by Divine Inspiration,
and contained in the Holy Scriptures.
In opposition to his fellow-professors, he teaches these faithfully,
in his chair as a professor, and from the pulpit also, as a minister of Christ,
and he adorns his doctrine by a consistent life and conversation; he is well versed in,
and teaches the oriental, and many ancient languages; but,
so far from assuming anything because of his attainments,
meekness and humility are his covering.
He is acquainted with Friends`' religious principles.
He resided at Berlin when our dear friend Thomas Shillitoe visited it.
Tholuck acted as his interpreter in the meetings he had there,
as he understands and speaks English well.

29th. We visited this morning the spacious Orphan Asylum, founded by Franke,
celebrated for his piety and extensive benevolence.
Its fruits will extend to many generations.
Numerous are those who yearly partake of the benefits of it.
This establishment is a little town of itself.
They have at present only one hundred orphans, boarders on the premises;
but they have in their schools above two thousand pupils, of various ages.
We had some religions services among these.
They have also a large printing office, in which, since the days of Franke,
above four millions of Bibles have been printed, also a great many other volumes,
of the classics particularly.
Their dispensary for the use of the poor is well supplied,
and their large collection of curiosities sent here from the East Indies, South Seas,
etc., etc., by the missionaries that have gone forth from this establishment,
is of great interest.
The idols of those several nations display their gross darkness and superstition.

At eleven a.m., we met with a number of the young men who study under Tholuck;
they appear to have received, as into good ground,
the seed of piety sown in their hearts, which Tholuck is endeavouring to cultivate;
they meet with persecution here;
they are reviled by the students under the other professors,
but these sufferings appear to be blessed to them;
they see what are the fruits of the spirit of antichrist.
We had a satisfactory religious season with them,
and are comforted in the hope that they will bring forth fruits to the Lord`'s praise.
Tholuck wished to bring to us two very interesting persons,
but they are out of town at present;
one of them is under sore persecution by the Socinian party in the university;
he is a member of the civil tribunal, but is hated by his colleagues,
in consequence of his uprightness and firm adherence to Christian principle.
There is every reason to apprehend that he will be shut up in a fortress,
unless the King interferes,
which it is hoped he will do when a representation of the case is made to him.
Tholuck has an arduous path to tread,
but the Lord supports him amidst his numerous difficulties; his enemies,
like those of Daniel formerly, can find no occasion against him,
save concerning the law of his God.
He has from two to three hundred young men,
steady attenders at his lectures at the university.
He has the consolation to hope that every year from thirty to forty
of these young men go from the university to various parts of Germany
thoroughly established in sound Christian truths,
giving evidence also that they love the Lord Jesus Christ in sincerity.
He has given us the interesting account of a young man named Hoffman, who,
about twelve years since, went to Berlin, from a sense of religious duty as he thought,
to study to become qualified to go as a missionary to the East Indies.
He went accordingly to a mission-house, where he manifested great fervour and piety;
some of his fellow-students, who had taken Barclay`'s Apology out of their library,
began in his presence to make their comments;
some of them spoke with great contempt of the Christian doctrines it advocates;
this awakened the curiosity of this young man,
more particularly to examine for himself what those doctrines were;
he perused Barclay with great attention;
his interest was more and more excited as he went on,
and he became so thoroughly convinced of the soundness
of the great Christian truths treated by him,
that he told his teachers that his views were changed;
his mind was opened to see the nature of the Christian ministry,
and that the qualifications for it, as well as the call thereto must be from God alone,
through his Divine Spirit.
His teachers, who were much attached to him,
endeavoured to convince him of what they thought his errors,
but their arguments tended only,
by further examining the subject with the Holy Scriptures
and communing with his own heart,
to establish him more firmly in his views.
He left Berlin and soon after came to America to endeavour to be among Friends;
but he found great difficulty, as he did not understand English,
and was an entire stranger.
As he had but small means to support himself, he concluded to learn a trade;
during his apprenticeship he studied the English language;
he attended Friends`' meetings,
and became more thoroughly acquainted with their different Christian testimonies.
He had it under his serious consideration to join them in outward fellowship,
as he felt he had already done in spirit;
but about that time it was suggested to him that as the Lord had been pleased
to bring him to the knowledge of such great and important Gospel truths,
it would be proper for him to consider if the light, now shining in his heart,
was not designed to be put on the candlestick in his own nation,--that perhaps to him
was applicable the language of Christ to the man on whom his Divine power had been exerted,
"`Go home to thy friends and tell them how great things the Lord hath done for thee.`"
This brought Hoffman under very serious thoughtfulness;
the result was that he returned to Germany; he came back to Berlin,
and followed his trade of shoemaker for a livelihood.
He led for a while a very private life;
yet his light shone with such brightness that it could not be hid;
men of piety in Berlin took notice of him;
his humility and genuine piety made deep impressions upon them; they beheld,
under the humble appearance that he had assumed as a man, the dignified Christian.
Among those who first became acquainted with him, were Tholuck himself,
and Justice Folke, a pious and valuable man,
who in the year 1796 was very useful as an interpreter, and in other respects,
to our late and valuable friends, David Sands and William Savery,
who were then at Berlin on a religious visit.
Folke speaks of those dear friends with much respect and affection.
Hoffman died about three years since;
he continued to the last an eminent and bright example of piety;
by example and precept "`he proclaimed how great
things Jesus had done for him,`" and many did marvel.
He departed this life with a countenance beaming with heavenly joy,
and testified of the love and mercy of God in Jesus Christ his Redeemer,
rejoicing in the hope of his salvation.

Tholuck was once more with us before our departure,
and told us how very tenderly the hearts of some of the young men, his students,
were affected since the religious opportunity we had with them;
may they keep low and watchful.

30th. We left Halle that afternoon, and travelling during the night,
we came to Saxe-Weimar this afternoon.
I had for years felt my mind strongly drawn to this place.
The Duke and Duchess were persons of great benevolence and piety;
they were much tried at the prevalence of anti-Christian principles in these districts,
and to a lamentable extent, throughout most parts of Saxony.
My spirit is greatly pressed down under this dark spirit,
so much so that though now here, I have been almost tempted to take my flight;
but I am sensible that it is the love of Christ that has brought us here.
He may have a service for us, and should it be only silently to suffer for his sake,
his will be done.

31st. We were with Counsellor Peucer,
who takes an interest in the spreading of the Scriptures of Truth,
and thereby evinces that he is a Christian believer.
We were also with Doctor von Froriep, who knew my dear William Allen in England;
he is the physician of the present Grand Duchess; she had heard of our arrival at Weimar,
and he came to tell us that she requested that, if our time allowed,
we would go and see her at twelve o`'clock, at the palace here.
We accordingly went at the time appointed; she was much affected at meeting with us,
for it brought her to feel afresh the great bereavement she has
sustained by the decease of very near and beloved relatives that
she knew we had been with--the Empress Dowager of Russia,
her mother; the Emperor Alexander, her brother; the Empress Elizabeth, his wife;
and the Queen of Wirtemberg, her sister.
She was much attached to them;
the natural dispositions of her brother and sister were similar to her own, and,
besides this,
there existed between them a religious fellowship
which is stronger than the ties of nature;
her son, an only child of about fourteen, was the only one present with us;
he is an intelligent and amiable youth.
Our interview was of a religious character,
and she appears to like to dwell on serious subjects;
she also takes much interest in the promotion of benevolent objects;
besides giving her care and support to the various
establishments formed by the late Duchess,
mother of the Duke, her husband, she has formed others herself.
On parting, she took us by the hand in an affectionate manner,
requesting that we would visit her again before our departure from Weimar.
We had not reached the out door of the palace when Doctor Froriep overtook us
to give us an invitation from the Duchess to dine with her the next day;
we excused ourselves, stating that we should prefer, if it was agreeable to her,
to pass a little time with her in a more select manner than could be done at dinner.
On receiving this information,
she sent us an invitation to take tea with her at her more private palace of Belvidere.

Ninth month, 1st. Yesterday afternoon and today,
we visited a number of the public institutions, schools, hospitals,
the poorhouse and prisons.
The schools are under good regulations;
such of the children of the poor as appear to have
talents for it and suitable disposition of mind,
are sent to another school, where their education, which is gratuitous,
to qualify them for schoolmasters and mistresses, is completed;
many of these are now at the head of schools in various parts of the country:
in the choice made of such teachers,
care is taken to see that they possess moral and virtuous habits,
as well as literary qualifications.
The Grand Duchess visits the establishment frequently,
properly considering it as one of vital importance for the rising generation;
it was founded by the late Duke,
and appears to be the most complete of the kind that I have seen.
We were gratified in a visit to a retreat, formed by the present Grand Duchess,
for aged servants who have no dwellings or comfortable places of their own;
here they are provided with every accommodation that
their age or bodily infirmities may require;
they have their separate, clean chamber, an easy chair, suitable food,
clothing and many little comforts.
Another establishment, on nearly the same footing, is for the aged and infirm poor.
We found religious tenderness in some of the inmates of both these places.
We were in a girls`' School of Industry,
attended in turn by the young females who are about the Grand Duchess;
care is taken of their moral and virtuous education,
also to have them qualified for business as servants, or in some kind of trade;
attention is paid to them after they go out to places,
and if at the end of three years they have behaved well, they receive a sum of money,
and, should their conduct deserve it,
another sum is given them at the end of the next three years,
together with a public badge of merit.
Something of the sort is also done to discharged prisoners,
to encourage them in virtuous and moral lives.

At about six p.m., we rode to the Palace of the Belvidere.
It is about two miles and a half from Weimar.
The way to it is through a beautiful park, in which deer, pheasants, partridges, hares,
etc., abound, and as they do not appear to be molested, they are very tame.
The Duchess received us in her drawing-room.
For a short time we were by ourselves; but when tea was brought in,
four of her attending females came in with her son and four men,
with whom the conversation became general.
The Duke, her husband, is absent from home at present.
After tea we had a religious opportunity with them,
and were afterwards mostly with the Duchess alone.
She appears to have been taught in the school of affliction,
and has learned also under the teachings of the Lord`'s Spirit.
Thus she has obtained & portion of that knowledge which it is life eternal to possess.
Our spirits were contrited together under the sensible
evidence that the Lord`'s presence was with us.
He enabled us reverently to how down together at his sacred footstool.
We declined staving to supper; our object in a private interview was accomplished.
We retired about nine o`'clock, with peaceful minds.
We trust also that the Duchess will be strengthened to exert, with fresh courage,
her influence with the Duke, so as to put some check on the endeavours of the Socinians,
both by private priestly influence and the pulpit,
to disseminate their anti-Christian doctrines.

2nd. We had this day some religious opportunities
in which we preached Christ and him crucified,
delivered for our offences and risen again for our justification;
a doctrine which continues to be a stumbling-block
to the Jews and foolishness to the wise.

3rd. We set off for Leipzic early this morning,
and travelled over very extensive plains highly cultivated,
and on which an immense quantity of grain is raised; a forest-tree is hardly to be seen,
but there are excellent fruit-trees; the public road is planted with rows of them,
alternately apple, pear, plum or cherry trees,
and at suitable distances there are seats for foot-travellers and fountains of water.
But this beautiful,
fertile country conveyed to our minds sensations of gloominess and distress,
for the fertility of parts of this land may be particularly owing to the floods
of human blood by which these plains have been repeatedly drenched for centuries;
here battles have been frequently fought.
In the last war between the French and the Allied Army,
many thousands of men and horses fell a sacrifice to the ambition of man;
here and there small monuments stand erect,
proclaiming where some of their noted men fell and were buried.
A part of the land over which we travelled is, however, hilly and has deep ravines;
they have there salt works, and in some places by the sides of the hills are vineyards.
Leipzic is a place where great champions of infidelity have their seats in the university;
but here, as at Halle, there are a few preserved,
who are the Lord`'s instruments in counteracting the evil and the poison:
to these our minds were particularly drawn in Christian tenderness and affection,
with desires that the Lord may enable us to encourage and
strengthen them under their various difficulties and trials.
Soon after our arrival we were with Professor Lindner,
who is one of those pious and decided characters on the side of Christ and his truth;
he appears to have a right sense of the nature of the religious
engagement that has induced us to come to this place,
and has welcomed us with warm Christian affection.
Understanding what class of men we wished to be with,
he has undertaken to have such invited to meet us at his house this afternoon.

We found there a larger number than we anticipated, among others were Senator Volkman,
for whom we had a letter of introduction, Professor Seyffartb,
Recklam and others of that class; also a number of young men,
students under these piously-minded professors.
We had a satisfactory and instructive season together,
the Lord giving us to feel his baptizing power.
He also enabled dear Allen and myself to impart to
them the word of encouragement and tender counsel.

We visited various of their public establishments, as the orphans`' asylum, poor-house,
house of correction, etc.
Reeklam was our interpreter.
This city is well built, the houses have several stories;
it contains about forty-five thousand inhabitants, five to six thousand of whom are Jews;
it is surrounded by high walls and strong fortifications; but these,
instead of displaying, at present, the warlike aspect that they did years past, have now,
instead of guns, beautiful shrubberies, flowers and shady walks,
and the many breaches made during the wars are generally repaired.
During their renowned book fairs, many thousand strangers are in attendance;
they come from various parts of the world, from Persia, Arabia, Turkey, Russia,
and every part of Europe;
no where else can be found such a collection and variety of books.
In passing through the streets I was surprised to see the
very many large storehouses occupied by booksellers;
some streets are entirely devoted to them.

On the 6th, in the afternoon, we had a good meeting at Doctor Hahn`'s,
one of the professors of the university.
He is a man of a strong mind, improved by grace,
and brought down into the valley of humility, by the power of Truth,
and the softening influence of heavenly love.^
footnote:[Kahnis,
in his [.book-title]#"`German Protestantism,`"# calls him "`a man of truly evangelical love and gentleness.`"]
As he has learned in the school of Christ,
it is his endeavour to direct his pupils to Christ,
and to press on them a close attention to the teachings and guidance of his Spirit.
In the evening we had another meeting at Professor Lindner`'s.
It was intended chiefly for the young men,
students at the university under these pious professors.
It was a tendering season,--many of these young men
publicly testify that they wish to be Christians,
by attending those who preach and exalt the name of a crucified Saviour and risen Lord,
and not those professors who set up human reason,
and after whom the greater part of the students flock.
These few receive frequent molestation,
whereby they have an opportunity to show forth what
progress they have made in the Christian life.
During the meeting, some of them were broken into tears.
Professor Lindner, whilst interpreting for us, was also much affected.

7th. Early this morning we received a visit from
three of the collegians before going to the university.
They wanted to open to us their religious exercises and straits respecting several subjects.
We endeavoured to extend suitable advice to them, and proper encouragement.
They appear to be very sensible that the things of
God can only be known by the Spirit of God.
We therefore pressed upon them the necessity to retire often in their closet,
to wait for, and feel after the manifestations and teachings of the Divine Spirit.
They told us that several of them meet together frequently,
thus silently to wait upon the Lord,
or at seasons to unite together in putting up their prayers to Him.
They said that there are several small companies among them, of eight or ten,
who meet together for that purpose.
One of these young men has much interested us.
His father was poor and blind, and he, when a child, went about oegging,
to provide for his father`'s necessities; but, as often as he could,
he attended the public school in his village.
He so applied himself to study, that,
notwithstanding his many difficulties and his poverty,
he acquired sufficient learning to fit himself for entering the university.
Since his father`'s decease, by a little assistance he has succeeded in gaining admission.
He is now considered one of the best scholars they have;--but
he is not less proficient in the school of Christ;
his piety and general good conduct render him a bright example to all his fellow-students.
He lives here in much poverty; we found out that his lodging place is in a garret;
his bed a little straw, with but scanty covering in winter;
his food so insufficient that he looks much emaciated.
We thought him to be one of the Lord`'s poor,
and our hearts were drawn to him with warm affection and sympathy.

The day was spent in visiting pious persons,
and in having a meeting with others,--in all of which it was given us
to visit and to water the seed that the Lord has planted in their hearts.
We encouraged them also to abide with faith and patience in the tribulated path,
ever keeping in mind that the end for which tribulation is dispensed,
is that it should work patience,--patience, experience,--and experience, hope,
which maketh not ashamed, the love of God, through Jesus Christ,
being shed abroad in the heart.
