== Chapter LVI.

Fourth Visit to Europe

Bavaria--Wirtemberg

Though favoured to obtain a peaceful release from the Austrian capital, the darkness,
superstition and bigotry which so much prevailed left a sorrowful
impression upon these devoted servants of the Lord Jesus.
They could not rejoice when the ways of Zion mourned;
they could not but be partakers of the "`sufferings of Christ,`" where the light
of the Gospel of "`His glory`" was so much obscured by unbelief or misbelief,
and the spirit of the world.
They set off for Bavaria on the 26th of Ninth month, and travelling night and day,
arrived at Munich on the 29th. Stephen Grellet writes:

Munich, 29th. Our way was for some distance up the Danube, over a very fertile country.
We had the Austrian Alps on our left, covered with perpetual snow;
we had beautiful views before us.
Many monasteries are to be seen, inhabited by that kind of monks who live luxuriously,
whilst the poor cultivators of the land are greatly oppressed,
not in their outward circumstances only, but in their consciences also.
We felt much for some of these, but no waj opened for having any intercourse with them.
Near Linz there is one village where the whole population have
become convinced that Jesus Christ is the only Saviour and Redeemer;
consequently they have turned away from the priests.
Some of the Popish priests whom I visited some years since,
and who had renounced their errors, resided in these parts;
fruits of their pious labours now appear; they have suffered great persecution;
others also are now made willing to suffer for Christ`'s sake.
The Bishop of Linz is represented as being a man of a bitter spirit,
that breathes out cruelty;
in these acts he is prompted by a bull lately issued by the present Pope against
those poor sheep of the Lord`'s pasture who have their dwellings among wolves.
O when will the meekness and the gentleness of Christ
become the clothing of men`'s spirits,
of those especially who profess to be ministers of the Lord and priests of our God?

Many changes have taken place in Munich since my last visit;
the unsparing messenger of death has removed many of those
pious persons with whom I mingled here in religious fellowship,
to a better world, I hope.
The then Crown Prince is now King; we cannot see him, as he is absent at present;
I can only by writing impart to him my continued solicitude on his account,
that the love of Christ may have free course in his heart,
so that he may partake of the blessing of salvation in time and in eternity.

We were with Frederick Roth,
President of the Central Consistory of the Protestants in Bavaria;
the account he gives us of the removal from office of all those of their
clergy who had embraced or promulgated Socinian doctrines is grateful.
Tholuck, of Halle, was very useful in promoting this; he was at Munich a few years since,
on his return from Rome;
one First-day morning he attended the Protestant place of worship,
where their great and learned Unitarian preacher
expounded their principles at great length,
before a very numerous congregation.
Tholuck was requested to preach that afternoon; he tried to excuse himself,
having arrived in Munich that morning early, after travelling some nights;
but from a sense of Christian duty he consented.
The congregation in the afternoon was fully as large as in the morning;
Tholuck went over the several heads of the subjects
that had been treated upon in the morning,
and answered them so fully and clearly that the whole assembly
became convinced of the truth that Jesus is the Christ,
the Son of God, and the only Saviour.
Their great preacher was so confounded that he has not dared since to lift up his head.
The same work of reformation went on throughout the other Protestant churches in Bavaria.

We have been with several of the pious people here, that I visited in years past;
and it is truly grateful to meet with such as have retained the tenderness
of spirit which was conspicuous when I was with them before,
and to find that some of them have made further advances in the Christian life.

30th. Understanding that the Prince Oettingen Wallenstein, now Minister of the Interior,
etc., is the same young and tender-spirited Prince that I was with a few years since,
we went to see him.
He soon recognized me.
To my soul`'s comfort I found that the dew of his youth is yet upon him.
He continues in a tender state.
He feels the necessity to anoint with oil the pillar,
which in the days of his youth he raised up unto God.
It is his concern to fulfill with religious faithfulness
the duties that his important station requires of him.
Accordingly he uses great efforts to repress vice and immorality throughout the kingdom,
and to encourage religion and virtue.
He extends a care over the moral and religious education of the children,
of the poor particularly.
The reform of the criminals also claims his attention,
and he is very specially careful to see that liberty
of conscience be allowed throughout the kingdom.
It is a blessing indeed,
when men in power are thus endeavouring to promote
the glory of God and the welfare of man.
We had a precious and solemn season before God with the dear Prince.

Tenth month,
2nd. Yesterday and today we had several private religious
opportunities with pious persons on whom we called,
or who came to our inn to see us.
Many of these I had known during my former visits here,
and they appear to continue in a tender frame of mind.
We had also a meeting with a number of them, who collected for the purpose.
We had likewise a religious opportunity at the British Ambassador`'s, Lord Erskine,
with whose father dear William Allen was well acquainted.
Among the interesting visits made us, was one by the Baron Raflin.
It is about twenty years since I became acquainted with him.
He was then a lovely plant.
He appeared in earnest, the love of God constraining him to join himself to the Lord,
in a perpetual covenant never to be broken.
He tells me that he maintained his integrity for some time after our separation;
but the tide of worldly prosperity rose high upon him;
he was advanced to important stations in the Government; riches also increased;
under these changes his heart became lifted up,
and in the same proportion as he pursued the ways of the world,
he departed from the way and the love of God; but the Lord,
in his great mercy and compassion, did not forsake him;
he extended over him his fatherly rod; he visited him with heavy affliction;
took away his idols, and, by his refining fire kindled in his heart,
removed the dross from it, and rendered it soft, as in former days.
With tears the dear man unfolded to me how graciously the Lord has dealt with him.
Now he lives, with his family, on an estate about twelve miles distant from the city,
where he spends his time in retirement from the world.
He heard that I was at Munich,
and his Christian affection prompted him to come immediately to see me.
His wife and oldest son are likeminded with him.
They sit down daily together with the younger children to read the Scriptures,
and then in silence and with reverence to wait on God,
for a qualification to worship him in spirit and in truth,
and also for the renewal of their spiritual strength, through his Divine Grace,
so that they may be preserved in his fear,
and enabled to walk in the way well pleasing to him.

We were likewise comforted with the young Baron Freyberg, and his tender-spirited wife.
They appear sincere in their desire to serve the Lord.
One of the King`'s Ministers has been twice with us.
He is one of those that I mingled with during my former visits here,
and who continues to evince a love for the Truth.
The Prince Oettingen Wallenstein came this evening to our inn,
where it was thought we might be more privately with each other, than at his palace.
We spent about three hours together.
His Christian protection of those Roman Catholics who have seen the errors of Popery,
shelters them greatly from the persecutions they would, otherwise, be subjected to.
Several of their priests and nuns continue to make public confession
that the Lord Jesus Christ is their only hope of salvation,
and that they consider and acknowledge Him, and not the Pope,
as the only Head of the Church.
Through Him alone they consider that prayers are to be made to God the Father;
but not to the Virgin Mary and to the saints,
whose memory however is very precious to them,
and whose lives and examples they desire to follow, even as they followed Christ.
There are also many of the people who turn away from Popery.
The Prince,
understanding that we proposed to visit some of the villages on the Donau-Moos marshes,
where many persons have been convinced of their former errors,
has not only encouraged us to go there, but has also sent for the Baron Baader,
who speaks good English, to accompany us there, and act as our interpreter.
Previous to our separation, we had with the dear Prince a contriting religions season.
He was greatly broken in his spirit.
He hardly knew how to part from us.
He took us several times in his arms, with tears in his eyes.
May the Lord strengthen him, by his grace,
and preserve him faithful to his Divine will unto the end!
My spirit is reverently bowed with gratitude before God,
in being now permitted to mingle again with a few among
the poor and those who have their dwellings in palaces,
whom he has rescued from the corruptions that are in the world,
and whom he enables to approach his sacred presence,
with broken hearts and contrite spirits.

3rd. Accompanied by the Baron Baader, we left Munich early in the morning for Neuburg,
and continued in that neighbourhood till the 5th,
visiting many of the villages on the Donau Moos.
This was an extensive, barren, swampy tract of land, which has been, of latter years,
drained and brought into a state of cultivation;
the land thus recovered is about forty miles in circumference.
Some of the villages are settled by Roman Catholics; others by Protestants;
one or two by the Mennonites.
Many of the Roman Catholics have seen the errors of Popery.
In the largest village,
nearly the whole of the inhabitants have turned away from the church of Rome;
and what is remarkable, this village, Carlshuld, was the most dissipated;
revelling and drunkenness were prevalent among the people.
Lutz, the Romish priest among them,
became uneasy with many of the anti-Christian doctrines
and practices of the church of Rome;
he saw their inconsistency with the Holy Scriptures,
which he was induced to peruse with greater attention,
when the truths of the glorious Gospel of Christ
became more and more unfolded to his view;
with this his love to God and to our Lord and Saviour Jesus Christ increased,
and his heart was also enlarged in love and religious concern for his parishioners.
These became tenderly affected by the new doctrines
now proclaimed to them by their pastor,
and the more so, as his life and conversation adorned what he preached.
This, together with the convictions of the Lord`'s Spirit, the faithful witness,
wrought so powerfully on their minds, that a general convincement took place among them,
and a reformation also, so that morality and virtue became some of the first fruits,
proclaiming that they had turned from darkness to light,
and from the power of sin and Satan to God.
This brought persecution upon them; it fell particularly upon Lutz, their minister;
for a time he maintained his Christian profession with firmness; but at last,
under suffering on the one hand,
and flattery and specious promises from the bishops on the other,
he turned away from the faith once delivered to the saints,
and subscribed again to the errors of Popery; and now,
instead of the fair prospects held out to him, he is immured in a convent;
but the people of the village maintain their faith and their allegiance to Christ,
and they are protected from the popish clergy by the Prince Oettingen Wallenstein.
They have nearly completed a meetinghouse,
in which we had a meeting for Divine worship--the first held in it;
it was a solemn and tendering season.
These dear people appear to have learned in the school of Christ,
and to have felt the baptizing power of the Lord`'s Spirit,
as well as to have partaken of that living bread that cometh down from heaven,
Christ himself, the bread of life.
A Protestant minister has now come to reside among them;
he appears to be a spiritually minded man.
The Baron Baader is a good interpreter; it is a new work to him,
but he seems to be brought under the power of that blessed Truth,
which he is our helper to communicate to others.

In the village of Stengerhoff we were much pleased by a visit to the family of Zekentman;
he appears like a patriarch among them; both he and his wife are very aged,
but vigorous in body and intellect.
They have fifteen children settled near them, with many of their brother`'s children,
grandchildren, etc.
We had a satisfactory meeting with them.
These also are generally turning away from the errors of Popery;
they meet together to hear the Scriptures read, which,
now that their eyes have been in some degree anointed
by the Holy Spirit to see the things of God,
the priests cannot prevent.
As they have but few Bibles among them they gratefully received
some that we presented to them with a number of religious tracts,
all in the German language.

We found the inhabitants of Under-Maxweiler, who were formerly Roman Catholics,
one of the most flourishing communities in those colonies; they are tidy and industrious,
and have built a pretty large and comfortable place of worship.
Our meeting there also was satisfactory.
We were much interested in their young people, who are numerous;
several of them have felt the love of God, through Jesus Christ,
shed abroad in their hearts.
In some of the villages entirely inhabited by Roman Catholics we found some openness,
both among the people and their priests;
one of these particularly wished us to go into their church;
but we preferred to meet the people in their schoolhouse.

It was noon when we came to the village of the Mennonites.
Those who had been in the fields had just returned home to their dinner; their minister,
who had been at the plough,
on being told that we wished to see the people collected together,
mounted one of his horses and spread the information
with such speed that in a very short time men,
women and children were assembled; on coming to the grounds that they cultivate,
we had been forcibly struck by the neatness and luxuriance of their fields,
where hardly a weed could be seen;
but on sitting with them we contemplated with much greater admiration
what we saw of their Christian deportment and felt of their spirits;
there was before us what seemed to be a field that the Lord has blessed,
and which he waters from his holy habitation.
The Gospel given us to preach among them had free course in their hearts,--men,
women and children were broken into tears,
and the Baron Baader whilst interpreting our communications was greatly affected.
It was a most solemn time.
These dear people followed us on our departure out of their village,
and continued to look after us as long as we remained in sight.
Previous to our leaving them we gave them a variety of religious tracts;
these several villages absorbed all we had on hand,
though we had received a supply from the editions we had printed in Berlin.
It is an interesting fact that,
throughout all the Protestant States that we know in Germany,
religious tracts are forwarded gratuitously by mail, even in large parcels;
they are in this manner forwarded to us,
to await our arrival in the chief towns we directed them to be sent to from Berlin.

We were anxious to obtain correct information of the religious
and moral condition of the inhabitants of these colonies,
especially of those villages where Popery has been renounced,
as well as of the others who are evincing their uneasiness under the Popish yoke.
Much pains has been taken to misrepresent these people,
and the Romish clergy have tried to persuade the Prince
O+++.+++ W. that they were evil disposed towards the Government,
or that they have embraced the impious tenets of the St. Simonians;
but we are now prepared to give the Prince a full
and pleasing account of the state we find them in,
and of the fruits of genuine piety that we behold among them.
We hope the Prince will continue to protect them from the persecutions
the Popish clergy are continually seeking to foment against them.

I regret that the Baron Gumpenberg, whose estates are in these parts, is not at home;
he was under very tender visitations when I saw him at Munich some years since,
and he suffered much for his conscientious faithfulness to the testimony of Jesus.

We returned to Neuburg late in the evening,
and spent a part of that night in preparing our report to
the Prince O. W. to be sent by Baron Baader on his return.
We request that the King would extend his protection towards the
Mennonites who have a Christian testimony against oaths and war,
so that they may be exempted from every requisition that they feel
to be contrary to the law and the testimony of Jesus Christ.

Early in the morning some of the colonists from several
villages came to our inn at Neuburg;
some had come that night twelve, others twenty miles to see us;
they were from home when we visited their villages; they wished to be with us a little,
and requested that we would give them some books
like those we had distributed among the people;
they told us that on their return to their homes, late in the evening,
they found every family collected listening attentively to what
one read to the others out of the tracts we had left them,
and that parents and children were in tears.
One of them, on returning home in the afternoon,
met some boys on the road reading a tract with much attention; he listened for a while,
and felt such a strong desire to have one of the
tracts that he offered a large price for one,
but the children replied that no money could induce them to part with such good books.
We were sorry that we had not a single one left to give to these dear people,
but we promised to send them some from Stutgard,
where we expect to meet with a fresh supply.

Their interesting labours in Bavaria being now nearly concluded,
they proceeded to the capital of the neighbouring kingdom of Wirtemberg.

On our way to Stutgard, we stopped at Augsburg,
to see some of the pious people I had been acquainted
with during my former visits to this country.
We were also at Ulm, but did not find we had any service to detain us there.
Soon after our arrival at Stutgard,
we were visited by many of those pious and very interesting persons,
who have been dear to me these many years;
that evening we had a religious meeting at the house of Herring;
three large rooms that open into each other were crowded; but above all,
the Lord`'s glorious presence seemed to fill the house;
many of our hearts were brought under an awful sense of the Divine Majesty,
and were reverently prostrated before the Lord.
Among the strangers present whom I had not known before,
was the Baron Julius von Gemingen, who resides at Steinegg;
he has of later time been brought under strong religious convictions,
to which he has not been rebellious; he appears to be clothed with humility,
and to endeavour to walk in watchfulness and fear; he came to see us the next morning;
we had an interesting time together.
The Baron has a great opportunity of doing good, and he appears disposed to improve it.
He has on his estates eight Seigneuries and villages, and also a town.
The inhabitants of the village of Muscruffin were lately Roman Catholics;
they have now joined the Protestants;
for a while they held their meetings for worship in a hall in his chateau,
which he had properly seated for that purpose;
but he is now building them a meetinghouse.
He gives pleasing accounts of the sincerity and piety that appear to prevail among them.
He takes a peculiar interest in the establishment of schools on his estates,
where the moral and religious education of the young people is watched over.
We have supplied him with some of the Scripture Lessons in German,
to introduce in his schools.

We find that the people in several parts of this kingdom
are becoming dissatisfied with man made ministers;
the people wish to hear the Gospel through ministers of the Lord`'s own appointing,
and not from those who preach for hire,
or who have received their commissions as ministers of the Gospel, from man.
I am comforted in hearing that Hoffman, and the congregation gathered by him,
about six miles from this city, whom I visited when I was last here,
maintain their place in the Truth.
Their number has enlarged, and another congregation, on similar Christian grounds,
has been formed not far from them.

We paid an interesting and satisfactory visit to my old and valuable friend,
the Countess von Seckendorff, widow of the late Count,
and Prime Minister of the former King.
Her two daughters and son were with her.
These young women appear to have retired from the world to serve the Lord.
I was also comforted by a visit from pastor Dann, whom I was with years ago,
on my way to Tubingen, when I went on purpose to see him in his exile,
in a rough country, and among a people not less so in their conduct.
By the grace of God, and the softening influences of his Divine Spirit,
he had been an instrument of mollifying their stony hearts, and,
instead of the briers and thorns, the seed that the Lord had blessed did flourish.
I then also found him under the weight of personal affliction; but, under it all,
the Lord was his stay and the rejoicing of his heart.
Soon after the death of the present King`'s father, who had exiled him,
he was called back, and he has since pursued his ministerial labours in this place,
with fruits to the Lord`'s praise.
His outward man is now bowing under the weight of years,
but his inner man is strong in the Lord.

We have been in company with a pious young lawyer, just returned from Vienna.
He was sent there to transact some business of importance for a banking house in Switzerland.
About the same time, three other pious young men also came to Austria,
in the pursuit of their trades.
They loved to mingle with those who love the Lord Jesus.
One of these young men,
being in company with a Roman Catholic whom he believed to be of that description,
spoke freely to him of the love of God, and salvation by Christ;
but he informed his priest of it, on which the young man was reported to the police,
arrested, and sent to prison.
His papers were taken and examined.
It was found that he corresponded with the two other young men, and the young lawyer.
These also were arrested, and their papers searched.
It was found that they entertained principles contrary to Popery,
for they were Protestants.
The three young men were sent to distant prisons, the young lawyer knows not where,
and he himself was carried, under an escort of police, to the frontiers of Bavaria,
with orders not to return to Austria, under severe penalties.
No wonder that, whilst we were in Vienna,
we felt ourselves so encompassed with the spirit of darkness,
and were sensible that an evil eye was upon us;
but the Lord did not suffer us to fall into the hands of unrighteous men,
and in his mercy restrained them.
Blessed and praised be his name, forever.

Tenth month, 10th. We wished to have been with the King,
but found that he had left Stutgard this morning,
and the time of his return is uncertain.
As dear Allen and myself did not think that we should stand acquitted in the Divine
sight without endeavouring to be with the Queen previous to our departure from here,
I wrote a few lines to her to request an interview.
Immediately on the reception of the note she sent us a message,
that she would receive us at twelve o`'clock. We went to the palace at the time appointed.
The Queen was in her drawing-room with her two young princesses only,
the eldest ten and the other eight years old;
she made us take seats near her on the sofa.
Our minds were soon brought under a sense of much solemnity and reverence before the Lord.
The heart of the Queen was prepared for our visit; it was tender when we first came in,
so that there was no need to utter many words,
for her inward ears were open to hear the language of the Spirit;
she loves the Lord Jesus,
and she endeavours to instil into the hearts of her
young princesses the knowledge of the Saviour,
which her worthy mother, the Duchess of Wirtemberg, had succeeded, by the grace of God,
to impart to her and her sisters.
She told us that her mother had wished that information
might be sent to her as soon as we came to Stutgard,
for she desired to see us, but she was from home at the present.
It has been a comfort to us to hear, from other quarters,
that the Queen`'s mother and her two sisters, the wife of the Grand Duke of Baden,
and that of the Crown Prince of Austria, maintain Christian humility and watchfulness.
It is rare to find the labours of love in a woman of the
rank of the Duchess thus blessed towards three daughters,
occupying such high stations in life.
We spoke a few words to the princesses to encourage them to walk in the fear of God;
they both were much tendered; we presented to each small books for daily meditation;
one of which was compiled by Elizabeth J. Fry.
The Queen told us that the girls would not fail daily to peruse them.
This opportunity with the Queen was one of those rare seasons in
which much of the Lord`'s contriting love and power is known;
may the Lord bless his work and carry it on even to perfection!

We paid another visit to the old pastor Dann, at his particular request;
some portions of my religious communication, when we were before together,
had made deep impressions on his mind,
and revived feelings that he said he had had for a length of time,
and which become deeper as his age increases.
They relate to the corruption that has spread so widely in the churches,
not that of Rome only, but among the Protestants also; he laments deeply,
especially over those who call themselves the ministers
of the Lord and priests of our God,
some of whom are great obstacles to the advancement
of the work of reformation in the church;
many of them preach themselves, or the devices of their own hearts,
and not Christ and his Gospel.
"`They have,`" said he, "`substituted Popish forms, or their own inventions,
for the pure and spiritual worship of God.
They have indeed in their churches a baptism, communion, worship, ministry,
but it is all outward, it comes not from Christ, nor from his Spirit,
and cannot gather the people to him;
their doings have a scattering tendency--their works,
their life and conversation proclaim that they neither
believe in the Truths contained in the inspired volume,
nor in Christ, the Saviour of whom the Scriptures testify;
others publicly manifest that they believe in neither.`"
He mourns over the ascendency that the Socinians and Rationalists
have obtained in many of the Protestant churches;
yet he rejoices in that there are many preserved,
both among the ministers and the people, who are spiritually minded,
and who love the Lord Jesus in sincerity.
The dear old man said that he shall descend to the
grave in a lively hope that the Lord in his own time,
by the brightness of his arising,
will dispel the mist of darkness that hangs now over the churches and the nations,
and that the kingdoms of this world shall become
the kingdoms of our God and of his Christ.

Amidst the close engagements that have pressed on my mind for a length of time past,
I have felt deeply the prospect of parting with my beloved
friend and co-worker in the Gospel of Christ our Redeemer,
William Allen;
he has been looking to this place as that where he
will feel himself liberated to return to England.
I feel heavily under it; we have been so closely united,
and harmonized in our prospects and services.
I feel it the more as I have weighty religious engagements before me.
Spain, in particular, is night and day on my mind,
and as the time when I may have to enter that nation is drawing near,
the difficulties of proceeding there are multiplying greatly.
That kingdom is now represented to be in a state of great confusion;
it is said that there is great effusion of blood,
and the prisons are crowded with victims; from place to place,
those who hear that I have it in prospect to go there,
represent to me the impracticability of doing so.
I had hoped that dear Allen would have gone with me, and now, we are going to separate!
Notwithstanding all these discouragements and difficulties,
the Lord`'s call to me to go to Spain is louder and louder,
and the time to endeavour to enter that kingdom appears, with clearness,
to be the forepart of next year.
O Lord! all things to thee are possible.
Thou canst make a way for thy poor servant, where none now appeareth.
My life, there also, thou canst preserve, if it is thy gracious will!
My dear Allen also thou canst direct to return to me, though now we are going to part.
Thy will, O Lord, in all things be done.
Condescend only graciously to continue to fulfill, on behalf of thy poor servant,
thy blessed word of promise,
"`I will teach thee and instruct thee in the way in which thou goest,
I will guide thee with mine eye.`"
So do, O Lord, and strengthen thy poor worm,
with faithfulness and singleness of heart to follow thee whithersoever thou callest.

For my encouragement I have remembered, that, when Jordan was overflowing its banks,
the Lord commanded Israel to pass over that river;
but as soon as the feet of the Priests and of the
Levites that bore the Ark of the Lord`'s testimony,
entered the river, the waters thereof divided on the right and on the left,
and the host of Israel passed over dryshod;
and stones of memorial were brought from the midst of Jordan, and raised up on its banks,
as monuments, proclaiming, "`hitherto the Lord has helped.`"--To this very day, O Lord,
thou hast helped thy servant; and thou canst do it again, even unto the end.--Amen, Amen!

In the evening we had a meeting at Herring`'s;
it was chiefly attended by those who have so learned
in the school of Christ as to seek for help,
salvation, and consolation from him only.
In good measure I hope it may be said of some of them,
that "`they worship God in the Spirit, rejoice in Christ Jesus,
and have no confidence in the flesh.`"
We had an instructive and edifying season together.

11th. This morning we received a note from the Minister
of State informing us that the King returned last night,
and would see us at about one o`'clock. We went accordingly;
he received us in his private apartment, no other person being present,
as had been the case in my former visits to him.
He expressed his satisfaction at seeing us once more in his dominions,
and made us take seats by him; we continued about two hours and a half together;
liberty of conscience, the religious and moral education of the youth,
the treatment of prisoners so as to endeavour to obtain their reform,
were amongst the subjects treated upon.
The nature of the peaceable kingdom of Christ was also fully set forth,
and the King was entreated to endeavour so to act and to live as to give evidence to
his subjects that he acknowledges the Lord Jesus Christ for his King and his Lord.
He was serious and very tender under what, in the love of the dear Redeemer,
we imparted to him.
Our separation was solemn; he said,
"`These hours we have now spent together are among the most precious
of my life;`" he desired that after my return to America,
I may continue to have him in my remembrance,
and put up my prayers for him unto the Lord.

As we were on our way from the palace to our inn, we were overtaken by a young woman,
a messenger from the Queen, who handed us a letter from her,
by which she bid us once more a Christian farewell; she had hoped, she said,
to have done it in person, by being present during our visit to the King,
but that he thought it was best that he should be alone with us;
the Queen then alluded to the solemn visit that we had paid her,--a
solemnity which she continued to feel,--and concluded by desiring
that we might continue to have her in our remembrance and prayers,
that she may be supported under every trial, and preserved from every temptation;
she concluded by signing herself simply "`Pauline.`"
I have no doubt that the King felt a delicacy in the thought
of seeing me in the presence of his present Queen,
as the last time I was with him was soon after the decease of his former wife,
the Grand Duchess, sister of Alexander, the Emperor of Russia;
he was then under a heavy weight of affliction, for he deeply felt his great bereavement.

On our return to our inn we found a large parcel
of tracts which we had ordered to be printed at Pyrmont,
and at Berlin.
We put up several parcels for the colonies on the Donau Moos,
and for several other villages and places where we had found or heard of pious persons.
We put all these in the way to be properly forwarded;
and I kept others to carry with me to distribute, as way may open,
during my continuance among the Germans.
Once more, before our departure, several persons came to bid us farewell,
and we took our leave one of another, in the love of Christ,
and the sensible evidence that his Divine presence was overshadowing us.

That same evening I parted also from dear William Allen;
we both felt keenly on the occasion; but could, with assurance of faith,
resign ourselves and one another to the Lord`'s disposal and almighty keeping.
Dear Allen was to set off for Frankfort a few hours after my departure, on his way home.
I travelled on my way very solitary; but the Lord was with me;
without him I lack everything; in him are all my fresh springs!
