== Chapter LVII.

Fourth Visit to Europe

Strasburg--Ban De La Roche--Switzerland

Though Stephen Grellet had left William Allen at Stutgard,
with the "`comforting hope`" that they would be united again in
the "`service of their Lord,`" he deeply felt the separation from
his "`beloved brother and nearly attached co-worker in the Gospel.`"
As he pursued his lonely journey towards the Rhine,
his heart often turned to him in Christian affection--and, on his arrival at Strasburg,
the next day, he thus writes:

To William Allen

Soon after we parted, the recollection of our reading in the morning was sweet,
particularly the latter part of the chapter (Acts 20.),
the parting of Paul with those who came to him from Ephesus.--I reflected,
with grateful feelings, on the help that the Lord has granted us,
and on the sensible guidance of his Spirit,
in directing our steps aright during our various journeyings,
and also that he had enabled us to close our united engagements as we have done,
peacefully.
I did not doubt, my dear brother, that thou wouldst carry thy sheaves with thee, and,
in the retrospect, feel that peace which the Lord alone giveth.
"`Thou wilt ordain peace for us, for thou only hast wrought all our works in us.`"

The journal continues:--

Strasburg.
Tenth month, 12th. Soon after my arrival a pious person came to see me.
He had accidentally heard that an American Quaker had arrived here,
and he thought it might be Isaac Hammer who was coming
a second time to visit them in the love of the Gospel.
It was Professor Ehrmann, who personally knew William Allen.
He was prepared to give me a kind welcome.
We soon went to see Gaspard Wegelin, an aged disciple of the Lord Jesus.
I had long heard of his piety,
and many labours of love in the cause of righteousness and truth in the earth,
which the Lord has blessed.
He is at present in a feeble state of health, but strong in the grace of Christ,
and full of love to Him.

13th. Ehrmann kindly came again this morning to accompany
me in a visit to several persons in their families.
Most of the inhabitants of this place, and of the country round, speak only German,
though belonging to France; so that I have need of an interpreter.
One of the persons I visited is Krafft, a useful and valuable man,
who occupies an important station, the responsibility of which he feels deeply;
he is here what Tholuck is at Halle, and Hahn at Leipcic.
Infidelity greatly prevails here,
and Krafft feels it laid upon him to endeavour to counteract it, as,
through the grace of God, he is enabled to do.
He has great place among the young people.
In the evening I had a religious meeting.
It was held at the house of Gaspard Wegelin.
The notice was spread chiefly among the pious part of the community;
the Lord owned us very graciously: my soul is often very sorrowful,
but at seasons I am enabled gratefully to rejoice in the Lord, in meeting with a seed,
here and there, which he has planted, and which, through his assisting grace,
and by living faith in him, brings forth fruit to his praise.
We were comforted and edified together.

I left Strasburg before daylight, on the 14th, for the Ban de la Roche,
the former residence of Oberlin, that humble but great man, and dignified,
useful servant of the Lord, whose works continue to proclaim his love to God and man.
I came thirty-four miles to Foudai, where resides Le Grand,
the particular friend of the late Oberlin;
he is solicitous that the useful institutions formed
by him should be conducted on the plan he designed.
Le Grand has two sons,
who with their wives and families reside on the same premises with him;
they carry on an extensive manufactory of a variety of tapes;
it was one of the plans of Oberlin to procure employment and the means of an
honest livelihood to the numerous inhabitants of a poor and stony land.
Immediately after my arrival Le Grand very kindly sent messengers
to the several villages on these mountains,
with the information of my intention to have a religious meeting with them that afternoon,
to be held in the central village where Oberlin used to reside;
his house there is at present occupied by his son-in-law,
who has succeeded him as pastor.
Accompanied by Le Grand I went there,
and was much pleased on meeting with faithful Louisa,
who was the right hand of Oberlin in promoting the religious, moral,
and literary education of the inhabitants of those mountains.
She is now aged, but still active; every week she takes her walks round the villages,
visits the schools, the sick and the afflicted,
imparts religious instruction to the young people,
and performs her labours of love as needed, and as her way for it is open.
She has trained several mistresses who are engaged in the schools;
she introduced me to some of these, whom she calls her fourth generation.
Oberlin`'s daughter is a pious woman.
Before the hour at which the meeting was appointed,
the people were seen running down the rocky mountains, and collecting in great numbers;
it reminded me of what I saw several times when on the island of Hayti;
they came from four to eight miles, though the notice was so short.
The meeting was held in their place of worship; the word of instruction, comfort,
and encouragement, was given me to preach among them,
but I had also a solemn warning to proclaim to some,
accompanied with earnest entreaties to turn away from their rash and evil purposes and,
after the example of the prodigal son, to return to their heavenly Father.
I was astonished at myself, to have this kind of labour among such a people;
but I was told afterwards that a son of the late worthy Oberlin
was in the practice of frequenting unprofitable company;
he had concluded to go that very night to Strasburg and enlist as a soldier;
hearing of the meeting, curiosity brought him there;
the word preached sank deep into his heart; the Spirit of Truth, the faithful witness,
performed his office in him; his purposes were changed,
and he spent the night in retirement and prostration of soul before God;
so that it might be said of him as of Saul,
after the Lord had appeared to him in the way, "`Behold he prayeth.`"

I returned that evening to the house of Le Grand, where,
before retiring to rest for the night, we had a precious,
uniting season together before the Lord; a fellowship of spirit was sweetly felt.
It appears that one of the rules established by Oberlin was,
that every one of his people should every year place
in the treasury one-tenth part of his net income;
this rule he enforced by love.
The money was applied to works of benevolence or charity,
and in the many improvements made in that once wilderness country.
Le Grand told me that for some years he would not
comply with what he considered an arbitrary rule,
though he highly valued Oberlin;
but he thought he could be his own almoner of the Lord`'s blessing on his temporal industry.
The losses that he sustained year by year in his business induced him,
at the end of a few years, closely to examine into the matter,
and he found that during that period they amounted exactly to the ten per cent,
on his income, which he should have put into the treasury, according to Oberlin`'s rule.
This discovery convinced him that Oberlin was right,
and he has acted ever since on the prescribed plan; now, instead of meeting with losses,
his income has yearly increased,
though he has not ceased from also being his own
almoner of the blessing that God confers upon him.

16th. I returned in good time to attend a meeting
I had appointed to be held last evening at Strasburg,
in the house of Krafft.
It was another solemn season when, by one Spirit,
we were baptized together into the one body, and drank into one spirit.
Among those present was a very interesting young Jew converted to Christianity;
he stood high among his own people;
now the love of Christ constrains him to devote himself to their good,
and to declare to them what great things the Lord Jesus Christ has done for his soul;
he is a Christian missionary among the Jews, many of whom reside in this city.
He is spoken of as being firmly established in the principles of Christianity,
and fervent in spirit in proclaiming that Jesus of Nazareth, the reputed son of Joseph,
is the very Christ, the eternal Son of God, and the Saviour of men.

17th. I was pleased with a visit I made to J. D. He was formerly a Lutheran clergyman,
but, as he could no longer comply with the various forms and ceremonies of that church,
which he considered at variance with plain Scripture
testimony and the dictates of the Divine Spirit,
he withdrew from them.
He now holds meetings in a place fitted up for the purpose, in his own house,
where many from among the several religious denominations resort.
His meeting place accommodates about three hundred persons.
The meetings on First-days are of a public character.
One at nine a.m. is for the town and country people.
At four p.m. for the town`'s people again; and at seven in the evening,
for the young people.
He has introduced no forms or ceremonies in these meetings,
but he endeavours to feel after the guidance of the Divine Spirit.
He is also extensively engaged in the distribution of the Scriptures and religious tracts,
both in the French and German languages.
He appears to be a man of exemplary piety, and is much respected by the people generally.

In the afternoon the young Jewish convert came to see me, bringing with him several Jews,
who also have their attention drawn from the Mosaic to the Christian dispensation.
I had an interesting and edifying opportunity with them.
The words of the Apostle to the Galatians,
"`the law was our schoolmaster to bring us to Christ,
that we might be justified by faith,`" were largely treated upon.
Some of them appear to have clear views of spiritual worship, of the Christian baptism,
by the washing of regeneration and the renewing of the Holy Ghost,
and of the real Christian communion, which is a participation of the Bread of Life,
Christ Jesus, who is our Passover.
They seem to understand how all the various services in the outward Temple
pointed to that most solemn service now in the temple of the heart,
where spiritual sacrifices are to be offered up, acceptable to God, by Jesus Christ,
the High Priest of our profession.
Their various ablutions for the purifying from outward defilements, they see,
point to the sprinkling of the blood of Christ,
who has loved us and washed us from our sins in his own blood.
I endeavoured to encourage them in coming to God
through Christ with full purpose of heart,
being of the true circumcision,
who worship God in the Spirit and rejoice in Christ Jesus,
having no confidence in the flesh.

I left Strasburg on the evening of the 17th, and arrived at Basle the next day.
Way opened for my having several meetings in that place; two at the Mission House;
the last was attended by a large number of the pious inhabitants.
Two others were held at Miriam Stackelberg`'s. She is a pious, rich widow,
who endeavours to honour the Lord with her substance.
She has an infant school for fifty children, and two others for boys and girls,
where their morals are strictly watched,
and they receive an education to fit them for business.
The meetings in her house were attended by persons
acquainted with the value of religious retirement,
and watchfulness unto prayer.
The time we spent together in waiting on the Lord, was very refreshing to my spirit.

Several persons came to see me, from six to ten miles distance;
they have so learned in the school of Christ,
as to have ceased from placing confidence in any of their own works or performances,
or in anything that man can do for them,
but two or three meet together silently to wait on the Lord,
or at other times to read the Holy Scriptures; others sit solitarily, alone,
in watchfulness and prayer.
I was much interested in one of these, the wife of a clergyman,
who resides five miles from here.
The dear Saviour has many sheep and lambs scattered about in this wilderness world,
and especially in Switzerland and Germany, who are acquainted with his voice,
and their place of feeding.
My soul is prostrated with gratitude at the Lord`'s condescension
in bringing me to an acquaintance with many of these,
arriving, as I do, at places where I am an entire stranger;
is it not of his doing that I should be brought in
contact with some of these his visited ones,
as was the case at Strasburg, here, and in many other places; Spittler, Blumhardt,
and a few others,
are persons whom the Lord has rendered instruments of much good in these parts.
I had also a satisfactory meeting with a company of persons called Pietists;
they are a serious people.

21st. Accompanied by Spittler, and a son of Le Grand, from Foudai, Ban de la Roche,
we went ten miles up the Rhine to Beugen,
to visit an interesting establishment for eighty poor orphans of both sexes,
and for twenty-four young men,
who are educated for schoolmasters in institutions where the pupils
support themselves by manual labour of various kinds.
Zeller and his wife, who are the superintendents of it, are persons of rare piety;
it is from an apprehension of religious duty that they occupy these stations;
Christian love and kindness are very conspicuously prevailing in their hearts;
by these they govern.
The same love seems to flow back from the young people towards them.
I had in the forenoon a satisfactory meeting in the establishment,
attended also by the people of the country near; early in the afternoon,
I had another meeting with the inmates of the institution much more select.
I could but compare this house to that of Obed-edom, on which the Lord`'s blessing rested.
The wife of Zeller devoted herself in very early life to the Lord,
and to this day she appears to be faithful in endeavouring to perform her solemn vow.
When about five years old, she was playing on some of the rocky hills of the country;
one of their large eagles saw her, and darted down upon her head; a man with a gun,
not far distant, watched the motions of the eagle, but did not see the child;
he fired and killed the bird, at the very moment of his darting upon the child`'s head;
great was his surprise, on coming to the spot,
to find the dead eagle by the side of the child.
The deep wounds made by his talons on her head,
show what a narrow escape she had from the voracious bird,
and from being wounded or killed by the gun.
This dear woman considers that her life thus spared,
is to be wholly devoted to the service of God.

I returned to Basle in time to attend another meeting at Miriam Stackelberg`'s.
Here I was pleased with a young woman I had not seen before.
She lately accompanied Miriam on a visit to some of the valleys of Sardinia,
where they were mostly among the Papists.
Persecution was stirred up against them by bigoted and envious persons,
because they had distributed some copies of the Holy Scriptures, and religious tracts.
They publicly received personal abuse,
and were even threatened with the loss of their lives.
Under these sufferings for Christ`'s sake,
this young woman appears to have grown in the root of religion.
Thus Divine mercy often converts our tribulations into rich blessings.

Zurich, Tenth month, 23rd. I left Basle early this morning,
and arrived here this afternoon.
I greatly enjoyed the ride.
I was alone in the carriage most of the way.
Beautiful and grand was the scenery before me;
it loudly proclaimed the Lord`'s power and wondrous works.
Much of my road was through deep valleys, by the side of the Limath.
Before me, at a distance, were high mountains covered with snow,
the lofty peaks of some of them lost in the clouds.
But, above all, my inward eye was open,
so as to behold wondrous things out of the law of God.
O! when, by his quickening Spirit,
we are enabled to contemplate the Lord`'s wonderful workings,
and to have a sense of what great things he has done for our souls,
how can we but be filled with amazement, and be prostrated very low before Him!
Under the fresh sense of what redeeming love and mercy have done for me, to this day,
my soul was greatly contrited.
In unutterable condescension and unmerited favour, a living hope was begotten in me,
that the Lord, who has thus been with me all my life long, would be with me to the end;
and that, in Spain also, he would make way for me,
and open a door to proclaim his great and glorious name.

24th. Antistes Gessner, hearing that I had arrived, early came to see me.
I went back to his house, the same which was occupied by the aged Antistes Hesse,
his predecessor, and where, some years since, I had solemn meetings.
The dear old man departed this life full of the love of God,
and peace and joy in the Holy Ghost.
He was a great example of humility and piety.
The valuable wife of Gessner remains as one established in love to the dear Redeemer;
also her sister Louisa Lavater.
Their dear young people had collected to see me.
Our meeting was in the Lord`'s presence.
We were reverently prostrated before him.
I returned there in the evening,
to attend a meeting of which notice was spread among the pious part of the inhabitants,
many of whom attended; and the Lord owned our coming together by his presence.

25th. I was in the families of several of the sick
or afflicted among the Lord`'s people here,
and had another meeting, largely attended, at Louisa Lavater`'s.^
footnote:[From the numerous letters addressed to Stephen Grellet,
by pious individuals with whom he had mingled in different parts of the Continent,
and with whom he kept up a correspondence for many years,
it may not be unsuitable to introduce the following, referring to the present visit,
though not received till a considerable time after:
{footnote-paragraph-split}
Zurich,
the 5th of 6th mo.,
1834.
{footnote-paragraph-split}
My very dear Friend and Brother in our Lord Jesus Christ,
{footnote-paragraph-split}
A
multitude of engagements has hitherto prevented me from thanking thee for thy very welcome
letter of the latter part of the 3rd month.
It is always a happy day to me and all my family, when we receive a letter from thee.
Yes, my dear friend, we have a very kind Master, who has guided thee,
and blessed thee greatly in thy journeys.
O,
that He may cause all the seeds of the truth which thou hast scattered abroad to sprout,
grow,
and bear fruit for eternity.
{footnote-paragraph-split}
The
recollection of thy last sojourn amongst us,
and especially of thy farewell, is always sweet, yet at the same time sorrowful,
like the parting of St. Paul at Miletus-they were all filled with
grief because he had said that they would see him no more.
We all never shall forget thy love for thy Lord and thy Christian kindness to us.
May the Holy Spirit often inspire thee to pray for us for me that I may finish my course,
and fulfill the ministry which I have received from the Lord Jesus Christ.
It seems to me that outward afflictions are much easier
to bear than those which sin causes in our hearts.
But there is nothing to be done but to surrender ourselves to our Saviour,
who alone purifies us;
being justified by faith we have peace with God through our Lord Jesus Christ.
{footnote-paragraph-split}
The
situation of our church is nearly the same as it was during thy stay among us;
yet I had the pleasure of seeing recently a proof that there are a few young
ministers who declare themselves openly on the side of evangelical truth,
and a very large majority voted for the good cause in our synod.
{footnote-paragraph-split}
Thou
art now on the point of leaving Europe and returning to America.
May our God bless thee and reward thee for all the good that thou
hast done in his name among the Christians whom thou hast met with,
and among us.
Our friendship cannot be dissolved, it will last forever,
for it is founded upon our Lord.
{footnote-paragraph-split}
Present
our sincere Christian salutations to thy dear wife and daughter,
and tell them that we hope, through the grace of God,
to see them in the mansions of our Lord, when we shall be forever with him.
All my family salute thee cordially.
{footnote-paragraph-split}
I return many thanks
for all the kindness which thou and our friend Allen showed my dear grandson,
M+++.+++ Usteri.
{footnote-paragraph-split}
I embrace thee heartily with all Christian love.
{footnote-paragraph-split}
G.
Gessner.
{footnote-paragraph-split}
My venerable Friend!
{footnote-paragraph-split}
You
will kindly accept a few lines from your friend Louisa,
who praises the Lord with you for having deigned
to crown with his blessing all your toils,
your labours, your prayers for the salvation of your brethren.
Venture, my friend, to repeat the language of our Divine Master,
"`my meat is to do the will of Him who sent me.`"
I am glad to tell you that the Lord has caused to sprout
some of those seeds that you have sown in my heart,
because I venture to hope that you will unite with me in prayer for their growth.
Never shall I forget the dinner, or rather love-feast,
which was held in my house the 25th of Tenth month, 1832,
which was sanctified by the presence of our Saviour,
who has united us still more closely in Himself from that
day.
{footnote-paragraph-split}
All the friends who were present
at the little meeting which you held one evening in my house,
and whom you have named in your dear letter are very grateful for your remembrance,
and entreat dear friend Grellet not to forget them in his prayers.
{footnote-paragraph-split}
O
how I congratulate your dear wife and your happy daughter on the
return of a husband and father so beloved.
May the Lord mark that period with abundance of grace.
Salute very cordially my dear sisters in Jesus Christ on my behalf.
I venture to hope that you will continue to let us hear from you occasionally,
and I am convinced that we are forever united in our Head.--We
meet each other when we look towards Him.
{footnote-paragraph-split}
Your
grateful friend,
{footnote-paragraph-split}
Louisa Lavater.]
It was a season of great brokenness of spirit.
The Lord has a precious seed among the young people.
May he water it from his Divine presence, where there is life forevermore.

St. Gallen, 26th. Travelling during the night I arrived here early this morning.
The few last days I felt it to press on my mind to write to Pauline, Queen of Wirtemberg,
in answer to her letter received after the visit paid to the King;
I wrote her accordingly on my arrival here,
and felt peace after discharging this debt of Christian duty.
I then visited several families of my former pious friends;
since I was here several have passed from the militant to the triumphant church,
but others continue to be witnesses to this day that, by the grace of God,
they are what they are.
I have been comforted in meeting with a number of precious young people,
who appear to come up in the footsteps of their pious deceased parents.
In the evening I had a large meeting;
the word of encouragement and consolation was given me to proclaim,
but I had also pretty close labour with some.

Zurich,
28th. Leaving St. Gallen very early yesterday morning I came back here that afternoon.
I had a large satisfactory meeting in the evening and another this morning, and now,
with peacefulness, my way is clear to depart.

Berne, 31st. I set off at noon from Zurich; a number of pious people of both sexes,
accompanied me to the coach, and continued with me till my departure.
I had a tedious, trying journey to this place.
We arrived at Arun at six p.m., and did not leave till half-past ten.
All the chambers in the inn were so crowded with
company which I could not assimilate with,
that I was obliged, in my own defence, to walk about the streets,
though the night was very cold and dark.
In some of the rooms they played at cards, in others were billiard tables;
there were music and dancing, drinking and smoking.
My head and my heart were made sick.
We arrived here early the day before yesterday.
I called on several of my former acquaintances, some of whom I was pleased to meet again,
they retaining their love for the Truth.

I was recognized by a female as I passed her in the street;
she saw me when I was here before, and was at a meeting;
she says it was the first time in her life that she had been in a Christian assembly;
she was greatly astonished at my communication,
for it seemed to her as if I was singling her out
of the large company and exposing her conduct,
even her secret thoughts, before them all,
and yet she knew that I could not have any knowledge of her,
nor could anybody have informed me of what none knew but herself;
but she has since found that there is One who knoweth the secret of our hearts;
now she knows and loves God, and is willing that he should try her, prove her,
and show her her thoughts.

I had a meeting that evening largely attended by a mixed company;
I was brought under deep exercise on account of some; but the Lord enabled me,
his poor servant, to minister to their several conditions,
and the meeting concluded under a precious solemnity.

Yesterday, accompanied by L`'Orsa, my former kind and faithful interpreter,
I called on many families, and had solemn and refreshing seasons with some of them.
In the evening I had another meeting.
This afternoon, still accompanied by L`'Orsa, I visited other persons in their families;
one was J. Gerber, who was lately at Sierra Leone as a missionary;
he has come here to recruit his health.
He knew well my valuable, deceased friend, Hannah Kilham,
and he speaks highly of her piety and great usefulness.
He left Africa the day after she sailed for Liberia.
I had an interesting and edifying season with him and a few others.

Neufchatel, Eleventh month, 1st. I travelled part of the night to this place;
the moon and stars shone brightly on the smooth surface of the lake,
and on the tops of the mountains.
The inhabitants of this and other cantons,
are in a state of ferment on account of some political questions,
and blood has been shed.
I met here, however, some who are of a meek and quiet spirit,
and appear to be seeking for those things that make for peace.
I had a pretty satisfactory meeting, attended by a far greater number than I had expected.
There are several young persons seriously disposed, who by pious conduct,
preach loudly to their parents.
I called on one of these, who is a magistrate; I was first introduced to his father,
who received me with politeness, but, on hearing the object of my visit, he said, "`O,
it must be my eldest son that you wish to see;
I concern not myself with things of this kind.`"
There are five or six persons at La Goulette who unite frequently
in sitting down together in silence to wait on the Lord;
they came here to see me.

Locle, 2nd. By travelling most of the night I arrived here about noon;
the ascent of Mount Jura is beautiful, but the land towards the top is very barren;
only a few patches are cultivated with potatoes and cabbages; a large population,
however, reside here.
The houses are mostly small, but very neat; all,
even the largest which occupy much space on the ground floor, have but one story.
This manner of building is adopted that they may be more protected from the wind,
which blows vehemently, at times, on this high ground.
These numerous inhabitants are occupied in manufacturing watches;
most of the works which are put together in Germany and France are made on this mountain;
many also are exported for the use of watchmakers in England and America.
Locle stands nearly on the top of the Jura, yet it is in a hollow,
and is thereby protected from the bleak winds;
it is said that there was formerly a large lake in this hollow,
whence this small town derives its name.
The land about it is well cultivated; many cattle and sheep are fed on it,
and excellent butter and cheese are made.
Mary Anne Calame, well known for her great benevolence, resides in this place,
together with Catherine Zimmerling, her intimate friend, who, during eighteen years,
has shared actively in her works of benevolence and charity.
They have, as inmates in their family, several young women,
who by afflictive occurrences have been brought into a reduced condition.
They have the charge of their education in every respect,
and qualify them to occupy useful and important stations in life; but, above all,
their especial care is to endeavour to imbue their minds with piety.
One of these young women is a Greek who, when a child,
escaped the massacre of the inhabitants of Scio soon after I was there.
Her parents were among the victims of the Turks.
I hope this young woman may become extensively useful in Greece.

The establishment of M. A. Calame is about a mile and a half from the town.
I went there with her in the afternoon.
It was very touching to me, as we entered on the premises,
to see the young people we met saluting her with filial respect and affection,
// lint-disable invalid-characters
by the name of "`Ma chère mère,`" "`my dear mother,`" and she calls them,
"`my children,"`and she acts truly towards them the part of a mother;
her time and property are devoted to them,
but her necessities in the maintenance of so large a family,
and the erection of the needful buildings which she has yearly to enlarge, are such,
that she has to be dependent on public benevolence;
in this she has never been disappointed,
though she has been repeatedly reduced to the last extremity,
not having even the "`handful of meal`" left in her stores; but the Lord,
the Father of the orphans, in whom is her confidence, has never forsaken her;
many and very interesting are the circumstances under
which her great wants have been supplied.
In a number of instances she has not known by what human hand help was extended,
but she had the conviction that the Lord had done it.
The dear woman, who knows that there is no limit to Omnipotence,
also feels that there is none to her benevolence;
thus she considers not her want of means,
but the needs of the poor orphans whom she cannot refuse to admit to her asylum,
whenever they are brought to her.
She first introduced me to the youngest children, from two to six years old;
they were all sitting on low benches, at their various employments, knitting, sewing,
or having their books, and the very little ones were unravelling pieces of old silk,
which, in another part of the house, is carded and spun.
Perfect stillness prevailed;
if they had anything to say to a motherly woman who sat facing them, it was in a whisper,
except that when we entered the apartment they all rose,
apparently delighted to see Mary Anne.
// lint-disable invalid-characters
They saluted her, "`Ma chere mère,`" and such as were near tried to kiss her hand;
but they soon resumed their seats and occupations.
Mary Anne went among them, giving them a few sugar plums.
Their mistress strongly attracted my attention.
She was herself knitting,
and conveyed instruction to the children with much kindness and affection,
on such a variety of subjects,
that I could hardly credit that I was among such a class of children, and so young.
The greater was my astonishment when I found that this young woman was blind.
Some of the teaching was on this wise: "`Children,
you have heard of the birth of the Lord Jesus Christ, our Saviour; can you, Mary,
tell me, where he was born?
And you, Sarah, do you know what kind of people came there to see him?`"
Of another she inquired how they knew that he was to be found there?
After a number of questions connected with the Scripture narrative,
to which the children answered very correctly, she said to another,
"`can you tell me some particular circumstance that
occurred at the time of the birth of our Saviour?`"
Several of the children said, "`there was then peace on all the earth,
and the Temple of Janus was shut.`"
Then again she said, "`and where was the Temple of Janus?`"
"`At Rome,`" was the answer.
She pursued, "`but where is Rome?`"
etc., etc.
Thus the blind woman, whilst going on with her knitting, conversed with the children,
on the Scriptures, history, geography,
etc. and they answered her questions without raising their eyes from their work.
By such kind of conversation the younger ones were also instructed,
and questioned on subjects within their capacity.
There are in the institution several schools for boys and for girls.
There are also various workshops here; for this is a school where manual labour,
both in and out of doors, is pursued.
Most of the teachers have received their education in this establishment.
Their spirits seem to be moulded after that of Mary Anne Calame.
The children are remarkably kind and affectionate to each other.
I had a meeting with them and their teachers, and other members of the household.
It was a solemn and tendering season.
During the course of my communication to the children,
I queried if some of them did not sometimes feel
their hearts so full of the love of Christ,
or so sensible that they had grieved the Divine Spirit in their unwatchful moments,
as to bring them to desire that they might retire into some private corner,
to pour forth their souls in prayer to God, or in praises for his great love to them.
Several sobbed aloud,
so that for a few moments I was under the necessity to cease to speak.
After meeting,
M+++.+++ A. Calame told me that yesterday some of the girls came to request
the privilege of the use of a small place in the garret;
she inquired what they wanted to go there for?
They hesitated for a while, but being pressed to answer, they burst into tears and said,
they wished to have some private corner where they
might retire to prostrate themselves before the Lord,
and pray to him.
Mary Anne told them, "`You need not go to such a place, my dear children,
you know that my private closet is unoccupied most of the day;
retire quietly there whenever you are inclined.`"

In the evening I had a meeting in the town,
which was also attended by M. A. Calame and her family; it was a good meeting,
for the Lord was with us.
M+++.+++ A. C. does not belong to any particular denomination,
having felt religious scruples against the forms
and ceremonies introduced by--many of them.
Meetings are regularly held in her family, which are attended by a few pious neighbours;
they sit down together in silence,
and seek for the presence of God in the temple of their hearts.

Neufchatel, 3rd. This morning I went to M. A. C.`'s house,
and had a solemn meeting with her family, including the young women educated in it;
I then returned to this place, descending the Jura on the opposite side of the mountain;
parts of the road strongly reminded me of Mont Cenis,
except that they exceed it in beauty.
The two large lakes below, the fine, cultivated plains, and the tops of the snowy Alps,
are very grand.
By using exertion I arrived here in good time for
a meeting I had appointed before going to Locle;
it was large, as the notice had spread some distance in the country.
The Lord enlarged me in preaching his glorious Gospel.

Yverdun, 4th. I was on the road for this place by four this morning.
I had heard much of a people in this city represented by some as
persons that had made great attainments in the life of religion.
I wished for an opportunity to judge a little for myself;
one of their chief men is a physician of the name of Duveley;
about seventy persons were met at his house when I came to it;
their meeting concluded soon after.
I had an opportunity to see and converse with them;
they are Ranters to a very high degree.
One of them thought that his faith had increased
far beyond the size of a grain of mustard seed,
that therefore he could walk on the waters of the lake,
and a few days since he actually gave out that he would do so.
A concourse of people collected on the side of the lake to see his performance;
he made the attempt several times, but the water could not bear him up;
he told the people that his faith was not yet strong enough.
I found them full of airy notions.

Lausanne, 5th. I arrived here early in the afternoon;
a great change has taken place since my last visit; many are removed by death.
The aged Polier is like a servant waiting for the coming of his Lord;
he has lost his sight,
but the light of the Lord shines brighter and brighter in his soul.
I had this evening a refreshing meeting at his house, when a number of his friends met us.

6th. I visited several pious families,
and was particularly interested in that of De Montel;
some of his wife`'s relatives from Neufchatel were also present;
it was a season of mutual consolation in the Lord.
Montel accompanied me to a meeting held in the afternoon;
it was largely attended by the inhabitants,
and by many persons who came from the coun try, several of whom are clergymen.
I found it a very exercising time, and had close labour among them;
there were however some precious and tender spirits present;
I thought most were too full of themselves and of their attainments,
to bow down to the simplicity of the Truth,
and to receive Jesus of Nazareth as "`Christ crucified,`" the hope of our salvation.
I left them with a heavy heart.

Geneva, 8th. I arrived here last evening.
This day has been closely taken up in visiting a number of pious families.
My soul is made glad in the Lord on finding that,
though some of them have been sorely chastened under the rod of affliction,
both of an outward and spiritual nature,
they have not been forsaken under their sore trials.
The Lord has been with them.
I have sweetly mingled again with Moulinier,
who seems to be fast ripening for a better habitation, even an heavenly; his colleague,
pastor Demalleyer, also; they, together with Galland,
maintain with firmness their Christian ground against
the strong body of Socinians here on the one hand,
and the Calvinists on the other.
The sisters of Galland, Mary Ann Vernet and others, continue in Christian meekness;
they seek for their supplies from Christ, the pure and everlasting spring.
This evening a meeting was held at pastor Moulinier`'s:
it was composed chiefly of those who know that it is good
to be found in a waiting frame of spirit before God,
that it is in the sanctuary of the heart that we are to seek him,
and that there also he is to be worshipped;
there he ministers of his goodness and mercy to those that wait upon him.
We were refreshed together, and united in spirit in praising his great and holy name,
who is blessed forever!

10th. Yesterday and today I was engaged in visiting the prisons,
and some valuable and useful institutions; one is for old men;
great care is bestowed on their bodily com forts; each has his separate, clean chamber;
everything that might tend to disturb the mind of an old man is carefully avoided,
and in the most tender and gentle way opportunities
are watched for to bring their minds to Christ,
and to stir them up to make use of their few remaining
days in preparing for another life.
I had some interesting and satisfactory religious service in several of these places.
This evening a meeting was held at pastor Demalleyer`'s;
it was a more mingled kind than the one at Moulinier`'s,
but the Lord enabled me to divide the word among the several states of the people.

I dined at Mary Ann Vernet`'s, where various branches of their families were present,
// lint-disable invalid-characters
also her widowed daughter, the Baroness De Staël. We had a contriting time together.
They keenly felt the loss of a valuable, pious relative, a son of Mary Ann`'s;
but they bear it as Christians.
In his attempt to save the life of another person from a building that was on fire,
he himself fell a prey to the devouring element.
The dear youth had for many years past devoted himself, as a Nazarite, to serve the Lord,
and he died whilst evincing his love to man.
I was a good deal with him, in my previous visit here, and I loved him in the Truth.

11th. I had another meeting at Demalleyer`'s, more select than that held last evening.
I had also one at Galland`'s; it was held in the chamber of one of his sisters;
she has long been confined to her bed, under much suffering,
which she bears with Christian patience and cheerfulness.
This meeting was mostly composed of pious females.
Several of these generally meet every week to wait together on the Lord; and,
what is remarkable, the wives of two clergymen and their daughters, are among them;
also the sisters of Galland and another clergyman.
May the Lord himself feed this little flock of his pasture, guide them by his Spirit,
and finally receive them to glory!
