== Chapter LVIII.

Fourth Visit to Europe

The Waldenses

Stephen Grellet had now taken his final leave of Switzerland.
His heart had often turned with much Christian love towards
the Protestant inhabitants of the valleys of Piedmont,
who have so long attracted the notice,
and called forth the benevolent exertions of their fellow Christians of other nations;
and to that interesting people he now turned his steps.
Though historians differ as to their origin, it appears to be certain that,
whether they derive their Christianity from primitive times or not,
their religious belief and church government from very remote periods,
have always been different from those of Rome in the dark, medieval and modern ages,
and it would seem to be more probable that the "`Men of the Valleys`" shepherds
and herdsmen should retain the Truth as it was first delivered to them,
than that they should be able to discover it amidst the darkness of the twelfth century,
when all Christendom was departing further and further from the light,
"`under the false teaching of subtle schoolmen, and ambitious and licentious hierarchs.^
footnote:[See Gilly; Monastier; Jane Louisa Willyams; Baines, etc.]

Charles Albert had obtained possession of the Sardinian throne,
and though the distrustful and restrictive policy
of his predecessors had not been entirely abolished,
he had put an end to many severities and indignities heaped upon the Vaudois,
and they were enjoying a time of comparative repose when
Stephen Grellet visited their isolated communities.

On leaving Geneva, he took the direct course to Turin,
and having reached Chambery he writes:

Eleventh month, 13th, 1832.
I have found as yet no door open for religious service in this place,
where I am detained till I can obtain a conveyance for Turin.
My time has, however, been employed in writing,
which my close engagements and travelling had long prevented.
This place is at the foot of the Alps, surrounded by mountains, rising one above another,
whose snowy summits are lost in the clouds.

Turin, 18th. I was four days on the road from Chambery here,
travelling early in the morning and late at night.
There being much snow and ice upon these mountains, we made but slow progress,
and in some places we were in considerable danger.
It was but a few days since, that a carriage,
by sliding on the ice to the side of one of these steep and narrow roads,
was precipitated to a great depth among the sharp rocks.

I met in these mountains a woman who is one hundred and eighteen years of age,
but is more active than many are at seventy; she walks with a firm step;
her sight and hearing are good; she has had a new set of teeth, but these begin to decay;
she says that she has never been sick; her memory is not only good, but local,
so that she is very minute in her relation of past events.

I have been with a few persons here, some of whom are connected with the Waldenses.
My chief inducement in coming here at present, is to visit that people,
scattered about in the valleys of Piedmont.
I was prevented from doing so when I travelled before in this part of the country.

Pignerol, 19th. I arrived here last evening; I had a solitary but very pleasant ride,
for my blessed Master was with me;
my soul was contrited under a grateful sense that be has,
in a marvellous manner and in great condescending mercy, kept, to this day,
his covenant with me, though on my part, with shame and confusion,
I beheld how frequently I have broken my own covenant with my Lord God and Redeemer.
He has enabled me to renew it this day, and to anoint the altar, with many tears;
may it prove to be an everlasting covenant never to be broken!
My soul also was poured forth before God in supplication for all whom
I have visited and labored with in the work and love of the Gospel,
in various parts of America and in these European nations.
May the Lord bless the works of his own hands everywhere,
and restrain the workings of an evil spirit under
whatsoever specious appearance it shows itself.
I felt deeply and shed tears for those who are carried
away captive by the spirit of unbelief;
my soul did yearn towards those in America who have been subverted from
the faith and the hope of that salvation which is through Jesus Christ,
by Elias Hicks and his coadjutors;
yet I entertain a hope that the Lord`'s faithful messengers will, in days to come,
when those who have been active in sowing the evil seed are laid in the silent grave,
be sent and commissioned to preach unto their children the glad tidings of salvation,
and the word of reconciliation with God through Jesus Christ.
The remembrance also of the thousands that have been slain on these
mountains and in these valleys for their love to Jesus,
and their faithfulness to his testimony, has been feelingly and solemnly before me.
I beheld how many of these have joined that innumerable
company who have come out of many tribulations,
and stand now clothed in white before the throne of God and the Lamb,
having harps in their hands.

La Tour, in the valley of Lucerne,
20th. Our road was among rugged rocks and deep hollows, but the land is well cultivated,
wherever there is a small spot of earth, even close up to the snowy mountain tops;
they have vineyards and mulberry trees,
for they produce a good deal of silk in these valleys.
At La Tour is the largest congregation of the Waldenses.
Bert is their pastor; his congregation is composed of about two thousand adults;
their whole number in eleven villages, hamlets or towns, scattered in these valleys,
is about twenty-two thousand persons;
they have about four thousand five hundred children at their several schools;
but most of these schools are held only in winter;
for as soon as the sun has acquired sufficient power to melt the snow,
their flocks are led to the mountains,
where they are left under the care of the elder boys,
till the cold weather brings them down again into the valleys.
Their accommodations for schoolhouses have hitherto been poor,
and as the cold is very severe in winter,
they hold their schools in many places in stables, warmed by the breath of the cattle;
these being generally dark are of course very ill-adapted for schools;
the women are attracted to the same place to be sheltered from the cold;
they bring their work with them; some knit and sew, or card the broken cocoons of silk,
or spin it, etc., so that a school-room here exhibits a curious sight.
This is not however the case in every village; great efforts have been made,
and some comfortable schoolhouses have been built, or are now building.
The present King of Sardinia appears to favour these people;
their sufferings and persecutions were great under his predecessor;
their disabilities have not however been wholly removed;
they are restricted to the narrow limits of the valleys or mountains they now occupy;
they cannot purchase land out of these limits; if they do, on informers representing it,
it is liable to be confiscated; thus,
they are confined to the cultivation of very small pieces of land,
hardly sufficient to support their families;
this is their reason for introducing the production of silk.
I have endeavoured to induce them to abandon the culture of the vine,
for the wine being consumed by themselves, yields them no income;
it is of such poor quality that it is not worth exportation,
and they have to purchase the grain which might be
usefully cultivated where the vineyards now are.

I met here Colonel Beckwith; he lost one of his legs at the battle of Waterloo,
and now endeavours to devote his time to acts of benevolence;
this is the third winter he has spent among the Waldenses;
he has been useful in promoting and in assisting them in the building of schoolhouses,
and in having schools for the girls separate from the boys.
He also endeavours to introduce among them the manufacture of a variety of articles,
the materials of which are of small value.

I went to most of their villages, and visited their schools;
at Bobi I was pleased with one for girls; it is conducted by a pious widow,
who endeavours to train up the young plants under her charge in the fear of God.
I found religious tenderness among the parents and the children in several places;
most of their pastors also appear to be conscientiously
concerned for the spiritual welfare of their flocks.
These visits were fatiguing, for I had to perform the journeys mostly on foot;
the snow was deep, and the rough paths on the high ground being covered with ice,
rendered walking laborious.
This was particularly the case in going up the mountain to Angrogne.
It is in that valley, and on that mountain,
that many battles were fought during the wars of extermination,
waged against the Waldenses at the instigation of the Papists,
whose armies were accompanied by the Inquisitors.
Many of those poor, unoffending people, who escaped the edge of the sword,
were burned by the Inquisition;
their great crime was their religious and conscientious scruples which
prevented their bowing down to and worshipping images made of wood,
stone, silver or brass, etc.;
and their placing their only hope of salvation in the mercy
of God through our Lord and Saviour Jesus Christ,
and not in the indulgences sold by the Popish priests,
or the absolutions pronounced by them.

Here they are in great want of a schoolhouse.
One, however, is in progress which will have good stoves to warm it.
On coming down the mountain I had a narrow escape; my foot slipped on the ice,
which brought me to the edge of a deep precipice among the rocks;
but my blessed and almighty Preserver protected me here again,
lengthening my days a little longer, that they may be devoted to his service, whose I am.

The district of St. John`'s is the most fertile of any of their settlements.
It contains about one thousand eight hundred inhabitants.
Several hamlets seated on the mountains belong to it; but,
during the winter months the inhabitants can very seldom come down.
Here they had only one hundred and twenty children at school.
Small schools are kept in the hamlets.
A few years ago, some clergymen from Geneva came among these poor, simple-hearted people,
and under the disguise of Christian kindness, brought in among them during their visit,
the evil seed of the Socinian doctrine.
It took some root among individuals, and in one of their pastors.
By strict attention, and the Lord`'s blessing especially, they hope, however,
that it is now pretty much extirpated;
but it has rendered them very watchful over the visitors who come among them,
that the morals and sound Christian views of a people descended
from ancestors who have deeply suffered for the testimony of Jesus,
may not be corrupted.

I returned to La Tour the 23rd, in the evening,
and had a satisfactory religious opportunity at the house of their pastor, Bert,
which was attended by many of these interesting people.

Turin, 25th. I returned here last evening late.
Before my departure from La Tour I visited their hospital.
It was founded but lately, and much aided by the Emperor Alexander.
The circumstance which I had heard only in part before,
is now related to me by a valuable young man, the son of John Paul Vertu,
a banker in this city.
My dear friend William Allen was at Verona, about ten years since,
at the time of the Congress of the Sovereigns of Europe.
Being then with the Emperor Alexander,
their conversation turned on the subject of the oppression and persecution exercised,
at that time, against the Waldenses, by the then reigning King, and the Popish priests.
Allen requested the Emperor to use his influence with the King of Sardinia,
in favour of that portion of his subjects, and the Emperor desired him,
on his return to England, to visit these Waldenses,
and to send him a statement of the circumstances under which he found them.
William Allen did so; he found them in a suffering condition.
Much distress and poverty prevailed among them; their sick and aged felt it very heavily.
The Russian Consul here at Turin,
not having occasion then to send a messenger to the Emperor,
said he would constitute as such, any one whom Allen would recommend.
This young man, my informant,
very kindly offered himself to be the bearer of these dispatches.
That he might have immediate access to the Emperor,
Allen gave him a letter to Baron Wylie, his physician,
who also was a particular friend of ours when we were in Russia.
It was late when the young man arrived at Verona.
Wylie had him introduced into the apartments of the Emperor.
On reading the dispatches, Alexander was much affected; he was left alone.
Wylie, as usual, came in to pay his visit as a physician;
he was surprised to see the Emperor leaning his head on his hand near the table,
and in tears.
"`What has happened,`" said Wylie, full of emotion,
"`that you are under so much affliction?`"
On which, Alexander handed him Allen`'s letter, and said,
"`Read this and see if I have not reason to be afflicted!`"
The very next morning he endowed this hospital forever;
made some other benevolent provisions in favour of the Waldenses,
and took immediate measures to try to induce the King of
Sardinia to repeal his severe laws against them.
It is in consequence of his interference that the present
King has become better acquainted with this people,
their peaceable spirit and their industrious habits,
and that he treats them with greater mildness than
was the case under the administration of his predecessor.
Baron Wylie has continued to correspond with my friend, Wm. Allen;
through him we had repeated messages from the Emperor Alexander,
whose kind remembrance of us, after we left Russia, continued to the close of his life;
shortly before his death,
he commissioned Wylie to let us know that his warm Christian love flowed towards us.
Various reports have been circulated respecting the cause and manner of his death,
but the account sent by the Baron shortly after his decease is
one that may be depended upon coming from an eminent physician,
who for years had been the constant attendant of the Emperor,
and who was much attached to him;
he says that the fever with which the Emperor was attacked
came upon him whilst he was travelling in the low,
unhealthy parts of the Crimea, near the Black Sea.
During his illness his mind continued to rest on the Lord Jesus as his only hope;
his delight was to have the Scriptures read to him;
he also wished frequently to be left alone, there is every reason to believe,
for the purpose of prayer and spiritual communion with God.

Finding that the schools among the Waldenses are very destitute of books,
I have made provision for some to be sent to them,
among others the Scripture Lessons in French, and a quantity of Bibles and Testaments.
Here I had two meetings;
one of them was attended by several of those Roman
Catholics that I was with on my former visit here;
but I do not find that they have made much advance in vital religion;
the way to the kingdom is too narrow for them.
The few Protestants here are descendants of the Waldenses; some of them love the Truth.
