== Chapter LIX.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Lyons
* Avignon
* Aix
* Nismes
* Congenies, etc.
* Montpellier
* Touluse
* Brives
* Perigueux
* Bergerac
* St. Julien
* Bordeaux
* Bayonne

Returning from the valleys of Piedmont,
Stephen Grellet went to revisit the scenes of his early college life;
to mingle once more with the little company of those
who profess with Friends in the South of France;
and to pay a last farewell visit to his beloved mother and near connections
in the different places of their abode on his way to the borders of Spain.

[.offset]
In continuation of his diary he writes:

[.embedded-content-document]
--

Lyons, Eleventh month, 30th. I arrived here late last night, by the way of Suze,
Mont Cenis, and Chambery.
We travelled night and day.
The drifts and depth of snow on the mountains rendered our journey perilous.
We had some narrow escapes.
In one place the passengers had to assist in holding up the carriage,
when the wheels were sliding away to the edge of a precipice.

I have been today with several pious persons, who, though Roman Catholics,
now see beyond the Pope and the priests;
their minds are burdened with the many ceremonies and superstitions of that church;
but their difficulty is great also on meeting among
the Protestant professors so many relics of Popery.
They wish to find a people whose principles and conduct, both civil and religious,
harmonize with what they conceive the doctrines of the New Testament
require from every true disciple of our Lord Jesus Christ.
One of these men is Stanislas Gillibert, a physician.
Bredin is another spiritually minded man.
My mind is introduced into much seriousness by visiting this place.
Here I received part of my education at the college of the Oratorians.
Here, also,
the Lord graciously extended very peculiar visitations of his love to my benighted soul.
It was, indeed, as a light shining in a dark place to which I have frequently recurred,
with reverent gratitude and wonder at the gracious condescension.

Twelfth month, 1st. I was this morning with Monod,
son of that worthy man of the same name at Paris.
This young man was the pastor of one of the Protestant churches here,
but his spiritual views of religion, worship, ministry, etc.,
have induced him to withdraw from that office; he holds meetings, however,
which are attended by many of the most pious among the Protestants,
and also the Roman Catholics.
His exemplary life and the purity of the doctrine he preaches,
which has for its object to bring men to Christ through
the obedience of faith and the teachings of his Divine Spirit,
induce many to gather about him.
He has been a remarkable instrument in bringing the inhabitants
of several villages hereabout to see the errors of Popery,
so as to desert their priests, and to sit down under, or to wait for,
the teaching of the Spirit of Christ.
When he cannot be with them, they meet together to read the Scriptures.
This young man is very zealous and mighty in the Scriptures.
He reminds me of what is said of Apollos.
What endears him particularly to me is that he appears to have a heart
open to become more perfectly instructed in the way of the Lord.

2nd. I had a satisfactory, small meeting at Doctor Gillibert`'s,
with a few other seeking persons.
His wife appears to be a sincere inquirer after the Truth.
I had another meeting at Adolphe Monod`'s,
which was attended both by pious Protestants and Roman Catholics,
who desire to come to the Shepherd and Bishop of souls, the Lord Jesus Christ.
These have been very interesting meetings,
as have also been some private religious opportunities with these tender,
seeking individuals.

Avignon, 3rd. I came here by steamboat down the Rhone, with great rapidity.
The current is so strong that it takes them nine days to go up again to Lyons.
We passed under the bridge "`St. Esprit,`" near Valence, with great velocity.
It was not till very lately that they have carried
passengers on board whilst passing there,
it being considered so dangerous.
The bridge, however, is much improved from what it was formerly.
It is a hanging one, of brass wires twisted together like a cable, but much lighter,
and stands so firmly, that it hardly shakes at all, whilst heavy carriages pass over it.
The banks of the Rhone are very fine.
I know few rivers, anywhere, that surpass it.
I stayed but a short time here, where I was with three persons, to some satisfaction.
The inhabitants of this place are strong papists.
Some years ago it belonged to the Popes of Rome.

I travelled during the night to Aix, in Provence.
My chief object in coming round by this place was to see Francis Gourrier,
who was a lawyer rising into eminence; but, becoming convinced of the errors of Popery,
and having also religious scruples in regard to pursuing the practice of the law,
he devotes himself to a religious life and acts of benevolence; he is,
to a considerable extent, convinced of the principles of our Christian Society.
He corresponds with several persons in France, Italy and Sardinia,
who also are more or less brought to see the Popish errors, and to whom he is of service,
in informing or strengthening their minds in the ways of the Lord.
Several of these are priests,
and some of them are now exposed to suffering for the testimony of Jesus.
// lint-disable invalid-characters
One of these, the Abbé Cousin, of Monaco, has suffered much from his fellowpriests.
They cannot endure his reading the Scriptures to the sick in the hospitals,
or to the prisoners.
These sufferings have been blessed to him.
He has thereby been brought nearer to the Lord, and in His Light he has seen more light,
even the light of the knowledge of the glory and love of God, through Jesus Christ.
Francis Gourrier`'s father, and other branches of his family,
are also becoming convinced of the errors of Popery.
I had a satisfactory season with them.

--

From Aix he passed on to Nismes, and having visited a few persons there,
he proceeded at once to mingle, for the last time,
with the little company of Friends in those parts.

[.embedded-content-document]
--

Congenies, 6th. I came here last evening,
and was very kindly received by my valued friends, Louis Majolier and family;
this is the fourth time, in the course of twenty-eight years,
that I make a religious visit to the little flock in these parts,
who are called by the name of Friends.
Today being their week-day meeting, I attended it,
and at the close spread before Friends, for their consideration and approbation,
a concern that I have felt with weight to visit them in their families.
They united cordially with it, and I proceeded in the service.

9th, First-day.
Many of those professing with us having heard that I am here,
came to meeting from several distant villages.
I was glad to see Friends once more, but my heart was deeply affected,
and my spirit was sad,
on beholding the lukewarmness and apathy respecting the things that belong to salvation,
into which many of this people have fallen;
it seems as if some had entirely lost sight of what once appeared so dear to them.
As the meeting in the forenoon was attended by many who do not profess with us,
the word given me to preach was not so particularly for
the professors with us as was the case in the afternoon,
when the meeting was more select; it was a time of close searching of heart;
many appeared to feel it, and to see wherefrom they had fallen.
It was a season when the baptism of repentance was preached,
and when also many did confess their sins.
I had another meeting in the evening,
when many gave evidence of the contrition of heart they
were brought to by the many tears that they shed.
May the Lord bless this fresh visitation of his love.

Codognon,
14th. I continued diligent in my visit to the families
at and near Congenies till last evening,
having also meetings with Friends select, and others among the inhabitants,
who appeared to consider it a privilege to attend them,
Roman Catholics as well as Protestants.
Here also I had a meeting among these different classes of people.

Congenies, 16th. I returned here yesterday,
and went to visit the few professors with us at Calvisson,
and had a large public meeting.
Today I had three meetings here, it being First-day;
those in the morning and afternoon were attended by Friends
and the people at large from other towns and villages.
They were seasons favoured by the Lord`'s presence and power.
There is considerable openness in these people to hear the declaration of the Truth.
O that there may be also a submission to it!
In the evening the meeting was more select, being for Friends only;
there was greater solemnity prevailing over us than
had been the case on most of the preceding occasions;
many appeared sincere in their desire to renew their
covenants with the God of our life and of our salvation;
may it be sealed by the offering up of the whole heart as a sacrifice unto Him!

The next day, accompanied by Louis Majolier, I went to Fontanaise;
the meeting was well attended by Protestants and Roman Catholics,
as also the succeeding one at Quissac.
The next was at St. Hypolite, where, on preceding visits,
I had two very remarkable meetings.
Most of those I knew here are deceased.
Our friend Paradon, who resides a little out of the town,
had undertaken to have a place for holding a meeting provided,
and also to give notice of the same;
on conferring with the principal inhabitants they had concluded
it should be held in their largest Protestant meetinghouse,
or temple, as they term it.
The Protestants here are numerous.
On our arrival we were met by several of the clergy;
as I was about entering the meetinghouse,
one of them not only offered but pressed me to put on his black gown, surplice, etc.,
which shows how unacquainted he is with Friends`' principles and Christian testimonies;
I had then but a short time to explain my conscientious reasons for declining his offer,
but after meeting I had a full opportunity to do so.
Their spacious meetinghouse was well filled, and the people behaved with seriousness.
The subject on which I was led to speak was salvation by our Lord Jesus Christ,
through faith in his name and obedience to the dictates of his Spirit.
I had after that a long opportunity with four of the Protestant ministers.
One of them, a zealous young man,
was disposed to enter into doubtful disputations on non-essential subjects,
which were easily put by, and we parted in love.
We went to Paradon`'s, a mile out of town, and had a meeting there.

The following day, on our way back to Congenies, we stopped at Crespian,
and had a meeting there;
the day after we attended their Two-month`'s Meeting at Congenies,
at which Friends very generally were gathered, from every part in this section of France.
It was a solemn meeting.
We parted from one another, never expecting to be again together in this mutable state;
we felt the fulness of Gospel love to flow amongst us.
I leave these dear people in hope that the Lord will care for them and watch over them,
and not suffer the enemy again to prevail.

St. Gilles, 25th. I arrived here yesterday afternoon,
in time to visit four families of Friends, and today I had two meetings.
One was held in the Temple of the Protestants.
Le Blanc, their pastor, a pious man, whom I have heretofore known,
hearing that I was here, sent me a very kind and Christian-like note,
stating that he was necessarily prevented from coming himself to see me, but that,
if I apprehended it my religious duty to have a meeting among the inhabitants,
he knew of no place more suitable than their meetinghouse,
nor any day when I could see more of the people collected together than this afternoon,
when he was very free, in the love of Christ, to omit officiating himself,
though this is a high-day among them ("`Christmas`"); and that if I accepted the offer,
he would give notice of it at the close of their service in the forenoon.
I considered the matter weightily, seeking for the Lord`'s direction.
It appeared best for me to accept the offer.
It seemed indeed to be the Lord`'s doing,
for I had felt my mind strongly drawn towards the people here,
and there appeared no probability of my being able to see them together.

The meeting I had in the forenoon was held in the Friends`' meetinghouse.
It was attended by those who go under our name, both here and in the neighbourhood.
I have some hope of them, here also,
that they may henceforth walk with greater circumspection and watchfulness.
The meeting in the Temple in the afternoon was very large; it was a mixed company.
I thought there were pious persons present,
to whom the word of comfort and encouragement was preached;
but there were others with whom I did earnestly plead of righteousness, temperance,
and judgment to come.
Whilst I was proceeding, my own heart being much affected with the awfulness of it,
I stated how solemn it was thus to join in company
with those who are met together to worship God,
and publicly to acknowledge and bow down in spirit before Christ Jesus,
the Saviour of sinners, who came into the world for this very purpose,
that he might save us from our sins;
but that possibly whilst some keep this day as a memorial
of the coming in the flesh of the Eternal Son of God,
thus to be unto us a Saviour and Redeemer, they have concluded on,
and made preparations to spend this very evening and night, perhaps,
in a riotous and sinful manner.
As I was uttering this, a man fell down from his seat on the floor;
there was some bustle for a short time; they carried him out, and I continued to speak,
a considerable increase of solemnity appearing over the meeting.
After the conclusion, I heard the people say to one another, "`He is dead, he is dead.`"
I was then told that this very man had made extensive
preparations for a sumptuous banquet this night,
when a variety of diversions were to be introduced: that,
on coming he had boasted how he would honour the Lord, and sanctify this day,
by going to a place of worship first, and then close it in feasting and revelling.
Some per sons, hearing him speak so, had reproved him for it,
which he answered by impious expressions.
The people appeared struck with astonishment at the awfulness of the event.
I received a deputation from the inhabitants in the evening,
requesting that I would have another meeting with them,
but I did not feel it my place to do so.
To the Lord and his Spirit I leave and commit them.

Nismes,
26th. I came here this forenoon and had a meeting at an asylum for Protestant girls.
One of our Friends, a young woman, Justine Benezet, is at the head of it.
She keeps her place as a Friend, and is beloved and respected by all.
The managers of the establishment, several of whom are clergymen,
treat her with all respect.
They are so convinced of her genuine piety,
that they do not object to her holding meetings in the asylum,
after the manner of Friends.

The next day I visited the prisons at the castle,
and had several religious opportunities with the prisoners;
some of these were distressing seasons to me, for I was among very depraved men,
hardened in vice and wickedness.
Their hearts appeared to be of the nature of the flinty rock.
In the evening I had a large public meeting; it was very quiet;
the Lord enlarged me among them in preaching the Gospel of life and salvation,
and the hearts of many seemed to be opened to receive,
or at least to acknowledge to the Truth; many tears were shed;
may the Lord bless and prosper his own work!

28th. Early this morning several pious persons came
to my inn to bid me farewell in the Lord;
we sat down together and were comforted in his presence.
He condescended to bless and break a little bread among us,
and to hand us a cup of consolation.

--

After this parting opportunity Stephen Grellet set off for Montpellier,
and arrived there the same evening:

[.embedded-content-document]
--

Lyssignol, one of the Protestant clergymen here with whom I have long been acquainted,
came soon to see me; he maintains his integrity in the Truth,
but he has his trials from his colleagues,
who have made many attempts to introduce into their schools sentiments calculated to
alienate the youthful mind from the simplicity and purity of the Gospel of Christ;
they also promulgate Socinian views from the pulpit.
I have endeavoured to encourage him to maintain his ground with faithfulness,
as a servant of the Lord Jesus Christ.
It is the practice here for the Protestant clergy every week to
interchange the places of worship in which they officiate;
thus it gives to the people at large an opportunity to make
their election of what kind of doctrine they choose to hear;
it would appear from this that the greater part are in favour of sound Christianity,
for the houses in which Lyssignol officiates are generally full,
and the others are but thinly attended.

The next day I visited their schools and prisons, also several pious persons,
and left Montpellier that evening for Toulouse,
which I reached after travelling two nights and one day.
We had a violent storm on the way; the rain fell in torrents,
so that both horses and carriage were well nigh being washed down the rapid streams,
caused by the rain on the highway.

Toulouse, First month, 2nd, 1833.
On presenting myself at the Police-office the day before yesterday with my passport,
I found among the chief magistrates present a good deal of seriousness,
and a desire to obtain information on Friends`' Christian principles and peaceable testimonies.
The subject of war is one of peculiar inquiry and interest to some of them.
Very nearly connected with this is faith in God, and in our Lord Jesus Christ,
the Prince of Peace.
If we believe truly in Him, we must necessarily keep his commandments.
This is his commandment, that we love one another as he has loved us.
How can then the servants of the Lord Jesus fight?
Their weapons are not carnal, but spiritual; their sword is that of the Spirit;
their whole armour is that of Light.
Many will assent to these Gospel truths, but the obedience of faith is lacking in them.
In the evening I had a satisfactory meeting, attended mostly by Protestants,
and a few serious Roman Catholics.

Chabrand, the Protestant minister, long known to me, continues to be a useful man.
He is spiritually minded,
and his ministry has the tendency to draw the attention
of his hearers to the influences of the Divine Spirit,
on their own hearts.
The Courtois, also, continue firm in their love to the Truth,
and are indefatigable in their labours to spread the Scriptures
and religious tracts among the Roman Catholics,
in many parts of France, and Spain also.
They have many colporteurs employed in that work.

3rd. Yesterday I visited three prisons.
I was much grieved in some of these visits.
The prisoners have free access to wine and spirituous liquors.
Some, under sentence of death, which is to be executed next week,
had bottles of strong drink with them.
I had, however, some satisfaction in one prison, where I found about sixty young men,
who are to be sent to the army in Algiers.
They seemed to feel their situation, and were tender.
I supplied them with Bibles and Testaments, which they appeared to value.
I had another religious meeting that evening with the inhabitants.
I felt very low, yet the Lord enabled me to minister to them.

I called today on several pious persons, both Roman Catholics and Protestants.
Others came to see me at my inn.
Some of them are in a seeking, tender frame of mind.
I feel much for them.
To the Lord and his Spirit I direct them.

--

A wintry journey of two nights and one day brought him once more to Brives,
where he writes:

[.embedded-content-document]
--

5th. I find my beloved mother in a very tender state of mind, green in old age.
Her heart seems to be full of love to the dear Saviour.
She appears weaned from a dependence on the priests, or outward observances.
Her heart is fixed, trusting in the Lord alone.
It is rare to meet with any one at her advanced age,
who retains such bright mental faculties.
She can relate occurrences of very ancient date, told her by her grand-parents.
Her grandfather was ninety-six years old when he died.
When he was a boy, the plague prevailed to such a degree at Limoges, that,
towards the last, there were not living persons left sufficient to bury the dead,
and the streets of the city were overgrown with grass.
Her grandmother at the age of eighty had a fall from her horse,
which she survived about six years.
Her own mother was also very aged when she died.

15th. There are no Protestants at all in these parts; my intercourse, therefore,
is entirely with the Roman Catholics;
I have had several religious opportunities with these at my dear mother`'s,
the Baron Le Clerc`'s, my brother-in-law, and also at the houses of others.
Many of the people were at meetings that I held here on my former visits;
they know therefore how to conduct on such occasions.
This time the priests have not interfered with me.

I have paid a satisfactory visit to the nuns at the hospital;
several of those that I met here before are yet living,
and have received me with Christian affection, particularly their aged Superior,
called La mere Cecile;
the religious opportunity I had with them was solemn and contriting; several of them,
I believe, hold frequent silent communion with God,
and amidst the round of forms that their religious order requires, they enjoy Christ,
the substance; they know where prayer is to be made,
and in the temple of the heart are worshippers in spirit and in truth.
This is the fourth visit that I have made them in the course of twenty-eight years,
and every time I have been with them my soul has been edified; moreover,
I find that those who, at the time of my first visit,
were young and of small religious experience, have grown in the Truth,
and in the increase of spiritual mindedness.
My soul does magnify the Lord my Saviour,
who has brought me to the knowledge of some among the various nations of the earth,
outwardly joined to separate religious names and communities, priests, monks, nuns, etc.,
to whom my heart is united in the Spirit,
and whom I can salute as disciples of the Lord Jesus Christ; by-and-by, I trust,
all these will be united as fellow servants of one Lord in the Church triumphant,
harmoniously singing praises, and ascribing glory to their God and Saviour.

I have been brought under very deep exercise respecting
my future proceeding towards Spain;
the time to enter that nation appears now to have arrived; yet I am told,
from place to place, that there is no possibility for me to obtain admittance there,
or to escape with my life if I do; the effusion of blood among them appears to be great,
and acts of much cruelty are said to be perpetrated;
but my religious concern to go there remains.
Direct my steps, O Lord!
Suffer not thy poor servant to be deluded in any of his movements,
but lead me by thy counsel; then,
into thy hands and to thy sovereign will I resign all the result;
my outward liberty or my life, O Lord, are in thy hands!
I entertained the hope that my beloved friend, William Allen,
would have it laid upon him from the Lord, to join me again,
so as to proceed together to Spain, but I hear nothing from him on that subject; but,
O Lord, be thou with me; let thy pillar of a cloud by day and of fire by night,
direct my steps and protect me!

Perigneux,
16th. I took a solemn farewell last evening of my much beloved and honoured mother,
also of my dear sister Le Clerc, and numerous family;
we were all prostrated together before the Lord in our spirits,
when on bended knees my soul was poured forth in fervent supplication for them.
I parted from my mother, and she from me,
as never expecting to see one another again on this side of eternity,
but in the hope that by the mercy of God in Christ Jesus,
we may be joined together again in the world of spirits
and the realms of everlasting blessedness.

I set off at midnight by the public coach, and arrived here in the forenoon.
I have here a very dear first-cousin; her name is De la Ribiere;
she is a woman of great piety, and has been so for many years;
her only son is the Commandant-General of the Gendarmerie in the department;
they invited their piously-inclined friends, all Roman Catholics,
and I had a religious meeting with them; their hearts, as well as their ears,
were opened to the Gospel truths given me to proclaim;
it may be said to have been a good meeting; none of them, except my cousin,
had been at such a meeting before.

Bergerac, 17th. I left Perigneux at midnight again;
it is not from choice that I thus travel in the night,
but I must keep the hours at which the coaches set off.
I arrived here at ten a.m. Here reside my sister De Boise and her children;
it has been very pleasant to mingle once more with them, also with several Protestants;
some of them have passed under severe afflictions;
the Lord gave me a word of comfort and encouragement for them.

I went thence to St. Julien, where my brother, Peter de Grellet, resides at present;
a considerable number of his neighbours met us that afternoon; they had never seen,
and most of them had never heard of a Friend,
but the Lord opened a door for me to preach the unsearchable
riches of the Gospel of Christ.
My visit to my dear nieces here was also very satisfactory.

I then returned to Bergerac, and met with some of the Protestants, who are numerous here;
there are about seven thousand of them; they are well supplied with Bibles;
a considerable number of these have been given or sold to the Roman Catholics, but,
in many instances, the priests have succeeded in obtaining them, and have destroyed them;
through the medium of their disguised agents also they have obtained many copies,
and committed them to the flames.

Bordeaux, 24th. I arrived here yesterday;
my mind is under such weight of exercise for Spain,
that I have no qualification to enter on any religious engagement in this place,
where also I hope to be again,
should the Lord spare my life from falling a sacrifice on the way I am now going.
"`Thy will, O Lord, be done,`" is the frequent aspiration of my spirit.

Bayonne, First month, 25th. Here I am on the frontiers of Spain;
I left Bordeaux early yesterday morning.
Among my fellow-passengers in the diligence was a Spaniard, the Marquis de Matta Florida,
with his wife and sister.
His father was one of the King`'s ministers,
but had been obliged to flee to France with his family, where he died lately.
The young Marquis, having some encouraging accounts of the state of the country,
has come thus far to see if it is safe for him to enter Spain again.
I find many Spaniards at Bayonne.
It is said that the factions that had the rule, and have shed so much blood,
are now subdued.

I also received, this day, a letter from my dear friend, Wm. Allen,
stating that he feels himself so forcibly brought under the weight of
religious concern to join me in my Gospel engagements in that nation,
that he expected to be able to leave London tomorrow, the 26th,
and join me here as soon as so long a journey will permit him.
How great is the Lord`'s goodness!
I arrive here surrounded with difficulties and discouragements,
and he opens a bright path before me.

There is a quarantine to be performed here before any one can enter Spain,
and another after passing over the frontiers.
During my detention dear Allen will have time to come.

Second month, 3rd. I have met here several serious persons, Protestants and Catholics,
some of whom are Spaniards, with whom I have religious opportunities.
Some of them are of a seeking mind.
One of these is the Sous Prefet, a man of a liberal and benevolent spirit.
I felt much distressed when I came here,
on beholding the multitude of beggars in the streets.
They are unwilling to do any work at all,
whilst they can obtain a precarious and scanty living by begging.
I also observed that, two days in the week, the number was greatly increased;
for they came in from the country, miles round,
and I noticed that benevolent men or women sat at their doors with bags of copper money,
and gave to the beggars as they came to them, as long as their bags held out.
By this mistaken benevolence in alms-giving, the system of begging is encouraged.
I thought that this could be remedied,
especially as I had visited their House of Benevolence,
which is a spacious but unoccupied building; I thought that if those alms,
given by the citizens, were properly administered, much more good would be done,
better provision made for the aged and the sick,
and work found for those that say they have none;
thereby immorality and sin might be repressed.
I formed my plan accordingly, and submitted it to the Sous Prefet,
who was so much pleased with it,
that the chief magistrates in the town were called together, and, with their approbation,
it was concluded to call a meeting of the benevolent citizens;
for nothing can be done availingly without their cooperation.

6th. Dear Allen met me the 3rd inst.
in the evening;
he has been almost constantly on the road since he left London the 26th of last month.
We have met in the fulness of Gospel love; we rejoice together in the Lord,
and we are also permitted to participate in the encouraging
hope that through His assistance we may endure,
with Christian patience and resignation,
whatever suffering may be permitted to come upon us during
the service we are about to engage in in Spain.
Dear Allen enters cordially into the plans formed to endeavour
to alleviate the misery of many of the people here,
and to put them in a way to support themselves by their industry and not by begging.
The principal citizens met last evening, also the public authorities;
the plan formed was approved by them;
the mayor and others were appointed a committee to see that it be carried into execution,
and, as soon as they are prepared for it, begging will be prohibited,
work given to those destitute of it,
and the wants of the sick and the aged liberally provided for.
This conclusion being now formed is a great relief to my mind.

8th. Official information is received today from Madrid
by which our quarantine is lessened one-half of the time.
These days past, we visited their prisons and schools.
We had also two meetings with the Protestant community,
which some of the Roman Catholics attended.
Joseph Veisaz is very much devoted in spreading the Scriptures,
particularly on the Pyrenees among the Basques,
into whose language the New Testament is translated.
We had a very interesting meeting at his house with some tender-minded people.

--

Their detention by the quarantine on the French side
of the Spanish frontier had now ceased,
and they were on the point of leaving Bayonne.
A few hours before their departure they received a deputation from the Jews,
respecting which Stephen Grellet remarks:

The Jews are a numerous and respectable body;
they had heard of the society organized to prevent public begging,
and they came to request that we would have a meeting among them,
and organize a Benevolent Society.
They do not reside in Bayonne, but on a beautiful spot near it.
They are generally wealthy, and have no poor among them,
for they give employment in their families to such
as might otherwise be dependent on public charity.
We did not see their need of such an institution; on the contrary, as they told us,
their hearts and purses are open to minister to the wants of suffering Christians.
We had a satisfactory opportunity with them.
