== Chapter LX.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Spain
* Madrid

Stephen Grellet now entered upon an entirely new field of labour.
In company, once more, with his faithful friend, William Allen,
he had crossed over into Spain at a time peculiarly
favourable to the accomplishment of his mission.

The attempts of Don Carlos, at the head of a powerful and bigoted party,
publicly to assert his claims to the succession against the right of the young Infanta,
had been defeated by the King`'s unexpected recovery from a serious attack of illness,
after he had been announced as already dead,
and his body had been exposed in one of the halls of the palace.
Queen Christina had regained her ascendency over the mind of her husband;
Ferdinand had dismissed Calomarde, and called Zea Bermudez to the ministry;
a short calm had succeeded a time of great political excitement,
and some good measures had been determined on and were in progress of being carried
into execution when Stephen Grellet and W. A. entered the Spanish dominions.

They arrived at Irun, the first town in Spain, on the 11th of Second month, 1833,
but were obliged to perform another quarantine before they could proceed into the interior.

[.embedded-content-document]
--

Irun.
Second month, 16th. We expect to be released today from this quarantine.
We are with a large company of Spaniards and Basques, crowded together.
Some are very noisy,
but in our small private chamber dear Allen and I have found a little sanctuary.
Our seasons of retirement, morning and evening particularly,
have been times of Divine refreshment.
We have also been diligently occupied in writing;--my time
had of late been so taken up that I could not do it.
I have now written various letters to some of the
pious persons I have already visited in Prussia,
Saxony, Germany, Switzerland, Sardinia, as well as in England and America.
Last night we had a violent storm of wind, rain and lightning;
the wind was so strong as to upset the heavy diligence whilst on the road near here.

We left Irun the 16th, about noon.
We tarried a short time at Tolosa, and again a few hours at Vittoria,
where we paid a satisfactory visit to a person for whom we had a letter of introduction.
It is a handsome city.
Part of our road from thence, through Miranda,
is so mountainous that we had ten mules to our carriage,
and repeatedly two yoke of oxen besides, to assist in taking us up the mountains.
The dangers on these roads are great.
We were favoured to escape any accident,
and preserved from falling into the hands of robbers,
who are numerous and regularly organized under their chieftains.
Not a week passes but robberies are committed on this road, and sometimes blood is shed,
when any attempt at resistance is made.
It frequently happens that some of these banditti
are your fellow travellers in the diligences,
and, at the places of stopping to change horses or mules or for taking refreshment,
they inform their confederates of the prospect there is of making a good prize,
and they lay in wait for the travellers in such strength as to overpower them.

--

They arrived at Madrid on the 20th of Second month,
and soon entered upon the object of their mission.

[.embedded-content-document]
--

22nd. Since our arrival at Madrid we have been in company with a few well-disposed persons,
through whom we may expect to become acquainted with others.
We were today with Cambrone, a Jurisconsult of eminence, and a conscientious man.
He has, on this ground, refused to accept places of considerable importance,
both here and in Cuba.
He is strongly opposed to slavery.
He, and his particular friend Solon,
another eminent lawyer with whom I became acquainted at Toulouse,
are now preparing works against slavery, both under this government and that of France.
They have also in view to publish periodicals to spread
light and interest among the people on this subject.
These two men are not merely philanthropists, but Christian believers also.

Through the medium of Sir Henry Addington, the British Ambassador,
we receive information that the Count D`'Ofalia, the Minister of the Interior,
has heard of our arrival, and wishes to see us this evening.
We suppose he may have heard of us through Count De Rayneval, a French peer,
and Ambassador to this Court.
His particular friend, the Sous Prefet at Bayonne, had written to him about us,
and also given me a letter for him.

23rd. According to appointment we were last evening with Count D`'Ofalia;
he was some years since Ambassador to the United States,
when he obtained considerable knowledge of the Christian
principles and testimonies of our religious Society.
He received us with courtesy,
and kindly inquired in what he could serve us in promoting the object of our coming here.
We had previously felt our minds drawn to visit some of their prisons, hospitals, etc.
We have often found that this kind of visits bring
us to an acquaintance with serious and pious persons,
to whom we might not be able otherwise to have access.
He at once said that he would prepare orders for our admittance to all such places,
and requested us to call upon him again tomorrow morning.

We next went to Vanness, our American Ambassador here.
I knew a brother of his in America.
His wife is a pious woman; before her marriage she resided in New York for a few years,
and knew some of our Friends; she had hoped, she said, that we would come to see her;
as she was riding out she had seen us in the street;
by our dress she recognized us as Friends,
and she could hardly resist stopping the carriage to speak to us;
we had a satisfactory opportunity with her and her family.
It was concluded to hold a meeting for Divine worship
at their house next First-day morning.
We next went to Sir Stratford Canning`'s, who is Ambassador Extraordinary here,
besides Sir Henry Addington, the regular one.
Allen had letters for him from London,
and it appears that he had received some others recommending us to him;
both he and his lady are serious persons; our intercourse with them was to edification;
we had also with them and their family a refreshing religious opportunity in the evening.

24th. This morning at eleven o`'clock we went, as appointed, to the Count D`'Ofalia`'s;
he manifested great freedom in conversing with us on subjects of benevolence and piety,
on the distribution of the Scriptures, and the state of religion in Spain,
which he acknowledges to be very low; he told us that he was yesterday with the King,
and spoke of us to him;
he informed him also of our intention to visit their prisons and other institutions;
the King directed that an order for our admittance to any place
we may wish to visit should be made out in his own name;
he also requested that we would furnish him with any remarks we may make in these visits.
How remarkable that the Lord should thus set an open door before us, in places where,
but a very little while ago, anarchy prevailed,
streams of blood flowed and the prisons were crowded with innocent victims.
We are told that, in some parts of this nation, the tyrants in power,
after putting some of their victims to a cruel death,
made out bills of the expenses attending the execution,
which they obliged the mournful widows to pay.

We next went to attend the meeting appointed at our American Ambassador`'s;
some persons who had been invited attended besides the family;
the time of our sitting in silence together to worship the Lord was very solemn;
what sublime description does David give of such a solemn engagement,
"`Give unto the Lord the glory due unto his name,
worship the Lord in the beauty of holiness!`"
Vanness`'s wife appeared to be sensible of the solemnity of the occasion;
she was broken down in her spirit, and shed many tears.
Dear Allen and I had words of consolation and encouragement to communicate to them.
Cornelius, the eldest son of the Ambassador, is a serious youth.

25th. Accompanied by Cornelius Vanness, as our interpreter,
we visited several of the prisons, also the orphan and poorhouse.

26th. We visited the foundling hospital, which is a large establishment;
they admit yearly from eleven to twelve hundred children.
It is at present under much better regulations and care than it used to be.
The Sisters of Charity have the internal care of it,
under the direction of a committee of about forty of the principal females of Madrid,
several of whom we met;
they not only accompanied us through the several departments of this large establishment,
but some of them were our interpreters.
The Duchess de Gorr, their President, was one of them; she is now a widow;
she has learned in the school of affliction;
her husband was one of the first Grandees in Spain.
Two priests accompanied us also;
they were serious under the several religious communications we made during these visits;
we had an opportunity with the nuns, and lastly with the female members of the committee;
they tell us that the Queen is now one of their number,
and has lately made great improvements in the management of this house.
I have not seen any of the sort kept more clean.
The mortality is, nevertheless, great;
during the first seven years it amounts to seventy-eight per cent,
and six per cent more from the age of seven to twenty-one years;
those who survive receive a good education,
and are instructed in several trades according to their capacities.

27th. I was ill last night, caused, I suppose,
by a large pan of charcoal left in a room between my chamber and that of Wm. Allen.
They have no fireplaces here,
and the only way they warm themselves is by bringing in coal in this manner.
My head was much affected; I had hardly strength to rise;
on going to Wm. Allen I found him affected in a similar manner;
but we were both relieved by the fresh air.
We visited today their great hospital,
which is a stately building erected by the former King; we found in it 1305 men,
and nearly as many women.
The men are under the care of the Brothers of Charity,
and the women under that of the Sisters;
though in both places a tender care appears to be bestowed on the sick,
yet the comfort and the cleanliness of the female department far exceeds that of the men.
We had interesting and solemn opportunities in some of the wards,
especially among the convalescents and the Brethren and Sisters of Charity.
The average number of patients admitted yearly amounts to sixteen thousand;
the average number of deaths is ten per cent.

After that we visited a nunnery used chiefly for training young women who,
from pious motives, devote themselves to caring for the sick,
in hospitals and other institutions.
They are mostly of respectable families,
and as there is no compulsion to induce them to adopt this manner of life,
nor to continue in it, they come here from religious or benevolent motives.
It is very rarely that any of them return to the world,
though sometimes they go for a few weeks or months on a visit to their near relatives.
There is connected with this nunnery a hospital for incurables.
Twelve aged nuns and their Superior, have the care of the young nuns.
Some of them, and the Superior, speak French, and were our interpreters in the sick wards.
We thought that some of the poor afflicted inmates evinced
religious sensibility and gratitude for our visit.
Their chapel stands in the centre of the wards,
by which we were brought several times into straits;
many wax-lights were burning on the altar,
before which we had to pass in going from one ward to another.
On entering the chapel some of the nuns,
dipping the finger in a basin containing their "`blessed water,`"
handed it to us to make the sign of the cross as they did.
I succeeded in making them understand, quicker than I expected,
our reasons for not conforming to such a practice; but,
when we passed close before the altar, they all knelt down, and those by me,
taking hold of my hand, urged my doing the same by saying,
"`The holy sacrament (i.e. the consecrated wafer) is now exposed.`"
I could then only say, "`By and by I will tell you why we cannot do this.`"
And though our going in and out of the wards brought us repeatedly through the chapel,
they did not ask us again to bow down to the altar,
and they finally omitted to do it themselves,
neither did they take any notice of our keeping our hats on except when
we were engaged in proclaiming the Gospel of Christ to the sick.
Our visit to these being accomplished, I said to the nuns,
"`Now I will explain to you what are our reasons for not using your blessed water,
as you call it,
or bowing before your altar;`" upon which the Superior brought us to her apartments,
where, with most of the nuns, we sat down.
They very quickly understood that the sign of the cross, as it is called,
cannot be the real cross;
or that cross that a man must bear if he will be a disciple of the Lord Jesus Christ.
The Superior said, "`My dear father used to speak exactly so.`"
Then respecting the chapel, the altar, the burning of tapers upon it,
the consecrated wafer to which they bowed and worshipped,
I opened to them those various subjects, according to the Scriptures;
a wide door also was open to preach to them the Lord Jesus Christ:
the nature of the offering that he has made of himself, once for all,
for the sins of the world; that the temple in which he is to be received by faith,
is that of the heart, where he is to be found ever present,
and to be worshipped in spirit and in truth;--there also it is that the true light,
Christ the Light of life, is to shine with brightness.
Dear Allen spoke excellently on some of these subjects.
The nuns seemed to feel deeply, and several times the Superior said again,
"`My dear father, my pious father, used to speak to us exactly so.`"
We parted from them in Christian love, and they evinced much tenderness.

28th. We were today at an institution for "`female incurables,`"
under the care of a nunnery of the same order.
We had a full and satisfactory time with the nuns.
Some of them, we think, are spiritually minded and of exemplary piety.
Then we visited a hospital for the King`'s servants; every
attention of course is paid to them.
We went afterwards to a prison,
which is in a cleaner state than some of the others we have been in,
but we are deeply affected at the insensibility and
hardness that many of the wretched prisoners exhibit.

Third month, 1st. We were this morning with the Count D`'Ofalia.
He appears fully disposed to attend to our suggestions respecting the prisoners,
particularly to have the boys separated from the men,
to have better ventilation in the prisons,
and to prevent the introduction of intoxicating drinks amongst them.

We were with the Count and Countess Lista, who generally reside at Grenada,
where they have large possessions, and where they endeavour, amidst many difficulties,
to promote a reformation in the corrupt morals of the people;--they have introduced schools,
in hopes that this early care of the youth, may, under the Lord`'s blessing,
bring about with these what they cannot effect with the parents.
Whilst we were with them several persons came in, viz., Vanness, our Ambassador,
Colonel Downie, Colonel Flinter, and others.
Flinter was lately Governor of the Island of Porto-Rico.
He is a great friend to the emancipation of slaves from their cruel yoke.
Our conversation turned on serious subjects,
and way was made for our having some religious service among them.

2nd. Accompanied by Cornelius Vanness,
we began our visit to the great prison early this morning.
On entering it the keepers told us they had orders to show us everything,
and to impart to us all the information we wished;
we knew that the order we had from the King required this, but,
as they have here prisoners of state,
special directions had been sent that we should be admitted among them.
We went first into a spacious yard, where many men and boys were promiscuously together,
guilty of all sorts of crimes, even the most atrocious;
many appear to be men desperately wicked; during the night they are shut up in dungeons.
Their punishment when unruly is to be detained in those dungeons for some days together.
Many of the prisoners, both men and women, are placed here for smuggling:
the contraband trade in tobacco especially, is carried on to a great extent,
and much blood is often shed between the officers of the government and smugglers.
The prisons for the women are above those of the men.
There is no classification whatever among any of them.
We felt much for some who are confined on suspicion only,
and are mingled among the worst of characters, though they are most probably innocent.
We hope to obtain their release.
We next went among the prisoners of state, some of whom are guilty of many crimes,
and have sent to the scaffold virtuous and valuable characters; but,
instead of being treated as they treated others when they had the power in their hands,
they are kindly used; some are even allowed to have their families with them,
especially their wives or daughters.
They are mostly of the nobility; we saw some generals, counts, dukes,
late ministers of state, etc.; some of these, however, though treated with kindness,
are closely kept in their separate apartments, "`all secret,`" as it is called,
having no communication whatever with any body, not even by writing;
but we were admitted among them.
Some appeared to be much dejected; and well they may,
if they are duly sensible of the blood-guiltiness that lies upon them;
way was open to direct some of them to Christ and to his Spirit, the faithful witness.
I was greatly annoyed by a monk, who said he had been in the United States,
and pretended to be acquainted with our religious principles; he had a wicked look,
bold and impudent; on inquiry,
we find he is imprisoned and tried for the murder of his bishop,
after which he seized on his papers, went to Rome and succeeded,
by false representations, to be made a bishop in the room of him whom he had murdered;
on his return to take possession of the bishopric, his crime was detected,
and he was put under confinement; but he succeeded in making his escape,
and fled for refuge to the King`'s palace;
but the King ordered him to be delivered up to public justice.

From this prison we went to the Countess de San Lorenza`'s; the Duke,
being under an attack of the gout, could not see us.
They are of the first Grandees of Spain.
They have been in England;
what they saw there has tended to expand their views in regard to works of benevolence,
which they endeavour to practise on their large estates;
their minds are also enlightened, so as to be convinced of many of the errors of Popery.
The Countess, and others with her,
appeared desirous to know more of our religious Society and its Christian testimonies;
we had an interesting time with them.
She gratefully received some books we furnished her with on those subjects.
We find among various persons a great openness for the distribution of religious tracts, etc.

In the evening we were at the Count de Teba`'s;
both he and the Countess are persons of serious minds,
inquirers after the things that pertain to salvation;
they had invited several of their friends like-minded with them;
they appeared to understand the necessity of silent retirement and waiting on the Lord;
it was an edifying visit.

In passing the streets of Madrid,
we have several times gone through the spacious square where,
under the hands of the Inquisitor, many victims have perished in the flames.
The place, like that at Prague, is surrounded by stately buildings,
with numerous balconies to accommodate the many spectators of those
deeds of darkness and cruelty perpetrated under the mask of religion,
which they even called "`Acts of Faith.`"
In the centre of these stately,
palace-like buildings is one over the balconies of which hangs a crown,
designating it as the place occupied by the Royal
family during those exhibitions of darkness,
cruelty, and superstition, devised by the devil and his agents.
In front of this balcony is the flagstone pavement,
on which the flames were kindled to devour the victims.
The present King, a few years since, put an end to these deeds of cruelty; but,
had the late faction prevailed,
it is apprehended they would have renewed them in all their horrors.

3rd. By appointment we visited, this morning, the Count Zea Bermudez, the Prime Minister;
we had a very satisfactory opportunity with him; we did not recognize him at first,
but he knew us well; he was at Petersburg when we were there,
and met with us at several places.
He is well aware on what religious ground we endeavour to move,
and that we have for object the present and everlasting well-being of those we visit;
he is therefore disposed cordially to promote our various engagements in this kingdom.

On our return we stopped at Colonel Downie`'s,
who has come several times to our lodgings to see us.
We had given him a Bible, which we found him engaged in reading.
He told us that, on coming once into his chamber,
he found one of his Spanish servants reading that Bible.
He was greatly affected and said,
"`Our priests never let us know the contents of this good book; and no wonder,
for it proclaims all their doings in their churches to be nothing but idolatry;
I would give,`" he said,
"`all I possess in the world to obtain such a treasure as this Bible.`"
We presented him with one.

In the afternoon we had a meeting at Sir Stratford Canning`'s,
with his family and a few others.
They appeared to appreciate the privilege of waiting on and worshipping the Lord.
In the evening, our meeting at the American Ambassador`'s was pretty numerously attended.
A number of Spaniards were there.
Some we had not seen before.
As they all understood French, I needed not the help of an interpreter.
Dear Allen attempts at times to speak in French also.
Some of these services are attended with deep exercise.
How wonderfully adapted are the great and important
truths of the Gospel to every condition of man!
We had a solemn meeting.
Several parted from us under much seriousness.

4th. Visited a prison for such as have been sentenced to a term of confinement
from three months to three years;there were two hundred and eighty-four men,
and about sixty women.
They are enlarging this prison so as to be able to classify the prisoners,
which is much wanted; for now,
boys and young girls are promiscuously mixed with criminals of every age.
We saw there a boy sent by his mother as to a place of correction;
but he is in the way of returning to her tenfold worse than when he came in.

We dined at Count de Teba`'s, with a pretty large company of Spaniards of rank.
These are trying situations to me, very humiliating;
but they are seasons when the Lord gives opportunity to exalt his blessed Truth,
and the testimonies thereof.
I dare not flinch from such exposures; for this very purpose he has sent me here,
to exalt his great name.
We had a full opportunity to proclaim the Truth among that assembly,
and to direct them to Christ and to his Spirit.

5th. We went this morning to the French Ambassador`'s, Count De Rayneval.
He is much pleased with the kind reception given us by the King`'s ministers,
D`'Ofalia and Zea Bermudez.
We dined at Balmaseda`'s, the banker, who has been very attentive to us,
by providing us with suitable lodgings, which we at first found very difficult to obtain.
Here, also, were many Spaniards; most of them are merchants,
and reside in various parts of Spain.
They gave us a deplorable account of the morals and conduct of
the clergy and monks very generally throughout this nation.
Great also is the oppression under which they keep the people,
by their various demands and ways of extorting money from them, besides their tithes,
which they levy on almost every kind of produce.
The mendicant monks are not less oppressive.
Stout fellows may be seen in the street, the public markets, at private dwellings,
and farm houses in the country, having large sacks with them.
They profess to lead a life of poverty, and to possess only what they beg for;
but their begging is an imperious demand; for, if they are denied,
they pour out curses and maledictions upon the individuals
who dare refuse to comply with their requisitions.
Fear constrains many to grant the monks`' request if they possibly can.
But the oppression of the people extends still further.
The Grandees have farmed almost everything from the Crown,
or have privileges granted them, as appendages to their stations.
One has the duty on salt;
another on everything brought into a town for sale;--on
this the collector puts his own value,
and this must be paid or secured before the person enters the town.
Thus the poor country people are so fleeced by the priests, the collector of dues,
the Government taxes, and the land-owner`'s rent,
that they have often to sell all and be turned out destitute.
This system of oppression drives many to acts of desperation,
and it is in consequence of this that there are so many beggars and highway robbers.
Men thus stripped of their all have no energy to labour;
for they know that if they work it is not for themselves,
and want drives them to commit all kinds of cruelties and crimes.
By these means fine tracts of land in this fertile country are neglected,
or very poorly cultivated.
Land-owners receive but a small income out of their large estates.
The revenues of the Crown are much reduced,
whilst the expenses are greatly increased by the number of the poor, and of criminals,
it is obliged to support.

We were this evening, by appointment, with the Count D`'Ofalia.
We pleaded strongly with him the necessity of allowing liberty of conscience,
and of preventing oppression by the Popish clergy.
He is sensible of the propriety of so doing,
but he does not see how it can be brought about, at present.
We told him that, if the Government does not take measures to do it,
the people may take the work into their own hands,
and it may then be attended with terrible consequences.
The Count told us that the King had expressed a wish to see us, but,
as he was not well then, he could not yet conclude on the day that it would suit him.

7th. We were occupied great part of the last two days in preparing a report,
to be laid before the King,
of our visits to the prisons and other institutions,--the state in which we find them,
the abuses which exist, the causes which lead to the commission of many crimes,
and the remedy which we submit for consideration.
The whole is sent to the care of Count D`'Ofalia.

8th. Among the persons that come to see us at our lodgings, is D. M. Vila,
a young man from Barcelona,
who has been in England and is acquainted with some of our Friends.
He accompanied us to an intimate friend of his, Gaspar Remisa,
who is the Director General of the King`'s Treasury.
He has four thousand men now engaged in draining extensive marshes on his estates,
on which he intends to form colonies.
For his encouragement to this,
he has obtained from the Crown exemption from tithes for sixteen years,
from the time the land is brought into a state of cultivation.
He is a liberal-minded man, and has established several schools on his estates.
We supplied him with copies of the Scripture Lessons,
to be printed in the Spanish language and introduced into his schools.
The Count D`'Ofalia sent us a message this evening requesting us to call upon him;
he told us that he was with the King last evening, and read to him our report.
The King was anxious to have early attention paid to the improvements suggested,
in order to diminish the mass of misery and evil prevailing in the land.
He knew that we were preparing for our departure from Madrid,
and proposed very soon to see us.

9th. We went this morning to our respective Ambassadors, the American and the English,
to have our passports in readiness, and signed by the French Ambassador.
D+++.+++ M. Vila paid us a very agreeable visit;
he suffered deeply under the late disturbances in this kingdom;
he was imprisoned for several months at Barcelona.
The manner in which he heard of us is rather singular.
About two weeks since, he received a letter from a Spanish Roman Catholic priest,
now in England; one of those, who, to save his life, left Spain during the late troubles.
He informed him of the pious objects that induced Allen and myself to come to Spain;
he wished him to find us out,
and to make us acquainted with such persons as he knows we would like to be with.
On the receipt of this letter, Vila came immediately here, and taking up a newspaper,
found there an account of our visit to some prison;
by which means he knew where to find us.

10th. Early this morning we had a note from D`'Ofalia,
requesting us to call upon him at eleven a.m.,
stating that the King would see us at five p.m., at his palace.
D`'Ofalia received us with his usual kindness,
and said that the King had told him again that he
much approved of our remarks in the report,
and had ordered that we should be furnished with letters
to the Governors of the Provinces where we may travel,
and to the public authorities, directing them to treat us with all civility,
and to let us have free access to every place that we may wish to visit.
These letters, signed by the King himself, were handed to us.
He told us also that orders had been given at the palace to receive
us with the quietness and simplicity that he knew we wished;
that the Duke of Aragon, Captain of the King`'s Guards,
would be in readiness to introduce us, but he advised us, as a matter of civility,
to be with the Duke a short time before we went to the King.

The hour now had nearly arrived for us to repair to a meeting for
Divine worship that had been appointed at the American Ambassador`'s;
it was attended by many persons.
The Lord very graciously gave us access to his holy presence,
and enabled us reverently to worship at his footstool.
The meeting continued a long time in solemn silence, when, on bended knees,
prayer and supplication, thanksgiving and praise were offered unto him.

We went to the palace about the time appointed;
the Duke of Aragon received us with much civility;
they had even removed the military that almost always stand about the palace.
The Duke brought us up the great staircase;
we first came into the apartment occupied by the King`'s officers and guards,
who at once introduced us into another spacious hall,
where the King`'s immediate attendants were in waiting.
The Chamberlain soon brought us into what appeared to be the court-room;
we saw nobody at first,
but very soon a plainly dressed person and a female came towards us,
holding a little girl by the hands between them.
We did not think they were the King and Queen,
till I observed her features which reminded me of a portrait I had seen of her,
and I queried, "`Is it the Queen before whom we stand?`"
"`Yes,`" she replied, "`and this is the King, and here is our young Princess, our eldest,
two and a half years old.`"^
footnote:[Afterwards Isabella II., Queen of Spain.]
We soon explained the reason of our embarrassment,
for we did not expect that the King was well enough to be out of his chamber,
and feared that his standing would be too great an exertion for him;
but they declined sitting down.
After some remarks respecting our visits to their public institutions,
and answering their inquiries on several subjects relating thereto,
in which the Queen took part with interest,
I noticed that the young Princess looked at us with great earnestness,
which the Queen also observing,
I said that it was probably the first time that she had seen two persons like us,
stand with their heads covered before the King and Queen.
This led to subjects of a religious nature,
and an inquiry into some of our Christian testimonies and practices; then,
under a sense of the Lord`'s power and love, I uncovered my head and proclaimed to them,
as the Lord through his Spirit gave me,
the word of reconciliation and of life and salvation through faith in Christ.
I felt much for the King under the severe trials that have attended him,
and the remarkable manner in which his life was preserved within the last few months,
whilst from his illness he was in a state of stupor,
and the prevailing party urged the physician to have the post mortem examination made,
though he protested that he was not dead;
it was at that very juncture that the Queen`'s party obtained the ascendency,
and the King`'s life was preserved.
In the course of my communication I alluded to Nebuchadnezzar,
and remarked that the King had, like him,
been driven out of his kingdom (having been sent a prisoner to France by Buonaparte),
had endured many afflictions and humiliations, but now the Lord had restored his kingdom,
and had instructed him to know that it is by Him
that kings reign and princes ought to decree justice.
As I went on, the King queried, "`Who is this King Nebuchadnezzar?`"
The Queen at once explained to him in what part of the Scriptures he would find it.
Then I expressed my earnest desire that, like him, he may honour the Most High,
by breaking off his sins by righteousness,
and his iniquities by showing mercy to the poor,
with Christian faith and confidence asking of God to give him wisdom and knowledge,
to go out and come in before the people so as to glorify his name.
We also entreated the King to mark the last years
of his reign by acts of clemency and of piety,
and the noble deed of giving to his subjects full liberty of conscience,
not doubting that they would thus be crowned with the Lord`'s blessing, and that,
finally, his earthly crown would be exchanged for a heavenly one.
Both the King and Queen were serious,
and on parting gave evidence of kind feelings towards us.
They both speak good French; therefore, all that was communicated was in that language;
none were present except them and ourselves.

From the palace we went to dine at Sir Stratford Canning`'s;
several persons came in afterwards with whom we had a time of religious edification.
O what a consolation thus to find among those who occupy high stations
in life a few who walk in the lowly path that Christianity calls us into.
We took an affectionate farewell of this interesting family.

11th. We were busily engaged in preparing for our departure;
several persons came to see us once more,
with whom we had precious and solemn parting seasons.
One of these was Remisa, the keeper of the King`'s treasury.

--
