== Chapter LXII.

Fourth Visit to Europe

Spain--Barcelona--Return through France to England

Their services in Valencia being concluded,
they left that place by the diligence on the evening of the 19th
and pursued their journey along the Mediterranean coast.
Stephen Grellet writes:

// lint-disable invalid-characters
We had the coupé to ourselves.
It was a great relief to be alone.
I was pretty comfortable the forepart of the night,
but next morning a violent chill and high fever came on,
and I was in a poor condition to travel; there was, however, no place to stop;
towards evening we came to the Ebro, which is there a pretty broad river;
we crossed it in a sail-boat; the wind was high and cold,
which seemed to pierce me through;
on the other side of the river an open kind of wagon
took us four miles to a miserable inn,
to wait for the diligence; there I laid down for a couple of hours,
which refreshed me a little.
About nine in the evening we arrived at Villa Franca,
where I hoped to have had more rest,
but instead of this we found many persons collected at the inn, who, it appears,
had heard of our coming; some from curiosity, others prompted by better motives,
wished to see us; most of them spoke French;
they seemed very desirous to improve the opportunity to inquire into our religious principles;
some appeared to have tender scruples,
and to be very uneasy under the yoke of bondage imposed upon them by the church of Rome;
they could not reconcile the priests`' conduct with their
views of what a minister of Jesus Christ ought to be;
others seemed to be spiritually minded persons; instead of obtaining rest,
my time was closely taken up with these people.
It was an opportunity attended with much seriousness and edification.

We stayed there only two hours.
Our road onward was very rough, and I became very ill again; my outward man,
during this journey, has endured great distress;
but the presence of the Lord and the sensible feeling
of my dear Redeemer`'s love so comforted my soul,
that I could understand how Paul and Silas,
whilst in the prison-house with their feet in the
stocks and their bodies lacerated by stripes,
could nevertheless sing praises to God.
My soul did magnify the Lord my Saviour, who has been with me in Spain,
according to his word, as he has been with me, the poorest of his servants,
in all other nations where he has sent me.

We arrived at Barcelona on the morning of the 22nd,
and I kept in to nurse myself whilst dear Allen went to visit the Governor and others,
and their hospital.
In the afternoon several persons, having heard of our arrival,
came in to see me during dear Allen`'s absence; one is Don Felix Forres Amat,
Bishop of Barcelona.
He is a remarkable character; notwithstanding the many obstacles put in his way,
he has succeeded both in translating and printing the Scriptures from the Vulgate;
it is a large work of seven volumes; he has presented me with a copy of it.
He was under the necessity thus to make a large work,
to obviate some strong objections against issuing it;
it is printed with both the Latin and Spanish on the same page;
he was also obliged to put in notes;
but in these he has confined himself to explanations
of the manners and customs of the people.
He succeeded in obtaining the sanction of the Pope.
This was about twelve years since,
when the Inquisition was in force and in great activity,
yet even then friends and enemies to the Bible were anxious to have it in their hands,
so the first edition was very soon disposed of.
He is now printing a second edition, and has proceeded to the third volume.
The Archbishop of Toledo, and the Nuncio of the Pope,
have made strong efforts to prevent him, but he hopes to succeed in completing the work.
The King supports him in it.
Amat is a man of liberal sentiments; he wishes for unrestricted liberty of conscience;
none but the Lord, he says, has the authority to control it;
he knows several persons in Spain who are like-minded with himself.
He much wished that we could see the Archbishop of Mexico,
who has lately written a book setting forth,
with much clearness and force of argument grounded on Scripture, his Christian views,
demonstrating that none but those who build on Jesus Christ,
as the sole hope of salvation, are members of the true Church,
and that no observances of forms and ceremonies, or the precepts of men,
can give a right claim to this membership in the church of Christ.
The Bishop told me that the day before yesterday,
as he was walking on the public promenade, between the Governor and the Chief Magistrate,
he stopped them suddenly, as the thought came before him, and said to them,
"`What do you think the people will say if they see me walk
between the two Quakers shortly expected here,
as I now do with you?`"
"`We cannot say,`" they answered.
"`Well,`" said he, "`I will tell you; they will say,
that the strong walls of intolerance and superstition are falling down.`"
He tells me also that several priests of the order of the Oratorians (those
among whom I received part of my education at the college of Lyons),
fled among the mountains during the late persecution; he represents them as men of piety,
and calculated to spread vital religion wherever they may be scattered.

23rd. I felt much refreshed this morning and had no return of fever last night.
My gracious Master has helped me; blessed be his name!
We have had a succession of visitors today, priests, canons,
merchants and persons of different ranks; among others several of the nobility,
and the Regent and Chief Justice.
We had free and full opportunities with them;
we set before them what the religion of Christ consists in,
and what are the fruits of the Spirit, contrasted with those of the flesh.
The hearts of some of them appeared open to understand and to receive our testimony.
Bishop Amat has come again to see us;
he told us that a rich man who had not obtained his
great wealth by the most righteous means,
feeling a desire to silence the strong convictions
of conscience by some meritorious works,
came to him,
and inquired how many masses he would advise him to have said to the Virgin Mary,
and to any of the saints he might point out,
in order that souls might be prayed out of purgatory,
and he might make atonement for his sins.
The Bishop told him,
that neither masses nor works of that kind could do any good to the dead,
neither could they remove from a guilty conscience a single sin;
that it was his duty to make restitution, as far as possible,
to those who had been wronged, and if that could not be done,
to be liberal in the relief of the poor, and our suffering fellow-beings;
but that even this, which it is right to perform, could not obtain the remission of sin,
nor could any priest, or even the Pope, confer this remission;
it was through the Lord Jesus Christ alone that this could be obtained,
and it must be sought for by deep repentance, evinced by amendment of life, prayer,
and faith in Him who is the only Saviour.
This person, the Bishop says, has so far taken his advice,
as to place large sums of money at his disposal, to be employed for the poor,
the fatherless and the widows,
and he appeared also to look in faith to the Lord Jesus Christ,
and to seek to him as the only hope of salvation.

25th. A number of seriously disposed persons came to see us today.
We had interesting and precious religious opportunities with them.
Very earnest appears to be the inquiry of some of them, "`What must I do to be saved?`"
No better answer can be given to such inquirers,
than the short but very comprehensive one given by
the apostle Paul to the jailer at Philippi,
"`Believe on the Lord Jesus Christ.`"
One of these serious inquirers is a young man who has been strongly
convinced of the iniquity practised in the church of Rome,
under the mask of religion.
When, a few months since, a change in the Government took place,
and those immured by their persecutors were set free,
and the prison of the Inquisition was also broken open,
this young man was one of the first who entered it,
and assisted in liberating the prisoners.

In the afternoon my dear Allen went into the country
to visit some of the poor people in their cottages;
and during these last days he has been to some prisons and other places.
My health did not allow of my going out; but several persons have come to me,
some from a distance in the country,
whom we should have been prevented from seeing had I been out.
Truly the Lord orders all things right.
This afternoon I went to visit the "`House of Mercy.`"
It contains about fifty women,
and three hundred and fifty girls of about eighteen years of age.
It is under the care of twenty-four nuns of the order of the Franciscans; they,
together with a priest attached to the establishment,
accompanied me through the institution, where I had several religious opportunities;
the last was with the nuns.
Several of the inmates of this house manifested much tenderness of spirit.

26th. We have prepared our report to the King,
respecting various subjects that have come under our observation since we left Madrid,
and the abuses which we hope he may correct.
We have also prepared an address to him and the Queen,
for whom we have felt much since we came into their dominions.
We have much peace in this our last service towards them.
We have also written to the Count D`'Ofalia, to whom we enclose all these documents,
which are written in French.
I visited a priest, a canon, recommended to me by Bishop Amat;
he suffered much during the late persecutions, and narrowly escaped with his life.
I went also to see the Captain-General, or Viceroy of this Province,
and the Chief Justice.
Allen had been there before alone, sickness then preventing me.
I had a very full opportunity in their respective families;
they both are liberal-minded persons.
Amat is of much service to them.
They are prepared to have full liberty of conscience introduced in this nation.
The population of Spain is composed of men of divers nations,
their countenances strongly denoting who were their ancestors-Moors, Arabs, Africans,
or the ancient Spaniards; but even among these there are marked differences;
separated by the mountains, they appear like so many distinct tribes,
and vary also in their habits and dispositions,
but all very generally agree in the one custom of wearing cloaks, winter and summer;
even young boys and beggars have them, be they ever so ragged and dirty;
in some places they are made of black wool, in others this is mixed with white;
but in Catalonia their cloaks are dyed of a deep red or scarlet colour.
The Catalonians are mostly a fine race of men, so that even the beggars among them,
with their tattered red cloaks, have no mean appearance.
They are also industrious, compared with the people in other parts of Spain.

Being released from further service in the Peninsula,
Stephen Grellet and his companion took their departure for France.

// lint-disable invalid-characters
Jonquières, 28th. This is the last Spanish town on the frontiers of France.
We left Barcelona yesterday at three a.m. In the
part of the carriage we occupied we had no company,
except a very zealous young man going to be ordained as a priest;
he is a full disciple of the Jesuits,
and at their word would be ready to do anything required.
We travelled through a beautiful and romantic country.
Part of our road was by the seaside, at other times among the rocks and mountains.
We tarried a few hours at Gerona, a place renowned during the last war,
for the siege it sustained from the French army, when, as at Saragossa,
the effusion of blood was very great;
it is said that from eighty to one hundred thousand
Spaniards and French lost their lives in that siege;
finally the whole of the fortifications were demolished.

Perpignan in France, 29th. On our way here we had in view high mountains;
one called Zea is a magnificent object; it is supposed to be five thousand feet high;
its summit is continually covered with snow.
// lint-disable invalid-characters
After leaving Jonquières we began to ascend the Pyrenees through narrow defiles,
amidst high and rough mountains;
the grandeur of the scenery before us proclaimed
to us the great and powerful name of the Lord,
before whom our souls were prostrated with admiration and praise;
from the contemplation of his outward works our minds were drawn
to that of the greatness of his love and mercy to us;
great indeed is the help and manifold the preservations
that he has extended to us his poor servants;
we felt our minds clothed with gratitude and wonder on reviewing
what he has done for us since we entered Spain.
He has opened for us a highway and a plain, beaten path,
where before not a stepping-stone could be seen by us.
Who but the Lord Omnipotent, who has the key of all hearts,
could thus open the King`'s heart to us,
and render him the instrument of making our way to a number of pious and inquiring persons,
to whom, otherwise, we must have remained total strangers, and they to us?
Blessed and exalted be his name forever and ever!

On our arrival here we presented ourselves, as required, before the police,
who not only treated us with civility, but evinced some religious thoughtfulness.
We had also a satisfactory interview with several persons who came to our inn to see us;
some of whom accompanied us in a visit to their prison.

Toulouse, 31st. We arrived here last evening.
Among the persons we were with today were some of the colporteurs,
who go about the country, to a considerable distance,
to distribute gratuitously or to sell the Scriptures along with their wares.
They go chiefly among the Roman Catholics,
and dispose of a considerable number of New Testaments;
their lives have been repeatedly much exposed;
they have also been sorely abused several times,
but their patience and perseverance are great.
They gave us very interesting accounts of their progress in this service,
which the Lord blesses.

Fourth month, 2nd. We have visited several schools,
and been with some of the nuns of the hospital,
for whom I had letters from their friends at Madrid.
We had also two meetings for Divine worship,
which were seasons of edification and refreshment in the Lord`'s presence.

Bayonne, 4th. We left Toulouse yesterday at seven p.m.,
and early in the morning came to Auch, where I went to see the widow of Solon,
who died soon after I parted with him at Toulouse, three months since;
both she and her brother are pious persons,
and feel the consolations of Christ under their bereavement.
We arrived here early this morning, having been two nights on the road.
We were satisfactorily with the Sous Prefet,
and had a meeting with the pious persons that we mingled with when we were here before.

Bordeaux, 6th. We left Bayonne yesterday morning, and arrived here today at four,
a.m. The road was rough, but yet we travelled with speed.
We called today on several serious persons,
and had a long walk to the Hotel of the Incurables, where there are eighteen nuns.
I had a letter for their Superior from the nuns at Madrid; she is a woman of piety;
our meeting with them was to satisfaction.
With the long walk and the fatigue on the road, during the last day and night,
I feel much spent this evening.

7th. First-day.
Dear Allen and I sat together as we usually do, to wait silently on the Lord;
his Divine presence and the contriting influence
of his love were felt by us to an uncommon degree;
on bended knees I was constrained to ascribe thanksgiving and praise to him,
our very gracious and Almighty Preserver and Redeemer, who has thus safely led us about,
kept us, and given a little ability, by the efficacy of his Divine grace,
to do the work for which he had sent us;
mercifully passing by the many haltings and shortcomings of his poor unworthy servants.
After meeting I continued for a long time under the
contriting sense of the Lord`'s love and power,
attended with the lifting up of my soul to him with adoration and praise;
whilst in that state I was seized, as in Spain, with a violent fit of ague;
I shook greatly; high fever succeeded.
I felt weightily my situation; a meeting was appointed for this evening,
and our places by the diligence to set off at ten at night for Paris were paid for.
Hope was, however,
given me that through the help of my blessed Master this might be accomplished.
I kept quietly in bed till the time of the meeting, when, though still very ill,
I felt a little increase of strength and went.
We had a good and solemn meeting.
The Lord enabled me largely to proclaim the Gospel
of life and salvation through Jesus Christ.

The Lord`'s baptizing power was over us,
and he enabled us to feel together the quickening influence of his Spirit.
I have just returned to my inn,
with a heart overflowing with gratitude and praise to God my Saviour,
who has again helped his poor servant.
Blessed be his name forever and ever!

Paris, 10th. Shortly after writing the above lines, we left Bordeaux.
Some fever continued during part of the night,
but it entirely disappeared before morning,
nor did I feel any return of it during the three nights
and two days that it has taken us to come here.
We called today on some pious persons to satisfaction.

11th. We breakfasted this morning, by invitation, at the Duke de Broglie`'s,
Prime Minister here.
// lint-disable invalid-characters
The Duchess`'s sister, the Baroness de Staël,
with whom we both have long been acquainted, is here also at present.
They both are pious women.
Guizot also, another of the King`'s ministers, was with us at breakfast.
I had wished to see him,
and thus an opportunity was given me to represent to him the sentiments
contained in some of the books they have in their public schools,
which are not in accordance with pure Christian doctrine.
He promised to attend to this.
He stated also,
that he has taken measures to have the New Testament introduced in all the public schools,
for which purpose he has ordered an edition of forty thousand copies.
He meets with no obstruction to it from the Bishops,
the greatest is from some of the priests.
After he and the Duke had retired to go to the Chambers,
we had with the two sisters a precious opportunity; they know the language of the Spirit.
The Duke, wishing to have more time with us,
pressed us to take a family dinner with him tomorrow.
In the afternoon we had religious opportunities with several persons,
both Protestants and Roman Catholics.

12th. I had much satisfaction in a visit to the Countess De Pellet.
Her father and mother, who are with her, are pious persons.
The Countess is in the daily practice of having all
her servants and family collected together,
whilst she reads to them a chapter in the Bible.
They were assembled for that purpose when I went in.
The Lord owned this religious opportunity,
and that also with the Countess`'s family and parents afterwards.
We dined as agreed upon with the Duke de Broglie, none being present but the family.
They have among their elder children some who know and love the Saviour.
They retain the deep impressions made upon them by the late decease of a beloved sister.
Her death was triumphant, full of faith and hope in the mercy of God through Jesus Christ.
The dear parents sensibly feel their loss, but they have also great joy,
through faith in Christ, in the death of their beloved child;
for she appeared to be one of the lambs of the Lord`'s fold.
// lint-disable invalid-characters
The Baroness De Staël was also with us.
Our time was spent to edification.
I had a short private opportunity with the Duchess,
but not sufficient to allow her time to unfold some
of the exercises and straits of her heart.
It was concluded that we should call upon her again tomorrow morning.

13th. We went again to the palace of the Duke.
I had a full opportunity with the Duchess.
The Lord is pleased to keep her under close discipline.
Many are the baptisms and secret conflicts she endures; but goodness and mercy follow her.
We had a tendering season together before the Lord;
he gave me suitable counsel and encouragement for her.
Then dear Allen and her sister the Baroness, who had remained in another apartment,
came in to us.
We joined together in offering unto the Lord prayer, adoration and praise.
We had at our hotel several edifying seasons with pious persons who came to see us,
and also with some whom we visited.

14th. First-day.
We had a meeting for Divine worship; a variety of conditions were present;
deep was our exercise for a length of time,
but the Lord enabled us to minister to their respective states;
the meeting concluded under great solemnity.

In the afternoon I went to see the Countess de St. Aulaire;
she and her husband are Roman Catholics; they have just returned from Rome,
where the Count was Ambassador, and they are shortly to set off for Vienna,
where he is going in the same character.
I saw the Count but a short time as he was going out.
I found in the Countess a pious, liberalminded person; she appears to be endeavouring,
by the Lord`'s assistance, to adorn her profession by Christian virtues,
and not by the works of man as prescribed by Popish priests.
She sees beyond all their superstitious practices.
Dear Allen, being otherwise engaged, was not with me here.
This evening we had a small but satisfactory religious meeting with a select company.

Calais, 17th. We left Paris the 15th. Two days and one night brought us here.
We have met with a few serious persons, and have visited their school,
and endeavoured to encourage in the right way, some who appear disposed to do well;
but they want energy and decision.

Stoke Newington, 18th. We left Calais last evening, and arrived here,
at my beloved friend Wm. Allen`'s house, this afternoon.
Our hearts overflowed with gratitude to the Lord,
who has brought us back in safety amongst our friends, and who enables us, in his mercy,
to rear for a memorial to his goodness many stones brought up out of deep exercises;
"`Hitherto the Lord hath helped`" is the inscription to be read thereon.
