== Chapter LXVII

Last Days and Decease

The last two or three years of Stephen Grellet`'s life were,
like some of the preceding ones, attended with much physical suffering;
but he had not followed cunningly devised fables in believing in
"`the power and coming of our Lord Jesus Christ;`" he knew Him
in whom he had believed-he endured as seeing Him who is invisible.
Remarkably applicable to his own experience were the words of comfort addressed by himself
to a beloved friend in an hour of conflict,--"`Trials and afflictions are,
to those who have known the Lord and the power of his redeeming love,
like the pressing of an aromatic plant;
the more it is under pressure the stronger and sweeter does the scent thereof arise;
well, therefore, may we say, in all our tribulations, Awake, O north wind;
and come thou south; blow upon my garden, that the spices thereof may flow out.`"

Whenever his health permitted, neither the inclemency of the weather,
nor the suffering of pain,
were allowed to prevent his publicly worshipping with his friends.
He seemed to forget his own sufferings in the griefs of others,
and still went from house to house, visiting the flock in their retired abodes,
and with tender sympathy, imparting the word of counsel, of comfort or encouragement,
where it was needed.

From the family record, and other sources of information, it is evident that,
as a father in the church, he was still fruitful in the field of offering,
and joyful in the house of prayer,
and that his ministry continued to deepen and brighten even to the end.^
footnote:[See the Testimony issued respecting him,
by Burlington Monthly Meeting.
{footnote-paragraph-split}
His fellow-citizens
of other denominations were not slow to recognize his worth,
and in various ways manifested the estimation in which he was held by them.
An able and impressive discourse on his life and character, by C. van Rensselaer,
a Presbyterian Minister of Burlington, New Jersey,
has been widely circulated both in England and America;
and the following is an extract from a brief notice of his decease,
which appeared in the Burlington American:
{footnote-paragraph-split}
"`As
a citizen he has been long known to the people of Burlington,
and we may safely quote the Apostle`'s appeal:
'`Ye are witnesses how holily and justly and unblamably he behaved
himself among you.`' A heart of larger sympathy we have never known,
or one more ready to comprehend and to minister unto
afflictions which were carefully concealed.
His Gospel preaching was of a character rarely equalled, and probably nowhere surpassed.
Its chief characteristic was its wonderful vitality.
Perfectly free from every trace of egotism, he preached '`Jesus Christ,
and Him crucified.`' The sufferings of his Lord for the sake of sinful man,
deeply and abidingly affected his soul.
His sermons manifested an extraordinary originality, scope of thought,
and spiritual wealth.
With demonstration of the Spirit, and with power,
he illustrated his subjects with passages brought from various parts of the sacred volume,
and which the hearer found presented in a light in which he never saw them before.
Holding all mankind as his brethren,
his public ministry and prayers evinced his large-minded
sympathy with the whole human race,
and his deep interest in the movements among the nations.
To him, it was a present sorrow,
if famine stalked through foreign lands,--if pestilence wasted distant cities,--if in
any part of the earth the sword devoured men for whom Christ died.
{footnote-paragraph-split}
There
was an unmistakable halo of good to be felt about him,
by which even the irreligious were impressed;
but of his personal traits those best can speak who were privileged
with his close friendship.
{footnote-paragraph-split}
His gentle,
kindly and true heart has forever ceased its beating;
and it remains for those who mourn his loss to bow
in resignation to the will of his rich Rewarder,
to rejoice in the perfect joy of his salvation, and,
carefully noting his shining footsteps, to follow him as he followed Christ.`"]

In the summer of 1853 he was again very ill--so ill that
it was not thought possible he could survive many hours.
This attack continued for some days,
and several weeks elapsed before he was able to go out again.
During this period the state of his mind was quite heavenly, and,
with a countenance beaming with love,
he would very often praise and glorify his blessed Lord and Saviour,
praying earnestly for his beloved family, and those who were about him.
Once, on being asked whether he had slept during the night, he replied, "`No,
except a little after four o`'clock;`" adding,
that he had been in the house of prayer for a long time,
pouring forth his fervent supplications, even to wrestling,--for himself,
for his beloved wife and daughter, for his sister Le Clerc, in her advanced age,
and for his brother Charles, and other members of his family in France;
then for those who had unhappily been drawn aside from the right way of the Lord,
mentioning some of these by name; for the Friends of his own meeting;
and for the multitude of sinners who were groaning
in bonds and misery of their own procuring.
Whilst thus interceding for different classes of his fellow-men, a bright view, he said,
opened to his mind of the unspeakable mercy of God in Christ Jesus,
and of the virtue of his atoning sacrifice,
which seemed to be a resting place to his soul.
Sleepless nights were often his portion,
but he frequently remarked that "`he had that which was better than sleep.`"
After a time of much pain he looked up to his heavenly Father, and said, "`I pray Thee,
not for a mitigation of my sufferings, but that the full end may be accomplished!
Thy mercies are great; they proceed from an everlasting fountain!`"
On a beloved friend coming in for a few moments,
and remarking upon the trial the dear invalid was passing through, he replied,
"`My dear Master has been very good to me-my consolations have far exceeded my pain.`"

On reappearing amongst his friends at their meeting, about two months after,
he spoke very impressively on the words of the Apostle: "`Blessed be God,
even the Father of our Lord Jesus Christ, the Father of mercies,
and the God of all comfort; who comforteth us in all our tribulations,
that we may be able to comfort them which are in any trouble,
by the comfort wherewith we ourselves are comforted of God.`"
Though at home he could hardly speak above a whisper,
on this occasion his voice was strong, and he spoke with much power.

About a fortnight after, on the 20th of Ninth month,
he received a refreshing visit from his beloved friends, Josiah and William Forster,
and their companions, John Candler and William Holmes,
who had lately arrived from England, as a deputation from London Yearly Meeting,
charged with the important work of placing in the hands of the
President and others in authority in the United States,
and of more generally disseminating among the inhabitants,
an address on slavery and the slave trade, issued by that meeting.^
footnote:[It was in the accomplishment of this important
service that that dignified and devoted servant of Christ,
William Forster, afterwards laid down his valuable life, in Tennessee.
See Vol.
I.]
True to the cause of the oppressed African race,
Stephen Grellet took a lively interest in the mission of his beloved brethren;
and they visited him again two days after,
when they had a very interesting religious opportunity together.
During the remainder of the year, though often very feeble,
and suffering much from the inflammation of his eyes,
Stephen Grellet was generally able to attend his own meeting,
and was frequently exercised in the ministry of the Gospel.

In the beginning of 1854 he was again brought so low by
another attack of illness that his life was despaired of.
As usual, not a murmur escaped his lips, but,
cheerfully bowing to all the dispensations of his Heavenly Father,
he often numbered his blessings and gratefully acknowledged that "`he was peaceful,
rejoicing in the Lord, and in everything giving thanks.`"
He again recovered, and was able to mingle with his friends in their religious meetings,
and in social intercourse, bearing frequent testimony, both in public and in private,
to the goodness of the Lord, and the preciousness of the Saviour`'s love.
But in the autumn his sufferings were renewed,
and there seemed but little hope that his days would be lengthened out.
One day, after having spent much time in quiet retirement of spirit,
he remarked that it was not from suffering that he had kept silence, but that,
during the solemn feeling which was granted him,
the song of praise which had filled his heart had been wonderful, adding,
"`If I had the pen of a ready writer I could fill
pages with the Lord`'s merciful dealings with me.`"
He then very sweetly and encouragingly addressed his little family,
reminding them how wonderfully the Lord had helped them,
thankfully acknowledging that it was His doing.
Thus days of--bodily affliction were, through abounding mercy,
times of much spiritual refreshment; and on his being raised up again,
seasons of religious communion with his friends frequently occurred,
when the venerable patriarch would pour forth the message of the Redeemer`'s
love with an unction that bespoke the source from which he drew his supplies,
and those present rejoiced in being permitted to drink together into the one Spirit.

In the course of 1855 Stephen Grellet was generally able to meet
with his friends when assembled for the worship of God.
On these occasions, as well as in more private opportunities,
he continued to give evidence, amidst all his bodily infirmities,
that his delight was in the Lord; and,
having been "`allowed of Him to be put in trust with the Gospel,`" he was often enabled,
"`so to speak, not as pleasing men,
but God who trieth our hearts,`" that his preaching
was in the life and power of the Spirit,
remarkably searching and baptizing,
evincing a deep interest and earnest solicitude both
on behalf of those who were yet afar off,
and those who had already found peace with God through our Lord Jesus Christ.

Clothed with humility, the nearer he approached to the source of infinite purity,
the more deeply he seemed to be prostrated in self-abasedness; and if,
rejoicing as he did himself, in "`the light of the knowledge of the glory of God,
in the face of Jesus Christ,`" he had, during a ministry of nearly sixty years,
laboured more abundantly than many, both at home and abroad,
to bring others to the same blessed experience, and to win souls to Christ,
he reverently acknowledged that it was not he, but the grace of God that was with him;
he well knew-he deeply felt and was not slow to confess,
that he had his treasure in an earthen vessel,
that the excellency of the power might be of God and not of man.

But the time of his departure was at hand.
In one of the last meetings he attended,
he enlarged in a very striking manner on the words of Paul, "`I have fought a good fight,
I have finished my course, I have kept the faith.
Henceforth there is laid up for me a crown of righteousness.`"
Eight days before his decease he was present at his own Monthly Meeting,
where he dwelt with much unction on "`the joy of believing,`" telling his friends
that it might probably be the last time he should plead with them.
And such was the case, for never again was his voice thus heard amongst them.
A paroxysm of pain obliged him to retire from the meeting before its close
the only time in his life that such an emergency had occurred.

He was from this time confined to the house, suffering extreme physical anguish,
in the midst of which he desired his friends might be informed that,
though tribulation abounded, consolation did much more abound.
Remarking that he might yet have to suffer much more, he added,
"`I desire not only to do so submissively, but cheerfully.
These sufferings are indeed agonizing; but in this my hour of extremity,
my Heavenly Father has not forsaken me, but is comforting me.
I have had to advocate his cause, and now I am called to serve by patiently suffering,
and to glorify Him even in the fires.`"
On one occasion he said, "`There is not only peace,
but peace and joy in believing-great joy!`"
And when, in the extremities of tried but not tired patience,
he would pray for a little mitigation of his sufferings, he invariably added,
"`Not my will, but Thine be done.`"

On being asked how he felt, though he could not tell of any lessening of his pains,
he simply answered, "`My dear Master is very good to me.`"
Again, "`I cannot think that I shall be forsaken;
He that careth for the sparrows will surely remember me.`"
"`My heart and my strength faileth,
but`"--and a radiant expressive smile told the realization of the remainder of the text,
which he had recited a short time before.
In a severe spasm he meekly said, "`Do not be discouraged; it is only the flesh.`"
The two succeeding days were attended with almost constant agony,
but each groan was turned into a prayer, ending with "`Not my will, but Thine be done.`"
Towards evening, on the 14th,
he submissively petitioned for a little relief from suffering,
if consistent with his Heavenly Father`'s will.
Very soon the pain finally ceased, and, while he took no notice of external things,
the reverence of his countenance indicated a peaceful communion with his God and Saviour.

He slept sweetly during much of the following day, and a little before noon on Sixth-day,
the 16th of Eleventh month, 1855, with his family around him,
the beloved and honoured servant of the Lord gently breathed his last,
full of days and full of peace.

THE END
