== Chapter I.

[.chapter-synopsis]
* Childhood and College Life

Etienne De Grellet Du Mabillier^
footnote:[This was the proper name of Stephen Grellet, in his own country,
the affix "`du Mabillier`" being derived from an
estate owned by his father before the Revolution,
when, with most of his property, it was confiscated.
Gabriel de Grellet had six children, viz.--Marie Josephine, married the Baron le Clerc,
died in 1854, aged 87. Mariette F., married a De Boise, died in 1839.
Pierre married Grace, daughter of Judge Ingersoll, of New Haven, U. S., died in 1841.
Joseph, married a Minon, died in 1845.
Etienne, the subject of this Memoir, married Rebecca, daughter of Isaac Collins,
of New York, died 1855.
Charles, married Caroline Warney, died 1857.]
was born on the 2nd of 11th mo., 1773, in France, in the city of Limoges,
capital of the modern department of Haute Vienne,
and situated in the beautiful district of Limosin.
He was the fifth child of Gabriel Marc Antoine De Grellet and Susanne De Senamaud.

His parents were wealthy, and ranked high among the nobility of that district.
During Etienne`'s childhood, his father, Gabriel De Grellet,
resided on his patrimonial estate.
He was owner of extensive porcelain manufactories, in the neighbourhood of Limoges,
as well as proprietor of some iron works.
For some years he was comptroller of the Mint, and, at one time,
formed part of the household of Louis XVI.
As the intimate friend and counsellor of the king,
he was accustomed to attend service with him in his private chapel.
A title was conferred upon him for the benefits he had rendered to his country,
especially by the introduction of the manufacture of superior porcelain ware.
His porcelain works were afterwards purchased by the king,
just before the French Revolution, but on account of that event, never paid for.

The ancestors of Susanne De Senamaud, Etienne`'s mother,
had resided at Limoges for many generations;
and their standing in the world was among the first
class of the inhabitants of that part of the country.
They were remarkable for their longevity; three of the family lived to above 90 years,
and she herself died at the age of 93. Her grandparents had transmitted to her the story,
heard from the lips of their grandparents,
of the ravages of a terrible plague which visited Limoges during their residence there,
and swept away nearly all its inhabitants; so much so,
that the most frequented streets were deserted, and the grass grew so high in them,
that it was mown like a meadow.

In religious profession the family of Grellet were Roman Catholics.
It was the religion of their ancestors on both sides, and,
while some of the present generation had chosen secular pursuits, there were others who,
in accordance with the system of their Church,
had quitted the blandishments of the world for the seclusion of the convent.
One sister of Gabriel de Grellet had long since taken the veil, and resided, as a nun,
in the convent of the Visitation at Limoges; another sister and her aged aunt, had,
with still more ascetic devotion,
submitted to the severer discipline of the convent
// lint-disable invalid-characters
of Clairetés. Not permitted to see any of their relatives,
the only communication with their friends allowed by the rules of the latter establishment,
was conversation through a double iron grating,
between the bars of which a thick curtain was suspended
to prevent the parties seeing each other.

Thus was the childhood of Etienne cast among the conflicting influences of rank,
and wealth, and the luxuries of life, on the one hand, and, on the other,
of the quiet and mysterious example of a voluntary withdrawal from the external world,
and all its attractions.
But of his early days, spent under the parental roof, he has told us but little;
and of the influence of his parents`' life and character upon him,--of their consistent
kindness and high moral bearing--we are left to gather some hints or glimpses only,
from the records of his after life,
and of their struggles with the trials and storms
which so soon swept over their poor suffering country.

To feel that, while he was in the world--enjoying its luxuries, and pleasures,
and excitements--there were others of the family group who had
renounced them all for the exclusive devotion of the convent,
and, as he was taught to regard it,
for the holier life of the "`__Religieuse__`" must have
sometimes overcast his young brow with serious thought.
When he called to mind, as he must have done, the coarseness of their frugal fare,
and pictured them, as the young mind is apt to picture what it learns,
"`rising three times in the night for prayer in the church,
from the hard boards which formed their couch,
even the luxury of a straw pallet being denied them,`" no wonder if comparisons,
and involuntary contrasts,
should have sometimes led into thoughtfulness of
his own life--its carelessness and follies.

While at home, he was educated with his brothers and sisters,
under the care of tutors who resided in the house.
"`My parents were desirous,`" he tells us,
"`to give their children such an education as should make
them accomplished in the eyes of the world;`" but,
though trained in the precepts of a high-toned morality,
they received little direct religious instruction.
The simple truths of Holy Scripture were not the food of their early childhood,--the
"`principles of the doctrine of Christ`" were not taught them,
and they had scarcely "`so much as heard whether there be any Holy Spirit.`"

A quick susceptibility to religious impressions seems, nevertheless,
to have marked the youthful days of Etienne de Grellet,
and early indications of the work of Divine Grace upon his heart were not lacking.
When quite a child, his thoughts on the omnipotence of the Divine Being,
the Creator of all things, so deeply affected him,
that he never afterwards lost the recollection of it.
At the early age of five or six,
the efficacy of prayer to an omnipresent and omniscient
God was remarkably confirmed to him.
His juvenile powers had been overtasked by a long Latin exercise;
he was quite disheartened.
Alone, in his chamber, he looked abroad upon the glories of the external world,
and remembered that it was God who had created them all.
The thought arose in his heart, "`Cannot the same God give me memory too?`"
He knelt down at the foot of his bed, and poured out his soul in prayer to the Lord.
His petition was immediately answered.
On re-perusing his lesson, he found himself master of it; and henceforward,
he was able to acquire learning with increased facility.
Even in his old age,
he could look back to "`happy days,`" when his childish heart was contrited,
and remember "`with grateful emotion,`" places in his father`'s house, where,
"`on his knees, with his eyes flowing with tears,
he had poured forth his supplications unto God.`"
He had learned to repeat the Lord`'s Prayer.
"`O how was my heart contrited,`" he exclaims, "`while uttering the words, '`Our Father,
who art in heaven.`'`" To be permitted thus to look up to his God, to call him Father,
and to consider himself as his child,
filled his young soul with the tenderness of reverential awe.

But, in a religious point of view, his external advantages were at this time very few.
"`I had none,`" he remarks in his Autobiography,
"`to instruct me,--none to whom I thought of unfolding my heart.
My proneness to vanity soon dissipated all serious thoughts,
my fondness for play gained the ascendancy, till the Divine visitation was renewed.`"

After a few years of home tuition,
young Etienne and his brothers were sent to several successive colleges.
The last he was at was that of the Oratorians, at Lyons.
Unlike the previous one,
in which "`great corruption and levity were introduced
among the pupils,`" this was a well-ordered institution,
and afforded many advantages to the students.
The Oratorians had, pretty generally throughout France, succeeded to the Jesuits,
in having under them most of the colleges.
As to their religious principles, they were chiefly Jansenists.
They exercised great care, not only to form the literary,
but also the moral character of their pupils.
Great pains were taken to prevent the introduction of pernicious books into the college;
but the students had free access to a large library,
well furnished with useful and instructive works.
To avoid opportunities for the spread of corruption among the collegians,
they were not allowed to mingle in small companies of two or three alone,
there being supposed to be much greater danger of
contaminating influences in these small coteries,
than in associating together in larger numbers.
To secure the best guard in this respect, each had a separate chamber.

In the college there were generally about seven or eight hundred pupils; and,
including the officers of the establishment, about a thousand inmates.
Order prevailed to such a degree,
that fifty or a hundred of the young men went up and down the stairs so quietly,
that the sound of their feet could not be heard.
During meals, one of the students uniformly read to the company,
and they were afterwards promiscuously called upon
to give an account of what they had heard.
This good order and strict discipline were found to be very beneficial.
It was moreover the practice, morning and evening, when assembled together,
and at noon in the place of worship,
to repeat forms of prayer according to the rules of the order.

Young Etienne applied himself vigorously to his studies,
and obtained several prizes for his proficiency in Latin.
He here laid the foundation for that general knowledge, and moral fortitude,
which marked his future character.
It was during his tarriance at this college also,
that he was again "`favoured with the Lord`'s gracious visitations to his soul.`"
To this he afterwards refers "`with instruction and gratitude,`" and,
commemorating the Divine goodness, he exclaims,
"`O the heart-meltings I have witnessed,--fervent were some of the prayers I then put up,
when on my knees, my cheeks bedewed with tears.`"

[.embedded-content-document]
--

"`As we were educated,`" he continues, "`by Roman Catholics, and in their principles,
we were required to confess once every month.
I had chosen for my confessor one whom I thought to be a pious and conscientious man;
and, as I could not understand how it was possible for a man to forgive my sins,
I asked him what he could say to satisfy my mind on that point,
for I considered that God alone could forgive sins--a doctrine, however,
which I had never heard of.
He, seeing further than many other priests,
told me that he considered himself invested with such authority, only so far as that,
if I was sincere, and truly penitent in the sight of God,
he was the instrument through whom information was given me that my sins were forgiven.
This rational answer gained him much of my confidence and respect.
He bestowed a fatherly care over me.

"`From my earliest days,
there was that in me which would not allow me implicitly
to believe the various doctrines I was taught.
Though I was told that they were mysteries which I was not to seek to see into,
yet my reasoning faculties brought me to the root of the matter--from created objects,
to the Creator--from time to eternity.`"

--

Among some of the "`__religious openings__`" he had at Lyons,
one left a very deep impression;
and the remembrance of it helped to sustain his spirit
under many subsequent exercises and trials.

[.embedded-content-document]
--

"`I thought I saw,`" he says, "`a large company of persons, or rather purified spirits,
on one of those floating vessels which they have at Lyons, on the Rhone,
occupied by washerwomen.
They were washing linen.
I wondered to see what beating and pounding there was upon it,
but how beautifully white it came out of their hands.
I was told I could not enter God`'s kingdom until I underwent such
an operation,--that unless I was thus washed and made white,
I could have no part in the dear Son of God.
For weeks I was absorbed in the consideration of the subject--the washing of regeneration.
I had never heard of such things before, and I greatly wondered that,
having been baptised with water,
and having also received what they call the sacrament of confirmation,
I should have to pass through such a purification; for I had never read,
or heard anything speak of such a baptism.`"

--

When, some years before, he had, along with some of his companions,
received confirmation, according to the rites of the Romish Church,
he had been bitterly disappointed, he tells us, that,
"`contrary to what he had been led to expect,
after the Bishop had performed the ceremony, he found his heart not at all changed;
that his sense of sin still remained; that his propensities to evil were, that very day,
as strong as ever;`" and "`thus,`" he adds, "`at a very early age,
I learned that neither Priests nor Bishops could do the work for me.`"

Before leaving the University,
he joined with other collegians in preparing for participating
in what is called the Sacrament of the Lord`'s Supper.
Earnest were his prayers that he might do it worthily; his heart was sincere;
"`and,`" he writes,
"`the Lord condescended to evince himself near to me under that shadow.
This feeling continued while I remained at the college,
and some time after I had returned to my father`'s house.
But then, going into company,
and having an opportunity of giving full sway to my vain and volatile disposition,
I soon lost these religious convictions.
I sought after happiness in the world`'s delights.
I expected to find it.
I went in pursuit of it from one party of pleasure to another; but I did not find it,
and I wondered that the name of pleasure could be given to anything of the kind.`"
