== Chapter II.

French Revolution--Removal to Demerara--Arrival at New York

Before Etienne had completed his sixteenth year,
the political horizon of his country was changed, and with it the horizon of his hopes.

Nearly allied to the nobility,
and by all natural ties and sentiments bound to their cause,
the family of Gabriel de Grellet shared their reverses,
during the great revolutionary struggle which now swept over France.
Their estates were confiscated, and he and his wife were thrown into prison,
and had a very narrow escape of their lives.

In the early stages of the fearful conflict Etienne
was too young to take a very prominent part;
but there was much to rouse his feelings, and to stir the youthful ardour of his spirit.
At the commencement of the Revolution, he tells us,
the inhabitants of the kingdom generally took up arms;
one scene of distress after another kept him continually afloat.
The many provocations which the nobility and their adherents had to endure,
and for which, he admits, they had, in some instances, given too much occasion,
would have driven him to extremities,--had it not been for what he gratefully
recognizes as a "`Divine interposition,`" which preserved him.
For, at that time, in the summer of 1791, he was violently seized with the small-pox.
During this illness he was brought very low.

"`The Lord,`" he writes, "`was pleased afresh to visit my benighted soul.
The state from which I had departed was clearly set before me,
and the misery into which I must be plunged,
if the thread of my life should then be cut off.
After much secret sorrow, for no man knew how it was with me,
the Lord was pleased to lift up the light of his countenance upon me,
and to enable me again to enter into covenant with him.
In adorable mercy he preserved my life,
and relieved me from the apprehension of being totally blind,
the disorder being much in the eyes.
But, alas! alas! soon I forgot his works, turned his mercy into wantonness,
and became more and more estranged from him.`"

Many and rapid were now the events which succeeded each other.
Soon after his recovery the nobility in general were retiring from France into Germany,
to join the standard of the French Princes,
and to unite with the armies of other Continental Powers to bring about a counter revolution,
and restore the King.^
footnote:[The emigration of the nobility and landowners was, at that time, at its height.
Nearly 100,000 of the most wealthy and influential body in France fled their country.
{footnote-paragraph-split}
"`All the roads to the Rhine were covered with haughty fugitives,
whose inability for action was equalled only by the presumption of their language.
They would admit of no compromise with the popular party,
and threatened their adversaries with the whole weight of European vengeance,
if they persisted in demanding it.`"--[.book-title]#Alison`'s History of Europe#.
Chap. vii.]
It was concluded that Etienne, and some of his brothers, should join them.
Towards the close of 1791, therefore, he writes, "`I left my dear father`'s house,
and bid him, as it proved, a lasting farewell, having never seen him since.`"
The brothers now proceeded to join the Royalists.
After stopping a few days at Paris, they passed on towards Germany, through Mont Midi.
Many were the dangers to which Etienne was exposed.
In recurring to these, and the narrow escapes he had, he remarks:--

"`I shudder when I remember the state of insensibility I was in.
I was not the least moved when surrounded by people and soldiers,
who lavished their abuses upon us, and threatened to hang me to the lamp-post.
I coolly stood by, my hands in my pockets,--being provided with three pair of pistols,
two of which were double-barrelled.
I concluded to wait to see what they would do, and resolved,
after destroying as many of them as I could, to take my own life with the last.
No thought of Eternity was then before me--no sense or remembrance that there is a God!`"

He was, however, mercifully preserved, and no violent hands were laid upon him.
After a short detention, he and his brothers pursued their way to Coblentz,
then the rendezvous of the nobility, the French Princes being there.
The winter and spring were spent in military preparations
for the approaching campaign in France.
Both morally and physically it was a time of much exposure to Etienne.

"`Everything about me,`" he says, "`and the very nature of the work I was engaged in,
was highly calculated to destroy every fiber remaining
of those tender impressions I had heretofore received;
but my gracious Lord did not wholly forsake me.
I was preserved from those gross evils that are too generally attendant on an army.
But O! the height of my infatuation!
I attributed my preservation to my own reasoning powers;
for I viewed the vices to which my companions were addicted in the same light as,
a little before, I had done jovial parties, for dancing, etc., etc.;
concluding that what degrades the man can yield him neither true comfort nor pleasure.
Divine light would, nevertheless, at seasons,
pierce into the inmost recesses of my benighted heart.
I was fond of solitude, and had many retired walks through the woods, and over the hills.
I delighted to visit the deserted hermitages which formerly abounded on the Rhine.
I envied the situation of such hermits--retired from the world,
and sheltered from its many temptations;
for I thought it impossible for me to live a life of purity,
while continuing among my associates.
I looked forward wishfully for the time when I could thus retire; but I saw also that,
unless I could leave behind me my earthly-mindedness, my pride, vanity,
and every carnal propensity, an outward solitude could afford me no shelter.

"`Our army entered into France the forepart of the summer of 1792,
accompanied by the Austrians and Prussians.
I was in the King`'s Horse Guards, which consisted mostly of the nobility.
We endured great hardships, for many weeks sleeping on the bare ground, in the open air,
and sometimes lacked provisions.
But that word honour so inflamed us, that I marvel how contentedly we bore our privations.
And what was it all for?
To contend for an earthly crown!
To satisfy our vain and proud minds!`"

Towards the approach of winter, owing to various political changes,
the Princes`' army was obliged to retire from France, and, soon after, was disbanded.
Etienne had been present at several engagements; he had seen many falling about him,
stricken by the shafts of death; he had stood in battle array, facing the enemy,
ready for the conflict; but, being in a reserve corps,
he was never actually called out to the murderous onset;
he was thus preserved from "`shedding blood,`" having "`never fought with the sword,
or fired a gun.`"
Though, at the time, he might consider it as a "`misfortune,`" he was wont,
in after days, to recur to this circumstance with peculiar thankfulness to Him,
who had so especially called him into the service of the Prince of Peace.

Numerous incidents connected with his personal history "`which
would alone fill a volume,`" and the well known events of the Revolution,
with the barbarities of Robespierre`'s reign of terror, are passed over in silence,
or but slightly touched upon, in his Autobiography.
After recording the retreat of the Princes`' army,
he simply remarks that he and his brothers "`went to Amsterdam.`"
From other sources we learn, that, being made prisoners of war,
he and his brothers were ordered to be shot.
The execution of the sentence was each moment expected,
when some sudden commotion in the hostile army gave
them an opportunity to make their escape.
They took the route of Brussels, and from there reached Holland in safety.

The young brothers soon met with kind friends in Amsterdam;
but it now became a matter of serious consideration what course to pursue.
Their attractions towards their beloved parents,
left behind amidst the varying vicissitudes of revolutionized France, were strong; yet,
to attempt to return to them,
without any reasonable prospect of being able to alleviate their trials,
seemed only like a useless exposure of their own liberty and lives;
and to remain long where they were was scarcely less dangerous.
Etienne and his brother Joseph finally concluded to go to South America.
Through the kind assistance of a republican General, a friend of the family,
they obtained a passage on board a ship bound for Demerara,
where they arrived in the First month of 1793, after a voyage of about forty days.

They were provided with letters of introduction from their
friends in Holland to some of the principal planters,
who received them with much hospitality.
Mercantile pursuits soon occupied their attention,
and during a residence of two years in the colony, which then belonged to Holland,
they had an opportunity of seeing much of the horrors of slavery,
and of becoming intimately acquainted with the ruinous
effects of that iniquitous and anti-christian system,
both upon the coloured and the white population.
They were much shocked, on their first arrival in the colony,
in observing the degraded condition of the miserable descendants of the African race,
whose almost naked bodies bore evident marks of the cruelty of their oppressors,
and whose backs were frequently covered with large scars, left by the lash of the whip;
some, still bleeding under the strokes recently inflicted,
had Cayenne pepper and salt rubbed into their wounds, to increase their suffering.
Such was the impression made upon Etienne by the scenes of cruelty and anguish he witnessed,
that, many years after,
the sound of a whip in the street would "`chill his blood,`"
in the remembrance of the agony of the poor slaves;
and he "`felt convinced that there was no excess
of wickedness and malice which a slave holder,
or driver, might not be guilty of.`"
The state of society in Demerara was deplorable.

"`It was a place of much dissipation,`" he remarks.
"`I do not recollect, during the whole time I was there, that I saw anything,
in anything, that indicated a feeling of religious sensibility.
There was no place of worship; no priest of any kind,
except one who had been there a few years, who was a dissolute, drunken man.
It was of the Lord`'s mercy that I, and the whole land,
were not destroyed like Sodom and Gomorrah.
At that time, the prince of the power of the air,
who rules in the hearts of the children of disobedience,
had obtained such a victory over me,
that I had become one of the number of those infatuated ones who call good evil,
and evil good,--darkness light,
and light darkness,--to so daring a pitch as to say--__There is no God!__
I not only thought that there was no God, and consequently no religion;
that all the profession of it was but priestcraft, invention, and deceit, but,
so plausibly had I compassed myself with sparks of my own kindling,
that I thought I saw a way to steer my own course.
I had become a complete disciple of Voltaire, and writers of that class.

"`How low, how degraded did I see man to be!
And yet I could dare to think I had reached to that state of philosophy,
and correctness of reasoning, that would enable me to rise from that sink of corruption,
and live a virtuous life,--even concluding that it was this
that preserved me from giving way to many of the vices,
which flowed like a torrent about me.
This was my situation when the Lord himself interfered to release me from that land,
and to open a way for my emancipation from a bondage,
far more to be dreaded than that of the poor slaves whom I commiserated.

"`In the forepart of the spring of 1795 there was a report that
a French fleet was coming to take possession of the colony.
The consequences of falling into their hands,
and the fear of seeing the same cruelties there, that were committed in France,
induced my brother and myself to conclude to leave the country immediately.
An American vessel being on the eve of sailing for New York, we took our passage in her.

"`Thus, in the space of two days, we took our departure.
A few hours later would have prevented it; for, in the evening, as we were going out,
we saw a fleet standing in, which,
we did not hear till some time after our arrival in New York, were the English,
and not the French.
However trivial this circumstance may seem,
it has often appeared to me as one that stands very prominent in the days of my pilgrimage.
I have viewed it as the Lord`'s interposition to
rescue me from the thraldom into which I was plunged;
these bonds, very probably, might have been rendered still stronger,
had I stayed till the English took possession of the colony.

"`During the passage we had several narrow escapes.
Once, after being chased the whole day by a privateer, off Martinico,
at sunset she came alongside of us; but, the sea being high,
they did not even send their boats to us; yet, as we heard on our arrival at New York,
a few days after, they made prize of another American vessel.
When near the Island of Dominica we suddenly found ourselves amidst a bed of rocks,
that threatened every instant our total destruction.
We were obliged to keep in a narrow channel through them.
This led us near to the island, where we saw the inhabitants flying to arms,
and pointing their cannon at us, supposing us to be a designing enemy.
Thus, between their guns and the rocks, we were in imminent danger;
when a way was discovered between the rocks, to make our escape to the open sea.
Twice, during the voyage, the vessel caught fire,
and several bales of cotton were so burnt as to have to be thrown overboard.

"`The morning before we landed at New York,
we were going at the rate of seven or eight miles an hour,
and found ourselves enveloped in such a fog,
that we could hardly see the length of the ship; suddenly it dispersed,
and we saw the Jersey shore, so near,
that men fishing on the beach were clearly perceptible
to the naked eye,--and immediately the fog returned.
A few minutes more, and we must have perished.

"`Thus did Divine providence repeatedly interfere,
and prevent my sinking into everlasting misery.
But such was the obduracy of my heart, all that time,
that I do not recollect to have felt any emotion of gratitude.`"
