== Chapter III.

[.chapter-synopsis]
* Retirement to Long Island
* His Conversion

Safely arrived, after all their perils, in the United States of America,
the two brothers made a short stay in the city of New York.
They soon concluded, however, to retire to Long Island,
"`where they could live more privately and agreeably,
till they might hear how it was with their parents,
and what were their wishes respecting them, either to remain in America,
or to return to them, if they thought it safe for them to do so.`"
They settled down, for the summer, at Newtown.
Here, as had been their former practice,
they sought the best company the place could afford.
It was "`a maxim given them by their dear father, when taking their last leave of him,
always to choose the company of their seniors in age,
and their superiors in rank and abilities, in preference to their inferiors.`"
This led them to visit at the house of Colonel Corsa, whose wife was a Franklin.
They were people of standing in the world, and the Colonel had served in the British army.
He had a daughter who spoke French, and,
the two brothers being entirely unacquainted with the English language on their arrival,
this was a great inducement to cultivate conversation with that family.
One day the conversation at the Colonel`'s turned upon William Penn,
and the daughter saying that she had his works, Etienne`'s curiosity was excited.
He had heard of him as a statesman and politician,
and expected to find something relating to these things in his works.
He took the volume, a large folio, to his lodgings, and, with the help of a dictionary,
began to translate it.
The subject which first engaged his attention was, however,
of so different a nature to what he had anticipated, that he soon laid it aside,
without proceeding far in the attempt to make out its contents.

Stephen Grellet, for so, dropping his French name, we shall henceforward call him,
had now nearly completed his twenty-second year.
His standing in society, his early training,
and the character of his youthful experience in life, had been of a peculiar kind.
Through the influence of surrounding circumstances,
the serious impressions which marked some of his early days,
had given place to sceptical opinions, and he was now a professed unbeliever.
But an important crisis was at hand.
Through one of those remarkable interpositions which, for special purposes,
sometimes distinguish the exercise of the Divine Sovereignty,
and the direct operations of the Holy Spirit, the thick veil of darkness was removed,
the evil heart of unbelief was taken away,
the faith and hope of the Gospel dawned on the soul,
and the objects and pursuits of life were completely and permanently changed.
His own words will best describe the simple facts connected
with the great turning-point of his life--his conversion:--

[.embedded-content-document]
--

"`Through adorable mercy, the visitation of the Lord was now again extended towards me,
by the immediate openings of the Divine light on my soul.
One evening as I was walking in the fields, alone,
my mind being under no kind of religious concern,
nor in the least excited by anything I had heard or thought of,
I was suddenly arrested by what seemed to be an awful voice proclaiming the words,
'`Eternity!
Eternity!
Eternity!`' It reached my very soul,--my whole man shook,--it brought me, like Saul,
to the ground.
The great depravity and sinfulness of my heart were set open before me,
and the gulf of everlasting destruction to which I was verging.
I was made bitterly to cry out,
'`If there is no God--doubtless there is a hell.`' I found myself as in the midst of it.
For a long time it seemed as if the thundering proclamation was yet heard.
After that I remained almost whole days and nights,
exercised in prayer that the Lord would have mercy upon me,
expecting that he would give me some evidence that he heard my supplication.
But for this I was looking to some outward manifestation,
my expectation being entirely of that nature.

"`I now took up again the works of William Penn, and opened upon [.book-title]#'`No Cross,
No Crown.`'# The title alone reached to my heart.
I proceeded to read it with the help of my dictionary,
having to look for the meaning of nearly every word.
I read it twice through in this manner.
I had never met with anything of the kind;
neither had I felt the Divine witness in me operating so powerfully before.

"`I now withdrew from company, and spent most of my time in retirement,
and in silent waiting upon God.
I began to read the Bible, with the aid of my dictionary, for I had none then in French.
I was much of a stranger to the inspired records.
I had not even seen them before, that I remember;
what I had heard of any part of their contents,
was only detached portions in Prayer Books.

"`While the fallow-ground of my heart was thus preparing, my brother and myself,
being one day at Colonel Corsa`'s,
heard that a meeting for Divine Worship was appointed
to be held next day in the Friends`' Meetinghouse,
by two English women on a religious visit to this land, to which we were invited.
We felt inclined to go.
The Friends were Deborah Darby and Rebecca Young.
The sight of them brought solemn feelings over me; but I soon forgot the servants,
and all things around me; for, in an inward silent frame of mind,
seeking for the Divine presence, I was favoured to find in me, what I had so long,
and with so many tears, sought for without me.
My brother, who sat beside me, and to whom the silence,
in which the forepart of the meeting was held, was irksome, repeatedly whispered to me,
'`let us go away.`' But I felt the Lord`'s power in such a manner,
that my inner man was prostrated before my blessed Redeemer.
A secret joy filled me, in that I had found Him after whom my soul had longed.
I was as one nailed to my seat.
Shortly after, one or two men Friends in the ministry spoke,
but I could understand very little of what they said.
After them Deborah Darby and Rebecca Young spoke also;
but I was so gathered in the temple of my heart before God,
that I was wholly absorbed with what was passing there.
Thus had the Lord opened my heart to seek him where he is to be found.

"`My brother and myself were invited to dine in the company of these Friends,
at Colonel Corsa`'s. There was a religious opportunity after dinner,
in which several communications were made.
I could hardly understand a word of what was said, but,
as Deborah Darby began to address my brother and myself,
it seemed as if the Lord opened my outward ear, and my heart.
Her words partook of the efficacy of that '`word`' which is '`quick and powerful,
and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.`'
She seemed like one reading the pages of my heart,
with clearness describing how it had been, and how it was with me.
I was like Lydia; my heart was opened; I felt the power of him who has the key of David.
No strength to withstand the Divine visitation was left in me.
O what sweetness did I then feel!
It was indeed a memorable day.
I was like one introduced into a new world; the creation, and all things around me,
bore a different aspect,--my heart glowed with love to all.
The awfulness of that day of God`'s visitation can never
cease to be remembered with peculiar interest and gratitude,
as long as I have the use of my mental faculties.
I have been as one plucked from the burning--rescued from the brink of a horrible pit.
O how can the extent of the Lord`'s love, mercy, pity,
and tender compassion be fathomed!`"

--

Religious convictions had now taken deep hold of his mind,
and he carefully sought to cherish them.
An anxious enquirer after "`the right way of the Lord,`" he became still further confirmed,
by evidence clear and satisfactory to his understanding,
that what he had experienced "`was really the work of the Lord`'s Spirit,
and not the fruit of an exalted imagination.`"
He now felt it to be his duty to unite with Friends in their meetings for Divine Worship.
Quakerism was, at that time, very imperfectly understood,
and little appreciated even by many Christian professors of other denominations;
much ignorance and prejudice still prevailed in regard to it.
It was by no means generally thought to be a creditable
thing to assume the character and appearance of a Friend.
Stephen Grellet boarded with a Presbyterian family; and some of those about him,
observing that he was disposed to embrace the principles of Friends,
began to reproach him.
Notwithstanding the natural intrepidity of his character, he hesitated.
He did not go to meeting when he felt that he ought to go.
Strong convictions for the sin of disobedience were the consequence.
Great were his sufferings,
under what he believed to be the heart-searching
influence of the light of the Holy Spirit.
"`This,`" he says, "`again set before my view the whole of my past life,
and into what thraldom and misery it had plunged me; I wept bitterly.`"
When the next meeting-day came he concluded to go;
but he went "`through fields and over fences,
ashamed to be seen by anything on the road.`"
To his great mortification,
it so happened that no meeting was held at Newtown--it having been transferred to Flushing,
on that day.
Finding the doors of the meetinghouse closed, he sat down, for some time,
"`in a retired place, and in a very tried state.`"
His cowardice was brought before him; like Nicodemus,
he had attempted to come by stealth;
he deeply felt that he had in effect been "`ashamed
publicly to confess Christ before men.`"
It was a time of great humiliation and searching of heart,
but it proved the means of confirming him in a more
unwavering and decided course of action,
afterwards.
From this time he went straight onwards.

[.embedded-content-document]
--

"`I was brought,`" he says, "`to resignation to endure the world`'s reproaches,
or anything it might be allowed to inflict,
if the Lord would but again lift up the light of his countenance upon me.
The following First-day I went to meeting, though it rained hard,
and I had about three miles to walk.
Divine mercy was pleased to be near, and, as a tender father,
the Lord condescended to instruct me.

"`I continued diligently to attend meetings, which were held in silence.
Very few persons assembled there,
and I had no communication with them at all for some time.
I have frequently considered since,
that it was a favour that my lot was cast in a place
where I had no outward dependance to lean upon.
In religious meetings, as well as out of them,
my single concern was to feel after the influences of the Holy Spirit in my own heart.
As my acquaintance with these increased, so did my exercises.
My heart was fitly compared to the ground covered with thorns and briars,
and even sturdy oaks and tall cedars.
O how many things had to be removed out of the way,
to give room for the heavenly seed to grow.
The axe of God`'s power was lifted up against the root of the corrupt tree.
As wave follows wave, so did my exercises.
Yet I must testify of the Lord`'s unspeakable love extended towards me;
it was great indeed.
The sense of it was so much with me,
that I do not know whether tears of joy and gratitude
have not flowed as plentifully as those of grief,
which latter have not been few.

"`My dear brother, seeing how my face was turned,
began to unite with some of the people about me in
reproaching the way in which the Lord led me,
which added much to my grief.
He could not bear to hear me tell of the Lord`'s work, as it was upon me.
In my absence, however, I found after a while, that he read in William Penn`'s works.
This encouraged me to hope that a seeking disposition was awakened in him,
though he tried to shake it off.
One First-day morning, when my prayer had been renewedly put up in secret for him,
he called me back, after I had set out to go to meeting, saying he would go with me.
How thankful did I feel!
Very few words passed between us by the way.
The earnest petition of my heart was unto the Lord,
that the power of his love and presence might be so displayed,
as to convince my dear brother, and bring him to bow to his righteous sceptre.
My prayers were heard.
It was a memorable meeting,--held in silence, however, as usual,--never to be forgotten.
Very soon after sitting down, great was the awfulness and the reverence that came upon me.
It was succeeded by such a view and sense of my sinful life,
that I was like one crushed under the millstones.
My misery was great; my cry was not unlike that of Isaiah, '`Woe is me,
for I am undone!`' The nearer I was then favoured to approach to Him '`who
dwells in the light,`' the more I saw my uncleanness and my wretchedness.
But how can I set forth the fulness of heavenly joy that filled me,
when the hope was again raised that there was One, even He whom I had pierced,
Jesus Christ the Redeemer, that was able to save me?
I saw him to be the Lamb of God that takes away the sins of the world;
who was delivered for our offences, and raised again for our justification;
who is our propitiatory sacrifice, our advocate with the Father,
our intercessor with God.
I felt faith in His atoning blood quickening my soul, giving me to believe,
that it was He who could wash me from my many pollutions,
and deliver me from death and destruction, which I felt to be my just desert,
for my many sins and transgressions.
On my earnest petition being put up to Him, the language was proclaimed,
'`Your sins are forgiven;
your iniquities are pardoned.`' Floods of tears of joy and
gratitude gave vent to the fulness of my heart!

"`Then I thought I heard again a sweet language saying,
'`Proclaim unto others what the Lord has done for your soul.`'
Apprehending that this was a requisition of present duty,
I began to plead excuses, from the consciousness of my inability to perform the service.
'`You know, O Lord, that I cannot speak English so as to be understood,`' was my answer,
'`and what am I, that I should proclaim your name?`'

"`There was not the least feeling then in me to flinch from doing, or becoming,
whatever the Lord would require of me, but a sense of my inability and unworthiness.
I have since seen that this was more to prepare me for a future day,
than a command for a present offering.
My spirit continued so prostrated before the Lord,
and encircled with his love and presence, that I was insensible to what passed around me.
The meeting concluded, and the people retired without my noticing it, till my brother,
speaking to me, drew my attention, and I saw that we two only were left in the house.

"`My gratitude was great,
when I found that my brother had partaken of the heavenly visitation.
From that time he attended meetings diligently, and was a great comfort to me.
But, during all that period,
we had no conversation with any of the members of the religious Society of Friends.`"

--
