== Chapter IV.

[.chapter-synopsis]
* Removal to Philadelphia
* First Exercise of the Ministry
* Admission into Membership

The "`disciple of Voltaire`" now stands before us as the
practical Christian--the humble believer in Jesus,
the Emmanuel, the Lord our righteousness, "`that lives and was dead,
and is alive forevermore.`"
How wonderful the change!
Incomprehensible to the natural man--but not on that account the
less real--it was a living comment upon the words of Jesus,
"`the wind blows where it wishes, you hear the sound thereof,
but can not tell from where it comes, and where it goes:
so is every one that is born of the Spirit;`"--it was a beautiful
illustration of the declaration of our blessed Lord,
"`when he, the Spirit of truth, is come, he will guide you into all truth:
for he shall not speak of himself; but whatsoever he shall hear, that shall he speak;
and he will show you things to come.
He shall glorify me; for he shall receive of mine, and shall show it unto you.`"
Under the presence and power of the Holy Spirit,
the transition from the mazes of infidelity to the humble
and believing reception of the truth as it is in Jesus,
in the love of it, was, in this instance, both rapid and complete.
It was peculiarly marked as the Lord`'s own work;
human instrumentality was but little made use of.
In the course of a few months the young convert had acquired an entirely new position.
God had not only "`revealed his Son in him`" as his own Saviour, but, as has been seen,
the call to "`preach Him`" among his fellow-men, had, at the same time,
been distinctly heard.
And he was "`not disobedient to the heavenly vision.`"

"`He is a chosen vessel unto me, to bear my name before the Gentiles, and kings,
and the children of Israel;
for I will show him how great things he must suffer for
my name`'s sake,`" was the word of the Lord to Ananias,
while he was hesitating to bear the required message to the praying Saul of Tarsus;
and in the case of Stephen Grellet, not altogether dissimilar,
it was instructively manifest that "`God`'s ways are not as our ways,
nor his thoughts as our thoughts.`"
He "`who commanded the light to shine out of darkness,`" had shined in his heart,
to give him "`the light of the knowledge of the glory of God in
the face of Jesus Christ,`" and henceforward his Christian character
is seen steadily maturing in the richness of a deep personal experience,
while, in the progress of the work of Divine grace in his heart, he was prepared,
during a long course of years, to partake largely of the blessing of those, who,
"`with open face beholding, as in a glass, the glory of the Lord,
are changed into the same image, from glory to glory,
even as by the Spirit of the Lord.`"

He felt as one "`alive from the dead,`" and his Christian walk bore evidence that "`the
life which he now lived in the flesh was by the faith of the Son of God.`"
He continued to frequent the "`little silent meetings`" at Newtown,
and to unite with Friends in their simple mode of worship.
Though, in his secluded abode on Long Island,
he had very little opportunity of associating with its members, by careful investigation,
he became increasingly convinced of the rectitude and scriptural soundness of
the Christian principles and testimonies of the religious Society of Friends,
and he felt it to be his duty entirely to carry them out in practice.
Great was his love for the Saviour, in whom he had joyfully believed,
and proportionately earnest was his desire to follow Him in all things.
There was something quite characteristic in the tender conscientiousness
with which he brought his views of Christian simplicity
and self-denial to bear upon his daily walk in life,
especially in connection with the costliness of some of his own habits,
and the privations endured by others.

[.embedded-content-document]
--

"`It was a time of much scarcity of provisions in France;`" he remarks,
"`great was the distress of the inhabitants.
My dear mother wrote me,
that the granaries we had at our country-seat had
been secured by the revolutionary party,
as well as every article of food found in our town-house.
My mother and my younger brother were only allowed the scanty
pittance of a peck of mouldy horse-beans per week.
My dear father was shut up in prison, with an equally scanty allowance.
But it was before I was acquainted with the sufferings of my beloved parents,
that the consideration of the general scarcity prevailing in the country,
led me to think how wrong it was for me to wear powder on my head,
the ground of which I knew to be pride.`"

--

The expensive habit was, of course, relinquished;
his Christian consistency was rendered more complete,
and his money saved for better purposes.

[.embedded-content-document]
--

"`Being convinced,`" he continues, "`of the propriety of the plain language,
I took up my cross in that also, though it exposed me to much ridicule.
Being about to write to my parents, the cross became great,
chiefly because this way of speaking was then adopted
by the Revolutionist party in France,
from whom my parents, with most of the nobility, were suffering so much.
But I was under the necessity with plainness and simplicity
to make use of the language I saw to be my duty,
leaving every consequence to the Lord.
Thus, becoming resigned, I felt sweet peace,
and this exercise tended not a little to strengthen me to bear
the various railings and frowns of the world that I had to encounter.
Some who before had courted my company, now turned away;
and this became a blessing to me,
for it tended quickly to make the separation greater between me and the world.
One circumstance occurred that I may not omit, as it shows that,
when we are endeavouring to follow the ways of the Lord,
he may turn our anticipated difficulties into encouragements.
I had occasion to go to New York to see one of our first merchants on business.
I was afraid lest, presenting myself before him in such a different manner,
he might make some mortifying remarks;
for it was a strange thing to see a Frenchman becoming a Quaker.
I felt my mind very low, and exercised before the Lord, when I came to him.
He, seeing my embarrassment, said to me, in a very mild and respectful manner: `'sir,
I perceive you are embracing the principles of the Society of Friends;
it is one of the most respectable societies I know.`' This was an unexpected encouragement.

"`By letters from our dear parents, we learnt that it was their choice that we should,
for the time being at least, remain in this country,
seeing that the troubles in France continued great,
and that our lives would be exposed by returning to it.
Our parents were in constant jeopardy.
Their estates were under sequestration,
and it became necessary for us to turn our attention
towards engaging in some kind of business.
Our means began to be low,
and yet our feelings for the sufferings in which our beloved parents might be involved,
caused us to forget ourselves, strangers in a strange country,
and to forward them a few hundred dollars we had yet left.

"`I did not find it easy to obtain suitable employment,
but I sought right direction of the Lord.
We first came to New York, where I stayed about two weeks.
I was much refreshed with the company of some valuable Friends.
I considered it a special privilege to sit with them in their religious meetings.
Their hearts were also opened in love towards me,
and as I saw that it was the Lord`'s doing, from whom every good comes,
in gratitude I returned the praise to him.
The exercise of bearing a public testimony to the Lord`'s truth,
and of declaring what he had done for me, came again upon me, with force, in that city.
But dwelling in stillness, and waiting for clearness,
I was favoured to see that the time was not yet.

"`It was concluded that I should go to Philadelphia, and my brother,
meeting with a situation, continued in New York.
Our separation was painful, having partaken together of many trials,
and feeling much united in our religious exercises.
I arrived in Philadelphia in the 12th mo.
1795, and met with a very kind reception from many Friends.
I found fathers and mothers in a spiritual sense.
They, having a feeling of the exercises that were upon me,
were tender of me,--and they were so with judgment.
They had but little to say in words,
but I often felt that my spirit was refreshed and strengthened in their company.
I could say much of what I have experienced of their watchful care and love,
and of the help and counsel they have been the instruments to convey to me.

"`I had several offers to engage in commercial concerns, both in Philadelphia,
and from my European friends, particularly in Holland, from whom I received proposals,
by letters, to place me in an extensive way of business with the West Indies and Holland.
But, keeping my eye single to the Lord, whose direction I sought,
I could not be easy to accept any offer of this kind; for I saw that if I did,
the sense of life in me, that was very tender, might easily be destroyed.
I therefore preferred, for a while, the occupation of teaching the French language.
I engaged in it, it is true, much in the cross; but,
having repeated evidence that it was a right engagement for me,
it became easy to submit to it.
I was at first concerned lest it should not be sufficient to procure me a living.
For, from the complexion of things in France,
I could not entertain any expectation that I should
receive pecuniary means from that quarter.
After many anxious thoughts on this head, one day,
as my mind was gathered in reverent silence before the Lord,
the language was strongly impressed:
`'seek first the kingdom of God and his righteousness,
and all things needful shall be added.`' The evidence that it was the direction of Omnipotence,
whose promise is sure, was so clear, that no doubt remained; and for months after that,
I was so relieved from temporal anxiety,
that I had no more thought about it than if I had not lived in the world.
I was closely engaged in my school,
and though I scrupulously paid every requisite attention to it, yet,
during the intervals, my mind was wholly relieved from anxious thoughts about it.
The one thing needful only absorbed me, while walking in the streets,
or sitting in the house.
I speak it with care,
yet the remembrance of those days can but deeply humble me with gratitude,
seeing how the Lord kept me close to himself.
A sense of his presence was so continually upon me,
that not only my words but my thoughts also, were narrowly watched.
My exercises had no interruption, but, like the rolling waves of the ocean,
they flowed one upon another.
If I took a book to read, a single line would detain me for hours.
Sometimes I have been a whole week in reading and pondering a single chapter in the Bible.

"`My mind was, at seasons, so taken up with a sense of the Lord`'s love,
that it seemed as if I could have continued days and nights swallowed up in it.
But though the love of God thus filled my heart,
yet most of the time it was clothed with deep exercises.
Every step of my past life was retraced again and again.
I suffered deeply not only for the evil I had done,
but also for the good I had omitted to do,--not only
for the great loss I had sustained myself,
but also for the harm I saw that my example might have done to others.
I saw the emptiness and arrogance of Cain`'s reply to the Almighty,
'`Am I my brother`'s keeper?`' We ought to be watchers over one another,
and great is our responsibility as moral agents.
The whole of God`'s creation, especially his rational one, was brought very near to me.
O! what is not the power of Divine and redeeming love able to do?
What a thorough change it produces!
My transgressions had been great; the last years of my pilgrimage especially,
had been marked with such circumstances, as to have totally estranged me from Christ,
and my mind had been worked up, to a high degree,
into a nature opposite to the lowliness, the meekness, the forbearance and charity,
becoming a servant and disciple of Christ.
Deep therefore were the baptisms necessary to bring me out of my fallen state,
to that holy mountain where none hurt or destroy.`"

--

During the winter of that year Deborah Darby and Rebecca Young (afterwards Byrd),
who had been the first instruments through whom "`the Gospel`'s
refreshing streams had reached his heart,`" at Newtown,
visited the families of Friends in Philadelphia,
and Stephen Grellet had frequent opportunities of being with them.
They were made the means of confirming him in the knowledge of Christ,
and he thankfully acknowledges the benefit derived
from their company and labours in the Gospel.

A year had not passed since the hand of the Lord was effectually laid upon him,
when He who had "`called him by his grace,`" was
pleased so remarkably to "`reveal His Son in him.`"
And "`one of the exercises which now lay with much weight upon him,
was the continued apprehension that it was required of him publicly
to testify of the Lord`'s wondrous works and mercy towards him,
in the assemblies of the people.`"

[.embedded-content-document]
--

"`I saw,`" he tells us, "`my unworthiness to engage in such a solemn service,
and felt myself to be altogether a child,
that was only beginning to breathe the breath of life.
Though I had made some progress in the knowledge of the English language,
I knew how defective I was,
and especially unqualified to act in the capacity of an ambassador for Christ,
in the congregations of the people.
How great was the Divine condescension in those days of my deep probation!
As a father answers his child,
so the Lord condescended to answer all my pleadings and excuses;
to give me also a sense of the source from where all power, strength, and ability flow.
He showed me how He is mouth, wisdom, and utterance to his true and faithful ministers;
that it is from Him alone that they are to receive
the subject they are to communicate to the people,
and also the when and the how.
It is He who gives the seeing eye, the hearing ear, the understanding heart,
and enables the dumb to speak.
I saw how, at the day of Pentecost, the disciples of our Lord, who were born again,
'`not of corruptible seed, but of incorruptible, by the word of God,
which lives and abides forever,`' were taxed with opprobrium,
when the fruits of that new birth, through the everlasting spirit,
were brought forth in them, and every one heard them in their own tongues,
speaking of the wonderful things of the kingdom of God.
But what depth of knowledge they were endued with,
after they had received the Holy Spirit!
The mere touching upon these things may suffice to bring some of my fellow servants
to consider the Lord`'s gracious dealings with them.
My desire for them is that they may come to the state of
the child,--the weaned child,--that they may come to Christ,
and learn of him; for though there may be much instruction in the sciences of the world,
yet Christ is the only teacher in the things of God.
Great was the Lord`'s condescension in instructing me, his poor servant,
and deep were the impressions made on my mind,
in attending to the immediate teaching of the Holy Spirit.

"`Meeting after meeting I was under the pressure
of exercise to stand up and speak a few words;
but the sense of the awfulness of the engagement prevented me, time after time,
till the Lord`'s displeasure was felt to be kindled against me.
O the depth of my baptisms, in those days!
My disobedience did not, however, proceed from any outward considerations,
or even the crosses involved to the natural man.
I was brought too low to have thoughts of this kind; and, I think I may say,
my love for my dear Master was so great,
that no sacrifice or suffering would then have been thought too much;
but I could not believe that such a poor creature as I was,
such a great sinner as I had been, could be fit to engage in such a solemn work.
My condemnation was, that after repeated evidences of the Lord`'s will respecting me,
I should still continue to be of a doubtful and fearful mind.
It was on the 20th of 1st month, 1796, the third day of the week,
that I first opened my mouth in the ministry.
For some days after this act of dedication, my peace flowed as a river,
while my eyes were like fountains of tears of gratitude,
in that the Lord had so mercifully continued to bear with me.
Besides the internal evidence he gave me of his Divine approbation,
several of his dignified servants, as William Savery, Samuel Emlen, Rebecca Jones, etc.,
stood up after me,
bearing testimony to the Lord`'s power and the sufficiency of his Divine Truth,
as displayed on my behalf.`"

--

Stephen Grellet had not, at this time,
made application for membership in the Society of Friends.
Though his advancement in the school of Christ was unusually rapid,
he was not precipitate in his movements--Christian prudence and caution marked his steps.

[.embedded-content-document]
--

"`Friends,`" he says himself,
"`saw the tender and exercised state of mind in which I was,
and dealt with me with much feeling and affection.
Even while acting towards me the part of nursing fathers and mothers,
their wisdom and care were manifest, neither to lay hands suddenly on me,
by encouraging me to become a member of their Society, nor to discourage me,
while not yet one,
from bearing among them the testimonies the Lord gave me for his Truth.
My spirit was so absorbed in the one thing,
that for some time I did not much think of seeking for an outward
fellowship with a people to whom I was closely united in spirit;
but, when the concern came before me to apply to become a member among them,
which was not till the summer following,
I was brought under close exercise that I might take a right step.

"`The ground of my faith, the nature of the testimonies I had already borne publicly,
and what I apprehended I was convinced of, were closely considered.
For I saw that it would not do for me to become a member of that
religious society unless I was established in their Christian principles,
and was convinced also that these principles were
consistent with the Truth as it is in Jesus.
I thought that because Friends professed principles
similar to those which I had been led to adopt,
through the teaching of the Holy Spirit,
and because I had so often found among them the Sowings of the Divine Light and Life,
to my great refreshing,
this was not a sufficient ground for me to conclude to become one of their body.
I was afraid to take such an important step,
without a clear pointing and evidence that it was my duty so to do;
which I sought for with many prayers, watchings and fastings.
My religious principles and testimonies were again carefully considered,
and I also attentively reexamined those professed by Friends.
It was not till I was brought to see and feel again the foundation upon which they stand,
even the eternal rock--Christ Jesus,
that I could feel satisfied to join them in outward fellowship.
The first rudiments of the Christian religion, the fall of man,
my own fallen and sinful condition, redemption and salvation by Christ alone,
the true Christian baptism, the supper, Divine inspiration, worship, ministry, etc.,
were again fully brought into view.
At last, feeling with satisfactory clearness,
that Friends were the Religious Society the Lord
would have me to unite with in Christian fellowship,
I made application, at the North Meeting, to be received by them,
which they accepted in the fall of the year 1796.

"`I have been a little particular in describing my exercises,
and the weight attending me, before I applied to become a member,
as I have often felt since,
that much responsibility attaches to us who have
joined this Society on the ground of convincement:
for if we do not come in at the right door, that is both of conviction and conversion,
we cannot profit the people we come among,
neither can we be much profited by them ourselves.
No man, nor any religious body, can save any.
Salvation comes from God alone.
How can any be on the saving ground, who publicly profess,
that they are convinced of the Christian principles and testimonies
which our religious Society maintains (which I am most fully persuaded
are founded on the blessed Truth as it is in Jesus,
according to the Holy Scriptures), who do not walk accordingly?
It would be better for them never to have come to the knowledge of them,
and of God`'s Truth, than after having been brought thus forward, not to keep to them.
Consider, I beseech you, my dear brethren and sisters,
what discouragement such are bringing on the young people, as well as others.
Do they not speak, by their conduct, the language of the evil spies?
Was it by constraint, or in the pursuit of worldly honours, preferments, and glory,
that we joined this people?
Some of you must unite with me in saying,
O no! but it was under the convictions of Divine Truth,
in pursuit of the life and peace of our souls,
that some of us have been made willing to encounter the frowns and reproaches,
not only of the world, but of former friends and near relatives,
to lose among them our reputation and estates, to be reviled and evil-spoken of,
yea to suffer the loss of all things, and to count them all dross,
so that we might win Christ, whom we saw to be the only One,
worthy of our pursuit and of our love.
O Friends! in the remembrance of his marvellous dealings towards us,
in the days of our great and unfathomable distress, and unutterable exercises,
how he has led us, sustained us, kept our souls alive in famine,
brought us to the refreshing streams, been our Shepherd to feed us,
our Bishop to instruct us, and our Saviour to deliver us,
can we help feeling our hearts to be lifted up, and our tears of gratitude to flow again!
Let none of us then rest satisfied in an outward profession of
those testimonies which we have attained through many conflicts;
but let us feel after an establishment in that Truth which is over all,
and must spread from sea to sea, and from the rivers to the ends of the earth.
Ah Friends! how mournful would it be, if any of us,
after having known the salutary and refreshing influences
of the blessed Truth to draw near to us,
from the ocean of everlasting love,--should outlive the day of visitation, and,
the tide returning back to its centre, be left dry and desolate!
You all, who feel the bedewings of Divine love,
walk under its influence:--live in the Truth, and the Truth will keep you,
and do all things for you.
Every terrestrial object shall pass away, but the Truth endures forever!`"

--
