== Chapter V.

Philadelphia Yearly Meeting--His Parents--First Journey in the
Service of the Gospel--Acknowledgment as a Minister of Christ

Stephen Grellet had now become a member of the religious Society of Friends.
In the maturity of early manhood, he had taken a deliberate but a decided step.
In uniting himself to a Church which, while,
in common with other professors of the Christian name,
it gave its "`hearty assent and consent to all and everything`"
appertaining to the fundamental Truths of the Gospel,
as contained in the inspired records of Holy Scripture, yet differed, more or less,
from most, as to the mode and extent in which it believed itself required,
under the government and guidance of the Holy Spirit,
to carry these principles out in practice, he appears, at once,
to have found a permanent resting-place for his soul.
There is no trace, in his most private memoranda at this time, or ever afterwards,
of the least misgiving as it regards the position which he had felt it right to assume.
Neither the reminiscences of his early connection with the Papal system,
nor the different phases of scepticism and infidelity through which he had passed,
appear to have left the elements of doubt or hesitation upon his mind.
Born of the Spirit,
and become a "`child of God by faith in Christ Jesus,`" he had
counted the cost;--without attempting to do the work by halves,
he had consecrated himself entirely to the service of his Redeemer,
and he had already received, and publicly exercised,
a gift in the Ministry of his Gospel.
The love of God was remarkably "`shed abroad`" in his heart.
He had felt the preciousness of "`the blood of Jesus Christ his Son,
which cleanses from all sin`"--and,
deeply impressed with the truth that the "`sons of God`" are "`led by the Spirit
of God`"--it soon became the characteristic bent and concern of his mind to "`walk
in the Spirit,`" and to bring forth the "`fruits of the Spirit.`"
Peculiarly marked as had been his previous course,
and very unusual as were the developments of his after life,
the Providence and Grace of God were signally displayed in his
being brought into connection with a Christian community which,
according to the usages of the primitive Church of Christ,^
footnote:[See Noander`'s "`Planting and Training of the Christian Church,
by the Apostles.`"--Chapter on the Constitution of the Gentile Church.]
allows such full scope to the operations and leadings of the Holy Spirit,
and admits of the free exercise of every spiritual gift,
in whatever direction the rightly authorized ambassador
for Christ may be called to labour.
For his soon became, and for a long course of years continued to be,
emphatically "`A Missionary Life,`" in a sense in which probably
no other religious Society could have recognized it,
or made way for its full development and practical carrying out.

Soon after he was received into membership with the Society
of Friends the Yearly Meeting was held in Philadelphia.
It was the first Meeting for Discipline which he attended.
That large Yearly Meeting, to which he now belonged,
was at that time distinguished for the number and
character of the faithful servants of the Lord Jesus,
who stood in the foremost ranks,
and truly adorned the Doctrine of God our Saviour by the meekness and gentleness,
as well as the devotedness of their lives.
Stephen Grellet remarks:--

I received much instruction at that Yearly Meeting.
The weightiness of the spirits of many Friends, I thought, was very conspicuous.
Business of peculiar importance, and which claimed much interest, was transacted.
One of the concerns was relative to the Indian tribes,
which some Friends were appointed to visit.
A large committee was set apart to have the particular care of this concern,
which has been much blessed in their hands.
Other Yearly Meetings shortly after felt a similar concern,
to extend a Christian care over some other tribes.
Their labours of love have been so blessed in several instances, that it may be said,
respecting some of these people, that the wilderness has flourished.
Some of them have been brought, in a considerable degree, to a civilized state,
in the cultivation of their lands, etc.,
besides being in some measure made acquainted with the truths of the Christian religion.

Another subject, which obtained much of the attention of Friends at that meeting,
was the state of the oppressed Africans.
The Yearly Meeting came to the conclusion that any people of colour,
becoming convinced of our principles,
and making application to be received as members of our Society,
ought to be treated as white persons, without any distinction on account of colour,
seeing that there is none with God,
who has made all the nations of the earth of one blood,
and that Jesus Christ has died for all, and is the Saviour of all who believe in Him,
of whatever nation or colour they may be.

The horrors of the French Revolution continued,
and while humbly endeavouring to pursue the path of Christian duty,
as it had been opened to him in the new sphere in which he moved,
Stephen Grellet`'s tender and susceptible heart was frequently
brought into much conflict on behalf of his beloved parents.

"`The accounts which I received, in those days,`" he remarks,
"`of the distracted state of my native country, much afflicted me.
My dear parents being in prison,
I expected every day to receive the mournful tidings
of their having met with a cruel death,
among the many victims who fell a sacrifice to the
ferocious spirit that had overspread the nation,
having been informed also that some of those who heretofore had
professed to be the most intimate friends of my dear father,
and others to whom he had rendered many services,
were now his greatest enemies and persecutors.
This brought me to test the ground of my religion,
which is love Divine,--love even to enemies.
My prayers were put up for his persecutors, and, through adorable mercy, I found that,
though I abhorred the spirit that influenced them, I could pray for them,
and desire their salvation as my own.
Yet, as I was afraid of myself, and knew that the adversary was very near,
to strike at the Christian temper in me.
I felt the necessity of keeping a double watch over
my lips,--not to talk of what was passing in France;
and over my heart,--not to entertain any thoughts
but such as flowed from the Divine spirit of love.`"

After remarking upon the comfort and efficacy of prayer under the
trying circumstances in which his beloved parents were placed,
he continues:

"`And here it may be proper also to state,
that they were preserved from an untimely death,
and delivered from the hands of unmerciful men,
though my dear father was several times on the very eve of being taken to the guillotine,
and my mother also.
It was finally concluded that they, and others,
should be put to death the day following the death of Robespierre, when,
that very morning, instead of being led to execution, as proposed,
the prison doors were opened for their liberation.
I may further gratefully say, that none of my near relatives suffered a violent death,
during those days of terror, as they have been justly called; which few, if any families,
situated as ours was, can probably say.
A first cousin of mine was ordered to be put to death,
but on the morning appointed for his execution, he was rescued.

"`And now, while relating the Lord`'s gracious dealings,
I feel my spirit contrited at the remembrance of them.
He indeed led me about and instructed me, and brought me so under his discipline,
that in those days, he was felt to be the life of my soul, and the spring of my thoughts.
The watch over the avenues of the heart was so maintained that if a single thought presented,
foreign to heavenly things, or such as concerned not the salvation of my soul,
I was greatly troubled; so that in the evening, when, as was my practice,
before I made a record of the manner in which the day had been spent, I came,
silently and solemnly in the Lord`'s presence, to inspect my heart,
how it had been with it during the day, if I found that it had been turned,
even for a short time, unprofitably from God, its centre, I could not retire to rest,
till I had a sense of the Divine mercy and forgiveness.
My enquiry was not so much, whether I had retired from the world to wait upon God, as,
whether I had retired from God`'s presence to harbour worldly thoughts.
These were days of close discipline, days of deep trial,--but days of great joy also,
in which the Lord had so warmed my heart,
that my spirit was absorbed in the love and the things of God.

"`During the following year I continued in much retirement.
I spent most of my time alone,--alone I should not say,
for I was never less alone than when in my chamber, separated from outward association.
My indwelling was then with the Lord, in his presence, at whose school I learned,
and in whose discipline I was closely kept.
Yet I underwent many temptations; for when the adversary could not lift me up,
he sought to cast me down.
O the depth of agony I sometimes passed through!
But the Lord, through all, was my helper and the lifter up of my countenance,
when sometimes I was sunk so deep in the low dungeon
that I thought I could not rise again.
Many days and nights have I spent in pouring forth my tears before the Lord.
But you, fellow pilgrim! that may be led into the trackless deep, as I have been,
where the weeds appear to be wrapped about your head,
receive the testimony of one who has trodden the path before you,
and allow it to act upon you as an encouragement to keep the word of the Lord`'s patience,
amidst all his dispensations, even when you can not see the end of them.
The lower he has brought me,
the more he has given ability to bring out of the deeps bright memorials;
the greater has been the temptation,
the more excellent the power and the mercy to deliver from it;
for the Lord has graciously ministered to his poor servant.

"`I was led, in those days, into some peculiar straits,
and on this subject I cannot omit speaking a few
words to those who are under tender scruples,
and who apprehend that these are of the Lord`'s requiring.
Keep under them, my friends; eye the Lord under them; but, at the same time,
be careful not to judge your brethren,
who are not led into the same restraint as you are.
For these exercises may be brought upon you for the very purpose to humble you;
but if you judge your brethren, and give way to a censorious spirit,
self in you will be exalted,--death, and not life, will have dominion over you.
Make a distinction between that which is essentially and permanently obligatory,
and those straits and exercises that belong only to yourselves,
in order to keep you under close discipline,
and in which your obedience will be equally requisite,
when the Divine command may go forth to you, to cease from those things, as now,
when you think you are called to practise them.
And you who are not led into straits, like your brethren,
be tender of their scruples,--feel for them--and encourage them, even to faithfulness;
for nothing, ever so small, which is of the Lord`'s requiring, is to be slighted;
and it is in proportion as we are faithful in little things,
that we are made rulers over more.
One of the difficulties under which I was brought related to my eating and drinking.
I felt myself prohibited from partaking of animal food,
and also of everything that was the produce of slavery;
for the sense of the sufferings of that people was heavy upon me.
After I had been thus led for about two years,
I began to be afraid lest I should continue in that manner of living from former apprehensions,
and not from the continued requiring of the Lord, and thus,
by being singular among my friends, improperly draw their attention to me.
In much fear I ventured one day to partake of animal food again,
but great distress came upon me, attended with a renewed evidence, that my outward man,
as well as my inner one, must be kept in much lowness.
I felt also an assurance, that when the days of my release from this fast should come,
I should have the same undoubted assurance of it, as I had then of being led into it.

"`I continued about five years under that exercise, and when my release came,
the free use of everything in the creation was set before me,
so that I received it with thankfulness and moderation.
Great was the fulness of the Lord`'s love, at that time,
and the sweetness of his presence.
It seemed as if heaven was opened, and the angelic host was about me,
proclaiming the Lord`'s praise and glory,
to which I was permitted to join my feeble accents.
This took place at the house of my dear friends John and Esther Griffin, at Purchase,
while travelling on a religious visit in company with my beloved friend John Hall.
A holy solemnity came upon us all.`"

The summer of 1797 was rendered interesting in the life of Stephen Grellet,
by his first entrance upon some of those services, in the Gospel of Christ,
for the good of his fellow men at a distance from his own home, which, in after days,
claimed so much of his time and Christian devotedness.
Though not yet recorded as an acknowledged Minister,
he felt it to be his religious duty "`to visit in the love of the Gospel,
and to distribute Testaments and religious books among the
poorer class of inhabitants about Little Egg Harbour,
Barnegat, and the sea-shore in New Jersey,
and in the Pines;`" and he "`took care to have the unity of his friends,
Ministers and Elders, at home,
before engaging in a work which he felt to be very important.`"
His friend, Enoch Evans, a valuable Elder from Cropwell meeting,
united with him in the service.

"`I proceeded in it,`" he says, "`in much lowness of spirit,
keeping close to my heavenly guide.
He so condescended to me, that on coming into a family,
a feeling of Divine love clothing me, I was enabled to communicate my concern for them,
so as, in many instances, to reach the witness for Truth in their hearts.
Many of those opportunities were favoured seasons,
and proved visitations of love and mercy to the people.
Most of them received us, and our books, with tears of gratitude.`"

On his return from this visit,
he found that some cases of the Yellow Fever had made their appearance in the city,
and many of the inhabitants had retired into the country to escape the infection.

"`I visited some of the sick,`" he writes, "`and felt much for the people.
The Lord was pleased to prevent the spreading of the contagion.
Many testimonies were borne, during the forepart of the year,
to bring the people to a sense of the Lord`'s mercy,
in having restrained the hand of the destroying angel;
forewarning them also of what was impending over the city,
if they did not return to the Lord, and break off their sins by sincere repentance.
This concern was heavy upon me for months,
so that sometimes it seemed as if I must go through the streets of that great city,
and declare to the people what the Lord was going to bring upon them,
because of their iniquities; for, when he had a little shaken his hand over them,
instead of receiving the warning, they had returned, during that winter,
to all their follies and vanities.
But after a while,
being present at several meetings when powerful and
clear testimonies were borne on this subject,
the concern of my having to proclaim the same through the streets, was removed from me,
for which I felt humble gratitude.
Yet my secret exercise for the inhabitants continued.`"

Thus, "`walking humbly with his God,`" was the mind of Stephen Grellet,
prayerfully observant of the "`signs of the times,`" and prepared to recognise the hand
of the Lord in those public calamities which are permitted to visit cities and nations,
for purposes too little regarded, even by those who bear the name of Christ,
and who would not willingly be suspected of calling in question the reality and minuteness
of that providential superintendence which takes cognisance even of the falling sparrow.
To the thoughtful reader,
these indications of character will appear to have
an interesting bearing upon the sequel of this narrative.

Steadily pursuing the path of Christian dedication,
Stephen Grellet had continued to exercise his gift as a Minister of the Gospel,
to the satisfaction of the Church, and, in the 3rd month, 1798,
he was duly recorded as a Minister of Christ,
by the Monthly Meeting for the Northern District, in Philadelphia,
of which he was a member.
Such an event could not fail to be deeply interesting to him.

"`It brought my mind,`" he says,
"`under renewed concern that I might be so preserved in watchfulness,
and humble walking before the Lord, as in no wise to wound his great and blessed cause,
which I believed he had condescended to call such a poor unworthy instrument,
as I felt myself to be, to espouse.
Earnest were my secret supplications that my life and conversation might comport
with the station of an ambassador for God--a minister of the Lord Jesus Christ;
one prepared to hold out to others what he has actually
known of His redeeming love and power,
speaking none other things than what he has himself tasted
and handled of His Divine and saving word of life.
In those days my mind dwelt much on the nature of
the hope of redemption through Jesus Christ.
I felt the efficacy of that grace by which we are saved,
through faith in Christ and his atoning blood, shed for us on Calvary`'s Mount;
and the excellency of the blessed gifts, which,
in consequence of this the meritorious sacrifice of himself for sinful man,
are offered to the believer in his name,
especially that of the outpouring of the Holy Spirit.
It was my soul`'s chief concern to draw the attention of
the people to this saving work and experimental faith,
and I felt that the best testimony I could bear to the efficacy of the Redeemer`'s love,
was to evince, by my life, what he had actually done for me.`"

It was the practice, at that time,
for the Ministers and Elders of the city of Philadelphia to assemble together,
once a week, for mutual conference and edification,
thus constituting what was called "`The Second-day Morning Meeting.`"
Soon after he had been recorded as an acknowledged Minister,
Stephen Grellet was invited to attend these meetings, and he remarks respecting them:
"`They were to me instructive meetings.
As a child amidst the fathers and mothers in Christ,
my mind was prepared to receive and improve what
my blessed Master was pleased to communicate immediately,
or through the instrumentality of his servants.`"
