== Chapter VI.

Second Journey in the Service of the Gospel--Yellow Fever
in Philadelphia--Yearly Meeting--Conclusion to Leave Pennsylvania

Not long after the important change in his position,
as a fully recognized Minister of Christ,
he believed it required of him again to travel in the service of the Gospel.

"`Feeling drawings of Gospel love,`" he writes,
"`towards some parts of the sea shore about Cape May, Great Egg Harbour, etc.,
having obtained the approbation and certificate of my friends,
I set off about the middle of the 7th month.
My dear friend Joseph Clark accompanied me in this service.
Besides visiting Friends in those parts, we went into about eighty-four families,
mostly of the poorer class of the inhabitants.
We had also several meetings among those of other denominations.
Very gracious was my dear Master in leading me about and instructing me,
and also in qualifying me, his very poor servant, who was but a child,
for the work he had sent me to do.
I returned home, after an absence of about three weeks and a half.

"`Hearing that the yellow fever had again made its appearance in Philadelphia,
the great exercise under which I had been for its inhabitants, returned with weight,
and I felt it my duty to go back to the city.
O how thankful did I then feel that I had not willfully
departed from the Lord`'s pointings of duty,
last winter, by not proclaiming through the streets,
the coming of that visitation of mortality among them.
If I had willfully departed from the Lord`'s command, it would then, I think,
have been too hard for me to bear.

"`A few days after I heard of the appearance of the fever, while I was yet in Jersey,
as I was sitting in a room, with my mind retired before the Lord,
I was seized with a violent pain in my back, head, and bones,
accompanied with a great shaking;
but my mind continued perfectly calm in the Lord`'s presence.
After having remained some time in that state, considering why it was so with me,
a secret language was proclaimed;
'`This is the manner in which those who are seized with the yellow fever are affected;
you must return to the city, and attend on the sick;
and thus also shall the disease take hold of you,`' or words very similar.
My spirit bowed in prostration before the Lord, and said,
'`Your will be done.`' Then I felt again free from pain.
I proceeded immediately to Philadelphia, keeping these things, however, to myself.

"`My friends of Woodbury, Haddonfield, etc., among whom I passed,
endeavoured to dissuade me from going to the city,
representing what dangers I should encounter;
but my mind was perfectly calm and serene about that.
When I came into it, the sight was solemn.
That great city, but a few days before full of inhabitants, was now nearly deserted;
its heretofore crowded streets, were now trodden by a few solitary individuals,
whose countenances bespoke seriousness or sadness.
On reaching the friend`'s house where I made my home, I found it shut up,
like most of the neighbours`'; but, obtaining the key, I opened it,
and resumed my former abode, though alone in it.
Several of my friends were urgent that I should go and stay with them,
but I could not be easy so to do.
Under the impression I had that I should have the fever,
I was unwilling to expose any of my friends to take it from me.

"`I went about for some time, visiting the sick and dying,
and assisting in burying the dead.
My friend E. G. was a faithful colleague in this solemn work, which,
however awful and gloomy, was yet attended with much peacefulness.
My feelings were much awakened, both on account of strangers and Friends.
How sweet and peaceful was the close of some,
so that I could have joyfully exchanged my situation for theirs;
but how great the contrast with others!
Some joyfully and smilingly departed,
in the fulness of the hope which the Gospel inspires;
whereas others experienced the agony and horrors of death--throwing their arms around me,
to keep hold of a living object, crying out in bitterness, '`I cannot die!
I am not fit to die!`' The horror of the scene is yet present with me.
O that those who live in pleasure might pause awhile, and contemplate the awful subject.
Do not leave it to a sick-bed, or a dying hour, to make your peace with God.
Rather, I beseech you, improve diligently your opportunity in time of health, and,
while the Lord`'s visitation is extended to you, make your calling and election sure,
through Jesus Christ!

"`In those days former friends were deserted; yea, even the wife was left by her husband,
and the husband became a stranger to his wife--seeking their safety in flight,
leaving their sick to the care of a strange nurse.
The dead bodies were conveyed to the grave, in most instances,
with no other convoy than the hearse and driver.
This was the case even with those, who, weeks before,
might have been attended by hundreds.
Most of the places of worship were shut up.
I think, for a while, none in that great city were left open,
but the Meetings of Friends, to which many of the sober people who could leave the sick,
often came; and we had solemn meetings, for the Lord`'s presence and power were with us.

"`The evening of the 25th of the Eighth month, having been much engaged that day,
in providing for about ten Lascars, (East India men) discharged from a ship,
and left destitute, without friends in a deserted city,
and also with some of my dear friends who were ill with the fever,
as I was in my chamber, exercised before the Lord on account of the sick,
some of whom were near their end, and actually dying at that very time,
about eleven at night, just as I had laid down,
my spirit being gathered in the Lord`'s presence,
I felt myself seized with the same kind of pains I had upon me when in New Jersey,
and the language was heard:
'`This is what I told you you must prepare for.`' My soul
was as it were swallowed up in the love of God,
and perfectly contented in the will of the Lord,
though I did not see the end of this dispensation.
After remaining about an hour in that state, feeling my strength fast declining,
and being alone in the house, I went downstairs to unlock the front door.
Had I deferred this a little longer,
it is probable that I should not have had sufficient strength to do it,
for it was with difficulty that I went up stairs again.
My friend, E. G., not seeing me the next day at the usual time, came to the house.
He soon brought me a physician and a nurse.
The former paid me but a few visits; for he took the fever, and died five days after.
The disorder so increased upon me that, my extremities having become cold,
my coffin was ordered,
and I was even returned among the daily deaths to the board of health,
as a '`French Quaker.`' But my dear Master had some further work for me to do,
before I could be prepared to enter into his Divine rest.

"`During the whole of that sickness I continued entirely sensible,
and while death seemed to be approaching, and I had turned myself on one side,
the more easily, as I thought, to breathe my last,
my spirit feeling already as encircled by the angelic host in the Heavenly Presence,
a secret but powerful language was proclaimed on this wise: '`You shall not die,
but live--your work is not yet done.`' Then the corners of the earth,
over seas and lands, were opened to me,
where I should have to labour in the service of the Gospel of Christ.
O what amazement I was filled with!
What a solemn and awful prospect was set before me!
Sorrow took hold of me at the words;
for it seemed as if I had had already a foot-hold in the Heavenly places.
I wept sore; but, as it was the Divine will, I bowed in reverence before Him,
interceding that, after I had, by His assistance,
been enabled to do the work He had for me to do,
and the end of my days in this probationary state had fully come,
I might be permitted to be placed in the same state in which I then was,
pass through the valley and shadow of death strengthened by His Divine presence,
and enter finally into those glorious mansions,
at the threshold of which my spirit had then come.
I saw and felt that which cannot be written.
Suffice it to say, that from that very time the disorder subsided.
My strength, by degrees, returned, and, in a very few days,
I was able to be removed to my kind friends`', E. and M. G.,
where I felt quite easy to go.
Their brother was then ill in the house, and died a few days after;
I was able to minister to him to the last.
Soon after this, five of that family were taken sick, and, for a while,
some of them were so ill, that going from one to the other,
I hardly knew which of them would die first.
My health was yet very slender,
yet I think I was about a week without undressing to go to bed.
For part of this time there were only two of us to care for them;
no nurses could be obtained.
The precious seasons, however, which I had by the sick beds of my friends,
sitting under the canopy of the Lord`'s presence,
often changed these scenes of mourning into joy.
They all recovered, and, the sickness in the city continuing,
I resumed my visits to the sick, and the poor.

"`One circumstance I may not omit to notice,
as a confirmation of what the Lord had showed me,
respecting the exercises I must prepare for during the residue of my pilgrimage.
In o religious opportunity, soon after my recovery,
at the first Second-day Morning Meeting I was able to attend, A. Howell,
in the course of his testimony, mentioned me by name,
and said that the Lord had raised me up,
having a service for me to the isles and nations afar off, to the east and west,
the north and south.
I had been careful to keep to myself the view I had had of these things,
on what seemed to me a deathbed.
I knew therefore that this was a confirmation of the word of the Lord to me, which,
like Mary of old, I hid in my heart.`"

The end of the Ninth month was now approaching;
the fever continued to prevail in the city, and the mortality was rather on the increase,
when the usual time for holding the Yearly Meeting of Philadelphia drew near.
Only few families of Friends, who were able to entertain company, remained in the city,
and it was no matter of surprise that considerable anxiety
should prevail as to the attendance of the Meeting.
On the appointed day, the 22nd of the month, however,
more Friends than could have been expected, under such circumstances, arrived,
"`with their lives offered as a sacrifice, should the Lord be pleased so to permit.`"
Though the number assembled was comparatively small, they were "`owned of the Lord,
and much blessed together in their meetings.`"
Stephen Grellet makes the following remarks in his journal at that time:

First-day, 23rd. We had very small meetings.
Instead of the crowd we have usually, at these seasons of our annual solemnities,
we are now, as after the shaking of the olive tree,
or the gleaning grapes after the vintage.
Yet the Lord owned us in a remarkable manner, by the overshadowing of his Divine presence.
O my soul, never forget the great mercy and lovingkindness of the Lord!
In such a time of distress and need, we see how vain is the help of man.
Living testimonies to the Lord`'s power were borne, and,
under the clothing of the spirit of supplication,
prayers were offered for the people in their distress,
that it might be sanctified to them.

Second-day, 24th. The Lord`'s hand is still stretched over us.
Some others of our friends are taken sick.
My brother, Joseph Grellet, in New York, is also ill with the same contagious disease,
which prevails in that city also.
At the opening of our Yearly Meeting, this morning, a solemn silence,
and holy covering were over us; our minds were refreshed in the Divine presence.
Several Friends expressed their comfort in being permitted to partake of such a favour,
and their reverent submission to the Divine will,
should the Lord be pleased to permit their lives to fall
a sacrifice to this their attempt to attend our Yearly Meeting.
After entering into a consideration of the propriety of
proceeding with the important concerns of the Society,
Friends concluded it would be better to adjourn that meeting to the Twelfth month, next.
The meeting accordingly adjourned.

"`About two weeks after this,`" continues Stephen Grellet, in his Autobiography,
"`further sources of mourning and deep prostration of soul before the Lord, were opened.
For, besides the continued distress in the city,
among my friends and the people at large,
we received information of the death of many of our friends from the country,
among whom were about twenty Ministers and Elders,
who had attended the opening of the Yearly Meeting.
I was very nearly united to several of them in Gospel fellowship--some
had been as nursing fathers and mothers to me.
O these were days for our walking softly before the Lord,
when with trembling we waited for further tidings,
having heard that several others in the country were ill.
Among these was Warner Mifflin,
that great friend and advocate of the cause of the poor slaves; and, shortly after,
we heard of his decease and that of several others.
My own life having been spared, even as one raised from the dead,
quickened in me earnest desires that I might so walk before the Lord,
as to answer the end of his dispensations--that my life, and my all,
might be devoted to his service.

"`At the adjournment of the Yearly Meeting, in the Twelfth month,
official information was received of the decease of so many of our dear and valued friends,
that it brought the meeting under much solemnity and awfulness before the Lord.
Friends then concluded henceforth to hold their Yearly Meetings in the Fourth month,
instead of the Ninth month of the year.`"

Towards the close of 1798, the propriety of changing his place of residence,
and joining his brother Joseph at New York,
was brought under Stephen Grellet`'s serious consideration.

A residence of more than three years in the city of Philadelphia,
in the midst of a large circle of valuable Friends, had been much blessed to him.
It had greatly tended to develop and confirm his Christian character,
and opened out for him a sphere of usefulness,
both as a member of civil and religious society,
and as a Friend and a Minister of the Gospel--in which he had enjoyed much of
the comfort and strength of "`Christian brotherhood and Gospel fellowship,
with fathers and mothers, brothers and sisters,
to whom he felt united in a relation nearer than any ties of consanguinity.`"
The Meeting to which he belonged was a highly favoured one, and at that time,
in a very flourishing condition.
It had among its members sixteen acknowledged Ministers,
and fourteen young persons who "`had a testimony for the truth,`"
though not yet recorded as approved Ministers of the Gospel.
He felt deeply sensible of the advantages he had enjoyed in the bosom of such a church,
and, when the prospect of joining his brother at New York was brought before him,
it is no wonder that he should have looked upon it with very mingled feelings.
He thus first notices it in his journal:

First month 24th, 1799.
My spirit, for several months, and lately especially,
has looked earnestly for the pointing of Truth, as it regards my removal from this place,
where my soul has been so often replenished with the Lord`'s heavenly bread,
and where I have almost daily opportunities to improve in the assemblies of his people,
to join my beloved brother Joseph at New York.
The prospect feels trying; yet, if I know my own soul, I have no will in it,
only desiring to be in my right place.

After much serious and prayerful consideration, and consulting with many friends,
whose judgment, in so important a movement, he highly valued,
the proposed change of residence was concluded upon.
The subsequent memoranda, in his journal,
evince that he had reason to believe that the step was a right one.
In one of these he remarks:

Second month 6th. This morning, in my retired, silent sitting,
I have felt the love and sweet presence of my dear Master
in a more especial manner than I have done for some time.
I have been fully satisfied of the rectitude of my
proceedings in preparing for my moving to New York.
I have had to remember how the Lord has been with me in this place;
how he has wonderfully blessed me, even with an increase of his heavenly riches,
settling me more and more upon Christ, the sure Rock of ages,
building me up in the most holy faith, sustaining me both as to temporals and spirituals,
working wonderfully, on many occasions, for my deliverance.
The acknowledgment has in some measure appeared applicable
to my state:--'`with my staff I passed over this Jordan,
and now I am become two bands.`' O my soul, never return to folly and vanity, but,
knowing experimentally that the Lord is good,
magnify and praise continually his Holy Name!

Before his removal to New York, he was liberated by his Monthly Meeting,
to pay a religious visit to Friends of several of the Monthly
Meetings in West Jersey--"`a debt of Christian love,
which he did not feel easy to leave undischarged.`"
On his return, he made the following record in his journal:

Fourth month 9th. I returned last evening from my little journey,
during which I was enlarged in my gift,
and many times felt the Lord to be a God near at hand, a ready helper.
My heart is full of gratitude, because he, when he puts his servants forth,
goes before them.
I have the reward of sweet peace for my small endeavours to labour in his cause,
in this little service,
which causes me anew to acknowledge that I do not serve a hard master,
but a rich rewarder of all those who love and serve him.

The Yearly Meeting of Philadelphia, held in the Fourth month, 1799,
occurred soon after this, and he remarks respecting it: "`Under a precious calm,
and holy solemnity,
the hearts of many were united in the true love and fellowship which is with the Father,
and with his Son Jesus Christ.`"

It was his parting opportunity with many beloved friends,
before changing his residence from Philadelphia to New York.
