== Chapter IX.

* His Marriage
* Death of His Father
* Religious Visit to the States of New York and Vermont, and Parts of Canada

The commencement of the year 1804 was marked by the interesting
event of Stephen Grellet`'s marriage to Rebecca Collins,
daughter of Isaac and Rachel Collins, of New York.
They had been acquainted for a considerable time,
and "`care having been taken fully to feel after
the Lord`'s approbation in this important step,
they were united in the marriage covenant on the 11th of First month, 1804.`"
It might be truly said that their union was "`in the Lord;`" and,
through a long course of years, in an eminent degree, attended by His blessing.

Not long after this change in his social position,
Stephen Grellet received the affecting intelligence of his beloved father`'s decease,
after a short illness, towards the close of 1803.
A two years`' imprisonment,
and all the anxieties and sufferings connected with the revolutionary struggles in France,
had impaired his health.
He had concluded to retire into Holland,
and had made preparations for leaving the city of Limoges, and France, when,
as Stephen Grellet remarks,
"`the Lord was pleased to order that his removal should be far more distant,
even to that world of spirits, where sorrows forever end.
The afflictions he endured, were, through adorable mercy, sanctified to him.
The last years of his life, his nature was changed;
mildness and kindness were his characteristics.
Even while in prison, under the iron rule of Robespierre,
he would encourage his fellow prisoners, to patient submission to the Lord`'s will.
He was a man of great integrity, much beloved by his family and friends.`"
After his decease, his widow relinquished the idea of leaving her native land,
and continued, with some other branches of the family, to reside at Limoges.

Fully capable of appreciating and enjoying the comforts and blessings
which had so recently been conferred upon him,
through the happy matrimonial connection which he had formed,
Stephen Grellet did not allow the endearments of home to interfere
with his devotedness to the service of his God and Saviour,
and in the Seventh month of the same year,
he entered upon an extensive religious engagement,
of which the following account is preserved.

[.embedded-content-document]
--

Having for a considerable time past felt drawings of Gospel
love towards the meetings in New York and Vermont States,
and parts of Canada, I made the necessary preparations for that journey,
arranged my outward concerns, and,
my Monthly Meeting giving me their testimonial of unity,
I left home the 7th of the Seventh month, 1804, committing myself, my beloved wife,
and my all, to the Lord`'s protection.
I began my services by going through the meetings
in Purchase and Nine Partners Quarterly Meetings,
and, having gone as far north as Hudson,
I crossed over into Duanesburgh Quarterly Meeting.
At Coeyman`'s I met with our valued friend Ann Alexander, from England,
on a religious visit to this land; we continued a few weeks in company,
to my great comfort, her ministry being truly weighty and instructive.
We had several silent meetings, to the disappointment of the people;
for very few understand the nature of silent worship.
This is probably one of the reasons why, with many, the word preached profits so little.
Through those parts, and in Saratoga Quarter, I had some large and solemn meetings;
among others, at Albany, Johnston, Saratoga Springs, etc.
I then went into Easton Quarter.
The Lord sustained me amidst daily baptisms; for the state of religion in those parts,
is very low; worldly-mindedness, ignorance, and self-righteousness,
are powerful enemies to it.

After attending Easton Quarterly Meeting, where my beloved wife met me,
I went into Vermont.
There I found a precious, living seed.
I visited in that State both Friends and others,
which services I closed on the 26th of Eighth month with two meetings,
one at Ferrisburgh, the other at Vergennes, in the Courthouse.
They were both favoured seasons;
for the love and healing power of our holy Redeemer were near,
to heal all that need healing, and are willing to come to Him.

Crossing Lake Champlain, my companion and I went to Peru,
where we had another season of Divine favour;
the Gospel dropped like a gentle rain on the tender grass,
and the young people were affectionately invited
to range themselves under the banner of Christ.
We went afterwards on Grand Isle, and had a meeting among the people.
A great alarm prevailed during the night; the drought had been great,
and of long duration; through some cause or other,
a fire began to spread in their tall cedar swamp; a high wind arose,
and the fire extended in every direction on the island, proceeding towards their fences,
houses, and barns, threatening general destruction.
It was truly an awful sight;
columns of fire ascended from the lofty cedars with a crackling noise.
But, through the exertions of the inhabitants, who turned out very generally to work,
and a blessing on their labour, we were relieved from the threatening danger.

We returned on the main land, and, through difficult and dangerous roads,
came to Chazy River, where I had a meeting, and then to Acadie,
the first village in Lower Canada.
On that journey we had again a narrow escape from fire,
which spread rapidly in the woods, through which we were travelling,
so that the tops of the trees over us were in flames,
burning branches often falling down near us;
and we had no other means of escape than to ride as fast as our horses could go,
before the underwood caught fire.

Feeling much for the poor Canadians, who, notwithstanding their great ignorance,
manifested religious tenderness,
I believed it my place to endeavour to have a meeting among them.
They are Roman Catholics, and the priest, hearing of my intention, strongly opposed it;
yet most of the people, instead of going to Mass, it being First-day,
came to the meeting we had appointed, and manifested much brokenness.
I thought it might truly be said, "`to the poor the Gospel is preached.`"
This was the first meeting wherein I preached in my native language.
Several of them came after meeting to confer with me, under evident religious concern.
I admired how some of their minds had been illuminated by the teachings of the Spirit,
so as to see beyond the popish creed,
and the hope of redemption through their meritorious
works or the absolution of the priests.
They were directed to Christ Jesus, the only Saviour,
without whom none comes unto the Father.

We went afterwards to La Prairie, a large village, where I felt much for the inhabitants;
but for a long time I could see no way to obtain a meeting among them.
The attempt I had made towards it, had excited in some of them angry passions,
and one of them had gone so far as to offer personal abuse,
which my blessed Master enabled me to bear in meekness.
Under many discouragements I had gone back to the inn, and retiring to my chamber,
I was pouring forth my soul unto the Lord,
who could relieve me from the concern I felt for the people,
or open a way for me among them.
While thus engaged, three persons came to see me.
They had noticed me in the street,
and wished to know if I desired to have a religious meeting in the place,
stating that one of them, being a school-master, had his school house at my service,
the others offering to give notice.
I concluded to have a meeting appointed in the school house,
at nine o`'clock the next morning.
But when public information of it was given, the priests, and some others,
went from house to house, among the Canadians, forbidding them to attend the meeting,
under penalty of being excommunicated.
They threatened, in like manner, the proprietor of the school house,
so that the persons who had been with me in the evening came in the morning,
to give me the reason why the meeting could not be held;
when an English person sent me word that her house was open to me for a meeting,
and that she would have preparation made in time.
I went accordingly.

The curiosity of the Canadians was excited, and as I passed through the streets,
they came to their doors and windows to look at me, as a strange being.
I found in the house, the rooms of which were pretty spacious, only about thirty persons,
mostly English.
While we were sitting in silence,
many Canadian boys and others gathered in the street near the door, and were noisy.
After a while, being introduced into feeling for the few present,
attended with Divine love, I stood up to impart what was on my mind towards them.
As I began to speak, the people out of doors came in, some in a turbulent manner;
but my heart turned in Gospel love towards them, and I soon ceased speaking in English,
and addressed them in French.
As soon as I did so, silence prevailed,
and a considerable number of Canadians continued to come into the house,
in an orderly manner,
to whom the blessed Redeemer enabled me to preach the Gospel of his salvation.
I directed them to Christ and to his Spirit in them.
The same who convinces men of sin, is able to deliver from sin;
their priests could not do it; no man can save his brother;
but Christ has come into the world to save sinners, even as many as, believing on him,
submit to his teaching and obey his Gospel.
The Lord opened the hearts of many of them so as to bring them into tenderness;
several of them gave vent to their inward convictions by expression,
// lint-disable invalid-characters
and now and then cried out in French, "`__c`'est la vérité__`"--this is the truth.
They were very loving after meeting,
and pressed me to come again and have meetings among them.
They now feared not what their priests might say or do.

Crossing the St. Lawrence we came to Montreal.
I visited there several pious persons,
and in one of their nunneries I had much openness with some of the nuns,
especially their superior.
I had also a meeting in that city.
We travelled afterwards up the river, towards the Cedars,
frequently under great discouragement,
because of the great ignorance and insensibility I found among the people.
Yet my spirit was comforted with some of them, particularly at the Cedars,
where I had a full and relieving time with two of their priests and some of their people.
The priests publicly acknowledged to the Gospel truths I had declared among them.
In other places I also found a door opened,
to draw the attention of the people from the various
inventions and superstitions of man`'s device,
to the blessed Redeemer and his truth,
revealed for the salvation of all those that believe.

We proceeded up the river about one hundred and fifty miles, through very bad roads,
or rather Indian paths.
Several times we were under the necessity of taking canoes to get over creeks,
and of having guides to swim our horses through,
so as to avoid the deep mud or quicksands.
The accommodations were very poor, and still more filthy.
In one or two places the people appeared bent upon doing us some mischief;
but we were favoured, without personal injury,
to reach the house of a person of the name of Snyder, in Greenville County.
Here our horses appeared to be failing, apparently through fatigue,
though they were both strong, valuable animals.
Mine was an uncommonly good horse.
I had paid a high price for him,
because I thought such a one was requisite for the journey.

Having heard that a few miles from the other side of the river there were several
families who had once belonged to our Society and some who did so still,
I felt inclined to go over to see them.
Leaving our horses to rest at William Snyder`'s,
and having appointed a meeting to be held at his house the ensuing afternoon,
we took a canoe and paddled ourselves over the St. Lawrence.
On our way across the river, we passed by several small islands; they were not inhabited,
and on landing on some of them,
the total silence which prevailed introduced the mind into solemn contemplation.
We had scarcely reached the United States`' shores and secured our canoe, when the sky,
that had been gathering blackness, turned into a blaze,
accompanied with loud peals of thunder; the wind blew vehemently,
so that the tall trees of the forest were like stubble,
prostrated before it in heaps about us.
I considered it a favour to have got to a place cleared from the timber,
so that we were out of the reach of the falling trees.
Nature appeared to be in a state of convulsion; awful was the sight; my soul could say,
"`great and wonderful are your works, Lord God Almighty.`"

A calm succeeded the storm,
and we ventured through the fallen timber to the habitations we aimed at.
We found there was in that part great openness to receive us,
and the following day being First-day, we had a meeting among the people;
several of them, though still members of our Society,
had not been at a Friend`'s meeting for years; the hearts of some were made tender,
for the Lord`'s power attended.

Having some miles to walk, we made all the haste we could to our canoe;
we saw a great collection of people on the other side of the river,
waiting for our return, and we landed in Canada in due time for the meeting;
but how damped were my feelings, when, on setting my feet on shore,
the first sight was my horse stretched on the grass--dead;
and that of my companion apparently in a dying state,
both bearing evident marks of having been poisoned,
which we could only attribute to those mischievous
people among whom we had been a few days previous.
There was not time however to dwell on the consequences
of being thus left destitute of a horse in a new country,
where others cannot easily be procured.
The people were collected.
I went into the house,
and my mind was soon gathered under the influence
of that power that stills the winds and the seas,
yea, brings every thought into captivity to the obedience of Christ.
Our holy Redeemer, the crown of the assemblies of his people,
condescended to reveal himself as being near to us.
It was a precious meeting, blessed be the Lord for the favour!
Many present could unite with my own soul in ascribing, on bended knees, praises, honour,
glory and blessing unto Him that lives forever and ever, and who,
through the sprinkling of His own blood--the blood of the everlasting
covenant--has consecrated the way for us to obtain redemption,
through faith in His name.

After meeting, the people becoming acquainted with the loss of my horse,
some of them kindly undertook to see if another could be found.
Next morning early one was brought, very inferior indeed to the one I had lost,
but the best they could obtain; I had to pay a high price for him, though not more,
I apprehended, than the scarcity of those animals among them warranted,
and I felt much obliged to the owner for his willingness to sell him to me.
My companion having some hopes that his horse might recover,
it was concluded he should remain behind,
and that I should proceed alone on my religious engagement in that province.

It was trying to be left alone in travelling through that new country.
I had heard of some settlements formed by persons that had been,
or were members of our Society, and I felt desirous of visiting them;
but there was no way to get there, except through unbeaten tracks or Indian paths,
thick woods, deep muddy soil, and several creeks.
The parting with my companion and the kind family of Snyder`'s was solemn.
I felt my engagement arduous, and as I proceeded thus alone on my journey,
my soul`'s aspiration often was, "`O Lord be near your poor servant to direct him aright,
and preserve him through these trackless woods.`"

It took me near two days to travel about thirty-two miles to Matthew Howard`'s,
a descendant of Friends, now a member of Parliament.
I met with many difficulties through the woods, deep mud,
and the fall of the timber across the Indian paths,
which obliged me to turn aside frequently, whereby I missed my way.
The sun being obscured,
I directed my course by the moss on the trees till I again found the right path.
Being often hemmed in by many trees that were blown down,
it was slow work to carry my saddle and saddle-bag,
to make my little horse jump over one tree after another, or,
when coming to the muddy streams, I had to urge him through them,
and then with my load on my back, to seek up and down the stream,
for a tree blown across the water, on which I could walk over to join my horse again.
My dear Master was pleased to bring me through all these difficulties,
meeting no other living creatures, that I noticed, but deer; these were numerous,
and twenty or thirty were often seen herding together.

M+++.+++ Howard received me with kindness,
and as I wished to have a meeting in that settlement,
he readily undertook to prepare for it.
It was held the following day at +++______+++ Smith`'s. His wife,
who was a member of our Society, had not been at a meeting for twenty years,
and had been bed-ridden for about six.
The Gospel flowed freely towards that people;
through various afflictions in that new country, their hearts were made soft,
and prepared to receive its consolations.
It was a sickly time among them; almost every family had some of their number to nurse.

After meeting, M. Howard kindly accompanied me to another settlement of the Wings,
fourteen miles further,
where I also found several who had a right of membership with Friends.
I had a meeting with them the next day, which the Lord owned by his Divine presence.
I thought it was right for me to encourage these few professors with us,
to meet together, for Divine worship, once a week at least,
believing that if they thus came together, in a humble and seeking state of mind,
before Him who can availingly minister to all our needs, temporal and spiritual,
they would find a blessing in it, both upon themselves and their children.
I feel very tenderly for these settlers in a wilderness,
destitute even of the common advantages experienced
by those residing in more inhabited parts;
only few of these can read, and among those that can,
few have a copy of the Scriptures with them.
May those among us who are surrounded with blessings of various kinds,
who have frequent opportunities, in religious meetings,
to seek for the renewal of their strength, and free access, in their houses,
to the perusal of the Divinely inspired records, improve under these favours,
and consider that where much is given, much also is required!
I believe it was in the ordering of Truth that my steps were turned to those people,
among whom there is a seed that the Lord will bless and prosper.^
footnote:[When visiting Canada again, some time after,
Stephen Grellet found a large body of Friends settled in that neighbourhood,
constituting Leeds Meeting.]

Gershom Wing kindly concluded to accompany me through the
further wilderness that I had to travel on my way to Kingston.
Thus was my gracious Master pleased to provide for his poor servant, through difficult,
and almost trackless paths.
After meeting he took me to his son-in-law`'s, fifteen miles on our way,
where I had a meeting.

The next day we travelled thirty-six miles,
arriving late in the night at the widow Brewer`'s,
whose husband had been a valuable Minister of Christ, and was but lately deceased.
Our way had been rendered the more difficult by heavy rains, and the fall of the timber;
so that frequently it seemed as if we could proceed no further,
especially on account of the deep waters we had to ford; but my kind guide,
accustomed to the woods and their difficulties, always found some expedient or other,
so that we got safely through, though not without some bruises, which,
for some time after, rendered travelling difficult; but under all the Lord helped me.

The next day being First-day,
I had a pretty large meeting among the few Friends composing that meeting,
and their neighbours.
Some of these were at first very unsettled, even rude and noisy;
but the Lord`'s power chained down the unruly spirits among them,
Truth rose into dominion,
and refreshment from the Lord`'s presence flowed
towards the poor and afflicted of his people.
In the afternoon I had another meeting in the village of Kingston,
(now a large town,) in the Courthouse.
During the forepart of the meeting I felt very low;
but I secretly cried to the Lord to help me,
centring in faith and resignation before Him in whom is saving strength.
His power was felt, and the streams of his Gospel did flow.

I was at West Lake meeting, and at their Select and Monthly Meetings, at Adolphus Town.
Some of these meetings were attended with peculiar baptisms,
but oh the melting of hearts under the contriting power
of truth that was witnessed in some of those seasons!
It is the Lord`'s doing; well may we say, it is marvellous in our eyes.

I felt much for Friends settled in the upper parts of this province, near Lake Erie,
but I found it impracticable then to visit them.
There was no way to get there through the woody wilderness, on horseback,
and I was told it would be nearly impossible, even on foot;
I therefore concluded to return to Kingston, and,
my dear Master relieving me from further services in Canada,
I proceeded across Lake Ontario towards the Black River, in the United States.
The only way to get on Grand Isle, about four miles from Kingston,
was to lash two canoes together, and to place my horse`'s fore legs into one canoe,
and the hind legs in the other.
The wind blowing fresh, the passage was attended with considerable danger.
When I reached the other side of the island,
there was another ferry of several miles to get over to the United States.
I found the boat had gone to the other side, and was unable to return,
on account of the strength of the wind.
I was therefore detained till noon the day after, when, the wind abating,
the ferry-man was able to return, to the great relief of his family as well as myself.
For, their provisions being spent, he had gone over to purchase a fresh supply.
It was a time of peculiar distress in the island; the drought had parched the ground,
and the squirrels, which were very numerous that year, had eaten up their corn.
Thus my horse fared but poorly, and as to myself,
I shared with the family in their scanty meals of some squirrels
which the boys succeeded in killing with their bows and arrows,
and for which I remunerated them as cheerfully as, in some other situations,
I might have done for the best fare.
In the afternoon I had a fine time in going across the lake.
On landing, I made all the haste I could towards Brownsville, but the road was so bad,
that I was obliged to walk and lead my horse great part of the way,
being sometimes deep in the mud.
I attempted to find some dry spot to pass the night, which became very dark,
but met with none.
I was, however, favoured to get safe to Brownsville late in the night,
grateful for the help received, and the shelter and food I now had,
after the long fasting.

I continued a few days in the neighbourhood of Brownsville, and had some meetings there.
Then I again took my solitary journey, a long dreary way to the Little Falls,
on the Mohawk river, and after a few meetings through Saratoga,
Easton and Nine Partners`' Quarters,
I returned to New York the latter part of the 11th Month.

My spirit was humbled before the Lord, my blessed Helper, for his many preservations,
and sustaining mercies, vouchsafed during that journey.
He had often made a way for me to get forwards,
when there appeared to be none,--blessed be his name, and magnified be his power,
forever!

--
