== Chapter XI.

[.chapter-subtitle--blurb]
First Visit to Europe

[.chapter-synopsis]
* Voyage
* Arrival at Marseilles
* Quarantine
* Visit to Congenies, etc.

Amidst a variety of minor religious services at and about home,
and the needful attention to his domestic and social duties,
nearly eighteen months had passed away before Stephen Grellet
felt the "`necessity laid upon him`" to take active measures
for accomplishing the long contemplated visit to his Fatherland;
but, in the spring of 1807,
"`believing that the time was fully come to resign himself to the
Lord`'s requiring,`" he once more "`settled all his temporal affairs`"
to set himself at liberty for the work to which he was called.
His friends of the Monthly, Quarterly, and Yearly Meetings,
"`entered into near sympathy with him in his religious prospect, and,
having furnished him with certificates expressive of their full unity with him,
in the proposed service,`" he again left his all,
and went forth as an ambassador for Christ, to the land of his nativity.
His beloved wife, still in a very delicate state of health, was left behind.
"`Though parting with her,`" he says,
"`as not likely to see each other again in this world, she was my faithful helper,
in encouraging me to devote my all to the service of the dear Redeemer.`"

From the journal which he kept, during this religious engagement,
the following extracts are taken:

[.embedded-content-document]
--

First-day, 14th of Sixth month, 1807.
At sea.
I have embarked this day on board the ship Brunswick, Captain Beadle,
bound for Marseilles.
This route I take, my mind being drawn to visit first the southern parts of France,
and the little body of persons professing our principles in those parts.
I came on board the ship at noon, directly from meeting, which,
through the adorable mercy and continued kindness of my dear Redeemer,
was a season of Divine favour.
I was on my feet, engaged in proclaiming the Gospel to a large number of Friends,
when messengers came at two different times to summon me on ship-board.

It was a solemn parting between my beloved wife and myself;
but the Lord gave strength in humble submission, to be resigned to his will,
and to follow him wherever he may be pleased to send me.
Lord, for your sake and your Truth,
my dear companion and your servant have offered one another to you;
keep her by your power, comfort her by your presence;
fulfill the promise you hast made to your servant,
"`My presence shall go with you and I will give you rest.`"
I feel, in my measure, like Abraham, called of God to go where he will show me,
to preach his Gospel, to suffer, or to do whatever he shall assign to me.
How consoling is the gracious promise that the Lord will
be with me in my going out and in my coming in also.
None can have ever gone on the Lord`'s service under a greater sense of their poverty,
weakness, and inability of themselves to do anything to the glory of God.

Several of my friends and near relatives came with me on board, so far as Sandy Hook,
and have left me at ten o`'clock this evening, to return with the pilot.
Now I am left a poor solitary one, none on board but the crew of the ship,
and some of them, being in a state of intoxication, appear very unfit for duty.
O you, Lord, the faithful and never-failing friend, be with me, lead me by your Spirit!

Soon after I penned the above the wind blew hard and increased to a storm,
which caused a very rough sea.
I was so affected with sea-sickness that I could not raise my head,
and by the heavy rolling and tossing of the ship,
almost every article in the cabin was loosed from, or broke, its fastenings,
and I was thrown out of my berth, and tossed from one side of the cabin to the other,
when another heavy sea, striking the ship, brought in a stream of the watery brine.
Every one was too much engaged to pay me any attention, at the time.
After a while things were put in some order,
and the cabin was drained by letting the water run down into the hold of the ship.
The cabin was now kept closely shut up, to prevent a recurrence of the same thing,
so that, in addition to sea-sickness,
my sufferings were greatly increased by the foulness of the air.
Our vessel had just returned from the West Indies, loaded with sugar and molasses,
and now most of her lading was in sugar,
the leaking of which gives to the bilge water an intolerable stench.
The air was so foul that every piece of silver about me turned black.
The day after I came on board, it seemed as if I should be suffocated;
the captain observing this, kindly carried me up to the quarter deck,
fastened with ropes a chair to the sides of it, in which he secured me,
that I might not be washed away by the waves that frequently came over the ship,
and carried away a good deal of our deck`'s lumber, and several of the hencoops.
But this situation, however awful and exposing, was far preferable to the cabin;
though my clothes were wet, day after day, by the sea, I did not get cold.

The works of the Lord, as I beheld them, are great.
The waves were like mountains, taking us up on high;
then they would suddenly break asunder, and let the ship fall as into a deep abyss,
with a great crash, as if she would break in pieces under the shock;
then she trembled like a leaf.
We were under the greater apprehensions as she is deeply laden,
which makes her labour hard;
truly applicable to our situation is the description given by the Psalmist (Ps. 107.,
23--29). At a time when my mind was absorbed in the deep contemplation
both of the nature of the religious services I had before me,
and the perils by which I was surrounded,
my attention was directed to those lofty waves and deep abysses,
and the heavy shocks the ship endured, amidst which she was preserved;
and I felt a living hope springing in me,
that the Lord God Omnipotent would also uphold me,
under the various afflictions and trials that would befall me,
if I only maintained a constant trust and confidence in him.
You hast shown your servant, O Lord, that your power is over all,
that he that trusts in you is like mount Zion that cannot be moved;
you hast condescended to revive to my drooping spirit,
when under complicated fears and dreads, from within and from without,
the soothing language, "`Fear not, you worm Jacob, for I am with you, be not dismayed,
for I am your God; when you pass through the waters I will be with you,`" etc.

26th. Yesterday and last night the storm was again raging,
but my mind was kept in calmness.
I have seen how those ancient worthies and faithful contenders for the faith of Jesus,
could rejoice in great tribulation.
Amidst the tossing and confusion occasioned by the storm last night,
my mind was introduced into a state of quiet, when my covenant was renewed with my God.
How sweet it is thus to covenant with the Lord!
Then, with cheerfulness, our all is resigned into his hands.

First-day, 28th. I have felt much for the crew of the vessel,
but way has not yet opened for our coming together to unite in the act of Divine worship.
I had hoped yesterday that we might have this privilege today; but a fresh storm prevails.
It has been a day, however, spent in much prostration of soul, under which,
through adorable compassion, my strength has been a little renewed.

Seventh-day, 4th of Seventh month.
For several days past we have been favoured with fine weather and fair wind.
This morning we passed in sight of Corvo, one of the Western Islands;
its shores are high; it appeared covered with beautiful vineyards.
The island is small, only about ten miles in length.
Tortoises (turtles) are numerous and large here, sleeping on the surface of the water;
our sailors lowered the boat, went softly to them, and brought several on deck.
They are a great treat on ship-board.

First-day, 5th. This forenoon I have had a meeting for Divine worship with my ship-mates,
the captain kindly making suitable arrangements for it, and, as the weather was fine,
none were left on deck but the man at the helm.
It has been a solemn and instructive season to us,
wherein the Lord enabled me to offer prayers and intercessions for our little company,
and for the preservation of our near relatives and friends, whom we have left behind.

13th. High winds and rough sea, which have made me very sick again; we saw,
at a distance, a fleet of about thirty sail of ships of war, but, it being squally,
none boarded us.
We are now near Cape St. Vincent; the sight of land is beautiful;
but oh what a weight of exercise do I feel at the prospect of the
sufferings I may have to endure in these European nations,
in the service of the Gospel of Christ.
Yesterday, especially, I felt this heavily.
I see no end of my services in these nations.

14th. We have passed today before Cadiz,
so near that we could look into the streets of the city.
We went through a British fleet which blockades that port.
One of the frigates boarded us.
The lieutenant treated us politely.
He says they have been several months on that station,
and they do not know how much longer they may continue.
To see so many engines of destruction brought many considerations before my mind.
Sad indeed are the consequences of the fall of man; "`Glory to God in the highest,
and on earth peace, good will toward men,`" is not naturally his soul`'s anthem.
With what perseverance and apparent cheerfulness do men endure
hardships and many difficulties in the service of an earthly prince,
shedding their own blood,
and that of thousands who have never done them any personal injury,
and that to obtain earthly glory.
Be stimulated, oh my soul, in the service of the King Eternal, waging war against sin,
and bringing to your fellow-men the glad tidings
of salvation through faith in the Redeemer`'s love.

15th. This morning we were boarded by four Spanish gun-boats;
several ill-looking men came upon our ship.
They appeared bent on plunder.
Observing my plain dress, they did not know what to make of me.
One of them at last called me "`Padre.`"
That is the way among the Roman Catholics of calling their priests--Father.
The examination of my passport, they thought, confirmed them the more,
that I was one of that class, when, treating us with more respect, they left us.
At noon we passed through the Straits of Gibraltar.
It is a grand sight.
Gibraltar on the left, and Ceuta, on the Moorish shore, to the right.
I feel much for the inhabitants of those countries, as I pass them.
Oh when will the light of Christ`'s gospel so shine upon them as to induce
them to turn away from their various superstitions and idolatries?

21st. Since we have come into the Mediterranean, we have had many calms;
the weather is oppressively warm.

24th. This afternoon we saw a ship coming towards us.
I apprehended she was a suspicious vessel; she had another in tow,
and as she came alongside of us, we saw her full of rough-looking men,
with swords or cutlasses in their hands, and other weapons.
The captain thought they were Algerines.
They ordered us on board their ship, and our seamen were in the act of lowering our boat,
to obey their summons, when, discovering an English frigate in chase of them,
they immediately made all possible sail to escape with their prize,
which was probably some merchant ship, they had lately captured,
the crew of which they reserved for slavery; this, very probably,
would have been also our portion,
had the frigate been a few moments later in making her appearance.
When our poor seamen saw the danger we were in,
some of them made doleful lamentations at their prospect of slavery.
My own mind was preserved calm; for I remembered what occurred to me some months ago,
in New York, while in a religious meeting, my mind solemnly gathered before the Lord;
I then felt that there was a possibility of my being taken,
during the passage on that sea, by some of the Algerines, or Morocco powers,
and carried into slavery by them.
My spirit bowed reverently before the Lord, in confidence that he might,
if it was his good pleasure, deliver me from the hands of merciless men,
and every other evil; but, if he had a service for me among those people,
I bowed in humble resignation to whatever he might suffer to come upon me,
praying that it might only turn to his glory and the salvation of my soul.
Thus, while these men were by the side of us,
I was waiting to see what the Lord had for me now to do for his great name.
I thought I could willingly proclaim to them the Gospel message of redeeming love,
or suffer among them for the sake of Him, who has suffered and died for us,
"`the just for the unjust, that He might bring us to God.`"
But after this day`'s fresh interposition of Divine power to deliver,
my soul has ascribed blessing, and praise unto Him.

First day, 26th. I had again a meeting with my shipmates.
The hearts of some of them appear to have been made soft,
by our great deliverance from the pirates.
There was an openness in them to join in worship
to Him who has thus condescended to favour us.
During the voyage I have had several private, as well as public,
religious opportunities with the crew of the ship.
Some good impressions appear to be made on some of them: may they be lasting,
so that they may escape the temptations attending them in port.

28th. We came yesterday in sight of Marseilles, and having taken in a pilot this morning,
at three p.m., he has brought us safe into port,
in that part where the shortest quarantine is required, which is fifteen days.
The place is confined, very little circulation of air, the water stagnant and filthy,
and vessels lie so close that one might easily jump from one to the other;
the smell of their bilge water, together with the heat of the weather, are very trying.
As soon as we arrived in port, a guard came on our ship,
to see that none on board go on shore, or on any of the other vessels,
nor touch any of the things pertaining to them,
which would lengthen the time of quarantine.
The pilot has also to remain on board, subject to the same laws of the quarantine.

29th. Hearing of the Lazaretto where I might go to perform my quarantine,
I have removed to it; it is a large establishment covering several acres,
in a very airy place, near the sea shore; it has spacious store-houses,
where all the cotton and other articles from the Levant are deposited,
to perform quarantine, which is very long,
especially when the plague prevails in those parts.
The buildings are divided into several blocks; spacious yards are attached to each,
so that persons performing quarantine of different lengths,
according to the parts they come from, are separated from one another.
In another part of this large establishment are the
places for such as come into port with the plague,
or contract disease after their arrival.
Great order is maintained throughout this vast institution.
It was erected about a century ago,
soon after the plague appeared that caused such ravages in Marseilles.
I have a guard now given me, who accompanies me wherever I go; he also acts as a waiter,
brings me my meals, etc.
I am settled in a double room, one for me, the other for my guard.
There is no other furniture than a table, two wooden chairs, and an iron bedstead,
on which I have placed my sea-bed.
I feel, however, as in a palace compared to the ship.
My chamber is very airy.
As there are at present very few persons in the establishment,
I can walk with my guard through nearly every part of it.
I understand that sometimes several hundred persons are in it.
This afternoon John S. Mollet came to see me; he is a Swiss,
but now resides in Marseilles.
Through various deep trials he has purchased some
knowledge of the Truth as professed by our Society.
It is a comfort to see him,
and he will be a help to me in becoming acquainted with pious persons in these parts.

30th. Several opportunities have presented for serious
conversation with some of the officers here.
My guard and some of the porters have manifested some tenderness.

7th of Eighth month.
Curiosity to see a Quaker frequently brings persons of various
ranks and conditions to see and converse with me.
Several popish priests have also come.
I have daily to maintain my Christian testimonies, and to open the principles of Truth.
The captain of the Lazaretto appears desirous to obtain correct information,
and often visits me on that account.
Among those that have come to see me, are some Spaniards.
Oh what darkness they have manifested.
One of them evinced much bitterness, and said, "`burning would be too good for me.`"
I have had today a religious opportunity with two of the porters and my guard.
There was some openness in them to receive the truths of the Gospel,
and to be directed to Christ as the only Saviour of sinners, and the Redeemer of men.

13th. Two of the seamen on the ship Brunswick are taken sick with a fever,
and brought here, on which account my detention will be lengthened,
to see how it will be with them.
Oh for a continuation of patience!--my heavenly Father has much sweetened my situation,
by the incomes of his Divine love and presence.

17th. For days past,
my spirit has been greatly burdened because of the superstition and gross darkness,
manifest amidst a pompous profession.
My room is very near the chapel here, and during the three last days,
they have kept a feast for their saints, so called,
at which they display great parade and gaudiness.

21st. An American female, just arrived from Boston, has been brought here.
She is in the last stage of consumption.
Her object in coming to these climates, is to seek health,
but it appears probable that she will not survive many days.
The Lord has given me the cup of consolation to hand to her,
and to encourage her to look up to Christ, as the only refuge and physician of souls,
who is near to purify and sanctify her and prepare
her for admission into his kingdom of spotless purity.
On account of the seamen`'s sickness I am still detained in this place.
It is very tedious, but while labouring for patient resignation,
I desire to cultivate a due sense of gratitude towards my ever gracious Master,
who is frequently felt very near to uphold me.

25th. I came out of the Lazaretto last Seventh-day, the seamen having recovered; but,
before they liberated me,
all my baggage and clothing were shut up for some hours in the fumigating chamber.
I was also under the operation myself about a quarter of an hour;
I had a small aperture to breathe through, else I should have been suffocated.

John Malvesin, brother-in-law to J. S. Mollet,
had kindly invited me to make his house my home while in Marseilles.
Last First-day, J. S. Mollet and a few others sat together with me,
to worship Him who is a spirit, and will be worshipped in spirit and in truth;
the Lord pouring forth of his Spirit upon us,
enabled us to approach him and to offer up our prayers to him.
My mind is much shut up in this large city;
corruption and vice are evidently very prevalent, so that I feel encircled with darkness.
I have, however, been with some persons with whom I have been comforted.
Dear Mollet and A. E. Kothen, a Swede, have awakened minds.
The Protestant minister, a young man, has felt the power of Truth,
but he needs much humbling to embrace and submit
to the lowliness of a self-denying disciple of Jesus.

First-day,
30th. I have had a meeting at my kind friend J. Malvesin`'s. The Lord was with us:
Kothen was much affected,
under the power accompanying the Gospel I had to preach among them.

31st. I went a little out of town, in company with Mollet, to visit a pious family,
composed of old people.
They are Protestants.
We found them in a sweet frame of mind.
I have also attended the funeral of the female I left sick in the Lazaretto.

6th of Ninth month.
First-day.
I had a meeting on board the ship Brunswick,
the deck of which the captain had prepared for the occasion.
Many of the captains and seamen of the vessels in port, that are not under quarantine,
came to it.
It has been a season of Divine favour; Christ, the only hope of salvation,
was preached to them, and their various states were ministered to.
Some of them were very tender.
Among these I was pleased to find some of my ship-mates, our sailors,
who acknowledged the Lord`'s favours they had witnessed during our passage.
In the course of the week I have had several religious opportunities,
some private and others more public, among the people here,
and I am now looking towards Languedoc.

John S. Mollet proposes to accompany me there.
He has a nice family of orderly children.
I have encouraged him, with Kothen, and a few others,
who appear well disposed and whose minds have, in some degree,
been brought under the baptizing power of Truth,
to meet regularly together for Divine worship,
not doubting that it will tend to their mutual strength and encouragement,
and be also as a little standard lifted up in this place of darkness, unto the Truth.
Kothen became a serious character, a few years ago,
through a very remarkable deliverance from the hands of wicked men.
He was going from Stockholm to Abo, in Finland,
when he found that the boat in which he had taken his passage belonged to pirates.
While they were in the midst of the Gulf of Bothnia,
he heard them consult in the Finnish language,
(which they thought he did not understand,) on the
best expedient of taking possession of his property,
and some proposed to throw him overboard.
Hitherto he had lived without much concern about religion, as a man of the world,
out of the fear of God, and a stranger to Christ, the sure refuge in time of trouble.
Now, he remembered God, and as he told me, perhaps for the first time in his life,
he put up a prayer unto Him, believing He could deliver him from the threatening danger.
The pirates finally concluded to take him to a small
rocky island that served them for a retreat;
through some erroneous impressions they had received,
they now presented him to an old woman, their mother, as they called her, as a preacher.
She, in the midst of such a life, connected with men so dissolute,
yet retaining some of the religious impressions of earlier days, answered, "`Thank you,
my sons, tomorrow is the Sabbath, and we shall have a sermon,
which I have not heard for several years.`"
Poor Kothen felt much tried at the expectation thus raised respecting him.
Fears for his life, deterred him from undeceiving these people;
yet he felt himself utterly unable to answer their expectation.
He spent the night in great anxiety,
which was increased by several more pirates coming into the cave.
In the morning they made preparations for the meeting, put on their best clothes, etc.,
while poor Kothen could not command his thoughts,
nor was able to think of anything to communicate to the people.
When called upon to come in, and begin the worship, he went into the cave,
as if going to death.
Soon, however,
his mind was again drawn to feel the all-sufficiency of the blessed Redeemer;
he supplicated in His name, that the Lord would help him,
and his soul was contrited under a sense of His love towards him, a poor, sinful,
fallen man, as he felt himself to be.
He felt also the same love and offers of Divine mercy,
extended towards those poor people, under a sense of which, he was melted into tears;
he set before them their sinful condition, the depravity of the human heart,
and the awful consequences of living and dying in that state;
then he directed them to Christ the friend and Saviour of sinners.
As he went on thus speaking to them, he was the more affected,
as he felt the sinful state of his own heart,
and the hope that was now set before him also through
sincere repentance and faith in Christ,
the Lord.
Those poor people were most of them broken into tears; the old woman, after meeting,
took him in her arms with motherly affection,
and directed a boat to be ready to take him and all his baggage to Abo.
The sense of this merciful deliverance, and display of Redeeming love and power,
made such an impression on Kothen that, to this time, through Divine grace helping,
he endeavours to keep the covenant into which he then entered with God, his Saviour.

Congenies, 10th. I left Marseilles early yesterday for this place,
after having a refreshing opportunity, in the Lord`'s presence,
with some of those whose hearts he has visited by his Spirit, in that city.
There is in these parts a small body of people professing with Friends.
They appear to have existed long before they had
any knowledge of our religious Society in England,
and to have embraced some of the same Christian principles and testimonies.
I have seen ancient records in manuscript, by which it is shown that at various periods,
they suffered great persecutions under the Papal powers, some of them being tortured,
and put to death, amidst excruciating torments.
Among these sufferers were several very young persons,--delicate young women, who,
like the ancient martyrs, were enabled to endure, through faith in Christ Jesus,
whatever cruelty could devise, rather than yield to Popish superstitions and idolatries.
They suffered considerably also in common with the other Protestants;
I have seen copies of some very interesting letters,^
footnote:[These no doubt had reference to the "`Wars of the Camisards,`" which
produced the "`Troubles in the Cevennes,`" so graphically described by M. Court,
their historian.
After the revocation of the Edict of Nantes by Louis XIV., in 1685,
the most cruel and protracted persecutions commenced against the Protestants of France.
They raged with great violence in Languedoc.
About the beginning of the eighteenth century, a little band of Protestant peasants,
wearied out by the sufferings to which they and their
fellow-professors had long been subjected,
took up arms to rescue some of their brethren from the tortures they were enduring,
and the cruel death about to be inflicted upon them by the Romanists.
After having succeeded in this object,
they retired to the mountain fastnesses for safety,
from which they defended themselves against their papal persecutors.
Their number gradually increased to a little army of mountaineers;
and under the name of Camisards, (probably, according to Court, from Camisade,
the French for a sudden attack by night,) they carried on, for several years,
a bloody warfare against their oppressors.
Great excesses were committed on both sides, and the expostulatory letters,
of which Stephen Grellet here speaks,
were probably among the remonstrances addressed to the Protestant warriors,
by those of their own persuasion, who disapproved of their violent proceedings.]
which they wrote to these their fellow Protestants,
when some of the latter took up arms to repel by force,
the sword stretched out against them, at the instigation of the Church of Rome,
during the war in France against Protestantism.
They expostulated with them on account of the inconsistency
of their conduct with their Christian profession,
showing them how far they were from being gathered under the Standard of Christ,
the Prince of Peace,--while in their warlike proceedings they did unto others,
when they had an opportunity, the very things,
they complained that they did unto them,--they plundered, they destroyed;
whereas the servants of the Lord must not fight, but must be even like their Master,
render good for evil, love them that persecute them, and not avenge themselves.
Thus they maintained a faithful testimony against war;
they objected to oaths also and recognised silent worship,
and a ministry that proceeds from the influence of
the Divine Spirit and depends not on human acquirements.
They did not know of the existence of our Society in England and in America,
till the time of the American Revolution and the war which
in consequence arose between England and France.
A Friend of Falmouth, in England, had shares in several vessels.
The other owners, not being members of our Society, concluded to arm those vessels.
He remonstrated in vain against it.
These ships made several prizes upon the French.
His portion of the prizes was given him,
but as he could not conscientiously take an active part in the war,
so neither could he share in any emolument arising from it; on the restoration of peace,
therefore, he sent one of his sons to Paris, who by public advertisements in the papers,
etc.,
stated that the owners of certain vessels that had
been captured by the vessels in which he had a share,
should on their application to him,
receive their respective portions of the proceeds of the prizes;
at the same time giving his reasons why,
as a Christian and a member of the religious Society of Friends,
he could not share in gains arising from war.
This statement coming to the knowledge of the little body here,
they deputed a few of their number to go to London to confer with Friends there.
They rejoiced to find that the Lord had so large a body, both there, and in America,
maintaining the same religious testimonies as themselves.
After that period they were visited by some of our Friends,--George Dillwyn, Sarah Grubb,
Mary Dudley, and their companions were the first, then William Savery and David Sands,
and last, Richard Jordan.
But these dear friends, not speaking the French language, at least very imperfectly,
had not a very full opportunity of becoming acquainted with them.

17th. I continue diligently engaged among the little flock in this village.
I have had religious opportunities in every one of their families,
also several meetings for Divine worship among them, and with the inhabitants at large,
who are Roman Catholics and Protestants.
There is great openness among them.
Mollet has accompanied me in these services.
He has a pious mind,
and I hope this engagement will tend to strengthen
him to walk as one more devoted to the dear Redeemer.
Several among the little flock here speak in the ministry.
Louis Majolier may be considered among them as a father and a pillar.
Finding that they have no discipline among them,
so that those whose conduct has been disorderly,
and through whom weakness and suffering have been spread over the whole body,
have not been properly dealt with for their recovery,
I had a conference with them last evening on this account.
The importance of the subject was spread before them,
and the necessity of having a discipline, adapted to their state and strength,
agreeable to Gospel order.
It was an instructive season;
the brokenness of heart of many of them reminded me of the time when the
Book of the Law was read to the people in the days of Nehemiah.
With weeping and sobbing many of them confessed their manifold weaknesses,
and their lack of allowing the love of God, through Christ, to have free course in them,
to which were traced their low estate,
and their falling away from the purity of that profession,
which their forefathers had maintained amidst so many sufferings.
They united in the propriety of establishing a discipline,
and have appointed a committee for that purpose.

19th. Codognan.
Yesterday morning, on my way to this place, I had a meeting at Muse, a small village.
In the afternoon and this morning I visited the few
families of those under our name here,
who are in a weak state.
I also had interviews to my comfort, with some pious Protestants in the village,
and last evening had a meeting with the inhabitants, who very generally attended.
At first some appeared shy, but after a while their hearts were opened,
and the Gospel was preached largely unto them.

21st. St. Gilles.
I came here last evening and found about ten families of professors under our name.
I have had two meetings with them.
That in the afternoon was attended by the inhabitants.
Chabran, the Protestant Minister, was present.
The Lord has opened his understanding in the Truth.

22nd. I came to Vauvert,
where reside a few families of professors under the name of Friends.
I had a meeting with them and others, about two hundred persons.
Two priests and one of the professors of the college at Montpellier were present;
the latter was much tendered under the solemn truths of the Gospel, given me to unfold.
I opened to them the way through which alone we can come unto God,
which is through Christ, the Way, the Truth, and the Life;
that it is only by the Spirit that the things of God can be known, etc.

23rd. I went back to Codognan, visited again the few Friends there,
and reached Congenies that night.

24th. Attended their week-day meeting in silence.
My mind was much engaged for them, that they may be gathered into that state,
where our whole expectation is from the Lord alone,
in which therefore the soul is prostrated before him,
hearkening to the secret language of his Spirit, and waiting for his Divine guidance.

Louis Majolier accompanying me, we went to Fontanaise, to Samuel Brun`'s,
his father-in-law.
He and his wife are valuable aged Friends.
There are three more families in the village,
and we had that evening a good refreshing meeting with the inhabitants.
Next day had another precious meeting at Paradon`'s, two miles beyond St. Hypolite.
It being First-day, and notice having gone before,
people came to it from six to twelve miles distance.
Many very tender seeking persons reside on these mountains,
where the Lord has had a precious seed for ages;
they have greatly suffered in the times of persecution.
The same evening I had another very large meeting in the town of Ganges.
The streets were thronged with people, round the house, but they were very quiet.
The Gospel flowed freely towards them, and many hearts were open to receive it.
It was a time to be had in lasting remembrance;
for the Lord`'s grace and power were exalted, and many, with tears, acknowledged it.

The following morning, we returned to St. Hypolite, where also,
feeling my mind engaged to have a meeting, a place was provided.
It was thought sufficient to contain the people, being a pretty large room;
but it seemed as if all the inhabitants of the town had turned out.
The whole house was filled, and a very large number stood in the street,
in a quiet becoming manner.
I had taken my seat near the window,
a very convenient place to be heard both in the house, and in the street.
For some time I sat under great distress of mind, yet at the same time,
the love of God through Christ, flowed in my heart, towards the people.
Abiding under it, I felt the Lord`'s power to rise over all,
believing that whatever trial might come upon me, He would support me even unto death.
Then I thought I felt his word of command to preach unto the multitude Christ,
with his attributes and Divine offices; when,
on hearing some bustle through the crowd towards the door, Louis Majolier, who sat by me,
whispered to me, "`The Commissary of Police is coming.`"
I so felt the Lord`'s power, that I answered him, "`Fear not, only be quiet.`"
The Commissary then drawing near to me said,
"`Are you the person that is going to preach?`"
I replied, "`It may be so, please sit down.`"
On which, taking me by the collar of the coat, he said,
"`You must follow me to the Mayor,`" when I answered, "`I may not detain you long,
please take a seat a little while`"--on which I began to speak to the people,
as the Lord gave me.
He stood amazed, keeping hold of me, as I spoke, till at last, he said,
"`I go and make my report,`" and then he retired.
I continued preaching to the people, who all kept quiet, not moved at all by what passed.
Indeed, on the contrary, when the Commissary, on his way to the door,
passing by some soldiers who were in the meeting-room, ordered them to go and take me,
they answered, "`We cannot disturb a man thus engaged.`"
I continued about an hour to speak to the people, as the Lord enabled me;
for he was with us, his love and power were felt by many,
whose spirits were greatly contrited; the Divine witness reached their hearts.
Having taken my seat, and now feeling myself clear, the meeting concluded,
when I judged it expedient to go immediately to the Mayor`'s office,
to see if he wanted anything of me; several persons accompanied me.
Not finding him there, I was proceeding to his house, when I met the Commissary,
who began to threaten me with imprisonment,
and with heavy fines upon those who were at the meeting.
We went together with him to the Mayor`'s house; he not being then at home,
we waited a considerable time for his return.
In the meanwhile, many people, out of concern for me, and others from curiosity,
were gathered about to see the end of this.
At last, when the Mayor returned,
the Commissary went to him to make his own representation,
which prepossessed him against us, so that when we came in, seeing me with my hat on,
he put on a pretty angry countenance; but I, in a mild, respectful manner,
gave him some of my reasons for thus appearing covered.
I had hardly given my explanation, when, with a placid countenance, he said,
"`I know something of the Society of Friends, and their manners.`"
Then, making me sit by him, in presence of the people now collected,
he inquired into the object of my present engagements,
which led to the unfolding of the religious principles of our Society,
and various Christian testimonies; after which, in presence of all,
he read audibly the translation in French of my certificates,
and heard my account of the care extended by our Society towards their ministers,
when thus going abroad as ambassadors for Christ.
He said after that, "`I am sorry you have been disturbed;
had I been here it would not have been so.
If you wish to have any more meetings,
I shall have care taken that every arrangement be made, and nobody will disturb you.`"
I accepted his civility, and we parted; his heart was open towards me.
I left with him several books, in French, on religious subjects,
which he kindly accepted; and the next day, on my way to Quissac, another town,
a messenger, sent by his wife, overtook me,
requesting that if I could spare some more of our books for some of their friends,
it would oblige her.
Among the books I gave were Penn`'s [.book-title]#Rise and Progress of Friends#, his [.book-title]#Maxims#, [.book-title]#No Cross No Crown#,
and some tracts I had printed at Nismes;
among others the short account of our principles and Christian testimonies, etc.
The name of the Mayor is Laperouse.

At Quissac, where I arrived that afternoon,
the people were very ready in making way for my having a meeting among them,
and as no room large enough to accommodate them could be found,
it was concluded to have the meeting out of doors.
It was a fine, serene evening.
They made choice of an orchard surrounded by high walls, which they seated,
placing lanterns in the trees, in which also many persons had taken their station.
There were thought to be about one thousand five hundred persons collected.
I have seldom known a more solemn stillness prevailing
in a religious meeting than we witnessed there.
It was a time of very precious visitation of the Lord to this people;
the Gospel descended upon them as the dew on the tender grass.
The Lord has a precious seed in these parts.
These are the plants I had felt so much for when in America,
which the Lord now enables me to visit, making me, his poor servant,
an instrument in his hands, to water them;
may they not be satisfied to be brought under the convictions of the Truth,
but yield obedience thereto.

I returned through Fontanaise, and had another refreshing season with a few there,
and then came back to Congenies,
having during the last six days travelled mostly on foot;
for we had but a small mule for three of us.
The weather was very warm, but the Lord has strengthened me for the service,
and is also my soul`'s rejoicing.
I returned to Congenies in time to have an evening meeting with Friends and others.

Tenth month, 2nd. I went a few miles to see a Protestant minister,
who when George Dillwyn, Sarah Grubb, and Mary Dudley visited this place,
attended a meeting they had, on which account, he suffered a good deal of persecution;
dwelling under the impressions he had received,
his mind became more and more enlightened in the Truth,
his heart being open to the teachings of the Lord`'s Spirit.

First-day, 4th. I have had two meetings at Congenies, the last, especially,
being very large, the people of the neighbouring towns and villages,
Papists and Protestants, having come to it.
The Lord condescended to own us by his presence,
and to enable me again to preach his everlasting Gospel of life and salvation,
to the contriting of many hearts.
The meeting concluded with fervent supplications for the
Divine blessing upon the inhabitants of these southern climes,
and grateful acknowledgments for the many mercies received.
Many, after meeting, expressed their sense of the favours of that day,
and the blessing it is to sit under a living ministry.

5th. I have had a general meeting with Friends from
the various places I have visited here,
for the purpose of considering the proposed introduction
of a Christian discipline among them.
Previous to entering into the business for which Friends had met,
we were favoured to feel the overshadowing of the Divine presence,
preparing us for that day`'s work.
The Committee set apart at a preceding meeting for the purpose,
presented the essay of a draft they had prepared,
in which they have made a proper distinction between advices,
that they ought to endeavour to comply with, and the rules of discipline, which,
adapted to their weak state, they ought to submit to, and walk consistently with,
if they wish to remain members of this religious body.
They then proceeded to appoint Overseers, and some Elders,
that due care might be extended to the flock generally,
and exercised towards those among them who apprehend it to be their
duty to speak sometimes in their meetings as ministers,
that these might be preserved from falling into the snares
and extravagances which some among them have given way to.

6th. Proposing to depart from Congenies tomorrow,
I have spent the day in paying many solemn parting visits, and this evening,
I have had one more meeting with this little flock.
Our spirits were contrited together, and once more refreshed in the Lord`'s presence,
prostrated before our blessed Redeemer, in gratitude, that to the last,
we were favoured to feel the extension of his love.
This is a hard parting to many of us, to some of the dear young people especially,
in whom I hope the seed of the kingdom of Christ has taken some root.
May the Lord water it, and cause it to bring forth fruit to his own praise!

--

Stephen Grellet now felt at liberty to leave Languedoc,
and early next morning proceeded on his way to Montpellier.
Many of the inhabitants of Congenies, and most of the "`little flock,`" who had been,
more especially, the objects of his Christian labours,
accompanied him some distance on the road;
"`the dear people seemed as if they could not part with him, and,
having once more supplicated before the sacred footstool,
imploring the Divine blessing upon them,`" he left them, "`looking after him,
as long as they could see him.`"
On arriving at Sommieres, in the midst of an annual fair,
he could neither obtain accommodation at the inn,
nor a conveyance to take him forwards on his journey.
Having, therefore, given directions for his baggage to be sent after him,
he set off on foot, "`staff in hand, like a poor pilgrim,`" and reached Montpellier,
a distance of about twenty miles, late in the evening.
He spent one day in that city.
"`Through the medium of D`'Encontre, the professor I met with at Vauvert,`" he remarks,
"`I was introduced to a few religious persons,
and have had a solemn and satisfactory meeting among some of the people.`"
