== Chapter XIII.

[.chapter-synopsis]
* New York Yearly Meeting
* Deputation to Visit Subordinate Meetings
* Elias Hicks
* Religious Visit to the Southern and Western States
* Death of Thomas Paine

Peacefully returned, from an interesting visit to his Father-land,
Stephen Grellet was soon called upon to mingle again in religious
exercise with the assembled brethren of his own Church,
and to unite with them in active exertions for the
promotion of the Redeemer`'s cause within its borders.

[.embedded-content-document]
--

"`At our Yearly Meeting in New York, in the Fifth month, 1808,`" he writes,
"`an exercise feelingly came over Friends on account of our young people,
that the parents should increasingly manifest their concern for them,
by training them up in a religious life and conversation
consistent with our Christian profession,
and that, as a proper step thereto,
a more strict care should be exercised by parents and guardians over the youth,
especially on the afternoons of First-days,--that,
instead of spending their time in visiting, or in unprofitable company,
they should endeavour to keep them at home, reading together the Holy Scriptures,
and also other books calculated to bring them to
the knowledge of the truths of the Gospel,
and the consolations of the Christian religion,
that thereby they might become better acquainted also with
the nature of the profession we make as a religious Society,
to ignorance of which may be traced many of the out-goings from among us,
as is lamentably obvious.
The interesting subject was so deeply felt in that meeting,
that an appropriate minute was made thereon,
and a Committee of three men and three women Friends was separated, to attend,
as their way should open, all the subordinate meetings of that Yearly Meeting,
and to enforce as they should receive Divine help,
the necessity of this pious and important concern.
I was one of the Committee separated to that service.`"

--

Soon after the conclusion of the Yearly Meeting,
the Committee thus appointed engaged in the work.
They found it a deeply interesting but "`a laborious
and arduous service,`" and the mind of Stephen Grellet,
deeply imbued with the knowledge and love of the Saviour,
and watchfully turned to the Spirit`'s teachings,
while earnestly concerned that souls might be "`won to Christ,`"
or be confirmed in the Truth as it is in him,
could not fail to be keenly alive to everything
that had the least tendency to lead away from him,
or to lessen in the view of others the beauty and loveliness of his character,
and the completeness of his Divine attributes.

[.embedded-content-document]
--

"`I became introduced,`" he says, "`into very deep and painful trials; for Elias Hicks,
one of our Committee, frequently advanced sentiments repugnant to the Christian faith,
tending to lessen the authority of the Holy Scriptures,
to undervalue the sacred offices of our holy and blessed Redeemer,
and to promote a disregard for the right observance of the first day of the week.
Though his assertions were often so covered that few understood him fully, I frequently,
fervently, and earnestly laboured with him.
He promised that he would be more guarded; but vain promises they were,
and several times I felt constrained publicly to
disavow the unchristian doctrine that he advanced.
My distress was great when in my native land, amidst popish superstition and darkness;
but now it seems still greater, among my own religious Society,
as few appear to be sensible of the threatening affliction
that I see gathering upon us;--the cloud becomes darker.
Some time past he advanced these, and other sentiments of the same kind, very cautiously,
but now he grows bolder.
I think it is three years since, when, at a public meeting in this city,
after he had advanced some such sentiments, I felt it my place,
(in that meeting,) to open and explain the subject, how, as a religious Society,
we had uniformly received and maintained the fundamental Christian truths,
in harmony with clear Scripture doctrine.`"

--

Though, at that time, comparatively a young man,
associated in religious service with men of much longer standing,
it is interesting to see in these simple records
of his early course as a minister of the Gospel,
how clearly Stephen Grellet was enabled to detect
the subtle fallacies of an acute but shallow thinker,
in the incipient stages of that departure from the "`Truth as it is in Jesus,
according to the Scriptures,`" which twenty years after was so fearfully developed.
As a faithful watchman, Stephen Grellet early saw its character,
and anticipated its results--true and steadfast in
his allegiance to the cause of the Redeemer,
he bore unflinching testimony to the eternal glory of His name,
and sought to vindicate the doctrinal soundness of
the Christian community of which he was a member.

After returning from this engagement in the service of the Church,
he resumed his ordinary occupations amidst the comforts of home.
It had, however, been "`given him in the behalf of Christ not only to believe on him,
but also to suffer for his sake,`" and his time and
talents were still devoted to his cause.

[.embedded-content-document]
--

"`During the winter,`" he remarks,
"`I endeavoured to engage in some little temporal business;
but I was not permitted to pursue it many months.
For, believing that my blessed Master called me in the service of his Gospel, once again,
to the Southern, and some parts of the Western States,
I made the necessary arrangements for such a journey.
My dear wife concluding to stay, during my absence, at her father`'s,
who had now removed to Burlington (New Jersey), we broke up housekeeping, and,
with the unity of my friends, and their testimonials of approbation,
I left home on the 18th of Third month, 1809.
My wife accompanied me as far as Burlington,
which place we reached in time to attend their meeting, on the 23rd. I sat it in silence,
but in this silence my mind has often been refreshed,
and encouraged faithfully to follow the Lord in all his requirings.`"

--

Thus cheered by the good presence of the Lord,
and having left his beloved wife under the care and protection of her earthly parent,
he committed himself and his all into the hands of his Heavenly Father,
and proceeded on his mission, in obedience to His will.
Of this engagement, which was an extensive one,
the following particulars are extracted from his memoranda.

[.embedded-content-document]
--

Philadelphia, First-day, 26th. I have been in the morning at the North Meeting,
to which I belonged while my residence was in this city,
where also the Lord was pleased to grant his poor
servant many instructions and sweet encouragements.
I was largely engaged among them, and we had a refreshing season from the Lord.
In the afternoon I was at their large, new meetinghouse in Arch Street,
and in the evening at Pine Street.
The Lord`'s power was near us,
the stream of the Gospel flowed like oil towards the poor
in heart and contrite in spirit,--blessed be Israel`'s Shepherd,
our Holy Redeemer, forever.
My kind friend Thomas Willis came here from Long
Island to accompany me through part of this journey,
and in the evening my valuable friend Thomas Scattergood, coming in,
administered a word of encouragement to us in the
prosecution of the service of the Gospel of Christ,
the Saviour.

Baltimore, 2nd of Fourth month.
We have spent a few days here, visiting several Friends`' families,
particularly the sick, widows, and the afflicted,
my dear Master enabling me to break among them a little of the bread of consolation.
This day I have attended their two meetings; they were seasons of deep exercise,
for the spirit of the world has taken deep root among many,
estranging them from the love of God.
Lay low, O my soul, abide in humility and meekness before the Lord your Redeemer,
whom you hast so frequently known, under your past deep conflicts and baptisms,
to be your strength in weakness, your leader and deliverer.

We proceeded after that through Elkridge, Sandy Spring, Indian Spring, and Annapolis,
to Georgetown, having meetings in all those places.
I was also under great exercise because of the oppression
under which the poor slaves are kept,
and I was engaged, in some places, to describe to the people the nature of that religion,
which is pure and undefiled before God, and to contrast it with the fruits of slavery,
brought forth among them.
At Annapolis,
the people generally evinced great ignorance of the
things pertaining to Christ and his kingdom,
yet the Lord was pleased to permit his Truth to be declared among them.
At Georgetown, the meeting was held in the Presbyterian meetinghouse,
and was well attended,
as was that at Washington City,--my holy Helper strengthened
me to bear to them the good tidings of great joy,
which shall be to all people, testifying of the Saviour, which is Christ the Lord.
D+++.+++ Madison, the President`'s wife, and her sister, who were at meeting, appeared tender,
and invited me to go and see them; they were formerly members of our Society.
A physician, a tender-spirited man,
with much feeling related to me the following circumstance: A few weeks ago,
he was sent for by a planter, who resides some miles hence, to visit one of his slaves.
On entering the miserable cabin in which the sick man was,
the slaveholder accompanying him, he saw the poor slave stretched on a little straw.
On examining him, he found him in an apparently unconscious and dying state.
The master, who was not aware of his low condition,
began in very abusive language to upbraid and threaten him, using very coarse epithets;
he said, "`By pretending to be religious, and going to your meetings,
you have got this sickness; but, as soon as you are better,
I will cure you with a thousand lashes.`"
The physician told him that, from all appearance,
the poor man had but a few moments to live;--upon which,
the slave suddenly raised himself, lifted up his eyes, and, stretching forth his hands,
said in an audible voice, "`I thank you, Lord Jesus, my blessed Redeemer,
for all your mercies to your poor servant;
now receive my spirit into your kingdom;`" and then expired.
The scene was awful; the slaveholder stood speechless and amazed;
amidst his threats and reproaches, his poor slave was taken out of his power;
he could oppress him no longer,
his spirit had triumphantly quitted its afflicted tenement.
The slaveholder and the physician both remained silent about ten minutes, and,
without uttering a word, the latter mounted his horse and left the place,
with impressions that continued deep upon him, as he related the circumstance to me.

9th. We had two meetings at Alexandria;
in the morning I had very close doctrines to deliver,
having passed through deep baptisms,
because of a spirit of infidelity that continued to be felt here,
as was the case on my previous visit.
In the afternoon, the poor and humble travellers were encouraged.
From Alexandria we went to Occoquan; had a meeting in a mill, fitted up for the purpose,
and the following day had another at Fredericksburg, in the Courthouse,
at both of which help was received of the Lord to preach Christ,
the Saviour of penitent sinners.

Visiting all the meetings in that part of the country, we came to Richmond, Virginia,
where we had two large meetings; we had one at Petersburg the following day, which,
through the pressing invitation of the Episcopalian clergyman,
was held in their meetinghouse.
He who has promised to be unto His people, mouth and wisdom,
enabled me to speak largely of the nature of the true Church, and of its holy Head,
Christ Jesus the Lord, and of what is the order of the priesthood in his Church,
and of the ministry he calls them to.
I pleaded also the cause of the poor slaves,
as it is often given to me to do in these Southern States;
many minds were tendered under the Lord`'s power.

After visiting every meeting in the compass of Gravelly Run Quarter,
we came into the lower parts of North Carolina, Pasquotank and Perquimans Counties;
we visited every meeting in that large Quarterly Meeting.
We had also several meetings, where no Friends reside, at Edenton, Elizabeth City, etc.
Some of those meetings were seasons to be long remembered;
the Lord opened the Gospel stream, and caused the doctrines thereof to flow.
At Newbegun Creek, I opened to the people the state in which Adam was before the fall,
then described the mournful condition of man in the fall, and the impossibility for him,
by any efforts or wisdom of his own, to extricate himself from it,
and to regain that state of purity and acceptance with God,
and paradisiacal felicity which he has lost by sin; that we have all sinned,
and have come short of the glory of God.
Then I unfolded this great Gospel treasure--Salvation
through faith in Christ Jesus the Lord;
what He has done for us, without us, through the blood of his Cross,
his meritorious death and most holy and acceptable offering of Himself for our sins,
whereby we are reconciled to God; and what, through his eternal Spirit and Divine Grace,
he does for us, within us; that, through the obedience of faith,
we may be renewed again through Him, both obtain remission of sin,
and witness a newness of life,
and finally an entrance into his glorious kingdom of everlasting blessedness,
where Satan, the grand deceiver, the old adversary, has no more place,
and the purified spirits can never fall.
I have found tender minds seeking after Truth, at several places,
and had a word of encouragement to give to them.
We had meetings also among the slaves, their masters appearing to encourage them to come;
they were seasons of instruction both to slaves, and such of their masters as attended.

1st of Fifth month.
We had, at Button`'s Creek,
a meeting of the Ministers and Elders in that Quarterly Meeting;
the Lord made it a time of close searching of heart; but He,
the great physician of value, was near; it was a contriting season.

4th. Returned into Virginia, and was at meeting at Somerton, where there was a marriage,
which had attracted a large number of people.
At the close of the meeting, the bridegroom gave a general invitation to all present,
to come to the wedding-dinner.
My companion, Thomas Willis, and I were particularly invited to it,
but we could not feel our minds at liberty to go.
I have a great objection to such large and promiscuous companies,
which frequently open the door for much dissipation; yet I can make allowance for what,
in a new country when the inhabitants were but few, gave rise to such a practice;
but now I consider it is high time it should be discontinued,
especially in our religious Society.
It is indeed the concern of Friends,
that temperance and moderation should be maintained at marriages, funerals,
and on all other occasions.
We went back to dine at our friend Jesse Copland`'s;
but in the afternoon I apprehended it was my duty to join the wedding party,
at which we found a large company, at least one hundred and fifty persons;
tables were also spread out of doors,
round which were collected many of the black people.
I was glad to see these in the way of making a good meal,
which the poor slaves do but seldom.
My mind came under a religious concern for that large and promiscuous company,
and at a suitable time, when they had finished their repast,
they were all invited to sit down together, under the shade of trees,
where provision had been made for the purpose; the Lord, my blessed Master,
enabled me to hand to them some of the wine of his kingdom,
to the grateful acknowledgment of many, that the last wine was the best wine.
At the close of that religious opportunity,
I requested the company quietly to retire to their several homes, which, soon after,
they very generally did.
I notice this more particularly,
as companies on such occasions frequently continue together till late at night,
to the great injury of one another.

We attended a few more meetings thereabouts, and their Quarterly Meeting,
then held at Cedar Creek, which was a time of much conflict;
some of the people come to these meetings as to a place of diversion,
which is a great concern to Friends.
At that meeting, the Lord`'s Truth was exalted, and the Life was brought into dominion.

We had a meeting at Portsmouth, in the Methodist meetinghouse; another at Norfolk,
at the Courthouse; the Mayor and most of their chief inhabitants, attended.
I found a seed in both of those places that I was enabled to visit, and,
in the power of the Gospel,
I unfolded many of the truths pertaining to the kingdom of Christ.
The last meeting concluded in prayer for the rulers of the land,
that they may rule in the fear and wisdom of God, and protect the oppressed.
The Lord was also entreated on behalf of the poor slaves, and the Africans generally,
as even such of them as are free are greatly borne down by the laws of this state.
After meeting, some were heard to say,
"`This is the everlasting Gospel that we have heard,`" others answered,
"`We have the witness in our heart,`" and some said, "`We could have sat till night.`"
Blessed be the name and power of Him to whom all glory belongs!

We had the next day a meeting at Bennett`'s Creek,
where I was greatly oppressed under a sense of the wickedness,
and even the blood-guiltiness of some present,
and I spoke to the people of the awful condition
of those who thus follow the way of Cain.
After meeting,
I heard that three men were present who had been engaged in the murder of a black man;
but, as the evidence of slaves is not received,
the law takes no cognisance of their crime.

12th. My dear friend, Thomas Willis, left me to return home.
I sensibly feel the separation,
for he has been a fellow-helper to me in my Gospel labours;
I feel it very weighty to be left alone to bear the various baptisms attending
such a solemn service,--O Lord help your poor and dependant servant!
That day I had a meeting at Suffolk, in the Courthouse;
the Gospel was like dew distilling on the tender grass;
glory and praises be unto the Lord.
He is with his poor servants, in their extremities; I was very low;
the Lord has helped me.

14th. I was a second time at Black-water, which was a large meeting,
mostly composed of slaveholders and their slaves.
It was a favoured meeting,
the Lord enabling me to divide the word aright to that mixed company.
I then crossed the James`' River and came to Williamsburg; the meeting there was large;
the inhabitants and collegians very generally attended; Christ, the Saviour of men,
was preached; the nature of true worship, in spirit and in truth,
and of the ministry in Christ`'s Church, was unfolded.
The following day I was at Skimeno.
I was largely engaged in setting forth what is the Christian baptism, by which a man,
being regenerated or born again, becomes qualified to partake of that living bread,
which nourishes the soul unto eternal life;
then I showed how all the former dispensations were pointing to Christ,
the end of all shadows.

The Quarterly meeting, now held at Wain Oak, coming on, I went there,
and continued in that neighbourhood till their Yearly Meeting for the State of Virginia.
During those several meetings I was introduced into deep baptisms,
both on account of our own Society, and the people of that land,
and at times I had close testimonies to deliver among them;
for the word of the Lord is as a fire and a hammer
on everything with which he has a controversy.
Towards the close of the Yearly Meeting, men and women sitting together at my request,
the Ancient of Days in a wonderful manner revealed his power among us,
so that we could feelingly acknowledge that the shout
of the King immortal was heard in our camp,
and under the power of his melting presence, many were bathed in tears.
The following day I attended a meeting held for the black people in these parts,
which was a season of Divine favour.
I went afterwards to Richmond, Genito, and Lynchburg,
much exhausted by hard riding and the heat of the weather.

31st. Had a meeting at Lynchburg, in the Courthouse; and the next day at South River;
at both those places, the iniquitous practice of slavery,
and the cruelties used by the tobacco planters upon the poor slaves, lay heavily upon me.
At South River, as I was setting forth the abominable traffic in human flesh,
three men came in and sat before me.
It afterwards appeared,
that they were travelling through the country on such inhuman business, and,
seeing a concourse of persons coming to the meetinghouse, they came in also,
in hopes of hearing of some slaves they might purchase.
I knew nothing of these circumstances; but, as I was speaking,
tears would now and then escape them, and after meeting they said to some persons,
that I so represented the wickedness of their trade
that they could not refrain from weeping.
O that they might be tears of true repentance!
I came that night to Elias Fisher`'s,
a friend with whom I had some conversation at their Yearly Meeting,
and who proposes to accompany me during a part of my present religious engagement.

We had a meeting at Joice Creek, which was very much disturbed by some unruly persons;
I left the place with a heavy heart.
We went the following days to the meetings of Upper and Lower Goose Creek,
and reached New Garden, North Carolina,
in time to have a meeting there on the 7th of Sixth month;
through the comfort that flowed from the Divine presence, we were much refreshed.
The day following, we attended a meeting at Dover, in silence,
and on our way back to New Garden, we paid a visit to a man, ninety-six years of age,
who has lost his sight, but is in a state of Christian sweetness;
I was comforted in being with him.

At the Quarterly Meeting, Friends were comforted and edified together.
We went afterwards through all the meetings composing
the Quarterly Meetings of New Garden and Deep River,
having meetings also in the Courthouses in some of the towns.

--

Having completed his religious engagements in North Carolina,
Stephen Grellet passed over the Blue Ridge mountains and entered Tennessee.
The number of Friends in that State was not large, and their meetings were few.
They constituted one of the Quarterly Meetings belonging to North Carolina Yearly Meeting.
He visited them all, and held meetings with the inhabitants of many towns,
both in Courthouses, and the places of worship of various denominations, and remarks:
"`Many of these meetings were seasons highly favoured by the Divine presence and power.
Through this State, I have found some pious persons,
and the stream of the Gospel has frequently flowed towards them.
O that they may settle upon Christ Jesus,
the only sure foundation of our hope of salvation!`"
From Tennessee he went into Kentucky, and thus continues his memoranda:

[.embedded-content-document]
--

Stanford, 22nd of Seventh month.
My mind being strongly attracted, in Gospel love, towards the inhabitants of this State,
I have yielded to the prospect of religious duty to visit them.
There are no meetings of our Society here,
neither do I know that any Friend has ever travelled in these parts on a Gospel embassy.
The Lord who calls me here, is all-sufficient to make a way for me,
so as to have a service for the promotion of the blessed Truth among these people.
We have travelled over hills and mountains, and have forded several deep waters;
about one hundred miles of this journey having been
through what is called the Wilderness of Kentucky.
Besides the difficulty of the road, especially on account of almost continual rain,
we had considerable dangers to apprehend from robbers,
as we heard that several persons had been plundered, and some murdered,
by white persons under the disguise of an Indian`'s dress.
It is also worth noticing, with grateful acknowledgments, that,
though we have met with travellers who had been detained
several days by the great rise of the river,
we have not been impeded one hour;
for the rain ceasing a little while before we came to the waters,
we found them in a fordable state, and soon after, heavy rains returning,
those rapid streams were not passable; some persons, attempting to cross, were drowned.
To have been under the necessity of encamping near these streams, would have been trying,
as there are no houses or cabins, to obtain any kind of shelter or refreshment.

We had meetings at Stanford, Danville, Lancaster, Richmond, etc.
At all these places, the people`'s minds were open to receive me,
and the messages the Lord gave me to deliver among them.
At Lancaster, there was a band of soldiers, on their way to some western post;
the officer brought them all to meeting.
Some of these meetings have been memorable seasons.--Ah! what abundant cause have I
to be encouraged to follow my blessed Master in all the ways of his commandments.
He is indeed my strength and my help; blessings and praises be forever ascribed to him.

Lexington, 28th. This is the chief town in this State, and is improving fast;
they are building at once large blocks of handsome brick houses.
The soil in this State is very fertile,
and a considerable quantity of produce is brought to the towns,
where there are navigable waters.
I had a meeting here today, in the large, new, Presbyterian meetinghouse,
which was attended by their minister, the inhabitants generally,
and also the Episcopalians and Baptists; it has been another season of Divine favour;
may I, with increased dedication,
be offered up in faithfulness to serve the Lord in all the ways of his requirings.

We went after that meeting to Versailles, Frankfort, Georgetown, etc., etc.,
having meetings very generally in all the Courthouses in the country;
and travelling hard from place to place,
we have found an open door in the hearts of the people,
and I have been much enlarged in Gospel labours among them.
I have felt much reduced after these arduous services, and probably the more so,
as on my coming into this State, I found that after I had had a meeting in a place,
it was with difficulty I could prevail on the innkeeper
to receive due compensation for my entertainment,
and I therefore made it a practice to settle my bill at the inn before meeting,
which was mostly held in the forenoon,
and to set off for the next place directly after it, without dinner,
thus having no refreshment till evening, and riding in the hot sun,
and that after meetings in which I had been long engaged before a numerous congregation.
O that the seed of God I have visited in this State,
and been made an instrument to water, may spring forth to the praise of the Lord!
From place to place, I have found it a time of renewed visitation to the people.

--

Leaving Kentucky he crossed the Ohio, and once more set his foot on Free-soil.
The State of Ohio, though of comparatively recent origin, already began to exhibit,
in its rapidly increasing population and general prosperity,
the blessing of exemption from the blight of slavery.
His journal proceeds:

[.embedded-content-document]
--

Cincinnati, 4th of Eighth month.
This forenoon I have had a meeting in their largest meetinghouse.
There are a few families of Friends here, but they have not yet any meeting allowed them.
My blessed Master has strengthened and qualified me to preach him to a numerous congregation,
to the renewing of the faith, I hope, of many of the people.

5th. By travelling hard, through a heavy rain, we reached Waynesville this evening.
It is the first settlement of Friends in this part of the State of Ohio.
The pouring down from the clouds was but a faint simile
of the streams of heavenly love and life in which,
during the ride this day, I was immersed, even as into the ocean of everlasting Love;
thus, this evening, notwithstanding the exposure and fatigue, I feel greatly refreshed.

6th. Attended Miami Monthly Meeting, held at Waynesville;
it did not conclude till near sunset.
I think they received about sixty certificates of removals into their borders,
so great is the emigration into these parts.

7th, First-day.
I was again at this meeting; the shout of the King immortal was heard in our camp,
so that, in living faith, some of us could say, "`This is our God;
we have waited for him, and he will save us: this is the Lord; we have waited for him,
we will be glad and rejoice in his salvation.`"

I set off the next day for Whitewater, Silver Creek, etc.,
and returned again to Waynesville to attend their Quarterly Meeting.
I have attended three meetings and ridden one hundred and forty-five miles,
most of it over bad roads, or rather Indian paths, through an uninhabited country,
from one settlement to another.
One afternoon we had not even an Indian path to direct our course.
The sun, for a while, enabled us to keep in the direction we intended,
but it becoming cloudy, we were under great difficulty;
we rode through thick underwood till late in the night,
when we were favoured to reach a small cabin, in which we took shelter,
but had nothing to eat; our saddles served us for pillows.
Before sun-rise the next morning we were again on our horses,
and yet we did not reach the meetinghouse at West Branch,
till after the meeting had been sitting, at least, half an hour.
It was a memorable meeting, well worth all the toil endured to reach it.
The day before, I had been at Whitewater, in Indiana,
the only meeting of Friends in that State.
The last days have been attended with more bodily
fatigue than I ever remember to have experienced,
having very little food, and sometimes being obliged to chew the bark of wood for a meal;
but, under all, my spirit has praised and magnified the Lord,
my Saviour and never failing Helper.
He has indeed been very near, so as greatly to contrite my spirit.
As I was riding, my soul was poured forth unto him,
on behalf of all those among whom he has given me to labour in the service of his Gospel,
these years past, both in these American States and in France,
and also for my particular friends and near relatives,
that he may bless them and protect them.
How near have the sheep and lambs of his pasture, wherever scattered, felt to me!
May the Great Shepherd of the flock feed them and watch over them!
Under the sense of the favours I enjoyed, I have thought, who can say,
I serve a hard Master?
He is indeed a bountiful Master, and a rich rewarder.

12th. The Quarterly Meeting today was so large that
about two hundred could not get into the house,
during the transaction of the business.
For the meeting for worship, sheds had been made with green bushes round the house.
This is the first Quarterly Meeting held here,
and they have already appointed a committee for a division of it.
This shows how rapid is the settlement of this new country.

Elias Fisher, my kind companion,
has been taken so poorly with the fever prevalent in these new and low countries,
that I am under the necessity of leaving him behind, with some kind friends,
he also proposing to return home as soon as he is able.
It is trying to be alone; be near,
O Lord!
By you all my needs are satisfied.

Caesar`'s Creek, 13th. In the course of my religious services,
I have seldom passed through greater depths of exercise than I did at this meeting;
and my attempt to communicate to the people what was on my mind,
did not afford me much relief.
This exercise, together with the relaxed state of my frame,
through the fatigue and exposure of the preceding weeks,
so pressed upon me that I fainted at the close of the meeting; but,
after resting a little while at the house of a Friend, near the meetinghouse,
I was able to proceed in the afternoon,
towards the meeting appointed for the following day, near Jonathan Wright`'s house,
who was with me and kindly waited upon me.
Chills and fever came on in the night, which made me feel very feeble in the morning;
nevertheless I went to meeting, and through adorable mercy, soon after I took my seat,
all my sufferings were forgotten.
My spirit being quickened afresh in the love of the Gospel of Christ,
out of weakness I was made strong,
and I was extensively engaged before a large congregation.
Many were contrited under the feeling of the renewed visitation of God to them:
I hope some of the young people will, in days to come, recollect this day as one,
when stones of memorial were given them to rear up as an Ebenezer.

--

After this meeting Stephen Grellet proceeded to Fairfield.
Here he was obliged to yield to the pressure of disease, and, for several weeks,
his religious engagements had to be suspended.
On his recovery he thus resumes his memoranda:

[.embedded-content-document]
--

Fairfield, 4th of Ninth month, 1809.
My travelling in my Gospel embassy has been interrupted through a heavy illness.
My health appeared to be sinking by degrees, till at last,
the symptoms of the fever prevailing here, at this time of the year,
were evidently upon me, and besides the high fever,
an inflammation of the lungs rendered my situation still more critical.
I came here to attend the meeting I had appointed, with some others,
at the close of last Quarterly Meeting; but the disease had made such progress,
that it was with great exertion that I went to meeting, and while sitting in it,
I became convinced that it would be in vain for me
to attempt to proceed any further at present,
and that I must be resigned, if it was my dear Master`'s will,
to lay down my earthly tabernacle in these distant parts,
far separated from my dear wife and near friends.
I was then engaged, on bended knees, with fervency of spirit,
to supplicate for resignation to the Lord`'s will,
whether it might be a continuation of my life,
to have it devoted to the service of my Saviour and Redeemer, or now to lay it down,
amidst my engagements in advocating His blessed cause of righteousness and Truth;
I interceded also for all those among whom I have laboured for years in the Gospel,
that my feeble services among them may be so blessed as to draw their hearts to Christ;
and lastly, prayers and intercessions were offered for the assembly present.
After this I felt sweet peace, in the prospect of being laid on a bed of sickness.

I now went to my kind friends, William and Henrietta Willis`'s,
who gave me every attention and accommodation their circumstances, in a new country,
allowed.
Their log-house or cabin is rather more commodious than the others in the neighbourhood,
which have but a single room, where all the family sit and sleep,
and where all the cooking is done; but this had another small log-chamber joined to it;
this they prepared for me, and it is to me like a little palace,
though it is so open that I can count the stars as I lie on my bed.
The fever soon increased to such a degree that those
about me gave up all hope of my recovery.
I was fully aware of my situation,
but under a sense that I had come here in the service
and at the command of my blessed Redeemer,
I felt sweet comfort in committing myself to his Divine disposal and care,
now in sickness,
as he had strengthened me to do in the prosecution of the work of his Gospel.
I had again a full view of what I had beheld of the
joys of God`'s salvation through Jesus Christ,
when near the gates of death with the yellow fever in 1798; but I have seen also,
that the end for which my days were then lengthened is not yet answered,
that though I have been extensively engaged, as it was shown me then that I should be,
in the service of the Gospel of my blessed Master,
very wide and extensive fields are yet before me, both in this and in distant nations;
therefore I have said, "`Lord,
your will be done! do with me and for me as is good in your sight,
only bestow upon your poor servant the blessing of preservation, that through life,
and the sufferings attending, I may glorify you, as also by my death,
whenever the work you hast for me is accomplished.
The place of my release, near or far from my beloved family,
and the circumstances attending my earthly dissolution, I resign, O Lord,
entirely to your disposal.`"
The fever has now subsided, but I am very much reduced,
so that I cannot take more than a few steps without resting.

6th. Though in much feebleness, I rode to meeting today.
O what a favour,
once more thus to be enabled to join my friends in
offering up public and solemn worship to the Lord,
experiencing, among the two or three gathered in his name,
the fulfilment of the promise made by the dear Saviour,
in the days when his eternal Divinity was clothed with humanity,
"`I am in the midst of them.`"
Thus is my soul bowed in deep reverence before Him, who was with me,
making my bed in my sickness, and now, on my first going out,
and that in the presence of His people, to worship His holy name,
condescends to manifest by His presence that He owns us.
I was strengthened also to preach the Gospel again to the people.
The balm of Divine consolation flowed, like oil, towards his tribulated ones.
On my return to my kind friends, W. and H. Willis, this evening,
I feel my strength considerably increased.

Chillicothe, 9th. Finding my health still improving,
and being desirous with all diligence to pursue my religious engagements,
I yielded to the impression of duty, to come to this place,
which is the seat of Government of the State of Ohio, and to have a meeting here.
Accordingly, the 7th inst., I left Fairfield,
and travelling slowly I have arrived here today, thirty-one miles.
This evening I have had a meeting with the inhabitants of the place,
in the Presbyterian meetinghouse, a commodious building.
I felt anxious lest, in my feeble state,
I should not speak so as to be heard over so large a congregation; but,
blessings and praises be to our all-sufficient Helper! the work is his,
the power to do it is his also, and the glory belongs to him,
which my whole soul and spirit in reverent prostration ascribes unto him.

Dry Run,
10th. Information was spread some days past of my intention to be at this place today,
which has brought here Friends and others from some distance.
One-half of the people could not get into the meetinghouse,
but sat round it in a quiet manner; we had a solemn meeting: Christ Jesus,
the only hope of our salvation, was preached to them.
In the afternoon,
I had another refreshing season with several Friends
that had come from Fairfield and thereabouts,
once more to bid me farewell.
I have met here my kind friend, Benjamin W. Ladd, who has concluded to accompany me,
till I reach the Yearly Meeting of Baltimore, which I propose to attend,
and to which the meetings in this State belong.

Brownsville, Pennsylvania, 25th. On my way here, I have had several meetings,
both among Friends, where they have meetinghouses,
and among those of other religious societies,
in the Courthouses or their places of worship.
I am very closely united in Christian fellowship
to the religious Society to which I belong,
but my Christian fellow-believers among other religious
denominations are also very near to me;
Christ`'s love is to all--he has died for all:
may the Lord so open the hearts of all to receive this blessed and saving knowledge,
that they may be turned from darkness to light, and from the power of Satan to God.
I have travelled under much bodily suffering these last two weeks.

Hopewell, Virginia, 2nd of Tenth month.
I had several meetings on my way to this place; at some of them the Gospel,
like a gentle stream, ran towards the people.
The love of God through Jesus Christ towards poor, fallen, sinful man,
for his redemption, is an inexhaustible spring.
Praise and magnify, O my soul,
that love and power that have followed me during this my present service in the Gospel,
as also on former occasions, under various exercises and baptisms.
Amidst my many spiritual conflicts and bodily sufferings,
my God has been my shield and my strength;
seasons of extremity have been so many opportunities
for his arm to be made bare for my help.
Bless the Lord, O my soul, and forget not his many benefits!

Baltimore, 14th. I had several meetings on my way to this city,
where I arrived last week, to attend their Yearly Meeting, which concluded this day.
It has been a season of much mental suffering to me.
Day after day I have borne in silence the burden of my distress,
except that at one of the meetings for Ministers and Elders,
I was enabled to unfold a little of the nature of the exercise of my mind.
Our Society maintains several great and important testimonies which,
in the opening and power of Truth, were committed to our forefathers;
and as these testimonies have been kept to and maintained,
they have been a great blessing both to our Society and the people at large,
over whom their influence has more or less extended.
A pure Gospel ministry, or in other words, a pure, clear,
and full testimony to the truth, as it is in Jesus,
must be acknowledged to be a great blessing to a congregation,
and to a religious society.
The influence of those who stand in the station of Ministers is great over the people,
either to bring them to Christ, by their example and precepts,
or to scatter them from Him.
Hence the great success of the ministry in the early days of the Christian Church.
The early history of our Society bears a similar testimony;
hence the growth in the truth,
and in the saving knowledge of our Lord and Saviour Jesus Christ, that was conspicuous.
My concern is sometimes great for our much favoured society.
If a forward, self-willed ministry gains the ascendancy among us,
we must become scattered as a people;
for that ministry which stands in the wisdom of man,
can never reach to the deep things of God;
it can neither understand them nor minister of them;
Christ crucified is foolishness to it.
I have travailed for an enlargement in Christian depth and experience with our Elders,
that they may be favoured so to labour as to avert
the threatening evil in various parts of our Society.
A Minister of the Gospel of Christ must be acquainted with and established in the faith,
and the hope of redemption through Christ,
else how can he minister to others what he himself has not.
An Elder, who is to be a judge of the ministry,
to help the weak and to instruct the ignorant,
must also be fully convinced of and established in the great truths of Christianity.
My soul has deeply mourned because of the many deficiencies I behold in these respects,
and the sad consequences which I anticipate, a spurious ministry will bring over us.
Yet, with gratitude it must be acknowledged,
that we have among us a few baptized Ministers and Elders,
who stand as fathers and mothers in the church, and also as faithful watchmen in Zion.

Deer Creek, 15th. Today a numerous company came to meeting;
many slaveholders among them, with whom, in Gospel love, I have had closely to labour,
showing them what the Christian character, and the fruits of the Spirit are.

Burlington, 17th. I arrived here this evening, where, through Divine mercy,
I am favoured to find my beloved wife restored from a severe illness;
we are permitted to unite together in celebrating
the excellency of the Lord`'s power and mercy,
who has preserved us both on a bed of sickness,
and supported us under our several probations.

--

After spending a few days at Burlington, Stephen Grellet, accompanied by his wife,
proceeded to Philadelphia, and from there to the meetings composing Concord,
and parts of the Western Quarterly Meetings,
in most of which he found "`an open door for his labours in the Gospel.`"
During the course of this journey they experienced a remarkable preservation from drowning.
Going down a steep hill, at the foot of which was a deep mill-race,
Stephen Grellet was unable either to stop or turn the horse, but horse and carriage,
with himself and wife, and a young female friend who was riding with them,
were suddenly precipitated into the water.
With characteristic presence of mind and prompt exertion,
he succeeded in rescuing both his companions and the horse from their perilous situation,
when a few moments`' hesitation or delay, would probably have caused the death of all.
In recording the event, he remarks,
"`This preservation of our lives induced us renewedly
to adore and praise Him in whose hands we are,
and to desire, with an increase of faith and confidence,
to commit ourselves wholly to his Divine guidance and almighty protection.
Certainly we have abundant cause to put our trust in the Shepherd of Israel,
who sleeps not by day, nor slumbers by night.`"

Having completed his religious engagement,
he returned to New York just eight months after he had left home;
"`strong emotions of gratitude and praise filling his heart,
while once more united with his little family in private devotion,
to wait together upon and to serve their blessed Lord, and holy Redeemer.`"
On account of his wife`'s health they had resided,
for some time previous to his last journey, out of the city, at the village of Greenwich.
At the same place lived the notorious Thomas Paine.
An authentic account of the last days of such a man
may have some historical value and interest,
and Stephen Grellet thus notices his decease:

[.embedded-content-document]
--

I may not omit recording here the death of Thomas Paine.
A few days previous to my leaving home on my last religious visit,
on hearing that he was ill, and in a very destitute condition, I went to see him,
and found him in a wretched state; for he had been so neglected,
and forsaken by his pretended friends,
that the common attentions to a sick man had been withheld from him.
The skin of his body was in some places worn off, which greatly increased his sufferings.
A nurse was provided for him, and some needful comforts were supplied.
He was mostly in a state of stupor,
but something that had passed between us had made such an impression upon him,
that some days after my departure, he sent for me, and,
on being told that I was gone from home, he sent for another Friend.
This induced a valuable young Friend, (Mary Rascoe), who had resided in my family,
and continued at Greenwich during part of my absence,
frequently to go and take him some little refreshment suitable for an invalid,
furnished by a neighbour.
Once when she was there, three of his deistical associates came to the door,
and in a loud, unfeeling manner said, "`Tom Paine, it is said you are turning Christian,
but we hope you will die as you have lived;`" and then went away.
On which, turning to Mary Rascoe, he said, "`You see what miserable comforters they are.`"

Once he asked her if she had ever read any of his writings.
And on being told that she had read but very little of them,
he inquired what she thought of them, adding,
"`from such a one as you I expect a correct answer.`"
She told him that when very young his "`Age of Reason,`" was put into her hands,
but that the more she read in it, the more dark and distressed she felt,
and she threw the book into the fire.
"`I wish all had done as you,`" he replied;
"`for if the Devil has ever had any agency in any work,
he has had it in my writing that book.`"
When going to carry him some refreshment, she repeatedly heard him uttering the language,
"`O Lord!
Lord God!`" or, "`Lord Jesus! have mercy upon me!`"

It is well known that during some weeks of his illness,
when a little free from bodily pain, he wrote a great deal; this his nurse told me;
and Mary Rascoe repeatedly saw him writing.
If his companions in infidelity had found anything to support the
idea that he continued on his deathbed to espouse their cause,
would they not have eagerly published it?
But not a word is said; there is a total secrecy as to what has become of these writings.

--
