== Chapter XIV.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Voyage
* Arrival at Liverpool
* Religious Visit to Scotland

Again fixing his abode at New York, Stephen Grellet was permitted, for about two years,
to remain very much at home.
During this interval of comparative repose,
his ministerial labours were chiefly confined to the city,
and his own Monthly and Quarterly Meetings.
As he had been accustomed to do, under similar circumstances,
he again "`engaged in a small way of business,
to make provision for his family,`" and also, as he says, "`to obtain,
through the Divine blessing upon his endeavours,
the needful supplies to defray the expenses of travelling in the service of the Gospel.`"

In perfect accordance with the good order established
in the Christian community of which he was a member,
he might have availed himself, for the latter object, of the willing aid of his friends.
But, with characteristic disinterestedness, he declined to do so.
Hitherto he had been enabled, even in this respect,
to "`minister to his necessities`" from his own resources,
and he felt it to be a privilege both to spend and to be spent in the work of his Lord.

[.embedded-content-document]
--

"`He has so blessed me,`" was the grateful record of this devoted servant,
"`that to His praise be it acknowledged,
I have gone on my own charges throughout all the extensive
religious journeys I have to this time taken;
though some of these have been expensive; my journey through France,
and crossing the sea, especially so; and on this continent I have lost three horses.
But I have only thus returned to my blessed Master, in his service,
what he has bountifully bestowed upon me.
My friends in New York would have paid my passage across the sea,
but I could not be free to consent to it.`"

--

In connection with these remarks,
it will be recollected that the religious Society of Friends have long borne
an open testimony to the spirituality and freedom of the Christian ministry.
Resting upon the experience and example of the Primitive Church,
and the authoritative teaching of the New Testament,
they continue to maintain that there can be no right appointment to the sacred office,
except by the call of our Lord Jesus Christ,
nor any true qualification for the exercise of the gift,
except by the direct and renewed influences of the Holy Spirit.
Hence they hold that what is "`freely received,`" should be "`freely given,`" and that
therefore the ministry of the Gospel must be essentially gratuitous and free,
without money and without price,--without "`hire,`" and without "`pay.`"^
footnote:[Bearing upon this point, and the Saviour`'s charge to the disciples,
it is interesting to meet with sentiments like the following in an eminent modern
author of the Lutheran persuasion.
{footnote-paragraph-split}
"`The direction,
in a certain sense admonitory, freely to give what was freely received,
does not refer to the working of miracles alone, indeed, only in a lesser degree to this,
for none but a Judas Iscariot would ever conceive the idea of being paid.
It embraces all that they have to impart,
the exercise of their power to heal and their preaching of the kingdom at once,
indicating both as grace to be freely offered.
No gift of God`'s grace is to be bought and sold
with money.--(Acts 8:20). Or as Tertullian says,
'`Nothing that belongs to God can be bought.`"
A comprehensive and most pregnant position,
which cannot be too much laid to heart by God`'s ambassadors even to the present day;
condemning all improper methodical and commercial stipulations in preaching God`'s grace,
all payment that surpasses the limits of their need--(ver. 10),
and all those unbecoming perquisites which are ungracefully attached to the direct
ministration of the word and sacraments.`"--[.book-title]#Stier on the Words of the Lord Jesus#;
translated from the German by Pope and Fulton.
Vol. II, p. 10.]

But, while precluded, by these fundamental views of Christian truth,
from providing any pecuniary compensation for preaching the Gospel, they fully recognise,
on scriptural grounds, the justness of the claim of the preacher,
for the supply of his outward needs, upon those who hear him,
while actually labouring in the cause of the Gospel,
and expending his whole time and strength for their benefit.
During the progress and continuance of such undertakings the ministers
of the Gospel cannot be expected to provide for themselves,
and it is well known to be the prevailing practice of the Society,
to pay the expenses of their journeys,
and to maintain them during the course of their labours;--"`the
workman being worthy of his meat.`"

Stephen Grellet cordially accepted both these views, though, like the Apostle,
in regard to the latter, as we have seen,
he did not wish "`that it should be so done unto him.`"
He "`coveted no man`'s silver or gold,`" and when he felt himself constrained,
by the gentle influences of his Saviour`'s love,
to visit the churches that are scattered abroad,
and to proclaim to his fellow-men the unsearchable riches of Christ,
he did it in the spirit that sought not theirs but them,
and "`so labouring,`" both in his temporal, and in his spiritual concerns,
he sweetly realized the truth of the words of the Lord Jesus,
"`it is more blessed to give than to receive.`"

In the midst of his ordinary duties and home engagements,
he was not unmindful of the special requirements of his Christian calling;
and under the expansive influence of Gospel love, a religious concern,
relating to distant fields of labour, was often a subject of serious thoughtfulness.

[.embedded-content-document]
--

"`Kept, through Divine aid, from the spirit of the world,`" he writes,
in reference to this period of his life,
"`I have had the prospect of a great work steadily before me, and,
under the various baptisms attendant upon a state of preparation for it,
I have been instructively reminded of the steps necessary
to the building of a great house;
the foundation must be dug deep, for a great weight is to come upon it.
Under all these exercises the Lord has been good to me,
and has upheld me by the right hand of his power, enabling me, in faith and confidence,
to resign myself and my all to his requirings, and the guidance of his Spirit.
But, while my mind has been thus concerned for distant nations,
I have been also introduced into many exercises on account of our Society in these parts.
There is a cloud impending over us; a spirit of infidelity is insidiously spreading;
therefore I have, at times, earnestly laboured,
both in our meetings for Ministers and Elders, and in other meetings,
and with my dear friends in private also,
that by walking in more consistency with our Christian profession,
in our respective stations, we may avert the impending calamity,
which at seasons appears to me to be coming, like an overflowing scourge,
over our Society.`"

--

The sorrowful events of succeeding years, which are now matter of well-known history,
have sufficiently justified these serious apprehensions,
and painfully illustrate the deplorable consequences of a departure from the
simple "`word of the truth of the Gospel,`" or any violation of the plain testimony
of "`the Scriptures,`" which "`cannot be broken,`" in any direction,
with impunity.
But while, with a mind deeply imbued with the influences of the Holy Spirit,
and remarkably prepared to sympathize with the Church in all her vicissitudes,
Stephen Grellet was thus enabled to "`speak the truth in love`" and faithfully
to labour for the preservation of his brethren from foreseen danger,
the time drew near, when, in pursuance of his religious duty,
he had again to leave all for the Gospel`'s sake.

In the early summer of 1811, he entered upon a second visit to Europe,
and thus adverts to it in his Autobiography:

[.embedded-content-document]
--

Since my return from my religious visit to France,
I have been under almost continual pressure of mental exercise
in the prospect that I should soon have to return to Europe,
to labour more extensively among those nations,
in the work of the Gospel of our holy Redeemer.
I endeavoured to keep my mind very single to my blessed
Lord and the leadings of his Spirit,
and,
it having appeared to me last winter that the time had come
for me to prepare to enter upon this important service,
I accordingly settled my outward concerns,
and submitted my religious prospect to the serious consideration
and judgment of the Friends of my Monthly Meeting,
who gave me their certificate of tender sympathy and near unity.
The Quarterly and Yearly Meeting did likewise, and soon after this,
on the 23rd of the Fifth month, 1811, on the first day of the week,
after a solemn meeting, I went on board the ship Orbit, Captain Bool,
bound for Liverpool.
My dear wife and I were strengthened to part with one another,
under a solemn covering of the Lord`'s presence,
and enabled to resign ourselves and one another to his Divine guidance and safe protection.
O Lord! preserve your servant in the way in which he goes,
into which you hast called him, so that,
by keeping an eye single to your holy directions, he may faithfully follow you,
and do the work you hast assigned him.

--

The voyage was a favourable one.
Many passengers were on board,
some of whom were "`light and noisy,`" but Stephen Grellet
had "`the comfort of the company of John Burlingham,
a valuable Friend from Worcester, England.`"
He remarks:

[.embedded-content-document]
--

The 5th of Sixth month.
I was taken down with sea sickness soon after coming on board.
It is indeed a deadly feeling; but, what is the most trying,
is the conduct of some of our fellow-passengers,
who spend most of their time in drinking and rioting.

17th. These two last First-days I have had meetings with my fellow-passengers,
and such of the ship`'s crew as could be spared from duty.
Some of them were tendered.
I feel for the poor youths; they are like the prancing horse in the wilderness;
their conduct is however respectful towards me.
In the private opportunities I take with them, they manifest some sensibility,
and I hope some of the religious impressions made on them may continue.

21st. We are now in the Irish Channel, having been favoured, thus far,
with a good passage.
The prospect of land in sight so draws the attention of
my ship-mates that I have sat down alone in the cabin,
to wait upon the Lord.
With grateful acknowledgments I praise him; for I have not waited on him in vain.
He has been near me day by day, especially during my silent,
secret prostrations of soul before him; he has frequently contrited my heart.

--

Stephen Grellet arrived at Liverpool the day after the preceding entry in his journal,
the 22nd of the Sixth month, 1811, and he thus continues:

[.embedded-content-document]
--

I remained in Liverpool till the 3rd of Eighth month,
having sundry meetings with Friends in that large commercial place,
and several also among various classes of the inhabitants.
One of these was with the Methodists, in their large house,
among whom I was much engaged in the Gospel of Christ,
and many of us were baptized together by the one Spirit.
I had also a meeting in the Poor-house; about a thousand of its inmates were present.
I felt very tenderly for them.
Many had seen better days, but owing to the pressure of the times,
they have been under the necessity of coming here.
I had also a religious opportunity in that place, with about two hundred children.
Some of them manifested tender religious feelings.

During the time I have been at Liverpool, Paul Cuffee, a black man,
owner and master of a vessel, has come into port,
from Sierra Leone on the coast of Africa.
He is a member of our Society, and resides in New England.
The whole of his crew are black also.
This, together with the cleanliness of his vessel,
and the excellent order prevailing on board, has excited very general attention.
It has, I believe,
opened the minds of many in tender feelings towards the poor suffering Africans, who,
they see, are men like themselves, capable of becoming, like Paul Cuffee,
valuable and useful members both of civil and religious Society.

--

The Slave Trade had indeed, at this time, been for some years abolished,
both by England and the United States; but it was still carried on,
with all its cruelties and horrors, by the subjects of several other powers.
In countries where the importation of slaves from Africa was no longer allowed,
the desolating and widely extended effects of the internal slave trade
were still perpetuating the complicated miseries of this dreadful traffic.
Slavery itself still continued to prevail to an undiminished extent,
and with all the variety and enormity of the evils
and calamities inseparable from the inhuman system;
while the notion of the inferiority of the African race,
and the prejudice against colour,
had scarcely begun to give place to more enlightened views,
or to yield to the righteous influence of Christian principle.
Though some check had been given to the iniquitous
trade in the blood and bones of our fellow-men,
direct from Africa, our coloured brethren, for whom Christ died,
were still a down-trodden people everywhere, whose sufferings no tongue could tell;
and much remained, and still does remain to be done,
before this foul disgrace can be removed from the Christian name.
Stephen Grellet was one of those who deeply felt for the cause of the oppressed--"`the
wrongs of Africa;`" he heartily united with the friends of truth,
and justice, and humanity, in their efforts to do away the vices of a sinful,
and to lessen the miseries of a suffering world.
He delighted in the well-being of every son of Africa,
and the simple circumstance of the arrival of Paul Cuffee with his coloured crew,
in the port of Liverpool,
could not fail to touch a chord to which his heart must vibrate;
he welcomed him as "`a man and a Christian.`"
How many years, alas! have since elapsed,
and we are still "`guilty concerning our brother.`"

Leaving Liverpool on the 3rd of Eighth month, Stephen Grellet proceeded northward,
and thus continues his record:

[.embedded-content-document]
--

My mind has been under great concern that I might have a clear sense of the right way
in which I am now to proceed on this important embassy of my great Lord and Master;
for I believe that there is a right time and place for every day`'s work,
and my earnest desire is, that, day by day,
I may be thus found engaged in serving the Lord.
He has condescended now to renew with clearness the impressions I had while in America,
that the northern parts of this nation were to be
the beginning of my Gospel labours in this land.
Accordingly, feeling clear, for the present, from further services in Liverpool,
and accompanied by my valuable friend Abraham Binns,
who proposes to stay a few days with me, we came by Preston and Lancaster to Wyresdale,
on the black moors.
That meeting was attended mostly by shepherds,
and I came back to Lancaster in time to have a meeting
in the evening with the inhabitants of that place.
At all these places, the Lord, my blessed Helper,
strengthened me by his grace to do the work assigned me.

The following days I attended meetings at Yealand, Wray, Bentham, Long Preston,
and Kendal.
I am kept, day by day, in a state of great lowness and poverty; yet in many families,
as well as in meetings, I am clothed with a little strength,
both to visit the seed of Christ, and to minister to it.
As I pass through the country, my mind is frequently brought under solemn contemplation,
while beholding the abodes of some of our primitive Friends,
valiant for the truth and testimony of Jesus;
and the places also where many of them suffered greatly for their
faithfulness in the support of their Christian principles.
Many of their descendants, both in America and in this land, now trample under foot,
or set at naught these principles that were so dear to their ancestors.
Riches and grandeur have brought dimness over many; yet there is here a precious seed,
and my soul magnifies the Lord, in that I am permitted to visit it,
and to suffer with it.

I had many meetings among Friends and others in the Dales of Yorkshire and Westmoreland;
on the way I went to Swarthmore.
The present meetinghouse was built by G. Fox`'s directions, and at his expense,
on a piece of ground which is tithe-free.
By his will, he left directions that there should be a room in it,
prepared for the use of Friends travelling in the service of the Gospel of Christ,
that they might have a place to lodge in.
He also directed that his bedstead, a small table, two of his chairs, etc.,
should be placed in it for the use of the weary traveller.
By these minute instructions we may see the tenderness of that dear servant of Christ,
who had undergone so many sufferings and privations for the testimony of Jesus.
We also see the simplicity of manners and of living in those days,
when the Christian`'s life was one of self-denial,
consistently with the doctrines of our blessed Saviour.
The posts of the bedstead, and the chairs, are yet in the chamber, and I saw,
at a Friend`'s house, his large Bible,
which used to be fastened with a chain to the rail of the minister`'s gallery,
not as a relic, or from superstitious ideas, but for a better purpose.
In former days,
Friends were at times interrupted in the course of their religious meetings or ministry,
by opposers who sometimes made false quotations from the Scriptures,
or denied the correct quotations that Friends had made;
there was therefore a propriety in having a Bible at hand,
that the matter might be properly examined:
for Friends have uniformly maintained that they have
neither principle nor doctrine contrary to the Scriptures,
and that if any man, pretending to be under the influence of the Divine Spirit,
asserts anything contrary to the plain testimony of the Scriptures,
he is under a delusion.
Thus we find that Samuel Bownas, and others of our ancient Friends,
sometimes had to take the Bible out of their pocket, while preaching to the people, that,
by referring to chapter and verse,
they might show to the assembly that they were wrongfully
charged with having made false quotations.
I had to do the same several times in France while
publicly engaged in preaching the Gospel.

From Westmoreland I proceeded to attend all the meetings in Cumberland,
having also some among the people at large, in places where there are no Friends.
My services were laborious, having generally two meetings a day; but,
blessed forever be He who has promised, "`My grace is sufficient for you.`"
I have found it so under all my soul`'s probations; the Lord, my gracious Helper,
has been with me; none of his promises have failed.
At that time, in addition to the daily exercises attending my Gospel services,
the prospect of visiting Scotland was with weight upon me,
which greatly bowed me before the Lord,
and I believe it was a necessary preparation for that work.

We left Carlisle, where I had two meetings, the 8th of Ninth month.
John Ross, a valuable Elder in the Church, and William,
the son of my late much valued friend, John Hall,
with whom I was closely united in Gospel fellowship,
in a religious visit through the United States of America,
joined me at Broughton in Cumberland.
We proceeded by Kirklinton, Solport, Longtown, etc., to Kelso.
In most of these places there are no members of our Society,
and in some of them meetings have been very seldom held by Friends.
It is thought that there has not been one at Jedburgh since Samuel Bownas was there,
about a century ago,
when he was imprisoned for preaching to the people at the market cross.
I have had no personal abuse, but inward bonds and afflictions await me wherever I come,
and yet the Lord is pleased to open a wide door for service before me.
The meetings are crowded;
no place has yet been sufficiently large to hold the people that have come.
Amidst such crowds, out of doors, individuals, in some places,
have been disposed to cause a disturbance; but I may humbly say with G. Fox, formerly,
"`The Lord`'s power is over all.`"
At Lockerby the Priest interrupted us; but he was soon silenced.
His hearers were ashamed of him, and we had a solid, good meeting.
At Jedburgh, the crowd was so great, that for a while,
it seemed as if the prospect of a religious opportunity with the people must be given up;
but, through Divine goodness and power, all was brought into stillness,
and it was one of the best meetings I have had.

There are many French prisoners of war, on their parole, in most of these towns.
They are mostly officers, and very generally attend the meetings.
In several places I have addressed them in their own language,
towards the close of the meetings.
Seriousness appears among some of them, and many visit me at my inn.
I feel much for them.
May these opportunities for serious reflection be improved by them,
and together with the consideration of the sufferings and
wonderful escapes that many have experienced in Spain,
where most of them were made prisoners,
be so blessed to them as to bring them to the feet of Jesus,
and into obedience to his truth!
By their own acknowledgment, their present bonds are very light,
and attended with many comforts, compared with their heavy sufferings in Spain.

At Berwick the meeting was very large,
attended by the principal inhabitants of the place,
and a great number of British officers, a large garrison being kept there.
At Dunbar the meeting was held in the Methodist meetinghouse;
and that at Edinburgh was attended by a number of other people besides Friends.
Except a few members at Hawick,
this is the first meeting I have had with Friends since I have come into Scotland;
it was a solemn one;
yet I could not be relieved without having a public meeting in the evening.
This was a precious season,
and afforded a considerable degree of relief to my much exercised mind,
respecting that part of the town where the notice was extended.

I feel much for the inhabitants of this large city,
where a large profession of religion is made, and feel like a poor stripling among them.
Under this humbling view of myself,
I have need often to recur to the ground of my engaging
in this great and solemn work of an ambassador for Christ,
among these nations.
Had I wings at my command, in my weakness I might be tempted to take my flight,
or foolishly to act like Jonah; but thanks to my gracious and merciful Helper,
who continues to be a refuge for the poor and needy;
a strong tower is His holy name to all who trust in Him.
I have been instructed by the zeal manifested by a soldier, who,
hearing of the meeting I proposed to have last evening, walked seven miles to it,
through very bad roads, though he had been on duty the night preceding,
and he had to be again at his post early this morning;
he is in a preciously visited state of mind.

Edinburgh, 28th of Ninth month.
I continue in this city and its neighbourhood, under Gospel bonds.
I have had one or two meetings every day but one, since I came here.
I have visited Perth, Leith, Musselburgh, Dalkeith, etc., etc.
Under much poverty of spirit, deep baptisms have been my daily portion,
yet many of those meetings have been attended with a holy solemnity.

My mind being, for the present, released from further services in Edinburgh,
after a large and very solemn meeting on First-day morning,
I went over the Frith to Kirkaldy, where a meeting was appointed for me that evening.
Kirkaldy is a large village about one mile in length,
and another of the same size joins it.
The meeting had been appointed in the Courthouse,
and when I came to it I found it so crowded that I could hardly enter;
the place was so much heated by the breath of the
people that the candles were melting in the sockets,
and a very large number of persons were standing in the street; they stood very quietly,
and my mind was drawn towards them with strong feelings of Gospel love;
but I did not see how a meeting could be held among a crowd
thus situated in the Courthouse and in the street,
when, the expressions escaping my lips,
"`O that we had a place capable of accommodating
this multitude!`" a young woman who heard me,
said, "`O Sir, I do not doubt that we may have the church.`"
Without waiting my answer, she immediately passed away through the crowd,
and in a few minutes,
we were informed that in half an hour "`the church`" should be ready.
I therefore retired to my inn; but I had not been there fifteen minutes,
when I was told that the people were all collected in "`the church.`"
At the time the young woman had gone to see if it could be obtained,
the minister was himself officiating in it, but,
instead of continuing to the end of his service, he immediately wound up.
They had put fresh lights in the chandeliers, and his hearers remained in the house;
these, together with the people who came in from the Courthouse and the street,
made a very large congregation, whom I found sitting in great stillness.
The canopy of the Divine presence was over us in
such a manner that a holy solemnity was felt;
the streams of the everlasting Gospel flowed towards the people,
and the minds of many were contrited before the Lord;
praises and thanksgivings were ascribed to him, whose is the work, and the power,
and the glory.

The following day I had another very solemn meeting at Cupar.
It was attended by many of the French officers, whom, towards the close of the meeting,
I addressed in French, as only few of them understood English.
The following days I had meetings at Anstruther, St. Andrews, Dundee, Arbroath, Montrose,
and Stonehaven.
All these meetings were largely attended,
and eminently owned by the Lord`'s presence and power,
especially Arbroath and Stonehaven.
Several clergymen, at the conclusion,
confessed to the truths of the glorious Gospel of Christ,
that were proclaimed among them.
There is a seeking, visited seed in those parts.
Some appeared convinced of the Truth; may they also be converted to it!

Aberdeen, 8th of Tenth month.
I feel myself in this place of high religious profession, as in a prison-house,
encircled with darkness;
my way is entirely closed up from having a meeting among the inhabitants,
over whom I mourn silently;
and I find no place for the rest and relief of my exercised spirit.
I have had however a religious opportunity with the few members of our Society,
and professors with us, who have a meeting in this city.
I sat among them in much bowedness and prostration of soul before God,
and have offered prayers and intercessions at the sacred footstool,
on behalf of the Lord`'s tribulated seed wherever they be on the face of the earth.

9th. Went to Kinmuck, where I had a meeting with Friends and others.
I was thankful in the evidence that the Lord has among them a little remnant,
like a people poor and afflicted, but trusting in him.
I had a word of comfort to impart to them.
This is the furthest meeting to the north, that we have in our Society.

As my mind was drawn forth in the love of the Gospel towards the people at large,
I have found it my place to proceed towards Inverness,
having meetings at nearly every town and large village on that coast;
some of them have been seasons of Divine favour.
During these services in Scotland,
the Lord has seen fit to keep me under close discipline.
Day by day he has ordered my steps; he knows how frail I am and how little I can bear;
therefore, only one day`'s work has been set before me at once.
Frequently, when I have risen in the morning, I did not know where I should go that day.
Nevertheless, it has been so ordered, that every day I have had meetings,
generally in the evening.
The place I was to proceed to, being made manifest in the morning,
one of the Friends with me, being on horseback, rode to it,
and had preparations made for a meeting, mostly in one of their places of worship,
or Courthouses.
My companion and I, on coming to the place afterwards,
gave further assistance in diffusing printed notices of the meeting,
which we carried with us for the purpose.
At Inverness, I felt my mind released from further service in the north of Scotland,
and we came back southward over the Highlands,
having meetings in many of the towns and villages among the Highlanders.
I found some tender spirits among them,
and some of those meetings were particularly owned
by the Lord`'s presence and baptizing power.
I had also some consolation in several visits that I paid
to the cottagers in that wild and mountainous country.
I was in very few families where I did not find they could all read;
and most of them had the New Testament, printed in their own language.

I came to Glasgow the 26th of Tenth month, and had several meetings there;
a very large and satisfactory one in the Traders`' Hall.
Feeling much for the poor weavers in the villages and towns thereabouts,
I had some baptizing meetings in several places.
I found individuals in most of them who have known
the Lord Jesus Christ as their Saviour and teacher,
and their only hope of glory.
Some of them sit together in silence,
feeling after the motions and quickenings of the Divine Spirit,
to enable them to worship the Father of spirits, in spirit and in truth.

I proceeded after that to Greenock and other towns till I came to Port Patrick;
the Lord very graciously making way for me to preach
the unsearchable riches of the Gospel of Christ.
I found through Scotland, in various places,
some strongly entrenched in Calvinistic notions,
among whom I had deep exercises and close labours.
I had frequently to enlarge among them, on the universality of the love of God,
through Jesus Christ; his meritorious sacrifice for sin, yea,
for the sins of the whole world;
that these are faithful sayings worthy of all acceptation,
that Jesus Christ came into the world to save sinners,
and is the propitiation for the sins of the whole world,
that he would have all men come to the knowledge of the Truth and be saved; that,
in order that we might know those deep things of God,
which none can know but by the Spirit of God,
he has bestowed the visitations of his Spirit upon all; the Grace of God,
which brings salvation, having appeared to all, teaching us, etc., etc.
Thus I often earnestly pressed upon them the necessity to pay close attention to the
in-speaking word of God in their hearts,--to obey the teachings of the Divine Spirit,
and to seek to have fulfilled in them the very precious Scripture promises,
"`they shall be all taught of God;`" and the words of Christ,
"`every one therefore that has heard and learned of the Father, comes unto me.`"
By so doing they would understandingly read the Scriptures,
and escape being of the number of those, who search the Scriptures,
which testify of Christ, but will not come to him, that they might have life.

--
