== Chapter XV.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Religious Visit to Ireland

On the termination of his religious services in Scotland,
Stephen Grellet felt "`drawn in much Christian love
and interest`" towards Friends and others in Ireland,
and at once entered upon a general visit to that island.
The following particulars of his Gospel labours in the different provinces are preserved:

[.embedded-content-document]
--

The 17th of Eleventh month, 1811.
Accompanied by my valued friend, John Robinson of Glasgow, and William Hall,
we left for Donaghadee in Ireland.
We had a short passage, and came pretty directly to Mile Cross,
where there is a small meeting of Friends, which we attended in the evening.
Proceeding to Belfast, I was at meeting there in silence, among Friends;
but was much enlarged in a meeting in the evening with the inhabitants.
I went from there to Antrim and Lisburn.
At a public meeting in the latter place,
I was brought under very deep exercise and oppression
by the feeling of a spirit of infidelity.
O what darkness it brings!
But sinking deep before the Lord,
I was brought to feel the quickening influences of the Spirit of life in Christ Jesus,
and enabled to minister to that large congregation,
exalting the name and offices of Christ, who delivers the believers in him,
from the power of darkness, and gives them redemption through his blood,
even the forgiveness of sins; who is the image of the invisible God,
by whom all things were created, and who is before all things,
who is also the Head of the body--the Church;
who has not only given himself for the Church, but also bestows excellent gifts upon her.
He has given some apostles, and some prophets, and some evangelists,
and some pastors and teachers, for the perfecting of the saints,
for the work of the ministry, for the edifying of the body of Christ.
Then I proceeded to set forth the nature and excellency
of the ministry of the Gospel of Christ,
and what are the qualifications requisite for such a sacred office, which,
none are to take upon themselves, but such as are called of the Lord, as was Aaron.
There was great solemnity over the meeting, under which it concluded.
I heard afterwards, that about twelve clergymen were present.
There was then an assembly of the clergy at Lisburn, and these had come to the meeting.
There were some also present who were once members and ministers of our Society,
and a few years past went out with Hannah Barnard into infidelity.

I then had meetings with Friends in the province of Ulster,
and came to Lurgan to attend that Quarterly Meeting.
Owing to the troubles occasioned by the anti-christian
spirit which had extensively prevailed in that province,
most of the Ministers and Elders in those parts had
withdrawn from Christian fellowship with us,
and the Quarterly Meeting for Ministers and Elders, had been suspended twelve years.
It was now held again.
Friends in those stations are very few, but they appear to be a valuable remnant.
It was a solemn, contriting meeting; some of us were forcibly reminded of Nehemiah, who,
after his return from the long Babylonish captivity,
went around Jerusalem during the night,
to view the state of devastation to which it was reduced.
We had present with us several valuable Friends appointed
by the Yearly Meeting of Ministers and Elders,
to attend the re-opening of this select Quarterly Meeting.
The meeting on First-day morning was to me a suffering one,
being attended by some of those who have brought reproach on the Christian name.
In the evening meeting Truth was exalted and reigned over all;
blessed be the name of the Lord, whose works do praise him!
Ann Burgess, from England, on a religious visit to this nation,
also bore her testimony to the exaltation of Christ, and his redeeming power.
The Quarterly Meeting was attended with deep exercise of spirit,
and the business thereof was conducted to satisfaction.
The next day there was a large public meeting,
when the name of the Lord our Saviour was exalted.

I then went towards Dublin, having meetings on the way at Rich-hill, Grange, Charlemont,
Cootehill, etc.
I reached Dublin in time to be at their Monthly Meeting.
Bodily indisposition detained me in the house a few days,
being a good deal worn by the continued exertions
I have had to make since my arrival in England.

I left Dublin on the 14th for Rathangan, where I had two meetings, the next First-day;
both were proving seasons, as also that next-day at Edenderry.
The three succeeding days I was at Mountmellick, attending several meetings,
at the last of which the Gospel spring was opened in a refreshing manner,
to the contriting of many present.
The joyful prospect also was set before me,
that if the present apparent declension of my health
was to lead to the dissolution of my outward man,
before the services that I have apprehended the Lord has called me to, in these nations,
were accomplished,
he would graciously accept the free and unreserved
offering up of myself and my all to him,
and receive me, whenever he was pleased to cut the slender thread of my life,
into his kingdom, with his redeemed ones;
faith also was renewed that if it was his Divine will that
I should perform the whole of the work now before me,
with those further services in his Gospel which, at seasons,
he has given me to see afar off, as from Mount Pisgah,
he is all sufficient to qualify and strengthen his poor, unworthy servant for all.

The next places I visited and had meetings at, were Mountrath, Knock, and Roscrea.
At the last place the soldiers from the barracks, with their officers,
came very generally to an appointed meeting.
The next meeting was at Ballitore.
O the agony that I endured there!
A close, searching testimony was given me to bear among them.
O Lord! you hast seen the depth of my distress, and in your mercy and power,
you hast magnified your name.
A fig-leaf covering cannot hide from your presence.
At the Quarterly Meeting at Carlow close exercise attended me.
My mind however obtained a little relief at a public meeting,
held on the evening following the Quarterly Meeting.

1st of First month, 1812.
At Kilconner, and in the evening at Newtown Barry.
This was a very precious meeting, and was attended by many of the Roman Catholics.
The Gospel dropped down like dew upon the tender grass.
Many minds were reached, and tears were shed.

On my way to Waterford, I had meetings at Ballintore, Cooladine, Enniscorthy, Wexford,
and Ross.
Some of these were solemn, baptizing seasons.
Many of the soldiers and Roman Catholics attended, some of whom had been threatened,
if they went, with having to do penance by going round their church on their bare knees;
but after meeting, they told Friends, that for the privilege of being at such meetings,
they would be willing to go round on their knees ten times instead of once.
The meetings at Waterford were both solemn seasons,
and those held at Youghal were memorable opportunities.
O how great are the Lord`'s goodness and tender mercies!

I came to Cork on the 15th, under great weight on my spirit,
being sensible that bonds and afflictions awaited me in that city.

--

Under the pressure of much religious exercise,
it was "`a great comfort to Stephen Grellet here again to meet with his dear friend,
Ann Burgess (afterwards Jones), to whom he felt nearly united in Gospel fellowship.`"
They attended the Monthly and Quarterly Meetings together at Cork,
and also appointed meetings for the inhabitants of Kinsale and Bandon.
From the latter place they returned to Cork, to attend a funeral,
"`where both he and A. B. were engaged to minister
to a large company collected on the solemn occasion,
in the burial-ground;`" and,
having "`both felt a religious concern laid upon
them`" to visit the Friends of the city of Cork,
in their families,
"`in submission to the Lord`'s requirings,`" they united in this engagement.
Stephen Grellet remarks respecting it:

[.embedded-content-document]
--

We diligently pursued that service, during the whole of the following week,
except attending meetings in course.
Keeping close to the Lord`'s guidance,
ability was given to perform the work to some relief to my tribulated soul, and I hope,
to the comfort and encouragement of some of the visited.
We have had also a meeting for those who have been disowned by our Society.
The Lord, by his Spirit of wisdom and counsel,
enabled us to discharge this debt of Gospel love and good-will towards them,
with much more openness, and relief of mind, than could have been expected.
We had a very satisfactory meeting also with the young people.
Bless the Lord, O my soul, who has safely led you,
and supported you under these deep baptisms and exercises.

From Cork I went to Fermoy,
where I had a quiet and good meeting among the Roman Catholics;
no Friend resides in the place.
Then I had a few other meetings among that people, on my return to Waterford,
where I stayed a few days,
visiting Friends in their families and having some public service.
I found there some valuable Friends,
and tenderly susceptible young people;--the refreshings
of the Lord`'s presence comforted us together.
Several beloved friends accompanying me, I went to Kilkenny,
where I had a large meeting in the City Hall.
The remains of the popish Bishop, who was lately deceased,
were exposed in state to public view, which had brought many people from the country;
some of these came to the meeting, and, instigated by their priests,
very soon began to be abusive; but the Mayor of the place, who,
with some of his officers, had also come to the meeting, ordered silence among them,
with threats of immediate punishment to anything who should offer disturbance,
and the meeting was held in quietness and solemnity.
The meetings at Clonmel and Carrick, both with Friends and others,
were particularly owned by the good Master.
Blessed be the Lord, he commands the winds and the waves, and they obey him.
I frequently feel much for the Roman Catholics; there are some tender minds among them,
who have sensibly felt the influence of the Spirit of God, operating upon them.

At Limerick, I had close service; besides meetings with Friends,
I had several with the inhabitants in separate parts of the town,
particularly among the poor.
Oh, what misery and wretchedness I have beheld there, as in most parts of this nation!
My heart is made sad indeed, under the sense of the bodily suffering,
and of the darkness and depravity of many of the inhabitants.

On my way to Moate, I had several meetings, in places where no Friends reside.
They were generally quiet, but at some of them I narrowly escaped being severely wounded,
by stones thrown at me from out of doors,
while engaged in proclaiming the truths of the glorious Gospel of Christ among them.
Once, as I was going out of the meetinghouse, in the evening, in a dark street,
a large stone passed so near my head, as to cause my hat to turn round, but,
blessed be the Lord!
I have been delivered, his Divine Grace assisting, from every harm, and have repeatedly,
on these occasions, felt this short prayer to arise in my heart, "`Father, forgive them,
they know not what they do.`"
At many meetings, large numbers of the English soldiers have attended,
and generally much seriousness has been manifested among them; but, in a few places,
I have had no small labour in preventing some of them from doing mischief; for,
while evil-minded persons out of doors, threw stones or dirt at me,
they would go out to disperse the rude people; being armed, I feared the consequences,
and expostulated with them,
showing that retaliation would be inconsistent with the occasion for which we were met,
as servants of the Lord Jesus Christ, whose precepts we must endeavour to follow,
and love all men as he has loved us.
The Gospel of peace,
and the love of God through Jesus Christ were sweetly and powerfully preached,
and meetings which threatened to be disturbed,
have been held and concluded with the greater solemnity.
Surely this is the Lord`'s doing; all praise and glory be unto him forever.

From Moate I went to Athlone, and from there to Connaught,
and into Leinster province again.
In Connaught I had meetings in places where Friends had not been before.
Notwithstanding the persuasions of the priests, in many places, the people would come,
and seriously attend to the Christian testimony given me to bear among them,
to turn them from darkness to Christ the true light,
that enlightens every man that comes into the world, by whom alone we have redemption,
and without whom none can come to the Father.

I reached Lisburn in time to attend their Quarterly Meeting.
From there I went to Dublin,
where I continued some time visiting Friends in their families,
and having several meetings among them, and other people.
Suffering humanity has a strong claim upon my feelings,
and led me into many of the abodes of wretchedness and misery, poorhouses, prisons, etc.
I suffered deeply among them, but found, in some instances,
that the door for preaching the Gospel is open among the poor.
I had a memorable meeting among the seamen.
My mind was under considerable exercise towards them,
but I did not know that they were then in so peculiar a position.
On imparting my concern to Friends, after the close of one of their meetings,
they cordially united in it; when a dear friend stated,
that though he felt great unity with the concern,
he did not see how it could be accomplished;
for orders from the Admiralty in London had arrived,
to impress as many of the seamen as possible, and that in consequence,
not one was now to be seen, either on board the vessels or on the quays;
adding that he would go out immediately and see what could be done.
It was then near twelve o`'clock. The Friend went directly to the Admiral of the Port,
with whom he was acquainted,
and told him of the religious concern I had towards the seamen.
The Admiral answered, "`It is a hard thing that you ask me; here,
read what dispatches I have today from London;
the impressing of men is now going on in the city part of London,
heretofore exempt from it, but,`" added he,
"`if your friend can have his meeting this evening,
I give you my word of honour that no impressment shall be made to-night.`"
Now, that was the very time I had it on my mind to have the meeting.
Friends, therefore, had public notices printed, in which,
with the approbation of the Admiral,
his promise that there should be no impressment that night, was inserted.

The notices were distributed at the houses seamen are known to frequent,
and where they had concealed themselves.
The ground-floor of a large warehouse was prepared and seated for the occasion.
The meeting was appointed for seven in the evening, and,
contrary to the apprehension of some, the sailors turned out in large numbers,
so as to crowd the place.
After the meeting had been settled in much stillness, there was a bustle near the door,
towards which the attention of the sailors was directed with anxiety.
It was the Admiral accompanied by some of his officers.
Fears were entertained that he was not true to his promise;
but he marched quietly through the seamen, came to the further end, towards me,
and took his seat in front of them,
as if to proclaim "`you see me in your hands before you, you need not fear.`"
We had a solemn meeting; many of those weather-beaten faces were tendered, even to tears.
When the meeting concluded, the Admiral, under much feeling and religious tenderness,
expressed his sense of gratitude for the Lord`'s favour extended that evening,
and his hope that many of them would be lastingly benefited by this religious opportunity.
The meeting separated under that solemnity, and agreeably to the promise of the Admiral,
no impressment took place that night in Dublin.
But the succeeding days, throughout England and Ireland, it continued very rigid,
this being the time when France threatened an invasion.

3rd of Fourth month.
My mind now feeling clear from further services for the present in Ireland,
and Wales being presented with much clearness,
as the next field for Gospel labour into which I am to enter,
I have taken my passage for Holyhead.
We have had a precious, solemn meeting with Friends of Dublin, this morning.
With reverent gratitude I have to acknowledge to my dear Master`'s
love and tender mercy towards his poor unworthy servant.
He has been my help and strength every way.

For a time after my arrival in Ireland, my health was feeble,
so as to cause solicitude in the minds of my friends; but it is stronger at present,
though since the time of my coming to this nation,
I have had ten meetings more than one a day,
visited Friends in their families in several places,
and have travelled upwards of two thousand miles.
The Lord, by his Spirit, has graciously directed my steps,
delivered me from mischief intended by evil-designing men,
and although kept very poor from day to day,
he has clothed his servant with ability to perform the daily work assigned.
"`Bless the Lord, O my soul, and all that is within me bless his holy name!`"

--
