== Chapter XVII.

Second Visit to Europe

Lancashire--Yorkshire--Midland Counties--Essex

From Bradford Stephen Grellet passed on to Liverpool,
where he arrived on the 5th of Tenth month.
"`Again much refreshed every way, at the hospitable house of his dear and kind friends,
Isaac and Susannah Hadwen,`" he proceeds with his journal:

I continued a few days there and in the neighbourhood, having various services,
and attending their Monthly and Quarterly Meetings.
Dear Isaac Hadwen having concluded to accompany me awhile, we came to West Houghton.
It is a meeting composed of persons mostly poor in this world, and who,
on the ground of convincement, have of late become members of our Society.
Some show that they are not only convinced of the Truth,
but also converted by the power of it,
so as to walk as servants of the Lord Jesus Christ.
This second step, conversion after conviction, is a very important one,
not enough regarded by many, who, after having received the knowledge of the Truth,
remain strangers to the efficacious power of it on those who submit to it.
In the evening I had a very large meeting at Bolton,
in one of the dissenters`' meetinghouses.
I went to it in great poverty.
O how insignificant did I feel myself, even less than a child; but the Lord,
my gracious Helper, revealed himself to be a God near at hand.
He enabled me to preach the unsearchable riches of Christ,
and to invite them to come to be living witnesses to his
name--Jesus the Saviour!--by experiencing redemption,
through living faith in him.

Through the populous parts of Lancashire and Yorkshire
I had extensive services among the people at large,
especially the weavers,
for whose accommodation many meetings were held in spacious meetinghouses of the dissenters.
The distress generally prevailing in these parts, for lack of employment,
and on account of the scarcity of food, draws forth my very great sympathy.
The minds of some are made tender under their sufferings,
while others are driven to commit excesses,
to the great disturbance of their peaceable neighbours.

I have been much among the Kilhamiies, who have numerous congregations;
they are so named from Alexander Kilham,
who was a renowned preacher among the Methodists,
but coming to see further than his brethren, both as to church discipline,
and the spirituality of Divine worship, he separated from them a few years since.
His widow, Hannah Kilham, has become a member of our Society,
and a very precious dispensation of the Gospel is committed to her.
I have had very satisfactory meetings among those people.

At Chesterfield, besides having meetings with Friends, and with the inhabitants,
I had one with about two hundred French prisoners on parole.
One of them, an interesting young man, came afterwards to see me;
he loves the Truth as far as he has come to the knowledge of it.

Through these counties, as well as others, I frequently met with French prisoners,
chiefly officers; the men, both soldiers and sailors, being confined in large prisons.
I have had the comfort of finding some in a tender state of mind,
and several of them have become public professors of Christianity,
being convinced also of the errors of popery, war, etc.
At Lichfield, where a large number of these, my countrymen, are stationed,
many of them attended the meeting held in the large Town Hall.
It was a very solemn season.
Several of these prisoners are of high rank, generals, colonels, etc.
Three of the generals, one of whom had been at college, in France,
with a first-cousin of mine, came to see me after meeting, and expressed,
on behalf of the other officers,
their gratitude for the opportunity given them to become acquainted with some
of those excellent Christian doctrines to which they had been so great strangers.
May the Lord bless the days of their captivity!
I sometimes admire the ways of the Lord, who thus enables me to preach, on this island,
the Gospel of peace and salvation by Christ,
to a greater number of persons of such a character as these
than I might have had an opportunity of doing in France;
and now to do it at a time when they are, for a while at least,
out of the hurry and excitement of warlike movements,
and when suffering and reflection have tended to soften many of their minds.

Though he had been several times at Birmingham,
and had had considerable service among Friends and others,
Stephen Grellet now felt himself again strongly attracted to that place,
so that "`his peace appeared to consist in returning to it,
subject to the Lord`'s direction,
whatever might be the nature of the service required at his hands.`"
Arriving there the 15th of Eleventh month, he remarks:

On my way through a small town, I thought I was required to try to have a meeting there.
A place was accordingly prepared, and public notice given through the town,
when the magistrates, one of whom was an Episcopal clergyman,
sent me orders not to have the meeting, threatening that if I did,
they would come and break it up, and cast me into prison.
I endeavoured to have my mind retired to the Lord,
to feel further after his Divine guidance; and believing it was a service required of me,
and feeling resigned to whatever sufferings I might be brought into,
for my obedience to Christ,
I sent word to the justices that I did not know of any law
by which they had authority to prevent my having the meeting,
to which the love of Christ constrained me; that therefore,
notwithstanding all due deference to them, I continued the intention to have the meeting,
at the same time sending them a respectful invitation to attend it themselves.
The clergyman replied that he was warranted to prevent me, and would do so.
The meeting, however, was held, and attended by a large number of the inhabitants.
I have seldom met with a more serious company.
It was a solemn time;
many felt the power of the Lord`'s love and mercy extended to the melting of their hearts.
No magistrate came to it, nor was any disturbance offered,
and the Lord`'s power over-ruled all to his own glory.

When I came to Birmingham,
I felt the exercise which had been upon me for a particular class of the inhabitants,
greatly increased.
I had overwhelming sorrow also, because of the horrors of the war on the Continent,
where torrents of blood flow.
I felt as if I was among drawn swords and bayonets.
Then, deeply feeling the guilt of those who are the means of putting
into the hands of the warriors the weapons of destruction,
it appeared to me that those who manufacture them are sharers in the guilt.
I felt it was the Lord`'s requiring,
that I should have a meeting with as many of these as could be convened together;
though at that time, all those artificers were in full employ,
extensive orders having been given for such weapons.
After consulting with Friends, who most feelingly entered into my exercise,
they endeavoured to their utmost to promote my object.
The large meetinghouse of the Independents, was considered the most eligible,
being also central for those I wished most particularly to see.
The minister of that congregation, a pious man,
entered so fully into my religious concern,
that he not only relinquished his usual service on First-day evening,
but also spread the notice of my meeting at the close of his own in the forenoon.
The concourse of people was very great, the house was crowded,
and many remained out of doors.
Awful and solemn was the weight that was on my mind on that occasion,
and earnest was my secret prayer that the Lord would prevent the end,
for which that multitude had been called together, from being frustrated;
the crowd in the house was so great, and those out of doors so numerous,
that I feared for the consequences.
The all-gracious and powerful God was pleased, after a while, to bring that multitude,
both in and out of doors, into silence,
and to cause a Divine solemnity to spread over us.
He gave strength and qualification through his Spirit,
to proclaim what the Christian religion is;
what should be the manner of life and conversation of the professors of it.
It leads, it calls to love and peace; it is pure and undefiled,
and enables to bring forth the fruits of the Spirit.
These were contrasted with the fruits of the flesh; and the cause of war was unfolded,
its awful and dreadful consequences--misery, wasting, and destruction.
In these are deeply concerned, not only those actually engaged in the field of carnage,
but those also who give countenance, and are in anywise auxiliary to it,
as the manufacturers of arms and engines of destruction.
I spread before them the consideration, whether a greater trust in God,
and love to him and man,
would not lead to the pursuit of a kind of business in which his blessing might be expected,
and by which his glory might be promoted; and if, as enjoined by our blessed Redeemer,
we loved one another as he loved us,
all our works and labour would not tend towards the advancing of his kingdom,
and the coming of that day,
when men shall beat their swords into plough-shares and their spears into pruning-hooks,
and they shall learn war no more, nor fan the flame of it in anywise whatever.
The meeting concluded in stillness;
the people separated in a frame of mind which gave some
evidence that the power of Truth had been felt by them.
I felt great peace after that meeting, which closed with blessing,
adoration and praise and prayers and intercessions offered at the throne of grace.

The following day I had a meeting at Dudley, after which a French female,
whose mind had been greatly tendered on the occasion,
came to me to express her gratitude in that a countryman of hers,
was thus called to preach Christ, the Saviour of men, yea,
of sinners who repent and come to him in faith.
She is a sister of the late Brissot de Warville, who, like many others,
lost his life during the French Revolution.

From Dudley, Stephen Grellet`'s steps were directed towards a part of Wales,
which he had not visited before.
After this little digression, he remarks:

I returned by Worcestershire, Northampton, Huntingdon,
and others of the Midland counties, having many meetings with Friends and others,
the Lord continuing in a remarkable manner to strengthen
for the work to which he calls me;
deep are the exercises often attending,
and in some places very close the testimony given me to deliver;
but my peace and safety consist in faithfulness to whatever the Lord requires,
whether it be to administer the word of consolation to the afflicted,
or that of reproof to the disobedient and the unruly, or at times, as is my lot,
to feed or rather starve the full among them, with silence.
The latter seems to some a very strange thing; that I should appoint meetings among them,
and then have nothing to say to them.
O could they read in my soul, they would know, that on many such occasions,
deep is my travail before the Lord, and fervent also my supplications for them.

At Northampton a meeting was appointed on a First-day evening, in Friends`' meetinghouse.
My kind friend, Isaac Hadwen, went to see if the house was properly lighted,
and though it was about half an hour to meeting-time, he found the house full,
and as many more out of doors; in the fulness of his heart happening to say,
"`what a pity that we have not a house capable to accommodate
the people,`" a young woman within hearing answered,
"`Oh, I dare say my father would take pleasure in opening his house to you;`" whereupon,
without waiting for an answer, she hastened away and soon returned,
stating that very shortly her father`'s meetinghouse would be prepared for the people.
It was the house that Dr. Philip Doddridge formerly occupied.
I found a great company collected;
not one-fifth could have got into Friends`' meetinghouse.
There was a precious, visited seed among that people;
their spirits feel near and dear to me.
The minister of the chapel and his family attended;
he appeared to be a man of a pious mind.

Passing through Cambridgeshire, and being with Friends and others, I came to Stilton,
near which are the barracks, wherein are confined about six thousand French prisoners,
mostly soldiers, who are guarded by a body of English troops.
Baneful indeed is the scourge of war;
with deep anguish of spirit I have visited this portion of my fellow-men;
my heart yearns with love towards them, who are indeed very interesting to me.
In the conversations and religious opportunities I have had with them,
many evinced sensibility, under the chastening hand that has been upon them.
Some of them have been prisoners for nine years, and many, I find,
have been brought up tenderly, even in affluence,
having been conscripts that were forcibly taken from their homes,
bands of whom I saw in France, fifty or more chained together,
dragged as sheep to the slaughter.
Some of them inquired what had brought me to this island,
and what induced me to visit them in their affliction?
On being informed of the nature of my mission, in the love of Christ to these nations,
and what has prompted me now to visit them,
and that I had it also in contemplation to go over to France to visit
our countrymen in the love that seeks the happiness and salvation of all,
they replied, "`Our souls are full of gratitude to the Lord,
who has put it into your heart thus to think of us, and feel for us.`"
I could not have them collected together, the rules of the prison not allowing it;
but I had several satisfactory opportunities among them,
in the wards where they are confined, a hundred or more together.
O that the light of the glorious Gospel may so break in upon them,
and the power of Truth so come over them,
that though their bodies should remain many more years in captivity,
their souls may be liberated from the bondage of sin and corruption.
Some of them are contented in their present bonds, under the consideration that,
were they liberated and sent back to France,
they would soon be driven again into the army,
and placed in a condition worse than the present.

After Stilton, passing pretty generally through Cambridgeshire,
with a mind greatly oppressed by the prevalence of a worldly and a pharisaical spirit,
particularly at Ely, I came to Cambridge, under a great exercise and depression of mind,
so that during the night sleep departed from me;
yet I felt it to be the Lord`'s requiring that I should have a meeting there,
and that the collegians should be particularly invited to it.
There are no Friends residing in that place,
and some of the meetings that Friends have had here lately,
have been much disturbed by some of the rude young men; but I knew the Lord could,
if it so pleased him, restrain the spirits of these, and bless to some at least,
that religious opportunity.
Thus, with a mind bowed very low, but trusting in the Lord, I went to meeting,
accompanied by several dear friends.
Many of the collegians gave their attendance, together with the inhabitants.
The house was crowded, and for a short space there was a disturbance towards the door,
but soon all this subsided, and total silence prevailed; the Lord`'s power came over us,
in a very precious manner.
Christ, the Way, the Truth, and the Life, without whom none can come unto the Father,
was preached unto them.
The ground and source of true spiritual knowledge were unfolded,
a knowledge not to be obtained by coming to colleges or universities,
but by coming to Christ and learning of him,
having ears to hear what the Spirit says unto us; for the things of God knows no man,
but by the Spirit of God; and if a man has not the Spirit of Christ to teach him,
to lead him into the Truth, to purify and sanctify him, he is none of His.
Great solemnity prevailed, under the testimony given me to bear to the Truth.
Several of the collegians spoke to us after the meeting, with Christian tenderness.
Two of them came to our inn, in the evening,
and evinced a desire to have further information respecting some important subjects,
relating to their own state.
They expected to be ordained in a few weeks,
and now they appeared to feel the importance of the subject.
Some others were urgent that I should have another meeting among them; but,
my dear Master not requiring this of me, I proceeded to Saffron Walden,
where I had appointed a meeting.
Soon after it had settled into silence,
I was not a little surprised to see the two young collegians come in.
They sat down in a reverent manner, and so continued the whole of the meeting,
which was a solemn one.
They were invited to dine at the Friend`'s house where I was.
They had felt so much after hearing that I was to have a meeting there,
that they came sixteen miles on foot, to attend it.
They appear to be under great religious concern.
I could leave them no better advice than, to press upon them,
diligently to wait on the teachings of the Spirit of Christ, and to take no step,
but such as Christ himself leads his faithful followers into, according to his word,
"`My sheep hear my voice, and they follow me, etc., etc.`"
They left us in a very tender frame of mind.

Stephen Grellet now proceeded to visit the meetings of Friends in Essex and Hertfordshire,
till on the 25th of Twelfth month, he "`once more came to Higham Lodge,
to his dear and valuable friend, William Dillwyn and family.`"
