== Chapter XVIII.

[.chapter-subtitle--blurb]
Second Visit to Europe

[.chapter-synopsis]
* Religious Engagements in London
* Visit to the West of England
* Return to London

Leaving Higham Lodge, Stephen Grellet came to London, to the house of "`his dear friends,
Joseph and Rachel Smith, his very pleasant and comfortable home in the city.`"
Here he remarks:

[.embedded-content-document]
--

I soon felt the heavy Gospel bonds awaiting me in
this metropolis to be rapidly fastening upon me.
The depth of exercise into which I was introduced,
on account of the various classes of its inhabitants, is indescribable.
Rich and poor, but especially the last, including not only those in the city at large,
and in the various poor-houses, but also the inmates of prisons,
and places where many are confined because of their various vices,
rested heavily upon me.
Many sleepless nights I passed,
as the objects of these exercises and baptisms were developed to my view,
and it was given me clearly to see that I must stand prepared to engage in whatever
line of service my great Lord and Master was pleased to require of me.
For such a purpose, I felt, he had raised me up, from a most abject state,
and had now sent me here.
The awful consequences that would attend me, should I be unfaithful and attempt,
like Jonah, to flee from the presence of the Lord,
were in an appalling manner set before me.
On the other hand, the gracious promise was renewed, that if, in simplicity of heart,
I resigned myself to the Lord`'s guidance and requirings,
without consulting with flesh and blood, he would be with me, would make way for me,
and uphold me.
Thus I was enabled again to offer myself and my all to the Lord and his service,
not in that great city only, but also to go on the European continent,
or wheresoever he might call me, or his Spirit might lead me.
Great peace and quietness I felt after this full offering was made;
yet the weight of my chain was not thereby lessened,
or the cup I was to drink rendered less bitter;
neither was my concern for the members of our own Society
decreased by what I felt for the people at large.

I had extensive services with Friends in this great city and its vicinity,
and have paid religious visits to many of their families.
I have met with close trials in the course of this engagement, which is a humiliating one.
But my mind has been comforted,
and my spirit has often been refreshed with many beloved disciples of the Lord.
In this large Quarterly Meeting I have found fathers and mothers in the Truth,
brethren and sisters in Christ, and the fellowship of the Gospel; precious children also,
dear to my best life, because the life of Christ, through the eternal Spirit,
breathes in them.
I believe there are many among those, now children,
who will become valiant for the Lord and his Truth on the earth,
and honourable in his church.
It is precious indeed to behold young minds early
submitting to the baptizing power of Truth.

Having felt deeply for the sufferings of a large
portion of the labouring class in this city,
I believed it to be my religious duty to have religious meetings among them;
great numbers are out of employment, in consequence of the stagnation of business,
caused by the desolating war which the various European
nations are waging against each other;
and the distress is greatly increased by the general
scarcity of bread throughout this country.
Many efforts are made to administer some relief to the poor sufferers.
Friends generally are active and very liberal in these deeds of benevolence.
One of them has sent to London from his own purse,
the enormous amount of seventeen thousand pounds sterling,
besides what he has bestowed for the same benevolent object, in his own neighbourhood,
and other places.
But this liberality is not confined to Friends only;
I have been delighted in hearing of the charities
bestowed by many in the various ranks of life,
according to their ability.
I am particularly struck with the self-denial evinced by many of the rich;
as the high price of bread is owing to the scarcity of corn,
to reduce the price by lessening the quantity consumed,
they have declined the use of bread in their families,
substituting rice and other articles.

The first meeting I had among the distressed was held in the Friends`' large meetinghouse,
at Devonshire House, for the weavers of Spitalfields,
where thousands of them are out of employ.
They came in such numbers that they stood in the house as close as they could crowd,
and many could not get in.
Under the apprehension that they had been called together to have bread distributed,
some of them became very noisy, so that, for a time,
it appeared as if our object of having a religious meeting would be frustrated;
but my beloved friend William Allen,
well known to them by frequently handing out bread and other kinds of provisions to them,
told the people that the meeting had been called for a religious purpose--a
meeting for Divine worship--and therefore requested them to act accordingly,
so that, through the Lord`'s favour, they might be partakers of the benefits designed.
Stillness soon prevailed over the dense crowd,
and the Lord`'s power was manifested over us.
The earnest prayers that were put up for this people were heard.
The Gospel of Christ was preached to the poor, he fed them with good things,
even the consolations of his Spirit; many of them were broken into tears,
and the solemnity and quiet was not interrupted at the conclusion.
Some of them said, "`It is a precious gift we have had this evening.`"
My beloved friend, William Forster, was my co-worker in the Gospel of Christ.

After that, I had several other meetings among the poorer class in London,
held in the parts mostly inhabited by them.
I felt deeply for their outward misery,
but no less for the deplorable state of ignorance
and demoralization into which many of them are sunk.
It seems as if I should have to be baptized for the various classes of the people,
from those who occupy the highest stations in life,
to those who are in the most abject and degraded condition,
even those that inhabit the dark regions into which vice has plunged them.
I have the tender sympathy of many dear and valuable friends,
and at seasons the very precious evidence that the dear Redeemer and Comforter,
even He who was in ancient days with his people in their afflictions, is also with me.
Bless the Lord,
O my soul! and yield yourself unreservedly to every
service and baptism that he has for you.

Feeling my mind now led towards the people of high rank,
and the nobility in the West-end of London, and my much valued and beloved friend,
Mary Dudley, one particularly qualified, having a similar prospect,
we entered together into the service, and had meetings among them.
I did not find the same degree of brokenness and
contrition of spirit that I have done among the poor;
nevertheless,
we were comforted by mingling in spirit with some
of those who love the Lord Jesus in sincerity.

My next field of religious labour was more particularly
among the young people of our own Society,
for whom I felt much, and I had several meetings with them;
very mingled were my feelings; O how precious, how near in the Gospel,
have many of these felt to me.
I had also a meeting with those who have been separated
from our Society for various causes;
it was far more numerously attended than had been anticipated,
and a much wider door was opened for religious labour in Gospel love,
than could be expected.
Many of them, I believe, received the testimony I had to bear among them,
in the love in which it was delivered.

--

Stephen Grellet had long felt much on behalf of the Jews resident in London;
and in the course of his interesting labours in the service of Truth,
a meeting was now held with them in Devonshire House Meetinghouse,
which was well attended.
In connection with this engagement, he resumes his memoranda:

[.embedded-content-document]
--

Having observed,
among the numerous boys and girls that stand at the corners of the streets,
with trifling articles for sale, many Jewish children, I inquired into it,
and found that the parents of these children frequently
give them a basket with small articles,
as pins, needles, oranges, etc., and send them away from home to get their own living;
but I was told that many of them become a prey to wicked men and women;
the boys are enticed by pickpockets, or other kind of robbers,
to assist them in their depredations, and the girls are decoyed into haunts of vice.
I felt very anxious that some measures might be devised for extricating
these poor children from the paths of vice and misery,
when, to my great consolation,
I found that the same concern had already claimed
the attention of pious and benevolent persons,
and they had opened an asylum for them.
I was much pleased in visiting it.
They were instructed in various kinds of manual labour, to fit them for business;
but above all, their religious and moral instruction was attended to,
and some of them manifested much religious sensibility.
I was particularly struck with the solemn and feeling manner with
which they repeated some Scripture passages relating to the coming,
the sufferings, death, and resurrection of the dear Redeemer, our Lord Jesus Christ.
But I found in that asylum another class of Jews which also
claimed my very tender feelings and Christian affection.
They were grown-up young people whose minds have been attracted towards Christianity,
and who were endeavouring to obtain more knowledge of it than they could do at home;
in consequence of this, some of them had endured from their parents very harsh treatment;
some had even been turned out of doors, and left in a forlorn state,
for other Jews would not receive them.
Many of these had found a peaceful retreat in that asylum,
and appeared to have minds prepared, with gratitude to the Lord,
to appreciate the favour.
Among these were some young women, children of wealthy parents.
I paid several visits to them with great satisfaction,
and felt near fellowship with those who had the superintendence of the Institution,
for the love of Christ appeared to prompt them.

After passing days and nights under deep exercise on account of the degraded
and vicious portion of the inhabitants of this great city,
I felt that I had a service towards them, but I could see no way to discharge it.
I earnestly besought the Lord that he would open a way for me,
and then spread this important concern before my dear friends in London,
Ministers and Elders.
They deliberated upon it with much feeling and care; and,
believing it was a service required by the Lord, they encouraged me,
with simplicity and faithfulness, to attend to it.
Friends`' meetinghouse, in St. Martin`'s lane,
was considered the most eligible place to hold such a meeting,
being very near to neighborhoods resorted to by pickpockets,
thieves of various descriptions, and abandoned women.
It was a very arduous task for Friends to have to send notices of the meeting to such,
but they did it faithfully.
For the accommodation of that class of people,
many of whom spend their nights in revelling, etc., and do not go out much in the day,
the meeting was held in the evening, the 19th of First month, 1813;
but to have a concourse of such people brought together so late as seven o`'clock p.m.,
tended greatly to increase my fears of the consequences.
My confidence nevertheless was in the Lord,
that he would overrule all to his praise and glory.
The meeting was very generally composed of the class of men and
women towards whom my exercised mind had been directed,
except that some of the inhabitants of the neighborhood, seeing the house lighted,
had come in, not knowing for what kind of persons it had been chiefly designed.
My mind was at first brought under great dejection
and distress on beholding before me so many fellow-beings,
of both sexes, in whose countenances so much vice and depravity were depicted,
some of whom, perhaps, had never been in a meeting for worship,
and were strangers to religious sensibility.
My soul was also greatly moved in observing that they were mostly young people.
I wept bitterly over them; but the love of Christ, who came to save sinners,
to seek and to save that which was lost, filled my soul and prepared me,
not only to proclaim against sin, and the consequences of living and dying in sin,
but also to preach Christ the Saviour of sinners.
O, it was a solemn time indeed; the Lord`'s power was over us; the lofty heads,
the proud looks, were brought down.
I have seldom known such brokenness, and so general, as it was that evening.
The meeting remained in the same state during the silence after I had sat down,
a silence only interrupted by the sobbings or deep sighs of some of them.
At the conclusion, the people retired in the same quietness.
O what a display of the Lord`'s power and mercy!
Surely our hearts can but overflow with gratitude to him our blessed and sure Helper.
How great is his condescending mercy,
in thus visiting sinners and causing the offer of his pardoning love,
if they will submit to his terms, to be proclaimed.
Very feelingly was the prophet`'s message declared to them,
"`Seek the Lord while he may be found, call upon him while he is near;
let the wicked forsake his way, and the unrighteous man his thoughts,
and let him return unto the Lord, and he will have mercy upon him, etc.`"

The chief police magistrate in London,
hearing of that meeting through some of our Friends, sent me word that,
if I wished to see that class of people more generally throughout the city,
he would take measures to have them all collected,
when full opportunity would be given me to have meetings with them.
I acknowledged his kind offer, but could not accept it,
though I told him I should be obliged by his giving
me free access to the several prisons in London,
having felt much drawn towards that class of poor, wretched humanity.
My request was readily granted,
and I engaged very soon in the arduous and very trying service.

The Compters^
footnote:[These Compters have since been abolished.]
were the prisons I visited first; there is one in each district of the metropolis.
They are places to which the offenders, when taken up day by day, are committed,
and from which they are transferred afterwards to other prisons,
according to the nature of their offences.
When in the morning I visited these prisons, I was astonished at the number I found,
who had been taken up during the preceding night.
I had some very striking religious opportunities with them.

After that, I proceeded with a visit to Newgate, which occupied some days,
having religious opportunities in the many separate apartments,
where the miserable inmates are confined.
Several were under sentence of death.
In one cell there were four together, who were to be executed the ensuing morning;
one of these particularly drew forth our tender feelings,--my dear friend,
William Forster, being then with me.
His wife, with two children, came to see him for the last time, when we were there.
One of the children was a boy, about eight years of age.
The awfulness of the sight of his father under heavy irons, with the other prisoners,
his emotion from knowing that his father was to be brought to the gallows the next day,
together with the gloominess of the prison,
brought the child into a state of great terror and distress.
P+++.+++ Bedford knew the grandparents of this child,--poor weavers, but people of piety.
We felt it our place to visit them the day after the execution of their son.
We were much instructed in beholding that, in their very deep grief,
they were sustained by the comforts of the Christian religion.
The Lord Jesus was their refuge and strength under their great and sore trouble.
They produced a letter written by the poor prodigal the night previous to his execution,
addressed to his wife, and to his parents; the mournful widow now coming to the house,
the letter was read.
After describing his heartfelt sorrow and deep repentance for his crime,
and the hope that, notwithstanding his great unworthiness, the Lord Jesus Christ,
who had mercy on the penitent thief on the cross, would condescend to be merciful to him,
he most earnestly begged his aged parents,
whose grey hairs he was instrumental in bringing down with sorrow to the grave,
to forgive him also; he described his evil life,
which had now brought him near to an untimely end,
as being the consequence of his disobedience to them,
and particularly in having disregarded the due observance of the Sabbath,
so contrary to their parental entreaties.
Having begun to do so in the afternoon, it had led him into evil company,
and step by step he had become the companion of thieves.
He most earnestly entreated his wife to guard very particularly
the children from such dangerous and ungodly practices,
and to spend the afternoons and evenings of the Sabbath in attending religious meetings,
and reading the Bible, and books of devotion.
We found in the boy above mentioned so much sensibility,
that our interest in him became excited;
some kind friends assisted in having him sent to school.^
footnote:[The boy behaved so well, that he was subsequently placed at a boarding school,
and afterwards as an apprentice with a Friend.
The letter of his poor father, above alluded to,
was preserved and given to him on his coming of age.
He married and settled respectably in life.]

In the course of the visit through Newgate we found many boys who,
decoyed into vice by thieves and pickpockets,
and now mixing in prison with older and depraved men,
were likely to come out from there far greater adepts in crime.
We felt much for those poor youths,
and seeing the necessity of having them kept separate from other criminals,
we succeeded in inducing the sheriff and magistrates to
have another part of the prison appropriated to them.
P+++.+++ Bedford took an active interest in the concern,
and several of our young men Friends enlisted in it, with great advantage.

The visit to that part of Newgate which is occupied by the women prisoners,
had very nearly been frustrated.
The jailor endeavoured to prevent my going there,
representing them as so unruly and desperate a set
that they would surely do me some mischief;
he had endeavoured in vain to reduce them to order,
and said he could not be responsible for what they might do to me,
concluding that the very least I might expect was to have my clothes torn off.
But the love of Christ constrained me,
and I felt persuaded that He who called me to this service could again make way for me,
and preserve me.
Very earnest was my prayer to have undoubted evidence that
this was a service that the Lord required of me,
feeling that my having visited the men was not a
reason why I should visit the women also.
My request was granted, and the path of duty being clear before me,
I proceeded to the prison.
When I came to the small yard,
the only accommodation for about four or five hundred women,
I found there some who immediately recognized me, as having seen me in the Compters,
and who appeared much pleased at my now coming here.
They told me that no preparation had been made to receive me,
but that they would immediately do what they could towards it.
Owing to the darkness of the morning,
the prisoners had been unusually late in getting up, and many of them had not yet risen.
They occupied two long rooms, where they slept in three tiers, some on the floor,
and two tiers of hammocks over one another.
They had the whole soon rolled up, and all the women came together in one room.
When I first entered, the foulness of the air was almost insupportable;
and everything that is base and depraved was so strongly depicted
on the faces of the women who stood crowded before me,
with looks of effrontery, boldness and wantonness of expression, that, for a while,
my soul was greatly dismayed;
surely then did I witness that the Lord is a refuge and strength,
his truth is a shield and a buckler; the more I beheld the awful consequences of sin,
and the more deeply I felt the greatness of the depravity into
which these poor objects had been plunged by the devices of Satan,
the more also I felt the love of Christ who has come to save and has died for sinners.
As I began to speak, under the feeling sense of this redeeming love of Christ,
their countenances began to alter: soon they hung down their heads;
their haughtiness and proud looks were brought low,
and tears in abundance were seen to flow;
great was the brokenness of heart manifested on this occasion.
I inquired of them if there were any other female prisoners in the place,
and was told that several sick ones were up-stairs.
On going up, I was astonished beyond description at the mass of woe and misery I beheld.
I found many very sick, lying on the bare floor or on some old straw,
having very scanty covering over them, though it was quite cold;
and there were several children born in the prison among them, almost naked.

On leaving that abode of wretchedness and misery, I went to Mildred`'s Court,
to my much valued friend, Elizabeth J. Fry, to whom I described,
out of the fulness of my heart, what I had just beheld,
stating also that something must be done immediately for those poor suffering children.
The appeal to such a pious and sensible mind, as dear Elizabeth possesses,
was not in vain.
She immediately sent for several pieces of flannel,
and had speedily collected a number of our young women Friends,
who went to work with such diligence, that on the very next day,
she repaired to the prison with a bundle of made-up garments for the naked children.
What she then saw of the wretchedness of that prison induced her to devise
some plan towards the amelioration of the condition of those poor women,
and, if possible, the reform of their morals,
and instilling into their minds the principles and love of the Christian religion, etc.,
etc., as had been done, to some extent, on behalf of the boys.

--

In thus following Stephen Grellet through his Christian
labours among the haunts of vice and infamy,
and the abodes of crime and misery in the British capital, in 1813,
it is interesting to be able so distinctly to trace their connection
with the origin of those systematic efforts for the amelioration
of the condition of some of the most wretched of our fellow-men,
the permanent effects of which are too well known and appreciated to need comment.
In the memorable interview with Elizabeth Fry,
as well as in many of his services in the metropolis, he "`had, much to his comfort,
the company of his beloved friend William Forster;`" and what passed at
Mildred`'s Court first prompted Elizabeth Fry to those "`visits to Newgate,
accompanied only by Anna Buxton,`" (afterwards the wife of W. F.)
out of which ultimately arose that persevering devotedness to the
temporal and eternal interests of the poor prisoners and outcasts,
which has been so full of blessing to thousands, in various parts of the world.
A touching interest is added to this record, by the fact, that William Forster,
during his last illness in Tennessee in 1854, where, as the faithful minister of Christ,
he laid down his valuable life, a martyr to the cause of the poor down-trodden slave,
alluded with lively recollections to the circumstances
and results of the interview with E. Fry,
so graphically described by Stephen Grellet.
The journal proceeds:

[.embedded-content-document]
--

I also visited in Newgate the separate prisons for debtors, both men and women.
These were divided into two classes; those who had moved in the higher ranks of life,
and those in a lower sphere.
The opportunity among the first of these was a memorable one,
many of them were much affected;
they had been brought to that place from various
circumstances which they could not control,
through an accumulation of misery or disappointment.
Some, however,
evinced that they knew the Lord Jesus Christ to be their refuge in the time of trouble.

I afterwards visited all the other prisons in London, and also the several poor-houses.
While during the day I pursued the above engagements in prisons, poor-houses, etc.,
I had in the evening, in some parts of London,
several meetings of a character nearly resembling that I had in St. Martin`'s lane,
with the vicious and degraded portions of the community.
Several of my very valuable friends accompanied me in these visits also.

I felt much spent after these close engagements,
and so long breathing the air of prisons and poor-houses; and accepted, with gratitude,
the release that my good Master gave me, for the present at least, from London,
Gospel love prompting me now to visit Friends and
others in some other parts of this nation.

--

Abounding, as Stephen Grellet thus did, in the work of the Lord,
his labour was not in vain in Him,
and on being permitted afterwards to see some of its results, he remarks, "`Thus,
though my labours have been attended with deep suffering and mental distress,
I have cause, with reverent gratitude, to bless and praise the Lord,
in that those humiliating and trying services have
tended to the relief of many poor sufferers,
and I hope also to reclaim many from the paths of vice and misery.`"
Of his visit to the West of England he thus writes:

[.embedded-content-document]
--

Accompanied by my dear and valuable friends, Joseph and Rachel Smith,
I left London the forepart of the Second month, for Reigate, Dorking, etc., etc.,
when these beloved friends returned to London.
I now had one or two, and sometimes three meetings a day,
accompanied by my dear friend Peter Bedford, till we came to Shaftesbury.
In several places I had satisfactory meetings with the French prisoners,
and also visited some American prisoners of war;
for our two nations have unsheathed the sword.
It renders the communication very difficult,
so that it is but seldom I can now hear from my beloved wife, or she from me;
this opens a fresh occasion for presenting on the Lord`'s altar myself and my all,
to do and to suffer the whole of his will.

I visited Friends very generally throughout these counties, as far as the Land`'s End,
in Cornwall.
I had also meetings among the inhabitants,
many of which were held in the dissenters`' meetinghouses.
Some were very satisfactory, particularly among the Methodists,
to which the greater part of the miners belong.
Many years ago they were a lawless, dissolute set of men,
but now the fruits of religion appear in many,
and evince that there is a real reformation among them.

During my services in Cornwall I was joined by my valued friend Sarah Hustler,
with whom I have been closely united in Gospel fellowship.
She and Ann Burgess were then on a religious visit to that county.
We had many very large meetings among the miners, and the fishermen on the coast.
I have seldom known the baptizing power of Truth, meeting after meeting,
for so many days together, in the same degree.
Many of these meetings were held by candle-light;
the people coming late from the mines had not time to wash and clean themselves,
but their dust-covered faces soon gave evidence of
the stream of tears washing down their cheeks.
Sometimes the people had to stand, being much crowded;
yet it was astonishing with what stillness they would remain so long,
after having spent most of the day working in the bowels of the earth.

I came back through Devonshire, Somersetshire, and Oxfordshire to London,
the middle of the Fifth month, with a heart reverently prostrated before the Lord, who,
both in that great city and out of it, amidst very laborious services in his gospel, has,
in such a merciful manner, helped and sustained me, the poorest of his servants.
Surely there is great encouragement to trust in the Lord,
in whom there is everlasting strength.
On the European continent, many baptisms and sufferings await me,
in the service of his blessed cause of righteousness and truth;
but my mind is at seasons favored with quiet and cheerful
resignation to the whole of his sovereign will,
with a humble confidence that he can make way for me to perform whatsoever he requires.
O Lord, in filial reliance upon the all-sufficiency of your power and protecting care,
I commit myself again to you!
Surely I have great cause to trust in Him, and to magnify his power and mercy.
Since I landed on these shores, I have travelled more than eight thousand miles by land,
and have had two hundred meetings more than days in that space of time.
I landed feeble in body,
and yet my health has not prevented me a single day from prosecuting the Lord`'s work,
and he has richly supplied all my needs.

On my return to London, I have deeply to feel for my dear friend, Rachel Smith,
under the heavy loss she has sustained by the removal of her valuable husband,
my very dear friend, Joseph Smith; he survived but a short time his return to the city,
after accompanying me a little way out, last Second month.
The poor miss him much; his liberal mind devised and effected liberal things.
Among other standing monuments of his liberality are a number of neat alms-houses,
that he has had erected in Yorkshire, in the place of his nativity.
He was of a meek and quiet spirit; humility appeared to be his clothing.
Both he and his valuable wife often comforted me, last winter,
during my arduous religious services in this great city.

--
