== Chapter XXII.

Second Visit to Europe

Munich--Augsburg--Landshut--Braunau--Kirchberg--Ratisbon--Nurenberg--Oettingen

From Switzerland Stephen Grellet passed over into Bavaria.
That country was then in a very interesting state,
as it regards the spread of vital religion.
Towards the close of the last century, many persons had been quickened,
under the influences of the Holy Spirit,
to a deep and serious concern for the salvation of their souls;
and it was a well-known fact that there existed, in some parts of Germany,
a multitude of Christians, of the Roman Catholic persuasion,
who were distinguished from others of the same communion,
by a profound acquaintance with, and a sincere attachment to,
the fundamental doctrines of Christianity.
Persons of this character were particularly numerous in Bavaria.
A religious awakening had taken place,
not only among the members of the different flocks,
but among their pastors also,--nearly forty priests
were known to have been brought under its influence.
It was there that, forty years ago, Feneberg and Winkelhofer had taught,
and it was there that Sailer was still pursuing his useful labours;
while many priests of less note, once his pupils, were preaching the Truth, which,
though obliged to avoid much publicity, they desired to spread.
From Bavaria sprang Lindel, Gossner, and Boos,^
footnote:[See a valuable memorial of Boos,
translated from the _Archives du Christianisme_.--Christian Observer, September,
1827.]--those three faithful witnesses,
who were driven by persecution from place to place; and who,
wherever they turned their steps,
did not hesitate to proclaim that Gospel which had
brought peace and salvation to their own souls.
They were not proscribed for having taught any particular heresies;
but for having declared, with much force and fulness,
the fundamental truths of Christianity,--the natural corruption of the heart of man,
the impossibility of salvation by works, the need of the Spirit`'s influence,
and the free grace obtained for sinners by the expiatory death of Jesus Christ.

Sailer continued at his post, in Landshut, surrounded by many difficulties;
Gossner was preparing his translation of the New Testament for his Roman Catholic brethren,
at Munich; and Boos, not long before his banishment,
was still patiently enduring severe persecution,
in the midst of "`some thousands of spiritually minded persons in his
own parish in Austria,`" when Stephen Grellet visited those parts.
He thus continues his journal:

We crossed the Rhine at Rheineck, on my way to Munich.
On getting into the diligence, I was agreeably surprised to meet with J. Graff, of Geneva.
He was from home when I was in that city; but his wife,
one of the pious individuals whom I had visited there, had written to him respecting me,
and, recognizing me by my dress, he at once saluted me with warm affection.
Little did I think how providentially he had met with me,
to render me particular services.
When we came to Lindau, at the head of Lake Constance, our passports were examined,
and it was found that mine had not the vise of the Austrian Ambassador at Zurich.
I informed them that I had gone to his office,
but was told that he was absent and might be so for weeks,
but that his vise was not necessary, I having that of the authorities of Zurich.
The police officer would not, for a long time, allow me to proceed,
but insisted upon my going back nearly two hundred miles to obtain it.
Graff went immediately to some of the first inhabitants of the place, whom he knew,
and who came forward to offer themselves as my securities.
On this, the officer stated that his authority extended only to Kempten;
sixty miles further, but out of the way of the place where Graff intended to go.
He nevertheless kindly offered to accompany me there,
to see what further assistance he could render me, as he had friends at Kempten,
who would do everything for him.
On our arrival, I presented myself before the Commissary of Police there;
for some time he seemed determined to send me back to Berne, but,
by the interference of Graff and his friends,
the Commissary concluded to send me to Munich, under the escort of two soldiers,
that there I might abide by the decision of the Minister of Police;
but on further consideration of the expense of sending the soldiers with me,
he concluded to constitute me my own keeper,
with directions to deliver up myself and the charges against me,
immediately on arriving at Munich.
Matters thus settled, Graff left me with much affection,
marvelling with me at our providential meeting, when he could thus serve me.
I presented myself to the Minister of Police as soon as I arrived at Munich.
At first he appeared somewhat excited at my appearing before him with my hat on,
but a very few words of explanation sufficed.
He treated me with courtesy,
and at once removed everything in the way on account of my passports; he became,
moreover, a means of introducing me to serious persons of the first rank there,
among whom were several of the Ministers of State, particularly the Minister of Finance,
in whose palace I have had a very full opportunity, in a religious meeting,
to proclaim the blessed Truth.
The meeting was attended by a pretty numerous company;
to some of them I might perhaps seem like Paul, at Athens, in the Areopagus;
but some others were sober, and manifested religious sensibility.

The Baron Pletten, Director-general of the Posts, has been very attentive to me,
accompanying me in a visit to some pious persons,
and being my interpreter also in several meetings among Protestants and Roman Catholics.
Some priests among the latter, having become convinced of many of the errors of Popery,
have withdrawn from that Church.
There are about forty of these in Bavaria, I am told.
Three in this place endured much persecution,
and two have been obliged to leave the district.
Gossner is the only one remaining at present,
but there are a number of Papists who join with him; among these are several nuns.
I have found much spiritual-mindedness among these people;
they appear very earnest in their desire to come to the knowledge of the Truth,
and to walk in it.
The Lord`'s presence and power have been in a contriting
manner with us in some of the meetings I have had with them.
Persons like-minded, hearing of it, have come from fifteen to twenty miles distance.

Gossner is engaged, under religious concern, in the translation of the New Testament,
which he thinks might be of much service among many of the Papists,
who are desirous to read the sacred volume,
but are prejudiced against the edition of Luther.
He has nearly completed his translation,
but does not know where he can obtain the means to print it.
My mind being introduced into deep feeling on the subject,
I have put him in a way to have an edition of six thousand copies executed,
which I hope may be ready for circulation in a few months.

I have become acquainted with the physician to the Crown Prince, the son of the King,
who, hearing of me through him, has sent me a request to visit him.
I accordingly went to the palace, and found him in a tender spirit,
and under religious concern for his soul.
He proceeded to unfold the exercise of his mind,
and while mentioning the deep distress in which he had been,
the big tears dropped down his cheeks; "`Many a time,`" said he,
"`under strong convictions for my sins,
I have formed resolutions to pursue a different course of life,
but the very next temptation has overcome me;
none of my resolutions prove sufficient to preserve me.`"
I directed him to the Lord Jesus Christ,
as the only sure refuge and helper--the only Saviour,--able
to save to the uttermost all that come to him,
with a penitent heart and in faith.
We parted under feelings of solemnity.
The next day I received a letter from him;
after alluding to the feelings that have attended him since I was with him,
with a little faith that the Lord Jesus Christ might condescend to become his helper,
he said that that evening he had been with the King, his father,
and that on speaking of me to him,
who had heard of the meeting I had at the house of the Minister of Finance,
he had expressed a desire to see me himself,
and that accordingly he would expect me that forenoon,
at eleven o`'clock. The Prince requested me to stop a few moments with him,
before I went into the King`'s apartment.

Though I had felt some desire to have an interview with the King,
particularly in reference to the severe persecution
under which many of his subjects have suffered,
because, from conscientious motives, they have abjured Popery,
and the threatenings of the Pope`'s nuncio that they
would proceed to greater extremities against them,
I had been much discouraged from making an attempt to see him,
on account of the great obstacles, which, as I was told, were in the way.
But now, receiving an invitation from the King himself, I felt prepared to accept it.
I went first to the Prince, as he requested.
He told me that he had prepared the King to see me appear before him with my hat on,
and had given him some of the reasons for which the members of
our religious Society do not comply with the world`'s practices,
in this and other particulars;
but that he wished to know what reception his father would give me,
and therefore requested I would see him again, before I left the palace.
On my entering the King`'s apartment, I found he was alone, and waiting for me.
He came towards me as I entered, having his head uncovered;
I saw at once that he was not well pleased to see me with my hat on,
but after a very few words had passed between us, his countenance brightened up.
At first he had many inquiries to make relative to the object of my travelling,
the nature of my religious engagements,
and respecting several of our religious testimonies; that against war,
in an especial manner.
He also wished to know the result of my observations
in the visits I had made to their prisons.
Having answered his inquiries,
my way was open for introducing the subject of liberty of conscience,
and the sufferings that had been inflicted on several of his subjects on that account.
He very soon threw the blame on the Pope, his nuncio, and the bishops, etc.
"`They are continually teazing me on that account,`" said he, "`I am tired of them,
and will let them know it.`"
This very interesting topic led me to make some remarks of a religious character,
under which the King`'s mind appeared to be impressed; and at last,
when I was about to withdraw, he put his arms round my neck, and bid me farewell.
We had been together above an hour.

The Prince was delighted at my account of the reception the King, his father,
had given me.
I do hope that the powerful convictions that he has received, and the impressions that,
through the love of Christ, have been made upon him, will prove lasting.

Among the visits made me by pious individuals,
are those of two very interesting young men,
the Baron Gumpenberg and the Prince Oettingen.
They both give evidence, especially the young Prince,
that the visitation of the Redeemer`'s love is very peculiarly towards them.
The Prince is in a very tender state;
may the Lord bless the work that he has begun in these youthful plants.

I went to Augsburg, to visit a few pious persons there; among others,
a brother-in-law to my very kind friend Graff, and Conrad Smith,
a man in high station in the world,
but one of those meek spirits precious in the sight of the Lord.
He made the preparations and gave invitations for a meeting,
which was attended by a good many persons, who have become inquirers after the Truth,
by the very means devised to suppress it--persecution.
Several of these came to the meeting, from a distance of many miles.
The Lord owned us by his presence,
and gave me doctrines to proclaim suitable to their condition.

16th of First month.
I came to Landshut, my principal object being to visit Sailer,
a very remarkable Popish priest,
and valuable in the Lord`'s hands in extensively
promoting the work of reformation from Popery.
He is a man very well known for his learning, but more especially for his great piety;
he is also a teacher in Theology,--has educated many young men for the priesthood,
and has a number now under his care; he has endeavoured, as he told me,
to direct them especially to the school of Christ,
and to the influences of the Divine Spirit, under whose teachings alone, as he stated,
the things of God can be known.
The fruits of his teaching appear in that the greater number
of those priests who have of late deserted Popery,
received their education under his care.
I found that he, like Gossner, has in his hands several books of Friends,
which he said he often peruses.

He accompanied me in visiting several persons spiritually minded, like himself,
some of whom joined us afterwards in a religious opportunity,
which I had with the students at this university.
Several Popish priests also attended.
The particular subject given me to treat upon,
was the source from which a pure and living Gospel ministry flows,
even from Christ and his Spirit; that if we minister of the things of God,
we must have the Spirit of God, for without that Spirit they cannot be known,
and if we are moved and led by the Spirit of God, then we are children of God,
true members of his church, over which Christ is the Head.
This opened a wide door to preach Christ as the only Saviour and Redeemer,
enlarging on the Divine offices and attributes of
Him who will not give his glory to another,
nor his praise to graven images,
which those men attempt to do who exalt the Pope and his clergy, etc.,
and set up images of gold, silver, brass, etc.,
and fall down before them and worship them in open disobedience to the commands of God.
Sailer was my interpreter on the occasion.

18th. Late in the afternoon I left for Braunau, in a sleigh with post-horses,
the snow being deep and the weather very cold, and travelled during the night,
on account of the difficulty of obtaining accommodations in small towns or villages,
because of the soldiers occupying them.
Last night I had a narrow escape from robbers;
one of them sprang from behind a tree to take hold of the horse`'s head,
while the others were coming by the side of the sleigh; but the horses being spirited,
and the driver giving them a touch of his whip, they sprang forward,
threw off the man on one side, and we were soon out of their reach.
Though I frequently hear of the ill-treatment received by travellers,
this is the first attempt, as yet, made upon me that I know of.
Daily, however, I feel that my life is in jeopardy;
I have again and again to renew the surrender of it to the Lord,
and I stand resigned to whatever suffering may be permitted to overtake me.
Ai seasons I am comforted in the belief that he will not allow anything to befall me,
but what he will give strength to endure, and condescend to sanctify to me.

I found Braunau crowded with the Austrian soldiers, on their march forward;
but my object in coming was chiefly to endeavour to find and to visit some of
those pious persons who have become dissatisfied with their Popish profession.
I could not well reach their villages but by going on foot over the snow.
The first village I aimed at was Kirchberg, the residence of Langenmeyer,
one of those enlightened priests, who has endured much persecution;
and heavier trials appear impending, as they threaten to send him to Vienna.
There are several others of the Popish clergy in that neighbourhood like-minded with him.
He told me of thirty-one, five of whom met us.
Truly this is a seed of the Lord that I am called to visit,
and made his humble instrument to water in their distress,
from the spring that flows from his Divine presence.
They have among them many persons to whom their labours of love have been blessed,
and whom they are gathering to Christ as their only bishop, high-priest,
and hope of salvation.
They had them collected together,
and the Lord gave us to feel the refreshings from his Divine presence.
Langenmeyer was my interpreter of what the Lord gave me to communicate to them.
Such were the consolations received of the Lord that day,
that I was refreshed in body and mind,
though I had travelled the whole of the night before,
had close religious labours that day, and walked about twelve miles.

From Kirchberg he had intended to go to Gallneukirchen, near Lintz,
to visit Boos in the scene of his labours and sufferings, but prevented,
by circumstances not under his control, from effecting his purpose,
he sent him a message of Christian sympathy and encouragement, by his friend Langenmeyer,
and proceeded direct to Ratisbon.

"`On the road,`" he says, "`a heavy snow-storm overtook me;
but the Lord renders hard things easy, so that, though in my open sleigh,
and the cold so severe that the snow froze on my face,
yet the love of God so warmed my heart,
that gratitude and praises to his holy name were my clothing most of that night,
and I felt like Jacob when he came to Bethel.

In Ratisbon, I found in the Count Westerwood and family genuine piety;
also in the Princess. She has surrounded herself with those who, like her,
love the Lord Jesus.
Thus, amidst the thick clouds of darkness that hang over the nations,
and the tumult of war,
there are here and there those who know the Lord Jesus to be their sanctuary.
My spirit was refreshed in a meeting with a company of these pious persons,
when the external hardships of the preceding nights were forgotten.

21st. I came to Nuremberg, where, through letters of introduction I had with me,
I soon became acquainted with pious persons, chiefly among the Protestants.
Shoener, one of them, is an aged and venerable man, of exemplary piety;
he seems clothed with meekness and humility.
He is their chief clergyman here; but he, with a few others,
having become uneasy with many of the set forms prescribed by their church,
have ceased from them, endeavouring, as they say, in their worship,
to attend to the sensible motions of the Divine Spirit, be it in preaching, praying,
or in silence.
At several meetings I have had here, a pious young woman, who speaks French,
interpreted for me with much dignity and faithfulness.
After having been frequently with Shoener,
and he having sat by my side at several meetings,
on my telling him that I had not thought till that moment
to ask him to what religious profession he belonged,
whether Lutheran, Calvinist, Reformed, or what else, he answered with much seriousness,
'`I belong to none of these; I desire to be a Christian, and to have the name of Christ,
the Saviour,
and his Spirit upon me.`' He appears convinced of the duty
of yielding to the influence of the Spirit of Christ;
'`For,`' said he,
'`we have religion or are Christians only in proportion as we are spiritually minded;
the Spirit leads to the substance; it is efficacious, for the law of the Spirit of life,
in Christ Jesus, sets free from the law of sin and death.`' '`He had felt,`' he said,
'`the heavy burden which set forms and ceremonies impose on the conscience,
but now the Lord had set him free from these;
and we must leave the shadow to inherit the substance.`'

From Nuremberg I came to Oettingen.
I had letters from Sailer for the President von Ruosch,
and for the Princess Dowager of Oettingen.
The President would not allow me to stay at an inn;
both he and his valuable family treated me with the kindest hospitality.
I found in the palace my dear Master`'s presence,
for to some of its inhabitants the Lord Jesus is precious--they know him as a Saviour.
Among these, besides the Princess Dowager, is her sister-in-law, the Princess Jeanette;
the Baron Braun also, and the Princess Amelia, wife of the young Prince.
The latter is only eighteen years of age, but she manifests stability of character,
and an advancement in religion beyond her years.
With these, and several others, together with the pious family of President von Ruosch,
I had such solemn and baptizing religious opportunities as reminded
me feelingly of the interviews which William Penn relates to have
had with the Princess Elizabeth and the Countess de Home.
It is surprising how way has been made for me among that company.
I spent most of an afternoon with the Princess Jeanette and the Baron Braun,
in serious conversation.
I left the palace in peace.`"

Three weeks had now been spent in the midst of a body of Christians in Bavaria, who,
in the bosom of the Roman church, fully confessed, by their faith and practice,
the grand fundamental principles of the Reformation.
The bold and unflinching testimony thus borne against
many of the leading tenets and corruptions of Rome,
had been attended with a large measure of blessing both to priests and people;
and having taken his final leave of this portion of the Christian family,
on reviewing his labours among them, Stephen Grellet writes to a friend in England:

The fields in many parts I have visited are white unto harvest,
so that sometimes I have wished that I might have the life of Methuselah,
or that the sun might never go down,
that I might do my share of that great work which is to be done in these nations.
There is a most precious seed in these parts,
and in places where I have not actually visited it.
O did our Society stand faithful, what a blessing they might become!
Many are ready to gather to the standard of Truth,
from among all the various denominations and ranks.
I have been with rich and poor, princes and princesses,
Protestant ministers and Popish priests, all speaking but one language,
not upholding forms and ceremonies, but Christ and his Spirit.
I have visited various of those Romish priests in Bavaria of whom we had heard,
and have found them to be spiritually minded men.
I am nearly united to some of them.
A few have married, and have answered those who have come to visit them on that account,
out of the Scriptures, and the practice of the Primitive Church;
and they continue Romish priests still, much beloved by the people,
among whom they exercise a good influence.
Many of the people desire to have the Scriptures,
but have it not yet in their power to obtain them.
Some of their priests told me,
that they believe it to be their duty to remain in
their places for the sake of the people about them,
and to help others to come into the same spirituality.
I am not able to give them any other advice than closely and faithfully
to follow Him who has begun a good work in them,
and will lead them safely.
They feel very precious to me,
and I know they rejoice in the visit which Gospel love has led me to pay them.
My life seems interwoven with theirs.
Some think I am a man of deep learning,
while my greatest science is to know nothing--nothing but Jesus Christ,
and him crucified.
It is He who is mouth and wisdom, when my mouth is laid in the dust.
