== Chapter XXVIII.

Third Visit to Europe

Finland

A fine passage of forty hours across the Gulf of Bothnia brought them to Abo.
Their religious engagements in Finland and the journey
to Petersburg occupied little more than a fortnight.
Stephen Grellet thus proceeds with his memoranda:

Abo, 29th of Tenth month.
We arrived here early this morning.
It was a beautiful passage.
The numerous rocks and islands through which we passed are called "`the Thousand islands.`"
My mind was, however,
under too great a weight of feeling to enjoy the surrounding beauties.
On the one hand, I was prostrated before the Lord in adoration and praise,
for the help he has granted us through Norway and Sweden,
the wide door he set open before us to proclaim his
great and holy Name among the people at large,
and to many of their clergy;
and the manner in which way has been made for us to spread before
the King of Sweden and many of his nobles our religious exercise
and concern for the promotion of the cause of Truth among them.
But, on the other hand,
my spirit was brought very low under the weight and magnitude
of the concern upon me for this vast empire of Russia,
not knowing what may befall us here.
O Lord! all things are possible to you!
Not by might nor by wisdom, but by your Spirit only are your servants to be directed;
their help is from you alone!

Finding ourselves now again among a people of a strange language, the Finnish,
unable to ask for the most necessary things,
and being informed that for travelling through this country it
is needful to have a person who can obtain horses on the way,
drive them, etc.; we concluded to hire a man,
who was recommended to us as an upright and faithful person, who speaks French, Finnish,
and Russian, and who is able to serve us in various capacities.
We soon found his usefulness in showing us the way to persons we wished to visit,
and for whom we had letters.
The first of these was Count Steinhielt, Governor-General of all Finland.

The Count Rosenblad, of Stockholm, had kindly given us a letter of introduction to him.
He received us with Christian kindness,
and at once offered to give us free access to every place we may wish to visit.
We had passed the fortress, a most gloomy place,
in which we understood many prisoners are confined,
and we felt a great exercise of mind towards them;
but did not know that we could obtain admittance.
The Governor making us such an offer, we asked liberty to go there,
which he readily granted, by giving us an order on the commanding officer of the place.

30th. We became acquainted with a physician, named Hartman, a pious person,
who is very serviceable to us.
He speaks good English.
He has accompanied us to the Archbishop of Finland,
for whom we had letters from Count Rosenblad and others.
The Bishop speaks good French,
and appears to be a man of religious liberality united with piety,
which it is peculiarly pleasant to meet with in a person in such a station.
He manifested much interest in inquiring into our Christian testimonies; and, on parting,
expressed a desire to have further information.
We have visited their house of correction and the poor-house; most wretched places.
Their inmates are crowded together,
and so filthy that the air breathed seems calculated to cause the most infectious diseases.
We felt much for some of these poor sufferers.
Doctor Hartman has been our kind interpreter.
Some of their hearts appeared tender,
and they gratefully received the consolations of
the Gospel that we felt engaged to impart to them.
We found in one apartment a number of gypsies, brought here mostly for petty thefts.
There are many of these people in Finland,
and we learn their manner of life is much like that of those in England.

In the afternoon we went to the prison in the castle, accompanied by the Doctor,
and the Secretary of the Governor General.
The castle is about two miles out of Abo.
The approach to the prison is through an arched stone vault, which extends some distance.
The chains and irons fastened upon the poor prisoners
exceed what I have seen any where else,
though I have visited many prisons.
The Governor has it not in his power to remove these fetters,
but by his humane treatment, the prisoners are kept very clean,
and their cells dry and well warmed in winter.
We have taken a sketch of the fetters of these miserable sufferers, which, perhaps,
may be of use at a future day, in endeavouring to procure some relief for them.
One man has been confined in heavy irons for eighteen years.
The worst of all is that many, under great bodily suffering,
have minds as hard as the iron which nearly covers them.

31st. I felt so distressed last night under a sense
of the sufferings and misery which I had beheld,
that I could not sleep;
my soul was poured forth before the Lord that he would open
the way for the mitigation of so much distress.

1st of Eleventh month.
Yesterday we had a full opportunity with the Governor.
We laid before him the heavy sufferings of the poor prisoners in the castle,
and in the other prisons.
He feels for them, and says that he has taken steps towards a change in their treatment,
but has not yet succeeded;
he apprehends it has never yet come to the knowledge of the Emperor.
We pressed it upon him to exert his influence for the relief of such great suffering.
We have had a religious opportunity in his palace,
with his family and about fifty other persons.
His wife and daughters are serious characters;
we proclaimed among them the redeeming love and mercy of God, through Jesus Christ,
who would that all men, coming to the knowledge of the blessed Truth, should be saved;
and who has also given to every man, for this very purpose,
a manifestation of his Spirit.

This evening we had another opportunity with about forty or fifty persons;
two of them were our fellow-passengers from Stockholm, a young nobleman from Russia,
and a female; it was to some satisfaction.
It is hard for them to understand the nature of true silence before God,
and to follow the Saviour in the way of the cross.
The Archbishop sent us a request for another interview,
and wished us to take a family dinner with him.
We accordingly went to his house.
Our minds were strongly engaged before the Lord that, through the help of his Spirit,
he would preserve us from everything that could militate
against his blessed cause of righteousness and truth,
and enable us to promote it.
The Archbishop received us at first in his private apartment,
but soon brought us into a spacious room,
in which were his wife and several branches of his family,
who were shortly after joined by many of the clergy.
It appears that these had come to Abo from different parts of Finland,
on some special occasion,
and the Archbishop was willing to give them an opportunity to be with us.
On seeing such a company collect, we felt our minds brought under deep exercise.
My prayer was that the Lord would turn this time of trial to his glory,
and the exaltation of his great name.
After a while I felt that his power was over all, and my confidence in him was renewed.
One of the first subjects introduced by the Bishop was liberty of conscience.
We were enabled with clearness to state that the control of the conscience
is a prerogative which the Lord has reserved in his own hands;
to him alone it belongs, by his Spirit and his Truth, to rule in the hearts of men;
men may make hypocrites, constrain them to an outward profession,
but they cannot convert the heart.
Water-baptism and infant-baptism were the next subjects,
which led to our fully setting forth the nature and effects of the baptism of Christ.
Then followed what constitutes a member of the church of Christ;
the Christian worship and ministry,
out of which branched an allusion to the many ceremonies and practices
that have found a place among different religious denominations,
for which there is no authority in the Holy Scriptures, which, contrariwise,
bear testimony against them.
The Archbishop gave unequivocal assent to many of our sentiments on these subjects,
and several of those present united in the same; none made any objection;
but some requested further explanation.
They said that all the best forms and outward observances are but a shadow of the substance,
to which every true Christian is to gather;
"`none of these things,`" said the Archbishop, "`will be found in heaven; but love,
which should be universal on the earth, and love to God, which is to endure forever,
will prevail there.`"
When we came to the dinner table, instead of sitting down at once,
the company stood in silence behind their chairs, and then, without uttering a word,
we all took our seats.
I was seated between the Archbishop and his wife,
and took the opportunity to ask him respecting their
having thus stood in silence before sitting down.
He said that it is his regular practice in his family;
he considers it much preferable to the formal habit of uttering set prayers,
which often the heart does not feel;
but that in silence there is an opportunity for the heart to feel
after and receive a qualification for secret prayer to God.
During dinner he made several inquiries tending to edification.
I felt my mind strongly drawn, in the love of Christ,
towards the company with whom we had been thus unexpectedly brought to mingle,
and I was endeavouring to wait for a suitable opportunity
to express what I felt towards them,
when, after dinner, they all rose and placed themselves again, as before dinner,
behind their chairs, and so continued for a while in silence.
I then believed it was the proper time to communicate
what I felt to be the Lord`'s message to them.
Much seriousness and solemnity prevailed; and, before we separated,
the Archbishop expressed his gratitude that he and his brethren
had had such an opportunity to be with us,
which had been to their edification,
and he desired that the Lord might prosper and bless the work to which he has called us,
and bring us to the knowledge of thousands of his faithful servants,
in the nations whereto he is sending us, and finally, by his redeeming grace,
enable us to meet all together in the kingdom of his dear Son, our Lord Jesus Christ.
The whole of this was expressed in French, which the company understood; consequently,
it has been easier for us, than when an interpreter is required.

In the evening we had a tendering religious opportunity at the house of Dr. Hartman,
with his family and a few others.
His wife is a pious woman.
We left them in great brokenness of spirit.

They now took their departure from Abo, accompanied by their hired attendant,
the value of whose services, in facilitating their progress, soon became fully apparent.
Stephen Grellet continues:--

Helsingfors, 4th of Eleventh month.
We have passed the two last nights at very poor houses,
but the people were kind with the little they had.
We arrived here early this afternoon, and were this evening with Count D`'Ehrenstrom,
Governor of this place.
We had a letter for him from the Governor General at Abo.
This place contains about 5,000 inhabitants.
It was destroyed by fire when the Russians took possession of Finland a few years since.
The Emperor Alexander instituted an inquiry into the loss that each individual sustained,
which was made up; and now they are rebuilding the place with good stone or brick,
and not wood, as before.
We find G. W. Sundman, a merchant of this place, a serious person,
who kindly introduces us to some others like-minded.
He has accompanied us in a visit to the poor-house,
where he acted as our interpreter to the inmates.
Then, taking a boat, we came, amidst thick fog and rocks, to a fortress called Swabia,
which occupies five islands, and has in it six thousand Russian soldiers;
their wives and children amount to two thousand more.
It is a very strong place.
The prison contains at present four hundred and ninety prisoners.
We had letters for the Commandant of that place, Count Heydon,
who speaks both French and English, as does also his valuable and pious wife.
They gave as a kind welcome, and accompanied us in our visits to the prisoners.
Here we found no chains nor irons, as at Abo,
and way was readily made for our having religious opportunities with the prisoners,
and with the children of the soldiers at their schools.
One class of the prisoners has deeply affected us.
They are boys from twelve to fourteen years of age,
some of whom have come from distant provinces, and have been taken up as vagrants.
Count Heydon has in vain made application to their friends,
or to the authorities in the places from which the boys say they came, to claim them.
He intends to apply to the Emperor himself on their behalf.
We dined with the Count, and had a religious opportunity in his family.
The young people evince by their sensibility that
the pious care of their mother has been blessed.
It was a solemn and tendering season; the Count also evinced great sensibility.
On our return he accompanied us to the wharf,
and sent us over to Helsingfors in his own yawl, which had seven men to row it.

6th. We visited G. L. Zetterman, the principal clergyman at Borga.
We soon felt our hearts much opened towards him.
He has a pious, humble mind.
He is acquainted with,
and highly appreciates the excellency of the gift of the Holy Spirit.
He accompanied us on a visit to some individuals; and to their school and prison.
We are much pained, since coming to Finland,
to find that so many women are in these prisons for the crime of infanticide.
It appears to exist to a very deplorable extent.

From Helsingfors, they had a quick journey to Frederickshamm; the roads being good,
they travelled one hundred and fourteen versts, about eighty-four English miles,
in nine hours.

Frederickshamm, 7th. This place is in Russia, and is a fortified town.
We left the old Swedish frontiers at Lovissa, through which we passed without stopping.

8th. The Commandant of this place speaks the Russian language only,
but the officers very generally speak French also.
We are pleased with our visit to the prison;
the prisoners are better clad and fed than we found them in Finland.
Their irons are very light.
The Major of the regiment accompanied us,
and made way for us to communicate to the prisoners what we felt towards them,
himself interpreting for us into the Russian language.
We visited a school for the children of the soldiers.
There were a hundred and ninety-two;
some of them appeared to have minds susceptible of tender impressions.

We wished to return to our inn to dine,
but the General and officers had arranged among themselves that we should dine with them;
and as the General is not married,
they had concluded we should dine at Colonel +++_______+++`'s.
We found in the wife of the Colonel a mild serious woman.
The General and many of the officers came, and several of their wives accompanied them.
Before dinner, inquiries having been made into some of our Christian principles,
dear William Allen particularly entered into an explanation of our testimony against war.
It appeared a new thing to some of them,
but excited tender feelings and expressions of high approbation,
with desires that such a peaceable spirit might spread over all the nations.
The General, to whom one of the officers interpreted what was said, rose from his seat,
and put away his sword.
All the officers did the same, saying that "`they must at least, while with us,
lay down their carnal weapons.`"
We had after dinner a religious opportunity with them.
They were serious, and some of them tender.
In the evening several came to our inn,
and made further inquiries into our Christian principles.

Pursuing their journey they came to Viborg,
their last halting place before entering into winter quarters in the capital of Russia.

Viborg, 9th of Eleventh month.
We arrived here early this evening.
The weather is very cold, some degrees below zero, but the roads are good.
The Russians have now put on their sheep-skin clothing; some of them wear double skins,
by which they are thoroughly protected.

10th. A. Garnick, a merchant of this place, is a serious man; his wife, a pious woman;
as is also a female of the name of Lehman.
The latter has a large boarding-school for young women of the upper rank,
whom she endeavours to train in virtuous and pious habits, as well as literary pursuits.
We had an encouraging religious opportunity among them.

Baron Nicholey, Mayor of the place, and Secretary of State,
accompanied us to the prison in the castle,--a miserable dirty place,
dark and damp,--men and women and their young children all crowded together.
We were greatly affected in being with them.
O, that the Lord may open a way whereby relief may be extended to so many sufferers!
