== Chapter XXX.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Russia
* Petersburg, continued

Though the Emperor had returned to the capital, they had not yet seen him.
But they had subsequently two interviews with him,
and also spent some time with the Empress and the Empress Dowager.
As the time of their departure drew near,
they were indefatigable in the earnest pursuit of the object of their Gospel mission.
Stephen Grellet goes on to say:--

[.embedded-content-document]
--

10th of Second month, 1819.
We have been several times with Count Miloradovitch,
the Military Governor of several provinces.
He has kindly made way for our admission to several prisons.
He inquired what we had observed amiss, that might be remedied.
We told him that much might be done,
but that there were certain things that should be attended to immediately.
We remarked upon the great impropriety of confining
men and women indiscriminately in the same apartments,
and the demoralizing effect it must have; the soldiers on guard,
being placed inside the wards, adding to, rather than diminishing the evil.
We represented the great filthiness of the prisons,
which are full of the most disgusting vermin,
and do not appear to have been cleaned for years.
We suggested that as they have several large prisons, totally distinct,
they might easily confine the women in some, and the men in others;
taking care to make an entire separation between the older offenders and the young prisoners,
and those confined for small offences; and to keep out of doors the soldiers on guard.
To this the Governor replied, "`all this can be done.`"
On our being with him today, he said: "`all these things have been done.`"
// lint-disable scan-errors "lime"
The prisoners have been furnished with brooms, brushes, water, lime, etc., etc.;
they have themselves thoroughly cleansed their prisons,
and care has been taken that daily attention shall be paid to cleanliness henceforth.
The Governor seems disposed to have many other improvements made,
and especially to prevent, as far as he can,
the oppression of many of the country people coming to the town, by the police officers,
who, for very small offences, or even on suspicion, send them to these prisons,
where they are soon stripped of the few valuables they may have, even to a hat,
or a coat.
He has taken active measures to suppress this.
Thus, with gratitude to the Lord,
we see a little fruit resulting from our painful labours among these sufferers.
We have also succeeded in having many released,
who had been in prison for months because their passports were irregular,
or they had come to the city without them.

The Governor has considerably reduced the number of places where strong drink is sold,
confining these, as formerly, to cellars where no seats are allowed.
No kind of gaming is permitted,
nor anything that can induce the poor objects resorting there,
to remain longer than to swallow their fiery water.
During the absence of the Emperor, the Minister of Finance,
in order to increase the revenue arising from the consumption of strong drink,
had allowed the sale of it in upper rooms, coffee houses, etc.,
to the great demoralization of the people, who would be ashamed to go into the cellars.
The very day of the Emperor`'s return to Petersburg, the Governor said to him,
"`which do you prefer, the increase of your revenue,
at the expense of the morals of your subjects?
or their well-being, in not being enticed to evil?`"
The Emperor readily replied,
"`that the well-being of his people was far more dear to him than his revenues.`"
On which Miloradovitch said,
"`in your absence they have considerably increased the consumption of ardent spirits,
by allowing them to be sold out of the cellars;
and thereby drunkenness and vice have proportionably increased; but,
if it is agreeable to you, I will have those places shut up.`"
"`Do so,`" said the Emperor.
That very evening the Governor had it done.

Having told us that the Countess Potozka desired to be acquainted with us,
he accompanied us to her palace.
Her principal residence is in the Crimea, where she has large estates,
with a numerous population upon them.
She has established schools among her people,
and appears to feel concerned for their moral and religious improvement.
She has some knowledge of our Christian principles, and told us that she has, for years,
ceased to use formal prayers,
but that she silently waits for qualification to approach the throne of grace,
and to put up her prayers to the Lord, in whom is her only hope.
She is in the frequent practice of religious retirement.
It is on her grounds that John Howard was buried, near Kherson.
He took the jail fever there, during his visits to the prisons.
The Countess readily accepted some books we presented to her, treating of our principles.

On our return to our lodgings we found a messenger from the Emperor waiting for us,
with the information that he would receive a visit from us at six this evening.
At the hour appointed another messenger came to show
us the way to the private apartments of the Emperor.
We found him alone, and he received us with great affability,
"`like old friends,`" he said.
He made us sit down on a sofa on each side of him,
and recurred feelingly to the visit we paid him in London, by which, he said,
his mind was encouraged and strengthened,
under the trying circumstances then attending him.
He made many inquiries of a religious character,
which evince his concern to obtain a saving knowledge of the blessed Truth;
he has a good understanding of the Scriptures,
and clear views of that salvation which is through faith in our Lord Jesus Christ,
in whose grace and merits alone he trusts.
The influence of the Holy Spirit is a subject on which he appears to delight to dwell,
being, as he calls it, one of the corner stones of the Christian religion;
for if a man has not the Spirit of Christ, he is none of his;
and if the things of God can only be known by the Spirit of God,
then what hope of salvation can a man have who is destitute of or disregards that Spirit?
He inquired of the nature of our various religious
engagements since we have come into Russia,
and in what state we had found the public establishments, particularly the prisons.
We were glad to have the opportunity to acquaint
him with the wretched situation of several of these,
and of the poor-houses also.
We alluded especially to the prison at Abo; we showed him the sketch, taken there,
of a man with his fetters upon him.
The Emperor was much affected, and said, "`These things ought not to be;
they shall not continue so.`"
We also represented the case of the man there who
had borne these heavy chains eighteen years,
for having threatened, in an unguarded moment, to strike his mother.
The Emperor appears to be much interested in the subject of public education;
we therefore told him of the visit we made to the Lancastrian school,
and how greatly pained we had been in noticing there, and at the printing office,
that their lessons were a selection of sentiments calculated to demoralize the people,
and bring them into a far worse state than that in
which their ignorance places them at present;
that,
on this account we had been induced to begin to prepare a selection from the Scriptures,
under the name of "`Scripture Lessons;`" we then gave him
a brief outline of the contents of the little work.
The Emperor remained a few moments absorbed in deep thoughtfulness, and then said,
"`You have done the very thing that I was anxious should be done;
I had for a long time been contemplating how that mighty engine,
general public education, might be used for the promotion of the kingdom of Christ,
by bringing the people to the knowledge of the dear Redeemer,
and to the practice of Christian virtues; send me immediately what you have prepared.`"

The Emperor spoke in strong terms of his regard for Daniel Wheeler,
and considered his coming to Russia as a blessing to the people.
"`It was not,`" he said, "`the cultivation of morasses, nor any outward object,
that led me to wish to have some of your Friends come and settle here; but a desire that,
by their genuine piety and uprightness in life and conversation,
an example may be set before my people for them to imitate,
and your friend Wheeler sets such an example.`"
After this, he said, "`Before we separate for the present,
let us spend a short time in religious retirement together.`"
We were disposed to do so, for we felt the Lord`'s presence and power very near;
we continued for a time in solemn silence;
our spirits were contrited together:--after awhile,
feeling my mind clothed with the Spirit of prayer and supplication,
I bowed before the Divine Majesty on my knees; the Emperor kneeled by my side;
we had a humbling and grateful sense that the Lord
condescended graciously to hear our prayers;
we continued a short time in silence afterwards,--when we retired,
the Emperor expressing a desire shortly to be with us again.
We were about two hours with him.

14th of Second month.
During the last few days, besides attending, as usual, the meetings at Ochta,
we had several others in this place,
and have visited large establishments under the especial care of the Empress-mother,
particularly her schools for young women; one is for the nobility,
and contains five hundred girls; another is for the daughters of the burgesses.
They remain in these schools several years,
and their education extends to an acquaintance with domestic
economy and the general management of household affairs;
the literary education they receive is on a liberal scale; they learn several languages,
particularly the French and German.
Some females of high rank, like many of the men,
can speak fluently eight or ten different languages.
I have been with some who spoke fourteen with ease.
The Russian is a difficult language,
but it gives great facility to the well pronouncing of others.
We felt a great interest in these young persons;
their minds appeared open to receive our communications, offered in Gospel love;
we were accompanied in these visits by the Chamberlain of the Empress.
My dear friend, William Allen, is my fellow-helper in these religious engagements;
soon after we came into Norway,
he felt constrained by the love of Christ vocally to proclaim His name among the people,
in the more public or private religious opportunities we had.
By keeping close to the guidance of the Divine Spirit,
and being faithful to the Lord`'s requirings,
he has grown in the gift of the ministry of the Gospel committed to him;
he exercises it in much watchfulness and humility;
he is indeed a great comfort to me as well as a co-worker.

By appointment of the Empress-mother, we went to her palace;
Count Skotchinsky received us, and we were soon introduced to the Empress,
in her private apartment.
Her attendants kept at a respectful distance.
She was at first tenderly affected on seeing us,
feeling keenly the removal by death of her daughter, the Queen of Wirtemberg,
whom she knew we had seen in London.
Having heard that in the course of my journey I intended to be at Stutgard,
she requested I would not omit to visit her motherless grandchildren.
We could but commend the order and care maintained
in the schools under her patronage that we had visited,
but stated that we greatly regretted that the education of the girls,
among the mass of the people in this city, is totally neglected;
that we had not been able to hear of one single school for them, and that we found,
on inquiry, the same neglect prevailed throughout Russia.
To this perhaps might be partially traced the miserable,
comfortless manner in which many of the people live,
and the prevalent habit of drunkenness among them; whereas,
were their houses made comfortable by the good management of the wives,
they might be induced not to spend their time in improper places, and in bad company;
mothers, having received a virtuous education,
might extend the same towards their offspring;
we therefore urged the necessity for girls`' schools, under the care of pious,
well-concerned female teachers.
We acquainted the Empress also with the great exposure of females in prisons;
how many girls were sent there for very trifling offences,
even a simple informality in their passports;
they might enter the prison with virtuous habits, but leave it initiated in vice.
We also told her that visits to those prisons by females,
capable of advising and instructing such poor sufferers, might be highly beneficial;
to all which the Empress feelingly assented.
Conversation on serious and religious subjects opened an easy way for
us to draw her attention to things that pertain to the kingdom of God,
and to eternal life, and to represent to her how important it is,
that by the grace of our Lord Jesus Christ and our cooperating therewith,
we be found prepared to appear before God in a state of acceptance,
whenever he permits the slender thread of our lives to be cut.
She was serious and tender, and on parting from us said,
"`I wish to be kept fresh in your prayers.`"
The whole of our conversation was in French, which she speaks very well;
as is generally the case with people of rank here.

This evening our little meeting, held at our lodgings,
was a refreshing season from the Lord`'s presence.
He condescends to give us to see, with some clearness,
the way through which we are to be directed when ready to depart hence,
and we hope the time for it is drawing near;
dear Allen also sees with clearness that his place of religious duty is to keep with me,
at least till we reach the Grecian Isles.

First-day, 21st. Our meeting today at Ochta was held in silence.
O how precious it is to feel that blessed promise verified,
"`They that wait on the Lord shall renew their strength.`"

26th. Among some of the interesting persons that we have met with the last few days,
is the Baron Stackelberg; he is from Revel, in Esthonia,
a man of piety and great benevolence,
and is the person who first set free the serfs on his estates;
he was for a while subjected to many difficulties, even to persecution,
from his neighbours;
but his example has been followed by many who had at first cried out loudly against him.
The improvement made by the peasantry in those parts,
since they were liberated from their servitude, is great.
The first man to whom the Baron gave freedom has become pious and useful;
the Baron considers him as his right hand man,
in the introduction and general care of the schools on his estates;
he has also an establishment for the purpose of training schoolmasters for other places.

7th of 3rd month.
Several strangers came to our meeting today.
I was enlarged among them in preaching Christ, the Saviour and Redeemer,
who indeed sits at the right hand of God in that glorified
body wherewith he ascended up to God after his resurrection,
but is also very near to us, dwelling in the hearts of his followers by faith.
I therefore very pressingly exhorted them to walk and live in the Divine fear,
as in his presence.

9th. We spent, as we usually do once a week,
about two hours with Prince Alexander Galitzin.
He told us that the Emperor had given orders for the immediate translation from
the Slavonian into the Russian language of those portions of the Bible,
in our Scripture Lessons, that are not already translated,
and to have those Lessons immediately printed.
The New Testament in Russ is now printed, but the Bible is not yet done;
the translation not being completed.
The Emperor being apprised that the time of our departure is near,
has directed the Prince to have letters of introduction prepared for us,
addressed to the Governors of the Provinces, through which we travel,
and to his ambassadors to those nations where we may come, recommending us to them;
the expressions used by the Prince are, "`to recommend you, as being well known to him,
the Emperor.`"
We have also called on the Metropolitan, and Philaret the Archbishop,
to take leave of them.
Our interview with the latter was truly solemn and very contriting; he unfolded to us,
in much Christian freedom and tenderness, his religious scruples and exercises,
and during a short time spent in silence,
we witnessed the fellowship of the Spirit with one another,
for the baptizing power of Truth was over us; he was much affected on parting,
took us in his arms, and gave us a kiss of Christian love.
After our return to our lodgings he sent us short letters to the
several persons whom he knows to be pious and spiritually minded,
and who are on our way towards the South of Russia.

14th. Our departure appearing to be at hand has brought
us under very close engagements during these last days;
we have had many services of a public and more private character; some of these partings,
which most probably are a final separation from one another, have been very solemn;
we rejoice that we can entertain the hope,
that we leave behind us a seed that the Lord has visited.
Many of our private opportunities are also tendering seasons;
the one we had this evening with the Emperor was particularly so.
Having received information that he would be pleased to see us this evening,
we went at eight o`'clock, the hour appointed.
He again received us in his own apartment,
to which we went by a private door and staircase, without passing among the guards,
or the persons attending at the palace; no one, anywhere,
has appeared to take offence at our keeping our heads covered.
He received us with cordiality as before.
One of the first things he said was,
that the chains we saw on the prisoners at Abo were now removed,
and that the man we told him of, who had been eighteen years loaded with fetters,
was now liberated,
and orders were given for the better treatment of the prisoners generally.
He requested also, that in the course of our visit through Russia,
we would communicate directly to him, whatever we may notice in the prisons,
or other places, that we may think proper to bring before him.
The Military Governor had related to him what we had said of the
improvements that might be made in the prisons in Petersburg,
and he was pleased that the Governor had so speedily attended to it; he added,
that the Empress, his mother,
had given him some relation of the visit we had made to her,
with which she had been very much pleased.
She told him also what had been said respecting the
neglected education of the daughters of the poor,
which she had taken much to heart,
and he also felt so much the necessity of a speedy remedy,
that yesterday he made appropriation of money sufficient to establish
and support six schools for that class in this city,
so that they might receive a virtuous and religious education.
He said he had carefully looked over the Scripture Lessons that we had prepared,
and was delighted with them; that had we come to Russia for no other service than this,
it was accomplishing an important work;
that he would have these Lessons introduced for the use of all the schools in his dominions.
He also gave us an account of the manner in which he was educated from a child,
under the care of his grandmother, the Empress Catherine.
The tutors placed over him, he says, were men possessed of some good qualities,
but they were not Christian believers,
consequently his early education was calculated to estrange him from serious impressions,
and yet, after the manner of the Greek Church,
he was trained up in the habit of repeating some formal prayers, morning and evening,
but he disliked the practice of it; several times, however, after having gone to rest,
he so strongly felt the convictions of sin,
for the impropriety of some parts of his conduct during the day,
that he was constrained to rise from his bed,
and on his knees with tears to entreat the Lord`'s forgiveness,
and strength to act with more watchfulness.
These strong convictions continued with him for a length of time; but, by degrees,
for lack of attending to them, they became more and more faint; with dissipation,
sin gained more and more ascendency over him; but in the year 1812,
the Lord`'s visitation in love and mercy was renewedly
extended to him in a powerful manner.
It was about that time that a pious person,
(it was the Prince Alexander Galitzin who had been brought
up with him,) recommended him to read the Scriptures,
and gave him a Bible, which he had not seen before.
"`I devoured it,`" said the Emperor, "`finding in it words so suitable to,
and descriptive of the state of my mind.
The Lord by his divine Spirit was also pleased to
give me an understanding of what I read therein;
it is to this inward Teacher alone that I am indebted;
therefore I consider Divine inspiration, or the teachings of the Spirit of God,
as the sure foundation of saving knowledge.`"
He said much more on these subjects in a feeling manner.
We entered pretty fully into the nature of the peaceable kingdom of Christ,
and to what the Spirit of the dear Redeemer, who is Love,
would lead all those who are obedient to his dictates; on which he stated,
how great his soul`'s travail had been that wars
and bloodshed might cease forever from the earth;
that he had passed sleepless nights on account of it,
deeply deploring the woes and misery brought on humanity by war,
and that while his mind was bowed before the Lord in prayer,
the plan of all the crowned heads joining in the conclusion to
submit to arbitration whatever differences might arise among them,
instead of resorting to the sword, had presented itself to his mind in such a manner,
that he rose from bed, and wrote what he then so sensibly felt;
that his intentions had been misunderstood or misrepresented by some,
but that love to God and to man was his only motive in the Divine sight.
He was in Paris at the time he formed that plan.
We had spent a considerable time conversing on these very important subjects,
when he said, "`we are then going to be soon separated in this world,
but I am a full believer that, through the Lord`'s Spirit, we may,
though separated one from another, feel the fellowship and communion of spirit;
for with the Lord there is no limitation of space.`"
He requested that we would write to him as to a Christian friend,
through Prince Alexander Galitzin.
"`Finally,`" said he, "`I have one more request to make, that before we separate,
we silently unite once more in waiting on the Lord,
if so be that he condescend to give us a manifestation of his Divine life and presence,
as he did on former occasions.`"
We were prepared to accede to his request,
for we felt in a precious manner the wings of heavenly love to be stretched over us.
The Lord was present during a solemn silence that came over us;
our souls were very reverently prostrated before him;
he himself ministering to us in a most gracious manner.
After a while, in the love of Christ,
I felt constrained to impart a few words to the dear Emperor for his encouragement,
that he may hold fast in the ways of the Lord unto the end,
fully relying on the efficacy of his Divine grace to preserve him from all evil,
and to strengthen him for every good work.
He was bathed in tears; then dear Allen, on bended knees,
supplicated the Lord on his behalf, and that of his people.
The Emperor, who had kneeled by him, continued some time thus prostrated,
after William had ceased utterance.
Our separation was solemn.
It is very humbling and wonderful to me,
to see how the Lord has opened a way in these nations where I saw none at all;
truly the promise, "`the Lord will provide,`" has been fulfilled in a remarkable manner;
and besides, a door,
towards the further labours of love that may be required of us in this Empire,
is now open, so far, at least, as this can be effected by the good will of the Emperor;
but to the Lord alone we must look to give us an
entrance into the hearts of those we may visit,
to send forth his help to us,
and his blessing on our feeble efforts to advocate his blessed Truth.
May he strengthen us to plead with our fellow-men to turn to Christ,
from darkness to light, and from the power of sin to himself.

15th. Prince Alexander Galitzin sent us a message last evening that the Empress Elizabeth,
the wife of the Emperor, wished to see us this forenoon,
if we could possibly spare a little of our time to her.
We were very closely engaged,
but the religious feelings I had towards her five years since, when at Carlsruhe,
were still with me,
and the prospect of our departure without having
seen her seemed like leaving something undone,
therefore we readily accepted the invitation.
We went to the palace this morning,
and she received us in her private apartment in a very modest manner,
even apologizing for her request to us to come to see her;
she had for some time wished for such an interview, but had been fearful to propose it;
what she had heard of my visit at Carlsruhe made her regret not to have seen me there,
and now, what the Emperor told her of us induced her to request this visit.
Her heart was tender, and prepared of the Lord to receive what, in his love and counsel,
we felt to be our religious duty to impart to her; she was bathed in tears.
From what she told us, it is evident that Jesus, the Saviour, is precious to her;
she is of a retired character, is seldom seen in public when she can avoid it;
her dress generally is very simple; when she goes out she has only a plain,
two horse carriage, with the simple cipher E upon it;
whereas all the nobles have generally four horses to their equipages;
the Empress-mother has six.
The Empress Elizabeth told us how frequently she envied the humble
station in life of those maidens who carry the milk about St. Petersburg,
in order that she might live in privacy and religious retirement,
which she has not in her power to do now.
This has been a very satisfactory visit.

We dined at John Venning`'s; none were present besides his family,
and Prince Alexander Galitzin, Papoff, Paterson, and the widow of a pious clergyman,
who is now the companion of the Empress Elizabeth;
through the Emperor she had heard we were to dine here, and had invited herself,
as she said, though she is a frequent visitor at the Venning`'s. She is a pious woman,
who has learned both in the school of affliction and in that of Christ;
the Empress is much attached to her.
The Prince gave us several more interesting particulars respecting the dear Emperor;
among others,
the peculiar circumstances attending the renewing of those religious impressions
that of latter years have been of an abiding nature with him.
When the information was received at Petersburg that
the armies of Napoleon had entered Moscow,
a general panic came upon the inhabitants,
and they packed up their valuables to take their flight into some more secure place;
for they expected the French would soon march for that city.
The Emperor was preparing to go with the body of troops collected there to oppose them.
Prince Alexander Galitzin had at that time many men employed in repairing his palace,
which he continued calmly to go on with, while so many others were panic-stricken.
Some envious persons told the Emperor what he was doing, and that he must be a traitor.
He went to the Prince, and queried, "`Galitzin, what are you doing?
what means all this?
every one prepares to flee, and you are building?`"
"`Oh,`" said the Prince, "`I am here in as sure a place of safety as any I could flee to;
the Lord is my defence, in him I trust.`"
"`From where have you such confidence?`"
replied the Emperor, "`who assures you of it?`"
"`I feel it in my heart,`" answered the Prince,
"`and it is also stated in this Divinely inspired
volume`"--holding forth the Bible to the Emperor.
By some inadvertent motion of the hand, the Bible fell upon the floor--open.
"`Well, permit me,`" said the Prince,
"`to read to you in that very place on which the Bible lies open before us.`"
It was the ninety-first Psalm; on hearing which,
the Emperor stood for awhile like a man astonished.
The army, during that time, was marching out of the city.
It is the usual practice on such occasions,
or when the Emperor is to be absent for a length of time,
that the last place he leaves is their great church.
He repaired there;
the portion of Scripture read on the occasion was again the ninety-first Psalm.
The Emperor sent for the priest, and queried,
"`who told you to make choice of that particular passage of Scripture, this day?`"
He replied, "`that nobody had done it,
but that he had desired in prayer that the Lord would direct him
to the particular portion of the inspired volume he should read,
to encourage the Emperor,
and that he apprehended that Psalm was the word of the Lord to him.`"
The Emperor proceeded some distance, on his way;
and late in the evening he felt his mind under great seriousness,
and desired that the Bible should be read to him.
When the person who came in for that purpose began, he also read the ninety-first Psalm.
The Emperor, interrupting him,
queried "`who told you to read this?--has Galitzin told you?`"
He replied that he had not seen the Prince, nor had anything told him what to read;
but that on being told he was sent for to read to the Emperor from the Bible,
he had desired that the Lord would direct him to what was most appropriate for the occasion,
and accordingly he had selected this portion of Scripture.
The Emperor felt astonished at this, and paid the greater attention to what was read,
believing that this must be of the Lord`'s ordering;
he was therefore very solemnly and tenderly impressed, and from that time he concluded,
morning and evening, to read privately a chapter in the Bible.
He was the next day with the Princess Metchersky, at Tver.
They agreed to begin the Bible together, and regularly to read it every day,
so that they might both read the same portion, on the same day,
and be able to communicate to one another the particular impressions or reflections,
the reading of the day might have produced.
The Prince tells us that the Emperor has directed proof sheets
of the "`Scripture Lessons`" to be regularly sent us,
that we may see how the work progresses.

16th. Philaret has sent us a feeling, Christian note,
in which he desires "`that the Lord may be with us on our way,
as he was with his two disciples on their way to Emmaus.`"
The Metropolitan has also sent us a Christian farewell.
In the afternoon a number of persons joined us at John Venning`'s.
We had a very precious and solemn religious opportunity together;
our beloved friend, Daniel Wheeler, who was with us,
closed it with a very precious offering on his knees before the Lord,
ascribing praises and thanksgiving for the help granted to us, his servants,
for the important work in which we have been engaged in this city; humbly praying,
that He would be pleased to bless the work to his own glory, be with us who go,
and be with him also, now going to be left behind,
separated from his beloved brethren in person, but not in spirit.

--

At half-past six p.m. they got into a cabitzsky, a kind of large covered sleigh,
which they had purchased for the occasion, and,
"`having bid an affectionate farewell to all those dear friends,
who kept near to them to the last,`" they left Petersburg
for Moscow and the south of Russia.
