== Chapter XXXIII.

Third Visit to Europe

The Crimea--Karaite Jews--German and Swiss Colonies--Return to Perekop--Kherson--Nikolaiev--Odessa

Arrived at the chief scene of attraction in the Crimea,
Stephen Grellet and his companion at once resumed their accustomed work.
In the spirit of the Apostle, who--without giving up any Christian principle,
or lowering the standard of Gospel requirements,--was "`made all things to all
men that by all means he might save some,`" they freely mingled in religious
fellowship with all classes and denominations that came in their way,
both among the rich and the poor, "`ready, as much as was in them,
to preach the Gospel`" to all.
Of their interesting labours in those parts, and the conclusion of their visit in Russia,
at Odessa, Stephen Grellet gives the following description:

Simferopol, 5th of Sixth month.
This place contains four thousand inhabitants, who are mostly Tartars and Turks;
they have four mosques.
We find here some of the Spiritual Christians, here called Malakans.
One of them, a nice and intelligent young man, speaks some French.
They have Bibles and Testaments in some of the Eastern languages,
but they find very few of the Mahometans willing to read them; they will read written,
but not printed books.
One of the Malakans saying that he was formerly among the Duhobortzi,
I inquired of him how he had become convinced of his errors;
he answered with great energy, "`I had the Bible put into my hands; I read it,
and is it possible to read the Bible,
and not be convinced of the great errors under which I was?`"
We have had several very interesting religious opportunities with this people;
they give us the same answers to the questions we put to
them which their brethren at Ekaterinoslav did;
they have also given us much information relative to the great persecutions they
endured previous to the Emperor Alexander`'s interfering on their behalf;
in some distant governments,
his benevolent views towards them and his orders in their favour have been evaded,
so that some of their families are yet separated by banishment.
We have several copies of the New Testament in Russ just printed;
they were sent to us at Ekaterinoslav.
These people are delighted with them;
one of them read to the others in the Gospel of John.
This place, formerly called Akmetchet,
is situated at the entrance of the narrow neck of the Crimea.
Till the days of Catherine, the Tartars were numerous in all these parts,
and were once a powerful people.
As we have to pass through it again, we feel most easy, for the present,
to go to the further end of the Peninsula.
The Secretary of the Governor kindly takes charge of the greater part of our baggage,
which we need not carry with us.

We set off early in the morning of the 6th of Sixth month, for Baktchiserai.
The country is beautiful, rich and fertile, and well cultivated;
there are very fine vineyards, and lofty trees on the high ground.
This town is very ancient; it was the capital of old Tartary,
where their Khans used to reside; it is peculiarly situated,
lying in a deep and narrow valley, between two high hills;
one is composed of rocks of a soft nature,
which the rain has worn into a variety of fanciful shapes;
in some places the rocks project from twenty to thirty
feet over the houses that are built below;
others rise perpendicularly,
and houses of three stories with apartments are cut into them.
No women are seen in the streets without being covered with thick veils,
and these are of the poorer class; the men are busily engaged in their shops,
sitting cross-legged on pieces of matting or carpet;
their principal business appears to be the manufacturing of a variety of morocco leather,
and making slippers of it, which everybody here wears instead of shoes.
We took a police officer, a Tartar who speaks the Russian language,
which very few here do, to accompany us to "`the Fortress.`"
It is a place inhabited by Karaite Jews.
We went on foot, for a carriage could not travel that road.
The narrow valley between the two high hills continues about two versts beyond the town;
on getting out of it, we came among a large company of gipsies;
they had their tents pitched, covered with skins;
they are much the same people as those I have seen in England, Sweden and Russia,
except that some of them appear nearly black;
but this is said to be owing to their exposure to the weather and the hot sun,
as the children, generally, are nearly naked; they are, like other gipsies,
very fond of music.
Going still further, our way became narrower, and the rocky hill on our right higher,
and rather projecting over us than perpendicular.
Here there is a large Greek monastery cut in the rock;
the only door of entrance is about thirty feet above the ground;
the approach to it is difficult,
so that two or three men could defend it against a large body;
there is no access to the door but by a rope-ladder, let down for the purpose;
to attempt it by ropes from the top of the hill is not possible,
as these would hang perhaps twenty feet from the sides of the hill;
formerly many monks resided here, but now there are only three.
The country near is perforated by deep winding caves.
Some of them extend for miles underground.
It would be very unsafe for anything to enter unless
he was well acquainted with their various windings.
It is supposed that in times of persecution, and also of civil wars,
they were formerly used as places of resort.
Further on is seen, what is called "`the Fortress.`"
The path to it is steep and narrow, among the rocks; indeed it is so narrow,
that only one mule or horse carrying their leather bottles of water, can pass it.
We walked it in "`Indian file.`"
It has the appearance of a strong wall from sixty to eighty feet high; but it is a solid,
hard rock.
The entrance is through an iron door, leading to a narrow winding way,
cut out to the top of the rock, upon which stands the town.
It is inhabited by Karaite Jews.
The surface extends some distance.
The houses are two, three, and four stories high.
The windows have blinds or bars, so that none of the inmates can be seen.
We did not see a woman out of doors.
Arrived in the town, we sat down in the market-place,
for we were much fatigued by the walk and the powerful sun.
Some men, after a while, came to look at us, and soon after their High Priest approached,
and invited us to go into the synagogue, speaking to us through the medium of our Tartar,
who translated again to our Pole, and he to us.
His name is Isaac Covish.
We were soon joined by other Rabbis and Jews.
They have another synagogue near, one not being sufficient to contain them all.
They are about one thousand men, besides women and children.
They tell us that they have evidences, from their Records,
that their ancestors have been on this rock for more than nine hundred years; but,
by their traditions,
they trace their coming here to the time when Titus came against Jerusalem.
They differ much from other Jews.
Like that people formerly, they till the ground.
They have gardens, vineyards, ploughed fields, etc.
They take great care in the religious and moral education of their children.
Besides having the Law written on parchment, kept in the ark, which they showed us,
they have the Old Testament printed in books,
and each of their children has a copy of it.
It contains nothing but the simple Scriptures: none of the Rabbinical additions,
with which they do not unite.
They told me that our own Bibles are a very faithful version of theirs.
We have been told by the Governor and Police officers at Perekop and other places,
that these Jews are very exemplary in every part of their conduct;
they know of no instance of any of them being ever
brought before them for misdemeanour of any kind.
A very similar testimony is given of the Malakans wherever they reside,
so far as we have been able to hear.^
footnote:[According to Oliphant,
the Karaite Jews "`are remarkably and honourably distinguished by their probity,
and enjoy everywhere so high a reputation,
that throughout the Crimea the word of the Karaite
merchant is considered equal to his bond.`"]
A large number of the Jews collected about us,
and our conversation became of a more serious nature, chiefly with the High Priest;
he fully believes, he said, in the operations of the Divine Spirit, and that the Lord,
by the prophets, bears a clear testimony to it;
among other prophecies he mentioned that of Joel;
he also holds the sentiment that if all men were obedient
to the teachings and guidance of the Holy Spirit,
there would be no difference between Jews and Gentiles,
for all would bring forth the same fruits,
all would bring the same acceptable offering unto the Lord.
Ho was told that he must then believe that the prophecy of Joel was now fulfilled,
"`It shall come to pass in the last days, says the Lord,
that I will pour out of my Spirit upon all flesh,`" etc., etc.,
for we are now living in these latter days;
this led us to speak of the coming of our Lord Jesus Christ,
and the prophecies respecting him, the manner of his coming, the end for which he came,
etc., etc.
Among others, reference was made to this Scripture testimony:
"`The sceptre shall not depart from Judah, nor a lawgiver from between his feet,
until Shiloh come,
and unto him shall the gathering of the people be.`"--Gen.
49:10. He well knew that the sceptre had departed from
Judah some time before the destruction of Jerusalem by Titus,
that Christ had then come on the earth,
and in him was so literally accomplished all that the prophets had written of him,
that it might appear as if they had given a description of what had already come to pass,
rather than of what was not fulfilled till many centuries afterwards.
He remained silent and pensive for a length of time, then said,
"`I know not what to say.`"
We had some further serious conversation,
and on parting he desired that we might not forget
to visit some of his people further on in the Crimea,
expressing his satisfaction with our visit here; others did the same.
We parted in much affection,
greatly regretting that we could not have an easier
way to communicate with this interesting people,
what we said to one another having to pass through several interpreters;
yet from their answers we could judge that they had understood us.

On our way back we had some religious conversation with our Tartar;
he had been brought under some sensibility by what
had transpired during our interaction with the Jews,
and he made some inquiries relating to our Lord Jesus Christ.
In Baktchiserai they have many mosques; some are small,
but two especially are very large;
formerly they were very strict in the regular attendance
at all the stated hours of prayer,
five times a day; and those who did not conform,
unless prevented by sickness or very good reasons, were beaten with rods; but now,
since they are under the Russian dominion, they have their liberty.

7th. We came yesterday evening to Sebastopol; the road is through a beautiful valley;
we had a ferry to cross before entering the town,--a
most convenient sea-port on the Black Sea.
It contains twenty-five thousand inhabitants, but the greater part belong to the navy;
there are two thousand merchants, most of whom are Jews.
We had a letter for the Admiral who commands the place; he received us with kindness,
and gave us free access to such places as we felt it our duty to visit; a serious person,
who speaks the French language well, accompanied us as interpreter.
We visited their large hospital for sailors, and three prisons;
we had several religious opportunities with the inmates;
and a particularly satisfactory one at the Admiral`'s house in the evening, after tea;
a number of persons had collected on the occasion, among them were some Greeks;
several were in a tender state of mind.
We had also satisfaction in a visit to the children of the soldiers and sailors;
we feel much interest in the rising generation,
and great is our desire that these young men may have virtuous principles inculcated,
and that they may come to the saving knowledge of the Truth,
as it is in Jesus Christ our Lord.

9th. We returned to Simferopol, where also we visited the prisons, schools, and hospital.
We had a very interesting time with the Malakans;
it is surprising how well they are acquainted with the things of the kingdom of God,
and to notice the propriety of their quotations from the Scriptures,
in support of their various Christian testimonies.
They have given us, in writing, a short account of their principles,
as well as copies of letters they have received from their brethren in distant parts,
in which genuine piety and great religious sensibility are exhibited.
We had a solemn meeting among them; the Lord owned us by his presence.
We were also with the Vice-Governor and his wife, who are serious young persons.

Theodosia, 11th. On our way here we stopped a short time at Karasu Bazar,
a Tartar village, built in the Asiatic style; it contains ten thousand inhabitants,
three thousand of whom are Greeks and Armenians, with some Jews.
We visited their schools and poor-houses.
Many of the Tartars and Jews met us at the former.
We embraced the opportunity to preach the Lord Jesus Christ,
and to direct them to that grace and truth which came by him.
Among the Armenians we had a solemn season; their Bishop met us; he is a pious,
sensible man; he was brought into much tenderness,
and parted from us with great affection.
Thus, in a few hours,
we had an opportunity of proclaiming the salvation that comes by Jesus Christ to Tartars,
Mahometans, Jews, Greeks and Armenians! may the Lord bless his own work among them all!
We arrived at Theodosia in the evening.
Governor Engel, a valuable man, gave his assistance in our various religious engagements,
acting as a faithful interpreter.
O how graciously the Lord provides for us qualified persons without whose
kind aid we could not have any religious conversation with those we visit.
We went first to the prison and hospital;
then to a school for the children of Karaite Jews, where we also met their parents;
we had a satisfactory interview with them, and another with the Tartars;
this was held in their mosque, a very plain house inside; it has no images,
only a few words on the wall,
proclaiming that "`God is great and good;`" they
were attentive to what we communicated to them,
and gratefully received some books of a religious character.
The Jews did the same.
The Governor gave us the same good account of these Jews that we had before received;
their moral character stands high in this neighbourhood.
In the evening we had a time of religious retirement with the Governor and his family;
he appeared to feel what we had to impart on the occasion,
and gratefully accepted some of our books;
we frequently place some of these in their public libraries, in Latin, German,
and French; we also gave the Testament in Hebrew to the Jews,
and in Greek to the Greeks and Armenians.

12th. This morning early we set off for the German and Swiss colonies.
Governor Engel kindly gave us a Greek and a Tartar to accompany us, and to interpret.
These colonies lie out of the public road.
Heilbrunn, the first we came to, thirty-six versts from Theodosia,
is settled by emigrants from Wirtemberg.
The people were at work in the fields,
but as soon as they heard that we wished to see them, they repaired to the schoolhouse,
used also for a place of worship.
They have no minister among them at present,
but they nevertheless attend their meetings for Divine worship with great regularity.
We understand that the other German colonists hereaway are similarly circumstanced.
Our silent sitting together was very precious.
They are acquainted with spiritual worship.
We had but little to communicate in the way of ministry,
but we were edified and comforted together.
They were very urgent that we should stay the night with them,
but we wished to go on to the Swiss.
Some of them accompanied us to Zurichthal.
We were a motley group; the German, the Russian, the Greek, the Tartar, the Pole,
the English and the French,--all going the same way, for the same object.
O that people of all nations and languages may thus become banded together,
and harmoniously travel with each other in the one way to everlasting life!

The colonists here came from the canton of Zurich.
Our meeting for Divine worship with them on First-day morning was precious and solemn.
We sat a considerable time in silence together.
Worship in spirit and in truth was performed.
In the afternoon we passed through Rosenthal, a large villaga of Roman catholics,
on our way to Neusatz, another village of Lutherans, who came from about Stutgard.
We lodged that night among them, and appointed a meeting for the ensuing morning,
an invitation which was extended to another settlement of the same people.
Next morning a deputation came from the Roman catholic village to request
that we would not pass them by without having a meeting with them also.
As we passed through their village, my soul was strongly drawn towards them,
but I apprehended they might not be willing to attend a meeting appointed by us;
now we felt prepared to accede to their request.
Like their Protestant neighbours, they have no priest among them.
One comes once a year only.
The meeting in the forenoon was fully attended by the people of both villages.
A Swiss, who speaks French, was our interpreter.
It was a good meeting.
We felt much for these people.
Their care and concern for the religious education of their children appear to be great.
Their lack of a settled minister among them is richly made up,
for in their coming together for Divine worship, their dependence is not on man,
but on the Lord, the true minister of the sanctuary,
and they have evidently made some progress in the Divine life,
under the ministration of his blessed Spirit.

At the time appointed we arrived at the Roman Catholic village.
As we entered it, the steeple bell began to ring.
We expected that the meeting would be held in a private house,
but they told us that no place was more suitable,
or better able to accommodate the people, than their church.
On entering it we found a numerous company already gathered, for it is a large village.
They had lighted their wax candles on the altar, after their usual manner,
though the sun shone very bright.
I did not think much of this.
My mind was under much exercise for the people,
with earnest desire that they might come to the light of the Lord,
and be gathered to the brightness of his arising.
We took seats, facing the people, with our backs to the altar.
After we had sat a while in silence,
we were several times a little disturbed by a man coming
near us to ring again and again the bell of the steeple.
I could not think what the man meant, but at last he told me in Dutch, "`I do not think,
sir, that anybody else will come, for the whole village is here.`"
I was then about rising from my seat; the interpreter stood by me.
The Lord enlarged me in his Gospel.
The people were directed to Christ the Shepherd and Bishop of souls,
the High Priest of our Christian profession, who is very near every one of us,
and ready to minister in the temple of the heart to every one that waits upon him.
My beloved friend William Allen had something very
precious to communicate in these two meetings,
in both of which the people were brought into great tenderness of spirit.
On returning to Simferopol, our hearts overflowed with gratitude to the Lord,
who had enabled us to visit this portion of a seed which he waters from his holy habitation.

15th. This is the third time we have come to Simferopol.
We found here five of the Malakans who have waited several days for our return.
They are a deputation from their brethren,
who reside at a considerable distance in the Government of Tambov,
where there are upwards of two hundred families who profess with them,
and about as many more who are serfs, and meet with them when they can.
They came to these parts to look at the land,
and to see if they could remove to it with their families.
We hope that, by an application to the Emperor, they, and many others of the same people,
will be permitted to enjoy privileges similar to those of the Mennonites.
We believe they might be a great blessing to the benighted Duhobortzi.
They tell us that many among them formerly belonged to that class,
but that the Scriptures being placed in their hands,
they have been fully convinced of their errors.
They say that the name of Malakan is given them because
they abstain from the various observances of days,
fasts, and ceremonies of the Greek church.
Their answers to our inquiries into their religious principles,
entirely coincide with those heretofore given us.
They inform us that most of them can read,
and are in the daily practice of reading the Scriptures in their families.
They confirm the account given us of their great numbers in several Governments,
especially in Astrakhan, the Caucasus, Saratov, etc.

We went fifteen versts to the Vice Governor`'s, accompanied by his secretary;
we had a pleasant visit to his family;
his wife extends a pious care over their very interesting young people.
On our way we visited the widow of a celebrated natural historian;
she continues to feel her great bereavement.
In the evening we had a solemn religious meeting with the Malakans;
to become acquainted and mingle with these dear people would
alone well repay all our toil in coming to this nation.

16th. We left very early this morning for Perekop;
but some of the Malakans were at our door before daylight,
waiting to bid us farewell once more; they also brought us bread for our journey;
this is a very general practice in the Crimea, when departing to go into the desert;
to decline it would give great offence to the givers;
we had procured some ourselves before, but when we saw their sadness at our refusal,
we accepted their free-will offering.
One of their old people, a venerable looking man,
with his long beard and sheepskin covering,
appeared very desirous to go with us a little way; he got in and sat between us;
we could not converse with one another; but there is a language more forcible than words;
he held each of us by the hand; big tears rolled down on his venerable beard;
we rode on several versts in solemn and contriting silence,
till we came to a water which we had to pass,
when he took us into his arms with the greatest affection, kissed us,
and got out of the carriage; on looking back we saw him prostrated on the ground,
in the act of worship or prayer to God; and, after he rose,
as long as we could discern him, he stood with his face towards us, his hands lifted up;
we felt it, as he did, a solemn separation.
May the Lord bless and protect that portion of his heritage,
a people whom he has raised by his own power, and instructed by his own free Spirit.
We visited at Perekop the prison in the fortress, and the hospital, and set off at noon,
on the 17th, for Berislav, where we did not arrive till midnight.
We crossed the Dnieper for the third time at dark;
the only accommodation we could obtain was a dirty yard,
where we spent the rest of the night in our vehicle.

18th. We visited a small prison, in bad condition, and a hospital,
and travelled again over the wilderness to Kherson, where Count de St. Priest,
whom we saw at Ekaterinoslav, at the Governor`'s,
gave us an invitation to make our home at his house;
he is the Governor of this part of the country.
He kindly gave us his horses and carriage to take us to several places we wished to visit.
The Mayor of this city, a valuable man, and a Frenchman too, accompanied us,
as our interpreter.
We visited their several prisons.
That in the fortress, especially, is in a most affecting state;
the poor prisoners are crowded in small rooms, loaded with heavy chains;
the ceiling is not high enough to allow them to stand upright;
many of them have been confined three years;
their meagre and ghastly countenances proclaim their sufferings;
they have not even a few feet of room to walk in,
and are not allowed to go out into the yard; the air is very corrupt,
so that we could hardly breathe it.
They have a large body of soldiers on guard about them.
I have endeavoured to reason with the Commandant of the fortress
on the inhumanity of keeping fellow-beings under such suffering;
if he has not the authority to lessen the weight of the irons on the prisoners,
he might at least place fewer of them in a room, and,
under the strict guard of the soldiers, allow them to breathe fresh air,
during part of the day.
The weather is now very warm and these prisons feel like ovens.
They are now preparing to erect here a monument to the memory of Howard;
this is the place where he caught the prison fever, and where he died of it;
what better monument could they erect for him,
than a prison conducted after the plans he has given.
We intend to represent the whole of this to the Emperor.
We returned to dine at the Governor`'s,
and went afterwards to the Seminary for the sons of the clergy.
The Director and Rector of it are both pious men.
The latter kindly acted as our interpreter to the pupils.

The next day we had an interesting opportunity with about
one thousand five hundred of the children of the soldiers.
They receive a good education,
and some of them become qualified to occupy stations in the civil department.
We thought that religious sensibility was apparent in some of them.
The system of mutual instruction has been introduced among the juniors.
We presented them with fifteen sheets of the "`Scripture
Lessons,`" sent to us at this place from Petersburg,
by order of the Emperor.
We then paid a satisfactory visit to the Mayor,
who had been our kind and useful attendant.
He has a numerous family,
in whom the parents have the satisfaction of seeing the fruits of their Christian care.
We had a precious religious opportunity with them, and then set off for Nikolaiev.
As we were leaving Kherson, two of the Greek priests, whom we had seen at the seminary,
came to bid us farewell,
and to bring us five loaves of bread for our use in the wilderness,
to evince their love and good-will to us.
With much kindness and tenderness they desired that
the Lord`'s blessing might be on our labours of love,
and bring us safe back to our respective families.

22nd. Nikolaiev.
Admiral Greig, Commandant in Chief of the Black Sea and of this place,
received us with kindness.
We had frequently been with his sister at Petersburg.
We met at his house a pretty large company, with whom we had a religious opportunity.
Several of those present were seriously disposed, particularly a young couple:
the husband is a Chamberlain of the Emperor.
We visited several schools, poor-houses, and prisons.
They are in a better condition than those at Kherson.
By the kindness of Admiral Greig,
we are provided with two young men to accompany us as interpreters.
They appear to enter into our religious feelings,
and their spirits are tendered while they interpret our communications.

We have met a number of the Duhobortzi in this place.
They have read the Scriptures, they say,
and have seen the gross errors under which they had been; we find, however,
that their eyes are only partially opened,
but as they appear desirous to obtain the knowledge of the Truth,
we are encouraged respecting them.
They tell us that they know that several of those we visited
on the Moloshnaia now desire to read the Scriptures,
and they think that they see further than their old men and elders.
We had a religious meeting with them, and hope that we had suitable counsel to hand them.
They bear a good character in this place for uprightness.
Our inn here is kept by Jews.
They have a New Testament in Hebrew, which they value much.
We had a good opportunity to preach Christ to them.
They have compared the fifty-third chapter of Isaiah
with several portions of the New Testament,
and are forcibly struck with the minute correctness
of the prophet`'s description of the sufferings,
etc., of Christ.

Leaving Nikolaiev on the evening of the 22nd, they reached Odessa the next day.
Here they were detained by various engagements,
and finally closed their religious labours in Russia.
Stephen Grellet continues:--

Odessa, 28th. We have been occupied these last days in writing several letters;
one to the Emperor,
to give him an account of the miserable condition of several
of the prisons we have visited since we left Moscow.
We have also made a particular statement of our visit to the Mennonites, and the Malakans.
We have sent him an account of the religious principles of the latter,
and a representation of the sufferings to which a few of them continue to be exposed,
in some of the governments.
We have also requested, on their behalf, that he would allow them lands to settle upon,
near the Moloshnaia, or in that district,
and that the same civil and religious privileges should
be extended to them which he has granted to the Mennonites.
As they had hitherto been confounded with the Duhobortzi,
we have pointed out the distinction between them.
We have also once more conveyed to the dear Emperor, before leaving his dominions,
our souls`' solicitude that,
by the grace of our Lord Jesus Christ and faithfulness to the dictates of the Holy Spirit,
he may walk in the Divine fear and counsel,
and so fulfill the great and important stewardship
given him as Emperor over this vast nation,
that he may promote the honour and glory of God and the happiness of his subjects,
and finally obtain, through the redeeming love and mercy of God in Christ Jesus,
the salvation of his soul, and exchange his earthly for a heavenly crown.
We have also written to the Empress Dowager,
and sent her a statement of the great mortality in the foundling hospitals,
and our painful concern at finding that throughout, where we have travelled,
the education of the girls among the mass of the population is totally neglected.
The only places where we found a little attention paid to the girls,
were some of the Tartar towns, and there they only learned to read.
We have also addressed the Mennonites and the "`Spiritual Christians.`"
Our epistle to these will, we hope,
circulate extensively among this interesting class of people.

A letter received from the Danish Ambassador at Petersburg,
informs us that his King and Queen had directed him
to let us know that our epistles to them,
and the books we sent, were gratefully received.
Our time has been taken up in writing several other letters to Sweden, Norway, etc.
We cannot depart from this deeply interesting field of Gospel labour, where many,
among various ranks in life, are rendered very dear to us in the love of Christ,
without communicating once more with them in writing.
May the Lord bless them, and carry on to perfection the work of his Divine grace!

Count Langeron, a Frenchman, Governor-General in these parts,
appears well disposed to afford us all the assistance in his power;
two years since he succeeded here the Duke de Richelieu, now Prime Minister at Paris,
who was much beloved by the people generally; he stood as a father to the colonists.
This town contains forty thousand inhabitants, and looks much like an English city;
the streets are like those in Philadelphia, and have many good houses;
people of various nations are to be met with here.
It is a place of great commerce; the chief export is wheat.

The arrival yesterday of a French ship that touched at Constantinople,
where the plague prevails, has spread an alarm here.
A man on board the ship died of this contagious disease since her arrival;
another is not expected to live, and several others are sick.
We are thus brought under very serious considerations,
for Constantinople is the place to which we had intended to proceed from here;
earnest is our cry to the Lord that,
as he has thus far led us by his counsel in the way that he would have us to go,
he would direct all our future steps.

We have visited here three prisons, hospitals, and some schools;
one of the latter is for girls, and was founded by the Duke de Richelieu:
// lint-disable invalid-characters
it is now under the care of the Abbé Nichols.
My mind was under much distress during some of these visits, the last particularly;
though I felt much openness toward the young women
there in directing them to Christ and to his Spirit,
I cannot divest myself of the apprehension that the
Jesuits have taken a strong footing here,
and that the good intended by this establishment may be marred through them.

2nd of Seventh month.
Such is, we find, the Popish influence in these parts,
that in some colonies of Germans professing Popery, at no great distance from here,
the priests have obliged such of the people as had Bibles, to deliver them up, and they,
the priests, have burned them.
We have thought it proper to give information of this to the Emperor.
They had also a Bible Society in this place,
but by the priests`' influence it has discontinued its useful proceedings.
Notwithstanding these great discouragements,
a few individuals are endeavouring to form themselves again into a Society,
and to resume their labours; what, above all, must be considered the Lord`'s work,
is that about one hundred of the youths, aged from thirteen to seventeen years,
have of their own accord, formed a Society to distribute the Scriptures,
and subscribed their pocket money for the purpose,
which offering they make with cheerfulness.
// lint-disable invalid-characters
Several other boys at the Lyceum would gladly have joined them, but the Abbé Nichols,
who has the direction of it, will not allow it;
yet such at least as have not been prevented by their parents
have sent their pocket money to the Juvenile Society.
Thus children are raised up to promote, by their efforts to distribute the Scriptures,
what the Jesuits are endeavouring to destroy.

5th. We had a very interesting religious opportunity with the dear boys;
some of the parents attended; it was a precious season;
the Lord by his Spirit has visited these children,
and the love of Christ contrited many of them.
We had also a meeting with some of the pious inhabitants;
it was mostly composed of those who belong to the Greek Church,
but Papists were also present; Theophilus, the Archimandrite,
with whom we have been several times, and for whom we had a letter from Philaret,
was also present.
The Lord`'s name and power and his redeeming love was exalted among them;
many hearts were contrited.
In the evening Theophilus came to see us; he is a spiritually minded man,
and our conversation has been to edification.

After carefully weighing the subject before the Lord, craving his direction,
we have felt it to be our right way to proceed, as before contemplated,
over the Black Sea to Constantinople,
believing that the Lord can protect us from the noisome pestilence,
as he has done from many other imminent dangers.
After thus concluding we felt sweet peace,
and have engaged our passage on board a large British ship, the Lord Cathcart,
loaded with wheat, going by Constantinople to Malta.
This evening we hear that three more deaths, by the plague,
have occurred among the crew of the French ship,
and that several others are attacked with it.

6th. We met here a young Englishman convinced of our principles,
but not a member of our Society; he appears to have a tender conscience;
we have had several opportunities with him,
endeavouring to encourage him to walk uprightly in the sight of God and man.
This is a country where men ought to be particularly watchful to avoid giving any offence;
for the police very narrowly watch their every action, though they know it not;
perhaps in no country are the police more vigilant;
but he who endeavours to walk in the bight of God need not fear the eye of man.

7th. We visited General Ingoff, who has all the Colonies under his superintendence;
he was absent when we arrived here; we are much pleased with him; he is a mild,
serious man.
We afterwards went on board the ship, to have our baggage stowed away; she is a large,
fine vessel, lately returned from the East Indies.
This is a commodious port; many vessels from various nations are here at present.

The next day they set sail for Constantinople.
"`I am under no apprehension,`" says Stephen Grellet,
"`that I have left Russia before the right time;
I feel great peace in looking back upon my various religious labours in that Empire.`"
