== Chapter XXXV.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Scio
* Islands of the Archipelago
* Athens

Nearly a month was now occupied by a visit to Scio and Athens,
and some of the intermediate islands.
Of this, and the perilous incidents connected with it,
Stephen Grellet gives the following graphic details:

[.embedded-content-document]
--

We left Smyrna on the 31st of the Seventh month.
The boat on which we embarked is of the shape of a canoe, with two men to row it.
With ourselves and Martini, our Greek, we made five altogether, and with our baggage,
the boat was almost filled.
As it was fine weather it was expected that we should
reach Scio in about twenty-four hours;
a small quantity of provisions was therefore thought sufficient to take with us;
we went on very nicely for a few hours, when the wind began to blow heavily,
and the waves washed over us, to our no small danger;
each of us having a large camlet cloak, we spread them over us and the boat,
making a kind of deck;
at the same time we were busy baling out the water that washed in with every wave;
our rowers meanwhile made great efforts to reach an uninhabited barren spot,
called English Island, which is however pretty large.
We did not discover on it a single shrub or anything green:
perhaps there might have been some grass before the great heat of the summer,
but now everything is parched by the scorching sun.
We were thankful in being able to make a safe landing, for,
very soon after we had done so, the wind increased furiously,
and had we been still at sea, we could not have escaped a watery grave.
We tried to erect a kind of tent with the oars and the sail of our boat,
to protect us from the burning sun.
Very near the place where we were encamped are extensive ruins,
of which very little more than the foundation remains;
it appears there was once a large city on this island;
in the centre of it are the remains of large colonnades,
that supported a great extent of vaults.
The day after our coming to this island, two boats with Turks in them also came to it,
landing at the same place we had done.
My dear companion and the rest of the company had taken a walk to seek for water,
and I was left alone in the tent.
Some of the Turks came and sat down at the entrance of it, having with them fire-arms,
their large swords and poignards;
they began to fire their guns and pistols at blank-marks,
and by their signs urged me to show my firearms; they were beginning to be rude,
when my company, attracted by the firing, returned;
they at first thought I had been murdered; the Turks then retired to their boats,
where they continued during the night--which we passed in some anxiety,
watching their movements; but to our relief, towards morning,
they rowed away to another part of the island.
Our stock of provisions being very small,
we had to limit ourselves to a scanty allowance;
our greatest difficulty was the lack of water; we in vain sought for some;
neither could we discover any fish near the island, nor birds on it;
scorpions are very numerous,
several of these were under nearly every stone that we turned over,
and many were seen in our tent.
In our rambles in search of water we discovered some species of dwarf myrtles.

Our minds are preserved in calmness, stayed on the Lord;
we have the confidence that he can open the way for
our release from this state of danger and suffering.
In his will we feel resigned; with reverent gratitude we can also say,
that if our mouth is dried for lack of water,
our minds are refreshed by his Divine presence;
for truly we feel that our springs are in him, as David said,
"`All my springs are in you, O Lord.`"
Our bathing often in the sea is refreshing.

Eighth month, 3rd. Last evening, we saw another boat landing at some distance from us.
The men appeared very wet by the waves of the sea.
In the dark, Martini, our Greek, went towards them to try and find out who they were.
He discovered them to be coiners of false money.
He says that this island is much resorted to by that class of men, and by pirates.
These men it appears discovered us also.
We being five in number, they did not like to begin their operations so near us,
and early this morning they went to another part of the island.

Scio, 4th. The wind abated last night so as to encourage
us to put to sea again early this morning.
It was hard and dangerous work, till we had succeeded in doubling the Cape,
and were well drenched by the waves.
We reached this island early this afternoon,
with hearts prepared to ascribe thanksgiving and praise to the Lord,
who has sustained us under hunger and thirst, and delivered us from imminent danger.
Blessed forever and ever be his holy name!
Amen and amen!

5th. Accompanied by the British Consul, who is an Italian,
we went to see the Turkish Governor, and gave him the letter we had from Ali Bey.
He received us with affability, and kindly offered to assist us in whatever way he can,
while we continue on this island.
We find here a Greek Neophyte, named Bambass, a very interesting, sensible,
and pious man, of Christian liberality.
He takes great interest in the education of the children of his nation,
particularly of the girls.
That sex has been so neglected in this particular, that there are but few women,
even among the wives of wealthy Greeks, who can read.
Many of the men have received a good education in several parts of Europe.
Bambass is at the head of the schools here.
With much labour he has compiled a book of ethics from the ancient Greek philosophers.
His extracts contain the best sentiments out of their works.
He has a printing-press, and he intends this work for the use of the schools.
It has brought us under much concern that the minds of the
youth should be thus early directed to heathen writers,
instead of having instilled into them the pure principles of Christianity.
Where can we find any so pure, and so excellent as in the Holy Scriptures?
We visited also the five Ephori.
These are chosen yearly by the inhabitants of the island,
from among the first rank and the most worthy of their citizens;
though at the time of their nomination they may reside in other places,
or be engaged in their mercantile pursuits in various parts of Europe, the Levant,
etc.--yet on being nominated to the office, they immediately repair here.
The internal government of the island devolves upon them.
They purchase this privilege from the Turks,
whose Governor has the citadel in his possession.

8th. Feeling deeply the vital importance that an education given
to young people should be grounded on Christian principles,
we have prepared in the Greek language the same Scripture
Lessons we had compiled in Russia.
We have spent nearly the whole of these last few nights in completing them.
We have presented them to Bambass,
telling him also of our first inducement for preparing them in Russia.
He examined them with much attention, then said,
"`This is the very thing that is needed,--surely Divine Providence has sent you here.`"
Then, in the most noble manner, he concluded to lay aside his own work,
compiled with so much labour, and immediately to print the Lessons instead.
We have visited several Greeks, who reside in the country.
Some of them are men of religious feelings.

This is a beautiful island.
By means of irrigation they render it literally a watered garden.
The water is drawn night and day out of wells, by mules, horses or oxen,
which they change every three or four hours.
From the height to which it is raised it falls into reservoirs,
from there it comes down in a variety of fanciful forms, like cascades.
These are shaded by orange trees, lemon trees, grape vines,
etc.;--and under these they have delightful arbours,
amidst grounds on which a variety of excellent fruits, vegetables, etc.,
grow luxuriantly.
It is thought that Scio contains more than fifty thousand Greeks,
beside nearly the same number of Turks.
Twenty thousand of these are Roman Catholics.
Beautiful and refreshing as is the country, the town is dirty and disagreeable.
The place we lodge at is filthy.
Bugs abound, and musquitoes, fleas, etc., are so troublesome that we cannot rest at night.

We made the acquaintance of Petro Corpy.
He resides in Egypt, at Grand Cairo.
He is a tender-spirited man, acquainted with vital religion.
He tells us of several persons at Cairo and thereabouts, who are like-minded with him,
and who would appreciate such books as we had presented him with.
He has taken some in charge for the purpose; and as he is frequently with Ali Pasha,
we have given him some suitable ones which he will hand to him.
In various ways a little seed may be sown which may
produce a little fruit to the Lord`'s glory.
As the Pasha takes an interest in schools,
we send him also a manual of the system of schools on the plan of mutual instruction.

We went, this afternoon, four miles out of town on mules,
to visit some of the schools of Bambass.
Here we met with several of the chief Greeks of the island,
with one of whom we and some of the company took a late dinner.
The way opened for a religious opportunity with them.
The more we are with Bambass, the greater esteem we have for him.
He has at heart the best welfare of the people.

9th. Went out into the country to see Rodocanaki,
the primate of the five Ephori who govern the island this year.
He had kindly sent us mules for the purpose.
Both he and his family are religiously disposed.
He took us to see an Armenian who is banker to the Sultan.
He had heard of us and wished to see us.
We took the opportunity, while giving him some books of a religious character,
to request him to present to the Sultan some that we thought suitable
to draw his attention to the peaceable kingdom of Christ.
We were in the evening with the Greek Archbishop, Plato.
Here, as in Russia, we find spiritual-mindedness in the Greek upper clergy;
but their monks are generally, with some exceptions, in much ignorance.
Some of them are men who, to flee from the hand of justice,
have retired into monasteries;
but their putting on the monk`'s attire changes not their depraved hearts.

In the afternoon we went to the country seat of Peole Mavrocordati,
a very beautiful place; it was a treat to pass the night in a clean and cool lodging,
and to sleep on a bed, which we have very seldom done since we left Petersburg;
yet even here, as the man was arranging the bed-clothes, a scorpion, near the pillow,
bit him so severely that his hand swelled considerably up to the arm,
attended with much pain; dressed with some alkali it was, however,
nearly well by morning.
Scorpions are numerous in all these parts.
Professor Bambass joined us at this house;
we had a satisfactory religious meeting with them;
the purity and simplicity of the Christian religion,
as set forth in the Gospel by the Apostles, was unfolded to them,
and contrasted with the many ceremonies, Jewish and idolatrous practices,
that have been devised and introduced into the nominal
church by Christian professors under various names.
Bambass said, after the meeting concluded,
"`I fully unite with the testimony borne this evening among us;
I am in the monastic order; I was introduced into it when very young,
before my judgment was formed, or I was even of an age to form one.
Monks have done much harm to the church,
and they bear some of the strong marks the Apostles gave of the apostacy.`"
He highly approved of our views of Divine worship, and of the ministry.

Bishop Plato came here in the morning; we had a full opportunity with him and others;
as some of them do not understand French, the Archbishop acted as interpreter.
The particular subjects treated of were, redemption by our Lord Jesus Christ,
his saving baptism, Divine worship, the influences of the holy Spirit,
the cause of the great declension in the Church,
and the way whereby man can rise again from his fallen estate,
all of which he rendered with much precision,
as some competent judges told us afterwards.

13th. Petro Corpy has paid us another visit;
he appears anxious to obtain more information, and the knowledge of the saving Truth;
he also wished to know how he and his friends in
Egypt should conduct their meetings for Divine worship.
We directed him to a close attention to the guidance of the Divine Spirit,
for which we must wait, that we may be led into all Truth;
under its influence pure and acceptable worship is to be performed.
He is in a very tender state of mind;
he accompanied us in a visit to the prisons for criminals and debtors;
there is also a prison for females, entirely separated from that of the men;
they have women for their keepers.
The Vice-Governor, a humane man, a Turk, has these prisons under his care;
we had some serious conversation with him.

We are made very sad by the account we hear of the peculiar suffering which many families,
among the Greeks here and in other places,
are brought under by the machinations of some Popish priests and monks,
who came into these parts some time since from Rome as missionaries.
The greater part of the Greeks are of the Greek Church, but others are Roman Catholics;
many marriages have taken place between persons of these two denominations;
the missionaries now go about proclaiming excommunication and damnation upon
all those who have taken wives or husbands out of the pale of the church of Rome.
Many of these poor benighted people have been so frightened,
that they have actually been divorced;
some of them had lived very happily together twenty or forty years,
and have children and grandchildren; thus families are involved in serious difficulties.
Oh how dark! how mischievous is this anti-christian spirit!
I feel much sympathy for these poor sufferers.

Apprehending that the time of our departure from Scio is near,
we have hired a boat of about five tons, to take us to several other islands,
and from there to the Morea.
This evening we went out into the country to John Rodocanaki`'s, the primate,
to have one more religious meeting with the people in his neighbourhood.
Bambass was there.
The banker of the Sultan also, and several of the Ephori.
The minds of many were solemnized,
and appeared tender under the Lord`'s power manifested over us.
The banker was much affected.

By accounts received from Constantinople, it appears that the mortality,
caused by the plague, increased considerably after our departure from that city.
A very few days after we left Smyrna, great commotions took place there.
The Turkish populace rose en masse, and threatened a general massacre of the Christians.
French and English frigates being then in port,
the Consuls of these two nations sent word to the Turks,
that if they proceeded to take the life of a single Christian,
the frigates should immediately destroy the whole
of that part of the city which they inhabit.
The Turks were so intimidated, that they did not proceed to further extremities.
The cause of all this is thought to be the discovery of the bodies of six Turks,
beheaded by the Turkish authorities,
whom the people supposed to have been killed by some of the Christians.

--

[.offset]
Having completed their services in Scio, they crossed the Archipelago to Athens.--

[.embedded-content-document]
--

14th. As we were entering our boat this morning,
we met with some Greeks landing from Smyrna, who confirmed the above account.
One of them had a letter for me from my beloved wife, committed to his charge at Smyrna.
This letter has reached me in the very short space of ten weeks from America.
One of these men resides at Tiflis.
He confirms the account that they have there a translation of parts of Barclay`'s Apology,
and some other books, which he says will be much valued by many in that country.

We took our departure from Scio, accompanied by our Greek interpreter,
with peaceful minds, and grateful hearts,
for the Lord`'s help extended to us on this island,
where we leave many who have been much endeared to us,
in the love of the Gospel of Christ, our Redeemer.
'`We proceeded only ten miles on our way, for our boat is a dull sailor,
unless the wind is very fair.
Our two men and a boy who manage her, have not much energy.
We have now anchored for the night, at the south end of the island.
We went on shore to visit a monastery in ruins, on the top of a high hill,
and found in it a few individuals who live like hermits.
We had conversation with one who appears sincere in his religious profession.
He has withdrawn from the world, to spend his time in retirement.
In our walk, we came among their mastic plantations.
It is an excellent aromatic gum,
and is kept exclusively for the use of the seraglio of the Sultan,
unless clandestinely disposed of otherwise.
They chew it, mix it with bread or sweet-meats, and with their drink also.
There are twenty-one villages here, where it is cultivated.
It is not known to grow in any other part.

15th. Having passed last night in our boat, the starry heavens for our canopy,
we proceeded on our voyage, but had come fifteen miles only,
when our captain cast anchor again.
This is a very rocky coast.
We went on shore and found a beautiful grotto, where, sheltered from the sun,
we two sat down together in this solitary retreat, and held our little meeting.
The Lord contrited our spirits by his good presence; truly he draws near to the two only,
who are met in his name.
Though solitary,
we feel at seasons as if we were encircled by many
of our beloved friends in England and America,
and some of those precious ones whom we have visited in several places.
We unite with them in our spirits in proclaiming the love, mercy,
goodness and power of a gracious God and Redeemer.

17th. We were intending for Caristo;
but a strong contrary wind brought us to the island of Andros.
We visited their village,
and had a religious opportunity with the people and their priest.
We encouraged them to a pious and virtuous life,
and to give a religious and guarded education to their children, instructing them,
by their example, to live in the fear of God, and in obedience to his commandments.
We left with them several New Testaments in Greek.

19th. Came to Tinos this afternoon.
We had proceeded only a few hours towards that island, when we met a vessel,
the crew of which told us that last night they were chased by pirates,
in two large row-boats, full of men.
They had fired several times at them,
but their vessel sailing well had enabled them to escape.
This was unpleasant information; but as it was now noon, we hoped to escape them.
As we were going between the two islands, Andros and Tinos,
we discovered at a distance a row-boat, which we thought might be a fisherman,
and we kept on our course;
but the wind dying away we saw two other boats join it and come towards us.
Our captain soon knew them to be pirates of the worst kind, who destroy lives,
sink the vessel, and carry away only the plunder.
We were very near an inlet on Tinos, but there was no wind,
and the boat too clumsy to be acted upon by our oars.
Meanwhile the pirates had come very near us.
It did not appear that we could escape their merciless hands,
when He who commands the wind and the sea, and they obey him,
caused the wind to blow from the very direction, which took our boat,
fast as the flight of a bird,
right into the inlet of the island,--where the pirates dared not venture.
Had not the Lord thus in mercy interposed,
a few minutes more would probably have ended our mortal lives.
Surely we have cause to bless and to magnify his adorable name!
Our Greeks appeared to be sensible of the wonderful escape.

We visited the inhabitants in their little town; had some religious service among them,
and distributed some New Testaments and tracts.
We left them early this morning;
we were nearly out of sight when we saw a boat coming from the island towards us;
they were men who were absent from the town last night; on their return,
seeing the New Testaments and tracts,
they were desirous that we should give some to them also, which we did.
The wind was fresh and fair,
so that we swiftly passed the place where the piratical
boats had been lurking among the rocks;
but we saw nothing more of them.
We proceeded towards the island of Zea; but the wind rose to a heavy gale,
and towards evening the waves broke in upon us in a fearful manner;
our prospect was the more gloomy as the night was very dark,
and the coast of that island rocky.
Our Captain supposed he must be opposite the narrow entrance into the small harbour,
and he concluded to make the attempt to run in.
Through the goodness of Him whose ways are in the clouds and in the sea,
we were favoured to get in safely about midnight.
Refreshed with a little bread and cheese we had with us,
we passed the rest of the night in the boat.
In the morning we hired mules to ride up to the town,
which is situated at the top of the island.
Their towns or villages are generally on the highest ground;
it enables them to see from a distance the coming of an enemy.
The ascent to this town is very steep, up a narrow stony path,
six miles distant from the place where we landed.
We purchased some provisions, and through the assistance of the English Consul,
an Italian, and the schoolmaster, who both spoke French,
we had a religious opportunity with the inhabitants who collected on the occasion.
We had another satisfactory one with the children in the schoolhouse.
On our return we both had a narrow escape of our lives.
My mule made a false step among the rocks in a very steep place:
she fell upon her head with such force as to turn over, and come upon me,
thrown forward as I was to some distance down the hill;
my beloved companion seeing me thus fall, and the mule upon me,
made haste to dismount to come to my assistance;
but in his hurry his feet got entangled in the loops of a rope that served for stirrups,
and he also fell down under his mule; our Greek coming to our help,
neither of us received any material injury, though I was much bruised.

Leaving that island, we doubled Cape Colonna,
at the point of which stand many large columns, monuments of Grecian antiquity.
The evening of the 23rd the wind so increased that
our Captain sought for shelter in a bay;
we could not find any inhabitants, though we ascended a high hill to look out for them;
we passed the night again in the boat.
The scorpions on shore are so numerous, and a small red ant, whose bite is like fire,
so abundant, and the danger from robbers so great,
that we are told it is safer to be in our boat, at some distance from the land.

Athens, 24th of Eighth month.
Early this afternoon we landed on the Piraeus; we met with Pinkerton,
just as he was getting on board a vessel bound for Constantinople;
we had been several times with his wife at Petersburg.
We saw on the quay a large quantity of goat-skins filled with oil;
they have a curious appearance; the head of the animal is taken off,
the neck and the legs above the first joint remaining;
it is in this way that oil is shipped from various parts of Greece.
We procured asses to carry us to Athens; two wooden slabs,
on which we spread our overcoats, were our saddles;
loops at the end of a rope our stirrups; another rope served for a bridle:
thus we made our entrance into that ancient city.
It was a two hours`' ride; the road passes through ruins of old buildings,
which extend from the Piraeus to Mars`' Hill, and far beyond;
the ground to a great distance is covered with broken pieces of earthen vessels,
and the remains of large columns are prostrated here and there;
some are still standing round about or supporting their ancient temples.

25th. On our way to several persons, for whom we had letters,
we passed a number of ruins, among others, those of several temples;
our attention was particularly directed to those of Jupiter and Minerva;
though these buildings were erected above two thousand years ago,
parts of them are nearly entire,
many of the carvings appear as if they were but a few years old,
some of their ancient idols are still standing,
and the places where many more once stood still remain;
it gives one an idea to what extent idolatry prevailed in these parts,
where ignorance and darkness now reign extensively.
The generality of the Greeks here are in a debased state;
my spirits are greatly depressed, and my heart is sorrowful at what is now to be seen,
heard, and felt, and at the picture exhibited of ancient vice and darkness.
The only person we have as yet met with who manifests religious sensibility, is a Greek,
on his way back to Adrianople.

27th. A Capuchin friar has called several times at our lodgings to see us,
and we were told manifested great disappointment at not meeting with us;
he left a message pressingly requesting that we would call upon him;
a similar message was sent us also by Gropius, the Austrian Consul.
I was at first unwilling to go,
not expecting to meet in him anything calculated to minister comfort to my soul`'s distress;
but I felt it right, however reluctantly, to call upon him;
he resides at a place called the Lantern of Diogenes; on seeing him at a distance,
in the rough garb of the true Capuchin with a long beard,
I was the more prepossessed against him,
but I had hardly exchanged a word with him when my feelings were totally changed;
I saw in him the humble Christian, the spiritually minded man;
I felt I could salute him as the disciple of the Lord Jesus Christ; his name is Paul.
We had much freedom in religious and edifying conversation;
he is very industrious in distributing the Holy Scriptures among the people generally,
and he has given or sold many copies of the New Testament to the Turks,
who come privately to him to obtain it;
some of them have told him that they read it with great delight,
for they are convinced that the doctrine it contains has come from heaven.
He told us how greatly he was tried with the missionaries,
who have come from the Propaganda at Rome,
and are the evil instruments of destroying much domestic happiness among the Greeks,
who have intermarried with the Roman Catholics;
he said that he had strongly endeavoured to dissuade them from such conduct,
urging them to return home,
and that he had written to Rome to represent the mischief they are doing.
He spends much of his time in religious retirement,
for he knows that it is in the temple of the heart that the Lord is to be found,
worshipped and honoured;
that there is the altar on which acceptable sacrifice is to be brought to the Lord,
and there also is the light of Truth to be seen burning continually,--a light never
to go out,--not like those wax-lights that they have on their outward altars.
We encouraged him to keep this light that the Lord has lighted in his heart,
bright and burning,
to direct the attention of the people to it,--to be an instrument
to gather them to Christ and to his Spirit,
that they may know him as their Teacher and Almighty Redeemer.
He came to our lodgings in the evening to spend a couple of hours,
when we waited together on the Lord, and felt the refreshings from his Divine presence.
He told us that he had disposed of all his New Testaments,
and could not supply the present demand from persons
who appeared desirous to possess the inspired volume.
We placed several in his hands for this purpose;
also religious tracts in several languages, which he is delighted to have.

I heard of a converted Jew who was travelling in Arabia,
and had a number of New Testaments in that language, which he distributed on his journey;
he was also in the practice of frequently reading it to the people in the marketplaces.
On one of these occasions he was sent for by the Pasha,
who in a rough manner inquired of him, "`What is this that I hear of you?
it is said that you read in a book that declaims against Mahomet and our holy religion,
and which is calculated to cause the people to revolt against the Sultan, etc.`"
The Jew replied, "`You have been greatly misinformed;
for the book I read in has not the name of Mahomet in it;
it was even written before Mahomet was born; and,
so far is the doctrine it contains from exciting the people to revolt,
that if they were obedient to it,
the Grand Sultan could not have a more peaceful and upright people in all his dominions.
To convince yourself of it,
please to accept this one copy of it,`" on which he presented him with a New Testament,
in Arabic, very nicely bound.
The Pasha took it, examined it, and said,
"`It is a very pretty book.`"--Books in those parts are rare.
A few days after, the Jew had occasion to go to the palace of the Pasha;
when at the door,
he heard the Pasha reading in the Testament to many of his people who stood about him;
he was then reading some of the miracles recorded by the Evangelists,
and now and then made his own remarks to his attendants.
Observing the Jew at the door, he called out to him, "`Come in, come in;
I am reading out of your book to my people; Christ was indeed a great one;
I also observe that all his miracles were made publicly among the people,
whereas all those of Mahomet were in private.`"

We found a few serious persons among the Greeks, with whom,
as well as in the families of several of the Consuls, we had some religious service.

Meeting in the streets some black people who appeared to enjoy themselves,
and were dressed very clean, I asked them if they were slaves.
They said they had been such, but they were now free.
I queried how they had obtained their freedom.
They answered, that it was very common among the Turks,
when slaves have served them a sufficient number of years,
to compensate them for the price paid for them, and, if they have behaved well,
to give them their liberty.
Among these were several men and women under thirty years of age.
They appeared well-behaved persons.
What an example is here given to Christian professors, by Turks!
Such actions are very rare in our southern states.
I had an opportunity of seeing, at Smyrna, a considerable number of slaves,
lately come from the interior of Africa.
They were left at liberty to go about in the streets or in the market-place.
Some of them were even asking persons if they would not purchase them.
They are not treated as on the American shores, when landing from slave-ships,
or when marched from one state to another, chained together,
or shut up in jails at night.

--

Before leaving Athens,
Stephen Grellet was again brought into much thoughtfulness
on account of the time drawing near,
when his dear friend William Allen anticipated he might
be released from his present religious engagement,
and feel at liberty to return home.
He thus alludes to it in his last record at Athens:--

[.embedded-content-document]
--

My beloved companion has it under his serious consideration to leave me,
after we have visited some of the Ionian Isles, and to return to England.
I feel heavy at the prospect; especially as I have a weighty service before me;
particularly in Italy.
To your guidance, O Lord! and your Almighty protection, I submit myself.
You hast hitherto led about your servant,
and instructed and preserved him in the way that
you hast sent him;--in the continuance of your goodness,
mercy and saving strength, O! be pleased to increase my confidence!
You knowest how weak, and how poor I am,
and what proneness also there is in me to be of a doubtful spirit!

"`My mind is frequently brought,`" he continues, "`under deep feelings for Italy,--Rome, etc.
It is now upon me by night and by day.
The time appears to have nearly come for me to go there.
Heavy are my gospel bonds.`"

--
