== Chapter XXXVII.

Third Visit to Europe

Barletta--Naples

Stephen Grellet had now arrived at a peculiarly interesting,
if not a critical period of his mission.
In company with a beloved brother and fellow-labourer in the Gospel of Christ,
he had visited the Lutheran land of Gustavus Adolphus,--he
had traversed the regions of the Greek Church,
in the dominions of the Christian Alexander,--he had been in the Crescent City,
and had seen something of Mahometan rule;--he had mingled with
the discordant elements of the motley group of believers and unbelievers,
in some of the islands of the Archipelago, and in the Ionian sea,
and at Athens and Corinth.
He had left his beloved companion at Corfu, and now, a solitary pilgrim,--"`alone,
and yet not alone`"--he had set his face towards the land of Popes and Cardinals.
Himself, at one time, a child of Rome,--then an infidel,--now a Christian believer,
and a minister of Christ in the religious Society of Friends--a Protestant of Protestants,
he was about to enter the precincts of the city of Leo and of Hildebrand.
It required a very close and humble walk with God,--a very chaste adherence
to the cause of Christ,--a very prayerful attention to the leadings of
the Holy Spirit,--and a very firm reliance upon "`the word of the Truth
of the Gospel,`" based upon the inspired records of the Bible,
to come out unscathed from the ordeal that awaited him;--meekly bold,
he had to "`speak the truth in love,`" on all occasions and to
all,--without pusillanimously renouncing the simplicity and integrity
of his own character,--determined to know nothing save Jesus Christ,
and him crucified,--seeking nothing, pleading for nothing save the Truth,
as it is in Him.
The sequel will show how he sustained the trial,
and stood faithful to his God and Saviour.

On his lonely voyage he resumes his narrative:--

At sea, on the Adriatic.
The men on our small vessel are all Italians, among whom I am an entire stranger;
very solitary indeed, in every respect,
not knowing one inch of the way in which I am going,
save only that my conviction becomes stronger and stronger,
that bonds and afflictions await me.
Through his grace assisting me,--even me, the poorest of his servants,
and often one of the most fearful, the Lord enables me to offer up afresh my life,
or my liberty, persuaded that he is able to deliver me from all evil,
to his own praise and glory.
After going about twenty miles,
contrary winds obliged us to put into a small port in this island,
(Corfu.) Next morning I went on shore with the captain.
The chief officer at the quarantine ground speaks French;
by his assistance I had a short religious opportunity with some there.

About nine a.m. we proceeded on our voyage,
but on the following day high winds and a rough sea obliged us to seek again for a port.
We came to Brindisi on the Italian coast, where, by the aid of the mate of our cutter,
who is a Corsican and speaks French,
I was enabled to have some religious communication with the people.
The Commandant of the place came on board to see me.
He appears to be a serious man.
By means of the telegraph he had conveyed to General Church, twenty miles further,
information that I was there.
Church has the command of that part of the country called La Puglia,
anciently the granary of Rome.
I had known his mother and near relatives in England and Ireland, who were Friends.
Probably he also remembered me,
though he is now a very different character to what he was then.
He sent me by the telegraph a kind message.
The part of the Grecian coast that we have on our right exhibits great desolation.
The Turkish Pasha has acted with much cruelty towards the Greeks.
He has had many inhumanly put to death, burnt their habitations, plundered the people,
and now he obliges those that remain to flee where they can.
My soul is overwhelmed with distress for the poor surviving inhabitants.
I cannot obtain any information respecting the pious Bishop of Janina,
who translated Barclay`'s Apology into Greek.
It is much to be feared that he has lost his life with many others.

On his arrival at Barletta he had to perform quarantine,
before he was allowed to go to an inn, and mingle with the inhabitants.

Barletta, 25th of Tenth month, 1819.
The part of Italy that we have sailed by is beautiful, very fertile and populous.
The towns are numerous,
and many fine country seats are seen on the sea-shore between them.
The chief commerce is in wheat.

An English merchant who arrived here when I did,
is placed in the same apartments with me, in the lazaretto, though in a separate chamber.
It is by the kind attention of General Maitland, who wrote, it appears, on purpose,
that they have given me these separate rooms; a very great accommodation;
for in the other parts of the lazaretto they are much crowded,--men, women,
and children of various colours and nations;
many of them are poor Greeks who come to seek refuge in Italy.

26th. My dress has already attracted the curiosity of some of the inhabitants;
six of the principal men in the town have come to see me this afternoon;
they are allowed to do so, provided they neither touch me nor anything belonging to me;
or they would become subjected to the same quarantine that I have to perform.
Another great advantage that we have by being in separate apartments is,
that we are not liable to have our quarantine lengthened
like those who are in numbers together;
if one of them becomes sick, when their time is nearly expired,
they have all to wait till it is ascertained what kind of disease he has;
should it prove to be the plague, the quarantine of all begins again.
The persons who came to see me were very civil;
they inquired into some of our principles and practices.
Taylor, the Englishman who is with me, speaks Italian well, and interpreted for me.

1st of Eleventh month.
Ten persons came together to see me; two are Popish priests,
but they appear to have liberal minds;
I had a religious opportunity with that company directing
them not to the knowledge only of the Truth,
but to a consistent walking in that religion which is pure and undefiled.

7th. Almost every day some persons come to see me;
some are well disposed and religious inquirers,
but others have nothing but curiosity to bring them here;
I am thereby frequently brought under much exercise;
it was particularly so on account of several priests;
they appeared very destitute of religion,
and were inquisitive to know if I am not what they call here one of the Illuminati,
by which they mean such as are endeavouring to create a revolution in Italy.
Their spirits were a great burden to me.
This afternoon about thirty of the principal men of this town came in;
also seven priests with them;
some of them had been present at religious opportunities on preceding occasions;
now all sat together in silence, and I preached to them the Lord Jesus Christ,
the head of the Church, and only Saviour of men; none of the priests opposed.

I received a letter from General Church,
who apologizes for his not being able to come to see me; he expresses his friendship,
and sends me an order on all the military commanders between here and Naples,
to furnish me with bands of soldiers,
"`to protect me,`" as he says from the numerous highway robbers who daily attack travellers.
I have written to him, acknowledging his civility,
but reminding him that he must have forgotten the nature of the
peaceable principles in which he had his early education,
and that I placed my confidence in the saving power of Him in whose service I am,
who is the Captain of salvation to all those who trust in Him; but,
should He permit me to fall a prey to the hands of unrighteous men,
I submit to His sovereign will.
A large band of these robbers is headed by a woman;
it is said that she has about two hundred of them under her command;
the largest body lurks mostly near Marphonia, but they spread to a considerable distance,
to the terror of travellers, and of the inhabitants also,
whom they plunder when other supplies fail them.
It is in vain to have an escort of soldiers on the road,
for this only the more excites the cupidity of the robbers, who have their spies about,
and come in greater numbers, according to the strength of the escort.

8th. I was liberated from the lazaretto this morning; also Taylor,
my companion in confinement.
Before I left it,
I had a short religious interview with the Greeks who have fled for their lives;
I could not well have access to them before; I feel much for them;
many were sitting crosslegged on the floor, in a very dejected state;
some were serious and tender.
Soon after I came to the inn,
several of the most serious persons who visited me in the lazaretto, came to see me;
one priest among them;
he is much pleased with the "`Importance of Religion,`" in Italian, that I gave him.
I visited an institution for orphan girls; some of the managers,
who had visited me before, interpreted for me.
It is a comfort to see the young females in an asylum where pious
men and women appear to extend a tender care over them;
this is the more grateful, as the state of morals here, generally, is very low.

Among the persons who came to my inn this evening were some priests;
I had a more satisfactory meeting than on some previous occasions.
Afterwards some inquired into many of our religious principles,
how they might become members of our Society,
and how we could judge cf their fitness to become such.
I told them that, as the tree is known by its fruits,
so their lives and conversation would proclaim what they really are,
"`Not every one that says Lord, Lord, shall enter the kingdom of heaven,
but he that does the will of my Father,`" says Christ.

I had been so long detained in the lazaretto that I felt
pressed in my mind to proceed as early as I could for Naples;
Taylor intending also for that place, we concluded to hire a carriage for the purpose.
He is a serious young man, well acquainted with many of our friends at Manchester.
It is rather desirable to have a person with me who speaks Italian.
Our first day`'s journey was through a rich, flat, well cultivated country;
but the habitations are most wretched, resembling the Irish cabins,
except that the latter having no fire places,
the smoke escapes from the roof or the door.
We stopped for the night at a village, but kept in the carriage the whole of it.
The next day we ascended the Apennine mountains, and arrived late at a village.
We had set off three hours before daylight.
We had done so the preceding morning.
Here we heard much of the robbers.
Several persons had been plundered that day, both on the way we had come,
and also forward; but we saw nothing to disturb us.
On these mountains, where they cannot cultivate grain, they have the grape vine,
filberts, etc.; and in the most inaccessible places, chestnuts of the best kind.
The people appear generally to be very ignorant and superstitious;
their morals also stand very low, so that my mind is greatly oppressed;
neither the fine air nor the beauties of the landscape can cheer my spirits.

11th. We were favoured this day also not to meet with robbers.
Some of the people where we stopped to refresh our
horses seemed to marvel how we had escaped them,
but I knew to whom I am indebted;
the Lord is the Almighty protector of those who put their trust in him,
blessed forever and ever be his holy name!
When we drew towards Naples, in the evening, we passed near Vesuvius;
columns of smoke issued from it,
and we travelled a long distance over solid rocks of lava,
that had flowed down during former eruptions of this volcano.
We were stopped five times by Custom-house officers, to have our baggage examined,
so that it was late when we reached the Golden Eagle Inn at Naples.

Naples, 13th. Went to the police to present my passports.
They were much offended at my hat;
neither could they for some time understand the reasons I gave them for keeping it on.
Finally they asked what I should do if I met what
they call "`Saint Sacrament,`" in the street,
when carriages stop and every body uncovers himself,
whatever be the state of the weather; many even falling down on their knees.
I explained to them why I could not even then uncover my head,
as a mark of veneration or religious worship to this, or to any kind of imagery.
"`Then,`" said they, "`you must abide by the consequences.`"
I have in vain sought for piously disposed persons of whom I had heard.
I have however met with a young man, a partner in the house of Rogers and Brothers,
who is a serious person.
His name is Miles.
He kindly accompanied me as interpreter.
Calling on Routh and Valentine, I found a letter from my beloved friend, William Allen,
waiting my arrival.
His health was nearly restored to its former standard.
Sir William A. Court, British Ambassador here, receives me kindly.
This is very particularly the case with Henry Lushington, who with his wife,
appear to be persons of piety.

14th. Angelo Nobite came to see me this morning.
He greatly deplores the very low state of religion in this place; superstition, he says,
abounds, also vice and immorality: from what I see and hear, I can readily believe him.
Bibles are prohibited to be printed or imported.
Some weeks since four hundred Bibles were brought in.
They were seized, and the Bishop, numerously attended by his clergy,
had them burnt publicly in an open square.
The priests say,
that to allow the people to have the Scriptures in their
possession would endanger the safety of their church.
They also carefully try to prevent the introduction of religious books or tracts;
and yet, though my baggage was several times inspected, my books were hardly noticed.

15th. Had a refreshing religious opportunity at Henry Lushington`'s, with his family.
They have ten nice, well-behaved children.
// lint-disable invalid-characters
He accompanied me to Capo-de-monte, to see L'`Abbé Campbell, a liberal-minded man.
He has established a school for poor children,
where he introduces the system of mutual instruction.
I met at Henry Valentine`'s a pious young nobleman.
He deeply deplores the darkness and irreligion which, amidst so much superstition,
prevail over the land.
His name is Don L. Bonaprianola.
He has a knowledge of vital Christianity,
and is acquainted with the sensible influence of the Spirit of Truth.
Some religious tracts I have given him were gratefully received.
Everett, our American Consul, appears to understand the nature of my religious exercises,
and to feel for me.
He and Lushington accompanied me on a visit to the
"`Albergo de`' Poveri,`" which is a large establishment,
and contains two thousand four hundred and twenty-eight persons,
about nine hundred of whom are girls, and more than that number boys.
The principal director is an interesting and sensible man.
He had been educated for a monk,
but preferred a life devoted to benevolent pursuits to the idleness of the monastery.
He extends a watchful care over the moral instruction of the young people,
and appears divested of the narrow and superstitious views of the clergy.
He was very ready in making way for me to have some
religious communications in this establishment.
The children are taught several trades, such as spinning, weaving, tailoring, shoemaking,
printing, locksmith`'s work, turning, etc.
Some also are engaged in polishing coral, so that the place looks like a manufactory.

In the evening, accompanied by Bonaprianola, I visited the Prince Cardito.
Some other noblemen were present.
The Prince is a serious man.
He occupies the important station of Minister of public instruction in the kingdom.
He appears to feel the importance of the subject,
and wishes that such an education might be extended to the people at large,
as would tend to spread among them sound principles of morality and virtue.
He has very lately presented to the King a memorial on the subject.
The Prince made various inquiries on this important point.
The superstition,
into which the young people are introduced by the education which the priests give,
tends greatly to corrupt their morals;
indeed the greater part of the clergy are so corrupt themselves,
that thoughtful parents have great objection to have their daughters under their care.
Some of the company present have been to England, and are acquainted with several Friends.

17th. The Russian Ambassador here is Count Stackelberg,
a near relation of the valuable Baron of the same name, whom I met with in Petersburg;
he also is a conscientious man; like his relative,
he has set free the people on his estates in Livonia.
I made a satisfactory visit to his family.
A pious priest came to see me;
he laments the general ignorance of real religion that prevails among people and priests;
gross superstition is substituted; he said,
that very little liberality towards the relief of the indigent is to be met with;
but gifts for the liberation of souls out of purgatory abound.
This is a very favorite topic for priests and monks to preach upon; in Naples only,
he says, above forty thousand dollars are annually given by beggars in half cent pieces,
for that purpose; all this goes to the priests to say mass.
At nearly every door of their places of worship I see notifications posted,
that indulgences and pardons for sins will be obtained by entering the church,
performing certain ceremonies, or paying so much money.
Their funerals are in many instances very gaudy;
some have passed before the windows of my chamber,
that looked more like a masquerade than a funeral.
In some of these the corpse, richly dressed, was in a sitting posture,
on a kind of throne.

// lint-disable invalid-characters
18th. Accompanied by the Abbé Mastroti, I have visited a school for girls;
the mistress appears to have charge of that establishment from religious duty,
and endeavours to instil into the minds of the young people sound morality and virtue;
she appears to be a pious woman;
// lint-disable invalid-characters
the Abbé interpreted what I had to communicate to the girls.

19th. In the morning I received a visit from an aged man, once in high life,
but now much reduced in his circumstances;
a condition in which he has found a blessing wholly unknown before.
The fear of God and the love of Christ have taken possession of his heart,
and he now enjoys consolations to which he was totally a stranger,
in the days of worldly prosperity; he has very gratefully received some religious tracts.
My discouragements are often great; there are nevertheless some comforts here,
in meeting with a few souls to whom the Lord Jesus Christ is precious.
// lint-disable invalid-characters
This evening I met at Abbé Mastroti`'s, two young noblemen; one of them is a prince;
their minds were tendered under what I felt it in my heart to impart to them,
in the love of the dear Redeemer.

20th. By appointment of the Prime Minister, the Chevalier de Medici,
to whom I had sent the letter given me by General Maitland, I went to his hotel;
I found in the antechamber a great number of persons of all ranks,
waiting to have an audience with him; they surveyed me closely,
whispering to one another what kind of a being I might be, thus to appear with my hat on.
I was not left long among them;
for it appears that the Chevalier had given orders to his attendants
to admit me into his private cabinet as soon as I came;
he made me sit by him,
and proceeded to inquire into the nature of the engagements
I had had in the different nations where I had travelled;
then he was very particular in his inquiries into
various of our Christian principles and practices.
The reading of my certificates,
the short account I gave of the order maintained in our Society,
as exhibited in our discipline, the manner in which our meetings,
both for worship and discipline, are held, etc., etc., pleased him much.
I proposed to send him some of our books treating on these subjects, which, he said,
it would be agreeable to him to have.
He offered to give me orders for admittance to all their prisons,
or any other place I might wish to visit,
requesting only that I would impart to him what I might see,
to which he could possibly apply some remedy.
I made several attempts to withdraw, knowing that many persons were in waiting;
but he was not ready to let me go, till we had been above an hour together,
and then he accompanied me through the ante-chamber, where so many were waiting,
to the further door; they gazed at me, while they bowed very low to the Chevalier,
as we passed on.

// lint-disable invalid-characters
In the afternoon I was with the Abbé Mastroti again; several noblemen were present,
also the young prince whom I saw yesterday.
I felt for awhile much dejected; a heavy weight was upon my mind,
and I did not see how I could throw it off before such a company,
who appeared to be of the great and wise of this world;
but I thought that if I truly wished to be myself one of the wise in the Divine sight,
I must first become a fool, yea, be willing to be accounted so by others.
I proclaimed to them the day of the Lord, which shall burn as an oven, etc., etc.;
I entreated them to receive him in the way of his coming,
and be of those whose sins go before-hand to judgment,
and not of those whose sins follow after; not to trust in the doctrine of a purgatory,
but rather deeply to consider the description given by our
Lord Jesus Christ himself of what follows after death,
as set forth in the parable of Dives and Lazarus; the rich man,
not in purgatory--but in hell--lifted up his eyes and saw Lazarus in Abraham`'s bosom,
etc., etc.
The Lord`'s truth was exalted among them, and his power had the dominion.

In the evening I went to the Prince Cardito`'s. I feel deeply with him,
in his desire for the moral and virtuous education
of the youth among the mass of the people;
I placed in his hands a copy of the "`Scripture Lessons,`"
which dear Allen and I prepared in Russia.
I found with the Prince eight other noblemen,
who also manifested great interest in the subject;
they were inquisitive as to several branches of our Christian principles and testimonies;
this gave me an opportunity to set before them what the Church of Christ is;
the worship which his servants are to offer to Him who is the Head of his Church,
which is a pure church; this I contrasted with the church of Rome,
the worship of images introduced therein, the great impurity of so many of its members,
particularly of the priests and monks.
They acknowledged the correctness of these representations.
On returning to my lodgings I found a letter from the Chevalier de Medici,
enclosing orders for my admittance to the various prisons, etc.

21st. Accompanied by Bonaprianola,
I began the very painful work of visiting the receptacles of vice and crime.
I went today through the two prisons for women, a large one for men,
and a hospital for their sick.
This service took me from nine a.m. till four p.m. But my bodily
fatigue is small compared to the anguish of mind I have endured.
I do not remember that, in any day of my life,
I have been with so many fellow-beings so totally depraved and hardened.
Cages of very unclean birds, indeed, I have been in.
Many of the inmates of both sexes, and even children, have committed atrocious crimes.
I saw fifteen in one cell who are condemned to death.
Their crimes are of the deepest dye,
and they do not show the least sense of their situation.
My attempt to represent to them the awful doom that awaits them shortly,
unless by sincere repentance they seek for mercy and forgiveness
through Him who is the only Saviour of sinners,
appeared to have no more effect than the dropping of water on the flinty rock.
Some boys who are there, at the early age of eleven years,
have perpetrated several murders.
I endeavoured to turn the inmates of these prisons "`from darkness to light,
and from sin and Satan to God;`" but I do not know that a single individual,
out of several thousands I have been with this day,
has given the least sign of sorrow for his evil deeds.

22nd. Today I visited the foundling hospital, which in a very large establishment.
The mortality among the children admitted here is
not as great as in similar places in Russia.
About eighty nuns have the principal charge of it.
In one part there are about four hundred girls,
most of whom have attained the age of young women.
It is a kind of convent.
As I was going through a long corridor,
accompanied by several of the nuns and priests attached to this extensive institution,
we passed the door of their chapel, which was open.
I saw the girls, with several nuns, on their knees before a large Madonna,
or representation of the Virgin Mary, very richly and finely dressed.
Wax candles were burning before it.
They were singing to the image, but at the same time their faces were towards us,
laughing.
My soul was sorrowful on beholding them, and their superstition and idolatry.
The chief of the priests who were with me asked if I did not wish
to go into the church to see the girls at their devotions.
I told him I should like to do so if it were proper.
I felt a strong inclination to go in, but,
as from religious principle I do not uncover my head
in any place as if it was holy ground,
I was unwilling to give offence to anything by going in.
The nuns said, nobody here would be offended at it.
The priests also said, "`we have on our heads our cassocks;
your hat is to you no more than these are to us,
especially as it is from religious principle that you act.`"
Then I told them I would go in, on condition, that,
if I apprehended it was required of me by the Lord
to communicate anything to the young women thus assembled,
he, the chief priest, who spoke good French, would interpret for me.
He very readily agreed to do so.
We all went in.
Besides the girls, most of the nuns were in the church, about their great Madonna.
When they had concluded singing their hymn,
I told them how greatly my heart had been pained, as I passed by,
on seeing the lightness of their conduct while engaged
in what they call a devotional act:
that I could not however be surprised at it,
if they truly looked on that image before them as
what it really is,--nothing but a piece of wood,
carved by man`'s device, which can neither hear, nor see,
neither do good nor evil to any; our devotion, I said,
is to be to Him who sees the secret of our hearts, hears not our words only,
but knows our every thought; from Him we have everything to fear if we do not serve,
obey, and honour Him; and the richest blessings to hope for if we love, fear,
and serve Him: the worship acceptable to Him is to be performed in spirit and in truth,
from the very heart; this is the Temple in which He is to be found,
and in which He reveals himself.
Here, at noon-day, they have lighted tapers,
which cannot enable them to discover the sinfulness of the heart,
but the light of Christ, which enlightens every man that comes into the world,
and by which everything with which He has a controversy is made manifest,
shows us our sins, that we may look upon Him whom, by our sins, we have pierced:
He is the Saviour of all those that come to Him in faith and true repentance.
Then I proceeded to proclaim to them the Lord Jesus Christ as the only Saviour of sinners,
the only hope of salvation, the way, the truth, and the life,
without whom no man can come to God the Father;
all that pretend to enter by any other way than by him, the door,
are accounted as thieves and robbers.
The priest interpreted faithfully into Italian, of which I could judge.
The nuns and the other priests said several times, "`this is the truth,`" or "`it is so.`"
The countenances of the girls had much altered; they hung down their heads,
and tears flowed from some of their eyes.
Thus did my blessed Master enable his poor servant in a Popish church,
assisted by priests, to bear testimony to his blessed truth,
and against the superstitious worship that those
poor girls were offering to a carved piece of wood.
After we came out, some more of the nuns collected about us, and,
in answering some of their questions,
I further unfolded to them what acceptable worship to God consists in,
and also what is the only hope of salvation.
No man can save his brother, or give to God a ransom for his soul; that, therefore,
it is great presumption for any to attempt to take upon
themselves to pronounce absolution from sin on a sinner.
After opportunities of this sort I sometimes marvel
that they do not lay their hands upon me;
but here, on the contrary, they parted from me in tenderness,
and with expressions of their satisfaction with my visit.
Surely this is the Lord`'s doing; blessed and reverend is his name!

In the afternoon I went to the prisons of the Gallerians.
They are dismal places indeed.
The stone arches and the walls are black and sooty;
for they have sometimes a little fire in the prison, which is very damp,
and as there is no chimney, the walls that have not been swept for many years,
have a dismal appearance.
The water they drink is drawn from a well in the prison.
What they spill of it, and the raiu that comes in through the iron gratings,
causes the mud to be shoe-deep.
They are so crowded that when they lie down on the planes placed over their benches,
they completely cover the whole surface; and all cannot be accommodated.
Many are obliged to place their planes on the mud, under the others.
They are chained by the leg, two and two, so that their position is very uncomfortable.
Many of them have thus been confined several years.
Some young men, chained to older ones,
were brought to that prison when they were only twelve years of age!
In no country have I seen so many youthful criminals.
The only yard to which some of them may resort for a few moments,
is but twenty feet square.
I found some tenderness of spirit among a few of the prisoners.
There are about six thousand.
My feelings were overpowered.
The foulness of the air greatly affected me also.
But if, by my suffering, I can open a way for some relief to them,
it will administer consolation to my sorrow.
Some of these poor people seemed as if they could not believe their own ears,
when I imparted to them the encouragements which the Gospel holds out to penitent sinners;
that although their sins were as scarlet, or of a crimson dye, yet the Lord,
in his love and mercy, could make them as snow or wool.

I met at the Count Stackelberg`'s the Russian Minister,
and several Prussian and Russian noblemen; some of these I had been with in Russia;
the Lord made way once more to proclaim among them the unsearchable
riches of his love through Jesus Christ,
and to entreat them not to be hearers only of the glad tidings of the Gospel,
but so to believe as to obey.

Since I came to Naples, I am frequently much annoyed by friars,
who introduce themselves into my chamber, and are sturdy beggars;
they beg for masses to be said, and prayers to be made, as they say,
for souls in purgatory; they beg also for their own convents,
for tapers to burn before the images of their saints and of the virgin Mary,
to adorn their altars, etc.
They have their indulgences for sale, various relics, little images, etc.,
to all which they attribute great efficacy,
such as to preserve the wearers of them from the hands of robbers, from sickness,
from evil spirits, and many other things.
I find it difficult to get rid of them, and some,
finding they cannot obtain their purpose, become very passionate;
and yet a willingness has appeared in others to hear what I had
to say against their superstitious and idolatrous practices.

23rd. I was a third time with the Chevalier de Medici.
I had sent him a statement of some of my observations, particularly among the insane,
and in some of the prisons;
and I have now laid before him the situation of the Gallerians.
He took such an interest in what I stated in my former report,
and his feelings were so touched, that attention was immediately given to it;
some places have already been cleansed, ventilators are opened,
boys are removed from the other prisoners, their irons are changed for lighter ones,
etc., etc.
And now he appears disposed, with equal promptitude,
to have a complete change made in the prisons of the Gallerians,
and at once to have the boys removed elsewhere.
Should my deep sufferings in these visits have no other effect
than thus to mitigate the bodily tortures under which some of these,
my fellow-beings, have suffered for years, I am richly repaid;
may it not be for one of these ends that the Lord is opening
a door of access for me to plead with men in authority?
or that while the hearts of some of these are tendered,
under a sense of the Lord`'s mercies towards them,
they may become disposed to acts of mercy towards others?
I hope also that some of the poor prisoners will find consolation in the Lord Jesus,
whose mercies have been proclaimed to them.
Bonaprianola, Prince Cardito, and a number of others,
appear so to feel for that class of men as to be willing to visit the prisoners henceforth,
and to impart to them moral and religious instruction.
I particularly recommended to them the juvenile offenders.
I had a precious meeting with these benevolent persons,
together with a large company of those with whom I had been
previously in more select or public religious opportunities;
it was a solemn parting meeting.

I feel now as if I must hasten to Rome; various objects, tinder other circumstances,
might claim a few days of my time; Vesuvius displays a grand sight; in the day,
thick columns of smoke rise up to a considerable height; at night,
they are blazing pillars;
at a short distance from here are excavations made
into the streets of Herculaneum and Pompeii,
long buried under beds of lava, on which vineyards are now planted; but,
though as a man I should be greatly interested in visiting them,
they are not the objects for which my great and blessed
Master has sent me to these nations.
With singleness of heart I must prosecute the business to which he has called me.
My bonds for Rome also feel so heavy, that I could not have any pleasure in those things,
which, were I differently circumstanced, would interest me so much.
It has indeed been so with me for years past;
though in the course of my travels I am among, or pass near, objects of great curiosity,
and I have from early life taken great interest in such things,
yet the discipline under which the Lord has kept me,
and the weight of the religious service to which he has called me,
have been such that I have not felt at liberty to turn out of my way in travelling,
or to tarry longer in any place, merely to gratify myself.

This afternoon the Chevalier de Medici, in a kind and polite note, encloses me an order,
to enable me to pass through and out of the kingdom without
being subject to the detention of having my luggage examined;
he also sends me a letter for the Cardinal Consalvi at Rome,
who is his particular friend.
How great is the Lord`'s goodness in thus opening a door for me, his poor servant,
from place to place!
He it is who has the key!
If he opens, who can shut?
But when he shuts, none can open!
Medici, in his note,
states that measures are already taken to ameliorate the condition of the Gallerians,
agreeably to the representations that I made.

Stephen Grellet was now ready to depart.
Six years ago, it will be remembered, during his great conflict at Genoa,
he had received an intimation that "`to Naples and
Rome he should go,`" but "`the time was not yet.`"
Then "`the trumpet of retreat gave a clear and certain sound.`"
In the simplicity of faith he obeyed it, and found safety and peace.
Now to Naples he had been, and to Rome he was bent.
He followed no uncertain guide.
