== Chapter XL.

Third Visit to Europe

Munich--Augsburg--Stutgard

Stephen Grellet was again in Bavaria;
but many changes had taken place since his last visit.
The sacred rights of conscience had been little regarded;
religions liberty had been deplorably violated;
both King and people had quailed under Papal oppression; bigotry and persecution had,
in several instances, been but too successful in driving away the pastors,
and in scattering the flocks.
Dear as was the cause of Christ and his Church to him,
and earnestly as his heart yearned towards the humble
followers of the Lamb under every name,
his Christian sympathy and concern could not fail to be rekindled.
On his arrival at Munich, on the morning of the 7th of First month, 1820, he writes:--

It is six years since I was at this place before,
and I find that I must stand resigned to resume the heavy bonds that I had then upon me.

8th. I was this morning with the Baron Baader;
he informs me that through the influence of the Popish clergy,
much persecution has prevailed,
so that several of those pious Roman Catholic priests I was acquainted with,
have been scattered, and have gone to other nations; Boos^
footnote:[Martin Boos never actually left the Roman Catholic church.
He was one of those who thought that his usefulness would be lessened by such a step.
But being banished from his parish at Gallneukirchen, he retired to Dusseldorf,
and through the kindness of the King of Prussia,
afterwards obtained the appointment of Pastor of the parish of Sayn, near Coblentz,
on the Rhine, where he died in 1825.
He was a man of deep piety and great devotedness.
His labours to win souls to Christ were remarkably blessed,
to the conversion of thousands.
His own conversion was striking.
In the discharge of his office as a priest, he went, about 1789,
to visit a woman distinguished by her humility and piety, who was dangerously ill.
"`I do not doubt,`" said he, endeavouring to prepare her for death,
"`that you die calmly and happily.`"
"`And why?`"
said the woman.
"`Because,`" replied he, "`your life has been a continued chain of good actions.`"
The woman smiled, and said,
"`If I were to die relying for my salvation on the works which you mention,
I am certain that I should be condemned;
but that which makes me calm at this awful moment is,
that I rely on Jesus Christ My Saviour.`"
"`Those few words,`" says Boos, "`in the mouth of a dying woman,
who was looked upon as a saint, opened my eyes for the first time.
I understood the meaning of Christ for us; like Abraham, I saw His day.
From that time I announced to others that Saviour whom I had learned
to know and there were many who rejoiced with me.`"
Thus did this woman, whom he wished to prepare for death, prepare him for life eternal.
The impressions which he had received were never effaced,
He put in practice the lessons he had been taught,
and zealously preached the doctrines for which he had afterwards so severely to suffer.
"`His labours began to be blessed in an extraordinary manner.
He felt deeply his own insufficiency, and sought, in continual prayer to God,
and the assiduous perusal of the Holy Scriptures, the assistance which he needed.
He generally felt his own sinfulness and insufficiency most deeply,
when he was about to deliver a discourse intended to affect the consciences of others.
On these occasions he would often forget the sermon which he had studiously composed,
and committed to memory, and would acknowledge with tears to his hearers,
that he had nothing to say to them; but he would feel himself led on,
by the contemplation of their needs and his own insufficiency,
to urge upon them that which the Holy Spirit gave him at that moment for their edification.
Several discourses uttered thus from the abundance of his
heart were the instruments of a religious awakening,
which took place at that time at Gallneukirchen.`"
{footnote-paragraph-split}
After
a long life of much usefulness,
when he felt the end drawing near, he said to a friend,
that he was dying in that faith for which he bad suffered; and to another he wrote,
"`Even now I feel that none shall see the Lord without having washed his robes in the
blood of the Lamb.`"--See [.book-title]#"`Life and Persecutions of Martin Boos`"# edited by J. Gottner;
translated from the German.]
to the Rhine, Gossner to Flanders, and Lindel to Russia;
it is said that many thousand persons gathered together
at the time of the departure of the latter,
to take leave of him; he then preached his farewell sermon to the multitude;
the soldiers who had him in custody, to escort him out of the kingdom, were,
like the rest, broken into tears, and joined in the public lamentation,
that such a good man should be sent away from them.
Sailer, of Landshut, has refused to be made a Bishop;
many obstacles are placed in the way of his great usefulness,
in spreading light and religious knowledge among the people.
These persecutions have tended, however,
greatly to increase the number of serious inquirers;
many are eager to have a copy of the New Testament, printed by Gossner.
I have met here with Baron Von Ruosch and his pious wife, on a visit to their daughter;
they give me the cheering information that the Princess Oettingen, and her sister-in-law,
the Princess Jeanette, maintain their love to the dear Redeemer; with these and others,
many of whom I had known heretofore, I had a refreshing meeting in the evening;
the Lord`'s presence was with us.

9th. I have been with the Crown Prince;
I spoke freely with him respecting the persecution that
has driven so many pious persons out of the kingdom;
for, besides those who formerly stood among them as priests in the church of Rome,
and who, from conscientious principles, have abjured the errors they saw themselves in,
and have on that account been banished,
a considerable number of other persons have also left the kingdom;
many have gone to Russia, others to America.
The Prince deplores it,
and acknowledges freely that full liberty of conscience ought to be allowed;
that any attempt against it is an infringement of the prerogative of God;
he regrets much that Gossner has been sent away, and says he loved him;
and was a subscriber to his New Testament.
The Prince was very tender under what I had to impart to him; he loves the Truth;
but alas! the cross is in his way, and he lacks firmness in bearing it.
From the palace I went to Baron Ruosch`'s,
where a little company were collected in a meeting;
I had a solemn religious opportunity with them;
among those present was the Countess Lockner;
her father is Chamberlain to the Emperor of Austria;
she was much affected during the meeting.

10th. I visited their prisons, hospitals, etc.
They are in a better state than most I have visited of late.
The prisoners support themselves by their labour, and lay by something.
This is given them when they are discharged.
This evening I had a very interesting and precious meeting at the Baron Gumpenberg`'s.
The persecution excited here has caused many to grow in the root of religion.
They have advanced in spiritual-mindedness.
A solemn silence prevailed among us for a length of time.
As I found that the greatest part of the people understood French,
I did not make use of an interpreter.
Two, however, did not understand, and yet both were greatly contrited and shed many tears.
One of these resides at Ludwigsberg, ten miles from Stutgard.
When, six years since, I was at that place, he heard of me, and walked there to see me,
but I had just left the town.
Now, we have met here providentially.
He is a learner in the school of Christ,
from whom also he receives strength to walk in the Christian path.
I have been much comforted with him.
Here, also, I met with J. Graff,
who rendered me such essential service on my way to this city, six years ago;
he is a tender-spirited man.

I feel great oppression on my spirit on account of
the persecution excited by the Popish clergy,
to which the King has given countenance by banishing so many of his best subjects.
I cannot feel peaceful without endeavouring to plead with him on that account,
and to show him how such doings militate against him,
and how contrary they are to the law of righteousness and truth;
that religion which is pure and undefiled before God the Father
cannot induce any to persecute others on account of their religious
testimonies to the Truth as it is in Jesus Christ,
the Son of God and Saviour of men.

11th. I visited several pious and afflicted persons;
among these the widow and family of my former kind friend the Baron Pletten;
it was a tendering opportunity; the Lord is with her in her affliction;
he is also very near to Francis Heinbeck and wife, in their sore bereavement.
In the space of three years,
six of their near and valuable relatives have been removed by death.
His wife is in a very feeble state of health also; but the Lord blesses their affliction.
They moved in high life when I was here before; now,
they and their children walk in the lowly and narrow way that the Lord leads them in.
They have with them an orphan a young Countess, who is placed under their pious care.
The consolations of the Gospel were permitted to flow in that visit;
all appeared sensible of it.
This evening I had another meeting at the Baron Gumpenberg`'s.
It was larger than any of the preceding ones,
and more mixed, as to rank in life, poor and rich,
but very generally composed of such as love the Lord Jesus.
They have sensibly felt the teachings and influences of the Divine Spirit.
Some of them were from among the nobility; others servants, gardeners, and mechanics,
but all subjects of the same Lord and Lawgiver.
Gumpenberg interpreted for me.
Two of those present were formerly nuns,
but now they feel that the vows they have entered into with the Lord Jesus Christ,
the true Head of the Church, supersede those they had heretofore made before man.
This has been a solemn meeting;
by the one Spirit we were baptized together into the one body.

12th. The Countess Lockner wished to have a private
opportunity to unbosom the exercises of her mind.
Deep are her spiritual conflicts, for the Lord leads her to the strait gate,
and in the narrow way.
I feel very tenderly for her, but she is in good hands;--the Lord, who leads in the way,
is the Almighty Preserver and Comforter of the humble and faithful traveller.
This evening I met at the Baron Ruosch`'s about fifteen persons of high rank.
I had seen but few of them before.
It was a close searching season.
They were told that pretensions to religion without witnessing the substance of it,
could not profit anything,
neither could the performance of any ever so plausible ceremonies;
it is at the heart that the Lord looks.
"`It is not every one that says Lord, Lord, that shall enter the kingdom of heaven,
but he that does the will of my Father, etc.`"
It is not said, he that obeys the Pope, or priests, or the decrees of the Council, etc.
I pointed out to them where the Divine will is revealed as the Scriptures clearly state,
"`that which may be known of God, is manifest in man,
for God has showed it to him;`" and how in another place it is said,
"`the grace of God that brings salvation, has appeared to all men,
inching us that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly in this present world, etc.`"
I urged them to hearken to and obey the Divine Teacher, who speaks to the heart.

I was with Reigersberg, who is the Minister of Justice.
He appears disposed to make some alterations that
I suggested in their treatment of the prisoners,
calculated to promote a moral reform among them,
as well as to increase their present comforts.
He deplores the ascendency gained by the clergy,
and the persecution that has been the consequence of it.
He encourages me to lay this my concern before the King.

14th. I had several precious seasons in the families of the Lord`'s visited ones,
both of the rich and poor in this world;--truly God does not accept the persons of men,
but all they that fear him and work righteousness, poor or rich, are accepted with him.
Last evening I was at the Baron Leschenfield`'s, Minister of Finance.
Several persons of both sexes were collected on the occasion.
Among others, the Prince Oettingen Wallenstein, a serious youth.
The Lord gave us a good time together,
so that tenderness of spirit was evinced by several.

This afternoon the serious people in this place came
very generally to a meeting I had appointed for them.
The consolations of the Gospel through the Spirit were poured forth upon us;
the word of encouragement and instruction in the
way of righteousness flowed sweetly towards them;
there was great contrition of spirit over the meeting.
As I left it a messenger from the Minister of Finance came to request me to call upon him.
I thought he might have something particular to communicate to me;
but I was greatly surprised on entering his spacious apartment,
to find it filled with a large company.
Some of them I had met last evening, but many I had not seen before.
This was an opportunity given me, very unexpectedly, to proclaim the glorious Gospel.
We were soon brought into silence.
A weighty exercise came upon me.
I was indeed among one class of men only as respects their station in this world,
but not so as to their inward condition.
The greatest part of them were Roman Catholics.
The Lord enabled me to divide his word aright onto them,
and to exalt Christ our Lord as the Head Supreme of the Church, and the only Saviour.
Among those present were the young Prince Oettingen, and General Reiss.
It was late at night when I returned to my lodgings,
where I found a letter from the Crown Prince, stating that the King, his father,
wished to see me next morning.

15th. I went to the Palace.
I soon saw that my prayers had been heard; the heart of the king was opened towards me,
and was made soft.
I had proceeded but a little way in pleading the cause of his persecuted subjects,
on account of their conscientious scruples against
the principles and doctrines of the Church of Rome,
when the King said, he increasingly felt how delicate,
tender and important that subject was;
then he stated the many difficulties into which he had been brought by the court of Rome,
and what steps he had been induced to take contrary to his best judgment;
he was now endeavoring to act according to the dictates of his own conscience;
for he had no confidence, he said, in priests, or the conclave at Rome;
his subjects of every denomination were equally dear to him,
and had an equal right to his paternal protection.
I encouraged him to take the precepts of Christ for
his rule in the government of his kingdom,
and to seek for, and act himself under the influence of his Spirit.
I made particular allusion to perilous times in which he had lived,
and the deliverance granted him of the Lord.
I pressed earnestly upon him the necessity, now especially in his advanced life,
to spend his remaining days in the fear of God, and in acts of piety, virtue,
mercy and justice, desiring that he may himself obtain mercy and favour of God,
and have a well-grounded hope, that when he has to lay down his earthly crown,
he may be prepared to have it exchanged for one everlastingly glorious.
The King was tender.
He took me in his arms with affection,
and craved that the Lord may grant my heart`'s desire for him, and bless me,
wherever I go.

After this I was with the Crown Prince.
I encouraged him to adhere closely to Christ;
to follow the light by which things reprovable in the sight of God are made manifest,--for
the commission of which the Spirit of Truth condemns us.
I told him that it is by the Divine Spirit that power is given us to do,
or to cease from doing, what we cannot in our own will and strength.
I left him in a tender state of mind.
I then went a third time to the Minister of Finance,
and had a solemn parting opportunity with him and his family.
I hope that the King and his ministers, and the Crown Prince also,
are strengthened to resist being any longer made the tools of the Nuncio of the Pope,
their Bishops, etc., in the oppression of the pious people here.

This evening a large number met me once more at my lodgings.
Among them was again the young Prince Oettingen.
The Lord`'s power was sweetly felt to be over us.
It was a time when solemn resolutions were formed.
May they keep their covenants unbroken.
I have several messages from persons at court, who wish me to visit them;
but I believe my work here, for the present, has come to an end.
I commend them to God, and the word of his grace, which is very near them.
He can do the work for them.
All that the Lord`'s servants can do, is to direct men to Christ.
He alone is the Deliverer and Saviour.

Augsburg, 16th of First month, 1820.
This morning early, previous to my departure from Munich,
several serious persons came to see me, for the last time, perhaps,
and brought me a certificate signed very generally by the pious people I have visited,
in which they express their warm feelings of gratitude to the Lord
for the favour conferred upon them in his love and mercy,
together with their prayers that he may protect and
bless me during the residue of my days.

At about half way to this place I met, at the station where I changed post-horses,
with one of the pious persons who attended a meeting at Munich.
I had a satisfactory religious opportunity in his family;
he accompanied me to this place, and though it was six p.m., when we arrived,
he went immediately to his religious acquaintances,
and by seven o`'clock had about sixty of them collected together,
with whom I had a meeting.
The Lord made himself known among us by the breaking of bread;
it was a season when some present were more perfectly taught the way of the Lord.
It was in this neighbourhood that Lindel resided,
and where he has left a spiritually minded people; the Popish priest,
who now occupies his place,
uses every endeavour he can to destroy the good that
Lindel had been instrumental in promoting.

17th. I visited several persons here in their families,
some of whom I knew when I was in this city some years since;
they appear to have maintained their integrity; among these is Director Smith,
who in old age is bringing forth fruit unto eternal life;
he accompanied me to their prison;
a watchful care appears to be extended towards the inmates,
so as to promote their moral reform.
The Governor of the prison told me of an experiment he had tried on several prisoners.
Their ration of food, for certain offences, is only bread and water;
he made choice of two healthy, strong, young men;
to one he gave the bread and water separate,
so that he could eat the one and drink the other; to the other,
he gave the same portion of bread soaked in water; the consequence was that,
in a few weeks, the latter became very feeble and reduced in flesh,
while the other continued strong and healthy.
Then he changed their treatment,
and gave to the emaciated one his bread and water separate;
he soon recovered his flesh and strength, while the other,
now taking his bread soaked in water, was greatly reduced.
He continued the same experiment several times with the same result;
he tried it upon others, on whom it it had the same effect; it led him to the conclusion,
that poor people would find it to their advantage to convert their flour into bread,
instead of making it into porridge.
The Postmaster from Schaffhausen parted from me in great tenderness;
the Lord Jesus is precious to him.

From Bavaria he passed over into the dominions of the King of Wirtemberg.

Stutgard, 18th. I left Augsburg at six last evening, and travelling all night,
came here in twenty-four hours.
The cold was very severe; the high grounds were like a sheet of ice,
so that going up or down the steep hills, I met with many difficulties,
particularly near Ulm, when the horses and carriage, with the driver and myself,
were near being dashed down a deep precipice.
After descending the mountain, we found ourselves in another climate;
the snow had melted, and there was a great flood over the country,
and travelling was rendered difficult and dangerous;
but my good Master brought me safely here, blessed be his name!

19th. I called this forenoon on several of those pious persons
with whom I mingled in the fellowship of Christ six years since,
and whom I left gathered in good measure under the teachings of his Spirit.
I am encouraged in the hope that some of them have kept near the anointing,
and made advances in the Divine life under it;
I had now seasons of refreshment before the Lord in the families of Enslingman, Herring,
Flatt, the Countess Seckendorf, and others.
I have also been with the Prince Kodalesky, the Russian Ambassador here.
I had a letter for him from the Prince Alexander Galitzin;
the Baron Schaifhausen was with him;
he was tenderly affected under a short religious communication that I made to them.
The Prince was urgent that I should come again in the evening,
when the King expects to be with him, but I excused myself,
as I rather wish that my visit to the King should be private.
I felt much for him on the decease of his Queen, formerly Duchess of Oldenburg;
it occurred last winter, while dear Allen and I were at Petersburg; the Empress Dowager,
her mother, made me promise to see the King and his motherless children,
if I came to Stutgard.

This evening I attended a meeting for Divine worship that I had appointed in the morning;
the company was rather mixed; several Lutheran clergymen were present.
The Lord graciously blessed a little bread suitable
to the several conditions of the company.

20th. Accompanied by Herring, as my interpreter,
I visited three hospitals and the house of correction,
and had some religious opportunities in these places.
In the afternoon I had a meeting at Herring`'s,
and another in the evening at Enslingman`'s; they were both solemn ones.
Those present were, generally, piously minded persons,
and a number of preciously visited young people were among them.
My soul rejoices in the Lord, on beholding these tender lambs of his fold,
whom he has raised up by his power and in his love, since my last visit here.

21st. I was at several schools for both sexes; three of these,
for the children of the poor, were founded by the late much lamented Queen;
her watchful care over them extended very particularly to their religious,
as well as moral education; this is likewise the case in the asylum for orphans.
In all these places, as well as in the public schools, the Scriptures are read daily.
The King takes care that all the institutions, formed by the late Queen,
are kept in the same order in which they were during her life.
Several pious females of the court devote portions
of their time to daily visiting these places.
The dear young people give evidence that the labours
of love bestowed on them have not been fruitless;
many of them manifested religious sensibility under what,
in the love of the dear Redeemer, I felt it my duty to impart to them.
I also visited their prisons,
towards the inmates of which pious and benevolent persons extend Christian care,
as well as charity.
It was late in the evening when I finished these services.
On coming out of a prison, I was met by the Prince Kodalesky,
who had been in search of me at several places,
to let me know that the King wished to see me this evening;
being then not far from the palace, I went there immediately,
though I had not taken any refreshment since breakfast,
and I felt much spent by the close engagements of the day.
The King was alone, waiting for me; he knew that I was in Russia last winter,
and with his Queen`'s mother and her brother, the Emperor Alexander,
a few days after they received the mournful tidings of her decease;
he continues to feel deeply his great bereavement; he held me by the hands,
while large tears rolled down his cheeks.
The best proof, said he, that he could give, how much he honoured his late Queen,
and how dear she was to him, was to endeavour to imitate her in her piety and virtue,
and also to keep up all her establishments of benevolence,
on the same footing that she had placed them.
He also reverently spoke of the comfort the Lord extends to him, in the assurance that,
through His mercy his dear departed one has made
a blessed exchange in passing from time to eternity,
so that his great loss is her unspeakable gain.
His mind was open to receive what I had to impart
of the consolations of the Gospel of Christ,
and of the good hope that the Christian believer has,
when he shall have fulfilled the days of his earthly probation.
I endeavoured to encourage him so to live and act
as to honour the Lord during the residue of his life,
and to promote, by his example and precepts, the advancement of the kingdom of Christ,
which stands in righteousness, peace and joy in the Holy Spirit; that,
whatever other kings may do, he may resolve to seek peace and pursue it,
to be very tender of the consciences of all his subjects,
and to rule over them in the fear and love of God.
He was very tender, and fully acknowledged the truth of what I said to him.
Before I left him,
the King asked if I should not like to see his dear motherless children.
I told him that their grandmother, the Empress Dowager had requested me to do so.
Then he appointed the time of my coming again to the Palace, at seven tomorrow evening.

22nd. I visited an institute for girls, mostly of the nobility, called "`Catherine.`"
It was founded six months only before the death of the Queen.
It contains about two hundred and seventy pupils,
but they do not all board in the establishment.
Several pious females visit it daily.
They take care that it is kept up agreeably to the benevolent views of the Queen.
I met there two of them, the Countesses Seckendorf and Zepplin.
I had an interesting meeting.
Much religious sensibility was evinced by the dear girls.
I was then very agreeably in the company of several
persons who devote great part of their time,
and of their substance also, to acts of benevolence towards the poor and afflicted.
One of them was a preacher to me; her actions keep pace with her words.

In the evening I went to the Palace at the appointed hour.
I found the King again alone.
We conversed for about half an hour on religious subjects,
particularly on such as pertaiu to that salvation which is by the Lord Jesus Christ;
also on the religious and moral education of the youth in general.
The King concludes to send some young men and women to London,
to become qualified to introduce here schools on the plan of mutual instruction,
and to have the Scripture Lessons used in them, having them printed in German.
He again fully expressed his views respecting liberty of conscience,
and has lately acted accordingly.
A body of persons had separated on religious grounds, from the Lutheran Church,
and built a meetinghouse at Kornthal.
William Hoffman, a member of the Legislative body,
is one of the principal men in the separation.
The clergy in a body waited upon the King to request
him to dismiss William Hoffman from his public office,
thereby to manifest his disapprobation of his conduct.
He told them that he could not do any such thing,
that he should not interfere with any of his subjects on account of their religious,
or conscientious views.
I told the King that I had heard of those persons.
Some spoke much in their favour, others against them.
That I had it under consideration to go and see them the next day.
The King encouraged me to go, and to judge for myself.
He then asked me to accompany him upstairs to the nursery.
We passed through a long range of apartments all richly furnished.
I could not refrain from saying, "`how many unnecessary needs we make to ourselves.`"
We came at last to the children`'s apartments,--the
two little Princesses by his late Queen,
and her two sons by the Duke of Oldenburg.
Mary, the eldest of the Princesses, is only three years old, and yet speaks good English,
French and German.
Her sister is only eighteen months old.
The King, on presenting them to me, was bathed in tears.
On our return from the nursery,
he took me through the apartments that the Queen used to occupy.
I felt the love of the blessed Redeemer towards him,
and endeavoured to encourage him in a faithful adherence
to the dictates of the Divine Spirit,
and day by day to wait upon the Lord,
that he may receive renewed strength to perform the
vows that he had made in the days of his distress.
He would follow me to the outer door of the Palace, and, on parting,
desired to continue to have a place in my remembrance and prayers,
and that if at any time he could serve me, I would let him know.
This is a time of gracious visitation to his soul.
May the Lord prosper his work with him!

I am greatly bowed down before the Lord while contemplating his power, love, and mercy.
I behold the efficacy of it in poorhouses and in palaces,
among all classes of men of every nation or religious denomination.
The works of the Lord in every part of his dominion
proclaim his gracious and powerful name.

23rd. First-day.
Accompanied by Herring, Enslingman, and a few others, we left Stutgard,
early in the morning, for Kornthal,
where notice had been sent of my wish to have a meeting
with the Dissenters that reside thereabouts.
They have built a good meetinghouse;
it may comfortably accommodate one thousand two hundred persons;
but so many came from the villages round that the house, being very crowded,
contained many more.
I found there a tender people;
they have become dissatisfied with formal religion and outward observances;
their souls long for eternal substance, and no longer for shadows only;
we were gathered together into solemn silence before the Lord;
truly precious was the cheering hope that the desire of the hearts of
this large company was unto the Lord as their only hope and Saviour.
I invited them to come to him with full purpose of heart,
to receive him as their bishop and shepherd;
I unfolded to them the nature and effects of Christ`'s baptism,
whereby also the qualification is received to participate in his supper.
The baptizing power of the Lord was felt to be over us;
the Bread of Life and the cup of his salvation were very graciously offered to us,
and the language was revived, "`Eat, O friends, drink-, yea drink abundantly,
O beloved.`"

I had a satisfactory opportunity with William Hoffman,
who is made a valuable instrument of good to that people.
We returned to Stutgard in time to attend a meeting appointed there for that evening.
It was attended by the people at large;
many of the nobility and several clergymen were present.
The Lord enabled his very poor servant--for truly so I felt myself to
be amidst that large company--to minister to their various conditions.

24th. This morning I met with a few of those here
who appear to have made the greatest progress,
through the obedience of faith, in the blessed Truth;
we had a contriting season together.
I encouraged them regularly to meet to wait upon the Lord, so as to renew their strength,
to walk in the way of his counsel, and to worship him in spirit and in truth.
Our parting from one another was under much solemnity and Christian affection.
They are among those whom I can recognize as a portion of that flock of the Lord
Jesus who know his voice;--may they also follow him wherever he leads.
