== Chapter XLI.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* Switzerland

It was a matter of great interest to Stephen Grellet to
re-visit the scenes of his past labours in the Swiss Cantons.
On the 26th of First month, 1820, he reached St. Gallen, and writes:

[.embedded-content-document]
--

I left Stutgard in the evening of the 24th, travelled two nights and one day,
and arrived here this morning, so little fatigued that, without taking any rest,
I proceeded at once with the service of love to which my dear Master calls me,
in the prosecution of which my soul is often refreshed in his presence.
Many of those whom I met with in a preceding visit
are now gathered into the heavenly sheepfold;
through the tender mercies of God,
others have entered their ranks in the church militant;
from children they are now become strong men and women--burden-bearers in the church.
There is also a precious little company still living of those to
whom I had been heretofore united in Christian fellowship;
they appear to have kept their integrity in the Truth.
I visited their Orphan Asylum,
where again I have had a contriting religious season
with the dear children and their pious caretakers.
In the evening I had a public meeting,
which was particularly attended by the pious part of the inhabitants.
The Lord caused the stream of Gospel love to flow towards them,
and the consolations of the Spirit to distil upon them.
Tribulations have been indeed abundant with many since we saw one another,
but the consolations that are by Christ have abounded much more.
Truly some of these dear people can testify that
their afflictions have been largely blessed.

I left St. Gallen before daylight the next morning,
and in the afternoon arrived at Winterthur.
I visited several serious families, and had some religious service with them.
One is that of the President of the place.
I hear of some pious people among the mountains,
but the depth of the snow would not allow me to attempt to visit them;
and my dear Lord does not require this service of me.
I am comforted in the belief that he has many precious plants
that I may never hear of whom he cares for himself,
and whom he waters from his holy presence.

Zurich, 28th. I set off again before daylight this morning, and arrived early;
I find letters conveying painful intelligence.
O what a favour to have in the Lord a sure refuge;
I endeavour to keep my mind fixed upon him.
After pouring forth tears before God, I washed and anointed,
then called upon some of the pious persons I am acquainted with.
The dear aged Antistes Hesse is green in the Divine life,
bearing fruits to the Lord`'s glory.
Pastor Gessner, and his valuable family, retain their love to the dear Redeemer.
I had in the evening a precious religious opportunity
at his house when several other friends joined us.

29th. The Lord was very good to me last night,
enabling me to commit all my sorrows unto him; he can sanctify them.
I feel also refreshed in my outward man,
this being the first whole night that I have passed in bed since I left Stutgard.
Accompanied by Solomon Pestalozzi, the banker,
my kind attendant and interpreter six years ago,
I visited their prisons and house of correction, and had a meeting with the inmates,
collected together for the purpose;
it was attended with greater seriousness and religious
sensibility than is generally found in such places;
many of the prisoners were much contrited.

30th. I was in several families with whom I had religious opportunities.
I had also two meetings; one at the venerable, aged Antistes Hesse`'s,
at the close of which he bore testimony to the efficacy
of that grace and truth that come by Jesus Christ,
asserting also his full belief in the sensible influences of the Divine Spirit.
"`It is a quickening Spirit,`" said he, "`without it, man cannot live the life of Christ,
nay, he is none of his.`"
The other meeting this evening was at pastor Gessner`'s,
where the several branches of his family, and of the Lavater`'s were also present.
A solemn silence prevailed over us all, in which the Lord himself, through his `'spirit,
ministered to us.
We partook together of the one bread, and drank out of the one cup,
witnessing the truth that there is but one Lord, one faith, and one baptism.
Our souls were refreshed and comforted together.

Berne.
Second month, 1st. I left Zurich yesterday, early.
By travelling both day and night, I arrived here this morning,
and met again my former kind attendant and interpreter, L`' Orsa,
who has accompanied me to several families, where I had some religious service.
He kindly prepared the way for me to have three meetings today.
One was entirely composed of females,
the greater part of whom I had been with six years ago.
Another was among the pious of the inhabitants, and the last, at eight in the evening,
was composed of the people generally.
The Lord owned us by his Divine presence on these several occasions.
Blessed and adored be his holy name!

2nd. Long before daylight I left Berne for Yverdun, where I arrived early this evening;
when I visited, near my inn, a pious widow and her family, Johanna Conscentius.
She is from Memel in Prussia, and is here on account of the education of her son.
She has two daughters with her, who appear to know and to love the Truth.
Some other persons came in, and under what the Lord gave me to communicate,
some were tenderly affected.

3rd. I visited Pestalozzi`'s school this morning,
and had a full opportunity with him and several of his teachers,
but not to much satisfaction.
Some of them do not appear to be believers in the fundamental
doctrine of salvation by our Lord Jesus Christ.
I told Pestalozzi that it was impossible for these men to instruct others,
in what they do not believe in themselves.
I felt much distress on their account,
and pitied greatly the young people under their tuition,
though that school has great celebrity.
I left dear aged Pestalozzi in a tender state of mind,
and I believe that it would be a great relief to him, could he have pious teachers.
I must make an exception respecting the school he has for poor children.
Good is done there.

I left for Lausanne at noon, at which place I arrived in the evening;
when my old friend Polier accompanied me to Langallerie`'s.
I felt very low both in body and mind,
but many pious persons that I visited years since, hearing that I was there,
hastened to come in.
They continue to be acquainted with, and in the practice of, silent retirement,
into which we soon gathered.
I was favoured to draw some consolations out of the well of life,
and enabled to minister to others out of it.

4th. I had but a poor night.
A great weight of exercise was upon me.
Prayer is a blessed refuge in time of trouble.
The Lord was pleased to hear the voice of my supplication.
The day has been spent under very close engagements in visiting the families of many here.
Some of them, poor in this world, are rich in faith.
They know the quickening influences of the Divine Spirit.
Some of these seasons were very remarkable and interesting;
attended also with great brokenness of heart.
At two places there were twenty or more together.
Solemn silence was over us.
The Lord himself ministered to us.
While I was at Langallerie`'s, upwards of twenty persons came in to see me,
mostly one by one.
Some came from a distance, having by some means heard that I was there.
One came from Vevay.
They came evidently under religious concern, their chief language of inquiry being,
"`what shall I do to be saved?`"
The Lord was pleased to give me a word for each of them, according to their various needs.
I then saw that the deep travail of my soul during the night preceding
had been a useful preparation for the work of the day.
Well known unto the Lord is the end of all his dispensations to us.
It was late before I retired to rest,
with my spirit very reverently prostrated before Him, for his Divine help and strength.

Geneva, 5th. I was on the road some hours before daylight this morning.
On arriving here I was greatly comforted by meeting with my beloved friend,
William Allen; he could not obtain a passage from Malta for France,
which induced him to come by land from Italy on his way to Paris and London;
he has recovered his health very nicely.
It is cause of much gratitude that we thus meet again;
for a while it appeared very doubtful that his valuable life would be continued,
he was brought so very low.
Now we are permitted to enjoy very sweetly the preciousness
of fellowship in our Lord and Redeemer Jesus Christ;
we had a refreshing and consoling time together, in prostration of soul before him.

6th. We visited together several pious persons.
In the evening we went to pastor Dumoulinier`'s, where we had appointed a meeting.
We have felt very tenderly for him, and pastor Demalleyer.
They have to endure much from several of the clergy in this place.
OI what a cloud of darkness has come over many of these
since I was here! and with it a persecuting spirit.
We had a satisfactory meeting with the company convened at Dumoulinier`'s.
It was precious to feel that each one was engaged to endeavour
to draw for himself out of the well of the Lord`'s consolations.
A spring of living ministry did also flow towards them.
I translated into French what my beloved friend William
Allen felt it his religious duty to communicate.

7th. We met with a very interesting little company at the widow Pillart`'s;
we seemed to be all brought into the oneness of the Spirit in the Lord Jesus.
There are several gathered religious bodies or churches
that acknowledge Christ for their Head;
great difference however exists among them;
but in all some are to be found who are in the unity
of the Spirit in the oneness of the faith,
baptised with the same baptism,
and partaking together at the same table of the same bread,
ministered to them by their one Lord and blessed Redeemer.
My soul often blesses him in that he has given me to mingle with many of this description,
and to feel with them the quickenings of his Divine Life;
I have found some in every nation and among various denominations.

10th. During these past days we visited their prisons and schools;
also several pious and afflicted ones in their families;
we had several religious meetings;
one particularly well attended was held at pastor Demalleyer`'s.^
footnote:[Among the many seals to his ministry which Stephen Grellet left behind,
it may be interesting to preserve the following:In the autumn of 1853,
Eli and Sybil Jones, accompanied by Mary J. Lecky and Christine R. Alsop,
visited the widow and daughter of pastor Demalleyer, then staying at Clarens, near Vevay,
in Switzerland.
They were both present at the meeting so briefly noticed above,
and gave them this account in connection with it.
{footnote-paragraph-split}
A considerable
number of serious persons had met at pastor Demalleyer`'s. After some instructive conversation,
a time of silence ensued.
The whole company seemed impressed with the solemnity of it.
It was some time before anything was said.
Stephen Grellet then addressed the company in a very edifying manner.
While he was speaking, a gentleman, who was but slightly known to the family,
and had never before attended the little meetings occasionally held at their house,
entered the room and took his seat by the door, without interrupting the stillness; and,
it was thought, unobserved by the speaker.
For a while there was no change in the tenor of his discourse,
but towards the conclusion he was led to address himself, with increased solemnity,
to an individual whom he described as being in the greatest danger of committing suicide.
After a solemn warning against the fearful sin and its awful consequences,
the forgiving mercy of God,
the bountiful provisions and the entreaties and promises of the Gospel of Christ,
and the all-sufficiency of the help of the Holy Spirit,
even for the most destitute and sinful,
were dwelt upon in such a manner that all present were deeply affected,
wondering at the same time, why they should be thus addressed.
But, from that time, it was remarked that the gentleman,
who had unexpectedly come into the room while Stephen Grellet was speaking,
became more serious,
and frequently attended the evening services which continued to be held
by the little company of pious persons with whom he had mingled.
It was not, however, till many years after,
that the gentleman in question informed pastor Demalleyer,
that on the evening of the meeting, he had left his own house,
under the pressure of great trials,
with the full determination to throw himself into the lake.
On his way to it, an involuntary impulse caused him to take a less direct course,
which brought him to the house of the pastor.
He entered it, he scarcely knew why, and, through the Divine blessing,
it proved the means of his deliverance.]

My soul greatly mourns over many dark spirits here; Antichrist seems to triumph.
The majority of the clergy, the Doctors of Divinity, so called, have prevailed;
they have decided that the doctrine of the Divinity of our Lord Jesus,
and salvation through faith in his name, shall no longer be preached among them;
only their Socinian tenets are to be promulgated.
There are those, however, who cannot be restricted by such a law;
they feel it to be their religious duty to preach
the Lord Jesus,--delivered for our sins,
risen again for our justification,--and to resign themselves to the Lord,
whatever be the consequence.
We felt very tenderly for them, and we believed that we had a service in this place,
by endeavouring to encourage them to faithfulness in keeping
the faith that was once delivered to the saints.^
footnote:[The Truth as it is in Jesus is indestructible;
and it is well known that brighter days have since dawned upon Geneva,
and many other parts of the continent of Europe.
At the very time that Stephen Grellet was penning the above remarks in the city of Calvin,
many pious young men, both in Switzerland and in Germany, were undergoing,
often unknown to each other, a fearful conflict, in throwing off the fetters of unbelief,
and seeking to attain to "`the joy of faith, and the peace of believing.`"
Not a few of these are now preaching the faith which once they sought to destroy.
// lint-disable invalid-characters
Of this number is J. H. Merle D`'Aubigné,
the well-known historian of the Reformation.
{footnote-paragraph-split}
He
studied at the academy of Geneva,
and,
after having remained in the cheerless principles of Unitarianism
till near the conclusion of his course there,
a prayerful study of the Holy Scriptures was made the means,
under the Spirit`'s influence, of bringing him to believe in the Divinity of the Saviour.
Convinced of sin, the power of which he had felt in his own heart,
and obtaining the blessing of forgiveness through faith in the atonement,
he had experienced the joys of the new birth; but,
though "`willing to take up the cross of Christ, he was yet weak,
and preferred regarding it as wisdom rather than foolishness.`"
It was at this time (1817) that he first visited Germany
with the design of studying theology for a longer period,
before entering upon the active duties of the ministry of the Gospel.
{footnote-paragraph-split}
"`Every
theological journal I read,`" he says,
"`every book I looked into, almost every one, both ministers and laymen, whom I met,
were affected with Rationalism,
so that the poison of infidelity was presented to me on all sides.
{footnote-paragraph-split}
"`I
then entered upon a fearful spiritual struggle,
defending with my whole strength my still feeble faith,
yet sometimes falling under the blows of the enemy.
I was inwardly consumed.
There was not a moment in which I was not ready to
lay down my life for the faith I professed;
and never did I ascend the pulpit without being able to proclaim, with fulness of faith,
salvation by Jesus.
But scarcely had I left it when the enemy assailed me anew,
and inspired my mind with agonizing doubts.
I passed whole nights without sleep, crying to God from the bottom of my heart,
or endeavouring by arguments and syllogisms without end,
to repel the attacks of the adversary.
Such were my combats during those weary watchings,
that I almost wonder how I did not sink under them.
{footnote-paragraph-split}
"`It
happened at this time (1819) that a friend of mine,
F+++.+++ Monod, settled in Paris, was on the point of visiting Copenhagen,
where his mother`'s family resided.
Another friend of ours, Charles Rieu, was the pastor of Fredericia in Jutland.
We were all three Genevese; we had studied together at Geneva,
and had come at the same time to the knowledge of the Truth,
although Rieu had outstripped us in all respects,
especially in the simplicity of his faith and devotedness to the Lord.
We agreed to travel together to Copenhagen, and to meet at Kiel, the capital of Holstein.
Kiel is a German university, and at that time was the residence of Kleuker,
one of the oldest champions of German divinity,
who had been for forty years defending Christian
revelation against the attacks of infidel theologians,
in apologetic works of some celebrity.
There were many passages of Scripture which stopped me, and I proposed visiting Kleuker,
and asking him to explain them,
hoping by this visit to be delivered from my agonizing doubts.
{footnote-paragraph-split}
"`Accordingly
I waited on Kleuker,
and requested that learned and experienced Christian to elucidate, for my satisfaction,
many passages from which some of his countrymen in their writings,
had drawn proofs against the inspiration of Scripture and the divine origin of Christianity.
The old Doctor would not enter into any detailed solution of these difficulties.
'`Were I to succeed in ridding you of them,`' he said to me, '`others would soon arise.
There is a shorter, deeper, more complete way of annihilating them.
Let Christ be really to you the Son of God, the Saviour, the Author of Eternal Life.
Only be firmly settled in his grace,
and then these difficulties of detail will never stop you;
the light which proceeds from Christ will disperse all your darkness.`'
{footnote-paragraph-split}
"`The
old divine had shown me the way;
I saw it was the right one; but to follow it was a hard task.
God, who had already revealed to me the glory of his well-beloved Son,
did not forsake me;
but he used other agency to bring me to the mark which had been pointed out.
{footnote-paragraph-split}
"`As
steamboats were not at that time very regular,
we had to wait some days for the one in which my
friends and I intended to proceed to Copenhagen.
We were staying at an hotel,
and used to spend part of our time in reading the Scriptures together.
Rieu was an ear of corn which the Lord had early brought to full maturity,
and which was soon after carried to the everlasting garner.
Two years after I wept over his grave, amidst his desolate flock.
We all three communicated to each other our thoughts,
but it was Rieu who most abundantly brought out the hidden riches of the Book of God.
We were studying the Epistle to the Ephesians,
and had got to the end of the third chapter, when we read the two last verses,
'`Now unto him who is able to do exceeding abundantly above all that we ask or think,
according to the power that works in us, unto him be glory,`' etc.
This expression fell upon my soul as a mighty revelation from God.
'`He can do by His power,`' I said to myself, '`above all that we ask,
above all even that we think, nay exceeding abundantly above all.`"
A full trust in Christ for the work to be done within my poor heart now filled my soul.
We all three knelt down,
and although I had never fully confided to my friends my inward
struggles (for I dared not make them known to any but God alone),
the prayer of Rieu, filled with admirable faith,
was such as he would have uttered had he known all my needs.
When I arose in that inn room at Kiel,
I felt as if my '`wings were renewed as the wings of eagles.`' From that time
forward I comprehended that my own syllogisms and efforts were of no avail,
that Christ was able to do all by his '`power that works in us;`' and
the habitual attitude of my soul was to lie at the foot of the cross,
crying to Him, '`Here am I, bound hand and foot, unable to move,
unable to do the least thing to get away from the enemy who oppresses me.
Do all yourself.
I know that you will do it,
you will even do exceeding abundantly above all that I ask.`' I was not disappointed.
All my doubts were soon dispelled,
and not only was I delivered from that inward anguish
which in the end would have destroyed me,
had not God been faithful,
but the Lord '`extended unto me peace like a river.`' Then I could
comprehend with all saints what is the breadth and length,
and depth, and height;
and know the love of Christ which passes knowledge.`' Then was I able to say,
'`Return unto your rest, O my soul;
for the Lord has dealt bountifully with you.`'
{footnote-paragraph-split}
"`If
I relate these things,
it is not as my own history--not the history of myself
alone--but of many pious young men,
who in Germany, and even elsewhere,
have been assailed by the raging waves of Rationalism.
Many, alas! have made shipwreck of their faith,
and some have even violently put an end to their lives.
On this account I shall always remember the words of Scripture,
'`You host set my feet in a large room.`' '`He that glories,
// lint-disable invalid-characters
let him glory in the Lord.`"--See D`'Aubigné`'s [.book-title]#Germany, England, and Scotland#.
New York edition, 1848.]

--

Now apprehending that the time had arrived for dear Allen and I
to be once more separated for a short season,--he to return to
London,--I to proceed in my Master`'s service in France,
we have taken a solemn farewell of one another, cheered, however,
by the prospect that our separation will not be long.
