== Chapter XLII.

[.chapter-subtitle--blurb]
Third Visit to Europe

[.chapter-synopsis]
* South of France
* Return to England

Having completed his religious engagements in Switzerland,
Stephen Grellet felt once more drawn towards the little
company who profess with Friends in the South of France.
He left Geneva early in the morning of the eleventh of Second month, 1820,
and on the fourteenth he writes at Nismes:--

[.embedded-content-document]
--

I travelled to this place night and day, without stopping much on the road,
except a short time at Chambery and Grenoble.
My soul was deeply grieved at what I heard, saw, and felt during the journey.
This is the time of their Carnival, and the ludicrous and even obscene exhibitions,
in the streets and on the highways, are truly disgusting.
In these their profane doings,
they are surrounded by a multitude of wooden and stone crosses,
and various representations of their saints, etc.,
before whom they bow and cross themselves.
Many have of late been erected in commemoration of the success of their missionaries,
actuated by spirits similar to those that have done so much mischief in Greece.
I am told that some of these missionaries lately preached at Marseilles,
stating among other things, that "`the Protestants are a plague,
and that the country can never prosper while they are allowed to remain.`"
I have been with several Roman Catholics,
who have spoken with disgust of all these doings; they said, "`they preach fanaticism,
not Christianity.`"

The Lord may overrule all this for good,
and render it a means to bring many from Popish darkness and superstition,
to the light of the glorious Gospel of Christ.
On coming to Grenoble, amidst the sight of so much levity and superstition,
I was further grieved at beholding the multitude,
returning from seeing the execution of a woman of seventy years of age,
appearing as if they had been to a party of pleasure.
I called on several of the pious persons that I know in this city,
and had some satisfactory conversations,
mingling with them in their sorrows and sufferings;
for they are threatened by the Papists with renewed persecution,
which many of the priests are fomenting.

Congenies, Third month, 17th. On the fifteenth instant,
for the third time I came among the little flock here.
I continue to feel much for them.
The adversary of all good has been very busy since
my last visit to them in sowing his evil seed,
and in some instances he has prevailed so as to cause some bitter fruits
to come forth from plants designed to have been to the glory of God.
I mourn deeply over them; and I have laboured for the healing of differences among some,
and to bring to a state of reconciliation those who by the ties of relationship,
and still more by those of Christianity, ought to be closely united in love.
I am nevertheless comforted by meeting with some with whom I can unite again,
and mingle in the fellowship of the Spirit of the dear Redeemer.
Among these are some dear young persons who were but children when I was last with them.

21st. I had several meetings among this little flock,
and also attended their meeting for discipline,
to which came Friends from various other places.
They were seasons in which a visitation of the Lord`'s
love was very graciously renewed towards them;
even the dear children were much contrited under the sense of his power extended over us.
I have had, besides, several large public meetings,
to some of which the people from neighbouring towns and villages came.
The Lord`'s power was eminently felt to be over all.
Some of their clergy present, said, "`the truth as it is in Jesus, has been proclaimed.`"
Between meetings I proceeded diligently in visiting
the families of those who profess with us,
which service of love has been owned.
I went through deep baptism during that engagement, and there was, in some places,
close searching of heart.

Codognan, Second month, 22nd. My dear friend, Louis Majolier,
accompanied me here this morning.
I visited the few in profession with us in their families,
and deeply deplore their fallen condition; they appear to be a company of backsliders.
I had a meeting with them collectively, and endeavoured, in the ability the Lord gave,
to bring them to a sense of their state, entreating them to return, repent and live.
I had also a meeting with the inhabitants of the place;
mourning and lamentation were the clothing of my sorrowful spirit;
I sensibly felt applicable to them the language of the Lord Jesus Christ, "`O Jerusalem,
Jerusalem, how often would I have gathered you, but you would not.`"
Some appeared reached on the occasion;
may it lead to their bringing forth fruits worthy of repentance.

23rd. We came to Vauvert,
at which place I apprehended that I might stop to have a meeting, but on coming to it,
the way entirely closed in my mind; distress and sorrow came upon me.
I felt encircled with darkness, and under great oppression,
which gradually passed off as I left for St. Giles, where we arrived about noon,
at Firmin Marignan`'s. A meeting was held that evening
which some of the people of Vauvert attended,
and those that profess with us here were also very generally at it.
The love of the world, and the things of it, have caused deep wounds to some of them.
Their love to God and to his Truth has become cold; but the Lord,
in his love and tender mercy was pleased to extend a fresh visitation to them,
and to warm the hearts of some, at least,
by the quickening influence of his Divine Spirit.
Here, I am told that my not stopping at Vauvert is a great disappointment to the people there.
They had expected me, and their clergyman, a high Calvinist, had sent for three others,
like-minded with him, to come and assist him, their intention being, it appears,
to frustrate my having a meeting,
by substituting for it a disputation on some of their favourite tenets;
but the Lord has defeated their purpose; safe it is to follow his Divine guidance.

--

[.offset]
Stephen Grellet now took leave of his friends in Languedoc, and passed on to Montpellier.

[.embedded-content-document]
--

24th. This morning early, accompanied still by Louis Majolier, I came to Lunel, where,
after tarrying a short time, we separated in brotherly and Christian love,
he to return home, and I to proceed alone.
I felt very solitary on my way, as I frequently do, and shed many tears; "`Put them,
O Lord, into your bottle, are they not in your book?`"

I arrived at Montpellier early in the afternoon.
My old friends, D`'Encontre and others,
were very prompt in giving notice of a meeting in this place;
it was held at D`'Encontre`'s, and pretty well attended;
we were refreshed and encouraged together, to hold fast in the way of the Lord,
though some of us may find it a path strewed with many tribulations.
I am encouraged, however, in finding afflictions, like way-marks,
showing that we are in the right path;
for it is through many tribulations that we are to enter the kingdom.

Milhau, 26th. On my way to this place I crossed some high mountains,
where the cold was very severe; at some of the places where I stopped,
opportunities for religious service presented,
in which I proclaimed the love and mercy of God in Christ Jesus,
for the salvation of sinners.
I felt very peaceful on arriving here,
after coming down a mountain that we had been four hours in ascending.
I was much tired, and had scarcely sat down to a late dinner,
when some _gensd`'armes_ came in and asked for my passport,
in which they pretended to find some irregularity;
they took me for a person they were in search of;
one of those concerned in the murder of the King`'s nephew, the Duke de Berri, who,
a few days since, was assassinated at Paris.
They were rather abusive, and took me to the Sous-Prefet.
I did not know what would be the end of this; I expected to pass the night in prison;
but the Sous-Prefet soon recognized me by my likeness to my brother Peter,
who had been Receiver General of this department,
and made apologies for the conduct of the _gensd`'armes_.
There is great excitement through the country in consequence of that assassination;
the people are indeed in a state of ferment.
The overbearing spirit of the clergy, on the one hand, and that of many of the nobility,
on the other, who ought to have learned better things by what they have suffered,
render many of the people ripe for another revolution,
and sad would be the consequences should the Lord permit it to take place;
my soul deeply mourns over my native land since my coming into it.

Rodez, 28th. I arrived here yesterday morning, and visited their prisons,
and a few individuals,
but my mind has most of the time been plunged into such depression and distress,
that I have spent much of my time in my chamber pouring
forth my heart with many tears before the Lord.

Brives, Third month, 3rd. I left Rodez the twenty-ninth ultimo.
Passed through Montauban, Cahors, etc. etc. I tarried but a short time at any place,
except to make a few calls on some pious individuals.
My sorrows continued to be stirred up.
On the road I met with many cases of public distress;
for great suffering prevails throughout the country
I have travelled since I left the South of France.
I have several times stopped on the way to go into their wretched habitations,
where much misery was to be beheld.
Many of the inmates were widows and orphans.
Truly thankful was I to have small matters to hand them in their great distress.
Sometimes, when I stopped on the way, in villages or towns, to take refreshments,
the crowd of the poor that gathered so affected me,
that I had no comfort in taking my meals.
Many of these bore on their countenances the marks of being truly poor.
On inquiry I found that they had been mostly reduced to poverty,
by husbands and fathers having lost their lives in the cruel wars.

I am greatly comforted in my beloved aged mother, now above eighty years old.
Her mind is clear, and she is green in the Divine life.
The Lord Jesus is truly precious to her.
I have had some tendering seasons with her, and my other near relatives.
Some of them now see beyond the priests,
and their prescribed forms and ceremonies in religion.

6th. I had some satisfactory meetings with the persons I visited when here before,
and especially with the dear nuns.
Some changes have taken place among them by death, or removal to other places, but,
those who have come in their stead appear to be clad with the same spirit; others,
whom I had been with in preceding years, retain their religious sensibility.
This evening I had a solemn parting opportunity with my relatives and others.
The Lord was very near,
giving us to feel that through the fellowship of his Divine Spirit,
there are ties far stronger than those of consanguinity.

Limoges, 8th. I arrived here yesterday morning.
My parting with my beloved mother was truly solemn.
It may probably be a final separation here on earth.
On bended knees, my soul was very reverently prostrated before the Lord,
and I was engaged in putting up my supplications unto him for her, when,
bathed with tears, she also kneeled down by me.
My soul`'s request was that the Lord, by his Divine grace and good Spirit, would keep,
sustain, and comfort her in her old age, guide her by his counsel,
during her few remaining days,
and finally receive her unto himself in his mansions of blessedness.
On the road here, my heart was clothed with love for all men, everywhere,
both those whom I have visited,
and those that reside in places where my steps will never be directed.
O, how tenderly did I feel for the Lord`'s visited ones among the nations, rich and poor,
with whom I have been.
May he keep them day by day, by his Spirit,
and cause the light of his countenance to shine upon them.
Fervent also were my prayers for the members of my own religious Society,
who increasingly feel near and dear to me, many of whom are like bone of my bone;
the oneness of the Spirit in the Lord Jesus unites me to many of them.
The stronger my love is for my own people,
the more sensibly do I feel for the rents and divisions that a cruel enemy, as I believe,
is seeking to make among them, by sowing the seed of a spirit of unbelief in Christ,
the only Saviour of men.
I have many sleepless hours on this account, and have shed many tears.
I was glad that I was alone in the carriage, that I might,
unrestrained by the presence of anything, pour forth my heart unto God.
My distress for this nation, the land of my nativity, is also great.
I see blackness hanging over them.
The Lord will overturn, till he comes and reigns, whose only right it is.
Since coming here,
I have had several religious opportunities in the families
of such as I mingled with heretofore in religious fellowship,
and some meetings of a more public nature.
I was also with several of the nuns; two of whom are my cousins,
who retain their religious tenderness.

Paris, 14th. I entered this great city with a heavy heart.
Darkness and impiety prevail to a lamentable extent.
But the Lord has a remnant even here, both among the Roman Catholics and Protestants,
who are as a little salt among them.
There was today a great display through the streets
on account of the burial of the Duke de Berri;
his body has been kept in state, as they term it, ever since his assassination.
It appears he was beloved, and is much lamented;
for he was considered as the most virtuous of the French Princes.

16th. I have been with the Duke de Richelieu, Prime Minister of the King,
who was some years Governor in the Crimea;
he felt much interest in the account I gave him of my visit to the Menonists,
the Spiritual Christians, and the German colonists.
He appears borne down under the weight of the spirit
of faction that prevails in this nation,
and would greatly prize a retreat among those pious persons in the South of Russia.
I endeavoured to strengthen his hands to walk closely and
faithfully under the guidance of the Lord`'s Spirit,
whereby he would be enabled to repress the evil,
and strengthen those in whom there is some good.
There are such here who long that peace in the nation may be maintained;
but there are many others who only wait for an opportunity
to lift up the standard of war.
I was also with the General Pozzo di Borgo, Ambassador from Russia to France,
for whom I had letters,
and through whom I have sent some that I have written to the Emperor Alexander,
and to the Prince Galitzin; also to my beloved friend, Daniel Wheeler;
I feel my mind often drawn towards the dear Emperor,
pouring forth fervent prayers for him,
that by the grace of our Lord he may be preserved in obedience
to the Divine will as manifested to him.
A visit to a niece of mine,
who is placed for her education at an Institute founded
of late years by the Princess of Conde,
has brought me with several of those who have the management of it.
It is well conducted; love appears very generally to prevail within its walls;
every evening before retiring to bed, the girls kiss the hand of the Princess,
and the punishment they feel the most severe, when they have deserved any,
is to be denied this.
I felt great interest in a visit to a boarding school for Protestant girls,
established since my last visit by some of those pious females with whom I then mingled;
a religious and moral education is the principal object of this institution.
This also appears to be the case in another establishment for those of a poorer class;
both the caretakers and the pupils were very tenderly affected
in the religious opportunities I had with them;
two of the young women were much so, one is an Italian, the other is from Sicily.
I had also some satisfactory seasons with several companies of serious persons;
some were Papists, others were Protestants;
a number of Roman Catholics came to my lodgings to unbosom their souls`' distress;
they feel the critical state of the nation,
and they dread the consequence of the ascendency that the Jesuits begin again to have;
they have become convinced that the religion of Jesus
Christ does not consist in outward forms and ceremonies,
but in the love and fear of God so dwelling in our
hearts as to render us obedient to his Divine law,
even the law of the Spirit of life in Christ Jesus,
which sets free from the law of sin and death;
they see that none of the priests`' masses said for them,
their indulgences or absolutions, can avail.

19th. I meet with a greater number of Protestants of seriousness
and piety than I did on my preceding visit.
I am comforted also with some of the Roman Catholics,
but the generality of the people are engrossed with
their worldly pursuits or their pleasures;
others are full of politics,
or so bigoted that there is no room with them to receive
the simple and plain truths of the Gospel of Christ,
and yet, some of these various classes come to see me;
but evidently curiosity is their only object.

Calais, 21st. I arrived here this evening, having travelled night and day.
What shall I render to the Lord for his many mercies, saving help and strength,
and deliverances also during my many deep exercises
and close engagements in these European nations?
Bless your work, O Lord! everywhere let it praise you!

England.
Dover, 23rd. After a passage of eleven hours across the British Channel,
I arrived here last evening; the weather was rough, and the sea-sickness heavy upon me;
but I felt much refreshed every way by coming once more to my kind and valuable friends,
Thomas and Elizabeth Beck.
How pleasant to be again with my friends in religious fellowship with me.

Though it was late, and I felt the effects of the sea-sickness,
yet my soul was so bowed before the Lord, who has, in such a gracious manner,
led me about, and instructed and preserved me, that I was constrained, on bended knees,
to offer up to Him the tribute of thanksgiving and praise.

--
