== Chapter XLIV.

[.chapter-synopsis]
* Voyage Home
* Arrival at New York
* Philadelphia, New York, and New England Yearly Meetings
* Visit to Friends and Others within their Compass, and in Canada

Stephen Grellet embarked at Liverpool in the James Monroe, Captain Rogers.
Though sometimes becalmed--surrounded by thick fogs--and exposed to "`heavy squalls
and stormy winds`"--his homeward voyage did not occupy much more than five weeks.
He landed safely at New York on the Seventh of Eighth Month, 1820.

[.embedded-content-document]
--

At Sea.
Seventh month, 1st, 1820.
I came on board this forenoon; our vessel had gone to anchor below the Black Rock.
George Stacey, Robert Benson, and others accompanied me to her,
and at four p.m. we set sail.
I have five fellow passengers in the cabin, about twelve in the steerage.

First-day, 2nd. I sat very solitary this day,
yet felt the privilege quietly and silently to spend
most of my time alone in my small cabin;
now there is no weight of immediate religious service before me:
how different to the condition I have been in these two last years,
and that with very little intermission.
In my silent prostration of soul before the Lord,
I thought I felt a sweet communion with his servants in every nation,
and under various Christian professions, who love him, fear him,
and are this very day engaged in bringing to him their spiritual offerings.
I sensibly felt also that some of the dear friends I have
parted with were offering up their prayers for me.

This afternoon soon after passing Holyhead, we saw a ship at a distance; I could,
I thought,
most affectionately salute and bid God speed to dear
friends that I suppose may be on board of her;
Nathan Hunt coming to England, as an ambassador for Christ, our Saviour,
and William Rickman on his return home from America,
where he has been on a similar engagement.
I cannot know as yet how it is;^
footnote:[Nathan Hunt and William Rickman arrived at Liverpool on the evening of the 3rd.]
at about the same place, two years since,
I passed under similar impressions that were correct;
the same dear friend going to America, and my beloved friend, Hannah Field,
returning there, having accomplished her Gospel mission in England;
she was accompanied by my dear friends, Samuel and Susanna Emlen.
Thus the Lord gives the word, his servants go, others return:
O may all obey the voice of his commandments!

13th. I have been considerably under the effects of sea sickness till now;
the wind and sea, which have been high, have abated:
my head was in such a condition as not to allow me to read.
I feel very peaceful while looking back on my various steppings the last two years,
but as I draw near to America, the sense that bonds and afflictions await me is heavy.
O You who are a refuge and strength, a very present help in trouble,
forsake not but uphold Your poor servant under whatever may befall him;
he has none but You to flee unto.

First-day, 16th. I felt much for my ship companions, both passengers and sailors,
since I came on board,
but my health did not allow me to attempt to request their
collecting together for Divine worship till today,
when I dared no longer to put off making that effort.
The Captain has most kindly made way for it in the spacious cabin;
forty collected on the occasion;
the Lord`'s presence and power were in a very precious manner felt over us.

23rd. We had a total calm for some days; succeeded by heavy squalls and stormy winds,
so that our sailors are kept hard at work, day and night.
We had an awful time last night; the foaming billows rose very high,
and we went up and down with them in a fearful manner.
Amidst this confusion, however, the still,
small voice of the Lord was mightier than the noise of many waters;
my soul bowed reverently at the hearing of it.
The ship tossed and rolled about too much to allow us to sit down together in a meeting.

28th. The stormy weather was succeeded by thick fogs,
so that the captain has not been able to take an observation for some days;
he thinks we are near Sable Island, which renders him very watchful; we sound frequently.

30th. Thick fogs and stormy weather; the passengers sick; the seamen full of occupation;
so that there is no opportunity for meeting together;
but in the temple of my heart I have found the Lord`'s presence.
He has, by contriting my spirit, prepared himself an offering fit to bring before him.
Great is his power and mercy.

First-day, 6th of Eighth month.
Today we have fine weather; but,
in the expectation of discovering the American shores every moment,
the ship`'s company is too much taken up,
to allow them quietly to sit down and wait upon the
Lord to receive ability to worship him;
so I have retired to my small cabin, which I often feel,
(as I did in Liverpool when I sat in it for the first time,) as a little sanctuary.
The Lord condescends to be near to his poor servant.

7th. This morning, at eight o`'clock, we came abreast of Long Island, and at six p.m.,
we are entering Sandy Hook, with a good wind, and a pilot on board.
What shall I render to you, O Lord, for all your mercies?
All your promises to your poor, unworthy servant have been fulfilled.
You hast magnified your name above your word.
O what preservations! what deliverances! what displays of your power!
I went out very poor--I have been kept so day by day,
and yet all my needs have been supplied from your treasury.
Nevertheless, while it is in my heart, with gratitude and praise,
very reverently to commemorate the Lord`'s works and mercies,
a very humiliating sense attends me, under which I see my many shortcomings,
my frequent haltings, so that shame and confusion of face belong to me,
who am only an unprofitable servant.

New York, 8th of Eighth month, 1820.
I landed here last evening, and met my beloved wife and daughter,
who came two days since from Burlington, to await my arrival; and they did not wait long.
Our hearts overflowed with gratitude at our being permitted to meet again,
after an absence of two years and two months,
during which I have travelled about twenty-two thousand miles.
Silent and reverent prostration of soul before the
Lord was our only language to one another,
for some time; then, on bended knees, and with a bowed spirit, thanksgiving, adoration,
and praise were offered to the Lord.

My joy at our meeting is attended with some alloy,
on my receiving the mournful account of the decease
of that dignified servant of the Lord,
and father in the church, George Dillwyn.
I had anticipated for a length of time,
that I might be permitted to remove from this city to Burlington,
and out of the bustle of this commercial place to
spend the remainder of my days in a quiet retreat,
and long to enjoy there the company of dear friends,
and the spiritual fellowship of this devoted servant of the Lord;
but he is gathered to a better state; his spirit has joined the purified ones.
He followed me closely in spirit, here at home and also abroad,
during my long and distant journeys;
very often did he partake of my sufferings and of my joys;
may I now follow him to heaven above, by keeping, as he did, very close to the Lord,
and the motions of the Divine Spirit.

9th. Attended our meeting.
How mingled were my feelings!
My heart was overflowing with gratitude for the favour
granted to join my friends here again,
and to meet together to worship the Lord God of love and mercy; but alas!
I find the adversary has sown his seed of enmity to the Truth,
and enmity to those that love the Truth; that spirit has spread wide its roots.
On sitting in the meeting, instead of rejoicing among friends, as I had hoped to do,
as in former years, I wept bitterly.
Elias Hicks has led many to imbibe his anti-christian errors.
O! most gracious Lord, who hast been with me,
and hast preserved your poor servant amidst many
perils and sore conflicts in distant nations,
be near now, also, to uphold and preserve under present and impending trials.

--

A few months after his return an interesting little glimpse of his inner life,
and the endearments of home, is afforded in two extracts from letters.

[.embedded-content-document.letter]
--

[.letter-heading]
To George Stacey

[.signed-section-context-open]
New York, 12th month 8th, 1820.

I hear but seldom of William Forster.^
footnote:[W. Forster was at that time engaged in a religious visit in America.]
I feel very tenderly for him.
His exercises are many in this land.
Mine, for the present, when not on my own account, are on behalf of our Society,
under which I feel as one crushed;--but he has in addition, in a land of oppression,
to feel for the poor slaves.

My dwelling, since my return, is in very low places.
My health has also suffered many interruptions.
I must expect now to feel the consequences of my late great exertions.
There are however seasons when I am favoured with
a little capacity to appreciate my favours,
and to number them.
My R. G. and myself are comfortably settled for the present, and, with thankful hearts,
enjoy our chimney corners, our little charge enlivening the scene.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
New York, 2nd month 28th, 1821.

My health is but feeble.
My exercises, which for years had been chiefly directed towards the people at large,
are now pretty much concentrated on behalf of our poor Society,
and some of them are of such a nature that prayer and silent
travail appear the only way to get relief under them.

Our dear William Forster is diligent in his Master`'s service.
Perhaps I may see him at Philadelphia Yearly Meeting,
where I have some prospect of going, should my health permit.
My R. G. and myself are often bowed in much gratitude under a sense of our many favours,
and we esteem it a great one to pass now so much time together.

--

A longer tarriance at home and the renewal of more frequent fellowship with his friends,
did not remove his fears.
His love for Christ did not allow him to remain a
silent observer of what was passing around him.

[.embedded-content-document]
--

1821+++.+++ Third month, 1st. The spirit of infidelity is gradually progressing,
and the eyes of many seem to be so darkened that they cannot see,
nor does their heart understand; very close labour I have had with many of them,
privately and publicly, under the sensible feeling of Divine Love;
but I seem to them as Lot was to his sons-in-law when he
entreated them to flee from the destruction that was impending.
During my journeyings in foreign lands these years past,
perils often threatened me by sea and by land, and among robbers;
but now wounds are inflicted in the house of my friends,
among those with whom I had felt, heretofore, the fellowship of the Spirit of Christ,
uniting us together in the bond of peace.

--

In the Fourth month he attended the Yearly Meeting in Philadelphia,
and returned home in time to be at his own in New York, in the Fifth month.
After that, accompanied by his wife, he went to the Yearly Meeting for New England,
and visited many of the meetings belonging to it.
On a review of these labours, he makes the following record:

[.embedded-content-document]
--

Ninth month, 1821.
Last Fourth month I attended the Yearly Meeting in Philadelphia,
and a few meetings thereabouts.
It felt very pleasant to mingle again in Christian fellowship
with some of my long loved friends in that Yearly Meeting.
Their number is greatly reduced,
but the diminishing of the militant church is to
the enlargement of the church triumphant in heaven.

I wish I could have seen more of the young people
walking in the footsteps of their worthy elders,
who by living faith in Christ had obtained a good report, and, having kept the faith,
have died in it; but the love of the world blinds the eyes of many,
and to endeavour to avoid the cross, they turn aside to their own ways.
I could not help observing also with deep affliction
how many precious sons and daughters of Zion,
comparable to fine gold, seem becoming as earthen pitchers, the work of men`'s hands.
I have deeply lamented over many of their young Ministers,
who have had the anointing oil upon them,
and were designed to be the Lord`'s servants to glorify him,
but alas! the betrayer has prevailed over them; and not over them only,
but I fear also over some of their Elders.

Our Yearly Meeting for New York was in the Fifth month.
There also my anticipated joy in the prospect of mingling with Friends,
was changed for deep mourning.
Seeing how many seem to turn away from their allegiance to Christ, I have often queried,
Lord, who shall stand?

After that Yearly Meeting, my beloved wife accompanying me,
we went to that for New England, held as usual at Newport.
It was to me throughout a suffering time.
There is, nevertheless, a living remnant preserved,
and an earnest travail of spirit among these; I very sensibly felt it;
my soul was united closely to them under their exercises,
and I was comforted and encouraged in faith and confidence
that the Lamb--the Lamb of God,
slain from the foundation of the world--who takes
away the sin of the world--shall have the victory,
however greatly Gog and Magog may magnify themselves against Him;
every believer in and follower of Him, the crucified and risen Saviour,
shall also come out victorious from all the tribulations of the Gospel he may endure.

We went to the island of Nantucket,
attending the meetings of that and other Quarterly Meetings.
Many of a ranting spirit attended the Quarterly Meeting on Nantucket,
but the Lord`'s power was over all; the testimony of Truth was exalted;
He who in ancient days commanded light to shine out of darkness, shined also among us;
light rose over all the obscurity, and Friends were comforted together,
and encouraged to keep very near to the Lord Jesus, who is our light and our salvation,
and also the strength of our life.

After that I visited all the meetings as far as Lynn and Salem.
Friends were encouraged to keep in that retired, indwelling and watchfulness of spirit,
wherein preservation is extended,
and ability is received to set the Lord`'s Truth triumphantly over all opposition.
I was instructed and comforted to see how my dear
aged friend and faithful servant of the Lord,
Moses Brown, is enabled in the meekness of wisdom, and with clearness,
to maintain his testimony to the Truth.

We have returned from that journey in sweet peace,
encouraged to trust in the Lord amidst the fiery trials attending these days,
well persuaded that though many become like broken vessels,
yet none of those that trust in Him shall be confounded,
though they may be brought into the furnace, and there be tried as silver is tried.

--

He was now permitted to remain at home for a while.
The ensuing winter and spring were mostly spent in the bosom of his own family.
The "`care of the churches,`" nevertheless, still rested heavily upon him,
and soon after the conclusion of his own Yearly Meeting, in the Fifth month of 1822,
he again entered upon an extensive religious visit to Friends and others,
in some parts of the United States, and Canada.
Of these various engagements he gives the following summary.--

[.embedded-content-document]
--

Accompanied by my dear friend, John Hancock,
who was my very kind attendant during my religious visit to the island of Hayti,
I visited very generally all the meetings of Friends in the States of New York and Vermont,
and also in Canada; and had many meetings among the people at large,
where there are no meetings of Friends.
The concern that laid with great weight upon me, during my religious engagement,
was that Friends generally, and the dear young people particularly,
might be deeply rooted and established in the saving
knowledge of God and our Lord Jesus Christ;
for "`to know him, the true God and Jesus Christ, whom he has sent, is life eternal.`"
My commission day by day, and from place to place, was renewed,
to preach Christ and him crucified, unto the Jews a stumbling block,
and unto the Greeks foolishness,
but to them that believe the power of God and the wisdom of God,
who also is made to them of God wisdom and righteousness, sanctification, and redemption.
He was delivered for our offences, and was raised again for our justification,
and ever lives to make intercession for them that come unto God by him.
I directed them to him who is the Lamb of God that takes away the sin of the world,
and the author of eternal salvation unto all that obey him.
I rehearsed the words of the apostle Peter;
"`Be it known unto you all and to all the people of Israel,
that by the name of Jesus Christ of Nazareth, whom you crucified,
whom God raised from the dead, even by Him does this man stand here before you whole.
This is the stone which was set at nought of you builders,
which is become the head of the corner, neither is there salvation in any other:
for there is none other name under heaven given among men, whereby you must be saved.`"
Most affectionately did I entreat them, many a time, not to give way, in any wise,
to those who would seduce them from the hope of that
salvation which comes by the Lord Jesus Christ alone;
it is he who gave himself for our sins,
that he might deliver us from this present evil world,
according to the will of God and our Father.
I had the consolation, at times,
to be with those whose faith in the Gospel appeared to be confirmed;
but I bitterly lamented over many who have drank deeply of the spirit of infidelity,
so as to deny the Lord that bought them.

I found great changes in the face of the country in Canada since my previous visit there.
What was then a wilderness, has now become a fruitful field.
Friends have considerably increased, and many Meetings have been established.
Some are pretty large,
and in most places I was comforted in finding among them religiously concerned Friends,
who desire to maintain our Christian principles and doctrines, in the fear of God.
On our way to Kingston, we were, through the Lord`'s merciful interference,
delivered from the hands of evil designing men,
who evidently had in view both to rob us and take away our lives.
Many are the preservations that the Lord has extended to us,
of which we must be very sensible; but very many also are those that we know not.
Truly we can say with David, "`You are continually with me.`"
On our way to the upper part of Lake Ontario, we travelled through some dense forests.
A friend at whose house we stopped at Uxbridge, told me that, within the last few weeks,
he had met with fifteen bears on his way to the meetinghouse,
only about one and a half miles distance; so numerous do these animals continue to be.
There are also many wolves,
so that the settlers have great difficulty in protecting their sheep.

Their Half Year`'s Meeting, held at this time, at Yonge Street, was very crowded.
The people come from considerable distances to attend the meetings for worship.
The Lord owned them by his Divine presence, as he also did those more select,
held for Friends only.
They conducted their business with religious weight.

--

Here Stephen Grellet was in the neighbourhood of David Wilson,^
footnote:[H. C. Backhouse, that noble-hearted, devoted servant of Christ,
had an interview with him in 1833,
and remarks that she "`thought of what Paul said to Elymas,
and partly repeated it.`"--[.book-title]#Journal and Letters#, page 159.]
who had at that time obtained considerable notoriety, and succeeded,
notwithstanding the palpable absurdity of his irreligious and anti Christian opinions,
and the dishonest and immoral tendencies of his fanatical schemes,
in "`drawing away disciples after him.`"
After remarking upon the danger of assuming high notions of spirituality,
apart from a practical belief in the great facts and fundamental truths of Christianity,
made known in the New Testament, Stephen Grellet goes on to say:

[.embedded-content-document]
--

These people surely evince that the description given in the Scriptures
of the depravity of the human heart is not painted in too high colours,
"`The heart of man is deceitful above all things and desperately wicked.`"
Friends have a meetinghouse near; I had a meeting there,
which was largely attended by the people of the place,
and several of those miserably deluded persons.
My mind was brought under deep and sore travail, but God,
who commanded the light to shine out of darkness,
shone among us by the arising of his Divine presence, in which is the light of life,
and he enabled his poor servant to proclaim the glorious Gospel of Christ,
together with the excellency and the purity of the Christian religion.

I went up some distance beyond Norwich,
having meetings among Friends and the people at large,
and returned into the State of New York by way of Buffalo;
from there visited several tribes of Indians, among whom I met some serious persons;
particularly of the Seneca Tribe.
I have been comforted at seasons among that people,
under the apprehension that the language of the Apostle
Peter is applicable to some of them at least,
"`Of a truth, I perceive that God is no respecter of persons, but in every nation,
he that fears him and works righteousness is accepted with him.`"

I visited the meetings of Farmington, and Scipio Quarterly Meetings,
also those on the western side of the North River down to New York,
which we reached at the end of the Eleventh month.

We then proceeded to Long Island, where I attended all the meetings;
but here my soul`'s distress exceeded all I had known during the preceding months,
though my baptisms had been deep.
I found that the greatest part of the members of our Society,
and many of the Ministers and Elders,
are carried away by the principles which Elias Hicks
has so assiduously promulgated among them;
he now speaks out boldly, disguising his sentiments no longer;
he seeks to invalidate the Holy Scriptures, and sets up man`'s reason as his only guide,
openly denying the Divinity of Christ.
I have had many opportunities with him, in which I have most tenderly pleaded with him;
but all has been in vain.
When I saw him last winter I found that there was no more room to plead with him.

At all these meetings I felt myself imperatively called
upon to preach the Lord Jesus Christ as the only Saviour;
to expose the awfulness of the sin of unbelief,
and the fearful condition of those "`who have trodden under foot the Son of God,
and counted the blood of the covenant, wherewith we were sanctified, an unholy thing,
and done despite unto the Spirit of Grace.`"
I laboured the more earnestly both in meetings and in several of
their families because I believed this would be the last opportunity
I might have to plead with many of them in this way.

I felt very tenderly and affectionately for a small company among them,
to whom the Lord Jesus is very precious; whose portion is among the mourners in Zion,
and the heavy-hearted in Jerusalem.
To them the word of Divine consolation went forth repeatedly.

I returned home in the Twelfth month,
having travelled in that journey about five thousand miles,
and that under great pressure of mind from place to place; and now, since my return,
I sit solitary at home, like mournful Jeremiah,
taking up many of his lamentations as applicable to my own people.
The great day of the Lord is near,--it is near!
O Lord! be a strong refuge to those whose trust is in you, and who cannot deny you,
whatever their sufferings may be!

--
