== Chapter XLV.

[.chapter-synopsis]
* Removal to Burlington
* Religious Visit to Maryland
* Virginia
* North Carolina, etc.

For nearly twenty-four years Stephen Grellet had been a member of New York Yearly Meeting.
Though, during that time,
his religious services in America and Europe had
rendered his absence both frequent and long,
the city of New York had, for the most part, been his settled place of residence.
The time had now arrived when he felt at liberty to leave it, and in the Third month,
1823, he removed with his wife and only daughter to Burlington, New Jersey.
He thus became, and continued to the end of life, a member of Philadelphia Yearly Meeting.
To this important movement he refers in his memoranda.

[.embedded-content-document]
--

First month, 26th, 1823.
The time appears to have come for my removal with my family to Burlington, New Jersey,
agreeably to the prospect I had before my return home from my last European journey,
and I am taking some preparatory steps towards it.
I have been very anxious to do right,
and have sought of the Lord that he would direct my path.
I feared lest the trials attending me here should in any wise induce me to take my flight;
but I believe it is in the Lord`'s counsel that I contemplate such a step.
My trials here are indeed heavy, and my baptisms are fiery;
but I do not expect to be exempt from these in the Yearly Meeting of Philadelphia,
any more than here; for wherever my mind is directed in this land I behold trouble.
In the Lord alone is a refuge,
and under the shadow of his wings I desire to place my whole
trust;--verily he is a strength and refuge in time of trouble.
Had I not such a hiding place I must be entirely overwhelmed;
for every other refuge fails.
Thankful should I be could I be hid in some secret corner;
but my Divine Master commands me to proclaim his name, to vindicate his honour,
and to testify of that Salvation which is through him only.

Burlington, New Jersey, Third month, 28th, 1823.
I removed here with my family some days since.
I left New York very mournfully;
deeply was my heart affected towards very many of the members of our religious Society,
with whom I was once united in the fellowship of the Spirit, in the bond of peace:
once they appeared designed to be vessels of honour in the Lord`'s house,
but alas! how have they fallen!
I feel very tenderly for a little remnant left there who love the Truth; and the Truth,
I hope, will uphold them and keep them.
The Lord, the Almighty, is able to do so, and under suffering,
to increase their knowledge of the power and saving efficacy of the blessed Truth,
as it is in Jesus.

--

Not long after his removal he attended the Yearly Meeting in Philadelphia,
of which he was now a member.
A brief notice of it occurs in his memoranda.--

[.embedded-content-document]
--

Fifth month, 2nd. I have attended the Yearly Meeting in Philadelphia;
it was an interesting and solemn time, yet the sour leaven is working secretly in many,
throughout that Yearly Meeting.

--

Some months later he remarks,
in reference to his having taken up his residence at Burlington,--

[.embedded-content-document]
--

Tenth month, 8th. I feel peaceful in having come here; but my sadness is not lessened;
the little dark cloud, which years past, rested chiefly over a small spot at Jericho,
on Long Island, is now like a thick darkness over the land.

--

Stephen Grellet was not long permitted to remain
with his beloved family in their new place of abode.
Early in the spring of 1824 he again believed it to be his religious duty
to prepare to leave all to follow the leadings of that blessed Master,
whose voice he had so long known.
His mind had often been attracted in the love of the Gospel,
towards some of the Southern and Western States, as far as New Orleans.
After again attending his own Yearly Meeting, at Philadelphia,
he entered upon this extensive service, which occupied nearly a year.

[.embedded-content-document]
--

Third month, 6th, 1824.
A prospect of religious service that I had before me some years past,
so far as New Orleans, came again with weight upon me, during the last year,
and having apprehended that the time had now come to engage in it,
I committed myself to my dear Lord`'s guidance, whose I am, and to whose service, myself,
my small substance and my all are offered up.
Truly, we have here no continuing city: my beloved wife and I are very sensible of it;
ever since our marriage we have found it to be so; but the Lord is very good to us;
in blessing he blesses us, and multiplies his consolations to us;
all this is of his free and unmerited mercy,
for we are nothing but unprofitable servants.
I have no works of righteousness, nor of faithfulness to trust in;
my hope of salvation and acceptance before God is
through the mercy and love of my dear Redeemer.
I have put my small affairs in order, and obtained certificates of the unity of Friends,
both of the Monthly and Quarterly Meetings, with my proposed religious engagement.

Philadelphia, Fourth month,
24th. I left home for my contemplated journey in
the service of the Gospel of my great Lord and Master,
through the Southern and Western States.
I am now attending this Yearly Meeting;
a discontented spirit is evidently gaining strength in these borders; O! that Friends,
to whom the Truth continues to be precious, would rally nearer and nearer to it,
keep close under its influence; it would keep and preserve them.
Friends have evidently a sore warfare to engage in,
even against wickedness in high places; their weapons must be spiritual,
and the whole of their armour must be of God, or many will be wounded and slain.
I am nevertheless persuaded that, though the conflict may be long and sore,
the Lamb and his faithful followers will eventually have the victory.

My dear friend, John Gummere, from Burlington,
having kindly concluded to accompany me as far as Virginia,
we left Philadelphia at the close of the Yearly Meeting, and proceeded to Baltimore,
having meetings on the way.
Those held in the towns of Lancaster and York were largely attended by the inhabitants.
The Lord`'s presence and power were felt over us in a very gracious manner,
to the contriting of many spirits.
At the meeting at York, there were four ministers, two Presbyterian, one Episcopalian,
and one Methodist.
They united at the close of the meeting in the acknowledgment
that the Truth had been proclaimed to them that day.
A German and his wife, from Stutgard, were also present, whom I had been with in Germany.
They appear to retain their religious tenderness.

I had some close and trying services at Baltimore, and yet there are a few Friends there,
with whom I feel a precious unity.
I was refreshed in my spirit, by being there again, at my long loved friends`',
Gerard T. Hopkins and his valuable wife.

I took several meetings from there to Alexandria.
I was brought under sore conflicts of spirit, through that section of the country.
In some places my mournful language was,
"`they have taken away my Lord and I know not where they have laid him!`"
I have been several times at Alexandria;
but sorrow of heart has uniformly attended me there.
The pure seed is in bondage; how can I but be in suffering also?

I had at Fredericksburg a very large meeting in the Presbyterian meetinghouse.
The prospect of having a meeting at that place,
where I have repeatedly seen the poor slaves treated with great cruelty,
felt awful to me.
But the dear Master helped his poor servant to do the work required.
I was enlarged in setting forth the love of Him who has loved us while sinners,
and has commanded us to love one another as he has loved us.
His love is to all men, he has died for all, and we must love all,
and do to others as we would they should do to us.
Were this the case, could men oppress one another?
could they wage war against one another?
could they hold their fellow men, of any colour or nation, in a state of bondage?
The Lord`'s power came over the meeting in such a manner
as to bring conviction to the minds of the people,
and seriousness prevailed over all.
But, alas! it may prove to many as only the passing of the morning cloud.

On the way to Richmond, stopping on the road to feed our horses,
we saw a large concourse of slaves in an orchard.
They were holding a meeting, previous to the burial of an aged fellow negro.
Such a meeting was allowed them on the occasion,
and a magistrate was with them to see that order was maintained.
There was no need however of his interference, for they were very quiet and serious.
One of their number was preaching to them.
He was earnest and fluent in his communication, and the matter was good and appropriate.
It was pleasant to me to stand awhile among them, listening to what was said.
I doubt not that many of them were offering unto the Lord acceptable worship.

I had two meetings at Richmond; one was largely attended by the inhabitants.
I had several times, before now, apprehended that there are in this place,
among much of what is evil, some well-disposed, pious persons;
to these the Lord gave me to minister,
for their encouragement in the way of righteousness and holiness.

The Quarterly Meeting at Wain Oak was a time of suffering to me;
things are very low among them, and there is a great departure, among the young people,
from the purity and Christian simplicity of our religious profession.
Many of these have been sorely wounded by associating with slaveholders.

On the 15th of the Fifth month began the Yearly Meeting for Virginia,
held this time at Gravelly Run.
The meeting for Ministers and Elders was attended with solemnity;
a living remnant is preserved among this people.
Years since they were a numerous body, but many have removed to the Western country;
others are deceased; the weight of service is heavy on the few who remain.
Besides their important concern for the right maintenance of our Christian testimonies,
their labours on account of slavery are considerable;
some of them devote much time to it,
and they have been successful in promoting the freedom of many of the people of colour,
who were illegally held in bondage.
Among the cases that have multiplied their labours, is that of John Pleasant,
a valuable Friend, who lived in the days of John Woolman.
He had a large number of slaves;
he liberated all those that were above thirty years of age,
and made provision for the liberation of all the others,
as they attained to the age of thirty.
When this act was done, several of them were very young;
consequently it would require years before they could obtain their freedom.
During that long period the offspring of these multiplied to a great extent;
many of them were by evil disposed persons sent away and sold into remote States.
The object of the labour of Friends was to have a proper register of all these families,
of the ages of the children and their offspring;
to trace them out to the places to which they have been removed;
and to obtain the freedom to which they are entitled by the laws of the land.
They have been very successful; but, as they continue to trace out some of these people,
it opens fresh and arduous fields of labour.
Another case is that of an Indian girl, who was unlawfully detained as a slave;
she had a number of children, and the offspring of these have also greatly increased.
As she was, by right, a free woman, all her descendants should be free.
Friends have succeeded in liberating many of these;
several of them also having been removed into the Southern and Western States.
While the Meeting for Sufferings was sitting,
there came a deputation from a branch of the Colonization Society at Petersburg,
which is about twelve miles distant.
Some Friends were named to go out and confer with them and to know their object.
Their request, on behalf of the Colonization Society, was,
that Friends would unite with them for the promotion
of the object which that society had in view.
The Meeting for Sufferings gave due consideration to the proposition,
and were united in the judgment that they cannot join with other
bodies or societies in the management of matters of this sort;
and sent some Friends to give that information to the deputation,
together with the reasons that Friends have for doing so.
The deputation were so well satisfied with the reasons given them,
that they said they had not thought that our Society
could have such good and substantial ones.

The meeting next day was attended by a great concourse of people;
they came from several miles round; many from Petersburg, Richmond, etc.
No house could have accommodated them; the meeting was, therefore, held out of doors,
under the shade of large trees.
I dreaded the consequence, when I beheld the multitude,
lest there should be some unruliness; seats were provided for many,
but the greater number stood.
Great quietness prevailed over all, and the Lord was graciously near;
He enabled me to proclaim the unsearchable riches of the Gospel of Christ.

Friends here are few in number,
but they conducted the business that came before them in this Yearly Meeting,
with weight.
The precious badge of love and unity is apparent among them.
It was a season of edification to many.
My dear friend, John Gummere, left me at the conclusion of the Yearly Meeting.

I had meetings through that part of Virginia, as far as Suffolk.
These meetings were numerously attended by slaveholders.
I cannot describe the weight of distress brought on my mind on these occasions;
for the yoke of slavery has become heavy here; their treatment,
and the oppressive laws against the free people of colour, are not less so.
It is very evident that their Colonization Society, under fair, specious appearances,
has for its object to drive the free negroes away from the country, so that slaves,
by not seeing any of their colour in the enjoyment of liberty,
may the better submit to their state of bondage.
They have so increased the penalties on the free blacks,
that if anything of these is charged with having
stolen to the value of one dollar and fifty cents,
he is sold as a slave, and transported out of the country.
Those that have been set free of late, must leave the state within one year,
or else they are liable to be sold again as slaves.
Free people of colour are liable to be taken up as suspected slaves,
and confined in prison till they can give proof that they are free; but, being shut up,
they have not an opportunity to obtain this proof; or, should they obtain it,
if they cannot pay the expenses incurred by their imprisonment,
they are also sold as slaves.
Will not the Lord plead with the people for these things?
Will He not arise for the cry of the poor and oppressed descendants of Africa?
I feel deeply for them, and not less awfully for their oppressors.

From Suffolk I went to Norfolk, where I had another large meeting.
The Lord`'s servants can have no other doctrine to preach, than that which he gives them;
and as his word is yea and amen forever, so is his doctrine.
It cannot change.
The fast that the Lord has chosen, is to loose the bands of wickedness;
to undo the heavy burdens; to let the oppressed go free; and to break every yoke;
as he says by his prophet Isaiah.
O, that the people would not only hear, but obey the word of the Lord.

I passed from there into the lower parts of North Carolina,
attended their Quarterly Meeting for those counties, held this time at Sutton`'s Creek,
which was very satisfactory.
The public meetings were baptizing seasons.
Great crowds attended them,
and the Lord was pleased to extend his gracious invitation
to return to him with full purpose of heart.
Through those counties I had several large meetings.
Some entirely among the slaveholders.
Others, chiefly among the slaves; for, although it was given me to proclaim the Truth,
without disguise, to the masters, their hearts appeared to be open towards me,
and they made way very readily for the meetings I appointed for their slaves.
Some of the masters attended, but generally they said,
that they were persuaded that I would not say anything in their absence,
that I would not in their presence.
The Lord was very preciously near in several of these religious opportunities.

Sixth month, 7th. I had two large and laborious meetings.
That in the forenoon, was held in a large house, at Beach Spring.
When I came to it, I found it filled with women,
so that I had some difficulty in getting in,
and about the doors and windows there was a great crowd of men.
They stood very quiet, though the sun was powerful.
It was so warm that, during the service I had in that meeting,
the perspiration ran down into my shoes, and on the floor.
It was a season of much solemnity.
The meeting at three p.m., was held at Hertford, in the Baptist place of worship.
I was much exhausted after the preceding meeting, neither had I time to take rest.
I felt dismayed when I came to the house,
on beholding again another great concourse of people; but, on entering the meeting,
I felt as if it was encircled by the Divine presence,
and that the Lord`'s power was over all.
It was a baptizing season.
The Lord Jesus Christ was preached as the Light and Life of men.
Utterance was given to his servant,
and a door of entrance was opened in the hearts of the people,
to receive the word preached, so that, at the close of the meeting,
my strength seemed to be renewed, and my soul was greatly refreshed.
I went on my way about twelve miles that evening.

I attended the meetings in Contentnea Quarter, and had also several public meetings.
The bondage of the poor slaves is heavy in some places.
The heat has been so great, that both men and horses have dropped down dead,
while in the fields.
I have seen oxen, from whose nostrils the blood was running.
This has been the case several times with my horse,
so that I had some difficulty in getting on.

I came to Raleigh, where I had a satisfactory meeting in the house of the Methodists.
There are a few pious persons among the inhabitants of that place.
I went to visit the Governor,
to see if some steps could not be taken towards the amelioration
of the condition of the slaves in that state,
and to prevent the arbitrary cruelty exercised by many of their masters.
He received me with kindness, and heard what I had to say.
The Sheriff and some other principal officers of the Government were present.
On the broad subject of slavery, he said, it would be a great relief to him,
and many others, if they could be delivered from such a burden, under which,
the masters as well as the slaves are much to be felt for,
and it was his opinion that measures throughout all the slave states,
should be taken to promote their liberation,
similar to those that have been taken by the state of New York.
In answer, however, to what I had said respecting the religious and moral education,
the promotion of the solemn tie of marriage among the slaves, etc., he remarked,
"`as long as slavery continues as it is,
should we cultivate the tender feelings of their minds,
we should only increase their sufferings and misery, for,
if the attachment between husband and wife, or parental and filial affection,
be promoted, they could not bear it;
their hearts would be rent at the separations which are
continually made between individuals thus connected.`"
Some in the company asserted that the negroes were destitute
of tender feelings,--that they had no love or gratitude,
towards their masters.
I inquired, if, according to their acknowledgment,
the masters were endeavouring to destroy the tender
feelings and affection between a man and his wife,
and all parental and filial love and tenderness,
how they could complain that affection and gratitude were withheld from masters,
who treated them with such cruelty, as not only to oppress their bodies,
but also to degrade and debase their minds below the brutes,
who love and cherish their mates and their young.
The Governor was very civil, and requested that if I came again to this place,
I would come to see him.

I reached Hillsborough the 20th, and had a large meeting; no Friends reside in the place;
I could mingle in spirit with several who love the Lord Jesus.
I feel also much relieved from the weight of slavery,
which has for many weeks been like a mill-stone upon me.
There are but very few slaves in this part of North Carolina.
I now attended all the meetings of Friends in these Quarterly Meetings.
I felt much interest for the young people, who are numerous;
may they yield to the visitations of Divine love extended to them;
the Lord loves an early sacrifice.
In several places some of them have manifested such religious sensibility
as to induce me to entertain a good hope respecting them.

The 8th of Seventh month, accompanied by several Friends, I went to Salem,
where the Moravians have a large settlement.
My heart had been drawn towards them in Gospel love
when I was in these parts years since,
and the same feelings being now renewed,
I was best satisfied to make the trial to have a meeting among them,
though I was discouraged from the attempt by the information,
that hitherto they had carefully avoided admitting into
their settlement any minister from any other denomination.
It was late in the afternoon when we arrived in their town.
I went at once to their Bishop; my name and my speech betraying me to be a Frenchman,
brought to his recollection the account sent them from Germany, England, etc.,
of the visits I made there to several of their establishments.
When he found I was the same person he had heard of, he appeared much pleased to see me,
and on my telling him that the Lord`'s love towards
them had been my inducement to come here,
he very freely encouraged me to have a meeting with them,
and asked when I intended to have it.
I proposed the ensuing morning;
he said that the evening was the best time to have all the people collected;
early in the day many go to their rural labours, at a distance in the country;
and he proposed that very evening at eight o`'clock; it was then seven,
but he thought there was sufficient time to give the information.
When I went again to his house he accompanied me to their spacious place of worship,
and the house was filled with their people;
I do not know that a single person came in after us.
They sat, as at a Friends`' Meeting, in perfect silence; their minds also were gathered,
as I believe, before the Lord; his presence was over us,
and many of us were refreshed together before him.
I have seldom known a more solemn silence to prevail during the whole of a meeting.
The next morning, the Bishop accompanied me to the several schools,
the departments for the widows, the single sisters, and the brethren;
in which places I had religious opportunities; some were tendering seasons.

I left Salem in time to reach Union Town,
where a meeting for that afternoon had been appointed.
The heat of the weather was very oppressive, so that I felt much spent after that meeting.
Samuel Hutchinson, from Washington, who came to meet me in the lower parts of Carolina,
was also so much affected by the unwholesomeness of the water, and the heat,
that he was obliged to tarry behind to be nursed for awhile.

I now came into Deep River Quarterly Meeting,
and was at the several meetings that belong to it.
Some of them were so numerously attended by the inhabitants that
the meetinghouses could not contain one half of the people;
we, therefore, held these meetings out of doors, under the shade of trees.
My beloved friend, Nathan Hunt, accompanied me to many of them.
During one of these meetings we had a copious shower;
but the people were not disturbed by it; they were thankful for the rain;
none had fallen for a considerable time, so that in many places their flocks, horses,
etc., suffered for lack of water, and all greenness was dried up.
How very dependent we are on the Lord!
He opens his hand and we are fed; he hides his face and we are troubled.

The last meeting I attended in that Quarter, was that to which dear Nathan Hunt belongs;
it was one of those favoured seasons seldom witnessed; the shout of the King of Kings,
and Lord of Lords, was heard among us;
our spirits were very reverently prostrated before the Divine Majesty,
and living praises were ascribed to him.
Here Samuel Hutchinson met me again; his health has improved.

Accompanied by two dear friends, we set off for Lynchburg, Virginia,
about one hundred and fifty miles distant.
The first place we stopped at was Danville; Friends have never had a meeting there before.
The people of the town, and of the country for some miles distance, came to it,
and sat down in seriousness,
evincing that they felt the solemnity that ought to be our
covering when we come together to worship God.
Some of them were very tender,
and at the close of the meeting they parted from us in a loving manner.

Late in the evening of the 19th, we came to Staunton;
the weather had been so warm during the day, that we had to travel very slowly.
The blood so rushed down the nostrils of my horse, that I was obliged,
whenever I came to a run of water,
to let him stand in it awhile in as deep a place as I could get to;
this seemed to refresh him and stop the bleeding.
We heard of several men and beasts that had died on the road and in the fields,
in consequence of the heat.
The next day I had a satisfactory meeting in the Methodist place of worship.
There is only one family of Friends left here.
The emigration from this Quarterly Meeting to the Western country has been very general;
they wished to have their residence where slavery does not exist.
A few miles before reaching Lynchburg the same evening, the Lord, in tender mercy,
preserved my life from threatening destruction.
We came out from the woods to a rough turnpike, at a place where the descent is steep.
A herd of cattle with bells on their necks, came running behind us,
which frightened my horse; a dog at the same time seized him by the hind legs;
he furiously ran down the hill, kicking so that his hind feet came very near my head;
at last he ran the carriage against a stone with such force as to throw me out;
then the carriage passed over me.
I had three ribs bent in on the left side, a severe contusion on the head,
and the right wrist considerably injured; my back and hip were also hurt.
I was assisted into another carriage,
and got to the house of my kind and hospitable friend, William Davis, Jr.,
for which I was aiming.
I was so well nursed that very shortly after I was
able to ride out three miles to a meeting;
by the Lord`'s refreshing presence, my soul and my poor body also, were invigorated.
I had, however, to keep my seat while communicating what, in the love of Christ,
I thought was laid upon me for the assembly.

25th. I had two meetings; one in the forenoon with Friends,
the other in the Methodist`'s large house at Lynchburg,
attended by the people of the various religious denominations in the place.
The Lord was near and good; he strengthened me to proclaim his Gospel,
which is designed to be glad tidings of great joy to all people;
a joy that all may become partakers of, if, by their own fault,
they do not frustrate the purpose of the Redeemer`'s love towards them.
In his love and free mercy he has come to deliver us from the bondage of sin,
and has commanded us to love one another as he has loved us.
Can we say that we love him if we observe not his commandments?
Can we say that we love our fellow men,
if we act towards them contrary to what we would they should do towards us?
Should we think, that those who are now held under the galling yoke of bondage,
acted justly towards us,
were they to rivet the same heavy chains upon us that they are now laden with?
It will not avail us to say that slaves are of another colour than ourselves; they,
equally with us, are the children of the same Almighty Father.
He has made all the nations of the earth of one blood; Christ Jesus has died for all men,
and he commands us to love all men.
I entreated them to live in the Divine fear, to do justly, to love mercy,
and to walk humbly with God.
Much seriousness was over the assembly, and none made any opposition,
though I fully set before them the unrighteousness of slavery,
and the guilt of slaveholders.

Here my dear friend, Samuel Hutchinson, concluded to return home,
which is a great relief to me;
for I consider him much more unwell than he apprehends himself to be.
I have now a long and arduous journey before me over the mountains,
which seems formidable in my lame condition.

Winchester, Virginia, Seventh month, 31st. I arrived here this afternoon,
having been about six days on the road, which, especially over the Blue Ridge Mountains,
was rough and difficult, driving myself with my lame side and wrist, etc.;
my gracious Master has preserved me; blessed and praised be his name!
I had a young man with me on horseback,
who has been very kind and useful to me on the way.
The last few days I had meetings at Winchester, in one of the Dissenters`' houses,
then at the Ridge, Hopewell, Black Creek, etc.
Friends have become much reduced in number, and many of those who are left,
have forsaken their love of the Truth, to imbibe infidelity; some even have done so,
who formerly appeared to be well established.
My soul goes mournfully from place to place.

Union Town, Eighth month,
8th. Two young friends from Hopewell have kindly accompanied me here, on horseback;
they were helpful in getting across the Alleghany Mountains.
Some parts of the road have improved since I last travelled over them;
but most of the way continues to be very rough;
notwithstanding the fatigue of the journey my side is better.

I attended the Meetings of Friends on these mountains, and had some, also,
in places where no Friends reside.
From place to place I had to proclaim the first principles of Christianity,
many having been shaken away from the foundation;
the cross of Christ has become an offence to them;
they want to devise for themselves a way of salvation more
pleasing to their creaturely wisdom and natural understanding;
yet there is a remnant in these parts,
who are not ashamed to acknowledge a crucified and risen Lord,
as their only hope of salvation.

--
