== Chapter XLVII.

Religious Visit to Kentucky--Tennessee--South and North Carolina, etc.

Accompanied, now, by his friend John Street,
Stephen Grellet left the Blue River settlement of Friends in Indiana,
and crossed the Ohio River into Kentucky.

In this State I meet with great openness among the people.
They come readily to the meetings that I appoint,
and hear with all attention the testimony to the Truth I have to proclaim among them.
They freely also let their slaves come to meeting.
We had large gatherings at Elizabethtown, Munfordsville, Bowling-Green, etc.,
and so on to Russelville;
on the way to which we stopped at a large settlement of the Shakers.
We found among them greater openness than I have met with in some others of their establishments,
but yet there is much to cover the mind with sadness.
The meeting at Russelville was attended with solemnity.
There was brokenness of heart among the people generally.

We then entered into West-Tennessee, and went, under a good deal of discouragement,
some miles out of our direct road, to a small town called Springfield;
but I have found it again to be the safest way to follow the Lord`'s guidance;
he leads in the right way, though it be contrary to our own.
Here I found a people well worth visiting.
Their hearts were prepared to receive me.
The Lord`'s presence was with us in a meeting in that place, in an eminent manner.
I was reminded on the occasion of the testimony of the Evangelist,
that the Lord sent his disciples to those places where he himself would come.

First month, 14th, 1825.
We came to Nashville, where this evening we had a relieving meeting.
My mind, in many places, is deeply tried on account of the poor slaves.
The visits I pay to slaveholders give me opportunities to plead in private,
as well as in public, the cause of that suffering portion of my fellow beings.
How can I but do so, if I proclaim with faithfulness the truth as it is in Jesus!
It is a doctrine that many slaveholders are not accustomed to hear, but the Lord,
by his Spirit, raises a witness in their hearts to the truth of it,
and they appear also sensible that it is in the love of God,
and in love to their own souls, that I act towards them.
We can scarcely prevail upon the innkeepers to receive any compensation
for their entertainment of ourselves and our horses;
but we tell them it is their just due,
and that as in the free love of Christ we come to visit them,
our greatest reward would be to see them turn to the Lord with full purpose of heart.

We proceeded afterwards towards the settlements of the Cherokee Indians,
having several meetings on our way.
One of these was at Murfreesborough, their present seat of Government.
It was largely attended.
Probably, curiosity only, brought in many of the people;
but the Lord condescended to render it a time of the visitation of his love and mercy.
It was powerfully extended to them, and some appeared to be made sensible of it.

From there we came to the foot of one of the Cumberland
Mountains to a place called Stone Fort;
on the other side of the mountain we got to a deep stream, but neither broad nor rapid;
the melting of the snow had carried away the bridge;
we could devise no other way to cross it than each to ride one of the horses,
and to enter the stream slowly so as to allow the carriage to float on the water,
that our horses by swimming might drag it after them;
we succeeded beyond our anticipations.
We reached, that afternoon, a small town,
where my dear companion was taken ill with a high fever; the people were kind,
and suitable attention was rendered by a physician.
I had there a good meeting.

Two days after J. S. felt so well that we set off on our journey,
crossed the Tennessee River and came on the Indian lands.
The first of the settlements was that of John Ross, the father;
he treated us with kind hospitality; we had a meeting among the Indians;
many of them have made great progress in civilization, and have good farms well stocked;
their homes are comfortably furnished.
Several of their young people, the females particularly,
have received a good education among the Moravians.

22nd. We came to the widow Wolf`'s, a motherly, pious woman; she wore the Indian dress,
and her daughter had been educated among the Moravians.
I had a large meeting in their house that evening;
the Indians came to it from some distance.
Here we were told that about five years since, George Guest, one of their tribe,
now about fifty years of age, was heard to query of some other Indians,
why they might not have writings in their own tongue, as the white people have in theirs?
and thus be able to communicate with one another,
and keep records of what transpires among them, as the white people do?
They told him it could not be effected; but he said he thought it might.
He devised eighty-six letters or characters,
each of which is the beginning of a word in their tongue, and is itself a monosyllable.
He was about two years at work,
but he succeeded so well that he instructed several
Indians to read and write their language;
some of these went to Arkansas, where a considerable portion of their tribe reside;
they introduced the knowledge of these characters so completely,
that now they correspond with each other.
They are preparing a printing press to print their laws,
and even to have a newspaper in their own tongue.

23rd. We went to the Moravian settlement or Mission House.
Smith and his wife, the heads of it, received us with Christian kindness.
He readily made way for my having a meeting with the Indians;
it being First-day they had come in from some distance.
It was an interesting time;
many of them appear to have come to the knowledge of the Lord Jesus Christ as the Saviour,
and were very tender during the meeting.
The children that board in the Mission-House give proofs
of the religious care and instruction extended to them.
I had another meeting in the afternoon, which was equally satisfactory;
most of the Indians present understood English,
those who did not were as serious as the others,
and appeared to feel what I imparted to them by an interpreter.
We went that night to a wealthy Indian`'s, Van, by name; he has a large double house,
well furnished; there also I had a satisfactory opportunity.

24th. We came to another Indian`'s, John Saundore, who has a large settlement about him.
He took particular interest in spreading notice, and preparing a place for a meeting.
The Lord`'s baptizing power was felt among us.
They are a very interesting people.
Great sobriety generally prevails among them.
They are strict in preventing the introduction of spirituous liquors.
Their law imposes a fine of fifty dollars, on every attempt to bring them in,
and it is also ordered that vessels in which they are found, shall, with their contents,
be destroyed.

25th. We crossed another water by swimming our horses, the wagon floating behind; but,
being rapid and broad, we were in some danger,
as the current drove the carriage down with it.
We travelled about one hundred and fifty miles on the land of these Indians.
They treated us uniformly with civility.
We have generally found good accommodation among them, and, in many instances,
they have manifested religious sensibility.
Many of them have their land under good cultivation,
and have from twenty to fifty head of cattle; also from fifty to two hundred hogs, which,
when fat, they sell in the Southern States.
They are at present under great apprehension that they may
soon be driven away from their already diminished possessions.
The bordering States, principally Georgia, begin to encroach and harass them considerably.
John Saundore told me, "`when the white people landed on our shores towards the sea,
they had nothing to eat; we gave them of our provisions; they had no cabin,
we gave them land to erect some, and to cultivate corn;
we made them sit down on our logs, by us;
continuing to increase we gave them more and more room,
till now they have crowded us to the further end of our log,
and they press upon us so hard, that they will soon have the whole of it, for themselves;
and where can we go to spread our blankets?`"

On our way to Georgia, we swam, or floated, over several more watercourses.
Monroe is the first town in that State we came to, after crossing the Chattahoochee river.
We had meetings in several towns on the way to Milledgeville,
which is the seat of Government at present.
The meetings at Monroe, Madison, and Eatonton, were well attended.
The people were respectful, and behaved with seriousness.
It was remarkable that, though in private in some of their families, and in meetings,
I proclaimed against the great sin of holding our fellow-men in slavery,
a practice contrary to the imperative commandment of God,
to love our neighbour as ourselves, and to do to others as we would they should do to us,
yet none appeared to take offence at my plain speaking.
I am the first Friend they have seen in these parts;
yet some of them know our conscientious testimony against slavery,
and that the members of our Society, who formerly held slaves, have liberated them.
The hearts of the innkeepers also, in these parts, are so open towards us,
that we have difficulty in prevailing upon them to receive the
compensation due to them for the entertainment they give us;
but I cannot be satisfied to accept of their kindness,
and I also endeavour to compensate the poor slaves for the services they render us,
as we pass on among them.
We met at Madison a very interesting family.
The children, as well as their parents, were brought under great religious sensibility.
Tears flowed in abundance while I was addressing them.
They could hardly part from us.
The meeting at Milledgeville, though held in a spacious house and very crowded,
could not accommodate all the people, many stood at the doors and windows.
The Bishop of the Methodists, for this State, came to see me after meeting.
He told me that they have under close consideration to pass
a law to oblige their members to set their slaves free,
and he believes that the greatest part of their Society is ripe for taking that step,
which he considers one of vital importance to other Christian professors,
many of whom acknowledge that slavery cannot be reconciled with sound Christianity.

We went from there to Sparta and Augusta, having meetings in the towns on the way.
That at Sparta was a solemn one.
John Lucas, a pious man, would not allow us to remain at an inn.
He, like Cornelius, would have his household collected together;
his slaves came very generally; some of these were much affected,
and evince that the name of Jesus is precious to them.
I find indeed that several of them are in close religious fellowship with their masters;
they were introduced to me as brothers and sisters in Christ.
At meetings I have had of late there were many of that description;
in some places they occupy the galleries, in others the floor of the meetinghouses.

Augusta, Second month, 2nd. Here I find in Doctor Watkin`'s family some piety;
he accompanied me to several serious persons; among others,
the mother of the late Caroline E. Smelt,
respecting whom an interesting memoir has been published; she made a triumphant end.
The Doctor`'s wife and several young women, her intimate friends,
have not lost the religious impressions made upon them,
nor the earnest and pious words of Christian counsel that Caroline addressed to them.
I had solemn opportunities in some of their families, and with them collectively;
also a large public meeting.
Among the interesting characters I met with here, is a young man,
whose father is wealthy and lives in great style;
but this youth is brought under the yoke of Christ;
he cannot mingle in the dissipation of the family,
and spends much of his time in religious retirement;
he bears the marks of having been with Jesus.
I feel very tenderly for some of the Lord`'s children in this place;
may he water them and keep them!

At Waynesborough we had much satisfaction;
many are prepared to liberate their slaves when the laws will allow,
which they hope will be soon;
and as their love and goodwill expands towards their fellowmen,
so also it does towards the dear Redeemer.
They give me full opportunity at their houses with the slaves,
and allow them also to come to the meetinghouse.

At Jacksonboro`', where we had come under the expectation of having a meeting,
and proposed to have one appointed, my way totally closed.
It is a dissipated place, where the fear of the Lord is not.
Under distress for them, even to weeping, we passed on towards Savannah,
having meetings on the way; these were mostly very trying.
There we found that the poor slaves are under much oppression,
and the minds of their masters greatly darkened.
As they love not their fellowmen whom they see, neither do they love God,
whom they do not see.
Some parts of that country much resemble the state of the people that inhabit it;
the land is swampy and unhealthy; they have many reptiles, mosquitoes, alligators, etc.

I find at Savannah a young clergyman, among the Presbyterians, a pious person.
I had a letter for him from the widow Smelt, at Augusta.
His name is Steele.
He was educated for a lawyer;
but being visited with powerful convictions of the Holy Spirit
he has left the practice of the law for the service of the Gospel;
he is in a humble, tender state of mind;
he appears much more disposed to preach Christ and bring all near to him,
than to make proselytes to the Presbyterians; "`To Christianity,`" says he,
"`neither more nor less, we should all come.`"
His father is of the first rank in this place.
The public meeting we had here has been more satisfactory than I feared it would be;
I went to it under great depression.
The jealousy of some of the inhabitants was excited against my companion,
because he is from the State of Ohio; many are in a state of ferment,
and lately treated roughly some persons from the Eastern States,
who had handed out some pamphlets against slavery.
The meeting however was largely attended, and very quiet.
All human and slavish fears were taken away,
under a grateful and humbling sense of the Lord`'s presence and power,
so that I flinched not from proclaiming the plain and simple truth.
None spoke an unkind word to me,
though the circumstance of an alarm of fire in the
evening brought some of the inhabitants under anxiety;
they dread such occurrences,
much fearing lest it should be a signal for the rising of the slaves;
on such occasions they repair to their arms.
O how many evils slavery entails, both upon the slaves and the owners!
Some of the latter are very sensible of it,
and deeply lament the bondage under which they themselves are brought.
They speak very freely on the subject with me.
Several of the pious in this place kept near us to the last;
and as we are not likely to find any inns on the road we are going to travel,
they kindly gave us letters to some of their friends who reside on our way.

We left Savannah on the 6th of the month, crossed the river,
which brought us into South Carolina, and came to the plantation of W. T. Norton,
to whom we had a letter of introduction; he was not at home when we arrived,
but his wife gave us a kind reception; she had several female visitors;
one of these appears to devote much of her time and substance to acts of benevolence;
she has no children of her own, but has several orphans under her charge.
Five of these were bequeathed to her when they were only a few months old,
and one was only a few weeks.
Now she has a pressing request to take several more under her pious and maternal care.
I had a very interesting time with these females.

Late in the evening the master of the house came in,
with about twelve of the neighbouring planters, all armed.
I did not understand what I saw, nor what I felt.
We all sat down to supper; the master of the house was civil,
but my distress was not lessened.
After rising from the table,
he took me aside and told me how greatly he was himself tried;
for the white population of the neighbourhood were under arms,
and would that night encircle a swamp where they believed
about thirty runaway slaves had concealed themselves,
and they were determined to have them dead or alive; he could not excuse himself,
he said, from going with his neighbours; but he had resolved,
that should he see any of the negroes he would try to help them to escape;
or if seen by others, so that he could not avoid firing his gun,
he would take care not to point it at any of the slaves;
though he himself very narrowly escaped being killed by one of these a few weeks since.
He was on the outskirts of his plantation; a negro,
probably thinking that he intended to catch him,
fired at him and slightly wounded his breast.
"`But,`" said he, "`I pitied him; for he had a bad master,
who had driven him to acts of desperation, and it is the case with many others.`"
His own slaves behaved well, and he was endeavouring to treat them well;
"`Slavery,`" he added, "`is a dreadful scourge to the land.`"
I had a painful night, and dreaded to hear the result of the expedition.
But I was much relieved from my anxiety, when, on his return in the morning,
W+++.+++ T. Norton told me they had not found a single negro;
they had probably heard of their masters`' intention,
and retired to some other hiding-place; he was himself very glad it had been so.

We left this hospitable family, and came towards evening to the plantation of S. Smith,
who at once gave us a most cordial reception.
"`Come in, come into my house,`" said he, "`some formerly entertained angels unawares,
and perhaps you also bring with you one of the Lord`'s blessings.`"
He lost his wife eighteen months since.
She was a pious woman.
He greatly feels his bereavement.
He has two grown up daughters.
They would incline, he said,
to follow the example of their youthful neighbours in their dress and manner of life;
but,
as he believes this is not consistent with the simplicity
that the Christian religion requires,
he cannot consent, and they, as dutiful daughters,
submit cheerfully to their father`'s wishes.
They belong to the Baptists, but are not sectarians.
Many of his slaves have joined the Baptists also.
They meet together regularly, morning and evening, to have family worship.
At our request he very readily collected all those on his plantation,
with whom I had a meeting.
He is one who would rejoice did the laws of the land
allow of their emancipating their slaves.

The following day we came to Beaufort, a nice village.
Joseph and Mary Anna Smith received us with open hearts.
She is a sister of the widow Grimke of Charleston.
They belong to the Episcopalians,
but it may rather be said that they are members of the Catholic and Apostolic Church.
They are well acquainted with the sensible influences of the Spirit of Truth,
and it is their daily engagement to sit in silence together, to wait upon the Lord.
They know that the Christian communion is not any outward form or shadow, but in Christ,
who is himself the bread of life.
My soul has been refreshed and comforted by being with them.
The Baptists in this place are the most numerous, and their meetinghouse is the largest.
The members of other religious denominations with all readiness
attended a meeting appointed there at my request.
We had a serious company.
The word preached seemed to have an entrance into their hearts.
I had not for a length of time felt my soul so much at liberty, as I did there.
Surely the Lord has a people here that are precious in his sight.

The next morning, after a solemn opportunity with Joseph Smith and family,
we came through a low swampy country, where a great quantity of rice is cultivated.
We were pleased to see the slaves well clad, and looking so well.
But this is not the case everywhere.
The masters of some told us how greatly they reprobate the treatment of many slaveholders.
These bad masters are, they say, held in contempt by them.
So far it is a good step,
but may they entirely wash their hands in innocency from the gain of oppression!
When I plead the cause of the slaves with some of these, who are themselves kind masters,
and direct their consideration to what may become
the condition of the slaves after their death,
when the estates may be divided, and parents and children, husbands and wives,
be sold and far separated, and perhaps fall into the hands of evil masters,
they appear to feel deeply, and deplore the curse that is entailed upon them.

Now we came to Charleston, where are a few members of our Society, and some professors.
I had several meetings with them, and others also, more public.
One of these was in the meetinghouse of the Methodists.
It was a good one.
Here we again met with their Bishop, whom we saw at Augusta.
He is still in hopes that the time is near,
when the foul stain of slavery will be removed from their church.
I found also much openness among the other religious denominations,
the Episcopalians especially, and I had some religious service in families,
as well as in public.
It is cause for deep and heartfelt gratitude,
that there are those whose hearts are prepared to receive, or at least to hear,
the testimony of Truth; but there is also great darkness in this city,
as is the case in all places where slavery prevails.
Vice and immorality abound among the mass of the people.
I met at the widow Grimke`'s with a number of piously disposed persons,
with whom we had a solemn season in the Lord`'s presence.
The last meeting I had with those who profess with us was a time of close labour.
If we act as faithful servants of the Lord, we must speak the truth in love,
but with faithfulness.

We left Charleston the 14th, and had a tedious ride to Georgetown.
Though very tired, way opening to have a meeting the evening of our arrival,
I dared not put it by.
My flesh and my heart were ready to fail in the prospect,
but my blessed Master has sent me to preach his Gospel to the people;
my peace and my life are to stand obedient in all things to his divine will.
The meeting was held in their largest place of worship, and fully attended.
It was another memorable season.
A fresh evidence that the Lord has in these Southern States,
a seed under his Divine notice.
The visitation of his love, and the power of his Truth,
reached to the tendering of many of their minds.
It is to the operation of this, if they on their part keep faithful to it,
that I look for their emancipation from the bondage of sin and corruption,
and to their being constrained also, by the love and power of God,
to proclaim liberty to their slaves.

Wilmington, North Carolina, 20th. We arrived here early this forenoon.
Though worn down, I could not be easy without an attempt to have a meeting in the place.
I thought it would be small, the Conference of the Methodists,
which was to be held at Fayetteville, having adjourned to this place,
on account of the small-pox appearing there; the meeting, however, was a large one;
many of the Methodist preachers attended it.
The Lord helped his poor servant for the work required.
The qualifications of a minister of Christ were enlarged upon;
and also that form of sound words and of doctrines,
which is to characterize his ministry--not the enticing words of human wisdom.

My health seems to be impaired by exposure in these low, marshy countries;
the water we have to drink is very bad.
From Savannah to this place we have crossed nineteen streams, some pretty wide.
We have often travelled miles together in swampy ground,
where the water came up to the body of the carriage,
and was so black that we could not see the bottom of it.
Several times it was so deep that the carriage floated, and the horses swam.
We could not have turned back had we tried to do so,
the way open between the trees being too narrow to allow it.
We were also in considerable danger from the alligators, which are numerous.
They sometimes seize upon the horses, as they pass such places.
But the Lord has upheld us to this day, holy and reverend is his name!
We heard that very lately a horse and his rider were destroyed by these animals.

Newberne, Third month 1st. After leaving Wilmington, we met with considerable difficulty.
The rain being incessant rendered travelling dangerous and very tedious,
for the waters were high and the road very muddy.
We have been several times obliged to go miles round,
on account of the bridges being carried away.
From Swansborough we went forty miles up the river, where we hoped to find a bridge,
but this also was washed away.
Then, turning another way towards Newport river, we met, accidentally,
at Captain Ward`'s--where we inquired for the road--two nice, civil young men,
who offered to take us in a small boat over a wide river,
to their aunt Ward`'s. The tide was low and the boat could not come near the shore,
but these kind young men took off their nice clothes,
carried us on their shoulders to the boat, and went back for our baggage.
We left our horses and carriage under the care of their friend the Captain.
They then rowed us over the river, which is three miles wide.

We came to Hester,
widow of Joseph Burden`'s. She is a valuable member of our religious Society,
as was also her husband.
They joined it by convincement some years since.
He had many slaves, whom he liberated.
His death is considered a public loss, for he was a man of great benevolence.
She has seven sons and one daughter.
She accompanied us with her boat down the river to Beaufort,
where a few families of Friends reside.
These we visited, and we had also a meeting with the inhabitants of the place,
which they very generally attended.
By water, again, we went up to Core Sound Monthly Meeting.
Only about twenty families of Friends remain in that part of the country,
where formerly they were numerous.
In the year 1800, many removed in a body to the State of Ohio.
Strong inducements for their leaving, were the unhealthiness of the district, and slavery.
The land is low and marshy, much of it has been reclaimed from the sea.
The people, generally, have a very sickly appearance.
I felt tenderly for the few members of our Society who continue in this corner.
Some of them think it is their religious duty to remain,
to protect many of the people of colour,
who formerly belonged to those Friends who have moved away, and who, unprotected by them,
might be reduced again to slavery.
I heard very interesting accounts of the conduct of some of these people,
and of their sobriety and industry.
An aged negro,
who resides near the meetinghouse to which his master belonged
before he removed with his family to the State of Ohio,
has several times repaired the house, saying,
"`My old master or his sons may yet return here,
and I wish them to find their place of worship in good order for them to meet in.`"
Near another forsaken meetinghouse (there are several thus
left by the removal of Friends,) resides an aged black woman,
who used to attend meetings there with the family.
She continues to come to the house twice a week, regularly, on First and Fourth-days,
and sits alone in silence to wait upon and worship that God and
Saviour whom she has been instructed to know and to love.
I felt great interest and satisfaction in my visit there.
We went back to the widow Burden`'s, where,
with her large family and some serious neighbours, we had a solemn religious meeting,
and in Christian affection we separated from one another.

We came that day to Colonel Ward`'s. He stands high in the world,
but the power of truth has brought him low in his own estimation.
In a religious opportunity in his family, the great man was much humbled and tendered.
Also his wife and her aged mother.
He is one of those prepared to use all the influence he has,
to promote the passing of laws for the abolition of slavery in this State.
Others, with himself,
are fully convinced that it is a system totally contrary
to what the precepts of the Gospel of Christ inculcate,
and that wherever the love of the Saviour prevails, slavery must cease.

At Newberne I had a satisfactory meeting.
Since coming to these Southern States I have frequently marvelled,
and my soul has been prostrated before the Lord with gratitude, on meeting,
almost in every place, those who love and fear Him.
These I have found in the various stations of life, and not a few among the poor slaves.
I rejoice greatly that the light of Truth has shined in the hearts of some in high rank,
as I have found at Newberne also.
If they are obedient to it, their influence may, by the Lord`'s blessing,
have a powerful effect upon others.

There is certainly a great alteration for good in these Southern States.
When I visited them twenty-five years ago,
irreligion prevailed to a very lamentable extent.
Cockfighting, horse-racing, drunkenness and fighting, were common.
Very few houses of worship were to be seen;
but now piety and some of its fruits are to be met with.
Slaveholders can bear to be reasoned with on the great evils of slavery;
and they also hear, without marks of displeasure,
the testimony of Truth proclaimed against it, in meetings for worship;
as I have done in this place before a large assembly.
My impression is that the greatest and most important work
that the servant of the Lord can be engaged in,
is to bring men to Christ; there is the sure remedy for every evil,
even for sins of the deepest dye.
The love of Christ, coming to have the ascendency in the heart,
will become like the little stone that Daniel saw in his vision;
it will cover the whole earth; neither slavery, oppression of any kind, nor war,
nor any wicked practices will continue to exist.
I am for encouraging the right efforts of societies
formed for the promotion of the abolition of slavery.
May the Lord bless their efforts!
But, my most cheering hope to see this effected is in the benign
influence of the Spirit and love of the dear Redeemer,
our Lord and Saviour Jesus Christ.

Heavy rains coming on again rendered our travelling difficult and dangerous,
in that low country.
We travelled for hours together in water up to the body of our horses.
We succeeded in reaching Contentnea, which meeting, and the others near it, we attended.
At Tasborough we had a trying meeting,
for vice and immorality prevail there to a lamentable degree.
From there we proceeded towards Halifax, Petersburg, and Richmond,
where we arrived the 15th of Third month.
We had meetings at those several places.
I travelled under great bodily debility and suffering.
The dampness of the country, increased by the rains,
together with the poor kind of food we have had in many places, have greatly affected me;
yet, in meetings I have been strengthened to do the work of the Lord,
as required of a poor unprofitable servant.

We arrived at Baltimore from Richmond on the 20th,
having three meetings only on the way to it.
My dear Master, permitting my bodily weakness to increase,
graciously releases me from much further labour in the Gospel.
Good and merciful is He. Here John Street is going to leave me, to return home.

Though in feebleness, I was strengthened in three meetings in this city,
to labour earnestly and affectionately with Friends.
I very sorrowfully behold the advances that the adversary makes upon many of them.
O! the spirit of infidelity!
It robs the Lord Jesus Christ, if it were possible, of his Divinity;
and actually robs those in whose hearts it prevails,
of that salvation which comes by Him alone.
I leave many in this place with a mournful spirit.

On his return home Stephen Grellet thus closes the account
of his visit to the Southern and Western States.

Burlington, 26th of Third month, 1825.
I was favoured to return to my beloved wife and daughter,
for whom the Lord has very graciously cared, as he has done for me, his poor servant,
also.
Surely, according to his promise, he is to those that trust in him strength in weakness,
riches in poverty, and a very present help in the needful time.
He has been so to me in this journey, as in the preceding ones, wherever he has sent me.
O Lord! who should not fear you?
who should not glorify your name!
My beloved wife joins me in prostration of soul,
in praising and adoring the Lord our Helper and Saviour.

I have travelled in this journey about six thousand miles, and am now favoured,
through adorable mercy, with peacefulness of mind,
earnestly desiring that the residue of my days may be devoted to
the service of my dear Saviour,--not that I have any hope that
any of my works can render me acceptable in his Divine sight;
for I am but an unprofitable servant.
The Lord`'s works alone can praise him.
Of myself I am nothing, neither can I do anything that is good.
My hope for the salvation of my soul is solely in the unmerited mercy of God,
through Jesus Christ.
To him all glory and praise belong, forever and ever.
