== Chapter XLIX.

Religious Visit to Friends in New York Yearly Meeting

A Calm had succeeded the excitement that prevailed during the separation.
In five out of the eight Yearly Meetings of which
the Society in America at that time consisted,
the followers of Elias Hicks had effected a distinct organization.
In New York Yearly Meeting,
the secession had greatly diminished the number of members in the Society;
but among those who remained,
the bonds of Christian fellowship had been strengthened
by the things which they had suffered.
Stephen Grellet had long resided in their midst;
his heart had yearned towards them in Gospel love and Christian sympathy;
the time of holding their Yearly Meeting was approaching,
and he now felt "`impressed with a belief, that it was his religious duty,
to visit his brethren under their sore tribulations.`"
Of this service he gives the following particulars:--

I obtained the concurrence of my friends, in this engagement, and,
accompanied by Henry Warrington, a valuable Elder, I left home the 12th of Fifth month,
1829.
I took some meetings on the way to New York.
I then crossed over to Long Island,
where I had meetings with the small remnants of our Society.
Very little companies are left in those parts, where lately there were many Friends.
The people at large understand the ground of our separation,
and disapprove the anti-Christian doctrines held by the seceders.

I had several public meetings also, particularly in the eastern part of the Island.
They were attended by the serious characters of the various religious denominations.
Some of them were solemn meetings.

I returned to New York to the Yearly Meeting, a time long to be remembered.
Friends were deeply baptized together into suffering;
for in all their particular meetings, they have shared the same bitter cup.
Yet a song of gratitude and praise is raised to the Lord, who, by his power and mercy,
has preserved among them a remnant, to whom his adorable name is precious,
and whose hearts are opened by his Spirit, to feel more, and understand better,
what is the greatness of the love of God in Christ,
so that the world through faith in him might be saved.
Many are bowed in reverence while contemplating the depth of the
mystery of reconciliation between an offended God and sinful man.
This sore trial in our Society, which, through a spirit of unbelief,
has plunged many into gross darkness,
has tended to bring others to an increase of faith in, and a saving knowledge of God,
and of our Lord Jesus Christ.
There is also a perceptible growth in some of the dear young people,
who are not ashamed to acknowledge a crucified Saviour and risen Lord,
as the sole ground of their hope of redemption and everlasting salvation.

Nine Partners, Sixth month, 21st. We left New York three weeks since,
and had one or two meetings every day.
Some of these are now much reduced.
The separatists have very generally taken possession of the meetinghouses.
In most places, Friends have already built new ones.
Most of these meetings were held under much solemnity.
The Lord has chastened this people very sore, but he has not delivered them over to death.
His Divine presence, in which there is life, has been with us from place to place.
Blessed and adored be his name!

Farmington, Seventh month,
24th. I have attended all the meetings (except one)
composing the several Quarterly Meetings,
on both sides of the Hudson River, as far as this place.
Having mostly two meetings each day enables us to make rapid progress.
The days also being long, we can travel early in the morning, or late in the evening,
and thus accomplish much more than could be done in short days.
The adversary has caused a great scattering.
A valuable body is nevertheless preserved.
Surely our strength consists not in numbers.

Buffalo, Eighth month, 11th. I have now attended the meetings of Friends generally,
on my way as far as this place,
and had several also with those not members of our Society, where Friends do not reside.
The Gospel had mostly free course among them.
In the course of these two months past,
we have travelled about one thousand five hundred miles,
and been at seventy-four meetings.

Having crossed over from Buffalo into Canada, Stephen Grellet continues:

York (now Toronto), Eighth month, 24th. We went up as far as Falmouth and London,
and had meetings in all places where Friends have formed settlements,
and in other places also among the inhabitants; one of these, held among the Menonists,
was very satisfactory.
Anti-Christian notions have found an entrance also in these parts of the British dominions;
comparatively few, however, have embraced them,
but wherever they are admitted they bring forth the same evil fruits.

This country has much improved since I was in these parts;
many of the roads however are yet in a bad state; dense forests, deer,
wolves and bears still abound.
This city has considerably increased.
I had last evening a large, satisfactory meeting among the people.

We came to Yonge-Street and had several meetings in that neighbourhood,
and then attended the Half-year`'s Meeting in that place.
There was a large concourse of people, even from distant parts.
Very earnest was my cry unto the Lord that he would undertake for us that nothing
might take place to wound his blessed cause of righteousness and truth.
During the meeting for worship which preceded that for business,
several of the separatists made long speeches;
they were more guarded than is often the case,
in their language against the Scriptures and our blessed Lord and Saviour Jesus Christ.
I am thankful that though many of the people gave some evidence
of their disapprobation of the doctrine held forth,
yet they kept pretty quiet.
I felt it my religious duty, when a short time of silence gave me an opportunity,
briefly to state what Christianity is, and what it would lead to;
it changes the whole man.
"`If any man be in Christ he is a new creature, old things are passed away,
behold all things are become new, and all things are of God,
who has reconciled us to himself by Jesus Christ;
and has given to us the ministry of reconciliation, to wit,
that God was in Christ reconciling the world unto himself,
not imputing their trespasses unto them;
and has committed unto us the word of reconciliation.`"
After entering on these all-important and solemn subjects,
I proceeded to state what kind of doctrine ought to be preached
by a minister of the Gospel of Jesus Christ,
unto whom the word of reconciliation is committed, as the Apostle goes on to say,
"`Now then we are ambassadors for Christ, as though God did beseech you by us;
we pray you in Christ`'s stead, be reconciled to God.`"
I entreated, most fervently,
all present not to reject such great salvation as was offered to
all through the tender mercies of God and the love of the Redeemer.
Soon after this the meeting concluded,
and Friends proceeded to the business of the meeting under great weight and solemnity.
A meeting for Divine worship was held afterwards, and a great crowd attended it;
for Christian professors of various denominations felt much for Friends on the occasion;
they consider that the doctrines promulgated by the
separatists are attacks upon vital Christianity,
and many of them appear to feel it deeply,
and unite in prayer unto the Lord that he would restrain that spirit.
We had a solemn meeting; many of the members of our Society,
who had come from their distant homes to attend the Half-year`'s Meeting,
retired with hearts settled in the faith of the Lord Jesus.
Blessed and holy is his name, who has magnified his love, mercy, and power,
during these days, in a memorable manner.

I went back to York, and paid a visit to the Governor,
who is a relative of Sir Thomas Maitland,
who showed me so much civility when I was at Corfu.
I had a full opportunity with him respecting the militia laws in Canada.
The Governor readily promised to have relief given to Friends,
lie made particular inquiries into various branches of our Christian testimonies,
and kindly accepted some books, treating upon these subjects.
He also appeared deeply to regret the separation in our Society,
and highly deprecates the views of the seceders,
as well as those of David Wilson and his followers.

We attended all the meetings between York-town and West Lake.
Their Monthly Meetings were at first disturbed by the separatists,
but the Lord`'s power came over all, and they went out of the house,
leaving Friends peaceably and quietly to attend to
the business of the Church that came before them.
We had some baptizing seasons together;
for during these days of trouble the hearts of many
Friends have become soft before the Lord;
they are engaged in singleness to wait upon him, from whom alone our help comes;
blessed indeed are all those that wait upon him.
Our trials are sanctified to us, when they bring us to a state of dependence on God,
and to look with watchfulness unto prayer to Him from whom alone is our salvation.
I had some large and satisfactory meetings among the people in those parts,
and also at Kingston; some of these were held in their public places of worship.

On our way I passed near the place where John Hancock
and I had a narrow escape of our lives.
The house is now torn down.
Several travellers, who had been known to have come that way or to have lodged there,
had not been seen afterwards.
The house was searched, many stolen articles were discovered,
and it appears that the unhappy victims were murdered and buried in the woods.

We proceeded down the St. Lawrence and visited the
meetings composing the Monthly Meeting of Leeds.
This is the part of the country where twenty-five years ago my horse was poisoned.
The country was then mostly unsettled; now much of it is under fine cultivation.
Friends are pretty numerous, and some of them show forth the fruits of Christian piety.
When I was through that tract of country before, they were very few in number,
but I encouraged them to meet together for Divine worship, and reverently to wait on God,
who would increase their strength every way, and bless them.
He has done so in a conspicuous manner.
I had a large meeting among the inhabitants; they came to it from ten miles round.
It was a solemn and memorable season.
After that meeting, I felt my mind released from further service in this province.
I leave them with a peaceful mind,
and an increase of love and very tender interest for friends in Canada.
There is a small reduction in their numbers, by the secession,
but there is a general increase of vital piety.
They have also among them a promising rising generation.
I entertain the cheering hope that many of these
may become ornaments to their Christian profession.

Leaving Canada they crossed the St. Lawrence to Morris-town in the United States.

We went towards the Black River settlements,
and the other meetings that are to compose a Quarterly Meeting, now establishing.
There is in these parts a lively body of Friends, well disposed.
They have their trials, however; the enemy has found his way among them,
and has successfully sowed his evil seed,
so that in most of their meetings some individuals have joined in the separation.
But these sore trials, under the efficacy of the grace of God,
work together for good to them that love him.
Many Friends appear to have increased in weightiness of spirit.
May they abide therein, watching unto prayer.

We then proceeded by way of Johnstown, Galway, Glens Falls, etc.,
having meetings through that section of the country.
These were rendered very laborious and exercising,
from the circumstance that Elias Hicks was travelling in these parts.
It frequently happened that I had meetings in places
where he had been one or two days before.
The people had been brought under great excitement
by the anti-Christian doctrines he had delivered.
The pious were greatly astonished that one, under the garb and name of a Friend,
should preach such infidelity.
This induced many to flock to the meetings I had, to know if I held similar views.
From place to place I felt called upon to preach Christ
in all his glorious attributes and sacred offices,
and to proclaim that salvation which is through faith in him,
and the meritorious offering of himself as a sacrifice for sin.
Some of these meetings were truly solemn.
Many of the people were tendered;
others with gratitude acknowledged that the doubts respecting the truths of the Christian
religion that had been infused into their minds by the subtle reasonings of Elias Hicks,
were removed.

After one of these meetings, a man, bathed in tears, came to me,
and stated how sorely he had been tried by this spirit of infidelity;
that it had destroyed peace and harmony in his family,
where heretofore a most sweet union prevailed.
His wife and daughter had embraced those impious principles;
and their conduct had totally changed.
His endeavours to reclaim them only tended to alienate them more and more,
till the anguish of his mind became indescribable.
One evening, after pouring out his soul unto God, with many tears,
his faith revived in His all-sufficiency to remove mountains, and to change the heart.
He felt engaged to go to his wife, and taking her by the hand,
he prayed fervently to the Lord on her behalf and that of his daughter.
After that he felt his mind much relieved.
He could quietly wait and see what He on whom he had cast his burden would do.
He said nothing more to his wife on the subject.
A few days after she came to him, her spirit being greatly contrited,
and told him that the Lord had opened her eyes and softened her stony heart.
She now saw the darkness and the wildness of the notions she had entertained;
how it had estranged her from him, her beloved husband, and from everything that is good,
but especially, from the Lord Jesus, in whom, in her darkness,
she could see no beauty or comeliness.
A few days after, the daughter also saw the error of her ways,
and came to bow down before that very Saviour, whom she had lately despised and rejected.
"`Now,`" added the man, "`I am prepared very tenderly to feel for your Friends,
under the trial that has come over them,
by the influence of the spirit of antichrist and his emissaries;
but let them be engaged with faith and fervency of soul to look to the Lord,
who is able to bring deliverance to them.`"
This is a word of counsel in season; I wish all could hear it and attend to it.

We left Glens Falls the 10th of Tenth month and travelled towards the State of Vermont,
by way of Fort Ann, Vergennes, Ferrisburg, etc.;
from there we crossed Lake Champlain and came to Peru and Long Isle,
and had several meetings in that part of the State of New York;
going back into Vermont I had two meetings almost every day with Friends,
and in some places where no Friends reside, till I came to Rutland.
Some of the ground being mountainous and rough rendered the bodily exertion considerable,
but my good and blessed Master strengthened me for the daily work,
and upheld my spirit also under some heavy trials.
Several times we came close upon the steps of Elias Hicks,
and were twice at the same place though not at the same meetinghouse.
I was often comforted among some who retain their love for Christ,
and their integrity in the Truth;
many among these are mourners and heavy-hearted because
of the desolation that the enemy has made.

We returned into New York State by way of Lincoln and Danby,
and went through the meetings comprising Easton Quarter;
mourning and lamentation were my daily bread.
I did not mourn alone however; they have a small number among them,
like the two or three berries that are left after the vintage;
I had great satisfaction in visiting them.
Our gracious Lord is the God of all comfort, "`who comforts us in all our tribulations,
that we may be able to comfort them which are in any trouble,
by the comfort wherewith we ourselves are comforted of God; for,
as the sufferings of Christ abound in us, so our consolations also abound by Christ.`"
The lowly Christian traveller, therefore, has seasons when he may rejoice in the Lord;
for his sorrow is changed into joy;
with wonder he beholds the excellency of that Almighty power that can cause all things,
even the most bitter, to work together for his present and everlasting good.

We now came into the compass of Stanford and Nine Partners Quarterly Meeting,
and attended the meetings composing them; many of these were solemn seasons;
I also met with tender spirits among the young people;
some of them at first went among the separatists; but like the noble Bereans,
led further to search the Scriptures for themselves,
they were soon brought to such clear and strong conviction
of the Truth that Jesus is the Christ and the only Saviour,
that they have returned within the pale of our religious Society.

Eleventh month, 6th. We crossed the Hudson River and came into Cornwall Quarter.
Many of the separatists attended almost all the meetings I had there.
The exercise thus brought on my mind,
for a season diverted my attention from the members of our
Society whom it was my particular concern to visit.
But I found it safest, with much simplicity, to attend to the guidance of the Holy Spirit.
My heart was clothed with much Gospel love, and I fervently laboured with them,
considering that it might be of the Lord`'s doing,
that they had placed themselves in the way of hearing plain Gospel truths proclaimed.
After I had thus cleared my mind, the way was open towards Friends.
Some of these meetings were baptizing seasons.
May the Lord bless the work of his own hands,
to the everlasting praise of his adorable name, whose alone is the work,
and to whom all glory belongs.

I returned home by way of New York, the latter end of the Eleventh month,
having been upwards of seven months absent.
The nature of my exercises during this journey,
as well as throughout the various sections of our Society in these States,
in the course of some preceding years, has been very trying.
Bitterly have I lamented the devastation made in our ranks.
But my faith has never been stronger in the Lord;
being persuaded that by the power of his might,
he will finally subdue all things to himself.
The wrath of man shall praise him;
and to him every knee shall bow and every tongue shall confess, yea, even the rebellious,
that He alone is Lord of lords, and King of kings.
He is worthy of all honour and praise,--amen.

After his return from this visit of Christian love
and sympathy to his brethren in New York Yearly Meeting,
Stephen Grellet was permitted to enjoy a time of
peaceful repose in the bosom of his own little family.
His Christian interest and solicitude were, however,
kept alive to what was passing both in and out of the Society--at home and abroad.
A letter to a beloved friend in England contains some useful hints.

To A. A.

Burlington, 2nd month, 27th, 1830.

The state of our country is such that many of the valuable benevolent
societies you have in your land would not answer among us;
but yet there is room for doing much more than is done,
which would be beneficial both to those engaged in it,
and those towards whom their labours would be directed.
Even in our own religious Society there is a wide field open to bring our families,
and our young people at large,
better acquainted with the nature of our Christian profession.
I believe that ignorance of it is a fruitful cause
of the lamentable defection from our principles,
and the strength that the spirit of unbelief and infidelity has obtained.

Towards the conclusion of 1830, he makes the following memorandum.

During the course of this year I have been mostly at home,
except attending meetings here and in the surrounding neighbourhood,
and several other Yearly Meetings besides my own.
The disturbances caused by the late secession have very much subsided; nevertheless,
I have felt tenderly for Friends, who, in some places,
are left in a very feeble condition.
This is particularly felt in their Meetings for Discipline.
I see the great danger to which individuals of small religious experience,
though otherwise well disposed, are liable, when, in their zeal to become active,
they engage in matters too high for them and beyond their growth in the Truth;
they may thereby come to the loss of the little they had attained, wound their own souls,
and hurt the cause they were prompted, by their imprudent zeal, to attempt to promote.
My concern for some of these has at times been great; and I fear that, from this cause,
other trials may arise in our Society.
