== Chapter L.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Voyage to Liverpool
* Various Religious Engagements in England
* The Yearly Meeting in London
* Preparations for the Continent

It was now nearly eleven years since Stephen Grellet`'s
return from his third visit to Europe.
Much of that time had been spent in various religious
engagements in his own Christian community,
and among others, in the United States and Canada.
He had travelled extensively also in some parts of
America where Friends have no settled meetings.
The last few years of his life had been peculiarly marked
by circumstances and events which deeply afflicted his soul,
in sympathy with a suffering church.
But none of these things had moved him.
As he had partaken largely of the afflictions of the Gospel,
so his consolations also had often abounded by Christ.
Nor did he now count his life dear unto himself,
so that he might finish his course with joy,
and the ministry which he had received of the Lord Jesus to testify
the Gospel of the grace of God once more in distant nations.

His mind had for some time been gradually preparing
for a "`fourth missionary journey`" in Europe,
and in reference to this he writes:

[.embedded-content-document]
--

Twelfth month, 1830.
Amidst my concern and soul`'s travail for my beloved friends in this land,
I have very deeply felt for some of the European nations,
particularly some of those that I have not yet visited, to whom, and especially to Spain,
it seems as if I owed a great debt;
my life and my all must therefore be an offering bound with cords to the Lord`'s altar;
may these cords of love become stronger and stronger.

I feel also that I have a further debt of Gospel
love towards my friends in England and Ireland.
They have, of late especially, been very forcibly before me,
with the conviction sealed upon my mind that I must
go and mingle with them in their trials,
and feel for and strengthen them in the Lord.
I do not apprehend that they are to be tried by the spirit of infidelity
that has so extensively spread within our borders in this land,
but the adversary has many devices;
watchfulness unto prayer that we enter not into temptation is a sure retreat;
surely this must be the prayer of faith in the Lord Jesus,
the Saviour and deliverer from all the works and devices of the devil,
and of our own evil hearts also.

--

A few months later active steps were taken to prepare for
carrying out what he believed to be his religious duty,
and he remarks:

[.embedded-content-document]
--

Third month, 1831.
My religious concern to cross once more the seas and to visit Friends in England,
and other nations on the Continent of Europe, in the love of the Gospel of Christ,
my Lord and Saviour, having ripened to clearness,
with the evidence that now is the time for me to make the requisite
preparation for engaging in so solemn and important a work,
I have set my small affairs in order,
and obtained the certificates of the Christian sympathy and unity
of my friends of the Monthly and Quarterly Meetings of Burlington,
of which I am a member.
My beloved wife on this occasion, as on all preceding ones,
which have not been few since we became united together
by the endearing tie of the marriage covenant,
freely and with Christian cheerfulness resigns me to the Lord`'s service.
She is uniformly a great encourager to me to act
the part of a faithful servant of the best of Masters;
her soul travails with mine in such a manner that she had been deeply sensible
of the nature of the service that the Great Master called me to,
before I had disclosed to her or to any man the secret exercises of my heart.
We have several times parted with the apparent prospect
of never seeing each other again in this state of mutability,
but the Lord, in whose hands is our life, has brought us together again.
He may still do so if it be his good pleasure.
Into his hands, and to his sovereign will and disposal,
we commit ourselves and our beloved daughter--our only child.

Friends, at our Yearly Meeting in Philadelphia,
entered feelingly into sympathy with me under the weighty and extensive prospect of
service in the love of the Gospel of Christ in several of the nations of Europe,
and gave me their certificate of unity,
recommending me to the Christian notice of all those
among whom the Lord may be pleased to direct my steps.

--

After the Yearly Meeting, Stephen Grellet returned home for a short time;
but the hour of parting soon arrived.
On the 2nd of Sixth month, 1831,
he embarked at Philadelphia in the packet ship Algonquin, Captain West, for Liverpool.

[.embedded-content-document]
--

My beloved wife and daughter accompanied me to Philadelphia.
My dear child deeply felt the approaching hour of separation;
but she knows that she has an everlasting and almighty Father to lean upon,
who will ever be near to support, comfort, care for and bless her.
To his Divine keeping and protection I left my beloved wife and her, and came on board.

Both the cabin and steerage passengers regularly
meet together every First-day in the cabin,
when a meeting for worship is held,
unless the roughness of the weather prevents our assembling.
The captain very kindly makes way also for as many of the sailors
as can be spared from the ship`'s duty to meet with us.
Some of these meetings have been owned by the Lord`'s presence,
and were seasons of comfort and encouragement.
It is also our practice to read a portion of the
Scriptures after breakfast and in the evening,
when the cabin passengers very generally attend, and the captain is very seldom absent.

This has been the most comfortable sea-voyage that I have yet made;
the accommodations are very good.
The conduct of the seamen gives me great satisfaction;
I do not know that I have heard from anything of them the utterance of profane language,
and my fellow-passengers are respectful.
Our meetings also are attended with weight and seriousness,
and this appears to increase with some of our company
as we draw near the end of our voyage.
The steerage passengers and the seamen appear also to be grateful
for the repeated opportunities I have taken of reading the Bible,
or some useful and interesting religious tracts to them.

--

[.offset]
On his arrival at Liverpool, after a passage of twenty-eight days, he writes:

[.embedded-content-document]
--

Liverpool, Sixth month, 30th, 1831.
We landed here this morning.
My long tried and dear friend Isaac Hadwen,
again gave me a hearty welcome to his hospitable roof.
This being their week-day meeting, I attended it,
and was favoured by the blessed Master to have access to his Divine presence,
and to participate with many dear friends in the communion and fellowship of the Spirit,
and to worship at the sacred footstool.
Under a grateful sense, also, of the Lord`'s goodness and mercy,
who has been with me and preserved me during the voyage, fulfilling his gracious promise,
"`My presence shall go with you,`" thanksgiving and praise, prayers and intercessions,
were offered to him on bended knees, and with a reverently prostrated spirit.

Seventh month, 6th. My mind has been drawn particularly towards Friends under affliction,
by sickness or otherwise.
I have daily visited six or eight of these in their families,
and have much peace in the engagement.
It is the Christian`'s privilege to have a heart prepared to weep with them that weep,
and at seasons, to rejoice together in the Lord.
I also had meetings with the inhabitants, and others with Friends, to satisfaction;
but I had close labour in some of them.

--

[.offset]
From Liverpool he proceeded to the South, and was engaged in various religious services.

[.embedded-content-document]
--

Accompanied by Thomas Thompson, I left Liverpool for London the 7th inst.,
and was at Birmingham and Coventry meetings on the way.
I have seldom had a more lively and solemn sense of the
engagement of purified spirits in heavenly places,
than I had at the last meeting.
They worship before the throne of God,
joining with angels and archangels in singing the song of Moses and of the Lamb.
May I so keep under the guidance of the Holy Spirit,
and under the baptizing and purifying influences thereof,
that at the end of my earthly race, I may, through redeeming love and mercy,
be admitted into that blessed and glorious company,
and join them in the endless song of glory and praise
to the Lord God Almighty and to the Lamb,
my Saviour and Redeemer.
Earnest were my prayers, that my beloved wife and daughter,
from whom I am now separated for the service of the Lord in his militant church,
may he admitted also with me into those mansions of everlasting felicity.

The coaches travel with such rapidity, that we reached Stoke Newington the next evening.
My beloved friend William Allen, and his valuable wife, met me at Islington,
and took me to their house.
The solemnity on our first meeting was attended with such a humbling and
grateful sense of the Lord`'s goodness in bringing us together again,
that for a length of time, no words gave utterance to the feelings of our hearts.
After having thus continued in silence,
acknowledgments were made on bended knees to the Lord`'s mercy.
My secret prayers were that, if consistent with his good pleasure,
my beloved Allen may again share in a portion of the labours in the Gospel,
to which I am called in these nations.

First-day.
I attended the meeting of Gracechurch Street in the forenoon,
and that of Stoke Newington in the evening.
I met many of my beloved friends from other meetings,
with whom it was grateful to feel that the bonds of Gospel love which united us heretofore,
continue to be strong, by the efficacy of the Lord`'s power.
Among other friends whom I have met here, is James Backhouse from York,
who ia liberated for a very arduous and extensive engagement in the work of the Lord,
in the South Australian Colonies, the Mauritius and South Africa,
and he is here preparing for that service.

18th. Since my arrival here, accompanied by my beloved William Allen,
I have visited the meetings in and about London.
I rejoice in beholding a growth in the Truth manifested
by several beloved young Friends of both sexes,
who give evidence,
by submission to the yoke of Christ and walking in the path of self-denial,
that they are sincere in their desires to be his disciples.
Several of them have a gift in the ministry of the Gospel committed to them,
which they occupy in watchfulness and fear.
I have a good hope of them.

Various religious services pressing on my mind,
detained me in and about London till the 13th of Eighth month, when,
accompanied by William Allen, I went into the counties of Kent, Surrey, Sussex,
Hampshire, etc., having many public meetings, besides attending the meetings of Friends.
Woe were a short time at Lindfield,
where William Allen has his valuable establishment called Colonies at Home.
Many poor people reap the fruit of his benevolent exertions and liberality.
The cottagers he has settled there live very comfortably
on the small allotments of ground attached to each dwelling.
They were exceedingly poor before, and had to receive a weekly allowance from the parish;
now they are surrounded by many comforts, and attend to the education of their children,
which heretofore was totally neglected.
Dear William has besides, at this establishment, an Infant School,
and another school for boys and girls.
Manual labour is combined with school learning and religious instruction.
Some of the boys work on the land; others weave.
They have also a printing press, where many books are neatly printed.
The girls are occupied in various employments suitable for them.
These establishments are intended to show that while
land-owners give comfortable homes to the poor,
raise them from their abject condition,
and relieve the parish from the charge of their support,
they may themselves be benefited, and receive good interest for their money.
I had some very interesting religious opportunities and meetings among these cottagers,
and in their schools.

Ninth month, 24th. Having visited all the meetings in the counties west of`' London,
as far as Devonshire and Somerset, we returned to London.
Some of the public meetings, particularly at Hastings, Brighton, Chichester, Portsmouth,
Portsea, Poole, etc., were largely attended, and owned by the Great Master.
Dear Allen had very good service.
We had mostly two meetings a day.
Those in the evenings were generally of a public character.

--

After attending the Quarterly Meeting in London,
he went into some of the Eastern Counties, accompanied by George Stacey.

[.embedded-content-document]
--

We went through the counties of Essex, Suffolk and Norfolk,
and visited all the meetings of Friends.
At Maldon I received a pleasant visit from Robert Walker,
one of those collegians at Oxford, who, when I was there eighteen years since,
was brought into a very tender state of mind.
Hearing I was in the neighbourhood, he came ten miles to see me.
He continues in the same lowly spirit.
He much regretted that I could not spare time to visit his family at his own habitation.
He gave me the cheering account that several other young men,
who were at that meeting at Oxford, have maintained their integrity in the Truth.
May they so keep under the guidance of the Lord`'s Spirit,
as to bring forth fruits of righteousness and holiness.

On my way to Norwich, I visited a woman Friend, aged ninety-three years.
It was delightful to be in her company;
she seems full of peace and joy in the Holy Spirit, and of love to God and man.
Her understanding is clear, and she can recollect many incidents attending her life,
from five years of age to the present time.
She has had heavy afflictions.
She said that in contemplating the past and the present, and anticipating futurity,
her mind is so wrapped up in the love of the dear Redeemer,
that nothing but gratitude and praise attend her.
Is not this having already in possession the joys of God`'s salvation?

At a meeting I had at Saffron Walden,
my mind was introduced into much distress on account of the evils of infidelity,
and I felt it my religious duty to speak on the subject;
I had not proceeded long upon it,
when a young man was brought under such strong convictions, under the Lord`'s power,
that he cried aloud and wept in great distress of mind.
I was obliged to stop speaking for a while,
and then addressed a few words to him to encourage him to be calm,
and to look up to Jesus the Saviour, whom he had rejected and denied,
but whose love is towards sinners; He came not to destroy, but to save;
He had come to show even unto him his salvation.
I revived the case of Saul met with by the Lord on his way to Damascus, and wished,
that after his example, he also might say from his heart, "`Lord,
what wilt you have me to do?`"
The young man became quiet,
and I proceeded to deliver to the meeting the testimony to the Truth required of me.
After meeting I was told that this young man had been a notorious infidel,
and as far as was in his power used his efforts to corrupt many others.
The clergyman of the place had tried repeatedly what reasoning with him would do,
but all was unavailing.
On hearing what occurred at the meeting he remarked, as I am told,
that it must be the Lord`'s Spirit who had done this.

Here I am at Norwich, at my valuable friend,
Jane C. Gurney`'s. I feel much for her in her widowed state; her bereavement,
by the decease of her valuable husband, is great; but her loss is, I believe,
his eternal gain.

--

[.offset]
Proceeding on his journey, he continues:

[.embedded-content-document]
--

My dear friend, Thomas Maw, being now with me, I visited the counties of Cambridge,
Lincoln, etc.
Some of the meetings were seasons of much solemnity,
but at many others I had close exercise and service.

Eleventh month, 12th. I heard at Wisbeach of the decease, in Ireland,
at the house of Mary James Lecky, of my dear friend, Jonathan Taylor, from Ohio.
He was my fellow-passenger from America to Liverpool.
Coming to these nations as a fellow servant and labourer in the Gospel of Christ,
soon after landing he proceeded to Ireland, and after visiting most of the meetings,
and several times saying he could see nothing beyond Kilnock,
he peacefully departed there on the 8th instant.
He was a very devoted servant of the Lord; of a meek and quiet spirit.
I had very sweet fellowship with him.
Thus the Lord has been pleased to cut short the work in righteousness:
while we were on ship-board together he repeatedly said that the
chief service to which he thought he was called was in Ireland.

--

At Wisbeach, Stephen Grellet was joined by John Holmes, a Friend of that Meeting,
and proceeded from there to visit several of the Midland and Northern Counties.

[.embedded-content-document]
--

I had many meetings in the dales of those counties, and among the colliers and miners.
I feel deeply for that class of men; many are their privations and sufferings,
as well as of the poor weavers in the manufacturing districts.
My travelling among the colliers was attended with danger in many places;
for the men had "`turned out,`" as they call it,
refusing to work unless their wages were advanced; and they were under excitement,
increased by the lack of the necessaries of life to support their families;
some of them were driven to acts of desperation,
so as even to attack travellers on the road.
We however passed on unmolested, and had some large meetings in those very districts,
where the people behaved well.
I endeavoured to impress upon them the fear of God and the love of the Saviour,
and the duty of living under the influence of the
peaceable spirit of the Gospel of Christ.

On my way to Sheffield I was accompanied by a dear friend,
who imprudently took off the bridle of my horse as he stood harnessed to the gig;
the horse was so frightened that he darted forward, threw me down,
and both he and the gig passed over me; I received considerable injury on the head,
shoulder, knee, and leg.
As I laid prostrate on the dusty road, the bystanders thought I was killed on the spot,
for I could not move;
but my mind was wrapped up in a grateful sense of
the love of God through Jesus Christ my Saviour.
I felt indeed the strokes of the horse`'s feet and
the wheels of the carriage passing over me,
and was perfectly sensible of what might be the consequence;
but the language was distinctly proclaimed in my soul, "`You shall not die, but live.`"
And then Spain was placed again forcibly before me,
with the conviction that the Lord had a service for me there.
I was assisted to a house near,
and soon after taken to Sheffield to my dear and valued friend, William llargreaves`',
where medical aid was immediately obtained, and every kind attention bestowed.
My beloved friends, Lydia Hargreaves and her brother, nursed me in the most tender manner.

--

[.offset]
The day after the accident, he wrote:

[.embedded-content-document.letter]
--

[.letter-heading]
To John and Mary Hustler.

[.signed-section-context-open]
Sheffield, 17th of 1st mo., 1832.

[.salutation]
My beloved Friends,

I write to save you the feelings of solicitude that might be excited in your very tender,
sympathising hearts, were you to hear through some other channel,
what has happened yesterday, to dear John Adamson and myself.
It might have been very serious, but,
through the merciful kindness of Him who cares for the sparrows,
and watches over his people,
the little we have suffered only tends to excite strong
feelings of gratitude for the great escape with our lives,
and no broken bones.
This sense of gratitude has been such, even from the instant the accident occurred,
that my heart cannot yet get sufficient vent in ascribing
praises and thanks to my blessed Lord.
+++[+++After describing the accident, and safe arrival at W. H.`'s, he proceeds.]
Our very kind friends here do everything that it is possible to devise.
The physician ordered thirteen leeches, which have relieved me,
but bed is the best place for me at present.
I must cease, for I can hardly write more; but before I lay down my pen,
I must ask you to suppress feelings that hearts of near affection for me would prompt,
and to unite with me in ascribing gratitude and praise to our blessed Lord and deliverer.
In this dispensation I do feel nothing but gratitude, and a renewal of faith in Him.

My love to the dear friends of your family, especially to dear Mildred.
Farewell in near affection.

--

[.offset]
On the 25th, Lydia Hargreaves writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Mary Hustler.

How delightful to be able to tell you of the improvement in our beloved
friend,--though I believe he still suffers considerable pain.
I unite with you in fearing that so much writing is not good for him;
but it is impossible to repress the grateful feelings of his kind and affectionate heart,
which, like the fountain of love, seems always open, and always new.
Whatever he suffers, we never hear him complain,
for he always makes the best of everything:
and I never saw the Christian character so strikingly
and so beautifully unfolded and exemplified.
While we deeply regret the cause of detention,
we feel that the days which are so swiftly passing over us are, indeed,
days in which enjoyment inexpressibly sweet, and altogether unmerited,
is continually mingled;
and fervent is the heartfelt desire that profit and
instruction may be individually and lastingly known.

--

[.offset]
The journal continues:

[.embedded-content-document]
--

My detention, though attended with much bodily suffering,
was nevertheless a season of spiritual consolation and enjoyment.
Truly my soul could say, "`God is good to Israel.`"
He was very good and gracious to me,
so that I may gratefully number these days spent on a bed of languishing among
those in which my soul has partaken most largely of the Lord`'s consolations.
William Hargreaves related to me a circumstance,
which strongly evidences that the influences of the
Divine Spirit are not a cunningly devised fable,
nor the work of imagination.
Our dear friend, Hannah Field, from America,
during her late religious visit to this nation, being at Sheffield,
William Hargreaves and Benjamin Colley accompanied her to Barnsley.
After an evening meeting there, urgent business required their return home that night.
H+++.+++ Field, hearing of their intention, endeavoured to dissuade them from going,
and on their pleading the necessity of it, said, "`Well, friends,
if you do it I have a strong apprehension that you may be robbed on the way.
You had better wait till tomorrow morning.`"
But, being two together, and having good horses, they nevertheless concluded on going.
On parting from them she said again, "`I shall be very glad if you escape being robbed.`"
They had gone about half-way to Sheffield, riding near one another,
in earnest conversation on some interesting subject, when, suddenly,
a man sprung from the roadside, to take hold of one of the bridles, while others behind,
also tried to seize the horses, and another man, armed, was drawing near.
The Friends so quickly put their horses at full speed,
that the man who had seized the bridle was thrown on one side,
and those behind let go their hold.
A shrill whistle answered by another right before them, increased their sense of danger,
but they had no other course than to go forward, which they did at full gallop.
The night was dark, and they got home safely.
Two days after, H. Field was at Ackworth school,
when she met with some Friends from Sheffield,
of whom she inquired if W. H. and B. C. had returned home safely from Barnsley.
Being told that they had, she said, "`I am very glad,
for I feared they might be robbed on their way that night.`"

I recovered so rapidly that the 30th of the First month I was able to be dressed,
and to ride to meeting; I had hoped to have sat the meeting silently,
engaged in pouring forth my soul with gratitude before God,
and worshipping his great and adorable name.
But He, whom I desire to serve, and who for the very purpose that I should serve Him,
has again preserved my life, when on the very brink of destruction,
saw fit to introduce me into deep feeling and exercise with
a commission to proclaim the message given me for that congregation.
I did not know that I was able to stand on my feet,
but He who is the God of everlasting strength helped his poor servant.
It was a very solemn season; deep reverence was the clothing of many of our minds.
I forgot that I had any bodily ailment,
and contrary to the apprehension of my friends who thought
that after such exertion I should be quite sick,
I came downstairs in the evening, and,
amidst a numerous company of Friends who had collected
in the large parlour of my dear friend,
William Hargreaves, we had a refreshing religious season together,
and the stream of the Gospel was permitted to flow among us.
My bodily strength felt so much renewed that I saw my way open
to proceed on the embassy for which I have been sent to these nations.
Great is the Lord, and glorious is his holy name!

Accompanied by my kind friends, William Hargreaves and his daughter Lydia,
who has a good gift in the ministry, we left Sheffield the 1st of the Second month, 1832.
Riding in an easy, four-wheeled carriage,
I bore the fatigue of travelling with tolerable ease, as well as the sitting,
and the exercises of several meetings I had on the way to Birmingham.

Here my beloved friend, William Allen, came to join me for awhile.
It was very grateful to have his company at the meetings in Birmingham,
especially one on First-day evening, which was largely attended by the inhabitants.
Dear William had excellent testimonies to bear to the Truth.
We afterwards had several meetings on our way to Bristol,
and at Worcester we met very agreeably with Doctor Thomas,
who had bestowed so much attention on my dear Allen
during the illness he had on the island of Zante.
He gave us the affecting intelligence of the destruction by fire
of the part of Constantinople where we lodged when there;
the whole of Pera was reduced to ashes.
Great devastations have been made in that city since we left it, by the plague,
civil commotions, and fires.
Many, under such awful visitations, look no further than chance, as they call it;
but in the language of the prophet, we rather should conclude,
"`Is there evil in a city and the Lord has not done it?`"
My soul is often bowed very reverently before the Lord,
in desire that the inhabitants of the nations would look
to him under the various scourges whereby they are afflicted.
The cholera at present makes fearful and rapid progress in many places;
great is the mortality caused by it.

We came to Bristol the 10th instant, and continued a few days there,
having several meetings and visiting some families under affliction;
this is a service that I feel often laid upon me;
I believe some of these visits are rendered profitable; they are so to me frequently,
for truly it is better to go to the house of mourning than to that of mirth.

We then had several public meetings, and others among Friends generally,
through Devonshire and Cornwall as far as Falmouth.
Some of these meetings, held among the lead mines, were very interesting.
Vital religion has progressed among many of these people since my first visit to them.
The education of the children has, by the Lord`'s blessing,
contributed to the moral reform of the parents.
Great brokenness of spirit has sometimes appeared to extend over the large company collected.
May the Lord bless his work among that people and everywhere.
The dear Redeemer says, "`My Father works hitherto,
and I work,`" and it is a marvellous work.

--

The desire of his heart respecting a companion on
the Continent appeared likely to be granted;
and a little later he writes:

[.embedded-content-document]
--

My beloved friend, William Allen, left me at Falmouth, the 2nd of Third month,
to return to London,
to make preparation for being in readiness to join me in
my contemplated religious engagements on the Continent,
the weight of which service is now upon him.

There are valuable Friends in Cornwall.
Some among the young people are very hopeful.
A little company at Tavistock has much interested me.
That meeting was established since my last visit to that town.
A young man, educated in the Episcopal church, was from a child seriously inclined,
and sought frequently for places of retirement to put up his prayers to the Lord.
As he grew up his heart became enlarged in the fear and love of God,
so that the pleasures of the world had no attractions for him;
but his delight was to retire into the woods or lonely places to wait upon the Lord.
He knew nothing of Friends, and the manner he had heard them spoken of,
rather prejudiced his mind against them.

A few others joined him in retiring for devotional purposes.
They became acquainted with the Society,
and were fully convinced of the correctness of its Christian principles;
they one after another applied to be received as members,
and finally a meeting was established among them.
There are nearly forty, and a number of others are under convincement.
The meeting we had with them was solemn;
they appeared well acquainted with that unction that the Apostle told
the believers they had received of God and which teaches all things,
so that they had no need that any man should teach them.

The cholera is spreading in various parts of this nation;
the malignity of this disease is particularly manifest in persons of intemperate habits.
It is a pleasing circumstance that, as the disease spreads,
temperance societies increase, and the number of those who join them multiplies daily.

I returned to Bristol by way of Wellington, Exeter, etc.,
and tarried awhile in some of those places as well as at Bristol,
visiting many Friends in their families.
It is an arduous service;
the Lord condescended very graciously to enable me to perform it with peace of mind,
and also, I hope,
to bless the little bread that he gave me to hand forth from house to house.

From Bristol I went through Gloucester and Oxfordshire,
having meetings among Friends and others;
but the effects of the injury I sustained in Yorkshire increased considerably,
so that I was under much suffering, especially in my shoulder and chest,
and it became necessary to lay by for awhile to recruit my health.
Some of my friends thought there was no prospect that I could recover,
the disease having, as it appeared, made considerable progress;
but I so felt the weight of the service the Lord
calls me to perform on the European Continent,
particularly in Spain, that I could not see that the end of my earthly race had yet come.
I felt confident that if I was required to go to those nations my life would be prolonged,
and strength would be given for that work.
Seeing however that I must give up to be nursed,
I thought it best to go to the house of my beloved friend, William Allen,
at Stoke Newington, a distance of upwards of one hundred miles,
which those about me thought I was not able to perform.
The inflammation on my chest was considerable, and I had a high fever;
but the Lord helped me.
My kind friend and his wife met me on the way with their carriage.

I was so well cared for by these dear friends and the medical attendants, but,
especially, by the Physician of value, the Lord, my saving strength and Redeemer,
that I was able to go to Tottenham, the 20th of Fourth month, to my valuable friend,
Mary Stacey`'s.

Soon after coming to Tottenham, I was able to attend meetings again,
which I did diligently, in and about London, as they came in course.
I sat in silence in most of them.
Deep was my soul`'s travail;
but silent exercise and prayer unto God were my proper service.
It is a great favour, in our distress,
to be able to find access to Him who is a God that hears prayer.
Fervent have been my secret intercessions for the people to whom I am united
in Christian fellowship,--for this nation,--for those on the Continent,
that I have visited,--and those to whom the Lord is inclining my
heart to go shortly in the love and service of his glorious Gospel.

My way having opened again for religious service,
I had several public meetings in and about London.
The spreading of the cholera in some parts of this city and neighborhood,
has brought seriousness over many minds,
and thereby the hearts of some are perhaps the more open to receive
the testimony to the Truth given me to bear among them.
O! that the people would learn righteousness under these visitations of affliction!
The mortality in Paris is great.

--

Stephen Grellet now attended the Yearly Meeting in London:
in reference to which he remarks:--

[.embedded-content-document]
--

Sixth month, 2nd. The Yearly Meeting concluded this day.
There was a living travail of spirit prevalent.
The Lord and his Truth were exalted.
The Lord alone can frustrate the designs of Satan.
I rejoice in the belief that many beloved brethren
and sisters are sensible of the danger of his devices,
and that watchfulness unto prayer is the position occupied by many of these.

My dear friend, William Allen, obtained from the Meeting of Ministers and Elders,
their certificate of unity in his religious concern to unite with
me in parts of my contemplated Gospel labours on the Continent,
as his way therein may open.

Sixth month, 28th. After the Yearly Meeting, I went to the Quarterly Meetings of Essex,
Suffolk and Norfolk, and had some large public meetings.
These services lay with weight upon my mind to be discharged,
before I could feel at liberty to proceed for the Continent.

I returned to London in time to attend their Quarterly Meeting,
which was a solemn one,--as was the parting, for a season only, perhaps,
from friends tenderly beloved in the Truth.

--

[.offset]
A few days before his departure for Holland, he writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia Hargreaves.

[.signed-section-context-open]
Stoke Newington, 6th mo. 30th, 1832.

At Norwich I had the pleasure of seeing Jonathan Backhouse.
Four weeks before, he and his wife had been at Burlington, with my dear wife and daughter.
Thus, besides letters, I had tidings from an eye witness.
My daughter was pretty well,
and her beloved mother able to get to meeting,--not
much further than from your house to the gate.

May we not hope that day by day we are drawing nearer to our port,
and that even some of those storms that assail us and sometimes
threaten to overwhelm our very frail bark,
impel us much faster towards the destined haven, than mere sunshine and calm would do?
When under heavy pressure, discouragement may often prevail,
but in drawing near to our Holy Redeemer, these very trials become sanctified to us.
They have been so many a time.

--
