== Chapter LI.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Holland
* The Rhine Country
* Pyrmont
* Minden

Since his landing at Liverpool,
Stephen Grellet had spent a whole year in diligently labouring in the
service of the Gospel among his brethren in religious profession,
and the community at large in England.
He now went forth, for the last time,
as an ambassador for Christ to nations of another language.
His "`Fourth Missionary Journey`" on the Continent of Europe was the most extensive one.
It embraced parts of Holland, some of the minor states of Germany,
the dominions of Prussia, Saxony, Bohemia, Austria and Hungary, Bavaria, Wirtemberg,
Switzerland, Piedmont, France and Spain.
The difficulties of such an undertaking were obvious,
but "`eternal wisdom was his guide,--his help Omnipotence.`"
He had now grown grey in the service of the Lord;
and the richness of his personal experience gave
peculiar interest to this labour of love,
and brightness to this work of faith.
It was like distributing the well ripened fruit of his autumn life.

[.offset]
His records continue the thread of the narrative:

[.embedded-content-document]
--

Seventh month, 4th, 1832.
In company with dear William Allen I left London yesterday, by the steamer Atwood,
and came to Tiengermeten Island in Holland, where, on account of the cholera,
a quarantine has to be performed.
We are much crowded on the vessel, there being many passengers;
but we are under the necessity of remaining on board as
the number of persons on the quarantine ground is such,
that all the buildings there are crowded; they have come from France, England,
and other parts.

8th. Three men on board our vessel were taken with cholera,
and died in the course of twenty-four hours; so that our prospects were gloomy.
The day before these men were taken ill, we had a religious meeting on board the steamer.
I had noticed that several of them took strong drink to excess;
I pleaded earnestly with them on that account,
setting before them the evil of such a practice, rehearsing the Scripture assertion,
that drunkards are excluded from the kingdom of God,
unless they are favoured by his grace to come to repentance and faith in Christ,
and witness amendment of life;
these very men were also among those to whom we gave religious tracts,
and whom we noticed engaged that afternoon in reading them.
May the Lord have favoured them, at the eleventh hour,
availingly to supplicate his holy name!

Dear Allen, at the time of our private devotion, this evening,
opened the Bible on the 91st Psalm.
The Lord permitted it to be a word of encouragement and consolation to us;
through his Divine favour our trust and confidence in him,
the God of our life and of our salvation, have been renewed,
and our faith confirmed in the promise of the blessed Redeemer, "`Lo,
I am with you always, even to the end of the world.`"

9th. As the Atwood was going back to England,
the passengers on her had to come to the quarantine ground on the island.
The only vacant place, in which we could obtain shelter, is a large building like a barn,
used to put merchandise in, which also has to perform quarantine.
The air has free course through every part of the building, even the flooring,
which is elevated about three feet from the ground, and consists of very narrow boards,
about three inches apart from one another.
In a corner of this building, which soon became crowded by our fellow passengers,
we placed our trunks and baggage, on the open floor.
We so contrived it that it might serve us as seats, table, and place to lie down on;
and we felt very contented in the will of God, with our situation.
It being First-day, we held our little meeting,
and our spirits were sweetly refreshed in the Lord`'s presence;
for we were made partakers of his gracious promise
to the two or three that are met in his name.
Our spirits were contrited, and very reverently bowed with gratitude before Him who,
amidst our outward difficulties and gloomy prospects, ministered to us from his presence.
It is well we have provided ourselves with a tea
kettle and some small requirements of that kind,
as on our journey through Russia, Greece, etc., some years since,
for this appears to be the most inconvenient place
that could have been chosen for a quarantine ground,
and the most destitute of accommodation.
This ia however an extraordinary circumstance.
They have never been so crowded before,
and preparations are making to bring in provisions.
We find it necessary to boil the water, and let it settle before we can drink it,
and even then it has a sickly taste.

10th. Several persons who were here before us, have been liberated from the quarantine.
We now occupy the places of some of these,
and have the benefit of a chamber to ourselves, which is a great privilege;
though we are annoyed by swarms of mosquitos and other unpleasant insects,
which prevent us from obtaining much sleep.
There has not been any other case of cholera since we landed,
but we hear that four of the crew of the Atwood were attacked with this fearful disease,
on her return to London.
The origin of the name of this island, Tiengermeten, which signifies ten acres, is,
that formerly this was the whole of the land it contained, but, of latter time,
the washing of the sea has every year added to its size,
so that now it requires three hours for a fast walker to go round it.
The owner, however, continues to pay taxes on ten acres only,
though he has rented to the Government one hundred acres,
on which the quarantine ground and buildings stand, and he has two farms on it beside.

The room joining ours, is occupied by the Baron de Falck and his wife.
He was the Dutch Ambassador in London.
They were returning to Holland by way of France,
hoping that they should have a shorter quarantine to perform, but have been sent here.
We have some religious opportunities with his family, and others,
who sit down with us in our little meetings for Divine worship.
There are here persons of various nations.
It affords us an opportunity to supply them with copies of the Scriptures,
and religious tracts, which the days of leisure they have here give time to peruse.
We are pleased in observing an increase of seriousness in many,
and a disposition to make further inquiries respecting the ground of the hope of salvation.
Our detention on this island is not, we trust, without a service.
May the Lord render it a blessing to those with whom we mingle!

12th. We have letters from London conveying the affecting intelligence
of the decease of that devoted servant of the Lord,
Hannah Kilham, who was on her second religious visit in Africa.
She has spent much time and arduous labour in endeavouring to promote
the religious and moral education of the people in Africa;
her labours were particularly among the Foolahs and the surrounding nations;
she had also established several schools among their children;
fruits to the Lord`'s praise are brought forth by many who by her
instrumentality have come to the knowledge and love of the Saviour.
Now she has ceased from her labours, but her works of love remain to the glory of God!

We were released from our quarantine on the 15th. The preceding evening we had
a satisfactory parting opportunity with the Dutch Ambassador and his family;
a sister of his wife, a pious person, was now present;
she had come on purpose to see her sister; they had not been together for years,
and to have the pleasure to be with her,
she submitted cheerfully to all the privations of this unhealthy island.
We came the same afternoon to Rotterdam; the country is very flat;
we crossed dyke after dyke.
The land is in a high state of cultivation, and has many fruit trees upon it;
the pastures are luxuriant; the cattle beautiful,
being of the species that appear as if they had a white sheet over their backs;
they give abundance of milk; the premises about the farms are neat and clean;
their milk vessels of wood are quite white, and their kettles of brass like shining gold.

We found John S. Mollet, from Amsterdam, who had kindly come to meet us,
and to act as our interpreter.
We are much favoured in this particular, now,
as we were on our preceding visit to the Continent;
to the Lord our bountiful provider is the praise ascribed!
We three sat down together and held our little meeting;
it was a season of lowness and much poverty,
attended also with a feeling of weight on account
of the service that may be required of us.
Our prayers unto the Lord were that he would direct us in the way he would have us to go,
and enable us to perform whatever he may require.
I feel very poor and stripped, but our sufficiency is of God.
It is He who gives to his servants both to will and to do of his good pleasure.
Of this we were made sensible that very evening at
John Lamming`'s. He is a benevolent and pious man,
and has also an interesting family,
who evince that the religious care bestowed on them
by their parents is attended with the Lord`'s blessing.
As we were sitting silently with them,
the clergyman of the English Church and that of the Presbyterian both came in;
we could not flinch from proceeding in the religious opportunity we had with the family;
the clergymen were serious, and we believe it was an evening profitably spent.

16th. Early this morning we made a satisfactory visit to the Baron Makey,
Director of the Post Office; he is a spiritually minded man,
and not only believes in the influences of the Holy Spirit on the heart of man,
but he seeks frequently in places of retirement to have communion with God,
and to participate in the refreshings from his Divine presence;
he believes that the Spirit is one of the blessed gifts of the Redeemer,
the Lord Jesus Christ; therefore the more highly he values the gift,
the more also he loves and reverences the gracious dispenser of it,
for it is the fruit of his love and the purchase
of the atoning sacrifice of himself for us.
We were afterwards with the Baron La Deboar, who is a useful and benevolent man.
The two clergymen we were with yesterday, having heard that we were there,
came to meet us again, bringing with them the clergyman of the Dutch Kirk;
they seem to wish to be in our company, not for disputation,
nor to enter into controversy, but to inquire into some of our Christian principles;
we had an opportunity of setting before them our views of the nature of pure Christianity,
and the qualifications for a minister of Christ.
We forwarded to the quarantine on the little island
a parcel of Bibles and Testaments in several languages,
for the use of those who may yet come there.
We also visited and had religious opportunities in their prison and schools;
in one of these for the poor there are about one thousand children.
We felt much for the people of that city,
but we did not find that which would have warranted us to appoint a meeting there.
The cholera has made its appearance in this neighborhood, particularly about the Hague.
We accept with gratitude our release from going to that place.

We came to Amsterdam on the 18th, and visited the Infant School,
supported out of the interest of the residue of the money proceeding from the share
of John Warder in the prizes made during the war by a vessel in which he was concerned.^
footnote:[Before his removal from England, the late John Warder, of Philadelphia,
had some share in a vessel which, contrary to his earnest expostulation,
was armed by his partners, who were not members of the Society of Friends.
During the war with Holland she captured a Dutch vessel of considerable value.
John Warder`'s share of the prize-money was handed over to him; but,
with noble consistency of character,
in the faithful support of a Christian testimony against all wars and fightings,
he declined to appropriate the sum to his own use.
Great efforts were made to find out the real owners of the property, and,
as far as was practicable, it was restored to them.
But some could never be traced, and, being originally derived from Holland,
it was ultimately thought most in accordance with strict justice,
to appropriate the residue to Dutch purposes.
The result was the establishment and support of the Infant School at Amsterdam alluded to.
It was the first of the kind in Holland,
and now similar institutions are very general in that kingdom.]
They have now upwards of sixty children in that school.
The building purchased for the purpose is a convenient one, and the matron,
under whose especial care it is placed,
appears to act the part of a mother and of a Christian towards those young children.
Our testimony against war is exalted through this act of justice and benevolence.
Many persons come to visit the establishment.

We had several meetings in Friends`' meetinghouse which is a convenient one;
others were held at the house of J. Muller, a pious Menonist, and in some other places.
One of these was attended by many of the principal inhabitants of this city;
as they generally understand French, I spoke in that language.
In the other meetings J. S. Mollet interpreted for dear Allen and myself.
All these meetings were quiet, and some of them solemn.
There are piously-minded persons in this city,
towards whom we felt strong attractions in the love of Christ;
we visited a number of them in their families to our comfort and edification.

J+++.+++ S. Mollet accompanying us, we went to Zwolle.
I was in that place nineteen years ago, when my way was hedged up,
so that I could not have any meeting among the people.
We feel ourselves situated in like manner at present.
There is much bigotry among the Romanists,
and the Protestants are either swallowed up in the
pursuit of the gain and pleasure of the world,
or strongly entrenched in a self-righteous spirit.
I doubt not, however, that the Lord has here a few names, even as in Sardis,
that love and fear him.

On our way to the colony of Fredericksoord, most of the road we travelled,
as far as Meppel and Steenwyk, is similar to that from Amsterdam to Zwolle, a smooth,
beautiful pavement made of hard bricks.
It is like riding over the floor of a chamber.
The sides of the road also are planted with fine shady trees.
At regular distances there are clusters of them,
and seats for foot travellers to rest themselves, and fountains of good water.
From Meppel to Steenwyk we passed through a village, three miles in length.
The houses, or rather comfortless cabins,
are about three hundred yards apart from each other, and are erected on a low,
flat morass.
They have no chimney, and the smoke of the turf which they burn escapes through, the door.
They appear to have very little land cultivated about them, or indeed fit for it;
but the people derive their sustenance from the cattle that feed on these marshes,
and the produce of bees, of which they have a considerable number.
Every family is provided with boats, to which they are frequently obliged to resort,
by the rising of the water that surrounds them.

--

Of the interesting establishments for the poor,
commenced under the superintendence of General van der Bosch,
Stephen Grellet gives the following account.--

[.embedded-content-document]
--

Fredericksoord, which is colony number one, is the largest and the first that was formed.
Number two, called Williamsoord, is very near it.
Also number three, which as yet is but small.
The colonists were formerly paupers, and led a miserable life, in abject poverty.
The land, on which they are now settled was, a few years since, a barren heath.
They were at first supplied with tools to work with, food, etc.
Now, that tract of country is covered with neat, comfortable cottages,
to each of which is attached a piece of ground of twelve or fifteen acres,
sufficient to support a family.
The ground thus reclaimed by industry, resembles a cultivated garden or fertile field.
Besides numerous cottages, there are workshops, storehouses, etc.
These three colonies contain together several thousand persons.
A number of poor orphans, of a suitable age, are placed as apprentices to farmers,
or to learn various mechanical arts.
We had some religious opportunities among them,
and had satisfaction in visiting many of these people in their families.
A small part of the produce of their industry is yearly applied
to refund the advance of money made them to build their houses,
or to purchase provisions, till they could raise them themselves.
They are now generally surrounded with many comforts, have good clothes,
and on First-days, both the parents and children are well dressed.

From these colonies, we went to Ommerschans.
This establishment has on it a poorhouse and a workhouse.
The country through which we travelled to it,
much resembles the very poor pine and sandy land
in the western parts of the State of New Jersey,
United States.
This colony was formed by a benevolent society at the Hague,
which was joined by similar philanthropic persons at Amsterdam,
and was patronized by the Government.
They purchased a tract of land of this poor soil.
A canal which passes through it has been connected with the Zuider Zee.
This gives them great facility for bringing manure from the cities,
and for having their produce, or manufactured articles, conveyed to market.
A large portion of the land is now rendered very productive.
Part of this establishment is for those who, some years past,
were inmates of poor-houses, vagrants, etc., whose labour was chiefly to rasp logwood.
They were then in dirty crowded places; now, they have good accommodation.
Besides the cultivation of the land, they have several kinds of manufactories.
The other establishment is composed of such as formerly occupied penitentiaries or prisons.
They are engaged pretty much in the same kind of labour as the others,
but do not enjoy so much liberty, and are under the strict oversight of soldiers.
They have many children among them,
the offspring of these people or of others of the same character,
who receive good schooling,
and respecting whom some good hope might be entertained were they
kept separate from those that have grown up in vice.
These interesting establishments support themselves, and provide a fund also,
to be distributed among the prisoners, when their time of confinement expires.
As in each, both Papists and Protestants are confined,
they have the privilege of having their meetings for worship, separate.
We had several meetings among them, each denomination by themselves.
We had also religious opportunities in the schools, and in their hospital,
where our hearts were sickened at the sight of the miserable and suffering condition
into which vice and depravity have reduced many of our poor fellow beings;
if they would learn by the things that they suffer, it would be a delightful prospect,
and greatly mitigate our distress and solicitude on their account.

We returned to Zwolle, and,
no way opening for the relief of our minds towards the people there,
we prepared to go towards Dusseldorf.
However, the evening before oar departure,
about one hundred and fifty persons collected at our inn; they behaved with propriety,
but there was not much openness for Gospel labour among them.
We left them with a heavy heart.
We travelled through several fortified places, which are numerous in Holland;
among others, we went through Deventer.
Nineteen years ago I had a narrow escape from being shut up in some of these
places by a part of the French army that occupied those fortresses for some time,
after the Allies had entered France.
We tarried a little while at Arnheim, and entered Prussia at Elten.
As we had left Amsterdam previous to any appearance of the cholera there,
we were allowed to enter that kingdom without performing quarantine on the frontiers.

At Dusseldorf there are some valuable and benevolent persons.
But since we left Zwolle our spirits have continued day by day to be greatly depressed;
darkness and ignorance prevail to a high degree among
the Roman Catholics where we have travelled.
I felt anxious also on my own account,
how far my health would allow me to prosecute our journey;
but since coming to Elberfeld we have been comforted and cheered various ways;
letters from England and America do not represent the spread of the cholera,
and the mortality thereby, such as to warrant the statements that we have seen.
Here also we met with a number of those pious individuals with whom I mingled years ago,
at a time when they were under severe trials,
and when the Lord condescended to cause the consolations of his Gospel
to flow among them in such a peculiar manner that the remembrance of it
continues to be fresh with many of the people,
both of Elberfeld and Barmen, which are only two and a half miles apart.

Seventh month, 29th. Since I was here a meeting has been established at Barmen,
composed of persons who have become convinced of our religious principles;
some of these are in a tender state of mind.
This morning we had a meeting with them;
there was a solemn covering over us during the time we spent in silence together,
attended with an evidence, as we thought, that this people are owned of the Lord,
and are acquainted with the teachings of his Spirit,
through the influences of which they are enabled to perform
acceptable worship unto God in spirit and in truth.
Some of them have known the baptizing power of the Truth,
and have been strengthened to bear, with Christian fortitude and cheerful submission,
severe trials that they had to endure in consequence of their allegiance to Christ,
and their faithful adherence to some of those testimonies to the
Truth which they feel called upon conscientiously to maintain.
Our friend, J. S. Mollet, who has come with us thus far,
continues to be our faithful helper in interpreting for us as occasion requires.
Several of these dear people have come from among the Roman Catholics.
In the evening we had a meeting held in a spacious house between the two towns,
which was selected as the best calculated to accommodate the inhabitants of both.
It was a good, solemn meeting; the baptizing power of the Spirit of Truth was over us,
under the humbling sense of which many of the people were contrited.
Among those present were some of the Roman Catholic priests who
years ago suffered much persecution in Bavaria and Austria,
in consequence of having become convinced of the errors of Popery,
and preaching that salvation which is by Christ alone.
One of these is Lindel, with whom I have had much satisfaction;
he is a spiritually minded man, of a meek and quiet spirit.^
footnote:[Lindel had been a Roman Catholic priest in a parish near Munich,
and was one of those who, along with Boos, Gossner and others,
had been brought to the saving knowledge of the Truth.
He began to preach the Gospel in its purity to his parishioners.
His preaching was attended with extraordinary power from on high,
so that a great part of his parish were brought under the influence of the Holy Spirit,
and converted.
His fame spread, and multitudes flocked to hear him from all the surrounding country.
Many came under the saving power of Divine grace.
This could not be tolerated in a country like Bavaria, where Romanism was predominant.
Persecution was raised against him and his converts.
II o was thrown into prison, and forbidden to preach any more in the name of Jesus.
Finding that they could not be allowed to worship God in simplicity in their native land,
he and his converts resolved to seek an asylum in
some country where they might enjoy liberty of conscience.
What the Lord was doing for Russia,
and the patronage the Emperor Alexander gave to the Bible Society,
was by this time noised all over Europe.
These good people, therefore, turned their attention to Russia.
Lindel wrote to the Emperor, through Prince Galitzin,
giving a full account of the state of things,
and asking for a place of refuge for himself and his associates.
His application was well received by the Emperor.
Lands were allotted to them in Bessarabia,
and the Russian Minister at Munich was ordered to procure the permission of the
Bavarian Government for them to leave the country and settle in Russia,
as soon as they could dispose of their property, and leave their native land.
He was instructed also to procure the liberation of Lindel from prison,
and to send him on to Petersburg immediately. On his arrival at Petersburg,
the Emperor ordered one of the Catholic chapels to be placed at his disposal,
where he might preach the Gospel to all who chose to come to hear him.
This was a sad blow to the Papists; but they could not help themselves.
Lindel was soon flocked to by hundreds of all denominations who understood German,
and numbers, by his means, were converted to God.
This continued for some time,
and afterwards Lindel was going on comfortably with his colony of adherents in Bessarabia,
and getting them into good order.
Religion was thriving among them, and they looked up to him not only as a preacher,
but as a father.
Their worship was more Protestant than Catholic, a crime not to be forgiven,
as he was changing their religion.--(See William Allen`'s Life, vol.
2, p. 279.) He had in fact changed his own, inasmuch as he had married.
This was taken no notice of, apparently, at the time;
but when his wife brought him a son, a hue and cry was raised against him,
as an apostate from everything that was good,
and especially from the "`Holy Catholic Church.`"
How this should have told against him in Russia, it is not very easy to say,
seeing that all parish priests there are obliged to marry before they can be ordained.
But there was a wheel within a wheel.
The Jesuit Metternich was at work, and he had got Count Aretchcoff completely in his net;
and together they made the Emperor believe that Lindel had committed
such a scandal against religion that he ought not to be tolerated.
The consequence was, that he was ordered to leave the empire on the shortest notice,
and proceed by way of Poland to Germany, where, however,
he was well received by the King of Prussia,
and where he joined the Protestant Church.--See [.book-title]#Book for every Land,# etc.,
by the late John Patterson.
Edited by W. Alexander.]

30th. We visited a number of pious families to our mutual edification.
At four p.m., we had another meeting with those in profession with us; after which,
endeavouring to be better acquainted with their circumstances,
we found that by the jealousy of the Popish priests,
the magistrates have brought some of them under actual suffering;
some for having married after the manner of Friends;
others on account of their militia laws which are very severe;
others because they could not conscientiously take off their
hats in the Courts of Justice where they were summoned.
We have, in consequence,
been with several of the chief magistrates and officers of government,
to whom we have explained what are Friends`' principles,
and the conscientious ground on which they act.
We hope that relief will be granted them.
D+++.+++ Kemp, one of the most influential men both here and in Berlin, is very open to us,
and disposed to obtain all the relief he can for these dear people.
In the evening we had another meeting in Elberfeld;
it was attended by many of their chief men and pious persons;
their hearts appeared open to receive the Gospel Truths given us to declare among them.

31st. Accompanied by D. Kemp we went to Werden, eighteen miles,
to visit a large prison for convicts; it is a spacious place, kept in good order,
very clean and airy.
It looks like a manufacturing town; they spin, weave, and make a variety of clothing,
shoes, etc.
Each man has a certain daily task given him to do, and he is paid for what he does more.
By this means some of the prisoners have a handsome sum given them when they are discharged,
so that they are at once enabled to support themselves,
and have also acquired habits of industry and sobriety.
The Protestants and Roman Catholics have each a clergyman attached to the prison,
to give them respectively religious instruction.
We were pleased with the young Protestant minister,
who appears to have at heart the well being of the prisoners,
both respecting their morality and their religious principles.
Our meeting among these prisoners was as satisfactory as any we have had in any prison;
the minds of many appear to have become soft.
We returned to Elberfeld in the evening,
when several pious persons of the city and from Barmen met us at our inn,
with whom we had a precious parting opportunity.

A little after nine o`'clock the same evening, we set off for Pyrmont,
leaving behind us our dear friend, J. S. Mollet,
hoping that our blessed Lord and Master will provide us with another interpreter,
as we may need.
On our way we visited Bielefeld and Herford.
We passed through a fruitful country, in a high state of cultivation, where,
beside the large quantity of grain raised, a good deal of linen is manufactured.
Cottages are numerous, and each of these is a little manufactory,
while neatness and comfort surround it.
How far preferable is this system to those large manufactories or great farms,
where the poor labourers are kept in abject poverty, and in a degraded state.

On the 3rd and 4th of Eighth month,
we visited those who are in religious profession with us, in and near Pyrmont.
Louis Secbohm accompanied us as interpreter.
He is an excellent one.
I find the little company of professors with us in these parts
in a more hopeful state than when I was with them before.
Love and harmony prevail in a good degree among them.
There are also several interesting young persons.
In some of our religious opportunities there was tenderness of spirit manifested,
with an evidence that the knowledge and love of the blessed Redeemer,
the Lord Jesus Christ, has taken root in some of their minds,
whereby fruits unto holiness may be hoped for, to the glory of God.

On First-day, the meetinghouse of Friends,
which stands near one of the avenues leading to the mineral springs,
was attended by a considerable number of those who resort here from various parts,
to drink the waters.
Many in the meeting were serious, and manifested a reverent frame of mind;
but others were unsettled, evincing that curiosity only had brought them there,
and they added greatly to the exercise of our minds; but,
keeping closely under the guidance of the Lord`'s Spirit, he enabled us,
his dependent servants, to minister to the several conditions of that mixed company.
The Lord Jesus Christ was preached as the Saviour of men.
His various offices were set forth, and his holy name was exalted.
Our minds, however, did not feel fully clear of the weight of concern for the people,
and at the close of the meeting we requested that
those especially who love the Lord Jesus Christ,
would favour us with their company that afternoon.
A large number collected accordingly,
and we have reason to conclude that they were generally
of the description that we had desired.
It was a good and solemn meeting;
brokenness and contrition gave evidence of the religious sensibility of their spirits.
Dear William Allen, as well as myself, felt our minds much relieved after that meeting,
which concluded with prayer, thanksgiving and praise,
to the Lord God Omnipotent and to the Lamb, through the Eternal Spirit.

We spent the ensuing day in preparing to have several religious
tracts translated and printed in the German language,
and in the evening had a meeting with those in Christian profession with us,
and those who generally attend our meetings.
We feel tenderly for this people,
and we had a word of counsel and encouragement to administer to them.

We came to Minden on the 8th. On our entrance into that place,
which has been strongly fortified since my former visit here,
we were detained some time on account of a box, containing Bibles,
books and pamphlets of a religious character, for distribution as we find occasion.
They were taken to the custom-house,
to which some of our friends had to go several times the next day;
but at last they were returned to us.

Our minds here have been under depression.
The state of religion is low.
We also must be kept low ourselves, and suffer with the suffering seed.
We have visited all those professing with us, in their several families.
We had also a meeting with them.
We were brought into near feelings of sympathy for a few Friends,
in whom there is a living exercise of spirit, and we endeavoured, in the ability given,
to encourage these in the patience and faith of the Gospel,
and to strengthen that which remains in others.
We had also a meeting for the inhabitants,
which was held to satisfaction and the comfort of our minds, so that after it we were,
to a certain extent,
relieved from the load we have had upon us since our first entering into this town.
There being many soldiers in it,
has a great tendency to spread demoralization among the people.

10th. We went to Eidinghausen,
a village where several persons that profess with us reside;
we visited them in their families, and had a meeting with them.
The people there live, some might say, in ancient simplicity;
under the same roof are the dwelling-house, the barn, the cowhouse,
the stable for horses and their pigs, also the places for other live-stock, fowls, etc.
The part occupied for the dwelling is at the further end of this large building,
which has no chimney,
so that the smoke makes its escape as it can from the sides or the roof,
which is of thatched straw.
We had a meeting in one of these places; it was largely attended by the villagers.
It was a novel sight to us; we had on each side of us horses, cows, calves, sheep, etc.;
but it seemed as if a total silence was spread over all these,
as well as over the large company collected.
I believe that during the whole time of the meeting, none of the lowing of the cattle,
the bleating of the sheep, nor other noise was heard,
though before and after the meeting they were pretty loud.
Some of the dear people appear to have been much
sheltered from the corruption prevailing in the world,
and also to have minds acquainted with the power of redeeming love.
We were sweetly refreshed among them.
Here reside persons who,
for the maintenance of our Christian testimony against war and blood-shedding,
have suffered grievously.
Some of the tortures they were put to were cruel and of long duration.
One of our friends here has twice endured these tortures, and is now living;
he is a pious, valuable man.
Friends succeeded in having the case represented to the King, on which he was liberated,
and the like tortures have not been inflicted since;
but as the militia laws are not altered, similar cruelties may be renewed.

The next day we went to Hille, another village,
where five persons only are in religious profession with us;
but a few others under convincement join them in their meetings for Divine worship.
We had a meeting there, which was attended by most of the villagers.
They are generally in low circumstances in life;
but several of them appear acquainted with vital religion.
Truly, it may be said, that to day and yesterday the Gospel was preached to the poor.

We returned to Minden and had other religious opportunities with Friends and the inhabitants;
one of these was largely attended by the chief men of the place,
and was a season of Divine favour.
Here we received a deputation from some of the inhabitants of Herford,
to request us to go back to them,
stating that their houses and their hearts were open to us.
We gave due consideration to the subject;
but we did not apprehend it to be a service required of us.
We sent them a word of encouragement to congregate together to wait and
seek for the presence of Him who promised to be with the two or three,
and consequently with the many, who meet in His name,
that they might find Him to be the Minister of the Sanctuary,
the High Priest of our Christian profession, who speaks as never man spoke;
reminding them of the language of the Apostle, "`You need not that any man teach you:
but as the same anointing teaches you of all things, and is truth, and is no lie.`"

Our minds being now released from these parts,
we left Minden early in the morning on the 13th for Hanover.

--
