== Chapter LIV.

Fourth Visit to Europe

Dresden.--Herrnuut and Bertholsdorf--Rumburg--Prague

They now paid an interesting visit to Dresden.

We left Leipzic before daylight on the morning of the 8th of Ninth month,
and the road being good, we arrived at Dresden early in the afternoon.
Part of our road continued to be over extensive and fertile plains,
when the ground became undulated and finally rather hilly, and covered with fine timber,
or, in the cultivated parts, with vineyards.
The scenery was truly beautiful all the way to this place;
we enjoyed it the more as we were favoured to partake in
spirit of the serenity that our eyes beheld in the outward.
I was bowed down and contrited before God my Saviour under a sense of
his goodness and mercy in thus far guiding my steps on this journey,
as he has so graciously done on preceding ones.
He has enabled us to visit his suffering seed in various places;
strengthened us in our sufferings with it,
and given us the word of comfort and consolation for it;
in several instances enabling us to plead with those who are the oppressors.
Our spirits were united in fervent prayers for these,
that the Lord would break down their strongholds,
melt down their hearts by the power of his Truth, and cause his face to shine upon them,
that they may be saved,
and that he would also strengthen and comfort all those who seek him and love him.

While at Halle,
our minds were under such suffering on account of the infidel spirit prevailing there,
and so absorbed in deep feeling for the few who, like Lot,
are daily grieved among that people,
that we did not even think to visit their prison or poor-house;
and now we are told that the cholera prevailed in those places,
to the contagion of which we might have been greatly exposed had we gone to them.
The Lord knows best how to direct the steps of his servants; blessed be his adorable name!

9th. We were this forenoon with Von Lindenau, Prime Minister of the King;
we spent about an hour with him;
he appeared to take a deep interest in subjects of a serious character.
In the evening, during the time of our silent retirement together,
dear Allen and myself were introduced into great solemnity and reverence;
we silently worshipped God and offered him, unitedly,
the sacrifice of brokenness and contrition of spirit; and then, on bended knees,
in vocal prayer, we also mingled our requests and supplications,
first on our own behalf and on behalf of our dear and beloved ones,
from whom we are separated for the Gospel`'s sake;
then intercessions were offered for all those we
have visited as the Lord has directed our steps,
that he would also bless the works of his hands everywhere.
It has been a refreshing season to us,
animating us with fresh dedication to follow our blessed Lord wherever he may call us,
and to do or suffer the whole of his blessed will,
only craving his Divine and all-sufficient grace
to enable us so to do and to walk in his fear.

10th. We visited several pious persons; one of them was Nauman,
whom I was acquainted with nineteen years ago, when he resided at St. Gallen,
in Switzerland.
He has accompanied us to several places; among others, to D. Leonardi`'s,
who appears to take much interest in our Christian engagement among the nations.
He has undertaken to give notice of a meeting to be held
for the serious part of the inhabitants of this city.
Then, accompanied by him, we visited a school founded by the Count Einsiedel,
shortly before he was removed from office,
and the ascendency of the Jacobin party during the Revolution.
His school is however in operation.
Private contributions, together with the provision he has left for it,
enable them to educate in it four hundred children.
They are under the care of pious masters who endeavour
to inculcate sound Christian principles.
We also visited an establishment endowed by a pious
female for the education of twenty-five young men,
to qualify them to become schoolmasters.
They are boarded on the premises, and are educated in sound Christian doctrines,
guarded as much as possible from those freethinkers, and strong Socinian reasoners,
who abound in this city also.
Leonardi was our interpreter in these visits, both to the pupils and their caretakers.

11th. We received this morning a note from Lindenau, the Prime Minister,
telling us that Frederick, the Prince Regent, and nephew of the King,
wished to see us at eleven o`'clock this forenoon.
We had made a previous engagement to be at nine with the Count Callerado,
who is the Austrian Ambassador here; he was serious,
and appears earnest in desires that the Lord may prosper us in our labours of love,
and bless them to those we visit, and to open, as he said,
our way when we come to Prague.
He kindly gave us a letter to introduce us to the Governor there.
We gave him the perusal of our certificates.
He was struck with admiration at the order and care of our Society in liberating
their Ministers for the services to which they apprehend they are called.
We left the Count in good time to be at the palace at the hour appointed.
We were at once introduced to the apartments of the Prince.
The King, his uncle, has no children, and, as he is now old,
the reins of government devolve on Prince Frederick,
who is successor to the throne after his uncle`'s decease, his own father, Prince John,
also being an old man.
The Prince received us with affability and kindness.
He said he knew our disinterested motives for travelling as we do;
for love to God and man prompted us.
"`In this love and good will,`" he added, "`you embrace men of every description,
of every religious denomination, rich and poor;
you go among the most wretched in prisons and poor-houses,
and come to some of us also in our palaces.`"
As his heart was open towards us, we also felt ours enlarged towards him,
and freely spoke to him of the things of God,
and of that salvation which comes by Jesus Christ.
We told him that sin is the cause of all private and public misery,
the origin of all vice and wickedness.
A Government can have no stability where these prevail.
No power can eradicate them but that of the Lord Jesus Christ,
who came into the world to deliver us from our sins.
He came to put an end to sin, to finish transgression, and in the room thereof,
to bring in everlasting righteousness, and to as many as receive him,
he gives power to become the sons of God, even to as many as believe on him.
We entreated him to consider the sad effects of unbelief and infidelity,
and urged the promulgation of sound Christian doctrines throughout his dominions,
and the repression in a firm but Christian spirit,
of the great latitude taken in some of the universities in the kingdom,
where infidelity is openly taught,
and the minds of many of the youth receive the deadly poison,
which they again disseminate in various parts of the nation.
We entreated him also to live and walk in the fear and love of God,
through the grace of Jesus Christ, that, by his Christian example,
he may encourage his subjects to enroll themselves
under the banner of the Prince of Peace.
He was attentive and serious.
Our conversation was in French, and, as none were present but us three, we could,
with the greater Christian freedom, speak plain truths,
and the Prince was also the more ready to hear us.
Before we separated, he told us that his younger brother, Prince John,
desired also to see us,
and called for one of his attendants to show us the way to his apartments.
We found him in a serious frame of mind,
evidently prepared to receive what in the love and fear of God,
we might have to say to him, for he was well aware, as he acknowledged,
that we had no personal favours to ask,
but that it was his good and that of the people at large that we sought after.
Some of his expressions evinced that he has a tender heart.
We encouraged him to cultivate a state of watchfulness unto prayer,
that by close attention to the leadings of the Holy Spirit he may
increase in the knowledge of our Lord and Saviour Jesus Christ,
and be strengthened to walk in obedience to the will of God.
We expressed our desire that he might be enabled to animate his brother, the Regent,
in the promotion of piety and virtue in the nation,
and the suppression of those infidel principles openly advocated in their universities,
since no people can expect to prosper or to enjoy
the Divine blessing when the Lord Jesus,
our blessed Saviour, is rejected.
We therefore earnestly desired that both he and all the Royal family might give
public evidence by their lives and conversation that Christ is precious to them.
The Prince feels interested in the promotion of temperance,
for he sees that the use of intoxicating drink is an inlet
to much misery and to the commission of many crimes.
We presented him with the reports of the Temperance Society in England,
and those on prison discipline and public schools, with all of which he was much pleased,
and not less so with various publications treating on some of our Christian testimonies,
of which he desired to have a more perfect knowledge.

The meeting concluded upon yesterday was held this afternoon;
it was well attended by the class of persons we had particularly desired to see.
The Baroness Drechsel, a pious female,
well acquainted with both French and English as well as her native tongue, the German,
kindly undertook to interpret for us,
should we have anything to communicate in the meeting.
From the first of our entering the assembly we felt a solemn covering over us,
like the over-shadowing of the Lord`'s presence; it reminded me of the language,
"`Keep silence before me, O islands, and let the people renew their strength;
let them come near, then let them speak; let us come near together to judgment.`"
Those present seemed to feel the force of the words,
for all appeared to be gathered with one accord into solemn silence before God,
in which we continued some time;
when with my heart filled by the love of the Gospel I stood up; the Baroness stood by me,
and with great gentleness and modesty, but with striking dignity,
she interpreted sentence by sentence, from the French, what I communicated;
her own mind was very tenderly affected while thus engaged.
The great love of God in sending his well-beloved Son, Jesus Christ,
into the world as a Saviour and Redeemer, was proclaimed among them.
The meeting continued in a state of solemn silence after I sat down,
when Doctor Leonardi spoke a few sentences in German
which the Baroness interpreted into French,
saying that the Gospel truths that had been declared
were the Christian`'s sure and only hope,
and craving the Lord`'s blessing upon the word preached.
After that William Allen bore a solemn and impressive
testimony to the power and efficacy of the Spirit,
by whom deliverance from the dominion of sin is obtained and we
are made partakers of the grace and truth which come by Jesus Christ.
Towards the conclusion of the meeting,
access was graciously given to the throne of grace, and, on bended knees, prayer,
adoration and praise were offered up to God in the Saviour`'s name through the Spirit.

12th. Apprehending ourselves nearly ready to depart from this place, we went to see,
probably for the last time,
some of those persons we have mingled with in Christian fellowship;
among others we were with the Count Lindenau.
He told us that the two royal Princes, Frederick and John,
had expressed to him how gratified they were with our visit to them, and that they hope,
through the grace of God, to be able to put in practice the affectionate,
Christian counsel that we had given them.
We found in Adelaide Higetchen a woman of genuine piety;
her father was a Russian and a Papist;
he became convinced of the errors of Popery and joined one of the Protestant Churches;
this so irritated some of the benighted Papists, that they caused him to be murdered.
Adelaide thought it best to take refuge here; her affliction has been sanctified to her,
and it has brought her to a more intimate acquaintance with the blessed Truth,
and enlarged her heart in the faith and love of Christ.

After these parting visits they left Dresden and proceeded to Herrnhut and Bertholsdorf
the "`mother congregation of the Renewed Church of the Moravian Brethren.`"
Sprung from a small seed of bold confessors of Christ, who,
tried in the fire of persecution, remained faithful even unto death,
that "`beautiful little church,`" as Milner calls it, had weathered many a storm.
"`It could look back to a cloud of faithful witnesses of Divine Truth,
who amidst calumny and opposition, in bonds and imprisonments,
under a tropical sun and in boreal climes, far from home and kindred,
in the east and west, in the north and south, have erected the standard of the cross,
and enlisted thousands to allegiance to Him who died to save a world of perishing sinners.`"^
footnote:["`To withhold from the Moravian Brethren the testimony
of having done much for the kingdom of God,
would be hardening ourselves against the truth.`"--Kahnis [.book-title]#"`German Protestantism.`"#
See also Holmes`' [.book-title]#"`History of the Protestant Church of the United Brethren.`"#]
This interesting community still gave evidence of
lively zeal for the honour of their Lord,
and for the propagation of his Gospel when Stephen
Grellet and his companion visited them.
They arrived at Herrnhut^
footnote:[The name of Herrnhut was given to the settlement by Hertz.
"`We have called this place Herrnhut,`" he says in writing to Count Zinzendorf,
"`to remind us on the one hand, that the Lord is our protector and keeper,
and on the other, that it is our duty to stand in the watch-tower and keep ward.`"
From the name of their chief settlement the Moravians are well known in
Germany as "`Herrnhuters.`"]
early in the morning of the 13th of Ninth month, and, continuing his notes,
Stephen Grellet says:

Soon after breakfast we went to the house of the Count Donha, for whom we had letters.
Before these were opened the Countess, on hearing my name,
recognized me as the person she had repeatedly heard of
through her pious friends in Germany and Switzerland.
They had with them also a Moravian female whom I had seen at Neuwied, on the Rhine,
and who is married here to one of the ten persons on whom devolves the
management of the whole of the extensive concerns of the Moravians in
all their settlements in this and other countries,
and the various Missionary stations throughout the world,
each having a particular department to attend to, though, on all important subjects,
they consult together.
Their oldest Bishop, next to Fabricius, I find, is Huffel,
with whom I had some years since very satisfactory religious fellowship at Bethlehem,
in America.
Thus, on arriving at this remote place, a stranger, as I thought, knowing nobody,
I meet some old Christian acquaintances.
In the afternoon, the Count Donha came to our inn, to accompany us to Bertholsdorf,
a short distance from Herrnhut, a beautiful, retired spot,
where the ten persons above alluded to, reside.
The buildings, where such extensive and important business is transacted,
are necessarily spacious, but the whole, though neat, is very plain;
particularly so are the habitations of these ten Bishops; each has but two chambers,
beside a small parlour and out-buildings.
What a different appearance do these men present to the Popish or Episcopalian Bishops!
There also reside, in separate buildings, aged females,
many of whom are widows of Missionaries who have ended their
days in the field of useful and arduous labour,
in various parts of America, the West Indies, Africa, New-Zealand, and other regions,
where some of these females partook in the toils and sufferings of their husbands.
We paid some interesting visits to them, and the Bishops, and had tendering,
refreshing seasons together.
We returned with the Count in time to take tea with him.
He then accompanied us to the Moravian place of worship in Herrnhut, where men,
women and children were collected together to hear the Scriptures read,
as is their usual practice every evening.
The parts read in an impressive manner, were the first three chapters to the Philippians.
We thought it was good for us to be there.

14th. Count Donha came for us early after breakfast,
and accompanied us in a visit to their schools.
Children here enjoy great privileges.
The whole is conducted with much quietness and mildness.
Love and kindness appear to prevail among them all.
The Count kindly interpreted what we had to communicate
to the children or to the masters and mistresses,
as well as in a visit we paid to about three hundred single sisters.
The Countess Einsiedel is at the head of that establishment.
From the purest motives, she leaves her large and fine estates,
to devote her time to this act of Christian love and benevolence.
Justine Goerlitz is next to the Countess.
She reminds me much of my young friend, Justine Benezet,
at the head of the orphan asylum at Nismes in France, by her piety,
and the gentleness of her spirit.
A meek and quiet spirit is indeed of great price in the sight of God.
Among the females we visited there, some, particularly, interested us much.
Three are from Labrador; others from Sarepta, in Russia, near the Caspian Sea;
others from the West-Indies, and other parts; but all are united by the one Spirit,
and love the same Saviour.
They formerly spoke different languages,
now they unite in harmoniously singing the same song of glory and praise.
Our next visit was to the single brethren,
who exercise a variety of trades in and out of doors.
We had some religious service among them.
In the afternoon we visited the house for the widows.
Each has her separate apartments, all in great simplicity.
They appear acquainted with the place of prayer.
Our visit to them was of an edifying nature.
In the evening we had a meeting for Divine worship in the Count Donha`'s house.
He had preparations made for it in his two spacious parlours,
thrown together by folding doors.
The meeting was largely attended.
The Lord owned us very graciously by his Divine presence.
The baptizing power of the Spirit of Truth was felt, and tears were shed by several.
My soul magnifies the Lord,
who has given us the opportunity to meet with these
sheep of his pasture and lambs of his fold,
and to unite with them in ascribing glory, honour, majesty and praise, to Him,
the Lord God Omnipotent, and to the Lamb, our crucified Saviour and risen Lord.

The next morning, previous to our departure,
the Count came to see us once more to bid us farewell.
Both he and his pious Countess, will long live m our memory.
Our communication and fellowship with them, and many others in this place,
have been sweet.

They now passed over into the land of John Huss and Jerome of Prague.

We set off about eleven o`'clock for Rumburg, the first town in Bohemia.
The road was bad; very stony, but very romantic.
The rains and the weather have, in the course of time,
washed these stones into a great variety of fantastic shapes and forms.
In some places they appear like the ruins of vast edifices, with wide archways,
and high pillars; some resemble fortresses with their turrets;
some look like men on horseback, or horned cattle, and other objects.
Over the high ground, among the Silesian mountains, we found it very cold.
We had some difficulty at Rumburg, on account of our passports,
which none there could read, understanding no other language than German.
After some detention, two young men, travellers from Vienna, came in.
They spoke both French and English, as well as German,
and matters with the public officers were soon adjusted; but, by that time,
a crowd had collected about us, attracted by curiosity, to see the strangers.
They were, however, very civil, and I felt my mind drawn towards them in the love of God,
who has made of one blood, all the nations of the earth, whether they be Europeans,
or Americans, white, red, or black;--Christ Jesus has died for all,
would have them all to be saved from their sins, and to become joint heirs with him,
of his kingdom of everlasting blessedness and glory.
One of the young men from Vienna interpreted what was said.
They bid us farewell, wishing us a pleasant journey.

We now entered a country entirely inhabited by Roman Catholics,
as is abundantly shown by the many crosses erected on the roadside.
We passed over very high ground.
The Giant Mountains were in sight.
We were also for some miles among thick forests, covered mostly with pines,
like some of ours in America.
The beauty of the landscape in many parts is beyond description.
The hills and mountains have fanciful shapes, differing from one another.
Some are sharp-pointed, others are conical; others seem to be covered with ancient ruins.
We saw towards the high peak of one of these mountains, of very difficult ascent,
a monastery of the monks of the order of La Trappe,--the most rigid of any.
They appear there, literally to have the earth under their feet,
and even to have their dwelling in, and often above, the clouds.

Late in the evening of the 16th we arrived at Prague;
we had stopped a short time at Jung Bunglau on our way;
superstition greatly abounds there; there are, nevertheless,
those among them towards whom our hearts were warmed with Christian love,
and we much regretted that no way opened for more religious communication with them.
It is a great consolation to me to have the persuasion that there are
those among the various nations and the various Christian professors,
yea among Jews and Gentiles, who fear God,
and according to the measure of grace that they have received,
work righteousness and are accepted with Him, through the one Mediator.
We met with difficulties and dangers on entering this large and fine city;
the night was extremely dark, and they were making repairs in the street,
so that we were in some danger.

17th- We went this morning to the Governor`'s palace; he is absent, having gone to Italy;
but the Count Prozka, Vice-Governor, opened the letter that was given us at Dresden,
and with much kindness offered at once to give us every
assistance in his power during our continuance in Bohemia.
We acknowledged his kindness, but told him we did not expect to remain long at Prague,
and intended to proceed, when we left it, directly for Vienna.
We obtained from him some interesting accounts of the state of
morals and of the education of the people throughout the country.
The criminal code, which was very sanguinary, is now comparatively mild.
In years past the Popish Inquisition was here active and severe;
the flames by which John Huss and many of his adherents
were destroyed have often been re-kindled.
Many pious persons have suffered because of their conscientious
and faithful adherence to the faith and love of Jesus Christ,
but now, as at Rome, the Inquisition is conducted in a milder way;
yet the Popish clergy continue to have great power,
and they are supported in it by the laws of the State.
As we wished to visit their great prison,
the Count sent for one of his secretaries to accompany us,
and to serve us as interpreter; he is a mild and serious young man, and speaks French.
On our way to the prison, which is at a considerable distance from the Government-house,
he appeared desirous of improving the time by making various
inquiries on things pertaining to the kingdom of God,
and that salvation which comes through Jesus Christ alone,
not in consequence of our works or merits, or by the power or agency of Popes,
or of any man.

As we passed near his house he respectfully entreated
that we would stop a few moments to see his sister,
whom he represented as a young woman of sincere piety.
In the course of the interview we had with her we found her so;
she understands the difference between formal and ceremonial religion
and that religion which proceeds from pure and sincere love to God;
she appears to have deeply considered what the baptism
of Christ is by which a man is made a new creature,
and also what is that bread from heaven on which
this new creature or the true Christian is to feed;
her remarks on the purifying and sanctifying operations
of Divine grace and the renewings of the Holy Spirit,
evince a mind that has learned in the school of Christ.
She also stated her belief that the qualification requisite
to enable poor mortal man to approach the Father of spirits,
and to offer up to him acceptable worship,
must be through the influences of his Holy Spirit.
She was persuaded, she said,
that this is a service required of females as well as of males, and inquired, why women,
if thereto called of the Lord, could not publicly pray and preach;
for they worship the same God, who has a right to make choice of,
and to prepare and commission his own servants, whether male or female;
she wanted to know the views and practices of our Society on these important subjects.
We felt our hearts open to answer these inquiries,
and to encourage her closely to attend to the influences
of the Spirit who has thus far illuminated her understanding,
not only to give her some knowledge of the Truth, but who, as she is faithful,
will also enable her to live and walk in the Truth,
whatever may be her sufferings in consequence of it;
the Truth which is powerful will preserve and support her under all.
We left with these interesting young persons several books that
treat on the important subjects on which we had conversed.
They had not heard before of any body of Christians
who entertain religious views of this sort.
The Scriptures and the Lord`'s Spirit have been their sole instructors.

On our way to the prison we passed through the public square,
where the faggots were formerly kindled, and the flames devoured many pious Christians,
under the hands of the Inquisition of Rome.
The flat stones on which the piles were erected and the victims were placed,
identify the very spot where such cruelties were perpetrated under the mask of religion;
but I was not less deeply grieved at beholding the stately buildings around the square,
with the many large windows opening upon it,
which used to be crowded with spectators to see the
savage proceedings prompted by blind superstition;
some of these windows still show the conspicuous seats occupied by their great men,
both of the clergy and civil officers, during those exhibitions of cruelty.

We found about six hundred prisoners in the prison.
They carry on there a variety of trades.
By the sale of the articles made, the income considerably exceeds the expenses.
Even this year, during which the labours of the prisoners have been much interrupted,
they think that their receipts will exceed the expenses by fifteen thousand guilders.
The cholera prevailed there for about two months.
One hundred and fifteen prisoners died of it.
There are yet some cases existing, both in the prison and in the city.
The mortality has been great in various parts of the country,
so that in some places from one to two thirds of
the inhabitants have perished by that disease.
The ravages by it began last year.
In a number of instances it passed over some villages and towns,
attacking but very few of their inhabitants, while the mortality was great in others.
This year it pursued a different course;
its ravages have been great over those places that were spared last year,
and but few persons have been attacked with it, where it had prevailed before.
These prisoners generally wear heavy irons, and are kept under severe discipline.
We saw in one prison one hundred and fifty women under heavy irons also.
It is the first time that I have had such a painful sight.
None under fifteen years of age are sent to these prisons.
According to the magnitude of the offence committed, they are chastised with whips,
or by solitude and fasting, and then turned out;
but it is said that they are mostly soon apprehended again,
for the commission of greater offences.

This city contains seven thousand soldiers, and about eighty-six thousand inhabitants,
six thousand of whom are Jews.
It stands in a valley, through which runs the river Moldau,
over which is a handsome bridge.
The surrounding hills are high and beautiful.
On one of these is a spacious palace of the Emperor, and near it that of the Governor,
to which we have been.

In the afternoon we went to the Lutheran pastor`'s.
We found him a man of humility and piety.
His community is composed of about three thousand persons.
They are kept under great restrictions;
they are not allowed to print anything without special permission,
which is obtained with difficulty.
From the same cause they have but few Bibles among them.
The penalties are very severe on a Protestant clergyman,
or any other person attempting to proselyte any Papist to their religious tenets.
The Minister may preach his doctrine in his own place of worship, but not out of it,
and if a Papist attends the meetings of Protestants, he is liable to be prosecuted.
We feel very tenderly for those who live under such restrictions.
Sufferings, however, are, we hope, blessed to some of them, at least;
their hearts are kept soft under it,
and they appear to have a part in the blessing pronounced upon
those who are persecuted and reviled for Christ`'s sake.

On my return to the inn I found the waiter in my chamber,
attentively engaged in reading in my French Bible.
He appeared at first disconcerted, and began to make apologies,
but I soon removed his fears.
He said that he had not seen a Bible for some years;
formerly he had access to one which it was his delight to peruse,
but here it would be impossible for him to obtain one, and if he did,
he should be obliged to keep it closely concealed from the priests.
On conversing with him we found him to be a person of a pious, seeking mind;
he knows several others under like religious concern with himself;
but they are obliged to keep very silent;
otherwise persecution or a prison would soon be their portion.
We presented him with a Bible in German, and a few tracts in the same language;
it seemed as if he was receiving a treasure, which, he said,
both he and his friends would greatly appreciate, and endeavour to keep very private.
There are, we hear, many such pious and hidden ones in Bohemia,
well known unto the Lord though unknown to man.
