== Chapter LV.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Austria
* Hungary

The Austrian Empire did not appear to afford much scope for their Christian labours,
and they proceeded at once from Prague to Vienna.
Here they received much kindness from Prince Paul Esterhazy,
and through his means way was remarkably prepared
for a short visit to the borders of Hungary.
But, on returning to the Austrian capital,
no opportunity for extensive usefulness seemed to open,
and they soon felt themselves at liberty to leave the dominions of the Emperor.

[.offset]
Stephen Grellet gives the following account:

[.embedded-content-document]
--

We left Prague at five o`'clock p.m., on the 17th of Ninth month.
Thirty-seven hours of close travelling brought us to Vienna;
we arrived there low in mind and body; two nights and one day of constant motion,
together with our laborious engagements at Prague, preyed on the physical powers,
especially as I continued to suffer much from my lame shoulder;
we were still more oppressed in spirit by the darkness and
the Popish superstition that prevail to a high degree;
the police of the Austrian government strictly cooperate
with the clergy in upholding both.
We passed through several small towns where the cholera is still prevailing.
In one large village the flames had just destroyed nearly every house, so that now,
when the cold weather sets in pretty severely, the aged people,
the children and the sick are without a shelter,
and as nearly all their household goods have also
been destroyed they are left truly destitute.
Our hearts are sensibly touched with sympathy for them.
The country we travelled through in Bohemia is fertile and well cultivated;
but much of what we passed over in Austria is sandy and covered with pines; some miles,
however, before reaching Vienna, the soil is again fertile, especially near the Danube.

21st. On arriving in this city we had to present
ourselves at the police office with our passports;
close questions were put to us respecting our objects in coming here;
our answers attracted their attention and led to the explanation
of some of our Christian testimonies and practices,
which appeared things very new to them; they treated us civilly,
but we were very sensible that a jealous and suspicious eye was upon us;
we did not flinch from telling them with Christian candour
and clearness what our engagements had been in other parts,
and what was our inducement in coming among them.

The Baron D`'Escheles, and the Baroness his wife, came to see us.
He is the Danish Consul.
They are persons of superior minds.
We were also with the Prince Esterhazy,
who has been for many years the Austrian Ambassador in London,
and with whom dear Allen is acquainted.
A particular object that we had in seeing him,
was to obtain information respecting Hungary,
a country towards which I had felt my mind attracted, with no prospect, however,
that I am required to go much into it.
The Prince, besides owning large estates in Austria, has extensive ones in Hungary.
I think we were told that he has about eighty or
ninety thousand persons on his lands there.
Many are Roman Catholics and Protestants, others are of the Tartar or other nomad Tribes.
There is much good land in that country, where the vine is cultivated,
and a great deal of grain; but it has also extensive uncultivated plains,
as in the Crimea, among the Tartars.
There large flocks of cattle and sheep are fed.
The revenues of the Prince, in wool, are very large.
He is well disposed towards his people, and, as far as he can, independently of Austria,
he grants them full liberty of conscience;
consequently the free circulation of the Holy Scriptures is allowed among them.
He is anxious that schools should be established throughout his estates,
where a moral and virtuous education might be given to the people generally.
He encouraged us to go a little way at least into Hungary, to see for ourselves.
This I was willing to do.
The Prince told us that about forty miles up the Danube,
he has one estate on which are some towns and villages settled mostly by Protestants,
and that the whole tract of country, between here and there,
belongs to him or his father.
He added that we must expect to find there a very plain and simple people.
We inquired if we should find places to lodge at.
"`Yes,`" said he, "`there are some places where you may find some kind of shelter,
and also simple but wholesome food.`"
We wanted no more, we told him.
Then again he said, "`as you have no vehicle of your own,
and will be in a strange country, make use of my plain travelling carriage,
with a man to accompany you.`"
All these were unexpected offers to us.
We took time to consider of it, when,
finding that we could not well proceed there otherwise, we accepted the kind offer,
and have made arrangements to set off tomorrow morning.

We had engaged to take tea that evening at the Baron D`'Escheles,
whose residence is four miles out of the city,
and very near to the palace of the Emperor.
We expected to be with the Baron`'s family only.
Great, therefore,
was our surprise when we found ourselves in the midst of a numerous company,
mostly of the nobility, who, it appears, had been invited on our account,
but entirely unknown to us.
It was an opportunity that we could not have obtained by efforts of our own;
for the police is so strict, that we could not appoint any public meetings.
We are well aware also, that we are most strictly watched, for even the valet-de-place,
who is the servant that attends upon us at the inn,
or who goes out with us to show us the way to the places we visit,
is an emissary of the police; they contrive to place such over every stranger,
that all their movements may be closely watched.
The whole of the company spoke French;
our communication with one another was therefore without an interpreter,
on my part at least;
we were for awhile engaged in answering the inquiries
made by some who collected about us for the purpose,
but after a time way was made for our having a full opportunity
to proclaim before them all the glorious Gospel of Christ,
the King of kings and Lord of lords, the Head of the Church and the only Saviour;
we told them that he alone can save from sin,
and if those who wish to try to enter his kingdom
by any other way than by him who is the door,
are accounted in the Scriptures but thieves and robbers,
how much more are to be accounted as such those who
assume the power to open or close that door,
at their pleasure, to others!
We directed them to Christ, who is the way, the truth, and the life,
without whom none can come to the Father;
finally we commended them to God and to the Word of his grace,
which is able to build us up and to give us an inheritance
among all them which are sanctified.
Great seriousness prevailed over the whole assembly;
the doctrine was new to many of them,
but the faithful witness in their own hearts brought home
the conviction that it was the Truth as it is in Jesus;
therefore no objection was raised by anything.
Our spirits have magnified the Lord for his great goodness in thus
making a way for us to proclaim his great name as the only Saviour,
in a place where we seemed to be hedged in on every side.

The next morning the Prince Esterhazy sent his travelling carriage to us, as agreed upon;
it is a light but very plain vehicle; we had post-horses put to it;
but we were much surprised when at every station on the road where horses are changed,
the Postmaster refused to receive any money;
to this effect orders had been sent from the Prince, to whom, or to his father,
that tract of country as well as the post-horses belong.
But we were much more surprised when, arriving at Eisenstadt,
where we expected to find a village only,
and where the Prince had told us we should find some kind of shelter and plain,
simple food, we were driven to the Prince`'s chateau, a spacious palace, and his steward,
to whom information had heen sent of our coming, was waiting for us,
and had dinner prepared.
At first we thought that surely there must be some mistake; but the steward,
to remove every such apprehension,
showed us the directions he had from the Prince to have us accommodated in the palace,
and also to facilitate our going to the different
villages or places that we might wish to visit,
and to supply us with horses for the purpose out of his stables.

The Prince generally spends a few months here every year,
but at present there is nobody in the chateau, except the steward and his attendants;
there is, however, a regiment on the premises, and the guard is mounted.
This palace stands in the midst of a fertile plain, high hills and mountains are near;
the latter are covered with snow.
They are a continuation of the Alps that run through the Tyrol.
The Danube flows between the plain and them.
The view is most beautiful, and the air is very pure.

It was not the country we had come to see, but the people; to them, therefore,
our attention was directed.
The mass of the people here speak another language.
The steward kindly provided us with an interpreter who speaks English.
The first villages we visited, are settled by Croats.
They are a fine and hardy race of men.
They have much strength, are of high stature, and very industrious.
They are a mild and peaceable people.
A number of them speak the Bohemian language.
Their houses are white-washed, inside and out, which gives them a cleanly appearance.
We visited three of their villages,
which contain together upwards of three thousand inhabitants.
We found in some of these people, religious sensibility.
We felt also great interest in another village,
that contains about three thousand persons, mostly Austrians, and Roman Catholics.
The demands of the clergy upon these are so heavy that,
together with the imposts levied by the Government, they are kept very poor,
though they are frugal and industrious.
The cholera was prevailing in these parts during the Seventh and Eighth months last,
and has been very fatal.
This has been the case throughout Hungary.

We went to Oedenburg, the first town of any size in Hungary.
One half of the inhabitants are Protestants.
We paid a satisfactory visit to the pastor of their Church.
He is the head of one hundred and forty churches of the Lutherans,
in the districts on this side of the Danube.
Protestants are numerous in Hungary.
There are about two millions of the Reformed Church, and one million of Lutherans;
the rest are Roman Catholics and Mahometans.
John Kiss, the Lutheran minister here,
tells us that they have many schools among themselves,
but the Austrian government places great obstacles in the way of
their being supplied with suitable school and religious books,
and with the Scriptures also;
but that nearly every person in their congregations can read,
and that every one also has an opportunity of hearing the Scriptures read,
or of perusing some of the few copies they possess,
which they consider a great privilege.
What this clergyman tells us of the state of morals
among the Protestant community in Hungary,
generally, is very satisfactory; it appears to exceed that of the Roman Catholics.
He can speak of this with confidence,
particularly as regards the numerous churches under his superintendence,
which he visits once every year; and he further says,
that the Socinian doctrines are scarcely known among these,
and that their church discipline would not allow them in any of their members.
The little fellowship we have had in this place, with a few individuals,
is very satisfactory; but no way opened for a public meeting.

We visited also the village of Siegendorff, which is inhabited by Croats and Hungarians.
Our minds were, in much affection, drawn towards them.
Many of them appear acquainted with the operation of the Divine Spirit,
and the love of Christ.
The Prince has here one of his finest flocks of sheep.
He treats his subjects with kindness.
The neatness of the villages they occupy bespeaks the care bestowed upon them.
Here, also, all the houses are whitewashed, inside and out.

We felt ourselves released from going further into Hungary,
and we returned to Eisenstadt, to the Prince`'s palace,
where we remained but a short time, being anxious to return to Vienna.
That palace contains one hundred and six bedchambers;
but the steward tells us that on some occasions he
has found beds for above three hundred persons.
The chamber that I occupied fronted the Danube.
A little below it is the ancient castle,
where the treasures of the family of the Princes Esterhazy are kept.
Prince Paul, as we saw him at his residence at Vienna,
would not give an idea that he possessed such great wealth.
We found him quite simple in his own person.

Soon after returning to Vienna, we were with the Prince,
to acknowledge his unexpected and very kind treatment.
He took great interest in the account we gave him
of the situation of his Protestant subjects,
and the difficulties under which they are placed.
He thinks that he may succeed in removing the restrictions
which prevent their having free access to the Scriptures,
and a supply of suitable books in their families, and for the use of their schools.
We had free communication with him respecting the
value of the exercise of liberty of conscience,
and how oppressive it is in a Government to prevent this;
but he knows that this is a delicate subject to treat upon, in this Empire,
where Popery has so great an ascendency.
Before retiring from him, we had a solemn religious opportunity,
and we left him in a tender state of mind.

We visited Christian Ileyse, pastor of the Lutheran Church in this city;
as he speaks French, we had free conversation with him; he appears to be a man of piety,
attached to the cause of the dear Redeemer;
he gave us a deplorable statement of the condition of the Protestants in this city;
there are those among them who deserve not the name of Christians,
for they are Free-thinkers and Rationalists, or mere worldlings;
they do much harm to the Protestant religion;
but there are a few others to whom Christ is precious,
and who endeavour to adorn their Christian profession by piety and virtue;
some of these are particularly to be found in the surrounding villages.
He says that the difficulties the Protestants are
under in Austria are greater than in Hungary,
but, notwithstanding this, it is not uncommon for Roman Catholics to become Protestants,
though by doing so they are subjected to great persecution.
I have heard that the inhabitants of two villages are now in this predicament.
Heyse resided for some years in Transylvania;
he says that genuine piety was prevailing in several
sections of that country among the Protestants,
but that even there others had, to a lamentable extent,
adopted the Rationalistic opinions.
O how lamentable are the breaches made on vital Christianity!
Superstition on the one hand rules powerfully,
and on the other the spirit of unbelief has a wide sway;
true indeed it is that "`strait is the gate and narrow is the way that leads to life,
and few there be that find it,
because wide is the gate and broad is the way that leads to destruction,
and many there be that go in thereat.`"

We were in company with some of those called the Reformed Church; they,
like the Lutherans, are kept under the iron rod; a number of the Papists join them also.
Several priests and monks are convinced of the errors of Popery,
but they dare not make a public avowal of their faith,
knowing what persecution must follow.
But there being more simplicity among the common people,
we are told that nearly whole villages are embracing
the principles of the Reformed Church;
a number of persons from these are now in prison on that account.
Through the medium of pious characters we have put a number of religious tracts,
in the German language,
in a way to be extensively spread throughout Hungary as far as Bucharest,
and also here in Austria and Bohemia.

An interesting young man visited us; by having access to the Scriptures,
and attending to the convictions of the Divine Spirit, he has seen the errors of Popery,
in which he has been educated;
he cannot escape long unnoticed by the priests or the police;
but he appears resigned to whatever suffering the Lord may
permit him to be brought into for righteousness`' sake.
Should a way open for his retiring to a country where liberty of conscience is allowed,
he would thankfully accept it.
Very many in America and other lands, who enjoy this privilege,
are not sensible of the value of it,
nor of the sufferings that the lack of it subjects many tender-minded persons to.

--

[.offset]
On the day before their departure from Vienna,
Stephen Grellet writes to a friend in England.

[.embedded-content-document]
--

Last night the prospect having unfolded that we may proceed towards Bavaria,
after properly weighing it, we have attended to the needful preparation,
and taken our places in the diligence for Munich.
Were we to stay weeks here, very probably many things would open to our view;
there is indeed a great deal to excite our interest;
amidst many baptisms a precious and consoling relief is obtained at the throne of grace,
where our merciful High Priest is pleased to sanctify and render acceptable
to God the sacrifices that are laid upon the altar of offering.

We are glad, however, to be able to get away from Vienna;
the jealousy of Government and the whole of the police is such,
that the way to visit their prisons is much shut up.
The pious people among Protestants are under fear of speaking.

--
