== Chapter LXI.

[.chapter-subtitle--blurb]
Fourth Visit to Europe

[.chapter-synopsis]
* Spain
* Valencia

They left Madrid early in the morning of the 12th of Third month.
On reaching Valencia Stephen Grellet continues his journal:

[.embedded-content-document]
--

Valencia.
Third month, 15th. We arrived here about noon this day.
We were favoured to escape falling into the hands of banditti,
who are numerous on that road.
Only lately they attacked the diligence, which they robbed of a considerable sum of money.
As we passed through the towns on our way here,
we were much surprised to see the streets full of people looking at us.
At the public houses also where we stopped to take refreshment,
many of the better sort of inhabitants came into the room we were in,
and manifested desire to obtain information respecting our Christian principles.
We could not understand the meaning of all this;
we had never observed such curiosity anywhere else.
A Frenchman, who was a fellow traveller part of our journey,
though not in the same division of the carriage,
came in a very civil manner to our apartment and requested more information
respecting the principles and testimonies of our religious Society.
He said that on the road he had endeavoured to give to the multitudes thronging about us,
the little information he had,
and many now come to him with inquiries that he is not able to answer.
We asked him how the people knew anything about us.
"`Have you not read the newspapers?`"
he replied, and handed us one containing an extract from the Madrid Gazette,
with a copy of the order sent by the King to the
Governors of the Provinces and the public authorities,
and people where we may travel,
directing that due civilities should be shown to us by all,
and that free entrance be allowed us to any place we may wish to visit.
It states also, that we are members of the religious Society of Friends,
known by the name of Quakers;
that it is part of our religious scruples to enter all places and appear before everybody,
without uncovering the head,
considering that real honour or respect cannot be
properly manifested by taking off the hat;
that, accordingly, we had been before the King and Queen, and their young Princess,
with our hats on.
Orders are therefore given that no molestation be offered us, either on this,
or on any other account whatever.
It appears that this order was made known in the places we passed through,
and excited the curiosity of the people to see us.
Here, also, this order is published in their newspaper.
We are thereby rendered very public characters.
It places us, in some respects, in a trying situation; but, in others,
the Lord`'s hand may be seen in it,
for it furthers the object for which we have come to Spain;
pious and serious persons are attracted to us,
with whom we might not otherwise be able to become acquainted.
Several of these have been with us this evening;
they evince that religious inquiry is the object which brings them to us.
By this order of the King, also, we may escape being annoyed or molested in the streets,
where frequently the priests are met with, accompanied by persons with lighted tapers,
carrying the consecrated wafer to a sick or dying man,
when the passengers not only take off their hats, but fall down on their knees.
We did not meet with any of the priests on such occasions while we were in Madrid;
had we done so in some particular streets, we might have been exposed to much abuse,
if not to the loss of our lives.

16th. We paid a visit to the Governor General.
It was proper we should early deliver to him the King`'s letter.
He received us with kindness,
and said that he had a private letter from the King to the same import.
We were gratified by meeting in him a mild, serious man.
We endeavoured to see if we could not be released from visiting their prisons,
this being a trying service to us; we are thereby introduced into much mental distress,
and frequently into no small degree of bodily exposure and suffering.
But we could not feel excused.
We yielded therefore to the duty pointed out to us;
for we have not come here to please ourselves, nor to direct our own steps.

The Governor kindly found a person to accompany us, and to serve as interpreter.
He is a French physician, who is attached to the French Consul, Gautier D`'Are.
The first prison we went to is for the civil offenders of this city.
The prisoners are such as have not yet been sentenced; accused of small or great crimes,
they are all promiscuously together.
Some are in only for having tried to smuggle a few pounds of tobacco.
A blind woman is there on whom only three ounces of that contraband article were found.
There are also many boys from thirteen to seventeen years old,
charged with small and great crimes, even murder.

In another prison we visited such as have been sentenced
to imprisonment for a term of from one to ten or more years.
Many of these are shut up in small, dark cells, about seven feet square;
the only light or air admitted is through a hole, of about five inches square,
in the thick wall.
We found two or three persons in each of those cells; the air was so corrupt,
that we could hardly breathe it.
There are also larger cells, but these are more crowded in proportion to their size,
particularly in the two prisons called the Towers; these are dismal places indeed;
we descended into several of them through a steep, narrow, dark staircase;
the ceiling is a vault about thirty feet in height;
the light and air are admitted through a small aperture
in a wall from nine to twelve feet thick.
Bugs are numerous on the walls of all these prisons; they bear evidence that no broom,
consequently no whitewash, has passed over them for years.
Most of those immured in these dismal places are loaded with heavy chains;
but more horrible than all are the cells where those condemned to death are confined.
In some prisons of a better kind we found a considerable number of prisoners of state;
persons of all ranks;
some of these were among the chief in the late plots and insurrections,
and it is very remarkable that, but a few months ago,
the very men now confined here had these prisons filled with the Liberal party,
whom they treated with great cruelty,
daily sending some of them to private or public execution; now,
that in their turn they are themselves confined,
such of the Liberal party as have escaped with their lives, visit them,
not to upbraid them, but to administer some of those necessaries,
for the lack of which they had themselves greatly suffered.
The physician, our attendant, showed us where he was himself confined,
and also some of the men from whom he endured most;
but he spoke to them with kindness and feeling.
It is very pleasant to find that such a disposition
towards these prisoners prevails generally:
it evinces a Christian spirit.
One of these towers, perhaps both, was built by the Moors;
it appears nearly impossible for any prisoner to make his escape from such strong places.

We were this evening with Gautier D`'Are, the French Consul;
he gave us some moving accounts of the scenes of cruelty he had witnessed
during the late conspiracy against the King and the Government.
We were also in company with several persons who came to our lodgings
on purpose to inquire into several branches of our Christian testimonies.
Many among the people, persons of rank and priests,
are convinced that the superstitious forms and observances
in the church of Rome are no parts of the Christian religion,
but are in opposition to it.
Some of these were heretofore afraid to avow their sentiments;
several were put to death for doing so;
others retired to secluded places on the mountains.
We were much pleased with the seriousness of many of our visitors,
and very striking were their remarks while they contrasted
the excellency and purity of our Christian principles,
founded as they are on the testimony of the Holy Scriptures,
with the many inventions and superstitions that the ignorance
or depravity of man have accumulated in the Popish church;
we had a satisfactory and edifying religious opportunity with them.

17th. Today we visited their poorhouse; they have about six hundred inmates in it,
two hundred of whom are children;
their meagre countenances proclaim that their allowance of food is insufficient;
it is only eleven ounces of bread per day, and some very thin soup.
About two hundred more come daily to the doors to
receive a small portion of that miserable pottage.
We proceeded to another poorhouse, which is richly endowed by the Canons;
it is under the care of one of them, who has the sole direction;
he is named by the Archbishop; he appeared very ready to act as our interpreter,
though we had the French physician with us.
There are about eight hundred young persons, boys and girls; the apartments are spacious,
and very clean; the inside walls are lined to a certain height with tiles.
Their rations are sixteen and a half ounces of good bread, good soup and meat.
Various kinds of labour, suitable for each sex, are here introduced.
Our attendant, the physician,
told us that most of these young persons are children of the canons or priests.
Next we went to the hospital, which is a magnificent building, like a large palace;
the wards for the sick are large and airy;
in the centre of these is a very spacious place,
over which is a large dome which serves for a ventilator,
as well as to give light to the whole building.
The wards for the women are over those for the men;
they are attended by fifty of the Sisters of Charity.
Next to this hospital is the one for foundlings;
from twenty to thirty of those wretched infants are admitted every week.
Five out of six die the first year.
We went after that to the retreat for insane persons;
it is the worst place I have beheld anywhere; our feelings were overpowered;
we should have totally flinched from proceeding in a visit so repugnant to humanity,
was it not for the hope that the representation to the King of what we have beheld,
may lead to an entire change in the treatment of
this deeply afflicted portion of our fellow-men;
many of them are loaded with chains, and shut up in cells,
which are in a most filthy state; their food is thrown to them as to wild beasts.
Others are placed on platforms raised about three feet from the ground;
strong iron railings are in front of the whole,
and by iron rails also they are separated one from another;
each individual is shut in a cage; their food also is thrown in to them as to dogs.
The floor of these cages is paved with marble, slanting down from the back to the front;
to cleanse the filth that would otherwise accumulate in the cells,
they throw in daily a few buckets of water,
which renders many of these poor creatures frantic.
The females, we are told, are treated in the same manner;
but our feelings would not allow us to visit them.
We find that ten per cent.
only of the miserable objects admitted here recover.
The treatment is calculated rather to increase their malady ten-fold.
The last place we went to is the prison in the citadel;
the prisoners are chiefly conspirators; one of them is a Capuchin friar;
he was a chief among the conspirators;
he also went about to preach and persuade the people to
massacre all those who were opposed to their licentiousness;
in another part we found a priest, who also preached bloodshed and destruction.
This has been a wearisome and trying day; the air we have breathed,
the mass of human misery and depravity we have beheld,
appeared sometimes to be more than we could bear:
we did not find in any place anything that could administer
a drop of consolation to our afflicted spirits,
except the thought that our representations to the King
may be a means of diminishing this mass of human woe.
Curiosity could never induce me to visit such places;
the hope of being an instrument in the Lord`'s hand to turn some from darkness to light,
and from sin and Satan to Christ the Saviour,
and that their bodily sufferings also may be alleviated, constrains me.

Yesterday and today we were a good deal annoyed by the crowd of persons,
in the streets we were expected to pass through, eager to see us.
The windows of the houses were filled with persons of both sexes for the same purpose.
All, however, were very civil.
It is humiliating indeed to be thus made a public spectacle to men.
The King`'s printed order respecting us is the most calculated of anything
that could have been devised to excite the curiosity of the people,
and to induce some to inquire into the nature of our Christian faith,
doctrine and practices.
The few tracts we have handed to some serious persons, are eagerly read by many.

18th. We went to a prison for condemned women.
Here we found them quietly and diligently engaged in manual labour of various kinds.
It looks like a manufacturing establishment.
Both the house and the prisoners are clean.
A motherly looking matron has the oversight of them.
She is pious, and by kindness and love she appears to obtain such ascendency over them,
that the most unruly seem changed soon after they enter this prison.
Here most of them are sentenced for ten years or upwards, and, though confined for theft,
the matron tells us that it is very seldom that any article is stolen in the prison.
There are several instances in which the reformation has appeared
so complete as to induce the matron to recommend them to the Governor,
who has liberated them, and their subsequent conduct has continued good.
Among the inmates of this prison we had a satisfactory religious opportunity.
Tenderness of spirit was manifested by many of them.
The next place we visited is said to be for orphans of both sexes;
but by our kind attendant we find that they are children of priests.
They are admitted here from about seven till they are sixteen years old.
They are instructed in school-learning, and manual labour.
They are altogether under the care of the priests.
The boys`' dress gives them the appearance of young monks.
They are indeed trained in the habits of the mendicant friars,
for some of them are sent daily into the streets, and to the doors of the churches,
with a small bag about their necks; it is locked up,
but has a little hole into which pieces of money are dropped.
Our visit was rather trying.
We could not feel excused without proclaiming pretty close doctrine to the priests.
O! what wickedness is committed under the mask of religion.

We were again with the Governor, and several of the chief men of the place.
There appears to be a spirit of religious inquiry.
Many wish to know what is Truth; but how few are willing to walk in it!
We had this evening another interesting and satisfactory meeting with pious persons.
Some of them have come from a distance in the country, to be with us.

19th. I had a suffering night, with a chill and high fever.
The prospect is gloomy, for we had concluded to leave this evening for Barcelona;
how it will be now, the Lord knows, all things are possible to him.
He has so wonderfully made a way for us in Spain thus far,
that I cannot doubt he will also open a plain path for our departure from it.
I feel calm and resigned, trusting in him.
Blessed be his holy name, who is a sure and strong refuge, under every difficulty.

I continued very unwell till this afternoon, when the fever in degree subsided.
At that time some very interesting persons came to see us,
whom we had not been with before; several had just arrived from a distance.
One of them is a young priest, who is fully convinced, as he said,
that the church of Rome is Babylon the great, and that the Pope is antichrist; yet,
added he, "`The real antichrist is not a visible being,
but the prince of darkness that rules over the children of disobedience.`"
Another is an aged man, eminent in his profession as a lawyer.
He also has, for many years, been convinced of the great errors in the church of Rome,
and the great evils that have resulted from their many and gross superstitions.
He also laments over the depravity and wickedness of many of the priests and monks.
Some time since, he wrote boldly to the Pope, to the Archbishop of Toledo,
and to the King; to the latter he represented how many of his best subjects were,
under his name, brought into cruel sufferings, that others were put to death,
and multitudes were shut up in noisome prisons.
Upon which that wicked and cruel man who was then the King`'s Prime Minister,
sent orders to have him arrested,
and that sentence should be immediately passed upon him; but the Judge,
who was his intimate friend, devised means to save his life,
by representing him to be a madman in the highest degree;
he then sent him into one of the cells that I have described, among the insane,
and extended kind treatment to him there.
He remained six months in that cell, and thus narrowly escaped death.
He was released on the change in the Government;
and now that wicked minister is himself immured.
This aged man appears to be well acquainted with several of our Christian testimonies,
especially as regards the influences of the Spirit;
hence his views respecting Divine worship and the ministry are pretty clear.
He knows a number of persons convinced of the same important truths,
who reside in various parts of Spain, but have mostly retired to lonely places,
on account of the great persecution that lately prevailed, when many of his friends,
spiritually minded persons, perished.
Some died under the torments inflicted;--thus very
few now remain to associate in religious fellowship,
in or near Valencia.
Gross darkness prevails, both among priests, monks and people.
We told those pious individuals who came to see us,
that the Lord is very near to those that fear him;
that a book of remembrance is written for those that think on his name;
that though they should be so few as two or three only engaged in waiting upon him,
he has promised to be in the midst of them.
As we were thus proceeding to encourage them, the dear old man,
with brightened countenance and glistening eyes, said, "`O yes,
it is a blessed privilege for the two or three, or even the poor solitary one,
to wait upon the Lord, and to obtain access to his Divine presence.`"
This he had been very graciously permitted to realize, while shut up in his dark cell,
and treated by some of his keepers as a madman.
They left us apparently comforted by this visit.
We, on our part, felt them very near to us.
The young priest, if he keeps his place in the Truth, as he is now convinced of it,
will probably have much to suffer; we encouraged him,
should a day of trial come upon him, to remember that the Lord is a refuge and strength,
a present help in every day of trouble.

Soon after these had left us, several others came in to bid us, probably,
a final farewell; among these were the French Consul, the physician,
our kind interpreter, and several others;
we had with them a short season of spiritual refreshment; we commended them to God,
and the word of his grace, which is able to build us up,
and to give us an inheritance among all them that are sanctified.

The physician told us that, about a year since, he was sent for into a nunnery, to visit,
as a medical man, a female who was ill;
as he stood by her she appeared to wish to speak to him;
but not to be able to raise her voice above a whisper; he put his ear to her mouth;
she placed a paper in his hands, unobserved by those that were near,
and whispered in his ear, "`I have no bodily disease, but distress of mind.`"
The contents of the paper were to entreat him to devise
some means to rescue her from that horrible place.
She was a young woman of fortune in Italy, and, after her father`'s decease,
her brother contrived to get possession of her estate,
and through the agency of some priests,
to have her removed to Spain and shut up in this convent.
Very soon after this, and before anything could be done for her rescue,
the physician was himself imprisoned,
and he has not been able to hear anything of her since.

--
