== Chapter LXIII.

Fourth Visit to Europe

Concluding Services in England, Scotland,
and Ireland--Voyage to America and Safe Arrival at Home

After his peaceful return from the European Continent,
Stephen Grellet was not long before he resumed his
Christian labours among his friends in England.
He visited the meetings in and about London, as far as Buckinghamshire,
which kept him closely occupied till near the time of the Yearly Meeting.
In connection with this he writes:

A Conference, largely attended by Friends from various parts of the nation,
was in session for some time before the Yearly Meeting.
Friends were closely engaged in revising the Discipline.
It was to me an instructive time;
great harmony and solidity prevailed among Friends
while proceeding on this important service.

During the Yearly Meeting, and also in the Meetings for Ministers and Elders,
a deep travail of spirit prevailed.
Many dear friends are engaged to sink to the foundation, Christ Jesus, the Rock of Ages.
Thus, though this Yearly Meeting has been a time of much exercise,
it has also been a season of renewal of strength, attended with fervent desire that,
by the Lord`'s assisting grace,
we may so abide in watchfulness and prayer as to be preserved from an insidious enemy,
and that those over whom he spreads his net may make their escape,
as a bird from the snare of the fowler.

From London I went pretty directly into Yorkshire,
accompanied by my beloved and valuable friend, George Stacey.
I was at nearly all the meetings composing that and Durham Quarterly Meetings.
My service from place to place appears to be to draw the attention of Friends,
and of our dear young people especially, to the foundation of the prophets and apostles,
on which our worthy ancient Friends did build--"`Christ Jesus, the same yesterday,
today, and forever.`"
It is on him that our Christian testimonies are grounded.
The Spirit of Truth in our own hearts,
and the Holy Scriptures that have been given by inspiration of God,
bear a two-fold evidence of it.
We are therefore very willing that our religious principles
should be closely examined in the light of Truth,
and compared with the doctrine of Christ and his apostles.
When speaking of the principles or testimonies that we hold, as a religious Society,
we are apt to use the language, our principles, testimonies, etc.;
but we do not mean that peculiar principles or testimonies are given to us as a people,
which are not also given to all who desire to follow
the Lord Jesus in sincerity and truth,
in all the ways of his requirings; we only mean that,
acknowledging the rectitude of those principles, we feel it our duty,
as a religious body,
to endeavour to walk in accordance with them beyond
what many others appear to think needful.
I am fully persuaded that,
were all Christian professors sufficiently actuated by the Spirit of Christ,
all would be led by the one Spirit into the same Truth;
we should be but one body of Christians.
I am also comforted in believing that there are individuals in various nations,
and among different denominations of Christian professors,
who are joined together in the oneness of the Spirit, in Christ their Lord and Saviour.
It is my concern for the members of our religious Society,
that they may all be fully convinced of the rectitude of our Christian profession,
and be faithful in walking consistently therewith.
The Quarterly Meetings for Yorkshire and Durham were seasons
when the Lord`'s power was felt to be over us.
Many hearts were contrited under a solemn sense of it.

We came into Scotland on the 2nd of the Eighth month,
and visited Friends in that nation as far as Aberdeen and Kinmuck,
having also some large and satisfactory meetings among other religious denominations.
We returned by way of Glasgow.
There dear Peter Bedford came, to join me in my contemplated visit through Ireland.
G+++.+++ Stacey left us after a large meeting in that city, where many make a high profession;
would to God that many pomegranates were annexed to the sounding of the many bells;
how admirably were these coupled together in the priest`'s garments,
as ordered by the Lord under the Mosaic dispensation!

Accompanied now by Peter Bedford,
we crossed from Greenock to Ireland on the 24th of Eighth month.
We had a short but very stormy passage;
another steamer that left Scotland about the same time, has not been heard of.
It is apprehended that she has sunk with her numerous passengers, most of whom,
we are told, were Irish labourers returning from their harvest work in England.
How often has my life been preserved amidst imminent dangers!
May a life thus lengthened be, with an increase of faithfulness,
devoted to the service of my great and gracious Master!

We had two large and satisfactory meetings at Belfast; from there we went northward,
as far as Ballimoney, and returned by way of Gracehill,
where we had a baptizing meeting with the Moravians in their meetinghouse.
There is among that people a precious company who love the Lord Jesus Christ,
and who are as salt to those among whom they move.

The Quarterly Meeting for the province of Ulster was held at Grange.
I felt deeply for Friends there,
and for the people who collected at a meeting for worship;
many are descendants of parents who were members of our religious Society,
but from one cause or other have lost their membership;
they and their poor children are scattered, like sheep that have no shepherd;
they belong to no religious denomination, and appear to grow up in great ignorance.
I lamented deeply over them, seeing how numerous they are; I, nevertheless,
believe that the crook of the Redeemer`'s love is extended towards them,
to gather them within His fold.
I trust also that my sufferings and labours for that class will not be lost;
several dear and valuable Friends appear to have
their hearts enlarged in Christian love towards them,
and means are devising to extend suitable care to them.^
footnote:[The school at Brookfield, established in 1836 for the class here alluded to,
has been eminently useful and prosperous.]

On our way to Dublin, we stopped at Cootehill, and had two meetings there;
some serious disturbances have of late taken place in that part of the country,
between the Roman Catholics and the Protestants,
which have been attended with effusion of blood, particularly in this place.
Understanding that the Romish Bishop, James Brown, has acted with great moderation,
endeavouring to promote peace and quietness, I had a wish to see him.
I find him to be a mild and liberal-minded man;
he says that by cultivating good will and love towards all,
we may hope to see the mist of superstition dispersed,
whereas a contrary disposition tends only to increase the darkness and its deeds.
He hopes that if the various religious professors
will cultivate Christian love towards one another,
prejudice and animosity will soon be dispelled by the arising of Gospel light.
He had heard of my visit to Rome, and to the Pope,
and felt much interest in the short account I gave him of it.

From Dublin I attended all the meetings of Friends,
and had also several meetings with the inhabitants generally as far as Moate,
where the Quarterly Meeting for that province was held.
We went from there into Connaught;
the greater part of the people there are Roman Catholics; we had some very quiet,
solemn meetings among them.
At one of these the whole meeting was broken into tears.

We proceeded after that for Limerick and Cork.
We were comforted with Friends in those parts,
and the Lord`'s power was revealed in several large
meetings attended by many of the Roman Catholics,
to the contriting of many spirits; for the Lord reached their hearts.
The Quarterly Mecting for Munster province was held at Waterford.
Many Friends were comforted together;
a living travail prevailed in conducting the affairs of the church,
with a concern that a watchful care may be exercised,
that none of the doctrines afloat in various parts of the land,
may prevail over any of their members;--some of those
who have given reason to fear on this account,
were laboured with in much tenderness and Gospel love.

Eleventh month, 1st. We were at Kilnock, with my dear friend Mary James Lecky,
and her mother.
It was at their house that dear Jonathan Taylor,
with whom I crossed the sea on coming to this land, died.
They gave us some interesting accounts of his illness; he died in the faith of Jesus;
his sun went down in brightness.

After taking several meetings,
we came back to Dublin on the 6th. I had some more service among Friends there,
and also with the Moravians, and in a meeting with the inhabitants.

Feeling now released for the present from this nation,
our faces are turned back towards England.
We have had in Ireland many public meetings, and have been at all the meetings of Friends.
I have not had so much solid satisfaction in any of my preceding
visits to this nation as at this time.
There is a growth in the Truth among Friends generally;
and a very encouraging prospect respecting the dear young people.
Some are under the baptizing power of Christ,
and have lately given evidence that they are decided followers of the Lord Jesus.
Though my mind is comforted with Friends here, generally, yet I rejoice with trembling,
for some I am aware stand on dangerous ground;
zeal without knowledge has often done much harm; so it may be with some,
for whom I have both felt and suffered deeply.

On arriving again in England, he writes:

Liverpool.
Eleventh month,
11th. Here I am once more at my long beloved and kind friend Isaac Hadwen`'s,
who is full of love and greenness in his old age.
He proposes to be my companion for a while in the north of this nation.

We went pretty direct towards Westmoreland, where I had close and exercising services.
We then went into Cumberland,
and had some large and satisfactory meetings among Friends and others.
From Carlisle we turned towards Appleby, where my dear aged friend Isaac Hadwen left me,
and I proceeded through the dales of Westmoreland, and Yorkshire,
till I came to Bradford.
There is in those dales a tender people.
Much Christian simplicity is to be seen.
Some of the meetings were large, the people coming from considerable distances.
The baptizing power of Truth prevailed, in various places, to an eminent degree.
I was refreshed in body and spirit, at my beloved friends John and Mary Hustler`'s;
and the meetings I had at Bradford were graciously owned by the Lord`'s presence.

On the 16th of First month, 1834, I came to the Quarterly Meeting of Lancashire,
held at Preston.
Very mingled were my feelings there, and deep was my soul`'s travail.
I laboured in much affection with some of them.
This was also my line of service at Manchester, and in several other places.
I was nevertheless comforted with many dear friends and promising young people,
who are not ashamed to confess Christ before men,
and whose attachment to sound Christian principles is strengthened in this day of trial.

I went from there among the potteries and salt works as far as Nantwich; then into Wales,
Leicester and Warwickshire, and so on to Bristol.
I have been repeatedly brought into deep exercise in that city;
but my mouth has generally been sealed, no way opening to give utterance to what I felt;
now the Lord has been pleased to set an open door before me,
and enabled me in several large meetings to proclaim his
Divine counsel to the relief of my exercised mind.

I turned from there into Gloucestershire, Oxfordshire, Huntingdonshire, Cambridgeshire,
Suffolk, etc., and came back to London on the 20th of Third month;
having been very closely engaged these months past, generally holding two meetings a day.
My concern has of late been principally for the members
of the religious Society to which I belong,
that those who have known the blessed Truth may keep under the power of it,
watching unto prayer against every device and stratagem of the adversary.
My desire is great also for the dear young people that they may
be thoroughly acquainted with the nature of our Christian testimonies,
and encouraged with faithfulness to maintain them.
I am pleased to find that many of them are frequent
in the perusal of our ancient Friends`' writings,
comparing the clear testimony to the Truth set forth in them with the Holy Scriptures,
so that their faith is thereby confirmed.
The accounts of the sufferings of our early Friends in support of the blessed Truth,
and the gracious dealings of the Lord with them,
both at the time of their convincement and amidst their various labours in the Gospel,
are very interesting and instructive.
In many places it has been much laid upon me to draw the attention of Friends to Christ,
the author and finisher of our faith; preaching Him in all his Divine attributes;
what he has done for us without us, by the atoning sacrifice of himself for our sins,
and what, through his grace and good Spirit, he would do in and for us,
if we were obedient to his influence.
There are those who, with gratitude and praise,
can bear living testimony to what he has already
done for them by the efficacy of his Truth.

I was greatly comforted in being again with my beloved friend, William Allen;
but I was not long permitted to have his dear company in and about London.
My mind continuing under great exercise for Friends in various parts of this nation,
I felt it to be my religious duty to be resigned again to
visit a considerable number of their Quarterly Meetings.
Accordingly, accompanied by dear G. Stacey, I left London the 28th of Third month,
and attended the Quarterly Meeting at York, that for Durham at Darlington,
and that for Westmoreland at Kendal.
From there we travelled pretty directly to Bristol,
and then to the Quarterly Meeting at Exeter.
I was much exhausted with hard travelling and close exercise of mind,
but here the Lord healed his poor servant by the
lifting up of the light of his countenance upon me.
We had refreshing meetings; Friends were comforted together and encouraged.
After this I had meetings at Plymouth, Truro, Falmouth and other places in Cornwall.
From there I went to Worcester, to be at their Quarterly Meeting.
It was a solemn season.

We now went into Yorkshire and had two solemn meetings at Sheffield.
There I was again refreshed under the hospitable roof of my friends,
William Hargreaves and his valuable daughter, Lydia.
I can never forget their kind and tender care over
me when detained at their house about two years since,
after the accident, when my horse and gig had passed over me.

Proceeding to Liverpool I was met there by my beloved friend, William Allen,
and his niece, Lucy Bradshaw; they had come to accompany me to Dublin Yearly Meeting,
a further debt of love I had to pay to Friends of that nation.
At that Yearly Meeting the blessed Head of the Church favoured
us with many precious seasons when the refreshings from his Divine
presence distilled upon us like dew on the tender grass;
our cup, however, was not without mixture;
but Friends generally kept close to that Power which has
given them a living experience of the blessed Truth.
Joined by dear Allen I paid a relieving visit to the Women`'s Meeting;
that and some solemn opportunities among the men,
together with those in the Meetings for Divine Worship, have, by the Lord`'s help,
so relieved my mind from the deep exercise and concern
I had felt for Friends of this nation,
as to enable me, with reverent gratitude,
at the conclusion of this engagement now to say, "`Return to your rest, O my soul,
for the Lord has dealt bountifully with you.`"

London.
Fifth month, 9th. Accompanied by dear Allen, I crossed the channel on the 5th,
attended the meeting at Manchester yesterday, and arrived here today at noon,
with a grateful and peaceful mind.

I now attended several meetings in and about the city,
which I was thankful in being permitted to sit mostly in silence,
feeling as one that needed to be ministered to; a great weight is upon me,
as the Yearly meeting here is drawing near.

It was a time of unsettlement in regard to interesting and
important questions of a doctrinal and practical character.
Stephen Grellet deeply sympathized with his friends in their trials;
but his well disciplined mind could not be insensible how unsafe
it is to dwell upon the failings and weaknesses of the Church,
without at the same time keeping in view the resources
and goodness of the Great Head of it.
He well knew that in the exercise of a humble faith
it is needful to look not on the disease only,
but also on the greatness of the remedy, lest, in exclusively dwelling upon the former,
we should promote the designs of the great enemy,
by distrustfully falling into "`a repining and censorious spirit,
equally injurious to ourselves and offensive to our heavenly Father?`"^
footnote:[Upham.]
While, therefore, earnestly concerned that, both in principle and in practice,
they might be preserved faithful to Christ, and the leadings of the Holy Spirit,
according to the Scriptures,--keeping the foundation firm,
and the superstructure unharmed, his labours were to the comfort of his brethren.

Fifth month, 18th. The Yearly Meeting of Ministers and Elders beginning tomorrow,
many Friends have already arrived, so that all their meetinghouses were crowded today.
I attended Devonshire House in the morning and Southwark in the afternoon.
I was brought into deep exercise in these meetings;
it was laid upon me to set forth and exalt the blessedness
and the glory of the dispensation of the Gospel,
to describe its purity, and to entreat every one to come and live under its power.
What are all types and shadows compared to it?
In these there is no substance or life; they can only point to Him, who is the Life.
I contrasted the nature of real worship in spirit and in truth,
with that worship which stands in outward ordinances, forms and ceremonies.
I distinguished also between the outward rituals or observances of baptism and the supper,
and the Christian,
saving baptism and that meat which nourishes the soul unto eternal life.
I earnestly pressed upon all to be very watchful,
lest they should turn away from the eternal substance,
and follow after that which cannot satisfy the needs of the soul.

19th. The Meeting for Ministers and Elders had two sittings today.
Truth reigned over all, blessed be God forever!
I informed Friends that I apprehended myself now released by my
great and good Master from further Gospel service among them,
and in these nations,
and believed that I may be at liberty to return to America
soon after the conclusion of this Yearly Meeting.
Great solemnity spread over the meeting,
and many valuable Friends had testimonies to bear to the efficacy
of that Divine grace and power which have led me about,
instructed and kept me,
amidst the many exercises and perils that have attended my services in these nations;
others offered vocal prayer, thanksgiving and praise, to the Lord God Omnipotent,
through Jesus Christ our blessed Redeemer.
Friends separated a committee to prepare a returning certificate for me.

The Yearly Meeting continued its sittings till the 30th. We had many seasons
when our spirits were animated and encouraged to trust in the Lord forevermore;
for when some of us were fainting under the load of exercise and fear,
trembling like Eli for the ark of the testimony of God,
the shout of the King eternal and immortal was heard in our camp,
and the name of the Lord was proclaimed.
He is the saving help and strength of his people.
But we rejoice with trembling, "`for our enemies are lively and strong.`"
My deep solicitude and close exercise as I travelled over this nation,
especially of late, were not without a cause.
I have pleaded with all Christian affection and tenderness in private,
and laboured also very fervently in some of the meetings,
particularly at the close of the Select Yearly Meeting this evening,
which was a very solemn season.
Parting with my friends is deeply affecting to me,
for they are very dear to me in the Lord;
close is the bond of fellowship that unites many of us.
I have a lively hope that though we may never see one another again in mutability,
yet our spirits being united by that blessed bond of Truth, which is indissoluble,
we may be permitted, through the Divine mercy and love,
to be joined together before the throne of God and
the Lamb to celebrate his praise forever.
The parting between dear Allen and myself has been sweet and solemn;
we were very reverently prostrated together before the Lord.

There is something very touching in this simple record of the faithful minister of Christ,
towards the conclusion of his Gospel mission in England and in Europe;
and the interest can scarcely fail to be deepened
by turning to the memoirs of William Allen,
and finding how he "`went with dear Stephen Grellet to Devonshire House,
during the Yearly Meeting,
as it was the last meeting for worship he was likely to attend;
when Stephen had an opportunity fully to relieve his mind,
and his communication was very remarkable,
rising brighter and brighter towards the close;
Elizabeth J. Fry followed in supplication,
and there was a very solemn feeling over the meeting.`"
And afterwards, in the concluding sitting of the Yearly Meeting,
"`when the business was over, Stephen rose and delivered a parting exhortation,
which was remarkably solemn and impressive; to some he addressed the language of warning,
and he had sweet encouragement for the aged, and for tender, visited minds;
and in the silence at the close, there was a deep feeling of solemnity,`" and,
the Great Head of the Church having granted some precious seasons,
was pleased to confirm the faith of his servants in him.
And it is added, sorrowfully, respecting the Meeting for Ministers and Elders,
"`Dear Stephen Grellet was with us for the last time;
he spoke in a remarkable manner,--it was indeed a faithful communication.
Several Friends were with us at our lodgings,
and before we separated we felt the drawings of the Father`'s love, and,
after a time of silence, Stephen knelt in supplication.
It was a favoured opportunity.
We afterwards walked to Bishopsgate Street, to John Hustler`'s lodgings,
and then I took a final leave of him.`"^
footnote:[Life of William Allen.--Vol.
iii, pp.
173 and 174.]

Stephen Grellet proceeded towards Liverpool the same evening.

Accompanied by my beloved friends, John and Mary Hustler, who took me in their carriage,
I left London on Seventh-day evening and came to Luton that night,
attended their meeting the next day, and reached Bradford on the 3rd of Sixth month; and,
still accompanied by the same dear friends, I came to Liverpool.

From there he writes:

To William Allen

My beloved Friend,

Liverpool, 6th mo., 7th, 1834.

I have no letter from my beloved wife, as I had fondly expected.
This is a further opportunity for my will to bow down in submission.
To have heard that my beloved wife and daughter were better
would have been a great consolation previous to my embarkation.
The Pocahontas is a fine ship,--very commodious; she is expected to sail tomorrow morning.
I have been pleased in seeing once more our dear friends Joseph Bewley, and Jacob Green.
They left for Dublin last night.
Abigail Dockray is here at Isaac Hadwen`'s, with J. and M. Hustler.
So many Friends come to take leave of me that these
many partings are rather wearing to nature,
yet the dear Master has granted us some very tendering, solemn seasons.
This morning we breakfasted with Thomas and Elizabeth Robson;
she expects to leave this evening for Dublin.

My mind is preserved in much calmness and sweetness on my approaching departure
from a land where strong Gospel ties attach me to many dear Friends,
towards whom I have seldom, if ever,
felt so much of what it is through the baptism of the one Spirit to become one body.
I fully believe that it is in the Lord`'s pointings that I leave you,
and I am thankful to be favoured, on this my last step in this land,
to have the same evidence of my dear Master`'s Divine guidance,
as he has so mercifully condescended to grant me
in moving about from one nation to another people,
and preserving his very poor, dependent servant.
But, my dear brother, though leaving you,
my spirit continues strongly to partake of your tribulations
and baptisms for the blessed Truth`'s sake.
I have greatly joyed in your joys,--now I cannot but share deeply in your sorrows.

My love to my beloved friends at Stoke Newington; bid them be of good cheer,
for the Lord is with you; He will reign;
His blessed Truth must be exalted over all.--My love is strong to you;
I think it is towards you like that of David and Jonathan.

Eleven o`'clock.
The ship is to sail tomorrow morning at nine.
This evening I have your last and very precious token of love, your dear letter.
We have had a very solemn parting season at Thomas Thompson`'s with many Friends.
Farewell in much love, my very dear friends; my heart is very closely bound to you,
and to our dear friends among you who stand steadfast in the Gospel of the dear Saviour.

Your warmly attached friend,

Stephen Grellet.

Next morning, the eighth of Sixth month, 1834, he embarked,
on board the packet-ship Pocahontas, Captain West, for Philadelphia.
During the voyage he had an opportunity, by a passing vessel,
of sending a letter he had begun.

To William Allen

On board the Pocahontas, 6th mo., 13th, 1834.

My much beloved Friend,

I closed my last farewell from British shores to you, your precious wife,
your dear nieces, and our friends of Stoke Newington, at Liverpool.
I came on board on First-day as expected.
I was summoned at nine o`'clock a.m.,
yet we did not clear out of the docks till about twelve,
when a steamer towed us out and continued with us till about four,
p.m. Several Friends came on board,
but it being meeting time they could not continue long.
My beloved friends John and Mary Hustler,
and David and Abigail Dockray continued on the dock side till I could see them no more.
You well knowest, my dear brother,
the poignancy of the feelings attending such parting,--a
parting which is the more severely felt,
as it now includes in one great mass, all that for weeks I have passed through in detail,
from one dear friend and then from another--and yet a separation which
leaves me very closely bound to my dear friends now left behind;
for the bond of the fellowship of the Spirit that unites us is such,
that your tribulations for the Gospel`'s sake must continue
to be my tribulations,--and your joys in the Lord my joys.
It will be very interesting to me to hear from your pen, from time to time,
of what transpires among you, for these are eventful times.
May our dear Friends be preserved under the guidance of the Divine Spirit,
for it is that of Truth, which will triumph gloriously over all.

We have made very slow progress;
the wind ever since we left Liverpool has been contrary or calm.
We have cruised from the coast of Wales to that of Ireland, backwards and forwards.
We are now only opposite to the Bristol Channel.
Sometimes we have had heavy squalls and rough weather.
Our cabin-passengers are seven, besides the captain and three females in their cabin,
all very civil.
Most of them have been and are yet sick.
I have had my share, but I get on better than I expected.
We have a good ship; very clean.
We have many steerage-passengers, but, owing to the weather,
I have as yet seen but few of them.

24th. Except part of two days we continue to have head winds, and frequent rain;
the sea consequently is much agitated by the squalls; but I enjoy good health.
I have had very little sickness; besides, my mind,
though mostly clothed with great poverty, is mercifully preserved in calmness;
and a sweet evidence that I am here in my right place, and,
that under my blessed Master`'s guidance I have left the
field of Gospel labour in your land in the right time.
On closely inspecting my steppings about among the nations,
and in your land among our Society, I have, with reverent gratitude and admiration,
to mark the Lord`'s very gracious dealings towards his poor servant;
surely my hand may sooner forget her cunning,
and my tongue cleave to the roof of my mouth, than for me to forget the safety,
the blessedness of the leadings of the Lord`'s Spirit,
or ever to cease to testify thereof as a part,--a very important
part of the glorious dispensation of the Gospel.
O what a blessed hope is set before us! wonderful to contemplate! to be called
the sons of God! a hope set before all those that are led by his Holy Spirit.
Let us not cease, my beloved brother, to watch continually,
with all prayer and supplication.
O that all my movements,
in my feeble attempts especially to serve the dear Master
in the work of the Gospel or the service of the Church,
may be under this Divine influence!

The last two First-days I have had meetings with the people on the deck; the cabin,
though very spacious, would not contain all,--about one hundred, including children.
We can have but few seats for the women; the men mostly have to stand,
and the sea being in great commotion, that is not a very easy thing; yet,
as the dear Master very compassionately condescends to our low estate, even then,
amidst outward noise, by the wind and the sea,
inward calmness and stillness have been known, and the Gospel has been preached.
Last First-day, after the meeting on deck,
in the little meeting I held in my private cabin, Thomas Jacob^
footnote:[A young Friend from Ireland, his fellow-passenger.]
daily joining me, we had a precious time.
You, my beloved friends, who were then engaged before the Lord, were, in spirit,
very near.
I believe there were some of you with whom my soul united in offering,
through our blessed Redeemer, adoration and praise,
and supplication also for one another.

I hope I may receive a letter from you soon after my arrival at home,
and that you will not put off writing till you hast heard from me.
You know the power of strong affection,
and my unavoidable interest in all that affects you.
To hear especially of your precious wife will much interest me.
I should rejoice to hear that, if so be the good pleasure of her dear Master,
she regain her former strength.
We may, however, very safely commit our all to Him.
Behold we are in His hands!
I can hardly understand, myself, now that my face is turned towards America, why,
when looking towards my beloved wife and daughter,
the uniform word of caution is to keep them offered up to the Lord.
Is it to prepare me for what may yet be unfolded,
or rather that now returning with a mind released from heavy Gospel bonds,
for the prosecution of which service my dear wife and child,
my life and my all have been resigned to the Divine will,
I should not attempt to loose from the horns of the
altar of offering any part of the sacrifice?
The Lord has very graciously released me from the field of Gospel labour,
and now I reverently wait to see what he will further do for his great name,
and for his poor servant.

Seventh month, 3rd. Last First-day we had a precious meeting on deck.
The weather had been stormy in the night.
The waves in the morning often dashed over the ship; but about nine a.m.,
it began to abate, and about eleven we had a comparative calm.
How great is the Lord`'s condescension, in thus permitting that worship,
prayer and intercession, adoration and praise shall be offered unto him,
on the tossing deep, under the vast canopy of heaven, as well as on dry land,
and in places particularly set apart for the solemn act!

The fine weather continued till Second-day evening,
when strong contrary wind from the south-west began to blow,
and then passed to the north-west.
It continued vehement till yesterday afternoon; it was a tempest indeed;
during one night the ship had to lay to.
The scene was truly grand and awful; it was such as you would have enjoyed;
for the wonders of the Lord`'s power were seen.
But, above all, I must magnify his great mercy towards his poor servant;
for I have during that period enjoyed more of the consolations
of his Divine presence and the comforts of his Spirit,
than for a long time past.
Surely, my friend, we follow not cunningly devised fables when,
according to the influence and guidance of the Holy Spirit, we follow Christ.
During this passage, during these last days more than ever,
is my faith confirmed in the Truth, and in the efficacy of it.
We have now a nice wind.
The proud waves have come down,
and we glide on their smooth surface with excellent speed towards our desired port.

7th. There is a ship near, and it being nearly calm,
the captain proposes sending a boat to her.
So I hastily send you these lines.
We are in Lat.
40, Long.
56.

In much love to you all,

Your nearly attached,

S+++.+++ Grellet.

On his arrival at home,
he makes the concluding record respecting this his fourth and last visit to Europe.

We had a long but good passage, and arrived at Philadelphia the 21st of Seventh month.
That afternoon I went to Burlington, and met my beloved wife and daughter.
We united together in ascribing thanksgiving and praise to the Lord, our gracious helper,
who has been with us during our long separation,
and preserved us to this day--monuments of his Divine mercy.
I travelled during this last European journey above twenty-eight thousand miles.
We had many passengers both in the cabin and in the steerage,
with whom and the ship`'s crew, I had several meetings during the voyage.
These were held mostly on deck, when the weather allowed of it,
where all on board could be better accommodated than below in the cabin.
The Lord very graciously owned some of these meetings,
and some other religious opportunities I had with the steerage passengers and the sailors.
I had many seasons of retirement in my private room,
my soul being frequently poured forth in prayer unto God,
for the people of the nations I have visited,
and also for the members of the religious Society of which I am a member,
both in England and America.
They are a people very dear to me;
strong are the bonds of Christian fellowship that unite me to many of them.
There is among them a very goodly company to whom the Truth is precious,
and who by the power of the Truth and their faithfulness to it,
are made well qualified instruments in the Lord`'s
hand to advocate the blessed cause of the Redeemer.
I am permitted also to have a cheering hope that the departure of some
from the purity and simplicity of our Christian profession is,
through the Lord`'s blessing,
made a means of bringing many others deeper to the root of religion,
so as to become more firmly established in the faith of Christ,
and the knowledge of those principles and doctrines on which our primitive Friends built,
and which they did not flinch from maintaining before the world,
though the loss of their property, imprisonment and death,
were the consequence of their faithfulness.
To my great comfort I have seen clear evidence of
this manifested by some dear young Friends.
