== Chapter LXIV.

[.chapter-synopsis]
* Religious Visit to Ohio, Indiana, Baltimore and North Carolina Yearly Meetings, etc.
* Extracts from Letters

Stephen Grellet had now arrived at the close of his
varied "`missionary labours`" in distant nations.
Rescued by the power of the Spirit from the meshes of infidelity, he had been enabled,
in the vigour of early manhood, to enter in by Christ, the door, into the sheepfold;
rejoicing in the salvation of God, he had gone in and out and found pasture;
dedicating himself unreservedly to the service of the Redeemer,
he had known that when He, the good shepherd who laid down his life for the sheep,
puts forth his own sheep, he goes before them, and the sheep follow him;
for they know his voice.
That voice he had heard thirty-six years before, when, as he thought,
he was about to breathe his last,
and seemed already to have gained a foot-hold in the heavenly places,
and saw and felt things that cannot be written; it proclaimed the word,
"`You shall not die but live--your work is not yet
done,`" when distant parts of the earth,
over seas and lands, were set before him,
where he would have to labour in the service of the Gospel of Christ.
Under a remarkable coincidence between the openings
of Providence and the leadings of the Holy Spirit,
he had for many years been diligently occupied in a long series of religious engagements,
which,
in accordance with the clear intimation given him in the early part of his ministry,
had been gradually unfolded as the requirements of his Lord,
and he had now been brought back in peace from his last visit to Europe.
Saviour`'s words, "`My sheep hear my voice, and I know them, and they follow me;
and I give unto them eternal life, and they shall never perish,
neither shall any pluck them out of my hand,`" had been
beautifully illustrated and confirmed in his experience.
Had he followed a delusive guide, or a true one less faithfully, the issues of his life,
thus far, must have been very different to what it has been seen that they were.
He would not have so distinctly borne upon him "`the marks of the
Lord Jesus;`" he could not have given so many proofs of the reality
of the direct influence and guidance of the Holy Spirit,
and of the safety and blessedness of following his leadings in the path of holiness
and duty-while resting upon Christ alone as the foundation of his faith and hope.
Henceforward,
returned to the bosom of his own beloved family and a large circle of friends,
it was in the land of his adoption that, during the residue of his years,
he walked humbly with his God,
and exhibited a bright example of Christian simplicity and faithfulness.

[.embedded-content-document]
--

"`I continued pretty much at home,`" he writes,
"`except attending some of the neighbouring Yearly Meetings, till the year 1837,
when I went to Ohio and Indiana, attended those two Yearly Meetings,
and a number of the meetings composing them.
I had sweet peace in that engagement.
Many of the meetings I had in those States were attended by a considerable
number of those who have separated from us.
I was thus introduced into close exercise and labour,
but in some places a hope was given that with many of this class,
particularly of the young people,
an earnest inquiry after the Truth was the motive for attending these meetings.
May the Lord cause the light of his glorious Gospel to shine upon them!

In the year 1839, being accompanied by John Elliot,
I attended the Yearly Meeting for North Carolina,
and visited the meetings constituting several of their Quarterly Meetings,
and had also several meetings in Virginia.`"

--

Thus briefly he sums up the account of several years
immediately succeeding his return from Europe.
A few extracts from his letters will throw a little more light upon that period.

[.embedded-content-document.letter]
--

[.letter-heading]
To George Stacey

[.signed-section-context-open]
Burlington, 8th mo., 11th, 1834.

[.salutation]
My dear friend,

My last, written at sea and concluded after my arrival in this Western Hemisphere,
was sent last month.
I have already received testimonials of the kind
remembrance of some of my dear English friends.
I have a letter from William Allen, and one from Mary Hustler.

I was much grieved on coming to this land,
to find that the excitement we had feared in this country,
from the unwise measures and intemperate speeches of some of the
friends of the speedy abolition of slavery had actually taken place.
Serious riots had occurred in New York;--some blood had been shed, and property destroyed.
Many of the sufferers had been the innocent people of colour; but, above all,
what is greatly to be regretted is, that the cause which we have so justly at heart,
to see an end put to the wrongs and cruelties exercised
towards this portion of our fellow men,
equal objects of redeeming love and mercy with us, may thereby be greatly retarded,
and the yoke of bondage rendered heavier in the slave States.

It is to the credit of the magistrates that they exerted
themselves to repress the work of abuse and destruction;
it pains me much to see that the result of this renders the friends
of the black people more timid in pleading their cause.
May the power of Gospel love and the prevalence of justice, truth and equity,
rise triumphantly over all opposition!

My sister, S. R. S., has a very interesting coloured girl, just brought from Africa.
She appears to be ten or eleven years of age, very handsome for her colour,
and engaging in her manners.
She is thought to be a child of one of their chiefs, but she cannot yet speak English,
not even so as to tell her nation and the manner in which she was taken.
A captain of a ship lately arrived from Africa brought her, and, as he died on arriving,
no information can be obtained from that quarter.
The poor child, however, has been branded on the shoulder,
and such a dread had she that the same cruelty might be repeated, that,
on my sister having her un-dressed to put on fresh clothing, she screamed greatly;
now she seems as if she would hardly be out of sight of my sister or niece.
She has come a few times to meeting.
Once while my sister was on her knees, engaged in the solemn act of prayer,
large drops of tears descended her cheeks.
She is a true child of nature in her actions, but evinces affection and gratitude.
What a favour that she has not fallen into the hands of a slaveholder.

Our Monthly Meeting was on the 4th instant, when I returned my certificate.
The Lord`'s presence was with us, and his Divine, baptizing power was felt,
so that many minds were refreshed and comforted together.
Friends, very generally, gave me a hearty welcome home again.
I feel also, on my part, very grateful to my blessed Lord and Master,
for having brought me back again in the midst of them, with the evidence that,
as he led me away to visit you and the nations near you,
and in his love and mercy helped and preserved me in his service, so, in the same,
he has in the right time brought me back in safety.

Poverty is my clothing.
My station in great measure is with Mordecai at the gate;
but it is the gate of the King eternal, the holy and blessed Redeemer.
I trust that I may not be thought to assume too much, by saying that at this gate,
in that stripped state, in that poverty, I am permitted through adorable mercy,
to sit with great delight.
It is an unspeakable favour that I am now permitted to mend my own net; but,
during this private, personal enjoyment, my heart is not straitened,
but as much enlarged as ever in love, Gospel love, towards my friends and others,
near and afar off.
Sometimes I covet that such as have allowed little
pebbles to stand in the way of this pure stream,
might feel how sweetly it flows from my heart towards them.

The spirit of prayer is sweet; it proceeds from the ocean of pure love;
mercy gives access to it; it knows no bounds; under this sense I salute all my friends;
my dear wife cordially unites in this salutation.
We hear that the cholera has made its appearance in New York;
the day before yesterday there were ten new cases, some are of the malignant kind.
When the Lord`'s judgments are in the earth, may the inhabitants learn righteousness!
How precious the evidence that we are in his hands in temporals and spirituals;
therefore, with perfect trust in him, in peace we may be permitted to possess our souls;
may this abound more and more with us all.
Tell all my friends I am well,
and that in peaceful poverty I enjoy many blessings in my dear Master`'s presence.

[.signed-section-closing]
With very near brotherly love,

[.signed-section-closing]
Your nearly attached friend,

[.signed-section-signature]
Stephen Grellet.

--

In the Tenth month he again writes to G. S.,
and after speaking with much interest of Daniel Wheeler, he adds:

[.embedded-content-document]
--

Should dear Tholuck be yet in England give him my affectionate salutation,
as to a fellow-disciple of our blessed Redeemer, the Lord Jesus Christ.
May his visit to England tend to strengthen the Divine life in him,
so that the fruits of that blessed Spirit, the quickening influence of which he has felt,
be brought forth plentifully.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To George Stacey

[.signed-section-context-open]
Burlington, 1st mo., 3rd, 1835.

I believe that the Lord God Omnipotent reigns, and that his power is over all;
all those that fear him, and whose confidence is placed in him,
well know him to be an unfailing refuge in time of trouble; yea, moreover, all things,
through his adorable power, will work together for their good.
You can not be surprised at my feeling deeply for and with you under your trials;
for Friends in your land are very dear to me,--to many of
you I am united in the close bond of the Gospel of Christ.
To your nation also I am much attached, for the Lord has a precious seed among you;
may no national commotion, nor any other thing,
hurt it! but only serve to detect the more fully the adversary under his every transformation,
and every effort to divide and scatter,
so that the fruits of the Spirit of Christ be abundantly
brought forth to his praise and glory.

I find things rather low among us since my return;
the heavy shaking that we have endured has not removed the dust of the earth (earthly-mindedness),
nor brought many nearer to Christ,
yet there are some precious young plants that have their springs in the Lord;
for them I feel very tenderly.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To William Allen

[.signed-section-context-open]
8th mo., 1st, 1835.

[.salutation]
My dear friend,

I have been in thoughtfulness that the closing lines
of my last may have left you anxious about me.
I was then in a feeble state, and I find that now, at my time of life,
when brought down I cannot rise up again as speedily as I did years past; I have,
however, gone twice to meeting, which I have felt a great favour,
having for weeks been deprived of that privilege;
but not of the favour of sitting in my beloved Master`'s presence in my chamber,
and sensibly feeling the refreshings which flow from the very fountain of life.
Blessed forever be his adorable and ever excellent name!
This sickness has been to me one of those favours granted in love and mercy,
which I trust will never be forgotten while the few
more sands in my glass shall continue to run.

Your dear letter of the Fifth month gives an account
very cheering of your late Yearly Meeting.
My heart on the occasion fully joins in the feeling of grateful acknowledgment
as made in your concluding minute of the Meeting of Ministers and Elders.
Surely there are precious,
convincing evidences that the Lord has not forsaken his people,
though they be greatly tried and proved.
Their very tribulations become sanctified to them, so that out of the depth of them,
honour, glory and praises are brought forth to his holy and blessed name.

--

The tenth of Eleventh month, 1835,
after commemorating a providential escape from a serious injury, S. Grellet writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia Hargreaves

May a life thus spared be with more faithfulness
devoted to Him who has seen fit to lengthen it.
I had had a prospect for some time to attend the late Yearly Meeting at Baltimore:
when the time came, the pain in my side nearly left me,
and I have returned quite clear of it;
thankful also in finding that my wife and daughter have
been cared for by our dear Lord during my absence.
When we number our mercies, how great is seen to be the multitude!

Many afflictions encompass our steps, yea, with David we may say,
"`From my youth up I have been afflicted,`" yet we cannot withhold the reverent
and grateful acknowledgment that "`the Lord`'s mercies are new every morning.`"
That Yearly Meeting is small,
it has greatly suffered by the spirit that has inflicted deep wounds in our Society;
yet there is a small interesting remnant left.
On my return I stopped at Wilmington, where I had a debt of love to pay.

There are young Friends among you for whom I feel a great interest.
Discouragement in these days may appear greater than in past years,
but surely the power of Omnipotence is not limited.
He can render them valiant in his blessed cause, and instruments in his Divine hand,
to exalt his great name.
Through the Lord`'s help, one little one may chase a thousand,
and two of these put ten thousand of the armies of the aliens to flight.

Many blessings attend us, of the least of which we are not worthy;
but all is of the Lord`'s mercy! even from that pure stream
which it would be great ingratitude in me not to acknowledge;
and with David I can say,
"`Goodness and mercy have followed me all the days of my life.`"

[.letter-heading]
To William Allen

[.signed-section-context-open]
12th mo., 22nd, 1835.

My spirit is bound up in close fellowship with yours, under your various tribulations.
Few days pass but that I share in your baptisms.
But, when tribulations abound, the consolations that are by Christ abound also.
A precious hope is at seasons set before us,
that even all things will eventually tend to the furtherance of the blessed Truth,
and render many of us more firmly established in the purity of it.

[.letter-heading]
To The Same

[.signed-section-context-open]
Burlington, 2nd mo., 9th, 1836.

I am concerned to hear that your health is so much impaired since we separated,
probably never to see one another`'s face again.
You hast endured so many conflicts and afflictions
that the outward frame must unavoidably share.
Yet, however it be,
to the Lord we must not flinch to offer up the strength of our body and spirit.
He can strengthen the inner and outer man,
even out of weakness to make us strong for whatsoever
work he may require of his poor servants.

Dear`'s health seems to be breaking down amidst the trials of the day.
We think we cannot spare any fellow-labourers,
but we must refrain from calling in question the Lord`'s dispensations, or saying,
"`what are you doing?`"
Many are the causes near and far calling us to mourning and lamentation,
our harps being hanged upon the willows; yet, my dear brother,
let us not forget our strong evidences that the Lord God Omnipotent reigns.
Very sweetly I feel the application of the promise to you,
which perhaps you may remember we had once, with much comfort,
set before us when in Spain.--"`Go your way till the end be, for you shall rest,
and stand in your lot at the end of the days.`"
Our end cannot be very distant,--let us be encouraged to keep in our ranks to
the end,--under all our sufferings let it be as becomes a servant of Christ,
for whose blessed Truth`'s sake are the chief trials attending us.

[.letter-heading]
To Lydia Hargreaves

[.signed-section-context-open]
Burlington, 3rd mo., 25th, 1836.

Our trials in this state of probation are numerous, but then,
under the sanctifying power of the Truth, they may tend to deepen us in faith,
and in that saving knowledge which imparts eternal life.
Excellent and encouraging is the description given by the Apostle;
"`tribulation works patience, patience experience, experience hope,
which makes not ashamed,`" the love of God being shed abroad in our hearts.
Thus the Christian believer has good reason to endeavour
to keep this blessed word of patience,
for the Lord has promised that he will keep him in the trying hour.

We are very far separated from our English friends,
but with many of them we are permitted to maintain very sweet fellowship of spirit; this,
(at times I rejoice in the hope,) is only a foretaste of that blessed fellowship
subsisting between purified spirits through the endless ages of eternity.

Farewell in the Lord.
Grace, mercy and peace from God the Father and our Lord Jesus Christ, be with you.

[.letter-heading]
To George Stacey

[.signed-section-context-open]
Burlington, 6th mo., 30th, 1836.

I mourn with the mourners among you,
and unite with all whose dwelling is often in the house of prayer.
There, my beloved friend, is a precious refuge.
There the sorrowful spirit is made to rejoice before the Lord,
and to receive encouragement also,
with patience to wait and see what he will do for his blessed name and cause`'s sake.

I believe the Lord has not forsaken us as a people,
and that this dispensation is designed to prove in the end a blessing,
by bringing us to greater consistency with our Christian profession.
Believing in the Spirit, let us also walk in the Spirit,
and then the fruits of the flesh will be done away.

--

In the Spring of 1837,
Stephen Grellet received the affecting intelligence of the decease of his "`beloved
and honoured mother,`" an event which took place on the 20th of Second month,
and was communicated to him in a letter from his brother Joseph, who,
with many of her descendants, was present on the peacefully solemn occasion.
She was in her ninety-fourth year,
and it was a great comfort to Stephen Grellet to
think of her as "`full of love to the dear Saviour,
weaned from a dependence upon priests or outward observances,
with her heart fixed,--trusting in the Lord alone.`"^
footnote:[There are many letters from this excellent mother,
and from other members of his family,
all expressing the warmest affection and strongest interest.
It is difficult to select,--they all breathe the same spirit.
One, received soon after his return from his third visit to Europe,
is very characteristic:
{footnote-paragraph-split}
"`What
delight your letter gave your mother,
my tenderly beloved son!
After many dangers you are at last restored to your fireside,
to your dear wife and child, whom you hast found in good health.
What thanks should we render to the Lord!
I had received your letter from England.
I knew you was on the sea,--my spirit was near you, I felt every danger.
Your dear letter has removed the painful load from my heart.
You left me in great anxiety, but not on my own account,--that troubles me the least.
But other trials awaited me,
and I have needed to recall to my mind very often your tender advice,
to bow in entire submission to the will of the Lord, and as you hast told me,
to be fully persuaded that our crosses, our afflictions,
are given us by the hand of the tenderest Father.
Always remember me before the Lord.
When I call to mind your patience, your resignation, your advice,
I feel strengthened.
{footnote-paragraph-split}
"`I wish you, my dear children,
the Lord`'s blessing.
Remember me in his presence, and love, as she loves you,
your mother,
{footnote-paragraph-split}
Grellet.`"]

[.embedded-content-document.letter]
--

[.letter-heading]
To William Allen

[.signed-section-context-open]
Burlington, 8th mo., 11th, 1837.

[.salutation]
My dear friend,

Your three dear letters have all come to hand.
It was very kind indeed,
amidst so many pressing engagements and weight of concerns on your mind, to think of me,
and to give me the so interesting particulars of your Yearly Meeting.
It has been a memorable season; the Lord was with you.
This tells all.
With him there is life, strength and consolation.
You have witnessed all this; blessed forever be his adorable name.
Thus, while with the voice of thanksgiving and praise,
and also with hearts reverently prostrated before him,
we commemorate his mercies and saving help,
we may have our hearts expanded "`in hope for more,`"
under the residue of trials that are yet to be expected.
Noah, after he had joyfully beheld the returning of the dove with an olive leaf,
and hailed it as a proof that the waters were abated from off the earth,
was many days before he could go out of the ark; and when he did,
what a sad desolation was presented to him!
But then the same Omnipotence that had saved him from the overflowing scourge,
was his refuge and his saving help under still attending trials.

My health has been but feeble lately; for some days I have been confined to the house;
but with a little care, and especially with my dear Master`'s help,
who has never failed his poor servant, however feeble and impotent of himself,
for any service whereto he has called, all will be well.
We have, my dear friend,
great cause unitedly for praising and exalting the great and good name of the Lord;
yet how can it be that at seasons clouds are intervening so as to bring doubt and fear?
Well, these, perhaps, are permitted to lead us to increase in watchfulness,
and to be more frequent in the house of prayer.

I cannot describe to you the comfort I have in the brief
accounts you at times give of your soul`'s travail,
and some of your ministerial services in the dear Master`'s cause.
At this distance from each other,
it causes to flow in my heart that stream of Gospel fellowship which we
have so often witnessed when actually engaged together in distant nations.

[.letter-heading]
To Lydia Neild, (late Hargreaves)

[.signed-section-context-open]
Burlington, 12th mo., 16th, 1837.

I was favoured by my good and blessed Master with help to
accomplish the little service he called me to in the West.
I had some solemn satisfactory meetings among Friends
and persons of other religious denominations,
when the power of the glorious Gospel of Christ, the Lord of all,
appeared to have dominion over all.

The Yearly Meetings of Ohio and Indiana were considered
by Friends there the most solemn they had had for many years;
blessed be the Lord! from whom the life flows and the power is;
it is he that does the work, and his works only can praise him.
These are two large Yearly Meetings, Indiana especially.
There are valuable friends in that body,
and the visitations of heavenly love have evidently
been extended to many of the young people.
I am comforted also in believing that some of them
have received the Truth in the love of it.
In the reports of the Quarterly Meetings on the state of their schools
it appears they have among them 6429 children of an age to go to school.
O! what a field in those young plantations for labourers.

When in Ohio I went to see William Flanner; he was not able to attend the Yearly Meeting,
but was at his own meeting, and I spent a few hours at his home; he was nearly blind,
and very dull of hearing; but clear in his best faculties,
and strong in the love of Christ.
I was favoured to return home in better health than when I left it, and have so continued.
The Lord, in my absence, mercifully cared for my beloved wife and daughter,
so that we have again and again to set our seals to his great goodness.
Since this return I have been several times from home, for a little while,
attending to impressions of religious duty, for which I have felt peace.

[.letter-heading]
To William Allen

[.signed-section-context-open]
3rd mo., 8th, 1838.

I have been much of an invalid these days past.
What a favour to be at home with my dear family,
and above all to witness something of the precious influences of that Spirit
of comfort and consolation which brings with it refreshings from the Divine presence.
All this, and much more than we can ever number,
is the fruit of the love and mercy of God in Christ Jesus to a poor unworthy worm.
May we under an increased sense of it, and with enlarged hearts,
be still more prepared rightly to praise and exalt his holy and blessed name.

[.letter-heading]
To Lydia Neild

[.signed-section-context-open]
Burlington, 4th mo., 28th, 1838.

My health has been feeble for these months past, yet I hope to regain my late standard,
which will not rank me among the mighty; but,
if we have sufficient ability to perform the residue of the service
that the dear Master has for us in the militant church,
it is enough.

There is also a service in silent suffering,
under which the soul may be greatly benefited.
In this work I desire to be found abounding, now in my declining years,
yet I rejoice greatly in the Lord,
when I hear that such as are engaged in the dear Master`'s work.

--

[.offset]
After alluding to his illness, he writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Alexander

[.signed-section-context-open]
6th mo., 23rd, 1838.

I must, however,
tell you that my days during this sickness have been among the most happy of my life,
so much of the comforting and refreshing presence of my blessed and adorable Redeemer,
that my cup has run over.
Never before have I felt him so fully, so sweetly in his blessed character of a Redeemer,
a Saviour.
O how lovely he is in every part of his humiliation, of his sufferings,
and the agonies of his death; and that for the salvation of sinners!
To sinners it is given to know him, to feel him,
to love and adore him in the character and under the blessed name of Jesus.
"`The angels desire to look into these things.`"

John Warren has lately travelled in Nova Scotia,
and found several persons who once had a right of membership in our Society,
and a few members of it.
In three places he has collected these scattered sheep together,
and they being joined by some others that have become convinced of our principles,
now hold meetings.
I am told that after this dear friend had made his concern to visit that land public,
some of his friends appeared desirous he should put off his journey for awhile,
perhaps on account of the inclemency of the weather.
He answered, "`My Master has given me a few sheep:
I must speedily go and look after them.`"

[.letter-heading]
To William Allen

[.signed-section-context-open]
Burlington, 10th mo., 1838.

I have felt much interest in hearing of the nature
of the service of Samuel Capper in London.
How all classes of men, rich and poor, near and far,
are equally under the notice of our blessed Lord and Redeemer.
He sends his servants to proclaim to them all the glad tidings of the same Gospel.
It has been particularly striking,
that while S. C. was engaged with the poor in your great metropolis,
the concern of our dear H. C. Backhouse was with the rich at the West-end of the city.
The mention of her reminds me of a circumstance that will interest her.
I hear that E. P. K., her companion in this land, appeared in supplication last Firstday,
at her meeting in Philadelphia.
It has doubtless been a great trial of her love and faith in the Lord.

If our hearts are so gladdened when we thus see one here and another
there ranging themselves under the banner of Christ,
how greatly would our joy be enlarged if the mass of our
young people would yield themselves his servants,
but the love of the world powerfully operates to
the turning away of many from the cross of Christ.

[.letter-heading]
To William Allen

[.signed-section-context-open]
Burlington, 5th mo., 14th, 1839.

[.salutation]
My beloved friend,

I wrote to you a few days after the reception of your long letter of seven pages;
not a line of which could have been spared but to the abridgment of my comfort.
Though I have not heard directly from you since,
yet I have been gratified at hearing of some of your
engagements in your great and good Master`'s cause;
while I am thus permitted to share some of your joys-joys ever attending
a faithful devotion to the dear Redeemer`'s service,--I am not without
a sense of the nature and depth of the baptisms to be endured before memorials
can be brought forth out of the deeps;
yea, knowing the very tender texture of your mind,
my affectionate sympathy continues towards you.
O let us endeavour to keep very close to our blessed
Lord and the guidance of his Divine Spirit,
of the blessedness,
the safety and preservation of which there is a testimony
rising in our hearts that can never be forgotten;
yet, to my own confusion,
I often detect myself in a state of distrust--afraid of my own shadow.
"`When I sent you without purse or scrip, did you lack anything?`"
"`Nay, Lord,`" was the answer; this is our answer, my beloved brother;
wherefore then should we doubt?

I am surprised at myself not having written to you since Yearly Meeting.
Various engagements and pressures on the mind have been the hindrance.
Some of us went to that meeting under fears and weights,
but we felt the sentence of death in ourselves,
not to trust in ourselves but in the Lord alone,
to keep close enough under the guidance of his blessed Spirit;
and truly we have seen that not by might, nor by wisdom, "`but by my Spirit,
says the Lord,`" the work is done, and all the glory is ascribed unto Him.

I am not unmindful that your solemnity is very close at hand, and some of you are,
I believe,
to be found in fervent prayer that the Lord would
be pleased to meet with you and bless you together;
I have a little faith to believe that he will do it,
and enable you to rejoice in his presence.
+++[+++After alluding to some of their trials, he adds,]
But blessed be the Lord, he is a sure retreat under every difficulty,
and I know substantial good may be obtained under these,
while dwelling in watchfulness unto prayer.
O that I may reap abundantly of the blessedness flowing therefrom.

How beautiful are the feet of those Gospel messengers that publish peace,
that proclaim the name of the Lord! but how far more beautiful
are those servants of the Lord covered with the spirit of love,
of meekness, of forbearance, and patience-the spirit of their great Lord and Saviour!

[.signed-section-closing]
Farewell in the Lord, my much beloved friend, in the fellowship of the everlasting Gospel.

[.signed-section-signature]
Stephen Grellet

[.letter-heading]
To William Allen

[.signed-section-context-open]
7th mo., 7th, 1839.

Zeal, creaturely zeal,
is often rendered an instrument of the devil to bring about his evil purposes,
but zeal according to knowledge, zeal for the blessed Truth, how precious!
It is founded in humility; Divine love is its strength;
love to man its wide field of action.
I long for an increase of it in my own particular.
With it our lamps and vessels are like those of the wise virgins supplied with oil,
but darkness and barrenness in Christian virtues must attend such as are without it.

[.letter-heading]
To Lydia Neild

[.signed-section-context-open]
5th mo., 15th, 1839.

How pleasant it is to see some of the young people
filling up the ranks vacated by valuable parents;
the account of some beloved friends of the junior class is very consoling to me;
may they keep very close to the Lord`'s guidance by his blessed Spirit,
and then will they become Valiants for the Truth; not like many among us,
and not a few in your land,
who have cast away that shield on which the holy unction rests,
and by which the fiery darts of the enemy are quenched.
Happy would it have been for our Society if we had been found more generally engaged
in singly obeying that great command of love to God and love towards one another;
and, blessed be the Lord, this is the precious engagement of many.

After his return from North Carolina,
Stephen Grellet did not go much from home for some time;
but in his love to the Redeemer`'s cause everywhere and the deep
interest he felt in the prosperity of his own Christian community,
he was tenderly alive to all that related to objects so near his heart.
In allusion to some trying occurrences, he remarks in a letter:

[.letter-heading]
To George Stacey

[.signed-section-context-open]
7th mo., 28th, 1841.

There is an Almighty controller of events, in whom we may safely trust.
He can over-rule all things to the praise, finally, of his great name.
Amidst some of my fears and anxieties I am sometimes rebuked and instructed by
the remembrance of the words of the dear Saviour to his desponding disciples,
"`O fools and slow of heart to believe,
etc.;`" and as to gloomy prospects,--can anything transpiring
in our day be compared to the period when Herod,
Pilate, and the Jews conspired against the Lord Jesus Christ?
when all his disciples fled and forsook him; when he was crucified, died and was buried;
when the whole creation proclaimed the awfulness of the occasion, darkness, earthquake,
rending of rocks, etc., united with the mourning of the women?
Nevertheless this was the very period when the foundation was laid,
when the highway was opened, through the blood of the cross,
for the redemption and salvation of a guilty world, even of me, who frequently,
when remembering my past life, can and do feel myself as a chief among sinners.

Sometimes I am permitted to see, through the present thick cloud,
the arising of brighter days,
accompanied with a hope that the present tribulations
are preparing the way for the coming of it.

Surely all the Lord`'s promises to his Church will in his time be fulfilled;
not one can fail; should the number of his servants now become reduced,
Omnipotence can multiply them like the sand of the sea.

--
