== Chapter LXV.

[.chapter-synopsis]
* New York and New England Yearly Meetings
* Illness
* Baltimore Yearly Meeting
* Decease of William Allen
* Deputation to Indiana Yearly Meeting
* Letters

Hitherto Stephen Grellet`'s health had not been seriously impaired.
His strength of constitution had been tested by his
many and arduous travels in different climes;
and his well-developed and hardy frame had seemed to resist
with unusual tenacity the encroachments of disease.
But the time was now approaching when his physical powers so far gave
way as no longer to allow him to undertake any distant journeys.

In the summer of 1842 he attended the Yearly Meetings of New York and New England,
and soon after his return from that engagement, he was seized with an alarming complaint.
His illness was of several months duration,
and his medical attendant repeatedly thought that he was near his end.
Though his bodily sufferings were often great,
he was enabled to bear them with his accustomed fortitude, and patience,
in cheerful submission to his heavenly Father`'s will;--prayer and praises frequently
ascended to Him whom he loved to serve even in the furnace of affliction.
In reference to the final issue, he said,
that "`the love of his dear Saviour was very near to him; his dear Master was very good,
and did not forsake him in his extremity; all would be well, whether in life or in death;
Christ was ours, and he would fulfill the promise;
"`I will never leave you nor forsake you.`"
Again he exclaimed, "`Do not think that He who gives strength to suffer,
does not give love to endure; we must bless the Lord, not by the measure of affliction,
but by the measure of comfort and love!`"
He spoke touchingly to his beloved wife and daughter,
and earnestly gave them his blessing.
He tried to utter some lines of a hymn, and on his wife repeating them:

[verse]
____
"`There is a land of pure delight,`" etc.
____

he bowed his head and said, "`Out of the depths hast you answered me.`"
Again he remarked, "`My Saviour is my joy, my salvation, the rock of my strength,
my Redeemer, my song, my hope forever and ever`" "`He is my rock and my refuge,
but I am very poor--utterly unworthy.
I am but a child; I wish to be but a child.
We are very mercifully dealt with; my dear Master is very near me;
I feel his presence to be staying my soul;
I can do nothing but bless and adore his Divine name!`"

Much more might be added from the family record of
the precious words of counsel and encouragement,
and of Christian love, which flowed from his lips during this season of confinement,
but enough has been said to show how the exceeding
great and precious promises of the Gospel,
which, in health, he had so often proclaimed to others,
now were the rejoicing of his heart, when apparently near the portals of eternity.
His end, however, was not yet;
and on his recovery from this illness and a relapse he had in 1843,
it is interesting to notice the characteristic manner in which he speaks
of this portion of his life in the following extracts from his correspondence.

On the 22nd of Tenth month, 1842, he writes to his beloved friend William Allen,
and after expressing his great concern on hearing of his illness at Lindfield,
and his earnest desire and prayer that,
"`for the Church`'s sake and that of the blessed cause of
righteousness in the earth,`" his life might yet be prolonged,
he continues:

[.embedded-content-document.letter]
--

I am persuaded that your blessed Master and beloved
Lord has richly supplied all your needs,
has encircled you by his presence,
and given you richly to feel the joys of his salvation,
even when you may have pretty much concluded that
the spark of animal life was near being extinguished.
Good, very good indeed is the Lord;
when afflictions abound consolations by Christ abound much more.
You hast heard how very ill I have been myself.
It is three months since I was taken down, but am now recovered to a considerable degree.
You hast been these many weeks past in my very sweet but very anxious thoughts,
so that I often spoke to my beloved wife of my anxiety on your account,
fearing you was sick.
Is it not remarkable that we who, in company together in distant lands,
have shared many trials, exercises of mind and perils,
should now also have walked together, at the same time,
through what appeared to be the valley and shadow of death?
As under the former we were raised above fears of any evil,
our blessed Lord being with us, his staff supporting and comforting us,
so likewise in this latter he has been in a marvellous manner near us.
Truly I may reckon these last three months, though passed under such bodily suffering,
among the most blessed and precious of my life,
for by night and by day my dear Redeemer and his Spirit were near me,
and at the same time that the good remembrancer has
brought to mind the various portions of my life,
my soul`'s travails and exercises, the state of the churches past and present,
yet it has been in a way wonderful to describe, for no painful consideration attended,
no hard thoughts against the troublers in Israel, but love, Divine love,
was as a garment, or diffused like oil over all.
In my sleep, in my waking hours, even under what, through the violence of the fever,
might be considered a delirium, the thoughts of my heart were unto the Lord,
sweet and refreshing.
O I have had very full confirmation of the rectitude of our Christian profession-faith,
doctrines,
and hope being truly grounded on the foundation on
which the Apostles of our Lord Jesus Christ did build,
and that faith in Christ is that through which his
redeemed and sanctified ones have obtained the victory.
Surely that Christian hope which felt so clear, so sweet,
when apparently having already a foot out of time into eternity,
giving to feel the joys of God`'s salvation,
through the Redeeming love and mercy in and by Christ,
is a religion fit for a man to live by; yea, a hope springs from it,
that has on no occasion made ashamed those that have maintained it well.
My much beloved friend,
while giving you a concise statement of the Lord`'s tender mercy and very
gracious dealings towards your poor and very unworthy brother,
I have a steady eye to what I apprehend "`have also
been your blessed Master`'s dealings towards you;
so that we may well unite in the adoption of the language, "`Bless the Lord,
O my soul,`" etc.
And now, may the residue of these feeble lives, thus prolonged by the Lord`'s power,
be employed in showing forth his praise.
My wife desires her dear love to you and dear Lucy and our precious daughter joins,
and in gratitude, at the prospect of your restoration to health,
although we cannot expect to hear of your rising again to your former vigour.

Farewell, my much beloved in the Lord.
It is he who is your buckler, your shield, and finally your "`exceeding great reward.`"

[.signed-section-signature]
Stephen Grellet

[.letter-heading]
To the Same

[.signed-section-context-open]
Burlington, 5th mo., 22nd, 1843.

[.salutation]
My beloved friend,

The day before yesterday I received your letter of Third month, 31st,
and this day I have that of the 2nd inst.
By taking up my pen so quickly you see that I am in earnest to comply with your
request to hear frequently of your poor but warmly attached brother.

Your last letter gives me some relief.
I observe with comfort that, though feeble, you are able to go about,
and are often engaged in publicly advocating the cause of the blessed Redeemer,
so dear to you.
Both of us, my dear friend,
must expect it will take a long time to recover from
the long and serious illness we have had;
fully to recover from it, however, may never be.
I see no prospect of it on my part;
but what a favour that we have to do with so good and merciful a Saviour,
who knows fully the whole of our infirmities,
and requires nothing of his poor servants beyond their ability to perform;--to
the praise and glory of his great name we both have,
in harmony with other beloved fellow servants of the same Lord,
gratefully to acknowledge to his Divine help and strength in the
performance of every service required of us in years past;
every mountain of opposition did flee at his presence.
How often have we together sung his praises on the banks of deliverance! and now,
when nearly laid aside by age and infirmities, we can still proclaim his love, his mercy,
his power and his wondrous works.

I more particularly allude to what your soul is often
found engaged in than speak of myself,
whose harp is most generally hanging on the willows,--for day by day, almost,
there is that transpiring within the reach of my ear and heart`'s feeling that
leads to weeping and mourning,--favoured nevertheless with a small degree of
ability to lay hold of that hope which is like an anchor to the soul,
and reaches within the veil to the rock-Christ Jesus.

I made an attempt to attend our late Yearly Meeting in Philadelphia,
but my strength was speedily exhausted, and I had to return home.
This shows I am but a feeble man, but I could not wish it otherwise with me.
That the Lord`'s will may be done is my frequent prayer.
O my dear friend, if we can no more glorify his excellent name,
being actively engaged in proclaiming it among the nations,
under the guidance of the Divine Spirit,
let us maintain with resignation and Christian devotion,
this post of service still assigned us, to glorify Him in suffering.
Peter was to glorify his beloved Lord by his death.

My love to your beloved niece Lucy, Cornelius and wife, with their nice flock.

[.signed-section-closing]
Your very nearly attached friend,

[.signed-section-signature]
Stephen Grellet

[.letter-heading]
To William Allen

[.signed-section-context-open]
Burlington, 7th mo., 22nd, 1843.

[.salutation]
My beloved friend,

I wrote to you soon after the reception of your last letter,
and hope soon to hear of you again.
In your feeble state of health I do not wish you to use much exertion in writing to me,
however truly grateful it be to receive your dear letters.
Do we not enjoy a great blessing through the so wonderful working of the Divine Truth,
in that, though prevented from much even epistolatory interaction,
our minds can commune sweetly with one another.
I feel you frequently preciously near in spirit.
How precious the hope that our bond of union to one another is stronger than death,
and will be more lasting than time.

I am told that our friend, John Pease, proposes to embark for America next month;
surely we must accept it as an evidence that the
dear Redeemer`'s love is still extended to us,
seeing he commissions more of his messengers of peace, in the love of his Gospel,
to visit us.

The public distress in your land, in church and state, causes me much solicitude.
From early life, in France, I have beheld the frightful works of darkness,
attending revolutions.
In our poor Society in this land, much has transpired deeply to afflict,
but I shall die in full hope that the Truth will have the victory over all.
Not one jot or tittle of the Lord`'s testimonies concerning his kingdom and Church,
and the blessings finally attending, but shall be accomplished.

My health continues slowly to improve, though I cannot expect, any more than you,
to regain our former standard.
My beloved daughter has been ill, but our anxiety is a good deal relieved.
The Lord, our blessed Master, who wants us to be priests unto him,
time after time prepares offerings for us to present to him.
Surely he is greatly to be praised.

Anna Jenkins was liberated by the Select Yearly Meeting
to visit your nation again with very full unity.

My wife, whose very dear love is to you,
joins me in a message of the same to your dear Lucy,
also to our beloved friend Susanna Corder, Cornelius Hanbury and wife,
and their children.

[.signed-section-closing]
Farewell in the Lord, my much beloved friend,

[.signed-section-closing]
Your closely attached,

[.signed-section-signature]
Stephen Grellet

--

In the Autumn of 1843,
Stephen Grellet was so far recruited as to be able to attend the Yearly Meeting in Baltimore,
but his health continued liable to great interruptions.
He was "`deeply affected by the accounts he received
of the reduced state`" of his beloved friend,
William Allen,
and "`the prospect of a final separation on earth from that dear one;`" and when,
in the early part of 1844,
the intelligence arrived that "`his redeemed spirit
was gently released on the 30th of Twelfth month,
1843,`" he keenly felt the bereavement, both on his own account,
and for the Church`'s sake,
while he "`thought there was great reason to apprehend
that he should not tarry long after him.`"

Some months later, on reviewing the few last years of his life,
having nearly completed his seventy-first year,
he makes the last record in his Autobiography:

[.embedded-content-document]
--

In 1842, I was at the Yearly Meetings of New York and Rhode Island,
attending also a number of meetings in those States respectively.
Soon after my return home I had a severe illness, by which my health became so enfeebled,
that I was not able to be from home for any length of time; but in the year 1843,
I was strengthened to attend to the pointings of
religious duty to go to Baltimore Yearly Meeting.
I was favoured with sufficient bodily power to perform that
visit of Gospel love to the comfort and relief of my mind.
From that period to the present time, Ninth month, 1844,
my health has not allowed me to go from home.
With reverent gratitude I record how mercifully my good and blessed Master
now peacefully releases me from the weight of religious service abroad.
Good indeed is the Lord!
When he called me to labour in distant nations, or nearer home,
he gave strength for the service required.
Now that bodily strength fails me,
nothing is required but what I have ability to perform; and, through adorable favour,
the same mercy and goodness that have followed me all the days of my life,
continue to be with me in my advanced age and feebleness of health.--Blessed
and praised be His glorious and excellent name!

--

Though thus "`peacefully released`" from active service in distant parts,
the veteran "`soldier of Christ`" did not cease to feel
the need of keeping on "`the whole armour of God,
that he might be able to withstand in the evil day, and having done all,
to stand`" unshaken.
He continued to cherish a lively interest in all that related to
the advancement of the kingdom of Christ at home and abroad,
and, with lively zeal, chastened by knowledge and without guile,
he was quick to discern and faithful to bear his testimony against everything which,
however specious in appearance, had a tendency, as he believed, to dim the brightness,
to mar the beauty, and to retard the progress of the Truth as it is in Jesus.

Largely as he had partaken of the cup of suffering
in sympathy with the church under its former vicissitudes,
the more recent trials among Friends, in other Yearly Meetings and his own,
caused him much prayerful solicitude,
and not infrequently led him into deep conflict of spirit.^
footnote:[It was the time of the sorrowful developments and crisis in New England,
in which he deeply sympathized with the large body of Friends of that Yearly Meeting,
and rejoiced in the evidence they gave of a firm
hold on the fundamental doctrines of the Gospel,
and a faithful adherence to those spiritual views and Christian testimonies of the Society,
which he had himself so unflinchingly supported and
proclaimed through a long course of years,
and which he continued to believe were founded in the very Truth.]
But humbly trusting in God,
his unwavering attachment to the Redeemer`'s cause and a
close attention to the leadings of the Spirit of Truth,
were his safeguard and strength,
and the source of his rejoicing even in the midst of tribulation,
while his heart still flowed out in Christian love
and sympathy towards the ends of the earth.

About this time he writes in reference to the Yearly Meeting lately held in London;

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Alexander

[.signed-section-context-open]
6th mo., 27th, 1845.

All agree in the one testimony that the Lord owned in a very precious
manner his people assembled in that yearly solemnity.
He continues to care for his church.
From my very heart I have united with very many of you in ascribing
glory and praise to his excellent and adorable name.
What little he permitted Friends to see of the workings
of the enemy that comes in to divide and scatter,
has, I can well believe,
tended to bring them to feel the more forcibly the
value and preciousness of love and unity;
strong are the bonds of it.
In these days of trial I am frequently reminded of the fable of the traveller who,
as the wind and the storm increased, wrapped his mantle the more closely about him.
Thus may I hold firmer and firmer, with the girdle of Truth,
the mantle of love to God and man!

--

At the Yearly Meeting alluded to in the preceding extract,
four Friends had been set apart as a deputation to Indiana Yearly Meeting,
where a small secession had taken place in connection with the question of slavery.
On hearing of the appointment,
Stephen Grellet`'s heart glowed with interest towards his beloved friends,
and the object they had in view; and he writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To George Stacey

I hail the account of the proceedings of your Yearly Meeting and of your
expected coming to America with your partners in the mission of love,
as Noah must have done the dove with the olive leaf in her mouth.
Yes, my beloved friends,
I look towards you as ambassadors of peace and love-sent by the God of peace and love.
The travail of the Church with you has been indeed of a very solemn and interesting,
as well as of an important nature; and I trust that,
with the Lord`'s continued blessing upon it, his gracious designs will not be frustrated.
You all who, by accepting the important appointment,
do manifest how much at heart you have the health and prosperity of the church,
have my very near sympathy; for,
surely it is the love of Christ that constrains you
to make the sacrifice to attempt to come among us,
well knowing the privations and the sufferings that you will have to undergo.

--

[.offset]
On the arrival of the deputation at New York, he again writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Burlington, 9th mo., 1st, 1845.

I feel disposed to meet you with a few lines, to bid you and our beloved friends,
your fellow-messengers of love and peace, welcome to our land.

You are well aware that as afflictions abound among
us you must necessarily participate in the same;
but for this very purpose you are come.
Many Friends, I know, will greet you with much affection.
Many of us in Burlington have hearts warmly drawn towards you, and we hope that,
if only as wayfaring men, you will tarry with us on your way to Philadelphia.

My wife and daughter anticipate the pleasure of having you for our guest;
they are well acquainted with you, though personally unknown.
My dear friends, R. and A. J.,
on account of their relationship to Hannah Paul of Philadelphia,
claim to have dear Josiah and William Forster with them;
and I hope dear John Allen will come with you to my house.

The meeting of such friends, long known to each other, and well beloved,
involuntarily brings to remembrance the scene, when "`Paul saw the brethren, thanked God,
and took courage.`"
And as Stephen Grellet had welcomed the "`messengers of peace`" on their arrival,
so his heart was with them in the prosecution of their labour of love, and rejoiced when,
having accomplished the interesting service,
they were permitted to return home with the Divine
blessing resting upon their work of faith.

--

[.offset]
Not long afterwards, he writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Alexander

[.signed-section-context-open]
9th mo., 19th, 1845.

Lately the troubles of my heart were greatly enlarged, when feeling,
to an unusual degree, the great wickedness and depravity of man,
so lamentably exhibited in our days in various sections of the earth and of this land,
as manifested by the many crimes committed,
the horrors of slavery and all the cruelties and evils attending; then again,
on the other hand, what darkness and distress is produced by wickedness in high places!
Be our attention drawn to the church of Rome, the Hierarchical system,
or to our poor Society in this land-on every side is to
be discovered that which loudly calls for mourning,
weeping and girding of sack cloth.
But again, my dear friend, in all this we can only see and feel in part,
and a very small part; whereas the blessed Saviour, our Lord Jesus Christ,
had the whole of the weight of it laid upon him, yea the sins of the whole world,
and for this purpose he has come, to save a guilty world.
He is able to save to the uttermost; therefore behold,
if while looking at the things below sadness overwhelms,
heavenly hopes and joys are beaming forth when the eye is directed to the Lord Jesus;
let us therefore endeavour to have our hearts fixed on Him.

--

His health was still feeble,
but on the approach of the Yearly Meeting of New York the ensuing spring,
he felt well enough to yield to "`an apprehension of religious duty,
once more to mingle in Christian fellowship and love
with his brethren of that portion of the body.`"
It was the last time;
and he had much satisfaction in meeting so many of his beloved
friends on such an interesting and important occasion.
In reference to it, he remarks in a letter to a friend:

[.embedded-content-document]
--

My blessed Master permitted me to return home in sweet peace.
Though the engagements were close, and mental exercise often deep,
yet I have come back stronger than I went out.
My blessed Master is indeed very gracious to his unworthy servant.
This sense increases the desire that my life which has been spared,
and my days so unexpectedly lengthened, may be devoted to his service,
even though this should be by suffering for his blessed Truth.
O that I may glorify him in life and in death!

--

[.offset]
A little later, he writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia Neild

[.signed-section-context-open]
Burlington, 7th mo., 27th, 1846.

The number of my correspondents in England has greatly lessened;
the undeniable messenger of death has opened the
way for many of these to pass into a better world,
even into the kingdom of everlasting blessedness and glory.
Some very dear and beloved ones still remain, like myself,
a short time longer inhabiters of this world of probation, wherein, however,
we occupy a very important station; for on the proper occupation of it,
be the time longer or shorter, greatly depends our well-being.

O for an increase of faith on my part,
and a more steadfast abiding in watchfulness and prayer!
May I be preserved now in my advancing years, through grace and mercy unmerited,
but on which alone my hope centres, and be favoured in the end,
through the merits and intercession of the blessed Redeemer,
to be admitted among those who have come out of great tribulation,
and have washed their robes in the blood of the Lamb!

--

[.offset]
In the early part of 1847, he again writes:

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia Neild

We are permitted to continue here a little while longer; I marvel as to myself,
having been repeatedly brought as to the side of the grave.
O that the lengthening of my life may also be the enlargement of my heart to serve,
adore and glorify my Redeemer; Amen! so be it; amidst fiery trials,
only be his holy name honoured in life and death;
no matter of what nature or how deep our sufferings,
if they forward the purification of our souls, and tend to the glory of God;
then under these, we may join our worthy, ancient friend, George Fox, in saying,
"`Never mind, friends, the Lord`'s power is over all.`"
I believe it is so, therefore let us, through his assisting grace,
endeavour to possess our souls in patience, and in faith and confidence,
wait to see what he will do for his great name.

--

About the same time, having heard of the death of Clarkson,
he thus alludes to that great champion of Negro freedom, in a letter:

[.embedded-content-document.letter]
--

[.letter-heading]
To Ann Alexander

I have thought several times how much you must miss our late valuable friend,
Thomas Clarkson; you had so long enjoyed his interesting and instructive company.
Is it not very sweet and precious to contemplate how many of those beloved ones
we have known are now inhabitants of the celestial city with saints and angels?
Yet a little while, my dear sister,
and I have a joyful hope that there also your habitation shall be.

I salute affectionately your dear father, (Dykes Alexander,) and your aunt Alexander,
(late of York,) as travellers thitherward; yea,
not very far now from the pearl gate into that "`glorious city.`"

[.letter-heading]
To Josiah Forster

[.signed-section-context-open]
Burlington, 2nd mo., 26th, 1847.

[.salutation]
My beloved Friend,

I share with you and deeply feel the great stripping of the church among you.
We can truly rejoice in that there has been an enlargement of the church triumphant,
in heavenly places in Christ Jesus.
But the militant church, how greatly reduced among us here especially.
In ancient days, "`The Lord added to the church daily such as should be saved.`"
So was it also in former years in the borders of our religious Society; many of those,
thus added, have become of the saved of the Lord.
In my days I have seen in various parts of this land, how in several sections, ten,
twenty, and more, were month after month added to our number,
on the ground of convincement.
But I have lived also to see many of these scattered as to the four winds,
instead of becoming of the saved of the Lord.
This scattering seems to have so completely stopped the tide of convincement in others,
that now year rolls upon year and not one instance
is found recorded of any increase by convincement;
whereas many are the testimonies of disownment issued.
This, together with the steady work of mortality,
opens the prospect of a waste howling wilderness.
Nevertheless, when I consider from where sprung the multitudes of Israel,
and wherefrom also our Society sprung and grew up;
amidst what trials and sufferings they became instruments by which such excellent principles
and testimonies to the blessed Truth were upheld and maintained,--and which,
in the present day,
are highly appreciated by many who do not go under our name,--my
little portion of faith reaches to the fulness of hope that
the Lord will continue to work for his great name`'s sake;
for the end for which the Redeemer has come, has suffered, and ever lives,
will and shall be accomplished in his time.
I shall not see it.
But the time for it is progressing--it is drawing nearer and nearer, I think, sometimes,
that through the thick clouds that pass over our horizon, a view of this is permitted.
Not one jot or tittle of the Divine promises but what shall be accomplished;
for the Lord God Omnipotent reigns, and his power is over all.
But why have I entered upon the expression of such solemn things?
Dear friend, whatever gloomy things may at seasons appear to us,
let us trust in the Lord, and not be afraid.
He will work, even in our Society--and who shall hinder Him?

--

[.offset]
Writing to the same friend, a little later, be adds:

[.embedded-content-document]
--

I shall die in hope that better days will come,
and that the Sun of Righteousness will yet arise with healing in his wings.
O then, what virtue!
What blessed efficacy will flow!
Our wilderness shall then flourish, and our desert shall become as the garden of the Lord.
In His time, he will do this, and glorify his name.

--

There was at this time something peculiarly bright and searching
in Stephen Grellet`'s Gospel ministry in his own meeting.
At one time he rose with the Saviour`'s query to his disciples, "`Where is your faith?`"
and reminded his hearers that this was not addressed to strangers or aliens,
but to those who are frequently spoken of as the disciples of our Lord,
and who had given evidence of their faith in him, by having left all to follow him;
but who, in their frail bark, when the wind and the tempest beat high,
while the dear Master was asleep in the midst of them,
and they seemed as if they were actually sinking,
gave vent to their fearful anticipations in the cry, "`Master, we perish.`"
Many in the present day, whether they looked at themselves, the Church,
or the condition of the nations of the earth, were ready to adopt the same language.
But, discouraging as might at times be the view of some
whose life could not be much longer lengthened out,
yet he believed the power of the Most High could breathe even upon the dry bones,
as Ezekiel saw them spread forth in the valley; so that at his word,
bone should come to his bone, etc.
And happy would it be for those who, though dead in trespasses and sins,
should hear this quickening word-and be saved through the Redeemer`'s grace, and,
obeying his voice,
be enabled to bring forth fruit to the glory and honour of His great name.
"`But where is the faith which will cause the young man
and the young woman to bud and blossom continually,
as did Aaron`'s rod; or that will make them as a green olive branch?
Be watchful, therefore, lest, having been quickened unto repentance,
for lack of faith you be cast forth and be withered!`"

Speaking of the merciful dealings of Christ with sinners,
he said "`And when the shepherd finds the lost sheep,
after leaving the ninety and nine in the wilderness, how does he bring it home?
Does he whip it?
Does he drive it?
Does he threaten it?
No such thing!
He carries it on his shoulders, and deals most tenderly with the poor, weary,
wandering one!`"
