== Chapter LXVI.

Philadelphia Yearly Meeting--Illness--Letters, etc.

For more than fifty years Stephen Grellet had laboured diligently
in the service of the Gospel in various parts of the world,
and many had cause thankfully to acknowledge that, through his instrumentality,
they were plucked like brands from the burning,
and brought to the knowledge of the Saviour "`who died for us and
rose again,`" or had been confirmed in the faith of Christ,
and animated to faithfulness in following Him,
under the guidance of the Spirit who leads into all truth.
Gradually as the sphere of his active exertions in the Redeemer`'s
cause had been lessened by the state of his health,
he had still been able occasionally to go from home for a short time;
and in the Fourth month of this year, 1847, he went to Philadelphia,
to attend his own Yearly Meeting.
After being present at the Meeting for Ministers
and Elders he was taken ill during the night,
and obliged to return to Burlington the next day;
and from that time he did not again leave home even for a single night.

He was now in his seventy-fourth year,
and when thus wholly deprived of the power of going abroad by a disease which
subjected him for the rest of his life to frequent paroxysms of acute pain,
he bore the trial with meek submission,
and often praised the Lord for his goodness and blessed help in the hour of need.
His mental faculties and his spiritual perceptions remained unimpaired;
the love of Christ, and that rejoicing in him so often the privilege of the believer,
seemed to form almost the hourly and familiar habit of his soul.
Though sometimes prevented from worshipping publicly with his friends, he was able,
at intervals, to attend his own meeting,
where he was often engaged in the ministry of the Gospel,
to the edification and comfort of his hearers;
while those who were privileged to come within the circle of his daily influence,
under his own roof or when he mingled with his friends in social interaction,
could not fail to be interested and benefited by his conversation, when,
as the scribe well instructed unto the kingdom,
he brought forth out of the good treasure of his heart, things both new and old;
and they would often be edified by the solemn silence
that ensued-broken by words of comfort,
of counsel or encouragement,
that seemed like refreshment drawn from the "`nether
spring`" of the Saviour`'s presence and love,
peculiarly adapted to the need of the hour.

The characteristics which had marked his earlier days,
and largely attended his Gospel labours among all ranks
and conditions in the many nations he had visited,
shone with undiminished brightness in the evening of life,
when entirely confined to the precincts of home.
The warmth and ardour of his affections, his truly Christian cheerfulness,
blended with a quiet unaffected, unassuming dignity of manner,
at once humble and self-possessed, gave the impression of no ordinary person.
A true Frenchman in politeness, he was quite a model of the courteous and affable,
without the fawning flattery of the world.
Christian simplicity, sincerity and truthfulness,
marked his words and actions;--"`his look was love, his salutation peace.`"^
footnote:[To those who had no personal acquaintance with him,
it may be interesting to know that he was about the medium height, erect,
and rather slender.]

While, in the retirement of the home circle,
the graces of the spiritual life were thus daily exhibited,
Stephen Grellet continued to keep up an extensive correspondence with his absent friends,
and though his memoranda now cease,
his letters in great measure supply what is lacking to show the experience
of the aged Christian during the seclusion of his latter days.

On recovering from the attack which obliged him to
retire from the Yearly Meeting in Philadelphia,
he writes:

To George Stacey

Burlington, 5th mo., 13th, 1847.

I do not expect to write any other letter by this steamer.
It would be a great privation,
during the short time I may continue in this world of probation,
should I become deprived of the privilege of communing
in this way with my beloved absent friends.
I hope that, whatever deficiency there may be in this respect on my part,
they will not attribute it to a lessening of my affection for them;
for truly my love to you is strong,
and very sweet is the fellowship that my blessed Lord enables
me at seasons to feel with the spirits of many of you,
and not only with you, my precious fellow-probationers for a little while longer,
but also with the beloved departed ones,
now inhabitants of the heavenly Jerusalem among the spirits of the just made perfect.
O if, when we have our attention here below directed towards things that are seen,
we behold what afflicts, what joys and consolations, on the other hand, when,
through the Spirit and by the eye of faith,
we can contemplate those things which are above!
This is having our conversation in heaven;
there I long to have my heart more and more fixed.

His correspondence with Ann Alexander, the daughter of his "`beloved and valued friend,
William Dillwyn,`" had been so constant and long continued
that a series of extracts from his letters to her,
will from this time materially aid in exhibiting the different phases of his inner life.
To her he writes:

6th mo., 14th, 1847.--I have gratefully to tell you that my own health,
though still feeble, is much improved of late,
so that I am able comfortably to resume all my religious meetings.
I feel it a great privilege and consolation to be able to unite publicly
with my friends in waiting on and worshipping our great and gracious Lord.
He has indeed very mercifully condescended to be
ever near his poor servant in my approaches to him,
when necessarily detained at home in my chamber or bed;
so that I can reverently proclaim his goodness and tender mercy,
as being extended both in the closet and in the congregation of his people.
I am sometimes lost in wonder and amazement,
under a sense of the marvellous provisions that an
almighty Father and merciful God has provided,
for the sustenance and the renewal of the strength
of the weakest and poorest of his flock.
They that wait upon the Lord shall renew their strength.

8th mo.,
14th.--Last First-day night I had another attack similar to that
I had in Philadelphia at the time of the Yearly Meeting.
This last was of longer duration, and fully as severe, if not more so.
My blessed Master has again brought me through it for his all-wise purpose,
and has also enabled his very poor servant to glorify him in the furnace of suffering:
blessed be his adorable and excellent name!
Hast you not sometimes thought that dispensations of very sore affliction have at seasons
expanded the mind into a greater and deeper sense of our blessed Lord`'s great Love,
mercy, saving help and strength, than his multiplied favours?
As to myself, I ascribe this to my hard heart,
which perhaps is rendered more tender and soft by affliction, even severe,
than by favours.
This, therefore, enables me to understand the words, "`Rejoice in tribulation.`"
Truly I prove again that these are good for me, and I believe, my dear sister,
that your spirit responds to this; therefore, whatever the Lord gives, let us gather,
and accept as the food most proper for us.

9th mo., 28th.--If I continue to rally I may soon be able to go to meeting again.
As long as my dear Lord and Redeemer had any service
for me to perform among the nations of the earth,
for his blessed cause of righteousness and truth, he made way for his poor instrument,
where and to whomsoever he sent him, upheld the outward man amidst many difficulties,
privations and perils, and gave also by his good Spirit ability to preach his Gospel,
and to proclaim his love and mercy to the people.
The work was then to do his will; now my work is to suffer his will;
and in both services, I believe, he is equally to be glorified.

Dear friend, let us then be patient and resigned to our allotment, even to the end,
whichever way the Lord be pleased to call us to glorify him.
He taught some of us from the early days of our youth:
by his Divine grace and good Spirit he has enabled us to
an advanced period of life to declare of his wondrous works,
even of the salvation of sinners by his redeeming love and power: now,
when old and grey-headed, and that our strength fails, let us persevere, yea,
increase with fervency in the spirit of prayer,
which we have always known to be a precious covering when availing ourselves of it.
Let us say under its influence, "`Now also when I am old forsake me not,
till I have shown your power to this generation,
and your strength to every one that is to come,`" even your strength and power to keep
and sustain amidst the accumulated difficulties and sufferings attending old age,
bodily infirmities, and above all, the distresses and sufferings that attend the Church.
Under all, the Lord is a refuge, and a very present help in trouble.

My Lord and Master, through adorable mercy,
gives me at seasons joyfully to receive the dispensations, to kiss the rod,
and the disposer of it; and, still further,
at seasons to see how that which appears to be as a trying
storm to my frail bark in a tempestuous sea of trouble,
hastens it, nevertheless, nearer and nearer to the peaceful harbour.

Those whom we knew when here in this world as cross-bearers,
were very lovely and pleasant to our eye:
how much more lovely in our very finite vision do we behold them now that they are crown-wearers!

12th mo., 14th.--My general health is better,
so that of late I have had the privilege to attend
several times our meetings for Divine worship:
when prevented from so doing Divine mercy, as you are often a witness,
frequently condescends to reveal himself,
as being very near to the soul that pants for him, to refresh, comfort,
and strengthen him.
But, sometimes,
it would seem that there is a greater measure of
these blessings felt when the many are gathered together,
waiting, praying, and worshipping harmoniously under the influence of the same Spirit:
for then the many, being but one body,
may become partakers of the fulness of the blessings
that flow from the fountain to the whole body.

Very affecting are the fears of another famine in Ireland.
Surely the Lord`'s judgments are in various parts of the earth.
Church, States and people in the United States,
who by the Mexican war and the abominations of slavery,
contribute so largely to increase the general mass of human misery,
cannot expect to escape their day of retribution from the Lord.

1st mo., 14th, 1848.--This last year, like some of the preceding ones,
was marked by some pretty deep sufferings and conflicts of flesh and spirit;
yet in the end of it I see it crowned in such a manner with goodness, mercy and truth,
that I must inscribe on the memorial of it these true testimonies of gratitude and praise,
"`Hitherto has the Lord helped me,`" and "`Mercy
and truth have followed me all the days of my life.`"
O! that I may properly bless and adore His holy name!

After alluding to the things that were happening, as cause of much Christian solicitude:

2nd mo., 26th.--I must commit such fears as these, and many others,
which sometimes would dismay my fearful mind,
to the over-ruling power of Him who sits upon the floods and stills the raging waves.
He commands the winds and the sea, and they obey him.
I have been instructed sometimes by beholding a violent storm, with torrents of rain,
threatening much damage,
but whose effects have been to quench the violence of a devouring fire.
Thus the Lord can over-rule evil for good: have we not seen something of this?
Thus amidst fearful apprehensions, my fears are arrested by the solemn charge,
"`Be still, and know that I am God.`"
What a calm to the tossed mind the conviction of this brings!
Then is the wise conclusion come to, "`I will trust, and not be afraid.`"

3rd mo., 14th.--How industrious both you and your dear R. D. A. are,
each of you working in a separate field, but both prompted by the same impulse,
love to God and man,--yourself by your nice selections,
which my wife with me can testify are tending often to our instruction,
edification and comfort,
so that our hearts and lips often say that we are much your indebted friends!
And your dear husband is rendering many rough places
smooth,--opening the way for sobriety in many,
which leads to watchfulness and prayer, and brings to Christ.

5th mo., 3rd, 1848.--A very deep feeling is over me respecting the nations of Europe,
etc.;--therefore I feel it very needful to stand in my ward and watch the whole night.
I feel great unity with our dear friends, John and Martha Yeardley,
under their religious concern for several parts of your continent.
The unsettled and war-like aspect of these nations
renders such a prospect of service very formidable.
Under like circumstances in Germany my great Master made way for me,
his very poor servant: so he may for these our beloved friends.

Susan Howland, of New Bedford,
has the full unity and certificates of her Monthly and Quarterly Meetings,
to pay you a visit in Gospel love: she is a friend beloved; of a meek spirit.

7th mo., 21st.--I wish to become like a child, weaned from every outward consolation;
so that truly all my springs may be of the Lord.

On recovering from another attack of illness.

10th mo.,
12th.--How long I may be allowed the privilege to
attend meeting again is known to my dear Master alone.
I can ever confide in Him.
He has been with me all my life long.
He has been my help and strength in all my difficulties, even the greatest.
In my last illness he has again extended his mercy
and his upholding hand to his poor servant,
even so as to render the voice of thanksgiving louder than that
which excruciating sufferings in the flesh could not repress.
When considering what a poor, feeble, infirm creature I am now,
able to do next to nothing for my beloved Lord`'s cause, which, however,
is as dear to me as ever, I am prompted to query,
why am I left to remain a useless worm on the earth?
But I feel a check for indulging in such language, for He who has first given me a being,
knows also why I am continued here.
He has created us worms of the earth, that we should glorify him;
and is it not for the same purpose that he continues
us in being He renders such witnesses of his glory,
of his power, and of his mercy; and he calls and enables such to glorify him also,
glorify him in the fire, glorify him in sufferings, in life and in death.
Whatsoever be our passage out of time, may the Lord be glorified in it!

2nd mo., 28th,
1849.--How very sweet and encouraging is the account
you give of the last days of dear John Bell.
It is very precious to contemplate how the Lord is, time after time,
making additions to his glorious Church,
swelling the multitude of the spirits of just men made perfect.
Your dear husband`'s father, my beloved and honoured friend in the Lord, Dykes Alexander,
soon, I trust, will be among that glorious company, if he has not already joined them.
I heard this morning of the death of John Warren;
probably you will remember him when in your land;
he was a pillar in the Church of Christ,
and has only gone out of the militant to enter into the triumphant one.
The message of love of your dear father Alexander, as his last legacy,
is very precious to me; your dear Richard will not have any cause to mourn,
but rather to rejoice.
The event can but come close to your aunt Alexander,
but into the same blessed mansion she will probably soon follow.
"`Blessed are the dead who die in the Lord.`"
Truly we may respond Amen and Amen!

As my outward powers are declining,
my desires to the Lord are frequent that he would more and more quicken my spiritual,
open my eyes that I may see wondrous things out of his law,
and my ears that I may be more quick in hearing the language of the Spirit;
and especially that he would open my heart to love him more and more.
Many are the calls and strong the obligations to love him; this one alone is very great,
"`He loved us before we loved him.`"
The consideration of this one proof alone of his
great love and mercy covers me with shame and confusion,
seeing what coldness has often covered my heart:
witness the many instances when a faithful obedience
to his Divine commandments has not been adhered to.
Now after many years of religious profession,
and that the time of my departure hence is near at hand,
I have to make the confession that I have no works of righteousness to trust to,
no desert, no merit, but on my Lord`'s mercy only,
and on the continued extension of that same grace and love which
he extended to me before I knew him and consequently loved him,
I depend.
Surely it is with an everlasting love that he has loved me.

About this time Stephen Grellet was laid by for more than two months, by a fresh attack.
On reappearing among his friends at their meetings
for worship,--his ministry was very striking,
and very near access appeared to be granted to the throne of grace, when he was enabled,
in the Redeemer`'s name, to "`make vocal the needs of many,
in fervent prayer and supplication.`"
His words are spoken of by one who was privileged to hear them,
as being in "`the demonstration of the Spirit, and of power.`"

The freshness of his interest in what was passing is evinced
in his continued correspondence with A. A.

9th mo., 5th, 1849.--The tidings of Indiana Yearly meeting,
so far as we have heard are of a very satisfactory nature.
There is an increase of weight and vital religion in that very large Yearly Meeting;
seals to the labour of love of our beloved friends^
footnote:[Josiah Forster, William Forster, George Stacey, and John Allen.]
(the deputation of your Yearly Meeting to that) continue to be given:
many that had gone out in the separation that led to the visit of your dear messengers,
have returned to the bosom of Society.

In reference to the decease of Thomas Maw he adds:

I feel much for your cousin, Lucy Maw.
The bereavement is severe,
yet she has much to comfort her in the conviction
that the cause of her grief is one of joy unspeakable,
as I believe, to the dear departed.
He was, during some weeks,
my very acceptable and feeling companion during our religious engagements in your land,
and was rendered very dear to me.
The manner of his departure and the attending circumstances are, I think,
calculated to minister gratitude-he did not see death.
When convenient, please to give my love and Christian sympathy to dear L. M.

10th mo.,
2nd.--Your addition to your former letter of the
latter days of your valued and honourable aunt,
Ann Alexander, is truly interesting.
She lived near the Lord, in the faith of him, and she has died in him.
I feel very near sympathy for her only surviving sister, dear M. Hipsley.
It is rare to number so many sisters that have, in the same family,
lived so near the Truth,
and been such dignified instruments in honouring and exalting it,
as has been the case in the family of the Tukes.
Dear Mabel was the last of the sisters on whom the anointing oil was poured forth,
and will be the last also in glorifying the Lord by her death,
as she also does in her life.
Thinking of her and of her valuable partner sweetly reminds me of Zacharias and Elizabeth,
who both walked "`blameless before God.`"
My warm Christian love flows towards them.

To George Stacey

Burlington, 12th mo., 24th, 1849.

There is a spiritual fellowship which may have, yea I know has a free course,
whatever outward interruptions may occur.
I think I have some sensible experience of this;
for of late my health has allowed me to write but very little to much beloved friends,
even those who, though I have remained long silent towards them,
have nevertheless continued by their letters to contribute greatly to my comfort;
among these is our dear Josiah Forster.
He has a long, wintry journey in Germany with his valuable brother William,
and their companions.
I hope they will not suffer by it; they are, as we believe, in the service of the Lord,
and of his Truth; to his Divine care we may safely commit and resign them.
How very precious to have our minds established in this important truth,
"`You will keep him in perfect peace whose mind is stayed on you,
because he trusts in you!`"
Having for so long a time been tottering by the side of the grave,
I might be thought to be by this time so accustomed
to the contemplation as not to be moved by it:
it is not so.
The awfulness of appearing before spotless purity,
the vivid sense of my great unworthiness,
the deep conviction of my sins and transgressions often plunge the mind into many fears.
But O, what compassion also,
what merciful condescension of a blessed Saviour and gracious Redeemer,
to proclaim sometimes to his poor, sinking servants the language,
"`Fear not for I am with you, be not dismayed for I am your God; I will help you, etc.`"

How then, in our fears, should we not trust such a blessed Saviour?

Your poor friend has said enough about himself,
but he could never say enough to convey even a small part
of the great mercy and compassion of his adorable Redeemer,
who renders the days of his extremities seasons when saving help and strength are multiplied.

Most probably the account of the death of our dear friend, Anna A. Jenkins,
has come to your knowledge, and of the awfulness of it,
together with that of her eldest daughter, Sarah.
She appeared for a length of time preparing and prepared
for such a speedy release from this mortal tabernacle;
her conversation appeared to be in heaven.
The last meeting she attended was on First-day,
one day only previous to the flames consuming herself and daughter.
It was at Cranston, the meeting where she first spoke as a minister;
after having been engaged in her ministerial gift,
she stood up again and in a very solemn manner spoke of death,
saying that there were one or two present whose days, yea, hours, were numbered,
her daughter, Sarah, being present.
How soon was this realized!
My sister Smith, who was on a visit to her daughter Howland,
was with A. Jenkins shortly before the solemn event,
and was struck with the peculiar seriousness and solemnity that covered them;
she expected to have been again with her,
and was only prevented from going to Providence by a heavy storm,
else she would have been in the house the very night of the fire.

My dear wife and daughter have not been able to be out for some weeks;
Rachel is now nicely, but her beloved mother is very poorly.
What else can we look for at our time of life?
We have also many favours and blessings to enumerate.

My wife and daughter request that their love, together with mine,
be given to your beloved wife, also to yourself, for whom they retain a warm affection,
as does also your closely attached friend,

Stephen Grellet.

To resume the extracts from letters to Ann Alexander:

4th mo., 26th, 1850.--Our Christian love and fellowship is sweet and stable,
because it is founded in the Truth, where no change is.
There is another medium whereby I am permitted, at times,
to feel sweet communion with you, my beloved sister; it is in the Spirit;
very near to my best life I thus feel you;
sometimes in it I joy in your joys and mix in your sorrows,
for I know you hast not yet escaped to those glorious
mansions where sorrows have ceased forever;
yet I can bid you good speed in your journey towards it.
Amidst trials and discouragements that attend in the way,
much help is received by the poor and often weary pilgrim,
by keeping his eye fixed towards the dear Saviour.

5th mo., 31st.--Our beloved H. C. Backhouse is now admitted, we doubt not,
into the everlasting habitations; her loss to many here and to the church is great,
but to her the change is exceedingly glorious.

On recovering from a renewed attack of his complaint:

9th mo.,
6th.--Once more I am risen again from what threatened to be my last earthly conflict-risen
to be again a witness that the Lord is verily a God near at hand in troubles and sufferings-yea,
my beloved sister, to understand a little with yourself, the meaning of that Scripture,
"`Glorify the name of the Lord in the fire.`"
O that I may more abundantly glorify him in all my afflictions,
in every part of the short residue of my life, and in my death; and,
through the unmerited mercies of a gracious Redeemer,
be made ready to glorify him during eternity.

1st mo., 30th, 1851.--Do you not see with us, (alluding to his wife) how,
under the disguise of affliction,
a gracious and almighty Father deals with us very manifestly?
During many years of our life we were much separated one from the other.
I was even far off in distant nations: but now, in our advancing years, we are permitted,
by the same all merciful One to be kept very near to one another,
our beloved daughter most kindly and affectionately ministering to us both:
without her I do not know what we should do;
but it is the Lord who thus provides for us in this particular, and in everything else;
so that we are all witnesses of this so very precious scripture,
"`He that spared not his own Son, but delivered him up for us all,
how shall he not also with him, freely give us all things.`"
Must we not gratefully acknowledge that we receive from
his Divine hand from above what we could not ask or think,
yea, blessings innumerable: temporal and spiritual.
"`All things`"--very comprehensive words!
In these things, can we not sometimes trace,
what at other times we denominate afflictions?
My heart of late has overflowed with wonder, admiration and gratitude,
under the contemplation of this all important, interesting truth,
herein indeed is God`'s love manifested towards poor, lost,
sinful man,--"`He spared not his own Son, but gave him up for us all!`"
And this is a sure pledge of what, in the continuance of the same love and mercy,
he is disposed to do for us in time and eternity.
Dear friend, let us come boldly unto him with all our needs and infirmities.
In Him are all our springs.

On the expected opening of the Crystal Palace in London, he writes:

The congregation of so many persons from so many
nations that are expected to be then in London,
has brought me into very serious and solemn consideration, and perhaps you will,
and may indeed smile, when I tell you that I, poor I, like an old worn out race-horse,
which on hearing the sound of the horn or trumpet, is all animation, ready to start,
so your poor, old,
feeble friend has felt so much of the love of Christ
and his Gospel towards such an expected multitude,
that he thought, should the command be given, there would be a willingness to try,
at least, to limp or creep, though not to run as formerly.

9th mo.,
17th.--The account of the great bereavement that my truly loved and Christian friend,
Dr. Steinkopff has sustained by the decease of his valuable wife,
greatly excites my near sympathy for him.
She was a good helpmeet to him; her Christian, meek, quiet,
and humble spirit seemed to keep pace with the doctrine
that dear Steinkopff has been preaching these many years.
He had in her a treasure on earth: this treasure is now transported into heaven,
where he is, I trust, favoured to visit it even now with great consolation;
and as they were in great measure but one spirit on earth, they shall be one in heaven,
thus realizing the prayer of our blessed Lord and Redeemer,
"`that they also may be one in us.`"
A little while, and dear Steinkopff will, I trust,
realize this blessed promise in its fulness.
One with Christ! what a glorious hope!
One with those that have believed in Him and loved Him; what joy!
What encouragement also for us patiently to wait
and quietly to hope for the salvation of God!
Give my love to him,
and tell him that the nearness of spirit and fellowship I had with him,
when I was personally with him, is not interrupted by long absence from one another.

Speaking of afflictions and sufferings, after recovering from a severe illness, he adds:

I have compared them to a rough diamond,--very rough and unsightly in appearance,--nothing
in it appears desirable:--but remove some of the crust from that rough stone,
and then what a bright gem is discovered!
So, when, through the eye of faith,
we are enabled to see into the sufferings allotted to us, what a glory is unfolded!
Yes, we behold how these afflicting dispensations work for us
a far more exceeding and eternal weight of glory!
Then, in this very particular of our beloved Lord`'s dispensations,
we see what grateful cause we have to break out joyfully with David and say,
"`Bless the Lord, O my soul,
and all that is within me bless him for all his benefits:`" for we see,
we feel all these to have been to our benefit, and to bring a blessing with them.

12th mo., 19th, 1851.--I am under the necessity to abstain from reading writing,
and even print, unless it be large, which is a great privation.
I have, however, the Scriptures in large print,
which are my welcome and constant companion.
Should I be permitted to become deprived of this privilege also,
may not my good and blessed Lord be pleased to bring to my remembrance, as need may be,
portions of them suitable to my condition?
We may well trust in Him, who can abundantly supply all our needs.
He has to this day done so for me, his poor and unworthy servant,
temporally and spiritually; and his promise,
"`I will never leave you nor forsake you,`" is worthy of our full faith and confidence.
Think on it, my dear friend, when you are ready to sink under discouragement,
even ready to conclude that your Lord has forgotten or forsaken you.
Cordelia Bayes is in Philadelphia.
She was at our Quarterly Meeting, visited all the meetings that comprise it,
and the families of Mount Holly, a branch of our Monthly Meeting.
She tries to keep very near her guide, is very watchful in her movements,
and guarded in her conversation.

A few weeks ago we had here Lindley Murray Hoag,
on his return from North Carolina Yearly Meeting.
He gave a good account of our aged patriarch, Nathan Hunt, where he had been two nights,
and much enjoyed the company of this valuable aged servant of the Lord.

A painful inflammation of the eyes had almost deprived him of the power of using the pen,
and when nearly blind he writes:

1st mo., 13th, 1852.--For the first time I attempt to write,
though I am not able to read my own writing, and possibly you may not be able to do it,
but my good-will will be manifested,
and you will make every allowance for a brother`'s infirmities.
I know not what will be the result with regard to my sight; the dimness,
independent of the inflammation, continues or increases,
but no apparent defect in the eyes is yet observable;
perhaps it is only an attendant m the feebleness of the whole of my outward man.
Thanks, however, to the Lord, I am still able to see the excellency of the Truth,
and to love and adore my blessed and glorious Lord and Redeemer;
also I am able to join my friends in publicly worshipping him,
and sometimes also with the voice of thanksgiving and praise to proclaim his name,
and rehearse his praise and his works.

In these extracts a few gleanings only from a rich field where, had there been room,
much more might have been gathered, but embracing a period of several years,
till he was near fourscore, Stephen Grellet may be said still to be his own biographer,
and there cannot well be a nobler sight than a Christian patriarch
"`having served his generation by the will of God,`" thus enabled
to show how he was strengthened to "`hold fast the confidence,
and the rejoicing of the hope firm unto the end,`"
giving all the glory to Him to whom alone it is due.
